dvc.conf
dvc/command/data_sync.py
dvc/command/init.py
dvc/command/test.py
dvc/config.py
dvc/runtime.py
requirements.txt
tests/test_config.py

aws creds: look for path in dvc.conf, or look at ~/.aws/credentials

config modifications

---

build.cmd
innosetup/modpath.iss
innosetup/setup.iss

It uses nuitka to convert dvc.py into standalone dvc.exe and then
uses Inno Setup script to create an installer.

build: add builder for windows

---

innosetup/addsymlink.iss

build: add popup msgs about CreateSymLinkPrivilege

---

build.cmd
innosetup/config_gen.py
innosetup/setup.iss

1) Automatically update installer version by using dvc.main.VERSION
2) Make build.cmd more verbose and handle errors better

build: improve windows installer

---

dvc/command/base.py
dvc/command/data_sync.py
dvc/command/import_file.py
dvc/data_cloud.py
dvc/progress.py
dvc/utils.py

Progress bar improvements, --jobs and progress bar for LOCAL cloud and AWS

---

dvc/data_cloud.py

aws: don't forget to finish_target() after sync is done

---

dvc/data_cloud.py

aws: typo fixup for #105

---

dvc/data_cloud.py

This is a partial solution to #110 
as it solves the case where the local file gets corrupted by a partial download
(other cases of corruption can still be an issue)

download file to temp file, and rename only if success

---

appveyor.yml

appveyor: add windows build

---

README.md

Add appveyor icon to README

---

.appveyor.yml

appveyor: rename yml and add 'branches'

---

dvc/cli.py

cli: set dvc prog name to 'dvc'

---

dvc/command/init.py
dvc/command/test.py
requirements.txt
setup.py

dvc: get rid of pathlib

---

dvc/git_wrapper.py

Making sure git is configured at least with name and email,
so our commits can be commited without any problems.
Fixes #64.

init: check user.{name,email} to make sure git is ready

---

tests/test_utils.py

Some sanity tests to make sure something like #132
doesn't happen anymore.
Fixes #132.

tests: add test for utils.py

---

dvc/command/gc.py
dvc/command/remove.py
dvc/command/traverse.py

codeclimate noted a few similiar code chunks and it looks
like it is worth fixing them.

RFC: fix codeclimate warnings

---

build_macos.sh

build: cleanup build_macos.sh

---

dvc/cli.py

This looks and sounds much better.
Fixes #156 

cli: replace "dvc instance-create" with "dvc cloud create"

---

dvc/data_cloud.py

currently, an exception was thrown if the file was missing.

return empty md5 if file doesnt exist

---

dvc/data_cloud.py

aws: use multipart to push changes

---

dvc/data_cloud.py

Reverts dataversioncontrol/dvc#178

Revert "aws: use multipart to push changes"

---

dvc/data_cloud.py

cloud: fix typo

---

dvc/data_cloud.py

aws: use multipart to push changes, v2

---

dvc/data_cloud.py

aws: fix progress and chunk size for multipart upload

---

.travis.yml
functest/test-import.sh
functest/test-sync-aws.sh

travis: enable aws tests

---

dvc/data_cloud.py

aws: resume download/upload

---

dvc/command/data_sync.py
dvc/main.py
dvc/utils.py

Misc enhancements 

---

dvc/command/data_sync.py
dvc/main.py

These wasn't caught in pull-request as it doesn't
have secure env vars to test sync/pull/push/status.

build: fix errors on python3

---

dvc/data_cloud.py
functest/test-repro-code.sh
functest/test-sync-aws.sh
tests/test_workflow.py

pull: create dirs before pulling

---

dvc/cli.py
dvc/command/show_workflow.py
dvc/graph/commit.py
dvc/graph/workflow.py
requirements.txt
tests/test_workflow.py

Show target metrics deltas only in workflow graph

---

dvc/command/repro.py
dvc/command/show_workflow.py
functest/test-repro-code.sh

target: fix bugs and add repro test

---

dvc/git_wrapper.py

workflow: extract float before converting

---

dvc/__init__.py
dvc/cli.py
dvc/command/base.py
dvc/command/config.py
dvc/command/import_file.py
dvc/command/repro.py
dvc/config.py
dvc/data_cloud.py
dvc/executor.py
dvc/git_wrapper.py
dvc/settings.py
dvc/utils.py

RFC: find and fix errors and some warning reported by pylint

---

dvc/cli.py
dvc/command/import_file.py
dvc/command/init.py
dvc/command/lock.py
dvc/command/repro.py
dvc/command/run.py
dvc/command/show_pipeline.py
dvc/command/show_workflow.py
dvc/git_wrapper.py
dvc/graph/commit.py
dvc/graph/workflow.py
dvc/state_file.py
functest/tutorial_branches.sh
tests/test_workflow.py

It is much better to have the metrics in DAG and Git repository then in clouds or local disks.

Extract target metric to state files

---

dvc/command/repro.py
dvc/command/run.py
dvc/git_wrapper.py
dvc/state_file.py

git: save and use target commit in state files

---

dvc/command/repro.py
dvc/command/run.py
dvc/state_file.py

This reverts commit 3ec49f56efe1040c5fb03fb9074387e1ca280114.
Didn't solve the issue, need to research a bit more.

Revert "run: save target commit in state files"

---

dvc/cli.py
dvc/command/data_sync.py

Kudos to @gvyshnya for reporting these.

Misc cli bug fixes

---

dvc/command/import_file.py
dvc/command/init.py
dvc/command/run.py
dvc/data_cloud.py
dvc/executor.py
dvc/git_wrapper.py
dvc/path/data_item.py
dvc/state_file.py
tests/basic_env.py
tests/test_data_file_obj.py

Use md5 checksum instead of commit-ids for cache files

---

dvc/cli.py
dvc/command/merge.py
dvc/git_wrapper.py

dvc: add 'merge' command

---

dvc/command/repro.py

Ignore state file changes for data sources
…. Close #266

dvc-repro after dvc-merge

---

.travis.yml

travis: manually specify macos image

---

dvc/cli.py
dvc/command/add.py
dvc/command/checkout.py
dvc/command/gc.py
dvc/command/merge.py
dvc/command/repro.py
dvc/command/run.py
dvc/path/data_item.py
dvc/path/factory.py
dvc/state_file.py
dvc/utils.py
functest/test-repro-code.sh

This is very ugly code-wise, but stabilizes our state(stage) file concept and format. Expect RFC and optimization patches coming soon.

State(stage) files design changes

---

dvc/state_file.py

state: don't create dirs for local state

---

dvc/cli.py
dvc/command/repro.py
dvc/command/run.py
dvc/git_wrapper.py
dvc/path/factory.py
dvc/settings.py
dvc/state_file.py
functest/test-merge.sh
functest/test-repro-code.sh

Misc stage-file features

---

dvc/project.py
dvc/stage.py

repro: don't forget to update stage files after reproduction

---

appveyor.yml
dvc/stage.py
dvc/system.py
dvc/utils.py
requirements.txt
setup.py
tests/basic_env.py
tests/test_checkout.py

win: fix windows build and enable unit tests

---

dvc/cache.py
dvc/project.py
dvc/stage.py
dvc/state.py
dvc/system.py

dvc: cleanup artifacts from #382

---

functest/common.sh

functest: use uuid for s3 test

---

dvc/cli.py
dvc/command/fsck.py
dvc/project.py
dvc/stage.py

Note, now `fsck` outputs only files with conflicts. It can output everything by `--all` option.

Bugfixes and fsck refactoring

---

dvc/command/fsck.py
dvc/project.py
dvc/stage.py

Removes unnecessary 'cache=False' in deps list in stage file. Properly resolves defaults in hand written stage files.

stage: fix defaults and RFC classes

---

dvc/cloud/credentials_aws.py
dvc/cloud/instance_manager.py
dvc/data_cloud.py
tests/test_data_cloud.py

cloud: fixup for #404

---

dvc/data_cloud.py
dvc/project.py
tests/__init__.py
tests/test_add.py
tests/test_cmd_lock.py
tests/test_data_cloud.py
tests/test_gc.py
tests/test_init.py
tests/test_remove.py
tests/test_repro.py
tests/test_run.py

test: improve test coverage

---

.appveyor.yml
dvc/command/common/base.py
dvc/command/show_pipeline.py
dvc/main.py
requirements.txt
setup.py
tests/test_checkout.py
tests/test_show_pipeline.py
tests/test_workflow.py

test: improve coverage and fix bugs

---

dvc/command/show_workflow.py
dvc/data_cloud.py
dvc/graph/workflow.py
scripts/ci/after_script.sh
scripts/ci/before_deploy.sh
scripts/ci/before_install.sh
scripts/ci/before_script.sh
scripts/ci/install.sh
scripts/ci/script.sh

travis: fixups

---

scripts/ci/install.sh

travis: osx: don't forget to install graphviz

---

dvc/command/common/base.py
dvc/project.py
dvc/stage.py
tests/test_repro.py

dvc: fix repro bugs

---

dvc/executor.py
dvc/stage.py
tests/test_add.py
tests/test_checkout.py
tests/test_gc.py
tests/test_remove.py
tests/test_repro.py

Missing data source error message

---

dvc/logger.py
dvc/main.py

logger: init before using on early stages

---

dvc/stage.py
dvc/state.py
tests/test_state.py

state: don't forget to track inode

---

tests/test_data_cloud.py

test: test gcp only when env var DVC_TEST_GCP=true

---

dvc/stage.py
tests/test_checkout.py

dvc: don't add regular files to gitignore

---

dvc/output.py
dvc/project.py
dvc/stage.py

dvc: use relative paths in exceptions

---

dvc/output.py

output: check if dir exists before creating it

---

tests/test_repro.py

test: use swap_code function

---

.appveyor.yml
tests/test_data_cloud.py

test: test AWS on appveyor

---

.appveyor.yml
tests/test_data_cloud.py

Reverts dataversioncontrol/dvc#463

Revert "test: test AWS on appveyor"

---

.appveyor.yml

appveyor: setup aws creds

---

.appveyor.yml

appveyor: fix env vars

---

dvc/output.py
dvc/stage.py

output: don't forget to check inode when using cached state for changed() method

---

dvc/cli.py
dvc/cloud/data_cloud.py
dvc/command/data_sync.py
dvc/project.py
dvc/utils.py
tests/test_utils.py

This reverts commit 61b469144e5c893aa892f820a39aadeba325e3de.
It was poorly thought out.

Revert "cloud: process targets one-by-one"

---

scripts/hooks/hook-checksumdir.py

pyinstaller: add hook for checksumdir module

---

docs/doc.rst

doc: fix typos and add corrections

---

dvc/output.py
tests/test_repro.py

dvc: properly check dir

---

dvc/cache.py
dvc/cloud/base.py
dvc/cloud/data_cloud.py
dvc/cloud/instance_manager.py
dvc/cloud/local.py
dvc/project.py
tests/test_cache.py
tests/test_data_cloud.py
tests/test_fsck.py
tests/test_gc.py

dvc: use two-level hash for cache

---

tests/test_data_cloud.py

test: fix data cloud test

---

dvc/cloud/aws.py
dvc/cloud/base.py
dvc/cloud/data_cloud.py
dvc/cloud/gcp.py
tests/test_data_cloud.py

dvc: cloud: reuse connections when processing targets

---

dvc/cache.py

cache: fix upper limit for sub dirs

---

dvc/output.py

checkout: use is_dir_cache

---

dvc/command/checkout.py

checkout: don't forget to set perms back

---

dvc/command/data_sync.py

status: print paths relative to cache dir

---

dvc/output.py

repro: don't fail if dir cache is not present

---

dvc/command/checkout.py

Speeds up checkout for 30K files from 6sec to 3.5sec

checkout: optimize lost hardlink search

---

dvc/cache.py
dvc/output.py
dvc/state.py
tests/test_checkout.py
tests/test_state.py

cache: check for cache corruption

---

tests/test_checkout.py

tests: add debug msg

---

tests/test_checkout.py

test: add debug msgs for mtime issue

---

dvc/output.py
dvc/state.py
requirements.txt
scripts/ci/install.sh
setup.py
tests/test_checkout.py
tests/test_state.py

State and travis fixes

---

tests/test_checkout.py

tests: checkout: sleep(1) to emulate realistic behavior

---

dvc/command/data_sync.py
tests/test_cache.py
tests/test_data_cloud.py

Combined coverage reports from linux and windows myself.

increase test coverage to 90%

---

dvc/cloud/credentials_aws.py
dvc/config.py

aws: rename CredentialSection to Profile

---

.appveyor.yml
dvc/project.py
tests/test_repro.py

repro: fix --force option

---

dvc/output.py
dvc/project.py
dvc/stage.py

Misc fixes

---

dvc/output.py

output: remove: remove unused code

---

dvc/output.py

dvc: output: use shutil.rmtree

---

dvc/state.py

dvc: state: don't forget to load db

---

dvc/state.py
requirements.txt
setup.py

state: use str representations for inode and mtime

---

tests/test_state.py

test: add test for state reload consistency

---

requirements.txt
setup.py

dvc: add pyasn1 to requirements

---

dvc/scm.py

scm: dynamically import gitpython

---

scripts/build_windows.cmd

build: win: don't look for symlink ps script

---

dvc/output.py
dvc/project.py
tests/test_checkout.py
tests/test_repro.py

dvc: fix checkout/repro with stage files without md5

---

dvc/output.py

checkout: don't print 'cache not found' if cache is None

---

dvc/stage.py

stage: set default values for fields from stage files

---

.appveyor.yml
scripts/ci/script.sh
test-requirements.txt

coverage: try using codecov

---

.appveyor.yml

appveyor: don't call codecov for pull requests

---

dvc/__init__.py

dvc: dynamic version

---

docs/doc.rst

doc: remove show-pipeline section

---

dvc/__init__.py
dvc/cloud/base.py

dvc: cloud: cache_file_key: don't forget to assign to relpath

---

dvc/output.py

dvc: convert paths to POSIX when reading and writing stage files

---

dvc/cli.py
dvc/cloud/aws.py
dvc/cloud/base.py
dvc/cloud/credentials_aws.py
dvc/cloud/data_cloud.py
dvc/cloud/gcp.py
dvc/command/common/base.py
dvc/command/config.py
dvc/command/data_sync.py
dvc/command/remote.py
dvc/command/status.py
dvc/config.py
dvc/exceptions.py
dvc/logger.py
dvc/project.py
tests/test_config.py
tests/test_data_cloud.py

Fixes #606 
Fixes #605 
Fixes #604 
Fixes #596

config: Introduce 'remotes' instead of 'cloud's

---

dvc/stage.py

dvc: stage: don't write None and empty lists

---

tests/test_data_cloud.py

tests: data cloud: limit jobs to 2

---

scripts/ci/script.sh
tests/test_data_cloud.py

tests: cloud: fix naming scheme

---

dvc/state.py

state: handle non-existing path

---

tests/test_data_cloud.py

This will help simulate realistic behaviour on filesystems with poor mtime resolution.

tests: sleep(1) before modifying data files

---

setup.py

setup.py: don't mixup download_url and url

---

dvc/cloud/aws.py

aws: use profile setting

---

dvc/progress.py
dvc/utils.py

progress: don't print new line

---

dvc/cli.py
dvc/command/init.py
dvc/command/metrics.py
dvc/project.py
dvc/scm.py
tests/test_init.py

init: properly handle `dvc init` in directory without scm

---

dvc/command/repro.py

repro: print user-friendly error

---

dvc/cli.py
dvc/command/metrics.py
dvc/project.py
dvc/scm.py
requirements.txt
setup.py
tests/test_metrics.py

dvc: add `dvc metrics`

---

dvc/project.py
tests/test_metrics.py

metrics: don't forget to checkout()

---

dvc/cli.py
dvc/command/install.py
dvc/project.py
dvc/scm.py
tests/__main__.py
tests/test_install.py

dvc: introduce `dvc install` for installing git hooks

---

dvc/cli.py
dvc/command/checkout.py
dvc/project.py
tests/test_checkout.py

dvc: checkout single file

---

dvc/cli.py
dvc/command/config.py
dvc/command/remote.py
dvc/config.py
dvc/main.py
tests/test_remote.py

dvc: introduce 'dvc remote list'

---

dvc/__init__.py
dvc/check_updates.py
dvc/project.py
requirements.txt
setup.py

dvc: check updates and warn about using an older version

---

dvc/scm.py

git: untracked_files: don't forget to join paths

---

dvc/cloud/base.py
dvc/cloud/data_cloud.py

cloud: use status to determine which targets to push/pull

---

dvc/project.py
tests/test_metrics.py

dvc: try to add to gitignore every time for backward compatibility

---

dvc/output.py
dvc/scm.py

dvc: print warning when file/dir is empty

---

dvc/utils.py

utils: file_md5: don't forget to decode data on python 2

---

dvc/output.py
dvc/project.py

dvc: reuse collected stages

---

.travis.yml

travis: osx: add --enable-framework for pyenv

---

requirements.txt

reqs: require PyInstaller 3.3.1

---

scripts/hooks/hook-google_compute_engine.py

pyinstaller: add google_compute_engine hook

---

dvc/project.py
tests/test_cache.py

dvc: add cache dir to gitignore only if it is not external

---

.gitignore
dvc/cli.py
dvc/command/repro.py
tests/test_repro.py

dvc: add --cwd for dvc repro

---

dvc/remote/local.py
tests/test_checkout.py

checkout: create dir even if it is empty

---

.travis.yml

travis: run docker image with hadoop

---

dvc/stage.py
tests/test_repro.py

stage: try to specify user's shell when running commands

---

dvc/stage.py

status: report callback stages as changed

---

dvc/cache.py
dvc/config.py
dvc/dependency/__init__.py
dvc/dependency/hdfs.py
dvc/output/__init__.py
dvc/output/hdfs.py
dvc/remote/__init__.py
dvc/remote/hdfs.py
tests/test_repro.py

dvc: initial hdfs support

---

dvc/cli.py
dvc/command/remove.py
dvc/project.py
tests/test_remove.py

remove: add `-o|--outs` and `-p|--purge` options

---

dvc/cli.py

cli: fix `dvc remote` bug on python3

---

dvc/utils.py
tests/test_utils.py

utils: read in binary mode when converting CRLF -> LF

---

dvc/dependency/base.py
dvc/dependency/local.py
dvc/output/local.py
dvc/remote/local.py
dvc/stage.py
tests/test_repro.py

dvc: support external local deps

---

dvc/output/gs.py
dvc/output/hdfs.py
dvc/output/s3.py

outputs: fix `remove` methods for s3/gs/hdfs

---

dvc/cli.py
dvc/command/imp.py
dvc/dependency/base.py
dvc/project.py
dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/hdfs.py
dvc/remote/local.py
dvc/remote/s3.py
dvc/stage.py
tests/test_repro.py

dvc introduce `dvc import`

---

dvc/cli.py
dvc/command/root.py

dvc: introduce `dvc root` command

---

dvc/dependency/base.py
dvc/dependency/local.py
dvc/project.py
tests/test_repro.py

dvc: support dependecy files under tracked directory

---

tests/test_metrics.py

test: enable CLI metrics test on windows

---

.appveyor.yml
tests/__main__.py

test: run tests in NCORES processes

---

dvc/system.py
tests/test_system.py

system: add temporary workaround for getdirinfo() issue

---

dvc/cli.py
dvc/project.py
dvc/scm.py

dvc: push/pull/fetch/gc for all branches

---

scripts/innosetup/dvc.ico.dvc
scripts/innosetup/dvc_left.bmp.dvc
scripts/innosetup/dvc_up.bmp.dvc

innosetup: use new images

---

dvc/cloud/data_cloud.py
dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/local.py
dvc/remote/s3.py
dvc/remote/ssh.py
tests/test_data_cloud.py

Misc changes to reorganize and improve cloud/remote drivers.

RFC: data_cloud and remotes

---

dvc/config.py
dvc/dependency/__init__.py
dvc/dependency/ssh.py
dvc/output/__init__.py
dvc/output/ssh.py
dvc/remote/ssh.py
tests/test_data_cloud.py
tests/test_repro.py

dvc: support ssh deps/outs/cache

---

.travis.yml
dvc/dependency/base.py
dvc/dependency/hdfs.py
dvc/dependency/ssh.py
dvc/remote/base.py
dvc/remote/hdfs.py
dvc/remote/ssh.py
tests/basic_env.py
tests/log.log
tests/test_repro.py

hdfs: fix drivers and tests

---

dvc/cli.py
dvc/command/move.py
dvc/dependency/local.py
dvc/output/local.py
dvc/project.py
dvc/remote/base.py
dvc/remote/local.py
tests/test_move.py

dvc: introduce `dvc move`

---

dvc/cli.py
dvc/command/lock.py
dvc/project.py
dvc/stage.py
tests/test_repro.py

dvc: bring back `dvc lock` with `dvc unlock`

---

dvc/remote/base.py

cloud: keep downloaded dir cache file

---

dvc/project.py

pull: checkout only specified target

---

dvc/remote/__init__.py
dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/s3.py
dvc/remote/ssh.py
setup.py

Optional dependencies for cache strategies

---

dvc/remote/local.py

Speeds up checkout for a directory with 1K files from ~20 sec to ~1.7 sec.
Fixes #758

checkout: don't dump link_state for every file

---

dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/s3.py
dvc/remote/ssh.py

remote: print which dependencies we are missing

---

tests/test_cache.py

test: two repositories one cache dir

---

dvc/config.py
dvc/remote/local.py

config: allow specifying a list of cache types

---

dvc/remote/local.py

checkout: print better msg when cache is missing

---

dvc/scm.py

scm: print error if GitPython bug raises

---

tests/test_data_cloud.py

test: enable ssh test on osx

---

dvc/remote/ssh.py

ssh: choose md5 command depending on the os

---

tests/test_repro.py

tests: try enable GS test on CI

---

.travis.yml
scripts/ci/before_install.sh
scripts/ci/core-site.xml
scripts/ci/hdfs-site.xml
scripts/ci/install_hadoop.sh
scripts/ci/script.sh
tests/test_data_cloud.py
tests/test_repro.py

travis: test hdfs

---

.travis.yml
tests/test_data_cloud.py
tests/test_repro.py

travis: run hdfs test only on Linux

---

.travis.yml

travis: osx: install google cloud sdk

---

tests/test_metrics.py
tests/test_updater.py

Misc tests

---

tests/test_updater.py

tests: add test_updater

---

.coveragerc

coverage: exclude 'pass' and 'NotImplementedError'

---

dvc/output/local.py
dvc/project.py
dvc/remote/local.py
dvc/state.py
tests/test_cache.py
tests/test_state.py

dvc: misc improvements

---

dvc/project.py

dvc: don't forget to add state and state.lock to gitignore

---

dvc/scm.py

brancher: don't checkout if no branches is specified

---

.dvc/.gitignore
dvc/updater.py

updater: don't forget to convert to int

---

dvc/project.py

metrics: show: don't print branch if all_branches=False

---

dvc/remote/azure.py
dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/hdfs.py
dvc/remote/local.py
dvc/remote/s3.py
dvc/remote/ssh.py

This is a follow-up change to https://github.com/iterative/dvc/pull/868 which flagged a few Code Climate inspections due to duplicate code.

Fix CodeClimate inspections

---

dvc/remote/azure.py
dvc/remote/s3.py

remote: add comments for s3/azure exists() method

---

dvc/remote/local.py

collect: skip if cache dir doesn't exist

---

dvc/utils.py

utils: copyfile: properly join paths

---

dvc/state.py

dvc: sort dir cache by relpath

---

dvc/remote/s3.py

remote: s3: properly delete key

---

tests/test_data_cloud.py

test: check if we need to test RemoteAzure with _should_test_azure

---

dvc/cli.py
dvc/command/pipeline.py
dvc/project.py
tests/test_pipeline.py

Example:
```
$ dvc pipeline show process/Dvcfile           
raw/Dvcfile
cleanup/Dvcfile
process/Dvcfile
```
```
$ dvc pipeline show process/Dvcfile --commands  
download.py s3://mybucket/myrawdata rawdata
cleanup.py rawdata data
process.py data output
```

add `dvc pipeline show`

---

dvc/cli.py
dvc/command/destroy.py
dvc/project.py

dvc: implement `dvc destroy`

---

dvc/command/run.py
dvc/project.py
dvc/stage.py
requirements.txt
setup.py
tests/test_run.py

dvc: support `dvc add` for external files

---

dvc/remote/s3.py

We have to specify `endpoint_url` option for S3 Session client along with Resource object.

Specify endpoint_url on S3 session client

---

dvc/dependency/base.py
dvc/remote/gs.py
dvc/remote/local.py
dvc/remote/s3.py

remote: misc bug fixes

---

dvc/cli.py
dvc/command/common/base.py
dvc/command/config.py
dvc/command/init.py
dvc/command/install.py
dvc/command/pipeline.py
dvc/command/repro.py
dvc/command/run.py
dvc/project.py
tests/test_cli.py
tests/test_data_cloud.py

dvc: optimize imports to speedup startup time

---

scripts/ci/install_hadoop.sh

travis: use openjdk

---

dvc/cli.py

cli: add -a alias for --all-branches

---

dvc/remote/s3.py

s3: don't forget to configure all Session/Client params

---

dvc/remote/s3.py

s3: don't use Object()

---

dvc/project.py

status: print locked warning only when stage is locked

---

dvc/remote/s3.py

s3: don't use Bucket()

---

dvc/exceptions.py
dvc/project.py
tests/test_metrics.py

metrics: properly handle explicitly specified file

---

dvc/cli.py
dvc/command/metrics.py
dvc/output/__init__.py
dvc/output/local.py
dvc/project.py
tests/test_metrics.py

metrics: specify xpath in stage files

---

dvc/command/destroy.py
dvc/remote/gs.py
dvc/scm.py

Fixes #946. Kudos @cclauss for discovering!

dvc: fix errors found by flake8

---

dvc/cli.py
dvc/command/data_sync.py
dvc/command/status.py
dvc/data_cloud.py
dvc/dependency/local.py
dvc/progress.py
dvc/project.py
dvc/remote/local.py
dvc/scm.py
tests/test_data_cloud.py

dvc: show filenames in `push/pull` output

---

dvc/remote/local.py

status: don't forget about missing cache

---

dvc/remote/azure.py
dvc/remote/local.py
dvc/utils.py

dvc: additional progress info

---

dvc/project.py
dvc/stage.py

run: ask for confirmation when overwriting stage file

---

dvc/cli.py

dvc: fix help output

---

dvc/cli.py

dvc: print help if CLI args are wrong

---

dvc/remote/local.py
dvc/scm.py
dvc/stage.py

dvc: print more info for add/run/checkout

---

dvc/remote/hdfs.py
dvc/stage.py
dvc/utils.py

dvc: fix LD_LIBRARY_PATH on binaries

---

dvc/scm.py
dvc/utils.py

scm: fix LD_LIBRARY_PATH if running from a bundle

---

setup.py

setup: use proper env marker for futures dependency

---

dvc/__init__.py

dvc: ignore unraleted numpy runtime warnings

---

README.rst

Hey guys, this is how Hall-of-fame will look like on your repo.  I spoke to @dmpetrov about this PR before making it.
Note: it currently uses my GitHub user (sergey48k) for GitHub API. This takes ~10-20 requests off my limit. Not a biggie, but in case you are wondering why my username is in your source code, it's the reason why. I could also switch to any of you, but the only qualified DVC contributor is @efiop because only he has Sourcerer account linked with a GitHub account.
Also, note. If you accept this pull request, I will become a 'new' contributor to DVC, so my face will likely be on one of the badges for a few days. If you don't want it (and I won't be offended, don't worry), don't accept this request, but just copy the changes, and make a new pull request.
I hope you like it. …

Added hall-of-fame to README

---

dvc/project.py
dvc/remote/azure.py
dvc/remote/gs.py
dvc/remote/hdfs.py
dvc/remote/local.py
dvc/remote/s3.py
dvc/remote/ssh.py

dvc: print a msg when there is no cache to remove

---

dvc/config.py
dvc/project.py

config: add core.interactive

---

scripts/ci/install.sh

travis: retry pip install

---

dvc/command/status.py

status: print msg if there is nothing to reproduce

---

dvc/cli.py
dvc/command/destroy.py

destroy: mention removing data files

---

dvc/cli.py

https://github.com/iterative/dvc.org/issues/71

help: add a better description for `dvc init -f`

---

dvc/cli.py
dvc/command/add.py
dvc/project.py
tests/test_add.py
tests/test_checkout.py
tests/test_data_cloud.py
tests/test_metrics.py
tests/test_remove.py
tests/test_repro.py

dvc: add --recursive

---

dvc/dagascii.py

dagascii: make vertical space smaller

---

dvc/logger.py

logger: use colored prefix instead of coloring everything

---

dvc/cli.py
dvc/logger.py

dvc: use our errors in the argparser

---

dvc/cli.py

dvc: print command specific help

---

dvc/command/pipeline.py
tests/test_pipeline.py

test: cover pipeline show --ascii

---

dvc/remote/s3.py

s3: properly configure session and clients

---

dvc/config.py
dvc/dependency/base.py
tests/test_repro.py

dependency: only use rel_path for local deps

---

dvc/cli.py
dvc/stage.py
tests/test_run.py

dvc: check stage filename

---

dvc/command/repro.py
dvc/command/status.py

repro: print a msg when pipeline is up to date

---

dvc/command/pipeline.py

pipeline: fix corner case

---

dvc/command/pipeline.py
tests/test_pipeline.py
tests/test_repro.py

test: cover `pipeline show`

---

dvc/state.py
tests/test_repro.py

dvc: properly compute mtime of the directory

---

dvc/cli.py
dvc/command/destroy.py
dvc/command/run.py
dvc/project.py
dvc/prompt.py
dvc/stage.py

run: add `-y|--yes` option to bypass prompts

---

dvc/command/remote.py
tests/test_remote.py

remote: properly remove remote section

---

dvc/state.py
tests/test_repro.py

state: don't forget subdirs when computing effective mtime

---

dvc/state.py

state: don't forget to lock before dumping db

---

dvc/remote/local.py
dvc/state.py

state: limit db size and add a file size limit

---

dvc/remote/ssh.py

ssh: don't recv() before checking with recv_ready()

---

dvc/project.py
dvc/scm.py

`dvc status` for directory with 100K files sped up from ~6 sec to ~2
sec.
Fixes #1121

dvc: don't scan output directories for dvc files

---

dvc/project.py
dvc/remote/local.py
dvc/state.py
tests/test_data_cloud.py
tests/test_state.py

state optimization

---

dvc/stage.py
tests/test_run.py

run: check that -f doesn't contain any subdirs

---

dvc/project.py
dvc/scm.py
dvc/stage.py

dvc: list changed files

---

dvc/config.py
dvc/progress.py
dvc/prompt.py
dvc/remote/local.py
dvc/remote/ssh.py

ssh: add 'password' and 'ask_password' options

---

dvc/cli.py
dvc/command/repro.py
dvc/project.py
tests/test_repro.py

repro: introduce -p|--pipeline option

---

dvc/remote/ssh.py

ssh: properly join chunks on python3

---

dvc/dependency/local.py
dvc/output/local.py

local: use is_local property

---

tests/test_checkout.py

test: don't forget to check return code

---

dvc/scm.py
tests/test_scm.py

scm: require abs path

---

dvc/cli.py
dvc/command/data_sync.py
dvc/command/status.py
dvc/project.py

dvc: introduce -d|--with-deps option

---

dvc/remote/local.py

dvc: properly join paths for push/pull progress bar

---

requirements.txt
setup.py

requirements: require newer google-cloud

---

dvc/system.py

reflink: osx: check that not older than High Sierra

---

dvc/system.py

osx: reflink: check if clib has clonefile()

---

dvc/remote/local.py

pull: add dummy call to try establishing the connection

---

dvc/cli.py
dvc/command/repro.py
dvc/project.py
tests/test_repro.py

repro: introduce -P|--all-pipelines

---

dvc/remote/s3.py

s3: fix dvc not loading AWS settings from environment variables

---

dvc/cli.py
dvc/command/gc.py
tests/test_gc.py

gc: add a comfirmation prompt

---

dvc/stage.py

stage: properly report StageFileFormatError

---

dvc/dagascii.py
requirements.txt
setup.py

show: use asciimatics to provide scrollable graph

---

dvc/dagascii.py

dagascii: add more keys

---

scripts/ci/script.sh
tests/__main__.py

test: upload coverage only on CRON

---

dvc/system.py
requirements.txt
setup.py

dvc: stop using ntfsutils module

---

dvc/remote/hdfs.py

hdfs: don't use close_fds on Windows

---

dvc/cli.py

import: add a note about supported schemes

---

dvc/logger.py
dvc/stage.py

repro: show which dependencies have changed

---

dvc/dagascii.py

dagascii: import asciimatics only when needed

---

dvc/logger.py
dvc/progress.py
dvc/remote/local.py

progress reporting fixes

---

.codeclimate.yml

codeclimate: turn all the checks on

---

dvc/logger.py
dvc/remote/azure.py
dvc/remote/gs.py
dvc/remote/local.py
dvc/remote/s3.py
dvc/remote/ssh.py

remote: use warning if upload/download failed

---

dvc/system.py

system: add workaround for buggy os.lstat().st_ino

---

.appveyor.yml
dvc/system.py

link: properly catch error on windows

---

dvc/remote/local.py

link: don't create links for empty files

---

dvc/scm.py
tests/test_install.py

install: add pre-checkout hook

---

dvc/system.py

system: catch link exceptions

---

dvc/exceptions.py
dvc/project.py
tests/test_run.py

run: Check for circular dependencies

---

dvc/command/root.py
tests/test_config.py

root: don't check project's lock

---

dvc/stage.py
tests/test_run.py

stage: check that cwd is inside the current project

---

dvc/remote/hdfs.py
dvc/stage.py

dvc: don't use $SHELL on windows

---

dvc/cli.py
dvc/command/remove.py
tests/test_remove.py

remove: Add confirmation when trying to purge

---

dvc/cli.py
dvc/command/base.py

cli: Move mutual exclusion of --quiet and --verbose to the parser level

---

dvc/project.py
tests/test_run.py

run: Add abspath to circular dependency check and include outs_no_cache

---

dvc/scm.py
tests/test_repro.py

scm: Add dir property to Base class

---

dvc/logger.py
dvc/updater.py

updater: Add some colors and a frame to the update message

---

dvc/cli.py
dvc/command/remove.py
tests/test_remove.py

remove: Set --purge as default instead of --outs

---

dvc/cli.py
dvc/command/pipeline.py
tests/test_pipeline.py

dvc: introduce `pipeline list` command

---

dvc/stage.py

run: warn if using fish shell

---

dvc/remote/local.py

remote: Show progress bar when linking large dirs

---

dvc/state.py
tests/test_state.py

state: add workaround for VACUUM bug on python 3.6 and 3.7

---

dvc/project.py
dvc/remote/local.py
tests/test_checkout.py

checkout: Remove selectively on directory files when changed

---

.dvc/.gitignore
dvc/project.py
dvc/state.py

gitignore: Add temporary SQLite files

---

dvc/scm.py
tests/test_checkout.py
tests/test_scm.py

gitignore: use unambiguous paths

---

dvc/cli.py
dvc/command/daemon.py
dvc/daemon.py
dvc/project.py
dvc/updater.py
dvc/utils.py

updater: spawn a background daemon

---

dvc/project.py
tests/test_repro.py

dvc: properly build DAG for dependency directories

---

dvc/daemon.py
dvc/updater.py

updater: don't throw errors when running in a daemon

---

dvc/cli.py
dvc/command/checkout.py
dvc/command/data_sync.py
dvc/output/gs.py
dvc/output/hdfs.py
dvc/output/local.py
dvc/output/s3.py
dvc/output/ssh.py
dvc/project.py
dvc/remote/base.py
dvc/remote/local.py
dvc/stage.py
tests/test_checkout.py
tests/test_metrics.py
tests/test_repro.py

checkout: Prompt when deleting files from working dir

---

dvc/updater.py

updater: catch lock error

---

dvc/project.py

init: Add a welcome message

---

dvc/dagascii.py
requirements.txt
setup.py

dagascii: use wait_for_input from asciimatics

---

dvc/dagascii.py
dvc/system.py
requirements.txt
setup.py

dagascii: don't use unreleased wait_for_input method

---

dvc/project.py

status: support --with-deps for local status

---

dvc/output/local.py
dvc/project.py

metrics add: Raise exception when path does not exist

---

dvc/cli.py
dvc/command/imp.py
tests/test_import.py

import: Output as on optional argument

---

dvc/logger.py
dvc/progress.py
tests/test_logger.py

progress: Respect the --quiet option

---

dvc/exceptions.py
dvc/project.py
tests/test_run.py

run: Check CWD specified as output in any stage

---

dvc/stage.py
tests/test_repro.py

dvc: don't report locked callback stages as changed

---

dvc/stage.py
dvc/utils.py
tests/test_repro.py
tests/test_stage.py
tests/test_utils.py

stage: properly handle dvc file md5

---

dvc/data_cloud.py
tests/test_data_cloud.py

dvc: dynamically load default cloud

---

dvc/analytics.py
dvc/command/daemon.py
dvc/main.py
tests/test_analytics.py

analytics: collect cmd early

---

dvc/logger.py
dvc/main.py
tests/test_logger.py
tests/test_run.py

dvc: handle KeyboardInterrupt

---

dvc/dependency/hdfs.py
dvc/dependency/http.py
dvc/dependency/s3.py
dvc/dependency/ssh.py
dvc/remote/azure.py
dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/hdfs.py
dvc/remote/local.py
dvc/remote/s3.py
dvc/remote/ssh.py
tests/__main__.py
tests/test_repro.py

remote: properly check status for remote outputs

---

dvc/remote/gs.py

gs: use md5_hash instead of etag for external deps/outs

---

dvc/project.py
tests/test_add.py

dvc: catch cached stages

---

dvc/logger.py
tests/test_logger.py

logger: Prevent adding multiple handlers

---

.travis.yml
tests/__main__.py
tests/basic_env.py
tests/test_add.py
tests/test_analytics.py
tests/test_cache.py
tests/test_checkout.py
tests/test_cli.py
tests/test_config.py
tests/test_data_cloud.py
tests/test_gc.py
tests/test_import.py
tests/test_init.py
tests/test_logger.py
tests/test_metrics.py
tests/test_move.py
tests/test_pipeline.py
tests/test_remote.py
tests/test_remove.py
tests/test_repro.py
tests/test_run.py
tests/test_stage.py
tests/test_state.py
tests/test_system.py
tests/test_unprotect.py
tests/test_utils.py

test: enable flake8 checks for tests

---

dvc/prompt.py
dvc/remote/ssh.py

ssh: mention private key passphrase in the prompt

---

dvc/config.py
dvc/remote/s3.py

- Docs: https://github.com/iterative/dvc.org/pull/135

remote s3: Add option to disable the use of SSL

---

dvc/dependency/base.py
dvc/exceptions.py
dvc/project.py
dvc/remote/base.py
dvc/remote/http.py
dvc/scm.py
dvc/stage.py
dvc/state.py
tests/test_run.py

Fix #1255
Fix #1168
Close #1259
RFC:
- Add / fix docstrings and privatize methods
- Add __repr__ method for core objects

run: Prevent argument duplication with deps/outs

---

dvc/project.py
tests/test_pipeline.py

:thinking: I'm not sure about this, could you review it, @efiop ?
I ran the test suite and it passed but it is likely that it didn't cover the correct cases.

RFC: Refactor pipeline definition

---

dvc/command/repro.py
tests/test_repro.py

repro: Fix --all-pipelines option

---

dvc/exceptions.py
dvc/logger.py
tests/test_logger.py

logger: handle chained exceptions

---

dvc/remote/azure.py
tests/test_data_cloud.py
tests/unit/remote/azure.py

azure: fix backward compatibility

---

README.rst

readme: Fix typo in ubuntu/debian installation guide

---

dvc/cli.py
dvc/output/ssh.py
dvc/remote/ssh.py
tests/unit/remote/ssh.py

See commit messages.
Updated docs at https://github.com/iterative/dvc.org/pull/152

ssh: `user` and `port` configuration

---

dvc/command/run.py
tests/test_run.py

run: Parse and quote correctly the command

---

dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/hdfs.py
dvc/remote/local.py
dvc/remote/s3.py
dvc/remote/ssh.py

RFC: remote: unify changed() method

---

dvc/cli.py
dvc/command/data_sync.py
dvc/project.py
tests/test_data_cloud.py

project: support recursive sync operations

---

dvc/state.py
tests/test_data_cloud.py
tests/unit/state.py
tests/utils/__init__.py

state: cast file size to string

---

tests/basic_env.py

test: enlarge test base bar content

---

dvc/command/imp.py
tests/test_import.py

Fixes #1488 
I think we should change related issue title, since original issue is not a bug.

imp: refactor import message

---

dvc/command/data_sync.py
dvc/project.py

-R options acts as boolean, minor daemon fix 

---

dvc/project.py
tests/test_move.py
tests/utils/__init__.py

move: handle directory as target argument

---

README.rst

As discussed with @efiop on discord, I think DAGsHub could be useful to the DVC community

Added DAGsHub to "Related Technologies"

---

dvc/exceptions.py
dvc/project.py
dvc/stage.py
tests/test_repro.py
tests/test_run.py

project: Detect circular dependencies on graph

---

dvc/output/base.py
dvc/output/local.py
dvc/remote/azure.py
dvc/remote/http.py
dvc/stage.py
tests/test_checkout.py
tests/test_repro.py
tests/test_run.py

stage: Checkout cached output when possible

---

dvc/daemon.py
tests/unit/daemon.py

daemon: set PYTHONPATH

---

dvc/remote/gs.py
tests/unit/remote/gs.py

remote: gs: don't forget to set projectname

---

dvc/command/status.py
tests/test_status.py

status: --quiet reflects changes on its exit code

---

.travis.yml
scripts/ci/before_install.sh
scripts/ci/install_azurite.sh
scripts/ci/install_hadoop.sh

travis: test azure and hadoop only during cron jobs

---

test-style-requirements.txt

style: Add flake8-docstrings

---

dvc/project.py
dvc/stage.py
tests/test_checkout.py
tests/unit/stage.py

checkout: Suggest git checkout when dcv checkout fails

---

dvc/remote/base.py

remote: notify when operation is not supported

---

dvc/remote/base.py
dvc/remote/hdfs.py
dvc/remote/ssh.py
tests/unit/remote/base.py

remote: define command error on the base

---

dvc/project.py
tests/test_metrics.py

* Fixes https://github.com/iterative/dvc/issues/1590#issuecomment-462323771
* Refactoring - simplifies metrics show code removes backward compatible behavior - all files that metrics show takes **must** be metrics files in DVC sense - there **must**  a DVC files that specifies them as a metric file.

Fix metrics show all braches/tags behavior when target is not specified

---

dvc/remote/ssh.py
tests/unit/remote/ssh.py

https://discordapp.com/channels/485586884165107732/485596304961962003/545702950350356502

ssh: handle url without path

---

dvc/remote/local.py
dvc/state.py
tests/test_add.py

add: recalculate checksum after link creation, test

---

dvc/command/data_sync.py
dvc/remote/local.py
dvc/repo/fetch.py
dvc/repo/pull.py
dvc/repo/push.py

push: When there's nothing to push, show a message

---

dvc/remote/local.py
tests/test_add.py

add: update state for known checksum for dir

---

.travis.yml
scripts/ci/deploy_condition.sh

travis: add xcode10.1 build

---

dvc/repo/move.py
dvc/utils/compat.py
tests/test_move.py
tests/utils/__init__.py

move: awareness of cwd when moving files

---

dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/hdfs.py
dvc/remote/s3.py
dvc/remote/ssh/__init__.py
tests/unit/remote/base.py

ssh: external-outs: check if cache exists before copying

---

dvc/stage.py
tests/test_repro.py

stage: always reproduce callback stages

---

dvc/repo/status.py
tests/test_status.py

status: imply --cloud when a remote is given

---

dvc/remote/azure.py
dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/local.py
dvc/remote/s3.py
dvc/remote/ssh/connection.py
dvc/utils/__init__.py

ssh: upload to a tmp file to prevent data corruption

---

dvc/output/base.py
tests/unit/dependency/gs.py
tests/unit/dependency/hdfs.py
tests/unit/dependency/http.py
tests/unit/dependency/local.py
tests/unit/dependency/s3.py
tests/unit/dependency/ssh.py
tests/unit/output/gs.py
tests/unit/output/hdfs.py
tests/unit/output/local.py
tests/unit/output/s3.py
tests/unit/output/ssh.py

From discussion on discord
https://discordapp.com/channels/485586884165107732/485596304961962003/548083580052701205

output/deps: raise proper exception when file/dir doesn't exist

---

dvc/command/gc.py

In accordance with what I understood the code actually does, as well as [the docs](https://dvc.org/doc/commands-reference/gc)
Note my question about --force though, I wasn't sure what to do with that.

Clarified command line flags for dvc gc

---

dvc/command/run.py
dvc/exceptions.py
dvc/output/local.py
dvc/repo/__init__.py
dvc/repo/move.py
dvc/repo/run.py
dvc/stage.py
tests/test_repro.py
tests/test_run.py

Fixes https://github.com/iterative/dvc/issues/1645

[WIP] Introduce wdir for DVC stage files

---

dvc/remote/local.py
dvc/state.py
dvc/utils/__init__.py
dvc/utils/fs.py
tests/test_add.py
tests/unit/fs.py

remote local/state : add check for cache dir metadata changes

---

dvc/remote/local.py
tests/test_add.py

remote local: add dir state update after processing the files

---

dvc/repo/add.py

Improve readability, remove unnecessary None stage check

[RFC] add command: refactor

---

dvc/logger.py
dvc/progress.py
dvc/prompt.py
tests/unit/progress.py

logger: Format progress bar interruption

---

dvc/stage.py
tests/test_stage.py
tests/unit/stage.py

Stage checksum with default wdir fix

---

dvc/remote/hdfs.py
dvc/remote/local.py

remote: upload/download to a temp file

---

dvc/exceptions.py
dvc/utils/__init__.py
tests/test_add.py
tests/test_data_cloud.py
tests/test_import.py
tests/test_logger.py
tests/utils/__init__.py
tests/utils/logger.py

utils: translate yaml file loading exception to dvc one

---

dvc/remote/azure.py
dvc/remote/gs.py
dvc/remote/http.py
dvc/remote/local.py
dvc/remote/s3.py
dvc/remote/ssh/connection.py
dvc/repo/imp.py
dvc/stage.py
tests/test_repro.py

Fix #1667
(Deleted https://github.com/iterative/dvc/pull/1670 accidentally)

stage: always reproduce when --force is given

---

dvc/remote/ssh/connection.py

Fixes #1701 which made ssh remotes unusable on windows machines.

Fixes #1701

---

dvc/command/add.py
dvc/exceptions.py
dvc/repo/add.py
dvc/utils/__init__.py
tests/test_add.py

add: support the `--file` option

---

dvc/state.py
tests/test_state.py

Apply inode value mapping when checking for an existing entry

---

dvc/exceptions.py
tests/test_add.py

yaml loading error: display relative path

---

dvc/remote/base.py
dvc/remote/local.py
tests/test_add.py
tests/test_data_cloud.py
tests/test_import.py
tests/test_logger.py
tests/test_metrics.py
tests/utils/__init__.py

push/pull/status -c: should complain on no checksum locally and remotely

---

dvc/repo/__init__.py
dvc/repo/add.py
dvc/scm/base.py
dvc/scm/git.py
tests/test_add.py
tests/unit/repo.py
tests/unit/scm/git.py

add: prevent adding git files

---

dvc/command/status.py

This is the first iteration to improve our code coverage and make it persistent. This PR increases code coverage for `dvc/command*` files to 100% and enables a check for it on our travis.

cli: status: remove unused code

---

dvc/stage.py
tests/test_checkout.py
tests/test_data_cloud.py
tests/test_repro.py
tests/unit/stage.py

stage: convert wdir path to posix

---

tests/__main__.py

Added `--exe` argument to nosetest default

---

dvc/logger.py

cli: Use correct color codes on Windows

---

dvc/cli.py
dvc/command/pkg.py
dvc/output/base.py
dvc/output/local.py
dvc/repo/__init__.py
dvc/repo/pkg.py
dvc/scm/base.py
dvc/scm/git.py
dvc/stage.py
dvc/temp_git_repo.py
tests/basic_env.py
tests/test_data_cloud.py
tests/test_move.py
tests/test_pkg.py
tests/test_scm.py

`dvc pkg install [git package] [dir]` command
Unit-tests are in progress.

[WIP] Pkg install

---

dvc/command/repro.py

Fix typo in repro.py

---

dvc/command/gc.py
scripts/completion/dvc.bash
scripts/completion/dvc.zsh

scripts: update completion for zsh and bash

---

dvc/command/cache.py
tests/test_cache.py

cache: provide at least one value in parser

---

dvc/exceptions.py
dvc/repo/__init__.py
tests/test_repro.py
tests/test_run.py

repo: check whether outputs in graphs do not overlap

---

dvc/repo/remove.py
dvc/stage.py
tests/test_run.py

remove: force remove to remove persistent outputs

---

dvc/command/metrics.py
dvc/command/repro.py
tests/test_repro.py

metrics: rename show, repro: display metrics

---

dvc/command/checkout.py
dvc/exceptions.py
dvc/repo/__init__.py
dvc/repo/checkout.py
tests/test_checkout.py

repo: fix stages gathering for checkout

---

dvc/command/add.py
dvc/command/base.py
dvc/command/cache.py
dvc/command/checkout.py
dvc/command/commit.py
dvc/command/config.py
dvc/command/data_sync.py
dvc/command/destroy.py
dvc/command/gc.py
dvc/command/imp.py
dvc/command/init.py
dvc/command/install.py
dvc/command/lock.py
dvc/command/metrics.py
dvc/command/move.py
dvc/command/pipeline.py
dvc/command/pkg.py
dvc/command/remote.py
dvc/command/remove.py
dvc/command/repro.py
dvc/command/root.py
dvc/command/run.py
dvc/command/unprotect.py

Move man doc links to descriptions, fix some help copies

---

dvc/cli.py
dvc/command/tag.py
dvc/exceptions.py
dvc/output/__init__.py
dvc/output/base.py
dvc/output/hdfs.py
dvc/output/local.py
dvc/output/s3.py
dvc/output/ssh.py
dvc/remote/base.py
dvc/remote/local.py
dvc/repo/__init__.py
dvc/repo/checkout.py
dvc/repo/commit.py
dvc/repo/status.py
dvc/repo/tag/__init__.py
dvc/repo/tag/add.py
dvc/repo/tag/list.py
dvc/repo/tag/remove.py
dvc/stage.py
tests/test_checkout.py
tests/test_tag.py

Initial implementation with basic `dvc tag add/list/remove` support and support for `dvc checkout stage.dvc@mytag`.

[RFC] introduce `dvc tag`

---

dvc/remote/azure.py

This enables `dvc pull` for azure connection strings which have read-only credential
resolves #1811

azure: do not create existing container

---

.dvc/config

dvc: use http remote for downloading dvc images

---

dvc/system.py

system: reflink: workaround SIP error

---

dvc/repo/status.py
tests/test_data_cloud.py

status: properly handle STATUS_MISSING case

---

dvc/progress.py
tests/unit/test_progress.py

checkout: reset progress bar on checkout

---

dvc/command/metrics.py
dvc/repo/metrics/show.py
tests/test_metrics.py

Detect json/tsv/htsv/csv/hcsv metric files by file extensions.
Fixes #1553

metrics: automatic type detection

---

scripts/hooks/hook-checksumdir.py
scripts/hooks/hook-google.cloud.storage.py

Fixes #1697
Added https://github.com/iterative/dvc-test/issues/4 .

dvc: pyinstaller: fix google.cloud.storage hook

---

dvc/version.py
tests/unit/test_version.py

Please see commit messages for more info.

Version generation improvements

---

dvc/remote/local.py
dvc/repo/scm_context.py
dvc/utils/__init__.py
dvc/utils/fs.py
tests/requirements.txt
tests/test_checkout.py
tests/test_remove.py

checkout/remove: properly handle broken symlinks

---

dvc/command/diff.py

Corresponds to changes in https://github.com/iterative/dvc.org/pull/236

Small `dvc diff` command help output changes.

---

dvc/version.py

version: show when the release version is dirty

---

dvc/command/run.py
dvc/stage.py
scripts/completion/dvc.zsh

dvc: deprecate --remove-outs

---

dvc/command/diff.py

diff: cli: add documentation link

---

README.rst

readme: new logo header

---

dvc/command/pkg.py
dvc/repo/__init__.py
dvc/repo/pkg/__init__.py
dvc/repo/pkg/install.py
tests/func/test_pkg.py

pkg: comply with design of other dvc commands

---

dvc/stage.py
tests/func/test_add.py

stage: commit cached stage to avoid data duplication

---

dvc/remote/ssh/__init__.py

ssh: respect no_progress_bar on download/upload

---

dvc/remote/base.py
dvc/repo/__init__.py

Some gc-related optimizations.

dvc: some minor optimizations

---

tests/func/test_metrics.py

test: dedup some metrics tests

---

dvc/data_cloud.py
dvc/remote/local/__init__.py
tests/unit/remote/test_local.py

status: optimization for already downloaded files

---

tests/func/test_commit.py

-----
Decouple tests from `tests/func/test_commit.py` from unittest.

commit: test: pytest style

---

dvc/config.py

Extracted from https://github.com/iterative/dvc/pull/1804/

config: implement bool_schema

---

tests/func/test_metrics.py

@efiop , @Suor, this issue is going to "fix" only the faulty test, let's discuss all the encoding related topics on a [different issue](https://github.com/iterative/dvc/issues/1957) and take a decision about how we should manage this across the code base.
-----
Fix #1929

tests: use UTF-8 when creating metrics files

---

README.rst

removed munched sentence in readme

---

dvc/logger.py
tests/unit/test_logger.py

logger: fix bug that ignored the progress bar

---

dvc/scm/git/__init__.py
tests/func/test_install.py

install: append commands if hook already exists

---

dvc/command/version.py

-----
These changes simply update the version help for better understanding.

Update version help

---

dvc/command/base.py
dvc/command/config.py
dvc/command/daemon.py
dvc/command/init.py
dvc/command/root.py
dvc/command/version.py
tests/unit/command/test_version.py

cmd: use CmdBaseNoRepo for commands without repo

---

dvc/system.py

use windows constants in system.py

---

dvc/remote/ssh/__init__.py

remote: ssh: fix error message

---

requirements.txt
setup.py

upgpkg: requests >= 2.22.0

---

.appveyor.yml
.travis.yml
scripts/build_windows.cmd
scripts/ci/before_deploy.sh
scripts/ci/script.sh

ci: automatically deploy to pypi

---

dvc/state.py

remove unnecessary arguments in state methods

---

.gitignore
scripts/ci/install_hadoop.sh
scripts/ci/remove_hadoop.sh
tests/func/test_data_cloud.py
tests/remotes_env.sample

test: update/add helpers to run tests against remotes

---

dvc/command/pipeline.py
tests/func/test_pipeline.py

-----
Issue:https://github.com/iterative/dvc/issues/1743
dvc.org
PR: https://github.com/iterative/dvc.org/pull/371

pipeline: show: dot: print dot

---

dvc/remote/base.py
dvc/repo/__init__.py
dvc/repo/status.py

Splitting #2044 in two PR's, one for the docstrings and the other for the actual implementation.

docs: add some docstrings about computing status

---

tests/func/test_checkout.py
tests/unit/test_logger.py

tests: resolve deprecation warnings

---

dvc/state.py

state: remove unused changed method

---

.appveyor.yml
.travis.yml
scripts/ci/before_deploy.sh

ci: build binaries on python 3.7

---

dvc/remote/local/__init__.py
dvc/state.py
tests/func/test_add.py

remote: local: roll back cache dir metadata storing

---

dvc/utils/__init__.py

remote: local: try to reflink before copying

---

dvc/progress.py
tests/unit/test_progress.py

Related to #1377
-----
stumbling twice on the same stone :see_no_evil:

progress: bug fix with --quiet

---

dvc/utils/fs.py

make get_mtime_and_size use single stat call for files

---

dvc/remote/local/__init__.py

This is useful for debugging remote operations.
-----

remote: don't use threadpool for single thread

---

dvc/scm/git/__init__.py

-----
I'm just adding a comma to the following message:
`To track the changes with git run`
It will then become
`To track the changes with git, run`

Adding a comma to the message to improve understanding

---

scripts/build_posix.sh

scripts:add description for debian package

---

scripts/ci/install_hadoop.sh

Related to
https://github.com/iterative/dvc/issues/1629#issuecomment-498023424
-----

tests: test hdfs on cron and releases

---

.appveyor.yml

ci: don't limit appveyor to master and devel

---

scripts/ci/install_hadoop.sh

This reverts commit 76c47558655ba8e6bafa8efa06f6368a12b030f6.
-----
These are already disabled in scripts/ci/before_install.sh

Revert "tests: test hdfs on cron and releases"

---

dvc/cache.py
dvc/command/cache.py
dvc/command/config.py
dvc/command/remote.py
dvc/config.py
dvc/data_cloud.py
dvc/dependency/__init__.py
dvc/main.py
dvc/output/__init__.py
dvc/remote/__init__.py
dvc/remote/config.py
dvc/repo/__init__.py
tests/basic_env.py
tests/func/test_config.py
tests/func/test_data_cloud.py
tests/func/test_remote.py

refactoring: move config logic from CLI to API

---

dvc/config.py
dvc/remote/s3.py

Fixes #1967 
-----
Documentation: iterative/dvc.org#421

remote: add basic support for s3 server side encryption.

---

dvc/remote/base.py
dvc/remote/local/__init__.py
tests/func/remote/test_local.py
tests/func/test_checkout.py
tests/func/test_repro.py
tests/utils/__init__.py

remote: local: add cache status check hardlink optimization

---

dvc/command/cache.py
dvc/command/remote.py

config: rename RemoteConfig variable in CmdRemoteConfig class

---

dvc/scm/git/__init__.py
tests/func/test_scm.py

scm: git: end gitignore with newline

---

dvc/command/version.py
tests/func/test_version.py

Check whether package is installed from source or binary

---

dvc/ignore.py
dvc/state.py
dvc/system.py
dvc/utils/__init__.py
dvc/utils/fs.py
tests/func/test_state.py
tests/func/test_system.py

```
------------------------------------------------------------
File "/Users/efiop/git/dvc/dvc/remote/local/__init__.py", line 280, in upload
no_progress_bar=no_progress_bar,
File "/Users/efiop/git/dvc/dvc/utils/__init__.py", line 129, in copyfile
System.reflink(src, dest)
File "/Users/efiop/git/dvc/dvc/system.py", line 125, in reflink
ret = System._reflink_darwin(source, link_name)
File "/Users/efiop/git/dvc/dvc/system.py", line 89, in _reflink_darwin
ctypes.c_char_p(src.encode("utf-8")),
AttributeError: 'PosixPathInfo' object has no attribute 'encode'
------------------------------------------------------------
```
that should be …

system: handle PurePath

---

dvc/command/data_sync.py
dvc/remote/base.py
dvc/remote/http.py
dvc/remote/local/__init__.py
tests/func/test_remote.py

dvc: return non zero error code on push/pull/fetch error

---

dvc/remote/azure.py
dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/hdfs.py
dvc/remote/http.py
dvc/remote/local/__init__.py
dvc/remote/oss.py
dvc/remote/s3.py
dvc/remote/ssh/__init__.py

Fix #1762
Fix https://github.com/iterative/dvc/issues/1825
-----

status: show a progress bar while gathering info

---

dvc/repo/init.py
dvc/scm/git/__init__.py

dvc: use realpath-ed paths consistently

---

dvc/command/pipeline.py
dvc/command/root.py
dvc/exceptions.py
dvc/ignore.py
dvc/path_info.py
dvc/remote/base.py
dvc/remote/config.py
dvc/remote/local/__init__.py
dvc/repo/__init__.py
dvc/repo/init.py
dvc/repo/reproduce.py
dvc/scm/git/__init__.py
dvc/scm/git/tree.py
dvc/stage.py
dvc/state.py
dvc/utils/__init__.py
tests/basic_env.py
tests/conftest.py
tests/func/test_add.py
tests/func/test_cache.py
tests/func/test_checkout.py
tests/func/test_metrics.py
tests/func/test_repro.py
tests/unit/utils/test_fs.py

pathinfo: extract relative path method to standalone method

---

dvc/repo/brancher.py
dvc/repo/metrics/show.py
tests/func/test_metrics.py

metrics: show: remove active branch from tags only show call

---

dvc/remote/http.py

http: enable progress bar

---

dvc/command/checkout.py
dvc/command/commit.py
dvc/command/data_sync.py

Fix #2063: Standardise order of command options in help messages

---

dvc/external_repo.py
dvc/repo/get_url.py

dvc: address review from #2160

---

dvc/repo/destroy.py
dvc/stage.py
tests/func/test_destroy.py

Fix #1011
https://github.com/iterative/dvc.org/pull/445
-----

dvc: destroy: don't remove data

---

dvc/command/get.py
dvc/command/imp_url.py

dvc: fix help messages for `get` and `import-url`

---

dvc/command/imp.py

import: add "beta feature" warning

---

dvc/state.py

state: use pep-0249 sql query formatting

---

.appveyor.yml

appveyor: require py3 to pass

---

dvc/api.py
tests/func/test_api.py

No tests yet, but this is how I expect this to look like.

dvc: add repo as url support to API

---

dvc/stage.py
tests/func/test_run.py

dvc: check stage name before running command

---

dvc/remote/ssh/connection.py

remote: fix race in and optimize SSHConnection.makedirs()

---

dvc/remote/base.py
dvc/remote/local/__init__.py
dvc/remote/ssh/__init__.py
dvc/state.py
dvc/utils/__init__.py
tests/func/test_state.py
tests/unit/utils/test_utils.py

state: bulk sql for unused links deletion

---

.deepsource.toml

`tests/**` will catch every file under `tests` dir, recursively.
-----
@efiop @shcheklein

Fix test_patterns glob in DeepSource config

---

dvc/config.py
dvc/remote/base.py

-----
Parallelizes `file_md5` and makes `get_file_checksum` return either a Future or an MD5 checksum.
Closes #2073.
The tests passed before I rebased from 1c6f46c0419232cc45f7ae770e633d3884bac169 to a54a34042ef637de1d8f1b715addc4d107f47547, so there must have been some important changes in between. I'll bisect and force-push a fixed version later today.

remote: base: parallelize _collect_dir

---

dvc/remote/base.py

-----
Fixes the progress bar regression in `_collect_dir` introduced by #2197, see https://github.com/iterative/dvc/pull/2197#issuecomment-508540262, and reverts generator expression in `_collect_dir` back to a for loop, see https://github.com/iterative/dvc/pull/2197#issuecomment-508540747.

remote: base: fix progress bar in _collect_dir

---

dvc/path_info.py
dvc/repo/__init__.py
tests/unit/test_path_info.py

-----
~20x (~2000s -> ~100s, 5000K files) `dvc add -R` to address #2203 
~If @Suor 's `isin` works fine we should merge that one. This path reduces the number of isin calls.~
Agreed to include Alexander's new `isin` version

graph outputs overlapping check optimization

---

dvc/path_info.py

dvc: optmize PathInfo.isin()

---

dvc/remote/base.py
tests/func/test_checkout.py

checkout: safe_remove output if no checksum is found

---

.travis.yml
scripts/build_windows.cmd
scripts/ci/before_install.sh
scripts/ci/check_python.sh
scripts/ci/install.sh

travis: win: don't override before_install

---

dvc/scm/git/tree.py

dvc: stop trying to fetch from remote when looking for git object

---

tests/func/test_repro.py

Following a DeepSource complaint

test: drop a reimport

---

scripts/build_windows.cmd
scripts/ci/before_deploy.sh

This will make it slower, but won't leave suprises for the release itself. Tests and travis optimizations will come soon, sorry for inconvenience :) 
-----

travis: try build packages on regular builds

---

setup.py

dvc: networkx 2.3 doesn't support py2 anymore

---

dvc/repo/imp_url.py
tests/func/test_import_url.py

imp_url: normalize path for default out name

---

dvc/command/imp.py

import: remove beta warnings

---

dvc/stage.py
tests/func/test_run.py

run: rerun deterministic callback

---

tests/func/test_import_url.py
tests/unit/command/test_imp_url.py

This one was failing randomly.
-----

tests: import-url: rewrite and move error msg test

---

dvc/output/base.py
tests/func/test_import.py

import: don't forget to add outs to gitignore

---

dvc/repo/add.py
dvc/repo/imp_url.py
dvc/repo/run.py
dvc/stage.py

run: use kwargs instead list of explicit arguments

---

dvc/repo/reproduce.py
dvc/stage.py

reproduce: use kwargs instead of explicit arguments

---

dvc/config.py
dvc/data_cloud.py
dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/local/__init__.py
dvc/remote/s3.py
tests/func/test_data_cloud.py

-----
Fixes #2221 
Fixes #2113

data_cloud: remove backward compatibilty on get_remote

---

scripts/ci/install.sh
setup.py

tests: use moto pre-release

---

dvc/path_info.py
tests/unit/test_path_info.py

url info: fix infinite recustion on deepcopy

---

dvc/dependency/repo.py
dvc/repo/get.py

import: only download specific output

---

dvc/stage.py
dvc/utils/__init__.py
tests/unit/test_stage.py

See commit messages for changes. Fixes #2209.

dvc: ignore Stage.meta in md5 calculations plus some polish

---

dvc/remote/ssh/__init__.py

ssh: do not ask for same password repeatedly

---

dvc/remote/base.py
dvc/utils/__init__.py

remote: base: try to retrieve path_info checksum from database upon dir checksum calculation

---

dvc/command/version.py
scripts/build_windows.cmd
scripts/ci/install.sh
setup.py

Workaround for https://github.com/iterative/dvc/issues/2284
-----

version: temporarily make psutil optional

---

dvc/repo/metrics/show.py
tests/func/test_metrics.py

metric: show: xpath should override stage file xpath

---

dvc/repo/scm_context.py
dvc/scm/base.py
dvc/scm/git/__init__.py

scm: reset tracked files after every operation

---

setup.py

-----
Workaround for [#2334](https://github.com/iterative/dvc/issues/2334)

Restrict ruamel.yaml version due import error

---

dvc/command/version.py
tests/func/test_version.py

version: don't skip link info and skip if there is no psutil

---

scripts/ci/before_install.sh
scripts/ci/install.sh
scripts/ci/retry.sh

travis: osx: retry brew update

---

README.rst

https://github.com/iterative/dvc.org/pull/513
-----

readme: add note about installing with conda

---

dvc/command/data_sync.py
dvc/command/status.py
dvc/repo/__init__.py
dvc/repo/fetch.py
dvc/repo/gc.py
dvc/repo/pull.py
dvc/repo/push.py
dvc/repo/status.py
tests/func/test_commit.py
tests/func/test_repro.py
tests/func/test_update.py

This will speed up cache collection and then run single cloud op for all
collected cache.
Fixes #2308.

dvc: batch push/pull/fetch/status

---

dvc/repo/reproduce.py

reproduce: properly handle --single-item case

---

dvc/repo/metrics/show.py

metrics show: extend NOTEs for show

---

dvc/command/status.py

dvc:Changes UP_TO_DATE_MSG in status.py

---

dvc/command/get.py
dvc/command/imp.py

dvc: Changes url description in get.py and imp.py

---

dvc/external_repo.py
dvc/scm/base.py
dvc/scm/git/__init__.py
tests/basic_env.py
tests/conftest.py
tests/func/test_diff.py
tests/func/test_install.py
tests/func/test_metrics.py
tests/func/test_repo.py
tests/func/test_scm.py
tests/func/test_update.py

[Contributing document](https://dvc.org/doc/user-guide/contributing)?     
-----
I have renamed git to repo in dvc/scm/git 
I'm unable to run tests (Import error of some files)
Fixes #1993

Renamed git property to repo object in dvc/scm/git

---

setup.py

Update azure-storage-blob package (== 2.1.0)

---

.travis.yml
scripts/build_posix.sh
scripts/ci/before_install.sh
scripts/ci/check_patch.sh
scripts/ci/check_python.sh

Partial #2361 
```
Run time:                 54m -> ~30m
Test windows 2.7:    24m -> 16m
Test window 3.7:      17m -> 13m
Test linux 2.7:           5:17m -> 3:37m
Test linx 3.5:             6:17m -> 3:55m
Test linux 3.6:           6:16m -> 3:44m
Test linux 3.7:           5:07m -> 3:37m
Test mac 2.7:            21m -> 7m
Test mac 3.{7->6}:    21m -> 7m
Build mac pkg:         24m -> 4m
Build win exe:          14:30m -> 9:30m
Build linux pkgs:      4:37m -> 3:07m
Build pypi pkgs:       2:36m -> 1:13m
```
least opened an issue for it? If so, …

travis: speedup install time

---

dvc/command/cache.py
dvc/command/metrics.py
dvc/command/pipeline.py
dvc/command/remote.py

cli: update man links to the new scheme

---

dvc/command/metrics.py
dvc/exceptions.py
dvc/repo/metrics/show.py
tests/func/test_metrics.py

metrics: allow multiple targets for show command

---

scripts/ci/before_install.sh
scripts/ci/install.sh
scripts/ci/install_azurite.sh

Trying to fix azure error on our ci:
https://travis-ci.com/iterative/dvc/jobs/224085273
-----

travis: use azurite v3

---

dvc/output/base.py
dvc/output/local.py
dvc/scm/git/__init__.py

A bunch of leftovers from a very old pkg implementation.
-----

dvc: remove unused code

---

dvc/remote/base.py
dvc/remote/http.py
tests/func/test_data_cloud.py
tests/unit/remote/test_http.py

http: add exception when trying to traverse remote

---

dvc/config.py
dvc/remote/s3.py

https://github.com/iterative/dvc.org/pull/573
-----
tested by running `dvc remote modify s3 acl bucket-owner-full-control` and checking the `.dvc/config` file
closes #2414

add acl config

---

.travis.yml

.travis.yml: add python version to build PyPi build scripts

---

dvc/repo/move.py
tests/func/test_move.py

repo: move: save stage after moving

---

dvc/remote/ssh/__init__.py

from https://github.com/iterative/dvc/pull/2333#discussion_r316185323

minor unreachable code move

---

dvc/stage.py
tests/func/test_add.py

dvc: use wdir = "." on add

---

setup.py

https://github.com/iterative/dvc/pull/2424#issuecomment-523990535
https://github.com/iterative/dvc.org/pull/582
-----

dvc: don't include gssapi

---

dvc/remote/base.py

cache: skip non-checksum files around cache

---

dvc/repo/__init__.py
dvc/repo/gc.py

-----
Fixes #2356 
Fixes #2046

repo.active_stages should return active stages

---

setup.py

workaround for google-resumable-media==0.3.3 build problem

---

dvc/command/remove.py

per https://github.com/iterative/dvc/issues/2456#issuecomment-526857699
Fix #2456
-----

remove: fix help output

---

dvc/stage.py
tests/func/test_add.py

-----
This change is also included in #2358, but since it also fixes #2125 it should be done ASAP.
Fixes #2125

stage: don't unprotect outs on stage create

---

dvc/remote/base.py

remote: base: check progress_callback when skipping on checkout

---

dvc/exceptions.py
dvc/repo/get.py
tests/func/test_get.py

get: show error message when path is a DVC-file

---

tests/func/test_add.py

test: add: remove TestDvcGit

---

tests/func/test_repro.py

test: repro: fix link types

---

dvc/remote/base.py
tests/func/test_checkout.py

remote: checkout: reuse _checkout_file functionality

---

MANIFEST.in
dvc/updater.py
fastentrypoints.py
setup.py

This is a huge package, which takes around 200 ms to load for me. This PR avoids loading it and thus saves startup time.
Should help with #2445.

perf: do not use pkg_resources

---

dvc/remote/http.py
dvc/remote/ssh/__init__.py
dvc/updater.py
dvc/utils/http.py

perf: import some things later

---

dvc/remote/azure.py
dvc/remote/base.py
dvc/remote/gs.py
dvc/remote/hdfs.py
dvc/remote/oss.py
dvc/remote/s3.py
dvc/remote/ssh/__init__.py
tests/unit/remote/test_base.py

Decreases `time dvc --version` from ~1.4 sec to ~0.3 sec.
Related #2495
Related #2445
-----

dvc: remote: optimize imports

---

dvc/exceptions.py
dvc/output/base.py
dvc/remote/base.py
dvc/repo/checkout.py
dvc/stage.py
tests/func/test_cache.py
tests/func/test_checkout.py

checkout: raise on non existing dir cache

---

dvc/command/diff.py
dvc/command/get.py
dvc/command/get_url.py
dvc/command/pipeline.py
dvc/command/root.py
dvc/command/version.py

Saves another 10-20 ms on startup time.

perf: import dvc.repo dynamically

---

dvc/main.py

Fix #2524 , after https://github.com/iterative/dvc/pull/2533#issuecomment-535317707

py2: display friendly error when raising a UnicodeError

---

dvc/exceptions.py

als made consistent the placement of inter-word space when there's a newline in the code
-----

Added a space in error message

---

dvc/logger.py
dvc/utils/compat.py

- fix #2547 using same approach as https://github.com/matplotlib/matplotlib/pull/10422

fix py27 compat

---

dvc/remote/ssh/connection.py

sftp: add a more descriptive error on mkdirs

---

dvc/stage.py

Config files like `~/.zshenv`, `~/.bashenv` etc, are loaded on each
shell invocation, which might overwrite the environment breaking the
commands we are trying to wrap. To fix that, we need to provide
appropriate flags to the shell we are using to avoid loading those
configs.
Fixes #2506
-----

run: make shell not load config files

---

dvc/utils/__init__.py
tests/unit/utils/test_utils.py

https://discordapp.com/channels/485586884165107732/485596304961962003/628766062472724510
Related to #2506
-----

run: improve pyenv PATH modification criteria

---

scripts/build_posix.sh

scripts: make completion scripts part of the debian package

---

scripts/build_posix.sh

deb/rpm/pkg: add zsh completion scripts

---

README.rst

Additional clarification for what DVC aims to do.
-----

Update to Readme

---

dvc/scm/git/__init__.py
scripts/build_posix.sh
setup.py
tests/func/test_add.py

git: escape filename before ignoring it

---

dvc/scm/git/__init__.py
dvc/stage.py

Move some messages generated during import from INFO to DEBUG log level.
Fixes #2489
-----

dvc: Reduce import output verbosity

---

scripts/build_posix.sh

Fixes https://github.com/iterative/dvc/issues/2585
-----

scripts: don't include completion scripts into mac pkg

---

dvc/version.py
setup.py

[dvc.org](https://github.com/iterative/dvc.org) documenting it or at least opened an issue for it? If so, 
please add a link to it.
-----
I have a problem when doing `pip install -e ".[all,tests]"` ([Error Message](https://gist.github.com/irchanbani/ed37593a550d5aae30a3bbff9522fe5b)).
After some discussion with @efiop this is [the solution](https://gist.github.com/efiop/a43869fdbb8a0f21f96a3ee8a050671a) that came up.

setup: change define __version__

---

dvc/remote/base.py

[dvc.org](https://github.com/iterative/dvc.org) documenting it or at least
opened an issue for it? If so, please add a link to it.
-----
Related #2565 
I think there can be one documentation change here:
`Saving 'data.xml' to cache '.dvc/cache'.` might not be required here.

Reduce verbosity of `dvc add`

---

dvc/cli.py

cli: changed help message (-h) to start with capital letter

---

dvc/logger.py
tests/unit/test_logger.py

logger: send warning messages to stderr

---

setup.py

As a part of the research for https://github.com/iterative/dvc/issues/2600
-----

setup: update pyinstaller to 3.5

---

dvc/external_repo.py
dvc/remote/base.py
dvc/remote/http.py

corrected ordering of base.py

---

dvc/__init__.py

__init__.py : Fixed the import orders in __init__.py according to PEP8 Standards.
Fixes issue #2617

Fixed wrong order imports accordance to PEP

---

dvc/progress.py

- fixes #2598 progress errors on narrow terminals/wide descriptions

fix ncols_desc=0

---

dvc/lock.py

Workaround for slow and obsoleted `gethostbyaddr` used in
`socket.getfqdn()`. See [1], [2] and [3] for more info.
[1] https://bugs.python.org/issue5004
[2] https://github.com/iterative/dvc/issues/2582
[3] https://gitlab.com/warsaw/flufl.lock/merge_requests/12
`flufl.lock` guys seem unresponsive, so we have to monkeypatch
this ourselves, at least for now.
Fixes #2582
-----

lock: monkeypatch socket.getfqdn used by flufl.lock

---

dvc/remote/local.py

I have changed the import orders

corrected import order

---

dvc/system.py

changed order of imports

---

dvc/repo/get.py
dvc/repo/imp.py

Added path.lstrip("/") in import

---

dvc/exceptions.py
dvc/output/base.py
tests/func/test_gc.py

CC @Suor
Fixes https://gist.github.com/leimbernon/21924e02a998e3f1604990f8a7824c37
-----

output: base: don't forget to return empty cache

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.rst

Related to: https://github.com/iterative/dvc.org/pull/726

Update URLs by replacing /contributing with /contributing/code

---

dvc/remote/ssh/__init__.py

ssh credential prompt before progress

---

dvc/remote/gs.py
tests/unit/remote/test_gs.py

gs: retry upload

---

dvc/repo/get.py
dvc/repo/imp.py

Reverts iterative/dvc#2651
Turns out people are actually using abs paths there O_o https://discuss.dvc.org/t/dvc-get-doesnt-work-with-absolute-paths-but-everything-else-seems-to/249

Revert "Added path.lstrip("/") in import"

---

dvc/repo/fetch.py

fixed typo

---

tests/unit/remote/test_local.py

fix typo(correct spelling of existence)

---

dvc/remote/local.py

typo changed for existance->existence

---

dvc/command/version.py
dvc/updater.py
dvc/utils/pkg.py

Added package manager to dvc version output

---

.github/PULL_REQUEST_TEMPLATE.md

fix PR template to mention recommendatory nature of CC and DS

---

dvc/utils/fs.py
tests/unit/utils/test_fs.py

Remove `get_parent_dirs_up_to`

---

dvc/ignore.py
tests/func/test_ignore.py

dvcignore: don't forget to use dvcignore when collecting dvcignores

---

dvc/repo/get.py
tests/func/test_gc.py
tests/func/test_get.py
tests/func/test_import.py

Fixes #2744 
---------------------

dvc get leaves dangling symlinks if source repo is set to use symlinks as its cache type

---

dvc/repo/checkout.py

checkout: don't cleanup links when checking out specific targets

---

dvc/ignore.py
dvc/repo/__init__.py
tests/func/test_ignore.py
tests/func/test_tree.py
tests/unit/test_ignore.py
tests/unit/utils/test_fs.py

ignore: make DvcIgnoreFilter use tree

---

dvc/main.py

dvc: add workaround for `LookupError: unknown encoding: idna`

---

scripts/hooks/hook-dvc.system.py

Also added a simple test to `dvc-test` repo [1].
[1] https://github.com/iterative/dvc-test/commit/5748744fa1ebb4e265f08fedcddc66a17e8bd914
Fixes #2754

pyinstaller: add pywin32/win32file hook

---

scripts/innosetup/addsymlink.iss

This allows dvc to be installed in a silent mode.

win: use SuppressibleMsgBox instead of MsgBox

---

.pre-commit-config.yaml
.restyled.yaml

dvc: remove reorder_python_imports formatter

---

dvc/__main__.py

Possible fix for #2850.

---

tests/func/test_add.py

TestAddUnsupportedFile
TestAdd
TestAddDirectory

add: test: convert to dir helpers 3

---

tests/func/test_move.py

test: move: convert to dir helpers

---

tests/func/test_commit.py

commit: test: refactor to dir helpers

---

dvc/exceptions.py

run: provide a hint if we get output duplication error

---

dvc/remote/hdfs.py
dvc/remote/local.py
dvc/remote/ssh/__init__.py
dvc/remote/ssh/connection.py
tests/func/test_add.py

remote: make `copy` links atomic for local/hdfs/ssh

---

dvc/remote/gdrive.py

Fixes #2947
I don't see any sanity checks.

remote: use absolute from root for gdrive credentials file

---

dvc/cache.py
dvc/daemon.py
dvc/logger.py
dvc/path_info.py
dvc/rwlock.py
dvc/scm/git/__init__.py
dvc/stage.py
dvc/utils/__init__.py
dvc/utils/compat.py
dvc/version.py
tests/conftest.py
tests/unit/test_version.py

Related: #1818 
Include some comments from: https://github.com/iterative/dvc/pull/3024

py3: remove methods for casting bytes in python 2

---

dvc/stage.py

fix for base None value

---

dvc/api.py
dvc/config.py
dvc/exceptions.py
dvc/logger.py
dvc/remote/base.py
dvc/remote/gdrive.py
dvc/remote/s3.py
dvc/remote/ssh/connection.py
dvc/repo/__init__.py
dvc/repo/checkout.py
dvc/repo/reproduce.py
dvc/rwlock.py
dvc/scm/base.py
dvc/scm/git/__init__.py
dvc/scm/git/tree.py
dvc/stage.py
dvc/system.py
dvc/utils/stage.py
tests/func/test_checkout.py
tests/unit/test_logger.py

py3: refactor exceptions

---

tests/func/test_data_cloud.py
tests/remotes.py

test: add _should_test_gdrive and _get_gdrive_url inside GDrive

---

scripts/completion/dvc.zsh

Close #2983
My apologies, @jorgeorpinel, missed it from the review.

completion: fix --relink problem

---

tests/unit/test_analytics.py

analytics: tests: migrate to dir helpers

---

tests/func/test_dependency.py

dependency: test: migrate to dir helpers

---

setup.py

setup: get rid of py2 reqs

---

tests/func/test_output.py

output: tests: migrate to dir helpers

---

dvc/command/imp.py

add space for import help text

---

tests/func/test_external_repo.py

tests: external_repo: convert to dir helpers

---

tests/func/test_init.py

test: init: convert to dir helpers

---

tests/func/test_get_url.py

test: get_url: convert to dir helpers

---

dvc/repo/get.py

get: refactor handling of git files and git-only repos

---

tests/func/test_scm.py

test: scm: convert to dir helpers

---

dvc/remote/config.py
tests/func/test_remote.py

remote: error out when modifying a non-existing remote

---

tests/unit/output/test_local.py

tests: local: unit: migrate to dir helpers

---

tests/unit/test_stage.py

stage: tests: unit: migrate to dir helpers

---

tests/unit/command/test_update.py

update: tests: unit: migrate to dir helpers

---

tests/unit/command/test_run.py

tests: run: unit: migrate to dir helpers

---

tests/unit/command/test_repro.py

tests: repro: unit: migrate to dir helpers

---

tests/unit/remote/ssh/test_connection.py

connection: test: unit: remove repo_dir

---

tests/unit/remote/ssh/test_ssh.py
tests/unit/utils/test_utils.py

ssh: test: unit, utils: test: unit: remove repo_dir

---

tests/unit/utils/test_fs.py

fs: tests: remove repo_dir

---

tests/func/test_data_cloud.py

test: use helper remotes in child classes of TestDataCloudCLIBase

---

tests/func/test_repro.py

Last PR for #2878. Closes #2878

test: use helper remotes in external repro

---

.travis.yml

travis: build snap in parallel with other packages

---

dvc/dependency/repo.py
tests/func/test_import.py
tests/func/test_update.py

Related to #3087
Unblocking https://github.com/iterative/dvc/pull/3150

import: don't forget to set rev_lock for git files

---

dvc/remote/gdrive.py

Fix gdrive multiple parents file list query

---

scripts/ci/deploy_condition.sh

minor comments

---

dvc/exceptions.py

exception: fix spelling

---

dvc/command/get.py
dvc/command/imp.py

> Per https://github.com/iterative/dvc/issues/3196#issuecomment-577306219
Fixes #3196

get/imp: update help output descriptions

---

tests/func/test_import_url.py

import-url: test: prevent in-repo testing

---

dvc/external_repo.py
tests/func/test_external_repo.py
tests/func/test_status.py
tests/func/test_update.py

erepo: pull each time

---

dvc/remote/gdrive.py

gdrive: Init drive if corpora property value requested.

---

dvc/external_repo.py
tests/func/test_external_repo.py

erepo: fix known sha handling

---

dvc/command/daemon.py

daemon config fix

---

dvc/remote/base.py

checkout: change loglevel to debug and simplifymessage

---

tests/func/test_repro.py

https://travis-ci.com/iterative/dvc/jobs/288986376
https://travis-ci.com/iterative/dvc/jobs/288986376

test: repro: prevent dvc.stages resetting

---

dvc/command/metrics.py

Matches iterative/dvc.org/pull/1014
> per https://github.com/iterative/dvc.org/pull/1014/commits/2c3452119545987f77b764e4aa6fc94d051092a7

metrics show: update -h output to match docs

---

dvc/remote/gdrive.py

Fixes https://github.com/iterative/dvc/issues/3457
----------------

gdrive: share drive vs just folder id when we set corpora param

---

setup.py

deps: upgrade jsonpath_ng to latest version

---

tests/dir_helpers.py
tests/func/test_ls.py

tests: add .gitignore files when upon dvc_add

---

dvc/repo/__init__.py
tests/unit/repo/test_repo.py

Should help with #2671 for commands like `push/pull/checkout` when particular stage file is specified directly.

dvc: optimize all target specific commands to not build graph

---

dvc/exceptions.py
dvc/repo/__init__.py
dvc/repo/reproduce.py

From https://github.com/iterative/dvc/pull/3363/files#r382117306

exceptions: use semantic exceptions

---

dvc/command/version.py
dvc/remote/base.py
tests/func/test_version.py

Since our remotes have optional dependencies, it is really useful to be
able to see what is currently supported. Also helps debug issues with
packages such as brew/conda/etc.

version: add supported remotes

---

dvc/repo/gc.py
dvc/repo/init.py
dvc/repo/reproduce.py
dvc/repo/status.py
tests/func/test_gc.py

Per https://discordapp.com/channels/485586884165107732/563406153334128681/689896480898810034

dvc: use consistent messages for InvalidArgumentError

---

dvc/command/pipeline.py
tests/func/test_pipeline.py

pipeline: fix `--outs` output

---

dvc/command/checkout.py
tests/unit/command/test_checkout.py

pull/checkout: fix empty log output if no state gets changed

---

dvc/config.py
dvc/remote/gdrive.py
setup.py

gdrive: config option to move remote file to trash only

---

dvc/repo/metrics/diff.py
tests/func/test_metrics.py

metrics: diff: fix bug with unchanged raw metrics

---

dvc/remote/local.py
tests/unit/remote/test_local.py

protect: ignore EROFS

---

dvc/stage.py

message: change already exists message

---

dvc/progress.py
dvc/remote/base.py
dvc/remote/http.py
dvc/utils/fs.py

+ closes #3521
+ [x] add `wrap_fn` helper
+ [x] use `wrapattr` and `wrap_fn` in all appropriate places
- related tqdm/tqdm#583

progress: wrappers

---

.travis.yml

- fixes #3550
- continues #3547

snap: deploy: fix authentication

---

dvc/remote/gdrive.py
tests/func/test_data_cloud.py
tests/unit/remote/test_gdrive.py

Partially addresses https://github.com/iterative/dvc/issues/2865
-------------

gdrive: method signatures cleanup, more safeguards

---

dvc/command/data_sync.py
scripts/completion/dvc.zsh

"pull from subdirectories" seems misleading. The pull happens from a remote.

pull: update help output (-R option)

---

dvc/system.py

Only import speedcopy on Win > 7

---

tests/func/test_diff.py

Fixed test_directories test in tests/func/test_diff.py

tests: test_directories

---

dvc/remote/base.py

gc: don't forget to load remote index

---

dvc/stage/cache.py
tests/func/test_repro.py

stage: rename `.dvc/cache/stages` -> `.dvc/cache/run`

---

dvc/stage/loader.py

Import ABC from collections.abc for Python 3 compatibility.

---

dvc/repo/imp_url.py
tests/func/test_import.py

import: check erepo is None before modifying url - fixes #3780

---

dvc/repo/checkout.py
dvc/repo/fetch.py
dvc/repo/pull.py
dvc/repo/push.py
dvc/repo/status.py

refactor: check if targets is instances of str

---

scripts/completion/dvc.bash
scripts/completion/dvc.zsh

Part of #3690
Partially fixes #3641

diff: autocompletion script for params, and show-md

---

dvc/repo/checkout.py
dvc/repo/commit.py
dvc/stage/__init__.py
dvc/stage/run.py

refactor: simplify checkouts and run, get rid of check_can_commit

---

dvc/stage/__init__.py
tests/func/test_commit.py

stage: fix commit

---

dvc/repo/reproduce.py

Part of https://github.com/iterative/dvc/issues/3777

repro: do not log when stage is locked and is import

---

dvc/command/base.py

Part of https://github.com/iterative/dvc/issues/3777

default target: reduce loglevel to debug

---

dvc/repo/plots/template.py

Newline at the end of template files on init

---

dvc/lock.py

lock: make froze message clickable

---

dvc/remote/base.py
tests/unit/remote/test_base.py

remote: is_dir_checksum: handle empty/None checksum

---

dvc/output/base.py
tests/func/test_add.py

dvc: don't write default values for cache/persist/metric

---

dvc/command/plots.py

plot: fixup for template help message

---

dvc/remote/azure.py
tests/unit/remote/test_azure.py

azure: drop obsoleted url format

---

dvc/remote/local.py
tests/func/test_remote.py

remote: local: protect uploaded files

---

dvc/dvcfile.py
dvc/repo/run.py
dvc/serialize.py
tests/func/test_run_multistage.py

dvcfile: serialize params on --no-exec

---

dvc/remote/hdfs.py
dvc/remote/local.py
dvc/remote/ssh/__init__.py
scripts/ci/before_install.sh
scripts/ci/install_azurite.sh
setup.py
tests/func/test_repro.py
tests/unit/remote/test_azure.py

test: fix hdfs/azurite/oss tests

---

dvc/stage/cache.py
tests/unit/stage/test_cache.py

run-cache: don't forget to set wdir

---

dvc/ignore.py
tests/func/test_stage.py

dvcignore: fix bug in subrepo detection

---

dvc/remote/gdrive.py

_credentials_location  to credentials_location to remove attributeerror.  Closes #3877 

Bugfix:  _credentials_location

---

dvc/ignore.py
tests/func/test_ignore.py

dvcignore: use correct root .dvcignore for subrepos

---

tests/conftest.py

tests: make ssh_server session scoped

---

setup.py

use fork of mockssh-server

---

dvc/repo/plots/__init__.py

- no error when modifying plot with no props yet
- do not turn into non-plot if all props are unset

Fix modifying plot

---

dvc/command/remote.py
tests/func/test_remote.py

https://discordapp.com/channels/485586884165107732/563406153334128681/717474697721413686
Fixes https://github.com/iterative/dvc/issues/3938
TODO:

remote: modify: fix --unset

---

scripts/hooks/hook-pydrive2.py

pyinstaller: add hook for google-api-python-client

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

issue template: do not auto-add labels on new issues

---

dvc/dvcfile.py

log: show modifying if entry already exists in dvcfile

---

dvc/remote/base.py
dvc/remote/local.py

Moving ignore logic to the remote itself, so that tree could behave
properly.
Related to #3897

remote: tree: don't ignore exceptions

---

scripts/ci/install.sh
setup.py

https://github.com/carletes/mock-ssh-server/pull/16 got merged. Updating ...
Related #3888

tests: update mock ssh server

---

setup.py

remove unnecessary dependencies

---

dvc/command/plots.py

Per https://github.com/iterative/dvc/pull/3911#discussion_r436238442 and https://github.com/iterative/dvc/pull/3948

plots: fix help message

---

dvc/repo/plots/data.py
tests/func/plots/test_plots.py

plots: find metric data in yaml dictionary

---

dvc/command/config.py

https://github.com/iterative/dvc.org/pull/1416

config/remote/cache: make --system/--global/--local mutually exclusive

---

dvc/dvcfile.py
tests/func/test_dvcfile.py

dvc.yaml: preserve meta

---

dvc/repo/plots/__init__.py

- running .plots.collect() not from repo root used to skip plot files
- make Plots.render() be more convenient to be called from outside

plots: fix a couple of bugs

---

dvc/daemon.py

#4021, do not make config directory world writeable

---

dvc/repo/plots/__init__.py
tests/func/plots/test_plots.py

plots: fix handling of multiple plots from single revision

---

dvc/command/dag.py

fix error message on dag.py

---

dvc/command/metrics.py
tests/func/metrics/test_diff.py
tests/unit/command/test_metrics.py

Rounding to 5 digits by default.
Fixes #3904
https://github.com/iterative/dvc.org/pull/1430

metrics: diff: introduce --precision

---

dvc/repo/plots/template.py
tests/func/plots/test_plots.py

Fixes #3969
https://github.com/iterative/dvc.org/pull/1436

plots: make sure template is using data anchor

---

dvc/repo/plots/__init__.py
dvc/repo/plots/template.py

Removing any sign of hard-coded anchors on the template side.

plots: clean up template anchors and collection

---

dvc/ignore.py
tests/func/test_ignore.py

dvcignore: ignore empty (None) patterns

---

.pre-commit-config.yaml
dvc/command/diff.py
dvc/dagascii.py
dvc/remote/ssh/connection.py
dvc/repo/__init__.py
dvc/repo/plots/data.py
dvc/repo/tree.py
dvc/scm/git/__init__.py
dvc/scm/tree.py
dvc/stage/serialize.py
setup.cfg
setup.py
tests/func/test_dvcfile.py
tests/func/test_gc.py

This PR adds flake8 extensions:
1. [flake8-bugbear](https://pypi.org/project/flake8-bugbear)
2. [flake8-comprehensions](flake8-comprehensions)
3. [flake8-debugger](https://pypi.org/project/flake8-debugger/)
4. [flake8-string-format](https://pypi.org/project/flake8-string-format)
Also, I have added complexity config with reasonable defaults to 15.

Add flake8 extensions

---

.codeclimate.yml
.deepsource.toml

adjust codeclimate config

---

dvc/scm/git/tree.py

git: make git_object_by_path private

---

dvc/command/data_sync.py

Related to https://github.com/iterative/dvc.org/issues/1289
https://github.com/iterative/dvc.org/pull/1481

push/pull/fetch: unhide --run-cache

---

dvc/command/git_hook.py
tests/unit/command/test_git_hook.py

git-hook: don't run when not in dvc repo

---

dvc/command/remove.py

Fixes #4094 
Issue for documentation: https://github.com/iterative/dvc.org/issues/1490

ui: remove: .gitignore in cmd description

---

dvc/command/freeze.py

Related to #4024, https://github.com/iterative/dvc.org/pull/1493

un/freeze: adjust stage naming to 1.0

---

dvc/remote/local.py
tests/func/test_data_cloud.py

tests: data_cloud: migrate the leftovers to pytest

---

dvc/utils/diff.py
tests/unit/command/test_diff.py
tests/unit/command/test_metrics.py
tests/unit/command/test_params.py

To finalize md table.
Fixes #4123

dvc: add trailing newline in --show-md

---

README.rst

Moving the most important widgets on the front

Reorder package widgets

---

dvc/remote/gdrive.py

https://travis-ci.com/github/iterative/dvc/jobs/357157580#L8485

gdrive: pop prefix kwarg

---

tests/utils/httpd.py

tests: http: fix typo

---

setup.py

To avoid conflict with https://github.com/aws-cloudformation/cfn-python-lint

Bump networkx

---

tests/remotes/__init__.py

https://travis-ci.com/github/iterative/dvc/jobs/364061489#L3623

tests: check if docker is present
