iterative/dvc

- dvc/external_repo.py
- dvc/scm/git.py
- tests/func/test_external_repo.py
Follow up to #3585.
Should fix #3473.
* erepo now clones with `--no-single-branch --depth=1 --branch=<branch>` when initialized with a valid branch or tag name (i.e. for `get/import --rev`)
* if erepo is init'd with `for_write=True` (i.e. dvcx) we use the old full clone + writeable copy behavior
* If shallow clone fails, we fallback to default full clone behavior
* If we reuse an already cloned repo and don't have the necessary revision, we expand the clone with `git fetch --unshallow` and then treat it like normal full clone
This does not address these other potential changes to erepo clone behavior:
* persistent cache #3496 
* sparse checkouts #3438
> erepo: --rev BRANCH: shallow clone

- dvc/daemon.py
We used `Popen` just to provide a general way of launching our daemons
on both Windows and *nix, but it is causing us issues when dvc is
launched from some exotic places (like nix package) or through `main()`
helper from a script that is not dvc.
This patch makes us just use `main()` directly in our double-forked
process.
Windows implementation has to use the `Popen` mechanism, because this is
the only way to daemonize a process on Windows. This means that dvc on
Windows is still susceptible to this problem, but there is nothing we
can do about it right now :(
Fixes #4206
Fixes #4165
> daemon: don't use Popen on linux/mac

- dvc/ignore.py
- dvc/tree/git.py
- dvc/tree/local.py
> ignore: use `use_dvcignore` flag

- dvc/utils/fs.py
- tests/func/test_add.py
> dvc: properly handle relative symlinks

- dvc/dependency/param.py
- dvc/repo/params/show.py
- setup.cfg
- setup.py
- tests/func/params/test_show.py
- tests/unit/dependency/test_params.py
We've been testing DVC with a few of our projects and for some of those we use a toml config to store parameters.
This PR adds support for parameters file in toml format. Example:
```
dvc run -n train                      \
-d data/input.csv                   \
-o model/model.h5                \
-M model/train_history.csv   \
-p params.toml:model.training \
python train.py
```
Where `params.toml` looks something like this:
> [transformers.numerical_quantile_transformer]
> n_quantiles = 300
> output_distribution = "uniform"
> 
> [model.training]
> epochs = 50
> verbose = 1
> add toml support for ParamsDependency

- dvc/ignore.py
This allows us avoid collecting dvcignore for the whole repo if we only 
care about particular paths. As a result, in a repo with 2 datasets     
(2M + 0.5M files), creating a defunct stage takes ~4sec on 1.2.0, but   
~1sec(most of it is actually dvc module initialization) with this PR.   
This is also a pre-requisite for dynamic dvcignore and subrepo          
collection (https://github.com/iterative/dvc/pull/4247) while walking   
the tree.                                                               
Also, it is important to clarify that regular `dvc status`(without      
arguments) has the same performance after this PR, because when we check
dataset for changes, we call things like `tree.exists()`, which call    
dvcignore and make it collect dvcignore in the dataset itself, so we …
> ignore: dynamically collect dvcignore

- dvc/command/experiments.py
Disables color/formatting styles in `experiments show` for now since it's not needed for testing/development and the current hard coded settings don't work for everyone.
Will be re-enabled later once we can do proper terminal settings detection.
> experiments: temporarily disable styling in `show` table

- dvc/daemon.py
Turns out macs are not happy with double-forks without exec.
Fixes #4294
> daemon: use Popen on Mac

- dvc/tree/gdrive.py
- setup.py
Better to solve it on PyDrive's side:
https://github.com/iterative/dvc/issues/4286
Fixes #4286
> gdrive: add workaround for downloading empty files

- setup.py
https://github.com/pytest-dev/pytest/issues/7558
pylint throws error for `pytest.mark.*` functions in pytest6.
```
tests/unit/repo/test_repo.py:15:1: E1102: pytest.mark.parametrize is not callable (not-callable)
tests/unit/repo/test_repo.py:33:1: E1102: pytest.mark.parametrize is not callable (not-callable)
************* Module tests.unit.remote.ssh.test_connection
tests/unit/remote/ssh/test_connection.py:87:1: E1102: pytest.mark.skipif is not callable (not-callable)
tests/unit/remote/ssh/test_connection.py:100:1: E1102: pytest.mark.skipif is not callable (not-callable)
```
https://github.com/iterative/dvc/pull/4257#issuecomment-665474467
> Exclude pylint==6.0 

- dvc/command/experiments.py
- dvc/command/repro.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
- dvc/repo/experiments/show.py
- dvc/repo/reproduce.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_repro.py
Related to #2799.
* Adds local temp directory executor and support for running experiments in parallel.
* Only `dvc repro` is currently supported
* Individual `dvc run` stages within a single `repro` command cannot be run in parallel
* `dvc repro --experiment --queue` can be used to add an experiment to the execution queue
* `dvc repro --run-all` will run all experiments currently in the queue
* `-j/--jobs` can be used to run experiments in parallel, currently defaults to 1 (run sequentially), will need to decide if we should default to cpu count for this?
* Queued experiments are listed in `dvc exp show` and denoted with `*`
Next steps:
* Reorganize executor output collection (currently collection is done …
> experiments: support local parallel execution in temp directories

- dvc/config.py
- dvc/exceptions.py
- dvc/path_info.py
- dvc/scheme.py
- dvc/tree/__init__.py
- dvc/tree/webdav.py
- dvc/tree/webdavs.py
- setup.py
- tests/unit/remote/test_webdav.py
Should fix #1153
Took WebDAVURLInfo from #3647
Relates to https://github.com/iterative/dvc.org/pull/1617
> tree,remote: add support for WebDAV

- dvc/main.py
- tests/func/test_status.py
Part of the issue is a bug from #3806                            
Kudos to @karajan1001 for finding this bug while working on #4282
> dvc: fix --quiet mode

- dvc/dependency/repo.py
- dvc/output/base.py
- dvc/stage/__init__.py
- tests/func/test_commit.py
> commit: make sure deps/outs exist

- setup.py
pytest 6.0.0 had issue with `pylint`, complaining for `pytest.mark.*` being `not-callable`. Ref: https://github.com/pytest-dev/pytest/issues/7558
[pytest6.0.1 has just been released](https://github.com/pytest-dev/pytest/releases/tag/6.0.1).
> Update pytest to >=6.0.1

- dvc/cache/base.py
- dvc/external_repo.py
- dvc/repo/tree.py
- dvc/tree/base.py
- tests/func/test_tree.py
> tree: get rid of explicit tree arguments

- dvc/command/remote.py
- dvc/config.py
- tests/func/test_remote.py
> remote: allow local options for repo remotes

- dvc/tree/base.py
We already do this in
https://github.com/iterative/dvc/blob/00de04c82d844b3bdf5162b2c78560f1b5656488/dvc/tree/base.py#L271
for both files and directories.
> tree: don't save hash twice

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
Should fix #4289.
* No longer use `git reset --hard` when doing checkout.
* Changes from the experiment commit are preferred over workspace changes, but all other unrelated and unstaged/uncommitted workspace changes will now be preserved after `dvc experiments checkout`
> experiments: more intelligent checkout behavior

- tests/func/test_version.py
Tests had checks for python version number, expecting it to be only
single digits, which was failing for me on 3.6.10 and might fail
in the future with Python 3.10.
I adjusted it to expect minor and patch version to be of multiple digits.
> tests: fix regex

- dvc/command/experiments.py
`dvc exp show --no-pager` can be used to output the `show` table directly to console instead of through the pager. Behaves the same as `git --no-pager`.
By default, if the console isn't wide enough to display the full table, params columns will be truncated first, giving priority to display the full experiment SHA and resulting metrics. In the future we should probably have options to only show certain metrics/params columns so that we don't need to truncate anything.
> experiments: add --no-pager option for `dvc exp show`

- dvc/repo/imp_url.py
- dvc/utils/__init__.py
- tests/func/test_import.py
Fixes #4169.
Makes `dvc import ... -o subdir/file` behave the same whether or not `subdir` already exists (new output will be `subdir/file.dvc`)
docs: https://github.com/iterative/dvc.org/pull/1668
> import: fix importing into subdirectory bug

- dvc/config.py
- tests/unit/test_config.py
config: use wtree for non-repo configs                                                  
For example, when `dvc import`ing something, dvc won't see stuff                        
declared in system and global configs, because GitTree doesn't see stuff                
that is outside of the git repo.                                                        
Discord context:                                                                        
https://discordapp.com/channels/485586884165107732/563406153334128681/740543492417126521
> config: use wtree for non-repo configs

- dvc/stage/__init__.py
- scripts/innosetup/config.ini
> repro: update status message for dvc-added files

- dvc/command/repro.py
- dvc/exceptions.py
- dvc/repo/experiments/__init__.py
- dvc/repo/reproduce.py
- dvc/utils/toml.py
- tests/unit/command/test_repro.py
Related to #2799.
Adds `dvc repro -e --params` option which can be used to specify experiment parameters via the command line.
* `--params` expects a comma-separated `key=value` list: `[params.yaml:]foo=1,stage.bar=2,stage.baz=1.234,...`
* Filename is optional, if omitted the default params file will be used
* Specified params are used *in addition* to any changes made in the user's current workspace, but command line values take priority over workspace changes.
* `-p` cannot be used to specify params in this way since it collides with `repro --pipeline`
* Currently only accepts single values per parameter (so you cannot specify multiple values to test at once for hyper parameter search yet)
Known limitations: …
> experiments: support `dvc repro --exp` command line params

- dvc/command/check_ignore.py
- dvc/prompt.py
- tests/func/test_check_ignore.py
Fix #4321
Introduce new arguments --all for dvc check-ignore
Add tests for dvc check-ignore --all
> Two new modes `--all` and `--stdin` for check-ignore

- dvc/ignore.py
- dvc/tree/git.py
- dvc/tree/local.py
- dvc/utils/collections.py
- tests/dir_helpers.py
- tests/func/test_ignore.py
- tests/func/test_tree.py
Part of #3369
I implemented this inside dvcignore, and it
should not require "internal" APIs hack as we discussed before.
Right now, `ignore_subrepos` will only work for the paths of subrepo,
not anything inside it. And the API user is more or less only
RepoTree, so should be safe (we switch DvcTree and repo.tree based
on path prefixes, so this is only required during `walk`, so as it
shows the repo that were previously dvcignored and so that we could
switch the trees later during walk.
So, if dir is `dir -> repo`
So, `tree.walk("dir")` will return `[]`,
whereas `tree.walk("dir", ignore_subrepos=False)` will return `["repo"]`
But, successive walk will just return `("repo", [], [])`, and could
just be ignored as …
> dvcignore: api to unhide subrepos directory

- dvc/utils/pager.py
* Enables support for ANSI terminal color escape sequences in `less` (needed eventually for experiments)
> pager: use --R/--RAW-CONTROL-CHARS with less

- dvc/command/check_ignore.py
fix #4361
1. Remove error message when input a empty string
2. Remove error message when read input from stream
3. Remove error message when interrupt by `CTRL-C`
> Remove error message when exiting `--stdin` mode

- dvc/config.py
- dvc/updater.py
- tests/unit/test_updater.py
Fixes  #1894 
Approach:
- Add core config key `check_update` with default value `true`.
- Updater will skip checking if the flag is disabled.
> Config to enable/disable updater 

- dvc/main.py
- tests/func/test_check_ignore.py
Thanks to @skshetry 's suggestions. A quick but might temporarily fix, is there any better solution?
fix #4351 
1. remove error message when no match found.
> Error message when no match found.

- dvc/cache/local.py
- tests/func/test_remote.py
Fixes #4343.
If a directory has files missing in both local cache and on the remote, we should still try to push the files we have locally, but should not push the `.dir` file. Otherwise, index will think the full directory is present in the remote after the partial push.
> push: do not push .dir file for directory with missing files

- dvc/command/check_ignore.py
per https://github.com/iterative/dvc/pull/4282#pullrequestreview-460270636
and https://github.com/iterative/dvc/pull/4282#pullrequestreview-460272287
iterative/dvc/pull/1673
> check-ignore: update help output

- dvc/repo/__init__.py
- tests/func/test_tree.py
fix #3869
Repo `add`,`checkout`,etc will not change `.dvcignore`, and can remove dvcignore reset after these operations.
No performance improvement in `dvc status`(only influence commands using `repo._reset()`) 
@pared  Excuse me, my `dvc add` tests failed.
On origin/master, clone the local repo to `./` then edit `hashes.txt` manually and run `asv run HASHFILE:hashes.txt`. And these is my error message.
> Remove dvcignore reset in `repo._reset`

- dvc/tree/azure.py
- setup.py
- tests/remotes/azure.py
- tests/unit/remote/test_azure.py
There has been some pretty drastic changes in 12.0, so migration
is a little bit more involved.
Fixes #3546
> dvc: migrate to azure-storage-blob >= 12.0

- dvc/command/get_url.py
- dvc/command/imp_url.py
- dvc/command/remote.py
I try but #4357
This matches iterative/dvc.org/pull/1680, actually.
> term: review "URL" term usage in remote cmds, and get/import-url

- dvc/command/experiments.py
Related to #4346
* Adds `--include-metrics/--exclude-metrics` and `--include-params/--exclude-params` options to `dvc exp show`.
* Options take comma-separated list of metrics/params columns to include or exclude from the output table.
* If `--include...` is used, only columns specified in the list will be displayed. If `--exclude...` is used, all columns except those specified in the list will be displayed.
* Matches nested metrics/params, so `--include-params featurize` will match `featurize.max_features`, `featurize.ngrams`, etc
* Params and metrics columns lists are handled separately, so `dvc exp show --include-params=foo` will display all metrics columns plus the single param column `foo`.
> experiments: add options to include/exclude columns in `exp show`

- dvc/ignore.py
- tests/func/test_ignore.py
Fix #4333, as `is_ignored_file` and `is_ignored_dir` and `__call__`
share the same call `DvcIgnorePatterns.matches`, we only need to focus
on the out of repo situation.
1. Add tests for the `is_ignored_file` and `is_ignored_dir` for the out
of repo condition.
2. Now `is_ignored_file` and `is_ignored_dir` returns false for those
files outside the repo.
> Solve result inconsistency of the DvcIgnoreFilter

- dvc/tree/http.py
- dvc/tree/webdav.py
> get-url: allow weak etag

- dvc/exceptions.py
The default error message is often invoked from running `dvc pull` and
in this case it is generally caused by not pushing to the remote. I
spent some time thinking about a replacement message and this seems to
be the most appropriate text I could think of.
Fixes #4316
https://github.com/iterative/dvc.org/issues/1660
> exception text: clarify error message

- dvc/ignore.py
- dvc/output/base.py
- tests/func/test_ignore.py
- tests/unit/output/test_output.py
> outputs: validate that output is not ignored

- dvc/path_info.py
Unused, empty http extra parts (params,query,fragment) cause problems
with pushing/pulling - lead to violation of the assumption where to look
for hash values in file/path names.
Context:
https://discordapp.com/channels/485586884165107732/485596304961962003/743454659733094520
https://discordapp.com/channels/485586884165107732/485596304961962003/743497749290287215
https://discordapp.com/channels/485586884165107732/485596304961962003/743571921622401136
> Derive WebDAVURLInfo from URLInfo instead of HTTPURLInfo

- dvc/repo/ls.py
- dvc/repo/tree.py
- dvc/tree/git.py
- dvc/tree/local.py
- tests/func/test_ignore.py
- tests/func/test_tree.py
- tests/unit/repo/test_repo_tree.py
Right now, no actual "functionality" is surfaced as
`subrepos` is always set to False by default for now.
Subrepos are collected dynamically and trie is created to track those repos inside `RepoTree`, and this does not incur any cost
as `.dvcignore` is shared among subrepos and `RepoTree` just utilizes them.
1. Create "MotherOfTree" that will be prefix-based and can switch between those just based on prefix. So, some separate tree class that works on top of RepoTree or  GitTree for submodules.
cons: Hard to traverse, especially heirarchial traversal required for dvc repos, etc.
> RepoTree: add support for subrepo traversal

- tests/unit/repo/test_repo_tree.py
Since #4229, we have started creating .dvcignore file after `dvc init`
This commit only adds that in assertions
> tests: add .dvcignore on the tests expectations

- dvc/cache/base.py
- dvc/cache/local.py
- dvc/dependency/repo.py
- dvc/output/base.py
- dvc/repo/diff.py
- dvc/repo/tree.py
- dvc/tree/azure.py
- dvc/tree/base.py
- dvc/tree/gs.py
- dvc/tree/hdfs.py
- dvc/tree/http.py
- dvc/tree/local.py
- dvc/tree/s3.py
- dvc/tree/ssh/__init__.py
- dvc/tree/webdav.py
- tests/func/test_tree.py
- tests/unit/remote/test_azure.py
Currently we kinda assume that whatever is returned by `get_file_hash`
is of type self.PARAM_CHECKSUM, which is not actually true. E.g. for
http it might return `etag` or `md5`, but we don't distinguish between
those and call both `etag`. This is becoming more relevant for dir
hashes that are computed a few different ways (e.g. in-memory md5 or
upload to remote and get etag for the dir file).
Prerequisite for #4144 and #3069
> tree: make get_hash return type and hash pair

- dvc/command/data_sync.py
- dvc/command/gc.py
Fixes #1310 
I don't think that documentation should be updated.
> ui: '-j' option now mentions docs

- .pre-commit-config.yaml
- dvc/repo/plots/data.py
- setup.py
- tests/remotes/__init__.py
There are some false positives in the older versions, particularly regarding type annotations that are blocking my other PR.
Also, there were some false negatives that seem to have been fixed, which has been adjusted.
> update flake8 to latest version

- dvc/command/check_ignore.py
- tests/func/test_check_ignore.py
fix #4407
1. Update test, now it can simulate a pipeline situation.
2. Solve remove `isatty` check in `dvc check-ignore --stdin` command.
> Solve check-ignore broken in a Linux pipeline

- dvc/repo/ls.py
- dvc/repo/tree.py
1. Rename `_get_tree_pairs` to `_get_tree_pair`. (addresses https://github.com/iterative/dvc/pull/4381#discussion_r469883810)
2. Add comments, docstrings and type-annotations. (addresses https://github.com/iterative/dvc/pull/4381#pullrequestreview-467470585)
3. Rename variable: `_discovered_subrepos` to `_subrepos_trie`.
4. Merge some nested ifs.
~~On top of #4403, will rebase after it's merged. See 9391f5b for review.~~
EDIT: Rebased
> cleanup RepoTree

- dvc/command/experiments.py
- dvc/repo/experiments/show.py
- tests/func/experiments/test_show.py
* Currently includes timestamps by default with a `--no-timestamp` option to hide them in the table output, not sure if this should be reversed for the default behavior?
```
❯ dvc exp show --no-pager --include-params=featurize
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ Experiment                        ┃     auc ┃ featurize.max_features ┃ featurize.ngrams ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ workspace                         │ 0.61314 │ 1500                   │ 2                │
│ acd59eb (2020-07-22 15:19:27)     │ 0.61314 │ 1500                   │ 2                │
│ ├── be1e801 (2020-08-11 …
```
> experiments: include experiment timestamps in `dvc exp show` output

- dvc/exceptions.py
- dvc/repo/metrics/show.py
> metrics: show: debug info on parsing problems

- dvc/repo/status.py
- tests/func/test_data_cloud.py
Fixes #4383
https://github.com/iterative/dvc.org/issues/1701
**P.S.:** I have also updated tests to make sure if targets missing both in cache and remote are handled properly bit these updates are dirty. So please inform me if there is a better way to implement them.
> status: check if target is missing both in cache and remote

- dvc/tree/http.py
> tree: http: try GET on failed HEAD

- dvc/scm/git.py
GitPython raises ValueError if `git rev-parse` is called with something that looks like an actual git SHA but does not match any known Git commits/objects. (this will happen if experiments workspace needs to be updated because the SHA is a commit from the parent repo and has not been pulled into the experiments repo yet)
> git: handle rev_parse exception

- dvc/cache/base.py
- dvc/command/git_hook.py
- dvc/dvcfile.py
- dvc/exceptions.py
- dvc/output/base.py
- dvc/scm/git.py
- dvc/stage/__init__.py
- dvc/tree/base.py
- setup.py
- tests/func/test_install.py
- tests/func/test_merge_driver.py
> dvc: introduce merge-driver

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
* Executors return a list of output paths via `executor.collect_output()`
* Collected paths should then be downloaded to experiments workspace with `local_tree.download(...)`
still need to investigate why stages aren't pickable/returnable across multiprocessing calls, but any changes related to that will probably come in a future PR
> experiments: abstract executor output collection using trees

- dvc/dependency/param.py
- dvc/exceptions.py
- dvc/repo/metrics/show.py
- dvc/repo/params/show.py
- dvc/repo/plots/data.py
- dvc/repo/reproduce.py
- dvc/scm/git.py
- dvc/stage/cache.py
- dvc/utils/__init__.py
- dvc/utils/serialize/__init__.py
- dvc/utils/serialize/_common.py
- dvc/utils/serialize/_toml.py
- dvc/utils/serialize/_yaml.py
- setup.py
- tests/func/metrics/test_diff.py
- tests/func/plots/test_plots.py
- tests/func/test_add.py
- tests/func/test_lockfile.py
- tests/func/test_repro_multistage.py
- tests/func/test_run_multistage.py
- tests/unit/dependency/test_params.py
- tests/unit/test_lockfile.py
This PR:
* gets rid of pyyaml
* uses ruamel everywhere
* tries to unite toml and yaml
https://github.com/iterative/dvc.org/issues/1704
Closes #4281
> Move to yaml1.2

- tests/func/test_install.py
The tests started to ask for gpg signoff. Could this be done without `git`?
Refer https://git-scm.com/docs/git-merge#Documentation/git-merge.txt---no-gpg-sign
> git: do not ask for gpg signoff on merge

- dvc/dependency/param.py
- dvc/dvcfile.py
- dvc/repo/metrics/show.py
- dvc/repo/params/show.py
- dvc/repo/plots/data.py
- dvc/utils/serialize/__init__.py
- dvc/utils/serialize/_common.py
- dvc/utils/serialize/_toml.py
- dvc/utils/serialize/_yaml.py
- tests/func/test_repro_multistage.py
* Also fixes plots not getting dumped on flow style
* Make serialization utils aware of trees
* Directly load yamls/tomls using utils, rather than using parser
On top of #4415, see https://github.com/iterative/dvc/pull/4415#discussion_r472113621
> Yaml with trees

- dvc/cli.py
- dvc/main.py
```console
$ dvc list . --cprofile
$ dvc list . --cprofile dvc.prof
```
Just a simple patch that I was using locally, thought I'd share.
Not available on Python3.6 :(. I'm fine keeping it just for me as well. :smile: 
And, that command feels like it's quite far.
> Enable profiling from cli

- dvc/dvcfile.py
- dvc/repo/experiments/__init__.py
- dvc/scm/git.py
- dvc/utils/serialize/__init__.py
- dvc/utils/serialize/_common.py
- dvc/utils/serialize/_toml.py
- dvc/utils/serialize/_yaml.py
Reduce boilerplate of create + load + dump during serialization/deserialization
```python
with modify_yaml(config_path, tree=repo.tree) as config:
config["repos"] = config.get("repos", [])
config["repos"].append(entry)
```
On top of #4425, see https://github.com/iterative/dvc/pull/4415#discussion_r472117862
> utils.serialize: modify_yaml contextmanager to reduce boilerplate

- dvc/command/diff.py
- tests/unit/command/test_diff.py
Fixes #4313 
PS: there may be scope for refactoring. Inputs are welcome ❗ 😄
> diff command: output in markdown format with hash

- dvc/repo/experiments/__init__.py
> experiments: support binary and untracked files in experiment patches

- dvc/tree/hdfs.py
- tests/func/test_import_url.py
> hdfs: implement isdir and isfile

- dvc/repo/status.py
- dvc/stage/__init__.py
- tests/func/test_status.py
fix #4191
1. Add a related test which would fail on current version.
> Outputs as target supporting for `dvc status`

- dvc/output/base.py
- dvc/stage/loader.py
- dvc/stage/serialize.py
- tests/func/test_run_cache.py
- tests/unit/stage/test_serialize_pipeline_lock.py
Prerequisite for #4144 and #3069
> output: dont rely on the default hash type

- dvc/external_repo.py
- dvc/tree/git.py
- setup.py
- tests/func/test_tree.py
See `._load()` implementation. Alternative is not using 3 io calls, but
simply use open and catch exceptions.
Reading is slow for old git revisions.
> Speed up dvc files load

- dvc/cache/local.py
- dvc/data_cloud.py
- dvc/repo/status.py
- tests/func/test_data_cloud.py
Fixes #4383 (again)
After  PR #4398 it occured, that `dvc status -c` output is bloated and informs about "missing" files twice (took from https://github.com/iterative/dvc/pull/4398#issuecomment-678673973):
> ```
> $ dvc status -c -R .
> WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
> name: data-in-cache2-not-in-remote.txt, md5: 599b9eea7a2c4f97be18c077d2df4789
> 	new:                data-in-cache-1-not-in-remote.txt
> 	missing:            data-in-cache-2-not-in-remote.txt
> ```
>If `missing` is now an expected status, the WARNING is probably no longer needed. So it could just output something like:
>
> ```
> $ dvc status -c  # Assumes default remote exists, otherwise -r myremote
> new:                data-in-cache-1-not-in-remote.txt
> …
```
> status: no warnings for missing state

- .github/release-drafter.yml
With this change, release-drafter will be able to categorically
write/create changelogs based on the labels.
Check this release which was generated by same config: https://github.com/skshetry/dvc/releases/tag/1.2.4
Fixes https://github.com/iterative/dvc/issues/4023
> changelog: categorize changelog entry using labels

- tests/func/test_lock.py
Patched to reduce timeout from default 5s to 0.01s
```console
$ pytest tests/func/test_lock.py
2 passed in 10.20s
```
```console
$ pytest tests/func/test_lock.py
2 passed in 0.20s
```
> tests: speedup lock tests

- dvc/config.py
- dvc/exceptions.py
- dvc/main.py
- dvc/tree/s3.py
- dvc/utils/__init__.py
- tests/func/test_s3.py
- tests/unit/remote/test_remote_tree.py
- tests/unit/tree/test_s3.py
> s3: provide more helpful messages on common errors

- dvc/command/plots.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/show.py
- dvc/repo/plots/__init__.py
- dvc/repo/plots/diff.py
- tests/func/experiments/test_experiments.py
- tests/unit/command/test_plots.py
- tests/unit/repo/plots/test_diff.py
Will close #4449.
* Regarding docs, this option is currently hidden from the help/usage output for `dvc plots diff` the same way that the option is hidden in `dvc repro`.
* By default, if a single experiment revision is provided, we will diff against the baseline/parent rev for that experiment, rather than diffing against HEAD/workspace.
> plots: add `dvc plots -e/--experiment` option

- dvc/cache/base.py
- dvc/cache/local.py
- dvc/dependency/repo.py
- dvc/hash_info.py
- dvc/output/base.py
- dvc/repo/diff.py
- dvc/tree/azure.py
- dvc/tree/base.py
- dvc/tree/dvc.py
- dvc/tree/gs.py
- dvc/tree/hdfs.py
- dvc/tree/http.py
- dvc/tree/local.py
- dvc/tree/repo.py
- dvc/tree/s3.py
- dvc/tree/ssh/__init__.py
- dvc/tree/webdav.py
- tests/func/test_tree.py
- tests/unit/remote/test_azure.py
- tests/unit/tree/test_dvc.py
- tests/unit/tree/test_repo.py
Initial implementation of HashInfo to avoid using explicit tuples and have a handier way of working with hashes (e.g. comparing hashes of different types).
Related to #4144 , #3069 , #1676
> dvc: use HashInfo

- dvc/command/destroy.py
- dvc/command/install.py
- dvc/command/status.py
- dvc/main.py
- tests/func/test_check_ignore.py
> dvc: show "Having any troubles?" only on unexpected errors 

- dvc/command/experiments.py
- dvc/repo/experiments/show.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_experiments.py
* Show git tag/branch names instead of SHAs where applicable
* SHAs can still be displayed using `dvc exp show --sha ...`
* Make timestamp formatting less verbose
```
❯ dvc exp show --all-commits --include-params=featurize --no-pager
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Experiment            ┃ Created      ┃     auc ┃ featurize.m… ┃ featurize.ng… ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ workspace             │ -            │ 0.50822 │ 1500         │ 4             │
│ executor-tree         │ 05:31 PM     │ 0.50822 │ 1500         │ 4             │
│ └── *41a9f4b          │ 05:34 PM     │       - │ 456          │ 5 …
```
> experiments: make `dvc exp show` more consistent w/viewer

- dvc/repo/status.py
- dvc/stage/__init__.py
- tests/func/test_status.py
fix #4482 
According to the discussion. Make `DVC status [outputs]` output format the same with `DVC status [stages]` instead of `DVC status -c [outputs]`
> Keep `status` output format consistents

- .gitignore
Currently `dvc/cache` is gitignored.
> gitignore: ignore /cache instead of cache

- dvc/command/experiments.py
Will close #4346.
* When using `--include-metrics/--include-params`, columns will be displayed left-to-right in the order specified by the `--include` option.
* `--sort-by <column_name>` and `--sort-order asc|desc` can be used to sort related experiments on the specified metric or param column.
* Only nested experiments will be sorted, baseline (formal) commits will still be displayed in the git history order.
* `--sort-order` defaults to ascending
* Only sorting by a single column is supported
```
❯ dvc exp show --include-params=train.seed,featurize --sort-by=featurize.max_features --sort-order desc --all-commits --no-pager
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳ …
```
> experiments: support column ordering & sorting in `dvc exp show`

- dvc/cache/base.py
- dvc/dependency/param.py
- dvc/dependency/repo.py
- dvc/external_repo.py
- dvc/hash_info.py
- dvc/output/base.py
- dvc/stage/loader.py
- dvc/stage/serialize.py
- dvc/tree/base.py
- tests/func/test_add.py
- tests/func/test_run_cache.py
- tests/func/test_tree.py
- tests/unit/dependency/test_params.py
- tests/unit/output/test_load.py
- tests/unit/stage/test_loader_pipeline_file.py
- tests/unit/stage/test_serialize_pipeline_lock.py
By itself `self.info` is quite confusing, as it is not clear what it is
about. Using `hash_info` makes much more sense and is required to
support alternative hash types.
Related to #4144, #3069, #1676
> deps/outs: get rid of self.info

- dvc/tree/repo.py
- tests/unit/tree/test_repo.py
The subrepos were not removed from getting traversed, due to which it was causing race conditions, as we were expecting
different directories to be traversed but as subrepos were still there, `next(repo_walk)` could consume from the subrepo instead of the expected directories.
This was too hard to debug :disappointed_relieved:.
> tree.repo: fix race condition when walking subrepos

- dvc/lock.py
Previously, it'd sleep for 5s. Now, it should retry 6 times
before timing out.
Also reduced the timeout to 3s.
> lock: retry when trying to acquire lock

- dvc/cache/base.py
- dvc/hash_info.py
- dvc/output/base.py
- dvc/tree/base.py
- tests/unit/tree/test_dvc.py
- tests/unit/tree/test_repo.py
Related to #4144 , #3069 , #1676
> dvc: separate cache and tree hashes

- dvc/cache/base.py
This is what we've been doing before. No need to try to pull it up from
the state db, as this is a clearly newly generated file that will get
deleted.
> cache: use get_file_hash instead of get_hash

- dvc/command/version.py
Create temporary file in cache dir. And use it to detect the supported cache types. Clear after cache type detection.
Fixes #2788
> version: improve link type detection fall back

- dvc/api.py
- dvc/data_cloud.py
- dvc/dependency/repo.py
- dvc/external_repo.py
- dvc/repo/__init__.py
- dvc/repo/fetch.py
- dvc/repo/get.py
- dvc/repo/ls.py
- dvc/tree/_metadata.py
- dvc/tree/dvc.py
- dvc/tree/git.py
- dvc/tree/repo.py
- tests/func/test_api.py
- tests/func/test_external_repo.py
- tests/func/test_get.py
- tests/func/test_import.py
- tests/func/test_ls.py
- tests/func/test_run_multistage.py
- tests/func/test_update.py
- tests/unit/test_external_repo.py
- tests/unit/tree/test_repo_metadata.py
This adds support for get/list/api/import/ls on a subrepo.
Also fixes #3180, by adding a granular url support for `dvc.api.get_url`
And, of course it fixes #3369.
> support subrepos for get/list/api/import/ls

- dvc/repo/diff.py
- dvc/tree/dvc.py
- tests/func/test_diff.py
Partially addresses #2982.
* Directory file contents is now diff'd properly (instead of only showing the top level `dir/` added/modified/deleted status)
* Uncached directory hashes are fetched from remotes using `RepoTree(stream=True)`
This does not implement pulling all uncached file contents by default, or the file size related tasks.
> diff: use RepoTree to compare directory contents

- dvc/path_info.py
- tests/unit/test_path_info.py
> dvc: override replace in HTTPURLInfo to include extra_parts

- dvc/cache/base.py
- dvc/tree/base.py
- tests/func/test_import_url.py
- tests/func/test_remote.py
> dvc: compute dir hash without external cache

- dvc/stage/cache.py
- dvc/stage/run.py
- tests/func/test_run_cache.py
Existing lock files are an edge case of run-cache.
Prerequisite for #4223
> run: consolidate run-cache logic

- dvc/command/diff.py
- dvc/repo/diff.py
- tests/func/test_diff.py
- tests/unit/command/test_diff.py
Partially addresses #2982.
Docs PR https://github.com/iterative/dvc.org/pull/1758
* When using `dvc diff` to compare local workspace against a git revision, diff output will include a new file state to indicate a file is missing from both the workspace and the cache (and most likely needs to be pulled), instead of showing that the file was deleted.
* `--hide-missing` can be used to suppress this new file state entirely.
* When comparing only git revisions (and not the workspace) this status will be suppressed by default.
[![asciicast](https://asciinema.org/a/thHUinCl2BD3rAMcU5cEYZufO.svg)](https://asciinema.org/a/thHUinCl2BD3rAMcU5cEYZufO)
> diff: add state for files missing from both workspace and cache

- dvc/main.py
Does not change anything, it's good to disable it just after `yield` to not show other stats by accident.
> Disable cprofile on exit in `profile`

- dvc/repo/__init__.py
- dvc/repo/checkout.py
- dvc/repo/experiments/__init__.py
- dvc/repo/fetch.py
- dvc/repo/pull.py
- tests/unit/repo/test_repo.py
Can make `locked()` work both ways by:
```python
def locked(f):
if isinstance(f, Repo):
return lock_repo(f)
...
```
Or provide `Repo.locked()` context manager sharing implementation - less things to import.
> Make repo lock reentrable and provide a context manager

- dvc/tree/dvc.py
- dvc/tree/repo.py
- tests/unit/tree/test_dvc.py
We used to use that logic in DvcTree back before we had proper trees.
Now we have a RepoTree, that combines git/workspace tree with the
DvcTree and dirty state clearly belongs to the git/workspace and not
the dvc itself, as dvc state only depends on dvc-files and lock-files.
Prerequisite for #4523
> tree: open: handle dirty state in RepoTree

- dvc/config.py
- dvc/tree/http.py
- tests/unit/remote/test_http.py
Our MLE team at Expedia Group uses JFrog's Artifactory for storing binary artifacts. While Artifactory supports an HTTP/HTTPS interface, instead of POST it only accepts PUT for the new artifacts. This PR provides an alternative in this case.
Documentation change:
https://github.com/iterative/dvc.org/pull/1769
[JFrog Artifactory HTTP REST API](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/iterative/dvc/4553)
> Allow config option for HTTP method for uploads (Artifactory)

- dvc/dvcfile.py
- dvc/repo/commit.py
- dvc/repo/freeze.py
- dvc/repo/plots/__init__.py
- dvc/repo/reproduce.py
- dvc/repo/run.py
- tests/func/test_dvcfile.py
- tests/unit/test_dvcfile.py
The API of `Dvcfile.dump` has been changed to
```python
dump(stage, update_pipeline=True, update_lock=True)
```
which will make it to always dump by default to both files,
and provide flags to suppress one or the other.
Fixes #4235
> dvc: change Dvcfile.dump to be synchronized by default

- dvc/ignore.py
- dvc/tree/dvc.py
- dvc/tree/git.py
- dvc/tree/local.py
- dvc/tree/repo.py
- tests/func/test_tree.py
- tests/unit/tree/test_dvc.py
- tests/unit/tree/test_repo.py
DvcTree itself shouldn't care about the dirty state at all, as there is really no such thing for it, since its state is determined by the dvcfiles and lockfiles present.
What's a little weird here is that if a cached file/directory doesn't exist in the workspace, it is not considered dirty and we just treat it as a dvc output. But if it is modified, then we do consider it as dirty. Have to think about this a bit more... 
Fixes #4523 
> tree: repo: handle dirty state

- dvc/ignore.py
- tests/func/test_check_ignore.py
fix #4555
1. Sub-repo pattern now would be considered in `check-ignore` command.
2. New outputs for sub-repo patterns in a `detail`
3. Related tests.
> `check-ignore` show sub-repo patterns

- dvc/cache/base.py
- dvc/cache/local.py
- tests/func/test_checkout.py
A user in discord complained that external outputs' checkout
was failing. Looks like, during refactor of `HashInfo`,
this was forgotten, and as no tests existed before, we had
a regression from 1.6.5 onwards.
This might have been avoided with Static Typings. :sparkles:
Discord context: https://discord.com/channels/485586884165107732/485596304961962003/755067231339020358
> Fix error during external outputs checkout

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
- dvc/repo/experiments/show.py
- tests/func/experiments/test_experiments.py
* Prerequisite for #4498
* Adds support for committing to an existing experiment branch rather than always creating a new branch per experiment
* This will not be exposed via any `repro`/`run` commands, for now it will only be used when running checkpoint experiments
> experiments: support committing to existing experiment branches

- dvc/config.py
- dvc/repo/scm_context.py
- dvc/scm/base.py
- dvc/scm/git.py
- tests/unit/scm/test_scm.py
Fixes #4330
I'd appreciate feedback on this.
- The name `scm_autostage` was arbitrary, but chosen to match `no_scm`. I wasn't sure if just `autostage` would be too generic or if `git_autostage` might not be future proof.
- Maybe `scm.remind_to_track` could be renamed `scm.handle_changes`? I didn't want to go there without feedback. It's named in tests, but not called anywhere else in the codebase outside the context of this patch.
- Alternatively, this change could be handled in `scm_context`. I thought altering the attribute/behavior in the scm class would be more straight-forward but, after writing out the previous point, maybe a separate maybe `scm_context` could read the attribute from the repo class and handle the logic there, calling a separate function if changes are to be staged. …
> scm: add config option to stage files automatically

- dvc/tree/gdrive.py
- setup.py
This bug is fixed in PyDrive2 1.6.2.
Fixes #4507
> gdrive: don't use hacks for empty files

- dvc/api.py
- tests/func/test_api.py
`get_hash` is an internal api, so conventions should be respected.
We've been discussing automatically entering state instead, but that is out of scope for this particular bug.
Fixes #4575
> api: enter state when trying to get a hash

- dvc/repo/metrics/show.py
- tests/func/metrics/test_diff.py
- tests/func/metrics/test_show.py
> metrics: accept any viable target in DvcRepo

- .github/workflows/tests.yaml
- tests/dir_helpers.py
- tests/func/test_api.py
- tests/func/test_update.py
- tests/unit/dependency/test_params.py
Saves us creating lots of unwanted processes, especially because of gitpython. This is the sort of stuff that causes our tests to be flaky (esp windows is notorious for hanging on git commands).
Related to #2215, #4406
> tests: cache test directories

- setup.py
Wheels fail to build on initial install. Install `wheel` to fix this.
Original error message:
```
Building wheel for pyyaml (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /home/david/Documents/job-hunting/dvc/.env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nhmea2xe/pyyaml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nhmea2xe/pyyaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-v2ewd51w
cwd: /tmp/pip-install-nhmea2xe/pyyaml/
Complete output (6 lines):
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...] …
```
> install: Potential fix for (non-fatal?) setup errors on Ubuntu 20.04.

- dvc/utils/serialize/__init__.py
- dvc/utils/serialize/_py.py
- tests/func/experiments/test_experiments.py
- tests/func/params/test_show.py
- tests/unit/dependency/test_params.py
* add py support for ParamsDependency
This PR adds support for parameters file in ".py" format. Example:
```
dvc run -n train -d stages/train.py -p params.py:SEED,Train python stages/train.py
```
Where params.py looks something like this:
```
SEED = 1
class Train:
lr = 0.0041
epochs = 75
layers = 9
```
dvc.lock looks like this:
```
train:
cmd: python stages/train.py
deps:
- path: stages/train.py
md5: 23be4307b23dcd740763d5fc67993f11
params:
params.py:
SEED: 1
Train:
epochs: 75
layers: 9
lr: 0.0041
```
> add py support for ParamsDependency

- setup.py
Paramiko has recently added support for `Match`
https://github.com/paramiko/paramiko/issues/717
which resulted in some users getting an import error about `invoke`
module, as it is not a default dependecy for paramiko.
@Pseudomanifold reported that installing `invoke` #4589 worked for
him, which means that this newly added paramiko feature works in
his case. That feature seems to not affect configs without `Match`,
so we could give this a try and install it by default.
Our conda package will be updated during the next release.
Fixes #4589
Fixes #4616
> ssh: install paramiko with invoke

- dvc/tree/ssh/__init__.py
A leftover from an ancient code back when we didn't have connection pools.
Fixes #4618 
> ssh: don't use self.path_info for upload/download

- dvc/cli.py
- dvc/command/base.py
- dvc/command/repro.py
- tests/func/test_cli.py
Fixes #4025
I was initally going to use `--cwd` and remove `--cwd` from `repro`, but that left `repro` with the very strange `args.c` value. So I turned to the tar manpage for inspiratoin and found the long form of `-C` is `--cd`. Tar is good enough for me.
I actually ran into this problem yesterday trying to launch dvc from ssh for a dumb reason.
I also added a docs PR:
https://github.com/iterative/dvc.org/pull/1780
> cli: add --cd flag to change directories before executing commands

- dvc/command/status.py
- dvc/repo/init.py
When there are no stages in the repo, show a friendly message to that effect and display a [getting-started](https://dvc.org/doc/start/data-versioning) URL.
Fixes #4395.
Note: This PR, as well as the incidental https://github.com/iterative/dvc/pull/4606, are part of the application process for a job with DVC.
> status: Show friendly message for empty project.

- dvc/config.py
- dvc/tree/ssh/__init__.py
- tests/unit/remote/ssh/test_ssh.py
This parameter is passed to paramiko.
See http://docs.paramiko.org/en/stable/api/client.html?highlight=allow_agent#paramiko.client.SSHClient.connect for more details.
Fixes #4186
> remote[ssh]: Add the parameter allow_agent

- dvc/command/base.py
- dvc/command/metrics.py
- dvc/command/plots.py
- dvc/repo/__init__.py
- tests/func/metrics/test_show.py
- tests/func/plots/test_plots.py
Initial hacky support, that still tries to create `.dvc` directory as a side-effect. That side effect will be addressed in the upcoming 
PR. This feature in general makes us really rethink what a dvc repo is and whether having `.dvc` is really required.
> metrics/plots: initial support non-dvc repos

- dvc/repo/__init__.py
- dvc/repo/init.py
- dvc/repo/plots/__init__.py
- dvc/repo/plots/diff.py
- tests/func/plots/test_plots.py
> repo: move templates to plots

- dvc/tree/gdrive.py
- tests/func/test_data_cloud.py
We still need this hack, as `Upload` doesn't support callbacks yet and wrapping an empty content into our own progress bar results in errors.
Fixes #4593 
> gdrive: revert back to the hack for uploading empty files

- dvc/command/metrics.py
- dvc/command/repro.py
- dvc/repo/metrics/show.py
- tests/func/metrics/test_show.py
- tests/unit/command/test_metrics.py
Fixes #4630. 
Refactors `CmdMetricsShow` to use a hidden `_show_metrics` function that is more easily testable, similar to `_show_diff` for `CmdMetricsDiff`
Fixed a now broken import & implementation in `dvc/command/repro.py` caused by the change.
Added a simple test case which passes.
> metrics show: allow falsey values

- dvc/command/metrics.py
- dvc/command/plots.py
> metrics, plots: update cmd targets help

- tests/func/test_add.py
- tests/func/test_api.py
- tests/func/test_gc.py
- tests/func/test_import_url.py
- tests/func/test_run_multistage.py
- tests/func/test_update.py
- tests/remotes/hdfs.py
> gha: enable hdfs tests

- setup.py
Fixes bash>=4.4 completion (https://github.com/iterative/shtab/pull/23 <- https://github.com/iterative/shtab/issues/22)
> bump shtab dependency

- dvc/repo/__init__.py
- dvc/tree/dvc.py
- dvc/tree/repo.py
- tests/func/test_api.py
Wrap path in Repo.open_by_relpath() with PathInfo.
Closes #4650
@efiop @pared @pmrowla, How should we get rid of this class of bugs?
Should we test more or solve it with docstring + type-checking? I find a lot of our bugs is due to this kind of syntax error or assertion errors.
> api.open: fix error if uncached file inside a dir is accessed

- .github/workflows/tests.yaml
- dvc/scm/git.py
- setup.py
- tests/__init__.py
- tests/func/test_output.py
- tests/func/test_version.py
- tests/remotes/hdfs.py
- tests/unit/dependency/test_hdfs.py
- tests/unit/output/test_hdfs.py
- tests/unit/test_info.py
Run CI for Python3.9, skips hdfs tests for 3.9
d673e2a
Also, `dvc[hdfs]` install will be a no-op till we have
a pyarrow wheel for 3.9.
Note that this does not add an entry to the classifier
claiming it supports 3.9, that will be added when 3.9
gets released (or, wait for pyarrow to be released).
> Run CI for Python3.9

- dvc/cache/base.py
- dvc/hash_info.py
- dvc/output/base.py
- dvc/repo/diff.py
- dvc/tree/base.py
- dvc/tree/dvc.py
Will fix #4580.
* `HashInfo.dir_info` is now stored as a dict instead of list, dir cache is still kept in the list format everywhere else
* `DvcTree._get_granular_checksum` now uses `out.hash_info.dir_info` to lookup file hashes
> diff/dvctree: optimize dir cache access

- dvc/command/metrics.py
- dvc/utils/diff.py
- tests/func/metrics/test_diff.py
- tests/unit/command/test_metrics.py
- tests/unit/command/test_params.py
Currently we have a "diff not supported" marker in the table, that is
used whenever dvc is not able to diff the values (e.g. no old one, no
new one or format error). It is quite ugly and it is much more intuitive
to just show both old and new values and now show that marker at all, as
if there is no old/new value it is intuitive that we can't calculate the
change. Next step is to add old/new "bad format"/etc markers for
unsupported types or malformed/missing metric files.
E.g., before:
```
Path          Metric    Value    Change
metrics.json  foo       1.2      diff not supported
```
after this PR:
```
Path          Metric    Old    New    Change
metrics.json  foo       —      1.2    —
```
https://github.com/iterative/dvc.org/pull/1839
Thank you for the contribution - we'll try to review …
> metrics: diff: make table more intuitive

- dvc/command/status.py
- dvc/utils/serialize/_yaml.py
- tests/unit/utils/serialize/test_yaml.py
Unfortunately ruamel's exception doesn't contain much info that we could
reuse, so we can only reasonably extract the exc.problem and have       
something like:                                                         
```                                                                     
ERROR: unable to read: 'dvc.yaml', found duplicate key "metrics" with value "[]" (original value: "[]")          
```                                                                     
Fixes #4664
> yaml: wrap ruamel's DuplicateKeyError

- dvc/command/repro.py
- dvc/repo/fetch.py
- dvc/stage/__init__.py
- dvc/stage/cache.py
- dvc/stage/run.py
- tests/func/test_run_cache.py
- tests/unit/command/test_repro.py
- tests/unit/stage/test_cache.py
This option allows run-cache to pull the cache for the outputs
when restoring a stage instead of pulling everything at once during
`dvc pull --run-cache`.
Fixes #4223
https://github.com/iterative/dvc.org/pull/1841
> repro: support --pull

- dvc/api.py
- dvc/command/experiments.py
- dvc/command/repro.py
- dvc/output/base.py
- dvc/repo/checkout.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
- dvc/repo/experiments/show.py
- dvc/repo/reproduce.py
- dvc/stage/decorators.py
- dvc/stage/run.py
- tests/func/experiments/test_experiments.py
- tests/func/test_repro.py
- tests/func/test_repro_multistage.py
- tests/func/test_stage.py
- tests/unit/command/test_experiments.py
Will close #4498.
* `dvc exp run --checkpoint` can be used to reproduce a checkpoint experiment
* Checkpoint stages should be generated using `--always-changed` and with `--outs-persist` for the intermediate checkpoint outputs
* When running a checkpoint experiment, a new commit in the experiment branch will be generated each time the running stage calls `dvc.api.make_checkpoint()` (or generates the appropriate `.dvc/tmp/DVC_CHECKPOINT`) signal file
* Reproduction and checkpoint generation will run forever until the user code exits or is killed via Ctrl+C
* `dvc exp run --continue <checkpoint_exp_rev>` can be used to resume a prior checkpoint experiment. Execution will be resumed from the tip of the checkpoint …
> experiments: checkpoints proof of concept

- dvc/api.py
- dvc/cache/base.py
- dvc/cache/local.py
- dvc/repo/__init__.py
- dvc/state.py
- dvc/tree/base.py
- tests/func/test_commit.py
- tests/func/test_data_cloud.py
- tests/func/test_remote.py
- tests/func/test_run_cache.py
- tests/func/test_state.py
- tests/func/test_tree.py
- tests/unit/dependency/test_params.py
- tests/unit/repo/test_repo.py
- tests/unit/tree/test_dvc.py
- tests/unit/tree/test_repo.py
Users could still load state preemptively if they want to bulk up
the operations, but other than that tree/cache will just load it 
when they need it.
This also mitigates previously fixed bug where we were forgetting to load
state for subrepos.
> state: use granularly

- dvc/command/experiments.py
- dvc/command/repro.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/run.py
- dvc/repo/reproduce.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_experiments.py
- tests/unit/command/test_repro.py
* Finishes separating the experiments specific behavior from repro
> experiments: migrate `dvc repro -e` to `dvc exp run`

- dvc/repo/collect.py
- dvc/repo/experiments/show.py
- dvc/repo/metrics/show.py
- dvc/repo/params/show.py
- dvc/repo/plots/__init__.py
- tests/func/plots/test_plots.py
> params, plots, metrics: unify collection

- dvc/command/experiments.py
Will close #4688.
```console
$ dvc exp show --no-pager
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Experiment            ┃ Created      ┃     auc ┃ featurize.max_features ┃ featurize.ngrams ┃ prepare.seed ┃ prepare.split ┃ train.n_estimators ┃ train.seed ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ workspace             │ -            │ 0.57756 │ 2000                   │ 2                │ 20170428     │ 0.2           │ 50                 │ 20170428   │
│ 11-bigrams-experiment │ …
```
> experiments: add `--show-json` for `exp show`

- .github/workflows/packages.yaml
- .github/workflows/tests.yaml
GitHub is deprecating `set-env` command, and we need to migrate to environmental files.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> github actions: migrate to envrionmental files

- dvc/tree/webdav.py
When executing `dvc import-url remote://some-webdav/data`, the name of
the WebDAV dependency in the created stage for data used to be `None`.
This resulted in the following error:
```
File "/home/schubert/projects/dvc/dvc/main.py", line 76, in main
ret = cmd.run()
File "/home/schubert/projects/dvc/dvc/command/imp_url.py", line 14, in run
self.repo.imp_url(
File "/home/schubert/projects/dvc/dvc/repo/__init__.py", line 51, in wrapper
return f(repo, *args, **kwargs)
File "/home/schubert/projects/dvc/dvc/repo/scm_context.py", line 4, in run
result = method(repo, *args, **kw)
File "/home/schubert/projects/dvc/dvc/repo/imp_url.py", line 54, in imp_url
stage.run()
File "/home/schubert/miniconda3/tmp/envs/some-project/lib/python3.8/site-packages/funcy/decorators. …
```
> remote: set dependency name for WebDAV

- dvc/dependency/__init__.py
- dvc/dependency/webdav.py
- dvc/dependency/webdavs.py
- tests/unit/dependency/test_webdav.py
This adds the dependency for WebDAV and enables calls like `import-url
remote://some-webdav/data`
Related to #4374
> remote: add WebDAV dependency

- .github/workflows/tests.yaml
Currently each time anyone pushes anything to any fork of DVC, the test build is triggered. I think we should not allow that. Since the only builds that are interesting to us are the ones for master commits/pull requests.
> tests build: buil on push/pr to master

- dvc/command/cache.py
- tests/func/test_cache.py
comamnd 'dvc cache dir' now prints the current cache dir
when no cmd flags are provided.
Fixes #1998
Signed-off-by: Girish Joshi <girish946@gmail.com>
> command: print the current cache directory when no cmd flags are provided

- dvc/api.py
- dvc/command/metrics.py
- dvc/command/plots.py
- dvc/command/run.py
- dvc/dependency/__init__.py
- dvc/exceptions.py
- dvc/repo/metrics/show.py
Per https://github.com/iterative/dvc.org/pull/1848#pullrequestreview-506217071
\+ a few copy edits on docstrings (per jorgeorpinel/dvc/pull/2)
> term: "metrics" plural in output messages

- .github/workflows/tests.yaml
As @skshetry noted under https://github.com/iterative/dvc/pull/4680 - the repository name is wrong. Since the introduction of this change, there has been at least few builds, none of which should actually execute (and they did). Seems like job-level `if` is not working as intended. Removing it for now.
> gha: get rid of unnecessary if

- .github/workflows/packages.yaml
Provide `GITHUB_TOKEN` for publishing actions.
Github Actions does not allow to use both `run` and `uses` in one step.
https://github.com/iterative/dvc/actions/runs/301977911 - example.
> gha: fix github token providing for assets upload

- dvc/repo/experiments/__init__.py
- dvc/scm/git.py
- dvc/stage/run.py
- tests/func/test_repro.py
- tests/func/test_repro_multistage.py
- tests/func/test_stage.py
* Checkpoint runs for a baseline commit with no param/source modifications now works as expected - experiment will be reproduced in a new checkpoint branch
* Checkpoint stage subprocess will be terminated when an error occurs during checkpoint generation
> experiments: support `exp run --checkpoint` for baseline commits

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
* warn if rev provided with `--continue` is ambiguous
* always provide tip of branch when suggesting to use `--continue`
> checkpoints: cleanup --continue usage

- dvc/config.py
- dvc/dvcfile.py
- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/parsing/interpolate.py
- tests/func/test_feature_flags.py
- tests/unit/test_interpolate.py
- tests/unit/test_stage_resolver.py
This:
* does not yet support parametrizing from params (only from provided TEST_DATA). Will be fixed in the upcoming PRs.
* hidden behind a flag for now ( enable via `dvc config feature.parametrization true`). Unlikely to change till we have loops.
* Syntax is same: `${ var }`. Also kept `${{ var }}` syntax for now. Thinking of using double braces, just in case for forward/backward compatibility as users might already be using single braces for bash expansion. 
* Escaping is done by `\${ var}` or `\${{ var }}`, i.e. backslash(`\`).
Part of #3633
> Parametrization support on dvc.yaml

- dvc/stage/cache.py
- tests/unit/stage/test_cache.py
> run-cache: don't save always_changed stages

- .github/workflows/packages.yaml
- .github/workflows/tests.yaml
Related to #4711 #4684 #4703
Turns out `env` is fine. I got confused due to lots of warning we have been receiving on our builds, and assumed that `env` is calling `set-env` somehow.
Context:
https://github.community/t/environmental-files-on-windows/137631
> tests, packages: roll back environmental files change

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
- tests/func/experiments/test_experiments.py
- tests/unit/command/test_experiments.py
* `dvc exp run --reset ...` can be used to reset/restart an existing checkpoint experiment branch from scratch if it already exists
> checkpoints: add `--reset` option

- dvc/command/experiments.py
Related to #4709
* Use `{:.g}` general format for floating point numbers in `dvc exp show` and `dvc exp diff` so that scientific notation is used when appropriate
* Add `--precision` option for `dvc exp show` (defaults to 5)
> experiments: use general format for floating pt numbers

- dvc/command/status.py
Addresses  #1618 issue
Update `dvc status -r X` or `dvc status -c` commands by printing out a more specific message if cache and remote are in sync with each other.
> #1618 Custom message when cache and remote are in sync

- dvc/lock.py
- tests/func/test_lock.py
Resolves: https://github.com/iterative/dvc/issues/4325
PR merged in dvc.org: https://github.com/iterative/dvc.org/pull/1842
> lock: added troubleshooting doc link in error message (#4325)

- .github/workflows/tests.yaml
`lxml` now provides wheel for Python3.9. 
Also, enable windows test for Python3.9
> Use lxml wheel instead of legacy setup.py builds

- dvc/dvcfile.py
- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/parsing/interpolate.py
- dvc/schema.py
- tests/unit/test_context.py
- tests/unit/test_stage_resolver.py
This  PR was splitted from https://github.com/iterative/dvc/pull/4734, as it became quite large without the tests. I have also removed `foreach` and `set` support from there to reduce scope.
This PR is also quite large, but the Context is well-tested and is about more than half of it.  Though, I have left the tests for the newer syntax, which will come in separate PRs.
> Support parametrization from params or vars section in dvc.yaml

- dvc/output/base.py
- dvc/repo/checkout.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
- dvc/stage/__init__.py
- dvc/stage/run.py
Will close #4707, may also be related to #4746.
* Adds support for allowing missing outputs in `repo.checkout` and `stage.run` (previously we supported missing `persist` outs for checkpoints, but we actually need this for regular outs as well).
For checkpoint experiments, we want to support the potential use case where a stage may contain both intermediate outputs (that persist) and regular (non-persist) outputs. Depending on when the checkpoint run is interrupted, the regular outputs may not have been created yet, but this should not be considered a failure state for checkpoint experiments.
> checkpoints: allow missing outputs on checkout and stage.run

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
- tests/func/experiments/test_experiments.py
> checkpoints: `--continue` from last run experiment by default

- tests/func/test_cache.py
> TestCmdCacheDir: roll back darwin skip

- dvc/tree/ssh/connection.py
- tests/unit/remote/ssh/test_connection.py
- tests/unit/remote/ssh/test_pool.py
> Escape spaces in file paths when running commands on SSH remote

- .codecov.yml
- .github/workflows/tests.yaml
Most likely because of this `if` conditional, coverage results were never pushed in the last two months. This conditional is unnecessary. 
> Make codecov push results on every run

- .coveragerc
- .github/workflows/tests.yaml
This prints coverage report on Github Actions log, and also enables measuring of branch coverage (eg: `if` conditionals).
Our coverage may decrease, but it will provide us better sense of our coverage.
> Display coverage report on the GHA log and measure branch coverage

- dvc/repo/experiments/__init__.py
- tests/func/experiments/test_experiments.py
Will close #4768
As stated in the issue, I'm sure more work will be needed, but this little tweak was enough to at least allow the experiment to run. Some more work would be required to get parameter diffs to show up nicely in `dvc exp show` (screenshot of current display is included below, see the change in activation function), but that might be out of scope for this issue.
If there are no major objections, I can go ahead and write up some tests and finish this PR off proper-like.
> Experiments: allow setting of list parameters

- dvc/progress.py
- dvc/repo/__init__.py
- dvc/tree/s3.py
- setup.py
- tests/func/test_tree.py
- tests/unit/command/test_diff.py
* [✔️] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.
* [❌] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.
Note: I don't think this requires documentation changes.
Closes #4783 
This PR changes a few `dict` calls to literals to make them compliant with `flake-comprehensions` recent changes. Literals should be faster as recommended by `flake-comprehensions`:
> It's slower to call e.g. ``dict()`` than using the empty literal, because the
name ``dict`` must be looked up in the global scope in case it has been
rebound. Same for the other two basic types here.
> Replace dict calls for literals

- tests/func/test_update.py
> test_update_import: roll back skip

- .github/workflows/tests.yaml
- tests/remotes/gs.py
> gha: add gs creds

- dvc/repo/__init__.py
- dvc/repo/metrics/show.py
- tests/func/metrics/test_show.py
- tests/func/plots/test_plots.py
Related to #4446, iterative/dvc.org#1881
> plots/metrics: support show for no repo

- dvc/output/local.py
- dvc/utils/__init__.py
- tests/func/test_add.py
Will fix #4654.
* `dvc add <symlinked_file>` now works as expected. The DVC file will be placed in the same directory as the original symlink
* `dvc add`'ing symlinked a directory or a file inside a symlinked directory is now forbidden.
Docs PR: https://github.com/iterative/dvc.org/pull/1890
> add: fix issue when adding already tracked symlinked files

- tests/func/test_get.py
> get: checking target path before downloading

- dvc/repo/experiments/__init__.py
- tests/func/experiments/test_experiments.py
Fixes a bug where the wrong experiments could be removed from experiments run stash/queue during execution. Cause was due to gitpython `log()` returning commits in reverse order of `git reflog`. So our stash indices would not be lining up properly with git's `stash@{index}` order.
> experiments: fix stash ordering bug

- dvc/scm/git.py
- setup.py
In my tests `Git._ignore` is taking around ~65seconds for the whole test
suit(~50K invocations). The reason is that `gitpython` is launching a real
`git check-ignore` process, that takes time and resources.
Switching to `pygit2` or `dulwich` makes it drop to ~5seconds, saving us
almost a minute of the test run time and a lot of resources by not
launching any processes.
I've chosen `dulwich` over `pygit2` here because it is much more
pythonic and the performance is on-par with `pygit2`.
> git: use dulwich for .gitignore

- dvc/cache/base.py
- dvc/exceptions.py
- dvc/repo/add.py
- dvc/stage/__init__.py
- tests/func/test_add.py
Will fix #4797.
Docs PR https://github.com/iterative/dvc.org/pull/1892
* `output.commit()` no longer fails if file cannot be linked during `cache.save()` (as long as the file was still moved to cache successfully)
* `dvc add` will succesfully create .dvc file if the link step fails, and will warn user about the link failure and suggest re-running `dvc checkout`
Link failure during add now looks like:
```
$ dvc add foo
100% Add|██████████████████████████████████████████████████████████████████████████████████████████████████████████████|1/1 [00:00,  3.35file/s]
WARNING: Some targets could not be linked from cache to workspace.
See <https://dvc.org/doc/user-guide/troubleshooting#cache-types> for more information. …
```
> add: warn on cache link errors instead of failing

- dvc/repo/experiments/show.py
- dvc/scm/git.py
- tests/unit/scm/test_git.py
We are going to end up needing to re-use this code for iterating over commits in a git branch in several places for checkpoints related functionality. It's general enough that I think it makes more sense for this to go in scm.git rather than in some experiments specific helper function
> git: move branch iteration functionality from experiments into scm.git

- dvc/command/repro.py
Adds a logger.info() statement to remind the user to run dvc push after
running dvc repro.
Closes #2359
> command: add dvc push instruction after dvc repro

- dvc/command/imp.py
- dvc/repo/imp.py
- tests/func/test_import.py
- tests/unit/command/test_imp.py
To be consistent with the same `--no-exec` param in import-url.
Fixes #4567.
------
Related docs change: https://github.com/iterative/dvc.org/pull/1900
> import: add --no-exec param

- dvc/tree/http.py
* Increased the `HTTPTree.REQUEST_TIMEOUT` from 10 to 60 seconds, as it was not changed after implementing upload for http.
Will fix #4819
> [#4819] fixed failing to push some files to http remote

- dvc/parsing/__init__.py
- dvc/schema.py
- tests/func/test_stage_resolver.py
Here's a wiki documenting the feature: https://github.com/iterative/dvc/wiki/Parametrization#foreach--in.
And, following are the examples for the foreach:
1. Looping through a list
```yaml
stages:
build:
foreach:
- foo
- bar
- baz
in:
cmd: python script.py ${item}
```
2. Looping through a dictionary
```yaml
stages:
build:
foreach:
models:
us:
thresh: 10
gb:
thresh: 15
in:
cmd: python script.py ${item}
```
3. Looping throuhg values in [vars](https://github.com/iterative/dvc/wiki/Parametrization#vars-section) or params.yaml
```yaml
stages:
build:
foreach: ${models}
in:
cmd: python script.py --thresh ${item.thresh}
```
You might notice `set` in the wiki. That is currently not implemented.
> Implement foreach ... in loop in dvc.yaml

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/parsing/interpolate.py
- dvc/schema.py
- tests/func/test_stage_resolver.py
- tests/unit/test_stage_resolver.py
On top of #4734 
Here's a wiki documenting the feature: https://github.com/iterative/dvc/wiki/Parametrization
This PR introduces set keyword, which can be used to alias a variable.
Some examples:
1. Setting variable inside for a stage to be DRY
```yaml
stages:
build:
set:
item: "value"
cmd: python script.py --thresh ${item}
always_changed: ${item}
```
2. `set` can _set_ list to a variable. But, it is not allowed to contain nested list or nested dictionary inside of it.
```yaml
stages:
build:
set:
item:
- foo
- bar
- baz
thresh: 10
cmd: python script.py --thresh ${thresh}
outs: ${item}
```
3. `set` can _set_ dict to a variable. But, it is not allowed to contain nested list or nested dictionary inside of it. …
> dvc.yaml: introduce set keyword

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/parsing/interpolate.py
Just moving the `set` to the `Context` class, as it'll make testing it easier.
> refactor context set/alias to Context class

- .github/workflows/tests.yaml
- setup.py
Use master branch for flaky-service
Generate TAP results during pytest
I have added my own fork of github action that does not fail even on an error. I'll be monitoring the CI frequently and will rollback if anything explodes.
> Add flaky-service (Again)

- dvc/cache/base.py
- dvc/output/base.py
- dvc/repo/checkout.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
Will fix #4777.
* `cache.checkout` now has option to suppress missing file warnings (missing outs are expected/allowed for checkpoints)
* `exp checkout` now behaves as expected for checkpoint branches and when untracked files already exist in the user workspace
> experiments: fix checkpoint checkout issues

- tests/__init__.py
To better reflect https://github.com/python/cpython/pull/14360
> tests: set subprocess._active to None

- dvc/tree/http.py
- tests/unit/remote/test_http.py
This PR is to fix #4288 . It is still a work in progress as I haven't written any tests for the changes I have implemented, and I need some guidance on where/how to write tests for the project. Do I add to the unit test script in `dvc/tests/unit/remote/test_http.py`? 
I'm not sure if this requires documentation, but I'll create a PR for it if needed.
> http: raise error on unsuccessful http statuses on `exists`

- dvc/repo/plots/template.py
- tests/func/metrics/plots/test_show.py
Relates to #3801 
I really wasn't happy with the default confusion matrix provided in DVC, so I dove into Vega-Lite and figured out how to add a few features:
* Text labels on each cell showing record counts
* Added new confusion_normalized template to show counts normalized by actual label
* I thought about adding a new anchor to control the normalization direction (groupby actual vs. predicted), but this can also easily be achieved by simply switching x and y :smile: 
**New `confusion` template**
**Results of `dvc plots diff` with new `confusion_normalized` template**
Here are some stylistic decisions I made that I'm open to reverting in interest of genericness:
- Made the plot much bigger (can't reasonably …
> Plots: Better confusion matrix, and normalized version to

- dvc/cache/base.py
- dvc/cache/local.py
- dvc/hash_info.py
- dvc/output/__init__.py
- dvc/output/base.py
- dvc/schema.py
- dvc/stage/cache.py
- dvc/stage/loader.py
- dvc/stage/serialize.py
- dvc/stage/utils.py
- dvc/state.py
- dvc/tree/base.py
- dvc/tree/hdfs.py
- dvc/tree/local.py
- dvc/tree/s3.py
- dvc/tree/ssh/__init__.py
- tests/func/test_add.py
- tests/func/test_import_url.py
- tests/func/test_install.py
- tests/func/test_lockfile.py
- tests/func/test_remote.py
- tests/func/test_repro.py
- tests/func/test_run_multistage.py
- tests/func/test_state.py
Related to #3256
https://github.com/iterative/dvc.org/pull/1907
> dvc: add size/nfiles for deps/outs

- dvc/command/plots.py
- tests/func/metrics/plots/test_show.py
We have been producing clickable HTML path basing on `repo.root_dir` while actually it was created relative to `cwd`.
This PR fixes the issue.
> plots: fix plots path when calling from different dir

- setup.py
moto has `aws-sam-translator` as an indirect dependency that since 1.29.0 started to have a `public` module
that causes conflicts in `flufl.lock` when it tries to use `atpublic` package (module is also called `public`).
```
tests/func/test_add.py:21: in <module>
from dvc.main import main
dvc/main.py:7: in <module>
from dvc import analytics
dvc/analytics.py:16: in <module>
from dvc.lock import Lock, LockError
dvc/lock.py:8: in <module>
import flufl.lock
/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/flufl/lock/__init__.py:3: in <module>
from flufl.lock._lockfile import (
/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/flufl/lock/_lockfile.py:42: in <module>
from public import public
E   ImportError: cannot import name 'public'
```
Oddly enough, this …
> dvc: limit aws-sam-translator version for moto

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/gc.py
- tests/func/experiments/test_gc.py
- tests/unit/command/test_experiments.py
Related to #4440.
* Adds `dvc exp gc` which can be used to remove experiments which are no longer needed
* `--workspace`/`--all-branches`/`--all-tags`/`--all-commits` are equivalent to the regular `dvc gc` flags - experiments derived from the specified set of commits will be preserved and all other experiments will be removed
* This command will not remove any objects from DVC cache, `dvc gc -e/--exp` option to preserve used-cache for experiments will be added in a follow up PR
> experiments: add `dvc exp gc`

- dvc/cache/base.py
- dvc/dir_info.py
- dvc/output/base.py
- dvc/tree/base.py
- dvc/tree/dvc.py
- tests/func/remote/test_index.py
- tests/func/test_add.py
- tests/func/test_cache.py
- tests/func/test_checkout.py
- tests/func/test_remote.py
- tests/func/test_tree.py
- tests/unit/output/test_local.py
- tests/unit/test_dir_info.py
- tests/unit/tree/test_repo.py
Currently, we are converting dir_info to/from lists all the time.
The reason is that dir_info is stored as list of dicts in *.dir files,
but that makes it hard to work with. In addition to that, we will likely
be changing .dir file format in the near future #829, so we need to
abstract away dir_info into something that we won't care how it will be
stored on disk.
Related #3256
Related #4847
> dvc: use DirInfo instead of dicts/lists

- dvc/command/plots.py
- dvc/exceptions.py
- dvc/repo/metrics/show.py
- dvc/repo/plots/__init__.py
- dvc/repo/plots/data.py
- dvc/utils/serialize/_json.py
- tests/func/metrics/metrics/test_show.py
- tests/func/metrics/plots/test_show.py
- tests/func/metrics/test_common.py
> plots/metrics: fix some communication disrepancies

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- tests/func/test_stage_resolver.py
- tests/unit/test_context.py
- tests/unit/test_interpolate.py
We wrap every data to one of the `Node` object. But, since we were
passing `self.data` instead of `self`, it was skipping the conversion
and instead was just trying to set data as-is, which would have make
our latter assumptions incorrect, as other codebases assume it to be
a `Node`.
I have added asserts in a few places. Also, I noticed that, on a few
test assumptions, when `resolving`, we were not converting values
back to it's original form (`CtxDict` -> `dict`, `CtxList` -> `list`
and `Value` -> _). So, I have added `node.value` property, as it is
a complement of the above fix.
This caused a ripple effect for the changes in the API as `foreach`
now resolved and changed the data to the original form,
which prevents us from tracking the data later in the "field".
So, `resolve`/`select` …
> parametrization: fix `merge_update` not converting data to `Node` object

- dvc/parsing/__init__.py
- tests/func/test_stage_resolver.py
We were still trying to load params file used in `use`
for local stages which was throwing overwrite error.
Thanks to @dmpetrov for pointing out.
> parametrization: skip loading globally used params section again locally for stages

- dvc/cache/__init__.py
- dvc/repo/gc.py
> cache: refactor cache types

- dvc/parsing/context.py
- tests/unit/test_context.py
Eg:
```yaml
outputs:
- ${foo}:
persist: ${persist}
```
> parametrization: Support keys of the dictionary to be interpolated

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
- dvc/repo/reproduce.py
- dvc/stage/__init__.py
- dvc/stage/run.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_experiments.py
- tests/unit/command/test_experiments.py
Related to #4821.
* checkpoint stage detection is handled automatically based on whether or not a stage contains `checkpoint` outputs
* `dvc exp run --checkpoint` is replaced with `dvc exp run`
* To force reset an existing checkpoint run from scratch, use `dvc exp run -f`.
* `dvc exp run --continue` is replaced with `dvc exp res[ume]`
> checkpoints: `exp run` and `exp res[ume]` refactor

- dvc/tree/webdav.py
> remote: avoid chunking on webdav. Fixes #4796

- setup.py
Tests started to fail recently with
```
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\moto\core\models.py:17: in <module>
import responses
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\responses.py:29: in <module>
from urllib3.connection import HTTPHeaderDict
E   ImportError: cannot import name 'HTTPHeaderDict'
```
caused by https://github.com/getsentry/responses/issues/354
> setup.py: limit responses version for moto

- tests/func/test_api.py
Related: #4792
Signed-off-by: Ioana Grigoropol <ioana.grigoropol@gmail.com>
> tests: mark azure test as flaky

- dvc/command/add.py
- dvc/repo/add.py
- tests/func/test_add.py
Related to #4816.
Signed-off-by: Ioana Grigoropol <ioana.grigoropol@gmail.com>
https://github.com/iterative/dvc.org/issues/1928
> api: add support for simple wildcards

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/run.py
- setup.py
- tests/func/experiments/test_experiments.py
Following up on my last [comment](https://github.com/iterative/dvc/pull/4769#issuecomment-714869426) on #4769 
So I did some testing and my idea to use [benedict](https://github.com/fabiocaccamo/python-benedict) to simplify the code actually works great... ~almost~. (**Update:** figured it out) As you can see in the changes here, you can replace a lot of code with a single built-in function call. This also has the benefit of using more standard `[0]` syntax for list accessing.
~I added more tests to make sure that everything was working, then I ran into this strange behavior on a single test case:~
~The params are being correctly updated and written, but for some reason the experiment doesn't seem to actually …
> Simpler param updates with python-benedict

- dvc/command/dag.py
- tests/unit/command/test_dag.py
> dag: add --outs option

- dvc/exceptions.py
- dvc/utils/fs.py
Files are checked for ownership by trying to `chmod` them before moving them around; if fail, return a verbose exception.
Previous behavior: moving files to a temp folder and then do the check; when fail, files seemed to be missing.
Should fix #4348 and maybe fix #2992.
> utils/fs: checking files ownership in 'move' (#4348)

- .github/workflows/tests.yaml
The tests added on pending PRs were making noise on the flaky service. Changed it to only send on the `master` branch.
> send TAP result to flaky service only on master

- dvc/cli.py
- dvc/main.py
This is a hidden flag (no docs needed) for a handy shortcut to pdb when
we need it. E.g. binaries built by pyinstaller are much easier to debug
with it.
> dvc: add --pdb flag

- dvc/repo/experiments/__init__.py
- dvc/tree/base.py
- dvc/tree/gdrive.py
- dvc/tree/gs.py
- dvc/tree/http.py
- dvc/tree/local.py
- dvc/tree/s3.py
- dvc/tree/ssh/__init__.py
- dvc/tree/webdav.py
- tests/func/experiments/test_experiments.py
- tests/unit/tree/test_tree.py
Will fix #4850.
* `BaseTree.upload()` now supports `file_mode` kwarg for applicable trees (currently LocalTree only).
* Behaves the same way as `download(file_mode=...)` - if the tree supports modes, the specified mode will be applied.
* For LocalTree, if mode is unspecified file will default to `LocalTree.CACHE_MODE` (same as existing behavior)
> experiments: preserve file permissions across tmpdir execution

- .pylintrc
- dvc/cache/__init__.py
- dvc/config.py
- dvc/dependency/__init__.py
- dvc/dependency/webhdfs.py
- dvc/output/__init__.py
- dvc/output/base.py
- dvc/output/webhdfs.py
- dvc/scheme.py
- dvc/tree/__init__.py
- dvc/tree/webhdfs.py
- setup.py
- tests/docker-compose.yml
- tests/func/test_add.py
- tests/func/test_api.py
- tests/func/test_data_cloud.py
- tests/func/test_gc.py
- tests/func/test_import_url.py
- tests/func/test_update.py
- tests/remotes/__init__.py
- tests/remotes/hdfs.py
- tests/unit/remote/test_webhdfs.py
* [✅ ] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.
* [✔️] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.
This is a draft PR to close #4687. Documentation is required ~but no issue or separate PR has been created yet~, is tracked by https://github.com/iterative/dvc.org/issues/1899, and being worked on in https://github.com/iterative/dvc.org/pull/1916.
As I work on the PR, I would like some input on:
* Choice of library: I went with [hdfs](https://pypi.org/project/hdfs/) as it seems to be the most stable.
* Scope: assuming consensus on library, there's some optional parameters that could be …
> Support for WebHDFS

- dvc/command/metrics.py
- dvc/command/plots.py
- tests/func/metrics/test_common.py
Related to #4837, fixes issues mentioned by @efiop
> metrics/plots: common tests: check for particular exceptions

- dvc/command/add.py
- dvc/command/imp.py
- dvc/command/imp_url.py
- dvc/command/run.py
- dvc/dependency/__init__.py
- dvc/output/__init__.py
- dvc/output/base.py
- dvc/repo/add.py
- dvc/repo/imp.py
- dvc/repo/imp_url.py
- dvc/schema.py
- dvc/stage/__init__.py
- dvc/stage/loader.py
- dvc/stage/params.py
- dvc/stage/serialize.py
- dvc/stage/utils.py
- tests/func/test_dvcfile.py
- tests/func/test_stage.py
- tests/unit/command/test_add.py
- tests/unit/command/test_imp.py
- tests/unit/command/test_imp_url.py
- tests/unit/command/test_run.py
Outs desc will be used by Viewer right away. Stage desc is for people to
start using now, but we won't be using it in viewer until DAG support is
added there.                                                            
This doesn't yet preserve the `desc` when re-`dvc add/run` something.
Same as with `meta`, that needs to be addressed separately in the follow-up PR.
https://github.com/iterative/dvc.org/pull/1951
> dvcfile: add desc field for outs/stages

- dvc/info.py
- dvc/tree/__init__.py
- tests/func/test_version.py
- tests/unit/test_info.py
- tests/unit/tree/test_tree.py
Show caches and remotes in the info output to assist in diagnosis of issues.
Fixes #4574.
Sample output
```sh
> dvc version
DVC version: 1.9.1+8f6350
---------------------------------
Platform: Python 3.8.6 on Linux-5.9.6-arch1-1-x86_64-with-glibc2.2.5
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda4
Caches: ssh, local
Remotes: ssh, azure
Workspace directory: ext4 on /dev/sda4
Repo: dvc, git
```
This change will require an update to the docs for [version](https://dvc.org/doc/command-reference/version) command. Will create a docs PR if the output format looks good for this change.
---
> dvc: include cache urls in info output.

- dvc/repo/experiments/run.py
When an experiment already exists, experiment only kwargs were being passed into regular repro, which would then fail with
```
TypeError: restore() got an unexpected keyword argument 'checkpoint_resume'
```
or similar exceptions
> experiments: fix bug where repro with run-cached stages may fail

- dvc/repo/experiments/__init__.py
- tests/func/experiments/test_checkpoints.py
I believe #4855 introduced a regression to do with experiments, checkpoints, and run cache. #4911 seems to have tried to address it, but I still get the same error:
```
2020-11-19 19:10:05,223 ERROR: Failed to reproduce experiment 'a32ea21' - failed to reproduce 'dvc.yaml': restore() got an unexpected keyword argument 'checkpoint_resume'
------------------------------------------------------------
File "/usr/local/lib/python3.8/dist-packages/dvc/repo/reproduce.py", line 175, in _reproduce_stages
ret = _reproduce_stage(stage, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/dvc/repo/reproduce.py", line 36, in _reproduce_stage
stage = stage.reproduce(**kwargs)
File …
```
> Bugfix: pop checkpoint resume from kwargs in experiments

- dvc/repo/experiments/__init__.py
- tests/func/experiments/test_experiments.py
#4823 introduced a regression with checking out of queued experiments:
```
2020-11-19 22:42:52,775 DEBUG: Checking out experiment commit '243e010'
2020-11-19 22:42:52,788 DEBUG: fetched: [(793,)]
2020-11-19 22:42:52,806 ERROR: unexpected error - expected string or bytes-like object
------------------------------------------------------------
File "/usr/local/lib/python3.8/dist-packages/dvc/main.py", line 90, in main
ret = cmd.run()
File "/usr/local/lib/python3.8/dist-packages/dvc/command/experiments.py", line 360, in run
self.repo.experiments.checkout(self.args.experiment)
File "/usr/local/lib/python3.8/dist-packages/dvc/repo/experiments/__init__.py", line 965, in checkout …
```
> Fix exp checkout queued and cleanup

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/schema.py
- tests/func/test_stage_resolver.py
- tests/unit/test_context.py
The schema is changed of `vars` to accommodate both use of
imports (`use` previously) and setting variables locally (`vars`).
Now:
```yaml
vars:
- params.yaml
- foo: foo
bar: bar
```
So, if it's the string, it's an import. If it's a dictionary, it's a local variable.
Also, the same distinction occurs for the stages.
```yaml
stages:
build:
cmd: "command --thresh ${thresh}
params:
- foo
vars:
- params.yaml
- foobar: foobar
```
Note that the distinction is not made internally for `vars` and `params` yet, not in `dvc.lock` as well.
> parametrization: change `use` and `vars` to just `vars`

- dvc/command/dag.py
- dvc/repo/__init__.py
- dvc/repo/graph.py
- dvc/repo/trie.py
- tests/unit/command/test_dag.py
- tests/unit/repo/test_repo.py
Fixes #4904 
Docs already say that we can do that, so no need to update them.
> dag: support output as target

- dvc/parsing/__init__.py
- tests/func/test_stage_resolver.py
Previously, "dir/../params.yaml" would have thrown an OverwriteError.
> parametrization: Skip already used vars, even if they are in a relative path.

- dvc/parsing/interpolate.py
- setup.py
Via pyparsing. The error message is not that great, as it's greedy.
But, it does point out where the mistakes are, correctly most of the
time. :)
Also raises appropriate error messages for ParseError.
> interpolation: support `[]` indices syntax

- .github/workflows/tests.yaml
- tests/conftest.py
- tests/func/test_output.py
- tests/remotes/azure.py
- tests/remotes/gdrive.py
- tests/remotes/gs.py
- tests/remotes/hdfs.py
- tests/remotes/http.py
- tests/remotes/oss.py
- tests/remotes/s3.py
- tests/remotes/ssh.py
- tests/remotes/webdav.py
- tests/unit/dependency/test_hdfs.py
- tests/unit/output/test_hdfs.py
Some of the tests are run by default, other requires
`--enable-{remote}` to run. The remotes that are run by default
also have a `--disable-{remote}` flag. All of the remotes can be
enabled using `--all` flag.
To use this functionality in the fixture,
`test_config` fixture has to be used and requires to call
`test_config.requires(remote)`.
In an individual test, you can simply use `pytest.mark.remote`
to make them skip or run.
> tests: allow selectively running tests for remotes

- .github/workflows/tests.yaml
This was increasing the wait times of the CI.
Also enabled codecov failure to not fail the whole CI pipeline, while I was at it.
> ci: reduce no. of macOS jobs

- tests/__init__.py
For some reason, tests on my machine started failing with 2048, though it's near to the end, so it needs to be a bit higher than 2048.
Also, the test was run without `--all`. 
> tests: increase ulimit to 4096

- .github/workflows/tests.yaml
- setup.cfg
- tests/__main__.py
- tests/conftest.py
Some of the flags from `python -m tests` are moved to `setup.cfg`, so that plain `pytest` works the same way.
> tests: move some flags from `python -m tests` to config

- dvc/dvcfile.py
- dvc/stage/__init__.py
- dvc/stage/loader.py
- tests/func/test_dvcfile.py
This is a bit hackish, but does the job done.
It feels like we need some unified way to be able to load
and dump, but not sure how. Till then, this data class
will be helpful in communicating between those.
> parametrization: prevent dumping parametrized stages

- tests/remotes/gdrive.py
A `tempfile.NamedTemporaryFile` cannot be read on Windows before closing. [REF](https://stackoverflow.com/questions/6416782/what-is-namedtemporaryfile-useful-for-on-windows)
> import-url: adjusting tests to run on Windows

- dvc/utils/__init__.py
- tests/unit/utils/test_utils.py
Even the title says _correctly_, this is done to support stages that was generated using a complex data, which is not officially supported.
eg:
```yaml
stages:
build:
foreach:
- level: 15
- level: 25
- level: 35
do:
cmd: echo ${item.level}
```
Here, the list has dict inside which is something that's not supported officially. This will generate stages having name similar to the
`build@{'level': 15}`, which works, but the `dvc repro <stage>` fails as the target parser looks for `:` to differentiate between file path and the stage name (eg: we support running single stage via `dvc repro ../dvc.yaml:build2`).
Though, I have to say, the parsing is getting complex. :( 
Fixes #4957 
> parse: parse target correctly for generated stages

- tests/docker-compose.yml
`Azure` tests are flaky for some reason. When I investigated [one
of the job], something seemed wrong with the Azurite or
the client lib.
On `AzureTree.blob_service`, we do the following to check if the
container exists:
```python
try:
container_client.get_container_properties()
except ResourceNotFoundError:
container_client.create_container()
```
When looking at the test log, I found out that the
`get_container_properties` was failing with
`ErrorCode:ContainerNotFound` whereas `create_container`
successively was failing with `ErrorCode:ContainerAlreadyExists`.
`create_container` is correct, but `get_container_properties` is
wrong here, as many of the Azure tests have already run successfully
before.
So, either the Azurite has/had bug or the client lib has a bug.
Anyway, we'll find out …
> tests/ci: update docker image for Azurite

- setup.py
- tests/func/test_api.py
- tests/func/test_checkout.py
Looks like it works in the newer versions of `moto`.
Not removing the fixtures just yet, maybe in the next PR if this gets approved.
> s3: use mocked s3 instead of the real one

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- tests/func/test_stage_resolver.py
- tests/func/test_stage_resolver_error_msg.py
The syntax is the following:
```yaml
vars:
- test_params.yaml:sub
- test_params.yaml:sub2,sub3
stages:
echo:
cmd: "echo ${sub} ${sub2} ${sub3}"
```
> parametrization: support loading vars partially

- dvc/command/repro.py
- dvc/repo/__init__.py
- dvc/repo/freeze.py
- dvc/repo/remove.py
- dvc/repo/reproduce.py
- dvc/repo/stage.py
- dvc/stage/loader.py
- dvc/utils/__init__.py
- tests/func/test_dvcfile.py
- tests/func/test_repo.py
- tests/unit/command/test_repro.py
This PR adds a way to be able to run the following stage `foreach` group through a single target `build`:
```yaml
stages:
build:
foreach:
- 15
- 25
- 35
do:
cmd: echo ${item}
```
Eg:
```console
$ dvc repro build
```
Also, this PR adds a `--glob` flag so that you can achieve the same with:
```console
$ dvc repro "build@*" --glob
```
Also note that, globbing is only allowed for the stage name, not to the file.
So, the following would work:
```console
$ dvc repro "dvc.yaml:build*" --glob
```
But, the below one won't:
```console
$ dvc repro "**/dvc.yaml:build*" --glob
```
Regarding the implementation, I have moved all of the target parsing logic inside `dvc.repo.stage` in a `StageLoad` class.
So, enabling these features on a `checkout` or similar commands should be straightforward.
Fixes …
> repro: support glob/foreach-group to run at once through CLI

- dvc/repo/add.py
- dvc/repo/imp_url.py
- dvc/repo/run.py
- dvc/stage/__init__.py
Having that logic in `create_stage` is unnatural and also has some
side-effects for unsuspecting users. For example, it will check the
filesystem for existing dvcfile and will try to load a corresponding old
stage. I've adjusted it with minimal changes to better reflect the logic
behind it.
Pre-requisite for #4907
> stage: move is_cached logic to Stage.can_be_skipped

- .gitignore
- dvc/repo/init.py
- dvc/scm/base.py
- dvc/scm/git.py
- tests/func/test_init.py
- tests/func/test_scm.py
> dvc: more explict error during init when .dvc is ignored by git

- dvc/dvcfile.py
- dvc/repo/add.py
- dvc/repo/imp_url.py
- dvc/repo/run.py
- dvc/stage/__init__.py
- dvc/stage/loader.py
- dvc/stage/serialize.py
- dvc/stage/utils.py
- tests/func/test_add.py
- tests/func/test_dvcfile.py
- tests/func/test_import_url.py
- tests/func/test_run_single_stage.py
We load meta anyways, even with a quick parser, so we should just
attach it to the stage too, to make it less confusing. Comments require
some additional legwork, so those are restored separately, as they were
before. Though comments too should be restored more explicitly by the
serializer class (to be introduced in the future).
Pre-requisite for #4907
> dvc: preserve comments/meta on add/imp/run

- dvc/stage/__init__.py
- dvc/stage/utils.py
- tests/func/test_add.py
- tests/func/test_import_url.py
- tests/func/test_run_single_stage.py
> dvc: preserve desc on add/run/imp

- dvc/parsing/__init__.py
- dvc/repo/params/show.py
- dvc/stage/__init__.py
- dvc/stage/loader.py
- tests/func/params/test_diff.py
- tests/func/test_stage_resolver.py
Previously, all of them were included in the `dvc.lock` file (which was just a hack) which made them appear on the `dvc params diff` automatically. This adds proper support of showing them, although the code has to be restructured later.
> parametrization: show interpolated vars in params diff

- dvc/parsing/interpolate.py
- tests/func/test_stage_resolver.py
- tests/unit/test_context.py
Previously, Python's `str()` was being used that
resulted in boolean transformed into "True"/"False".
Fixes #4996
> parametrization: convert bool to string as "true"/"false"

- dvc/repo/plots/template.py
Related to #4902
This change improves user experience for plots.
-----
- linear plot using [default plot](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoJFCgMATqYCeaEAAZKAJgAcrgKwvP9gMzv7LgDsnu6KIDSyynAAHmj2ShZwxHZIqghhEJhwOHb2YZg0CPrqCDnoAIwAbPaVPuUAnJX1AfaBIAC+CiZmlja5lGLu7oGBTuX25UH15Q31YRFRsajlCUkpaRlZZSDl+YXFSKV2VTV1jdNVu53d5lZQtuiO7pOBYjXuPvXTTfVO85ExNBOVbJdCpQ6bbJ2P5KApFTKHbYnWoNJrlZ5-a4gUy3PqPSgfEZ1GbjMSNdxjf6LNA+EHrCFKTJQ9A+PbwkpI6oo86TSpiDpdbE9O4PBwEr5Oez2MROYI+MaNKmA1BiOlgjaMrZ2fmw-YIo4VLlnJpOMasrE43r3fqVcpOJo+SqVV4zFzSmHhAFLdxq7EakBM7ahXXsxHHI2o37DPIW4V4sV854jGWfdxvXZKBbKyq+8HpTXMkCVNkHA07CPnJxRg …
> plots: make linear and scatter interactive

- dvc/tree/base.py
- tests/unit/remote/test_base.py
- tests/unit/tree/test_base.py
> tree: update hint about missing deps

- dvc/cache/base.py
- dvc/command/base.py
- dvc/state.py
- dvc/utils/__init__.py
- dvc/utils/fs.py
increase to trace level on various debug messages:
* cache/base: check start, stop, assumed unchanged if RO
* command/base:  assumed default
* state: fetched
* utils: assumed default
* utils/fs: path inode
fixes #4638   took some liberty with other debug level statements as suggested in issue.
> increase log level of messages to trace

- dvc/tree/hdfs.py
- tests/remotes/hdfs.py
Replace with pyarrow.fs.HadoopFileSystem, which has a different API.
Fixes #4905
Hi,
This is my first PR to this project, and I'd appreciate some feedback to keep going in the right direction. [pyarrow.hdfs](http://arrow.apache.org/docs/python/filesystems_deprecated.html) and [pyarrow.fs.HadoopFileSystem](https://arrow.apache.org/docs/python/generated/pyarrow.fs.HadoopFileSystem.html) have different APIs. I've updated affected methods but would appreciate guidance on the following:
1. The new API doesn't have a `close()` method, which is used in `/dvc/tree/pool.py`. One way to do this is to set each `close()` in try-except blocks. But is there a better way than this for example?
```
@contextmanager
def …
```
> hdfs: Replace deprecated pyarrow.hdfs.connect

- dvc/schema.py
- dvc/stage/__init__.py
- dvc/stage/run.py
- scripts/schema/dvc-yaml.json
- tests/func/test_repro_multistage.py
- tests/unit/stage/test_loader_pipeline_file.py
- tests/unit/stage/test_run.py
Fix #4373 
Doc PR: https://github.com/iterative/dvc.org/pull/1980
> Allow user to pass a list of commands for one single stage

- dvc/repo/__init__.py
- dvc/repo/stage.py
- tests/func/test_remove.py
- tests/func/test_stage_load.py
Might be useful for Viewer, but anyway, it's a good thing to move this to a `dvc.repo.stage`.
See https://github.com/iterative/dvc/issues/5008#issuecomment-736706202
> provide a callback to handle error during the stage collection

- dvc/external_repo.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/apply.py
- dvc/repo/experiments/executor.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/stash.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_show.py
- tests/func/test_checkout.py
- tests/func/test_import.py
- tests/func/test_install.py
- tests/func/test_scm.py
- tests/func/test_status.py
- tests/func/test_update.py
- tests/unit/scm/test_git.py
A bit of a rough move to make another iteration.
Pre-requisite for dulwich GitTree.
> scm: move logic to gitpython backend

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/apply.py
- dvc/repo/experiments/base.py
- dvc/repo/experiments/branch.py
- dvc/repo/experiments/gc.py
- dvc/repo/experiments/utils.py
- dvc/scm/git/__init__.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_show.py
* Moves some general exp ref related functions out of `Experiments` class and into `experiments.utils`
* `scm.resolve_rev()` now resolves human-readable experiment short names
* This adds support for using exp names in regular DVC commands like `diff`/`metrics`/`plots`/etc (using these commands with experiment git SHAs was already supported)
> scm/git: add support for resolving experiment names

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/stage/run.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_experiments.py
* Untracked files are now ignored when populating experiment executor. Only workspace changes to git-tracked files will be passed into the executor.
* To explicitly pass untracked files (such as a new code classes/files) into the experiment, the file should be staged as a new file via `git add <file>` or `git add --intent-to-add <file>` before running the experiment.
* Closes #4594.
* Only tracked files (including any "new" files which were staged via `git add`) will be included in the experiment commit.
* **This is a change from prior behavior (#4452)**. Support for the inclusion of untracked files should no longer be needed, as the types of intermediate files which were discussed in the original issue, should …
> experiments: ignore untracked files

- dvc/stage/run.py
- tests/func/test_repro.py
- tests/func/test_repro_multistage.py
- tests/func/test_stage.py
- tests/unit/stage/test_run.py
This rollbacks the bug introduced on #4934 that stopped showing commands during the dry run.
And, also prepends ">" in the command script instead of "$" sign as it broke the dvc.org docs markdown (https://github.com/iterative/dvc.org/pull/1980#discussion_r535788638).
> run/repro: show command on dry-run, add ">" to script output

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/stash.py
- tests/func/experiments/test_experiments.py
In certain situations it was possible for the staged/added args file to remain staged if an error occurred while trying queue/stash the experiment commit. This would lead to the file being committed into git, and then prevent the same experiment from being staged in the future (since workspace would always appear clean w/no experiment to stash due to the args file already existing).
* args file should no longer remain staged if an error occurs
* If args file exists and is Git-tracked we will output a warning and suggest how to remove it when running experiments
> experiments: handle state where tmp args file was committed to git

- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/stash.py
- tests/unit/scm/test_git.py
* Removes `scm` attribute from Git backends
* Makes backends configurable in `Git.__init__`
* Adds fixture for testing individual backends in `tests/unit/scm/test_git`
* Implements get/set/remove ref functions in gitpython backend
* Implements required dir/root_dir properties for dulwich backend
* Fixes some stash/reflog behavior that applied to all backends
> git: drop scm requirement from backends

- dvc/repo/trie.py
- tests/func/test_run_single_stage.py
The message given by the exception is not verbose enough `why` this exception is thrown.
Now gives the user more information as to why the overlapping paths should be changed.
When running the `dvc repro` command with the following `params.yaml` and `dvc.yaml` files an exception is thrown because paths of the output overlap in the tracked datasets directory. The exception message is not verbose enough for a user to understand the problem at hand. 
```yaml
buses:
- 1
- 2
vars:
- params.yaml
stages:
buses_pipe:
foreach: ${buses}
do:
cmd: python filter.py --bus ${item}
wdir: src/data_wizards_notebooks
deps:
- ../../datasets/raw data/file_${item}.csv
- "filter.py" 
outs:
- ../../datasets/raw data/file_${item}_filter.csv
```
Exception:
```
.../dvc/repo/trie.py", line 37, in build_outs_trie …
```
> Improve OverlappingOutputsError exception message.

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
- dvc/repo/experiments/list.py
- dvc/repo/experiments/ls.py
- dvc/repo/experiments/pull.py
- dvc/repo/experiments/push.py
- dvc/repo/experiments/utils.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_remote.py
- tests/unit/command/test_experiments.py
- tests/unit/scm/test_git.py
Related to #4897.
* Adds `dvc exp list [--rev <rev>] [--all] [<git_remote>]` to list available local or remote experiments.
* Experiments will be organized according to their parent/baseline commit (same as in `exp show`).
* If `git_remote` is provided, command will list remote experiments, otherwise it will list local experiments. `git_remote` should be either a Git remote name (i.e. `origin`) or a full Git repo URL (supports all Git URL specs, HTTP/SSH/etc)
* If `--rev <revision>` is provided, all experiments derived from the specified revision will be listed (defaults to current HEAD).
* If `--all` is provided, all experiments (derived from any revision) will be listed.
* Adds `dvc exp push [-f] <git_remote> …
> experiments: add `dvc exp push/pull/list`

- dvc/repo/experiments/executor.py
- dvc/scm/git/backend/dulwich.py
- tests/func/experiments/test_experiments.py
Using dulwich for add/commit/is_tracked saves us around 700 calls to real git, which makes windows not crash.
> tests: fix windows tests

- dvc/parsing/__init__.py
- dvc/schema.py
Only handling it through schema for now. There have been some discussions on supporting parameterization on `vars`, so internals could be repurposed. Rushing with it for the pre-release builds. 
> parametrization: disable `set` keyword

- dvc/command/experiments.py
- dvc/command/gc.py
- dvc/repo/__init__.py
- dvc/repo/brancher.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/pull.py
- dvc/repo/experiments/push.py
- dvc/repo/experiments/utils.py
- dvc/repo/fetch.py
- dvc/repo/gc.py
- dvc/repo/push.py
- dvc/scm/git/backend/gitpython.py
- tests/func/experiments/test_remote.py
- tests/func/test_gc.py
- tests/unit/command/test_experiments.py
- tests/unit/scm/test_git.py
Will close #4897.
Will close #4440.
* Brancher now supports `all_experiments` for iterating over experiment commits
* `--all-commits`/`all_commits` for any DVC command now explicitly refers to all commits reachable through standard Git refs: `HEAD`, `refs/tags/*`, `refs/heads/*`, `remotes/refs/*`.
* Previously, it referred to all commits reachable through any ref in `refs/*`.
* This should not visibily affect behavior for DVC users unless they were using their own custom ref namespaces.
* Experiments are explicitly excluded from this list of commits.
* Adds `dvc gc --all-experiments` option to preserve cache for experiments.
* `dvc exp push` now pushes DVC cache for the experiment by default
* `--no-cache` will …
> experiments: support experiments cache collection for exp push/pull/gc

- dvc/info.py
When the cache dir is only a symlink to other file system, `dvc version` will provide a misleading result. This patch resolves and normalizes the `cache dir` so that it correctly detects the file system we're using.
adding a test for this is a little bit troublesome for me, I'm not very sure what I should test for.
Fixes #5065
> dvc info: follow the symlink when deciding filesystem type

- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/objects.py
- dvc/tree/git.py
- tests/func/test_tree.py
Very rough WIP to see how this goes. On gitlab example `dvc metrics diff`(aka the using GitTree part) upstream dvc takes ~26sec, and now it takes with both dulwich and gitpython backends around 7sec (clearly there are more optimizations to be done here). The main difference is that we build a trie that is then pretty simple to use and also more efficient than just walking through the git obj tree every time. The trie is getting fully built right now, but it could be easily built dynamically too.
> git: use backend-provided trie in GitTree

- dvc/repo/__init__.py
- dvc/repo/collect.py
- tests/func/metrics/test_common.py
- tests/unit/repo/test_repo.py
We try to optimize `tree.exists` calls and probably a few others
in that, they either look directly into the workspace or,
to the cache without running graph checks. It does not seem
to be possible just to run graph checks on `find_outs_by_path`
due to those optimizations.
So, that's why the `collect` also does a graph check for this
reason.
Fixes #5027
Fixes #4010
> Run graph checks on `collect`/`find_outs_by_path`

- dvc/scm/git/__init__.py
Saves us around 2sec (from ~7.5 to ~5.5) when parsing gitlab repo (dvc metrics diff).
> git: don't list all commits to check for an empty repo

- dvc/command/imp.py
- dvc/dependency/repo.py
- dvc/output/base.py
- dvc/repo/imp_url.py
- dvc/stage/__init__.py
- dvc/stage/imports.py
- dvc/stage/params.py
- dvc/tree/base.py
- tests/func/test_import.py
- tests/unit/command/test_imp.py
Fixes #4838
iterative/dvc.org/pull/2008
It works on my computer now, but some more tests are still needed.
> New option `jobs` for `dvc import`

- dvc/system.py
> system: _reflink_darwin: use fsencode for path 

- dvc/command/config.py
- tests/func/test_cli.py
- tests/func/test_config.py
- tests/unit/command/test_config.py
Currently we don't handle bad name well:
```
(dvc-3.8.3) ➜  dvc git:(config-bug) ✗ dvc config section
ERROR: unexpected error - not enough values to unpack (expected 2, got 1)
```
With this PR, we check name to conform to either `remote.name.option` or
`section.option`, so we'll give a more friendly:
```
(dvc-3.8.3) ➜  dvc git:(config-bug) ✗ dvc config section
ERROR: argument name: name argument should look like remote.name.option or section.option
usage: dvc config [-h] [--global | --system | --local] [-q | -v] [-u] [-l] [name] [value]
Get or set config options.
Documentation: <https://man.dvc.org/config>
positional arguments:
name           Option name (remote.name.option or section.option).
value          Option value.
optional arguments:
-h, --help     show this help message and exit …
```
> cli: config: check name format

- dvc/command/config.py
- tests/func/test_cli.py
- tests/func/test_config.py
- tests/unit/command/test_config.py
Backport of https://github.com/iterative/dvc/pull/5090
Currently we don't handle bad name well:
```
(dvc-3.8.3) ➜  dvc git:(config-bug) ✗ dvc config section
ERROR: unexpected error - not enough values to unpack (expected 2, got 1)
```
With this PR, we check name to conform to either `remote.name.option` or
`section.option`, so we'll give a more friendly:
```
(dvc-3.8.3) ➜  dvc git:(config-bug) ✗ dvc config section
ERROR: argument name: name argument should look like remote.name.option or section.option
usage: dvc config [-h] [--global | --system | --local] [-q | -v] [-u] [-l] [name] [value]
Get or set config options.
Documentation: <https://man.dvc.org/config>
positional arguments:
name           Option name (remote.name.option or section.option).
value          Option value.
optional …
```
> [1.11] [BACKPORT] cli: config: check name format

- dvc/ignore.py
Prevents us from duplicating the work by walking into directories
searching for subrepos. Saves around ~1sec (5.8 -> 4.8) in
`dvc metrics diff` in a big git-only repo. And around ~2sec (9.7 -> 7.7)
for `dvc status` in a repo with big undvcignored dirs.
Related to https://github.com/iterative/dvc/pull/4284#issuecomment-664033700
> dvcignore: don't walk directories twice

- dvc/repo/graph.py
RepoDependency, for example, don't have any path_info
See: https://github.com/iterative/dvc/pull/4938#issuecomment-743709176
Related: #5035
> Skip building graph for dependencies without path_info

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- tests/func/parsing/test_errors.py
> disallow overriding `item` and `key` in the foreach loop

- dvc/command/diff.py
- dvc/path_info.py
- dvc/repo/diff.py
- tests/func/test_diff.py
***
Will close #3388.
The filter code needs to be improved (something smarter than starts with) and I think an error needs to be outputted if the target parameter is not found in the list of tracked files or folders. The documentation will also need to be updated accordingly once this is merged.
For now I've started with the original behaviour the issue started with (optional `--target` arg). Let me know if the behaviour from comment https://github.com/iterative/dvc/issues/3388#issuecomment-590692837 would be preferred (`dvc diff [-h] [-q | -v] [-t TARGET] [--show-json] [--show-hash] [--show-md] [--hide-missing] [a_rev] [b_rev] [targets [targets]]`).
> diff: add support for --targets

- setup.py
Some libraries are starting to use networkx 2.5, which is the latest version released on August.
DVC however depends on networkx < 2.5, which causes some incompatibilities. This restriction was likely to prevent future breaking changes, since it was added before the release of 2.5 (https://github.com/iterative/dvc/pull/4219).
I've removed the version restriction, ran all tests and everything worked ok.
> Remove version restriction from networkx

- dvc/command/base.py
- dvc/command/experiments.py
- dvc/command/repro.py
- dvc/repo/experiments/run.py
- dvc/repo/reproduce.py
- tests/func/test_repro_multistage.py
- tests/unit/command/test_experiments.py
- tests/unit/command/test_repro.py
Currently, we iterate over targets manually in CLI, which results in a
complicated code and a DAG collection/check overhead. With this PR we
collect the DAG once, figure out all the needed targets within it and
just reproduce them in one pass.
Pre-requisite for #5082
> repro: accept multiple targets

- dvc/repo/params/show.py
Previously, `configs` which was a list of PathInfo was being used
to check if the `vars` should be skipped or not.
But, the file is stored as a string that made that check redundant
which might have caused #5117 as they were being stored twice,
once as an expanded paramdependency and next as a flattened dict
from vars, which later during `flatten`, it might have panicked
from that duplication.
> params diff: skip params dependency for vars

- dvc/repo/metrics/diff.py
- dvc/repo/params/diff.py
During diff, we were loading the stages from the current `repo.tree`'s state, from the workspace and from the revisions provided, which would collect 3-4 times (noticed while looking at the logs in https://github.com/iterative/dvc/issues/5117#issue-769158964).
This is good for using `params.diff()` and `metrics.diff()` as an API, but slows down the cli usage.
> params/metrics diff: collect from revisions/workspace twice

- dvc/parsing/__init__.py
- dvc/stage/__init__.py
- dvc/stage/loader.py
1. Simplified callback stage debug message
2. Reduced no lock entry message to trace
If lock file does not have some entry, it will simply complain
that lock file is not up to date once.
If there is no lock file or empty lock file, it will complain that lock file not found.
3. Annoying parametrization related wdir-interpolated debug message removed.
> Cleanup debug log messages when loading stages

- dvc/dependency/repo.py
- dvc/external_repo.py
- dvc/tree/repo.py
- tests/func/test_external_repo.py
The intended behavior is to not ignore subrepos but not follow them. Think about it as `os.walk` seeing symlinks but not following them unless `followlinks` is set to `True`.
This is one of the pre-requisites to simplifying and possibly getting rid of ExternalRepo.
> erepo: get rid of get_checksum

- dvc/lock.py
Fixes init order bug in `dvc.lock.HardlinkLock`
```
ERROR: unexpected error - 'HardlinkLock' object has no attribute '_tmp_dir'
File "/usr/local/lib/python3.6/dist-packages/dvc/main.py", line 75, in main
cmd = args.func(args)
File "/usr/local/lib/python3.6/dist-packages/dvc/command/base.py", line 40, in __init__
self.repo = Repo(uninitialized=self.UNINITIALIZED)
File "/usr/local/lib/python3.6/dist-packages/dvc/repo/__init__.py", line 141, in __init__
friendly=True,
File "/usr/local/lib/python3.6/dist-packages/dvc/lock.py", line 199, in make_lock
return cls(lockfile, tmp_dir=tmp_dir, friendly=friendly)
File "/usr/local/lib/python3.6/dist-packages/dvc/lock.py", line 148, in …
```
> lock: fix AttributeError in dvc.lock.HardlinkLock

- dvc/parsing/context.py
- tests/unit/test_context.py
---
Fixes one issue pointed out on #5165.
The error will look something like following in case of top-level `vars`:
```console
$ dvc repro
ERROR: failed to parse 'vars' in 'dvc.yaml': 'data' is a directory
```
> parametrization: fix error when the file in `vars` is a directory

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/base.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/reproduce.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- dvc/scm/git/stash.py
- dvc/stage/__init__.py
- tests/func/experiments/conftest.py
- tests/func/experiments/test_experiments.py
Will fix #5155.
* Unexisting outputs will be ignored on initial checkout (before experiment reproduction)
* Staged Git changes will be reset prior to running experiments in workspace (otherwise stash merge conflicts may occur if a staged file was previously an untracked file).
> experiments: fix checkout error for unexisting outputs

- dvc/command/config.py
- tests/func/test_config.py
Support the --show-origin option for config, which, similar to git,
prefixes each config option with the source file it originated from.
Fixes #5119
> cli: config: add support for --show-origin

- dvc/command/cache.py
- dvc/command/config.py
- dvc/command/remote.py
- dvc/config.py
- tests/func/test_cache.py
- tests/func/test_config.py
- tests/func/test_root.py
By default `dvc config` and `dvc remote` show `repo`-level config in read-mode, but they should really use merged config instead, same as `git config` does. In write-mode we are doing everything right and write to `repo`-level config by default.
Per #4841 and #5126
https://github.com/iterative/dvc.org/pull/2064
> config: read merged config by default

- dvc/command/config.py
- tests/func/test_config.py
Not yet supported https://github.com/iterative/dvc/pull/5126#pullrequestreview-555287092
This is a temporary limitation, we will support it ASAP. No docs updates are necessary.
> config: temporarily forbid --show-origin without level

- dvc/stage/cache.py
- dvc/stage/run.py
- tests/unit/stage/test_cache.py
> run-cache: skip unhashable stages

- dvc/command/config.py
- tests/func/test_config.py
Builds on #5126 and #5184 by showing the full merged config when
listing or getting config options.
References #5126
References #5184
References iterative/dvc.org#2028
Fixes #5119
> cli: config: show merged config with --show-origin

- dvc/stage/run.py
- tests/func/test_repro_multistage.py
Implements an approach proposed by @skshetry.
Fixes #4373
https://github.com/iterative/dvc.org/pull/2071
> dvc: handle multiline command as list

- dvc/command/diff.py
- dvc/command/metrics.py
- dvc/command/params.py
- dvc/command/plots.py
to match iterative/dvc.org/pull/2062
> dvc: std/update --targets options

- dvc/_debug.py
- dvc/cli.py
- dvc/main.py
It (https://github.com/joerick/pyinstrument) is easier and faster than cprofile, in that it can show stacktrace
of where things are slow.
<details>
<summary>Example Report</summary>
```console
_     ._   __/__   _ _  _  _ _/_   Recorded: 14:34:14  Samples:  7227
/_//_/// /_\ / //_// / //_'/ //     Duration: 12.487    CPU time: 7.442
/   _/                      v3.3.0
Program: /home/saugat/repos/iterative/dvc/.env/env39/bin/dvc dag --instrument
12.487 main  dvc/main.py:25
└─ 12.401 run  dvc/command/dag.py:94
├─ 5.872 _build  dvc/command/dag.py:87
│  └─ 5.872 _transform  dvc/command/dag.py:53
│     ├─ 5.545 __get__  funcy/objects.py:25
│     │  └─ 5.545 graph  dvc/repo/__init__.py:357
│     │     ├─ 5.292 __get__  funcy/objects.py:25
│     │     │  └─ 5.201 stages  dvc/repo/__init__.py:369 …
```
> Add pyinstrument: a statistical profiler

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/executor/local.py
- dvc/repo/reproduce.py
- dvc/scm/git/__init__.py
Will fix #5177.
Will fix #5176.
* SCM hints for workspace runs now shows relpaths instead of abspaths
* SCM hints for tempdir runs are suppressed since they have no meaning until `exp apply` is used
* Errors for tempdir runs are now logged inside executor child process instead of in the parent process
> experiments: fix logging bugs

- dvc/tree/local.py
- tests/func/test_add.py
We lack more tests for PATH_MAX and NAME_MAX across the board :slightly_frowning_face: 
Also need to catch initial internal checkout problems after add and provide some helpful message/mechanism to let the user know that the data is safe and can be recovered.
Fixes #5200 
> add: handle long filenames

- dvc/dvcfile.py
- dvc/parsing/versions.py
- dvc/schema.py
- dvc/stage/loader.py
- tests/func/test_dvcfile.py
- tests/func/test_lockfile.py
- tests/func/test_repro_multistage.py
- tests/func/test_run_multistage.py
- tests/unit/stage/test_serialize_pipeline_lock.py
- tests/unit/test_lockfile.py
- New version encloses all of the lock details of all the stages inside `stages` keyword.
- Previously it uses to be just a dictionary of lock details of stages.
- New `meta` keyword has `version` identifier. We could add more metadata there in the future.
- 1.0 will be read-only and will be migrated to 2.0 format when any of the stages in the lock file are reproduced (should there be a command?).
```yaml
copy:
cmd: cp foo bar
deps:
- path: foo
md5: d3b07384d113edec49eaa6238ad5ff00
size: 4
outs:
- path: bar
md5: d3b07384d113edec49eaa6238ad5ff00
size: 4
```
```yaml
meta:
version: '2.0'
stages:
copy:
cmd: cp foo bar
deps:
- path: foo
md5: d3b07384d113edec49eaa6238ad5ff00
size: 4
outs:
- path: bar
md5: d3b07384d113edec49eaa6238ad5ff00
size: 4
```
Thank you for the contribution - we'll try to …
> Add versioning scheme in the dvc.lock

- setup.py
Looks like new version does not depend on `pkg_resources`, thus it should make dvc's startup faster.
> package: Increment shtab's version

- dvc/external_repo.py
- dvc/repo/__init__.py
- dvc/repo/diff.py
- dvc/tree/repo.py
* Also removed dvcfile related imports on `dvc.tree.repo`. This was making imports slower on `dvc.main`.
* `repo.diff` uses only a single pre-initialized repo tree instance.
> repo.tree: make imports lazy

- dvc/parsing/interpolate.py
A great benefit to this is that, if the dvc.yaml file
is never interpolated, the parser is never built, which
reduces the gap even further between 1.0 and 2.0 files (except the `context` :( ).
> parametrization: do not load parser on import

- dvc/dvcfile.py
- dvc/parsing/versions.py
- dvc/schema.py
- tests/func/test_lockfile.py
- tests/func/test_run_multistage.py
- tests/unit/test_lockfile.py
I mistakenly merged the last PR (#5128) where we had `{"meta": {"version": "2.0"}}` format. Now it only has:
```yaml
schema: '2.0'
stages: ...
```
> Use 'schema' top-level element in the lockfile for version

- dvc/cache/__init__.py
- dvc/config.py
- dvc/config_schema.py
- dvc/tree/__init__.py
I was just trying not to load voluptuous/compile schema unless needed. It made an improvement of ~0.05s in my machine for `dvc --version`, not that big. But, I liked the separation between schema and the config, so making a PR.
```
├─ 0.106 <module>  dvc/main.py:1
│  ├─ 0.043 <module>  dvc/config.py:1
│  │  ├─ 0.014 <module>  voluptuous/__init__.py:3
│  │  │     [41 frames hidden]  voluptuous, decimal, _pydecimal, re, ...
│  │  │        0.002 loads  <built-in>:0
│  │  ├─ 0.009 <module>  configobj.py:16
│  │  │     [34 frames hidden]  configobj, re, sre_compile, sre_parse...
│  │  ├─ 0.006 <module>  funcy/__init__.py:1
│  │  │     [24 frames hidden]  funcy, inspect
│  │  ├─ 0.004 ByUrl  dvc/config.py:80
│  │  │  └─ 0.004 walk_values  funcy/colls.py:151
│  │  │        [17 frames hidden] …
```
> Split config and schema

- dvc/main.py
* Moved exception handling imports wherever they occur
* Move dvc.tree and dvc.external_repo imports to it's
nearest use, as it is expensive for `--version`.
* Move analytics import to when it's used
* Move format_link to place where error occurs
This reduces ~0.02s consistently for me, which puts me @ 0.15s for `dvc --version`.
> Make few imports lazy on dvc.main

- dvc/tree/s3.py
- tests/func/test_s3.py
The `MaxKeys` represents the number of items to fetch in one request, if `limit` is not supplied this takes forever and potentially creates tons of requests (I found out about this because my code literally stuck on `from_tree.isdir()` for a very long time on a massive dataset). This is what `limit` is for. We could have also potentially fixed this in the client code by changing `list()` into a `next(<test>, False)` call but fixing this makes it redundant and just a fix of a code smell so not going to bother with it.
```
from dvc.repo import Repo
from dvc.tree import get_cloud_tree
URL = "remote://private/dataset-registry-private"
repo = Repo()
from_tree = get_cloud_tree(repo, url=URL)
from_info = from_tree.path_info
import time
start = time.perf_counter() …
```
> S3Tree._list_paths now recognizes the max_items limit

- dvc/repo/__init__.py
- dvc/scm/base.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- tests/func/test_scm.py
[**UPDATE**]: Went to implement `scm._reset()` function and use `dulwich` by caching its `IgnoreManager`. Regarding `pygit2`, leaving as-is till the migrations.
---
If we start making a lot of `is_ignored` checks, `dulwich` is a lot slower than `pygit2`. I'm toying with the idea of not walking through `.gitignore`-d files/directories for `repo.stage` and `repo.graph` collection.
On master version, the performance on `dvc status` is following:
```console
Time (mean ± σ):      4.240 s ±  0.192 s    [User: 3.535 s, System: 0.474 s]
Range (min … max):    4.141 s …  4.781 s    10 runs
```
On a modified version that does not traverse through git-ignored directory, the performance with the `dulwich`/`gitpython` and `pygit2` respectively are:
```console
Benchmark #1: dvc status with dulwich
Time …
```
> scm: implement gitignore

- dvc/version.py
Looking at the log is confusing, as the version is stuck in `1.11.0` whereas the recent one is `1.11.10`.
As the updater is also dependent on that version, it prints an ugly update message while running too.
https://github.com/iterative/dvc/issues/5023#issuecomment-758450519
Even though we are not releasing right now, it'd be better to bump the version as it can be no longer considered as 1.X.
> dvc: bump to 2.0.0a0

- .pylintrc
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/apply.py
- dvc/repo/experiments/executor/base.py
- dvc/scm/base.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- tests/unit/scm/test_git.py
Finishes moving the remaining direct `gitpython` calls from experiments into `scm` and implements them in both `gitpython` and `pygit2` backends.
> git: implement merge/checkout via pygit2

- dvc/repo/experiments/__init__.py
- dvc/repo/reproduce.py
* Will fix #5230
* Will fix #5249
* Related to #5247
> experiments: exp res bug fixes

- dvc/system.py
mypy fails on non-windows machines because the `sys` module does not have `getwindowsversion`.
> system: prevent mypy from checking windows-related method

- dvc/dvcfile.py
- dvc/repo/experiments/run.py
- dvc/repo/run.py
- dvc/stage/__init__.py
- dvc/stage/utils.py
- dvc/utils/cli_parse.py
- tests/unit/test_run.py
- tests/unit/utils/test_cli_parse.py
Pre-requisite PR for #5253. Moving some code to `stage.utils` to reduce duplications, that might be there when we introduce `stage add/create`.
Also changed `loads_params_from_cli` and `parse_params_from_cli` to `loads_params` and `parse_params` respectively.
> refactor run; move to stage.utils

- dvc/stage/__init__.py
- dvc/stage/run.py
- tests/func/test_lockfile.py
- tests/func/test_repro.py
- tests/func/test_repro_multistage.py
- tests/func/test_run_single_stage.py
- tests/unit/stage/test_run.py
Old cmd + no deps definiton has been obsoleted since 1.0 in favor
of --always-changed and doesn't affect our ability to read history for
metrics/plots/etc so we are safe to drop the support for 2.0 onwards.
Fixes https://github.com/iterative/dvc/issues/1407
We don't have any mention of callbacks since 1.0 so no changes for docs required.
> dvc: redefine is_callback as cmd and no outs/deps

- tests/docker-compose.yml
- tests/func/test_tree.py
Azure tests started failing today with the release of azure-storage-blog 2.7.0 .
They still work with real azure, so this is on azurite's side.
```
2021-01-14T16:09:43.1140570Z     return client.upload(
2021-01-14T16:09:43.1141820Z   File "/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 233, in upload
2021-01-14T16:09:43.1142819Z     raise HttpResponseError(response=response, model=error)
2021-01-14T16:09:43.1145036Z azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'x-ms-encryption-algorithm header or parameter is not supported in Azurite strict mode. Switch to loose model by Azurite command line parameter "--loose" or Visual Studio Code configuration "Loose". Please …
```
> tests: upgrade azurite and enable loose mode

- dvc/cache/base.py
- dvc/cache/local.py
- dvc/output/base.py
- dvc/remote/base.py
- dvc/repo/__init__.py
- dvc/tree/base.py
- dvc/tree/local.py
- tests/func/test_add.py
- tests/unit/cache/test_local.py
- tests/unit/tree/test_tree.py
Trees shouldn't have anything to do with protect/unprotect logic, as it is a purely cache-related thing.
This PR does a naive move, without generalizing it for all cache types.
Pre-requisite for #5255 
> dvc: move protect from tree to cache

- dvc/output/base.py
- dvc/stage/__init__.py
- dvc/stage/run.py
This PR aims to make `Output` source of the execution environment for `Stage.run`. It seems that outputs are the cause of `env.`
Related: https://github.com/iterative/dvc/pull/4902#discussion_r542551178
> checkpoints/live: move execution env to stage

- dvc/command/stage.py
- dvc/repo/__init__.py
- dvc/repo/add.py
- dvc/repo/run.py
- dvc/repo/stage.py
- dvc/stage/utils.py
- tests/unit/command/test_stage.py
Refactoring and introducing `repo.stage.create_from_cli` instead of using ugly `utils` (directly).
Also clarified API names, docstring and code, especially around `validate_state`/`check_graphs`.
> use `repo.stage.create_from_cli` to create stages

- dvc/repo/experiments/apply.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- tests/func/test_install.py
- tests/unit/scm/test_git.py
Implements required functionality for workspace `git checkout` and `git checkout -b` (`get_ref/set_ref/iter_refs`, `resolve_rev`, `reset`) in pygit2 backend.
> scm: implement pygit2 resolve rev and native checkout

- dvc/command/remove.py
- dvc/stage/exceptions.py
> cli: remove: fix error message for the case when file is not under control (#4497)

- dvc/command/remove.py
During `-v`, we need to be able to see the traceback and the cause/context of the recent exception.
> cli: remove: Show traceback on verbose

- dvc/command/completion.py
- dvc/command/repro.py
- dvc/command/stage.py
- dvc/repo/__init__.py
- dvc/repo/stage.py
- dvc/stage/__init__.py
Autocompletion only limited to the `dvc repro` for now.
> Introduce stage:list command with autocompletions

- dvc/exceptions.py
- dvc/stage/exceptions.py
This happens because KeyError quotes the error message.
We'd still like to keep StageNotFound being a KeyError
semantics, but workaround the __str__ implementation.
Mypy was having some problem with the previous `__str__`
override.
> Override __str__ implementation for StageNotFound

- dvc/tree/hdfs.py
- dvc/tree/webhdfs.py
- setup.py
- tests/remotes/__init__.py
- tests/remotes/hdfs.py
- tests/remotes/webhdfs.py
- tests/unit/tree/test_hdfs.py
Raw POC for hdfs and webhdfs. Both mockers are library-level, not emulating real hdfs protocol or http.
Now all [web]hdfs tests run on all operating systems (previously only linux).
> tests: add basic [web]hdfs mockers

- dvc/cache/base.py
- tests/func/test_checkout.py
- One some cases (like `dvc checkout foo` where the `foo/` is the whole tracked directory) the `filter_info` is going to be equal to `path_info`, which we don't actually need to filter
- Also, if the origin is a file, then there is no literal need to filter the hash_info
> checkout: don't filter hash if it is a file

- dvc/ignore.py
- dvc/output/base.py
- tests/dir_helpers.py
- tests/func/test_check_ignore.py
- tests/func/test_ignore.py
- tests/unit/output/test_output.py
> dvcignore: Fix incorrect ignored output computation

- dvc/cache/base.py
- dvc/cache/local.py
- dvc/exceptions.py
- dvc/remote/base.py
- dvc/stage/cache.py
- dvc/tree/base.py
- dvc/tree/local.py
- dvc/tree/ssh/__init__.py
- dvc/tree/webdav.py
- dvc/tree/webhdfs.py
- dvc/utils/fs.py
- tests/func/test_cache.py
- tests/unit/stage/test_cache.py
- tests/unit/tree/test_tree.py
Moving cache-related modes from the tree to the cache itself. On our way to unify transfer/push/pull/save functionality into one, so that we could use them in the 3.0 cache format.
Pre-requisite for #5255 
> dvc: refactor cache saving

- dvc/command/stage.py
- dvc/repo/scm_context.py
- dvc/scm/base.py
- tests/unit/scm/test_git.py
- tests/unit/scm/test_scm.py
This way we can still use it in the `commands` that don't have a corresponding decorated API in the `Repo` (stage:add).
```console
$ dvc stage add foo -o bar -c "echo bar > bar"
Creating 'dvc.yaml'
Adding stage 'foo' in 'dvc.yaml'
git add .gitignore dvc.yaml
```
> show `git-add` hint on `stage:add`,  refactor scm_context

- dvc/exceptions.py
- dvc/utils/fs.py
Fixes #5255
We need a proper solution for #4832, will introduce later.
This reverts commit 8e738262adf78f081473d32419c2fbc07811da4b.
> Revert "utils/fs: checking files ownership in 'move' (#4348) (#4832)"

- dvc/command/experiments.py
Will fix #5266
Will close #5009
* User column order is now respected
* defaults to order within params/metrics file (same as other dvc metrics/params commands)
* if `--include-...` is used, order used in `--include...` will take precedence over the params/metrics file
* If multiple params/metrics files contain an identical key, filename will be prepended in the column name
> exp show: cleanup data column handling

- setup.py
Started getting this error today. Pytest 6.2.2 was released a few hours ago.
```
INTERNALERROR>     self.config.hook.pytest_runtest_logreport(report=rep)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR> …
```
> tests: limit pytest version by <6.2.2

- dvc/cache/__init__.py
- dvc/cache/base.py
- dvc/cache/gdrive.py
- dvc/remote/base.py
- dvc/tree/base.py
- dvc/tree/gdrive.py
`verify` property is used to tell dvc if it should trust the cache files that come from that particular cache and it has nothing to do with the fs tree.
Pre-requisite for #5255
> dvc: move 'verify' property from tree to cache

- dvc/cache/base.py
- dvc/cache/local.py
- dvc/output/base.py
- dvc/tree/base.py
- dvc/tree/local.py
- tests/unit/cache/test_local.py
Both of these are not fatal and could safely be ignored.
Fixes #5255
> dvc: ignore errors on protect/set_exec

- dvc/cache/base.py
- dvc/tree/azure.py
- dvc/tree/base.py
- dvc/tree/gdrive.py
- dvc/tree/gs.py
- dvc/tree/hdfs.py
- dvc/tree/http.py
- dvc/tree/local.py
- dvc/tree/oss.py
- dvc/tree/s3.py
- dvc/tree/ssh/__init__.py
- dvc/tree/webdav.py
- dvc/tree/webhdfs.py
- dvc/utils/fs.py
- tests/func/test_tree.py
- tests/unit/remote/test_azure.py
> tree: Implement upload_fobj protocol to all trees

- dvc/dvcfile.py
- dvc/repo/stage.py
- dvc/stage/exceptions.py
- tests/func/test_stage_load.py
- tests/unit/test_dvcfile.py
Closes #5244 
A few fixes has been made along the way, including:
* better error message if the dvc.yaml and .dvc files are dvc-ignored.
```console
$ echo "dvc.yaml" >> .dvcignore
$ dvc repro
ERROR: 'dvc.yaml' is dvc-ignored. 
```
* better error message if the dvc.yaml and .dvc files are git-ignored.
```console
$ echo "dvc.yaml" >> .gitignore
$ dvc repro
ERROR: 'dvc.yaml' is git-ignored.
```
An open question is, what should we do about lockfiles if they are git-ignored or dvc-ignored?
Right now, we assume the lockfile as empty if they are dvc-ignored and we don't care about git-ignores
for the lockfiles. I feel that this behaviour is good, but if we want them to be consistent, please do tell me.
Another thing to keep in mind is, since the implementation depends on `isinstance(repo.tree, …
> stage collection: do not collect .gitignored dvcfiles

- dvc/cache/base.py
- dvc/dependency/repo.py
- dvc/external_repo.py
- dvc/repo/__init__.py
- dvc/repo/diff.py
- dvc/repo/fetch.py
- dvc/repo/ls.py
- dvc/tree/dvc.py
- dvc/tree/repo.py
- dvc/tree/webdav.py
- tests/func/test_import.py
- tests/func/test_tree.py
- tests/unit/test_external_repo.py
- tests/unit/tree/test_dvc.py
- tests/unit/tree/test_repo.py
- tests/unit/tree/test_repo_metadata.py
When we collect cache for pull/fetch or run status -c, we implicitly try to fetch the dir cache entry from the remote. And that's the behaviour that is expected from RepoTree too. There have been multiple times where we've tried to use Repo.repo_tree just to realise that it tries to fetch automatically, which is often not needed. 
This PR is more of a POC that tries to get rid of `fetch` flag and the implicit fetching during walk() that it implies in favor of just fetching stuff explicitly where we really need it (repo has `fetch` method just for that already).
Need to check performance and also 2 `webdav` tests fail now because they don't have open() support, and Tree doesn't fetch things automatically, as expected by the api code.
Depends on https://github.com/iterative/dvc/pull/5307 …
> RepoTree: get rid if implicit fetching

- dvc/cache/base.py
- dvc/data_cloud.py
- dvc/repo/add.py
- tests/func/test_add.py
- tests/unit/command/test_add.py
> add: implement saving straight to cache

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/run.py
- tests/func/experiments/conftest.py
- tests/func/experiments/test_checkpoints.py
- tests/unit/command/test_experiments.py
Related to #5247
* `dvc exp run` will now resume the previous checkpoint run by default (if it exists)
* `dvc exp run -r/--rev <experiment_rev>` can be used to explicitly resume from a specific revision, if it is omitted the resume point will be determined based on the workspace state (using last run/applied experiment). This option will likely only be useful for queued/parallel runs.
* `dvc exp resume` has been removed
* `dvc exp reset` should be used to explicitly reset/restart a checkpoint run
> experiments: drop `exp resume` in favor of auto-resuming in `exp run`

- dvc/api/__init__.py
- tests/func/experiments/conftest.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_remote.py
- tests/func/experiments/test_show.py
Cuts `tests/func/experiments` from 137s to 84s on my machine
> tests: reduce checkpoint experiment iterations

- dvc/schema.py
- dvc/stage/serialize.py
- tests/conftest.py
- tests/unit/command/test_status.py
This was loosened when introducing parametrization.
But, `foreach`..`do` should be considered first
before the stage's regular structure. And, cmd is made
required (as it should have been)
Related: #5371, #5370, #5312
> don't allow loading stages without `cmd`

- dvc/command/data_sync.py
- tests/unit/command/test_data_sync.py
The `--glob` flag is parsed from the command line, but in the
`CmdDataPull` class in the invocation the parameter (`self.args.glob`)
is not passed to the `pull` method implementation. Hence, always the
default value (False) is used. This commit fixes this issue and sets the
`glob` parameter properly.
Related to #5353
> Pass missing `glob` flag to `pull` command

- dvc/repo/collect.py
Closes #4446 
Related https://github.com/iterative/dvc/issues/3943
I tried playing around with branches and unifying the `workspace/''` issue in its source, but it is material for the whole issue - simple replace won't fix it. So for now I unified the warning message when collecting.
> collect: unify message for no file in workspace

- dvc/command/run.py
- dvc/command/stage.py
- tests/func/test_cli.py
- tests/unit/command/test_stage.py
Fixes #5342 
https://github.com/iterative/dvc.org/issues/2134
> stage:add: use remainder as a command script

- dvc/command/experiments.py
- dvc/repo/experiments/apply.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_gc.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_experiments.py
After discussion with @dmpetrov and @dberenbaum, overwriting any conflicting workspace changes with `--force` should be the default behavior when applying an experiment commit. Due to the nature of how we hide git usage behind experiments, it is not obvious to the user why applying an experiment can cause git conflicts, and in typical use cases for `exp apply`, overwriting conflicting changes is likely the behavior the user was already expecting to begin with.
* `--no-force` can be used to disable overwriting existing changes
> exp apply: force apply by default

- dvc/command/experiments.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/show.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_experiments.py
Related to #5247
* Adds short form `-A/--all-commits` for `dvc exp show`
* Adds `-n/--num <num>` option for `dvc exp show` to show the last `n` commits from HEAD (defaults to 1)
* Fix issue where duplicate (empty) commit would be created for checkpoint runs with untracked files present in workspace
> exp show: cleanup UI issues

- dvc/repo/run.py
Prevent computing hashes of dependencies when
no_exec is set.
Fixes #5368
> run: do not compute hash when no_exec is set

- dvc/command/stage.py
- dvc/stage/__init__.py
- tests/unit/test_params.py
> keep stage.dump() and dvcfile.dump() in sync

- dvc/repo/add.py
- dvc/repo/imp_url.py
- dvc/repo/run.py
- dvc/stage/__init__.py
- dvc/stage/utils.py
- tests/func/test_run_multistage.py
- tests/func/test_run_single_stage.py
This is a legacy logic that we used to have before run-cache. At this point it is not needed and is broken in some scenarios.
Part of https://github.com/iterative/dvc/issues/4841
Related to #5368
Fixes https://github.com/iterative/dvc/issues/4529
> dvc: get rid of can_be_skipped logic

- dvc/config.py
- tests/unit/test_analytics.py
- tests/unit/test_updater.py
So that if you have updater disabled globally, tests don't fail/work as expected. Tests are mocked anyway.
> tests: mock global config dir for Updater

- dvc/command/update.py
- dvc/repo/update.py
- dvc/stage/__init__.py
- dvc/stage/imports.py
- tests/func/test_update.py
- tests/unit/command/test_update.py
> update: implement --to-remote flag

- dvc/tree/azure.py
- dvc/tree/gdrive.py
- dvc/tree/http.py
- dvc/tree/oss.py
- dvc/tree/webdav.py
- dvc/tree/webhdfs.py
The fact that our trees have `self.path_info` is really confusing and some cloud implementations sometimes accidentally use it instead of the explicitly provided `path_info`. As an endgoal, we should completely separate `self.path_info` and the tree (aka filesystem) itself. So the tree should accept itsown options during initialization instead of the whole config section with the url.
We've been doing things this way because long ago we only had remotes that acted as both remotes, caches and trees at the same time. `self.path_info` is used as a `cache` location, so it has nothing to do with the tree(aka filesystem).
We are already following that isolation nicely in the most places, but this PR tries to cleanup a few leftovers outside `__init__`, so we could get rid of `self.path_info` in …
> tree: stop using self.path_info outside of __init__

- dvc/command/experiments.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_show.py
Will fix #5402 
Will fix #5406
* `exp run` now displays metrics as expected with `-m`
* `exp show --sort-by ...` now handles metrics/params file names as needed (i.e. `--sort-by path/to/params.yaml:my_param`)
* If no path name is provided, will attempt to match against any metric/params file, if multiple possible matches are found an error will be returned
> experiments: bug fixes

- tests/remotes/azure.py
- tests/remotes/base.py
- tests/remotes/gs.py
- tests/remotes/hdfs.py
- tests/remotes/http.py
- tests/remotes/s3.py
- tests/remotes/ssh.py
- tests/remotes/webdav.py
- tests/remotes/webhdfs.py
- Moves `write_text` to `Base` to reduce duplications
- Move `Webdav` fixture to use `webdav` client rather than creating files/directories in the workspace.
This was done before to speed up tests, but we found out that they never worked before as they were never used.
From https://github.com/iterative/dvc/pull/5275#discussion_r569483334
> refactor webdav to use client; extract write_text to base remote fixture

- dvc/config_schema.py
- dvc/tree/s3.py
- dvc/utils/conversions.py
- tests/func/test_s3.py
- tests/unit/utils/test_conversions.py
> config: Support ~/.aws/config parsing

- dvc/cache/base.py
- dvc/cache/local.py
- dvc/dependency/repo.py
- dvc/output/base.py
- dvc/tree/ssh/__init__.py
- tests/func/test_run_cache.py
- tests/unit/stage/test_cache.py
Pre-requisites for merging save and transfer as well as separating trees and their path_info's, and for the upcoming ODB.
> cache: generalize save and checkout

- dvc/cache/base.py
- dvc/cache/local.py
- dvc/checkout.py
- dvc/dependency/repo.py
- dvc/output/base.py
- tests/func/test_run_cache.py
- tests/unit/stage/test_cache.py
Checkout is an operation that builds object from cache(aka object
database) in a particular tree(aka filesystem). Thus it shouldn't be
part of the object database itself nor of the filesystem.
Pre-requisite for #5337
> dvc: move checkout out of cache

- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- tests/unit/scm/test_git.py
While working on vscode-dvc, both @mattseddon and I found that this change allows
us to run `dvc exp run`, and we cannot run it with dvc master otherwise.
Neither of us know exactly what the other effects of this change are, and I'm hoping 
someone more knowledgeable can find out- after which we can also probably give 
this PR a better name.
> pygit2, gitpython: handle relpaths in reset/checkout_index backends

- dvc/command/add.py
- dvc/command/commit.py
- dvc/command/destroy.py
- dvc/command/imp.py
- dvc/command/imp_url.py
- dvc/command/move.py
- dvc/command/remove.py
- dvc/command/repro.py
- dvc/command/run.py
- dvc/command/update.py
- dvc/dependency/base.py
- dvc/dvcfile.py
- dvc/exceptions.py
- dvc/output/base.py
- dvc/repo/add.py
- dvc/repo/get.py
- dvc/repo/move.py
- dvc/stage/__init__.py
- dvc/stage/exceptions.py
- dvc/stage/utils.py
- tests/func/test_add.py
- tests/func/test_merge_driver.py
Fixes #3960 
Documentation on dvc.org was already updated before.
> term: replace 'DVC-file' and 'stage file' with correct terms (#3960)

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
Will fix #5404
* Untracked (new) `dvc.lock` files will be ignored entirely with regard to experiment runs. This is essentially an extension of the existing `git reset` behavior for tracked lock files during `exp run`.
> exp run: clean untracked lockfiles before running

- dvc/command/experiments.py
- dvc/utils/pager.py
- dvc/utils/table.py
- setup.py
Will close #5247
* Updates rich version to 9.x, uses native rich pager support
* Re-enables color/styling in exp show table
* When using `--no-pager`, columns will be collapsed in right-to-left order if the table cannot fit into the console
* At least one metric column and one params column will always be displayed whenever possible.
* Params will be collapsed before metrics
* If the table still does not fit after collapsing all but one metric and param column, will fallback to rich's folding behavior for the remaining columns
TODO
> exp show: customize rich table rendering behavior

- dvc/cache/base.py
- dvc/cache/local.py
- dvc/checkout.py
- dvc/objects.py
- dvc/remote/base.py
- dvc/repo/add.py
- dvc/system.py
- dvc/tree/local.py
- dvc/utils/fs.py
- tests/func/test_add.py
- tests/func/test_s3.py
Moving almost as--is for now, but both transfer and link could use some refactoring.
Pre-requisite for #5337 and #829
> cache: move unrelated helpers out of CloudCache class

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/gc.py
- dvc/repo/experiments/remove.py
- dvc/repo/experiments/utils.py
- tests/func/experiments/test_experiments.py
- tests/unit/command/test_experiments.py
Related to https://github.com/iterative/dvc/issues/5437
* Adds `dvc exp remove <experiment> [<experiment> ...]` command for removing specific (named) experiments
* `--queue` option can be used to clear the current experiment queue
> exp: add `exp remove` command

- dvc/command/experiments.py
- tests/unit/command/test_experiments.py
Related to https://github.com/iterative/dvc/issues/5413
* `dvc exp reset` command is removed
* `dvc exp run --reset` option can be used to reset/restart checkpoints
> exp run: remove `exp reset` in favor of `exp run --reset`

- dvc/command/metrics.py
- dvc/command/params.py
Fix typo from #5193 that broke displaying usage for params & metrics commands
```
$ dvc params diff -v --help
ERROR: unexpected error - unsupported operand type(s) for %: 'tuple' and 'dict'
```
> metrics/params: fix bug preventing usage from being displayed

- dvc/state.py
They've been used for gitignore before we've moved state to .dvc/tmp
> state: remove unused files property

- dvc/command/experiments.py
- dvc/repo/experiments/run.py
- dvc/utils/cli_parse.py
- tests/func/experiments/test_experiments.py
Will close #5302
Since `dvc exp run` is the only command that uses parameter _overrides_ (as compared with `dvc run`, where you are simply specifying a list of parameters), it makes sense for it have a separate parsing function. Conveniently, `dvc.utils.cli_parse.loads_params` is only being used by `dvc.repo.experiments.run.run`. So I renamed this function to `loads_param_overrides` for clarity and updated it to use the logic described in the source issue. I also updated the test to reflect the new possibilities.
I didn't see anywhere in the docs where `dvc experiments` is documented, otherwise I would open a PR there as well.
> exp run: Separate exp param parsing from other commands

- dvc/cache/base.py
- dvc/checkout.py
- dvc/fs/base.py
- dvc/fs/local.py
- dvc/objects/__init__.py
- dvc/objects/stage.py
- dvc/remote/base.py
- dvc/repo/checkout.py
- dvc/state.py
- tests/func/test_state.py
We used to think this way, but state is not really an fs concept
(fsspec's dircache is though), as it is a cache of hashes of objects
that we are staging, and the hash doesn't depend on fs, as it is usually
computed by us by reading from fs.
Pre-requisite for diskcache-based state.
> fs: detach state from fs

- .github/workflows/tests.yaml
- setup.py
- tests/remotes/gdrive.py
When trying to publish to pypi, we get:
```
Invalid value for requires_dist. Error: Can't have direct dependency:
"gdrivefs @ git+https://github.com/intake/gdrivefs.git ; extra ==
'tests'"
```
Related to https://github.com/intake/gdrivefs/issues/21
> tests: temporarily exclude gdrivefs from extras

- dvc/command/plots.py
Related to #5453 
Reason: running `dvc plots diff --help` resulted in error:
```
ERROR: unexpected error - unsupported operand type(s) for %: 'tuple' and 'dict'
```
> plots: fix bug preventing usage from being displayed

- dvc/command/stage.py
- dvc/utils/humanize.py
- tests/unit/utils/test_humanize.py
Moving text truncation to utils and adding tests for it
> stage:list: move truncating text logic to utils, add tests

- dvc/repo/add.py
- dvc/repo/imp_url.py
- dvc/utils/__init__.py
- tests/func/test_add.py
- tests/func/test_import_url.py
During the discussions on #5445, it seemed `--external` is redundantly needed when trying to add an absolute path in the local system without `-o`. This wasn't the case for remote locations, such as `s3://` or `azure://`. So this PR forbids the usage of `--external` with `to-remote`/`to-cache` and normalizes absolute system paths just like other remote providers.
> add, import-url: always resolve the output in the local path for --to-remote

- dvc/stage/imports.py
- tests/func/test_update.py
> update: forbid updating repo-imports with --to-remote

- setup.py
- tests/func/test_live.py
Our builds are timing out because pip is confused by
> dvclive 0.0.1a1 requires dvc==2.0.0a0, but you'll have dvc 2.0.0a1+e61136 which is incompatible.
and tries really hard to resolve conflicts.
> tests: temporarily skip dvclive tests

- dvc/checkout.py
- dvc/dir_info.py
- dvc/fs/dvc.py
- dvc/objects/__init__.py
- dvc/objects/stage.py
- dvc/output/base.py
- dvc/path_info.py
- tests/unit/test_dir_info.py
Trie takes quite a bit of time(over 3 sec for 400K dir, so status from 13sec goes down to 10sec) to serialize and deserialize into/from list (that's how we store dirs in .dir cache files). This PR just brings a previously lost optimization, while properly abstracting dir_info building/reading methods.
> dir_info: only build trie when needed

- dvc/repo/experiments/executor/base.py
- tests/func/experiments/test_experiments.py
Will close #5472
If experiment is run with a specific target, only its dependencies (and outputs for earlier pipeline stages) will be checked out before reproducing the target, rather than checking out the entire repo/pipeline.
> exp run: if target is provided, only checkout target and dependencies

- dvc/config_schema.py
This is something I noticed while writing docs for config vars. We support it in the tree though the config var isn't on the schema.
> azure: add account key to the config schema

- dvc/repo/plots/__init__.py
- tests/func/plots/test_show.py
> plots: ignore binary plot files

- dvc/dependency/gs.py
- dvc/fs/gs.py
- dvc/output/__init__.py
- dvc/output/gs.py
- tests/func/test_add.py
- tests/func/test_gc.py
- tests/func/test_import_url.py
- tests/func/test_output.py
- tests/func/test_run_multistage.py
- tests/unit/output/test_gs.py
Switch from `md5` to `etag` as the checksum parameter. Due to `etag`
is not preserved while doing server side copies, this patch drops support
for external gs outputs.
Resolves #5527
> gs: use etag for the checksum parameter

- dvc/fs/fsspec_wrapper.py
- setup.py
delete is a direct alias to rm(), though apparently it is kind of
broken on the latest release of gcsfs. This doesn't change any behavior
but only uses rm() directly instead of the given alias.
> gs: Use rm() instead of delete() calls

- dvc/repo/reproduce.py
- dvc/scm/git/__init__.py
- tests/unit/scm/test_git.py
discord context: https://discord.com/channels/485586884165107732/565759186693128202/816602671967764490
* `To track the changes with git, run: ...` reminder now only suggests `git add` for files which actually need to be tracked by the user rather than all possible files.
* If nothing needs to be tracked (because nothing was modified or the changes are already staged in git) the reminder will now be suppressed entirely
* Reminder output should now be consistent between `dvc repro` and `dvc exp run`
Previously, `exp run` reminder would include a list of files which are aggressively git-added to ensure that full repo state was included in experiment commits. The reminder for `repro` only included the user-expected …
> repro/exp run: use git status when reminding to git-track files

- dvc/fs/git.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/pygit2.py
gitpython and dulwich implementations are not thread safe, which forces us to set `hash_jobs` to `1`.
> fs: git: use pygit2

- dvc/utils/fs.py
Same as with `protect()`, these errors might happen if fs is immutable
or doesn't support chmod()-ing. We can safely ignore these.
Fixes #5552
> utils: makedirs: ignore chmod errors

- dvc/fs/gdrive.py
- setup.py
Resolves #5551, ~~awaiting iterative/pydrive2#97~~
> gdrive: use the normal file backend for saved credentials

- dvc/fs/ssh/connection.py
DVC did not always pass a timeout to Paramiko's `connect()`. This could cause DVC to hang indefinitely when e.g. fetching files from an SSH remote FS.
With this patch we pass a timeout to Paramiko, which should prevent this behavior.
> fs: ssh: pass timeout to paramiko's connect()

- dvc/fs/gdrive.py
This doesn't change any behavior regarding our serialization (the issue for that is #5580) but only changes the path so that we would unblock the release.
> gdrive: change the temporary directory location to .dvc/tmp

- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
The `GitPythonBackend.checkout()` method already implicitly supported this parameter because it forwards `**kwargs` to the backend. `pygit2` didn't support this yet.
This patch fixes this inconsistency.
Let me know if you'd like to see a test for this.
Related to https://github.com/iterative/dvc/issues/2215
> scm: add `force` parameter to BaseGitBackend.checkout()

- dvc/repo/experiments/executor/local.py
Will close https://github.com/iterative/dvc/issues/5595
Will close https://github.com/iterative/dvc/issues/5478
After the changes to use `dvc.utils.fs.remove` instead of `TemporaryDirectory.cleanup()` in https://github.com/iterative/dvc/pull/5425, on Python <3.8 on Linux, a skipped/ignored exception message would be logged and visible during DVC runs (with or without `-v`). This happened when `cleanup()` was called on deletion of the tempdir object - the directory itself had already been manually removed by DVC, and `FileNotFoundError` is logged (but not re-raised) to note that `cleanup()` expected to remove a directory which no longer exists. In other python versions, the ignored exception is just silently …
> exp: subclass tempfile.TemporaryDirectory to handle cleanup

- dvc/checkout.py
- dvc/objects/__init__.py
- dvc/objects/db/base.py
- dvc/objects/db/local.py
- dvc/objects/errors.py
- dvc/objects/file.py
- dvc/objects/stage.py
- dvc/objects/transfer.py
- dvc/objects/tree.py
- dvc/output/base.py
- dvc/remote/base.py
- dvc/repo/add.py
- tests/func/test_odb.py
- tests/unit/objects/test_tree.py
No functional changes, just getting a bit too crowded in `dvc/objects/__init__.py`
> objects: split into separate files

- dvc/command/plots.py
- tests/unit/command/test_plots.py
Closes https://github.com/iterative/dvc/issues/4179
```
$ dvc plots show --open
```
I don't know if this is that useful, but I think this does save some time (I was feeling the need when I was going through `example-get-started`).
No way to be compatible across different platforms. For me on Linux, it's following:
```
$ dvc plots show | xargs xdg-open
```
Working on macOS and on Windows (cc @jorgeorpinel?) confirmation would be great. 
> plots: support opening plots file directly in the browser

- dvc/scm/git/__init__.py
- tests/unit/scm/test_git.py
Related to https://github.com/iterative/dvc/issues/5594
Reverts git status reminder change from #5544
> repro/exp run: revert use git status when reminding to git-track files

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
Related to https://github.com/iterative/dvc/issues/5593
If the result of `exp run` is identical to the parent commit (HEAD), do nothing. Previously, for `--temp` runs we would do nothing, but workspace runs would generate an empty named experiment which was identical to HEAD.
> exp run: do nothing if result matches parent (HEAD)

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
Will fix https://github.com/iterative/dvc/issues/5567
> exp run: fix issue where duplicate workspace runs would incorrectly conflict

- dvc/fs/gs.py
GCSFile employs a strategy for checking the success of the save operation by calculating the md5 hash on write and then when the file is closed checking whether the written md5 hash matches with the response from the server. Even though this is the default mechanism, it doesn't work with composite objects. There is also a checker for 'size' (like ensuring the same amount of bytes are written) and 'crc32c' (AFAIK this is supported in composite objects) but I don't think we need any of those since none of the other implementations (like adlfs) directly supports it (they don't implement such checkers). So this patch disables checking and resolves #5604
> gs: disable consistency checker

- dvc/command/experiments.py
- dvc/output/base.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/run.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_experiments.py
Will close https://github.com/iterative/dvc/issues/5553.
Docs PR: https://github.com/iterative/dvc.org/pull/2286
Adjusts `dvc exp run --reset` behavior for `checkpoint` outs:
- When `--reset` is used, any `checkpoint` outs will be removed entirely before running the experiment (regardless of whether or not a hash for the given out exists in `dvc.lock`)
- When `--reset` is used, all other (non-checkpoint) outs in `dvc.lock` will be unchanged
- Previously, `--reset` would reset the entire `dvc.lock` file to HEAD (i.e `git checkout HEAD -- dvc.lock`)
- `--queue` now explicitly implies `--reset`, and `--reset` is now mutually exclusive with `--rev`
- This was essentially already the case but we now explicitly error …
> checkpoints: completely remove checkpoint outs on `exp run --reset`

- scripts/hooks/hook-googleapiclient.model.py
> _The Google API Discovery Service JSON files from [googleapiclient/discovery_cache/documents](https://github.com/googleapis/google-api-python-client/tree/6970659a84d0eec6ff72f59e906716036516922e/googleapiclient/discovery_cache/documents) were being excluded due to a bug and, particularly, [`drive.v2.json`](https://github.com/googleapis/google-api-python-client/blob/6970659a84d0eec6ff72f59e906716036516922e/googleapiclient/discovery_cache/documents/drive.v2.json) is essential for our gdrive backend. Now we're explicitly asking PyInstaller to embed these files on the generated packages._ **(Fixes #5618)**
> build: add pyinstaller hook for googleapiclient

- dvc/fs/gs.py
Directories doesn't have etag entries, so we need to skip processing them on _entry_hook
> gs: process etag when it is available

- dvc/fs/azure.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/gs.py
fsspec caches the instances, so even though we instantiate a new instance it might retrieve one from the cache since we use the same authentication options. The retrieved instances come with their listing cache which causes problems on the test suite (considering they all share a single instance). This patch disables instance caching for all file systems, and also unifies the credentials APIs
> fsspec: skip instance cache on all filesystems

- dvc/repo/diff.py
- tests/func/test_diff.py
We were trying to reuse the first encounter of the file from the inverted hashmap again and again, which was throwing ValueError.
Fixes #5597
> diff: clear calculated renamed files from inverted hashmap

- dvc/command/status.py
- dvc/main.py
- dvc/ui/__init__.py
I understand this is a bit controversial, but it seems that using this `ui` object globally is the best thing to do.
DVC tries to provide a sane `API` as well as `CLI`. Extending api to accomodate `ui` object (which is for `cli`) does not seem like a good thing, as it extends our API surface and makes it ugly. We'd also need to pass them to the depth of our APIs.
Similarly, we cannot just use `ui` object in CLIs, as our cli commands are usually just wrapper to the `Repo` apis. So, even if we try hard to separate them and isolate it inside the `CLI`, it'd be quite difficult.
Looking at it, and the purpose that `ui` object serves, it seems to me that it is a global singleton object anyway (an instance in a single session of CLI). And, we use `loggers` in a similar way, so I find it fitting …
> ui: use global singleton UI object for printing

- dvc/command/plots.py
- tests/func/plots/test_show.py
- tests/unit/command/test_plots.py
This commit fixes 3 things:
1. The path printed on the terminal is properly is quoted.  This was
problematic when the output is piped to `xdg-open` if the path contained
spaces or quotes or special characters.
```console
$ dvc plots show -o 'plots with spaces.html' | xargs xdg-open
xdg-open: unexpected argument 'with'
Try 'xdg-open --help' for more information.
```
2. The path is resolved. This is not an issue at all but makes the
output look nicer.
```console
$ dvc plots show -o '../plots.html' --open
file:///home/saugat/repos/iterative/example-get-started/../plots.html
```
3. The path with which the browser is opened with uses relative path.
This is done to solve issue in WSL, that the absolute path is not
accessible outside the WSL for host programs as the linux filesystem
is available …
> plots: quote and resolve paths properly

- .github/workflows/packages.yaml
lxml wheels are built with an old SDK, which breaks osxpkg notarization:
```
* error for path "dvc-2.0.7.pkg/dvc-2.0.7.pkg Contents/Payload/usr/local/lib/dvc/lxml/etree.cpython-37m-darwin.so": The binary uses an SDK older than the 10.9 SDK.
```
> build: osxpkg: build lxml

- setup.py
- test_requirements.txt
Plan is to add dependabot to update those packages required for testing, after this gets merged.
> Move tests requirements to test_requirements.txt

- .pre-commit-config.yaml
- dvc/fs/ssh/connection.py
- dvc/utils/table.py
`black` has some issues with docstrings, so skipping that. 
Also fixed mypy errors:
1. Casting `columns` to the custom Column with collapse.
2. Ignoring typedef difference for RichTable._collapse_widths.
3. Suppressing error with conditional paramiko imports
https://github.com/python/mypy/issues/1153
> dvc: update precommit hooks

- setup.py
The recent release of rich-10 broke the internal API that we were depending on
for `exp show`. See https://github.com/iterative/dvc/issues/5722
Limiting it to `<10` till it gets fixed.
> deps: limit rich version to <10

- dvc/command/experiments.py
- dvc/utils/table.py
- setup.py
The signature of `__rich_measure__` has changed with the version change, see [changelog](https://github.com/willmcgugan/rich/blob/master/CHANGELOG.md#1000---2021-03-27). This should be able to fix that to keep compatibility
Fixes #5722
> dvc: fix breakage with rich==10.0.0

- dvc/ui/__init__.py
- tests/conftest.py
- tests/unit/ui/test_console.py
Before, we used to set it during initialization. But this
made it hard to test using capsys as capsys changes the
reference to sys.stdout and sys.stderr with the mocked one
during the test. But since we are using dvc.ui globally and
setting it to a real sys.stdout and sys.stderr before capsys
comes into effect, testing was not possible with it.
Now, by using property hack, we will be using the values of
sys.stdout and sys.stderr during the time of write, so the mocking
would work and would be easier to test.
> ui: Use sys.stdout and sys.stderr dynamically

- dvc/parsing/context.py
- tests/func/parsing/test_resolver.py
We were joining the paths in the following way: 
https://github.com/iterative/dvc/blob/09cb49542364694f2eec84f61b63e40ae8dcd05f/dvc/parsing/context.py#L404
This created the path such as `PosixPath: dir/../params.yaml`, which broke on GitFS when trying to get the key of the GitTrie,
as it is now changed to `('dir', '..', 'params.yaml')` parts instead of just `(params.yaml,)`.
Similarly, LocalFS.exists was also failing because of the unresolved path.
This is fixed by changing it to abspath first, removing those relative paths and then converted into `PathInfo`.
Closes https://github.com/iterative/dvc/issues/5731
> parsing: resolve relative paths when loading parameters

- dvc/fs/webdav.py
The assumption that the root of the URL to be `/` is incorrect. Just rolling back the changes made in b87e76aa84492 for the webdav.
No tests added as it's hard to test this, without changing the server root address. This was working before and I did verify it locally.
Fixes #5588 
> webdav: use root url to check and on mkdir to find recurse depth

- dvc/command/status.py
- tests/unit/command/test_status.py
This is achieved by using `lock_repo` context manager that can be used in a recursive depth that only resets stages when it has left any lock_repo blocks.
Also added some UI related tests for the status which I found missing.
Fixes #5621
> status: collect stages only once

- dvc/config_schema.py
- dvc/fs/s3.py
- tests/unit/fs/test_s3.py
Added the parameter to allow the use of SSL without the SSL verification. This uses the similar named boto3 parameter. 
Fixes #3450
> Added SSL verification option

- dvc/utils/table.py
In `exp show` we merge adjacent collapsed (minimum width) columns into a single column containing `…`. Prior to https://github.com/willmcgugan/rich/commit/2f752afaa931d67664967100bc990de3c6f6abbc rich assigned collapsed columns a minimum width of 1, after that commit the minimum width became 0.
Will close #5722
> exp show: fix column collapse behavior

- setup.py
3.10 has wheels for Python3.9 in Windows.
> Update pycryptodome to 3.10

- tests/__main__.py
- tests/unit/test_imports.py
Encountered some issues with python on windows. We should use `sys.executable` instead. 
This does not fix all of the issues, we still use `python` in a lot of our test stages, but they did not fail as they only depend on stdlib. Though we should fix this soon.
> use sys.executable instead of hardcoded python

- tests/unit/fs/test_hdfs.py
We modify the environment when passing env through the subprocess which changes some environment variables when pyenv is detected. 
https://github.com/iterative/dvc/blob/19d0b2af56633886f9272732b14195cd4ee322f8/dvc/fs/hdfs.py#L37
In the assertion of the test, we should also check this with the modified expected env vars (not to the real envvars).
This was making the tests fail when using pyenv.
> Fix test assertion with environment when using pyenv

- setup.py
fsspec 0.9 contains a lot of breaking changes, and since it is released yesterday some remote's haven't adapted using (adlfs) it and some others doesn't reference it properly (e.g gcsfs). `gcsfs==0.8` (should) require `fsspec>=0.9` but `adlfs==0.7` require `fsspec<0.9`. Until `adlfs` is updated to support new async system on the `>=0.9`, we can't update our versions. This patch fixes the ambigous dependencies to a certain version in order to not have any conflicts.
> setup: fix all fsspec remote versions

- dvc/fs/azure.py
This resolves the authentication issues highlighted in #5511. Before I was getting authentication failures with DefaultAzureCredential, now auth seems to succeed but I still face the problems in #5556 which make this hard to test beyond the fact that the error has changed from auth to threading.
EDIT: Hacked azure.identity.aio so that it doesn't complain by disabling asyncio.Lock - with this done I no longer get the treading errors of #5556 and auth works fine! Not really sure what is the cause of the threading issues and this clearly isn't a viable solution though...
> azure: use account_name with default credentials

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
Will fix https://github.com/iterative/dvc/issues/5628
Docs PR: https://github.com/iterative/dvc.org/pull/2348
> exp run: --reset no longer implies --force

- dvc/command/experiments.py
- tests/unit/command/test_experiments.py
> exp run: jobs should default to 1

- dvc/fs/base.py
- dvc/fs/ssh/__init__.py
- dvc/objects/db/base.py
- dvc/objects/db/ssh.py
- dvc/remote/base.py
- tests/unit/remote/test_base.py
> remote: use configured jobs number

- dvc/types.py
- dvc/ui/__init__.py
- dvc/ui/table.py
- dvc/utils/pager.py
- tests/unit/ui/test_table.py
This PR try to unify the tables behind the same abstraction (with facade?). 
A few possible abstraction has been left out, eg: unifying pagers and trying to use rich more. A temporary workaround exists for rich console, as it didn't work well with capsys during testing, and I was unable to figure out why it's happening. 
I also added a support for borders, and row styles in this PR for the rich table.
> ui: unify tables

- setup.py
With the adlfs's 0.7.1 release, we should be fine to update fsspec to 0.9 which would allow us to use newer versions of s3fs and gcsfs at the same time with adlfs.
> fsspec: update to 0.9 (including remotes)

- dvc/repo/__init__.py
- tests/func/test_api.py
This part of logic used to be only used by external repo for cloned
repos, but since we now handle local repos without cloning, we don't
always pass scm instance. This PR automatically creates scm instance
for such cases.
Fixes #5590
> repo: handle rev without scm

- dvc/command/experiments.py
Will close #5814
Docs PR https://github.com/iterative/dvc.org/pull/2383
> exp run: disallow --rev for workspace runs

- dvc/repo/diff.py
- dvc/repo/experiments/diff.py
- dvc/repo/experiments/show.py
- dvc/repo/experiments/utils.py
- dvc/repo/metrics/diff.py
- dvc/repo/params/diff.py
- dvc/repo/plots/diff.py
- dvc/scm/git/__init__.py
- tests/func/experiments/test_experiments.py
- tests/unit/repo/plots/test_diff.py
Will close #5750 
[![asciicast](https://asciinema.org/a/xTMncLndoFtOkwuSARH1GLfY9.svg)](https://asciinema.org/a/xTMncLndoFtOkwuSARH1GLfY9)
This PR addresses the issue in `exp show`, `exp diff`, `metrics diff`, `params diff`, `plots diff`, `dvc diff`
> exp: use exp baseline for DVC commands that compare to HEAD during `exp run`

- .github/workflows/tests.yaml
Due to https://about.codecov.io/security-update/ , there is a potential that we've leaked these. This PR takes a more granular approach when setting secret env vars so that this doesn't happen in the future.
We'll change these secrets after this PR is merged.
> gha: tests: don't set sensitive env secrets for all steps

- dvc/command/metrics.py
- tests/unit/command/test_metrics.py
`metrics show --precision <value>` was ignored due to it is never passed the underlying `_show_metrics` function.  Resolves #5840
> metrics: pass --precision to _show_metrics

- dvc/command/live.py
- dvc/command/plots.py
- dvc/config_schema.py
- dvc/repo/live.py
- dvc/repo/plots/__init__.py
- dvc/utils/html.py
- tests/func/utils/test_html.py
Initial implementation allowing custom HTML webpage template.
I decided just to allow users provide their own HTML, as long as there is `{plot_divs}` format string inside, so that we don't have to deal with additional args like `--vega-path` `--vega-lite-path` `--vega-embed-path` which would be necessary if we were to handle the template on our own, in `dvc` code.
How one can utilize new functionality :
```
#!/bin/bash
set -ex
rm -rf repo
mkdir repo
pushd repo
echo '[{"m":1},{"m":2},{"m":3}]' >> plot.json
echo '<html>
<head>
<script type="text/javascript" src="VEGA_PATH"></script>
<script type="text/javascript" src="VEGA_LITE_PATH"></script>
<script type="text/javascript" src="VEGA_EMBED_PATH"></script>
</head> …
```
> html: enable providing custom html page templates

- dvc/objects/db/base.py
- dvc/objects/file.py
When adding new objects with `odb.add()` when the `odb.verify` is set to False (or defaulted to False, which happens on almost all remotes except GDrive), instead of recomputing the hash again we'll simply check the existence of the cache file and not verify the contents. This speeds up the `dvc update --to-remote` by  %15 (from `2.49 minutes` to `2.24 minutes`). Part of #5768
> objects: don't recompute hash on odb.add() if verify is False

- dvc/data_cloud.py
- dvc/output/base.py
- dvc/remote/base.py
- dvc/repo/add.py
- dvc/repo/imp_url.py
- dvc/stage/imports.py
Removes `DataCloud.transfer`/`BaseRemote.transfer` and introduces `BaseOutput.transfer`. Part of #5768
> output: introduce BaseOutput.transfer

- dvc/repo/commit.py
- dvc/repo/experiments/__init__.py
- dvc/stage/__init__.py
- tests/func/experiments/test_experiments.py
Will close #5593
- Data dependencies are now `dvc commit`ed internally when stashing an experiment so that any modifications to that data dep are preserved in both workspace and tempdir runs (previously the changes were dropped entirely by the `exp run` `dvc checkout` step).
> exp run: `dvc commit` DVC-tracked data deps when stashing an experiment

- dvc/command/plots.py
- dvc/command/unprotect.py
```
dvc --help
```
The description of some commands does not end with a full stop. It is a stupid PR but for some reason this inconsistency stood out in my eyes.
> Add full stops in CLI help

- dvc/command/experiments.py
- dvc/command/metrics.py
- dvc/command/params.py
- dvc/command/repro.py
- dvc/compare.py
- tests/basic_env.py
- tests/func/metrics/test_diff.py
- tests/func/test_repro.py
- tests/unit/command/test_metrics.py
- tests/unit/command/test_params.py
- tests/unit/test_compare.py
We have introduce `ui.table()` elements and new data structure in #5852. This will unify all diffs/show into `dvc.compare` module and will make use of the new tabular data structure and the new `ui.table`. I am really sorry for quite a large PR (most of those are the test changes).
Fixes #5576 and fixes #5591.
> refactor diff and show to use new table ui and new data structure

- dvc/command/experiments.py
- dvc/compare.py
- tests/unit/test_tabular_data.py
It might not be apparent from the PR on why I am doing this. Basically, I am trying to separate the presentation logic with the other business logics. The indent guide seems to be a `rich-table` only thing. For example, if we have a `--show-md`, it might not make much sense to have that tree (but it can be there if we want to on a separate presentation logic). 
> exp show: separate ui representation of exp names and identifiers

- dvc/fs/base.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/gdrive.py
- dvc/fs/s3.py
- dvc/fs/webdav.py
- dvc/objects/stage.py
- tests/func/test_fs.py
Resolves #5877. This patch also drops ls(recursive=True) option and replaces all usages with the new fs.find() (fsspec compliant API).
> fs: introduce fs.find()

- .github/dependabot.yml
Seems to fit better into our current labels and makes release drafter generate proper changelogs.
> dependabot: use "maintenance" label

- dvc/scm/git/backend/pygit2.py
Will close https://github.com/iterative/dvc/issues/5641
> pygit: force release of odb contexts after checkout/merge

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/apply.py
- dvc/repo/experiments/base.py
- dvc/scm/git/__init__.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_show.py
Will close #5737, see original issue for full discussion of changes
After this PR
- Checkpoints can only be resumed (with no modifications) from the head of a checkpoint run. (New checkpoint branches with modifications can still be created from any intermediate or head checkpoint)
See example:
1. apply ambiguous commit and run with no modifications (error with no modifications)
2. apply ambiguous commit that is an exact match for a head and run with no modifications (resume from the exact matching head)
3. apply non-ambiguous commit and run with no modifications (error with no modifications)
[![asciicast](https://asciinema.org/a/BsdI6cf78qTYhlNTKsoApSm52.svg)](https://asciinema.org/a/BsdI6cf78qTYhlNTKsoApSm52)
> exp run: error out when trying to resume from intermediate checkpoint w/no modifications

- tests/func/test_scm.py
I experimented increasing max_run number, even to a very high number: 1000. Even in that case, it failed 947 times. So I don't really see a reason to mark it as flaky. Anyway, we are treating it as xfail by keeping it failing in the CI, so this PR does not change anything for us. :)
> tests: mark test_stash_pop as xfail on linux

- dvc/output/local.py
We need to resolve path_info to compare with `path_isin` with the `Repo`'s root. This is because we use a resolved path for the repo's root whereas for the output, it is just abspath. We could change the output's path_info, but to really make a change, we'd need to fix all of Stage, Output and Dependencies. This seem to be easiest to me.
Motivation: Test failures in https://github.com/iterative/dvc/runs/2498067350#step:10:10248.
> output: resolve path for path_isin checks

- setup.cfg
- tests/conftest.py
- tests/func/test_add.py
- tests/func/test_api.py
- tests/func/test_data_cloud.py
- tests/func/test_fs.py
- tests/func/test_import_url.py
- tests/func/test_update.py
- tests/unit/remote/test_remote_tree.py
We just need to mark them with `needs_internet` marker.
Unfortunately, it's not possible to do that automatically
with the fixtures as fixtures are per-session and we need
something on higher level (which the marker is not passed
through in the pytest).
Part of https://github.com/iterative/dvc/issues/5781
> tests: rerun gdrive and gs on failures

- dvc/repo/move.py
- dvc/stage/utils.py
- tests/func/test_move.py
Will close #5886 
- `dvc move` now uses `repo.stage.create` to create the new destination stage instead of just modifying the existing `stage.path` in order to do the necessary validation (check if dest overlaps with existing output, new `.dvc` file would be gitignored, etc)
> move: validate new stage before move

- dvc/command/commit.py
> commit,completion: Add stages completion for dvc commit

- dvc/command/base.py
- dvc/command/init.py
- dvc/info.py
- dvc/main.py
- dvc/repo/__init__.py
- tests/basic_env.py
- tests/dir_helpers.py
- tests/func/test_add.py
- tests/func/test_checkout.py
- tests/func/test_cli.py
- tests/func/test_run_single_stage.py
I have a feeling that it is causing the issues with shutil.copytree and some PermissionError during 'init', as we are not closing it between multiple 'main()' calls. But I am not quite sure, and this seems like a good thing to do anyway.
The error message could be seen in https://github.com/iterative/dvc/runs/2498067244#step:10:5463:
```console
D:\a\dvc\dvc\tests\basic_env.py:110: UserWarning: Failed to remove test dir: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\dvc-test.6432.9i20lxfe.CKjKY6gtu6d33MzUazViLz\\.dvc\\tmp\\links\\cache.db'
5464
warnings.warn("Failed to remove test dir: " + str(exc))
```
And, I think it might be causing [these kinds of …
> try to close dvc.state on exit

- setup.py
Since `aiobotocore` already hosts an extra with it's own pinned boto package, there is no need for us to also maintain versioning for boto too. This might also create conflicts since aiobotocore's version might not be always pinned, and different aiobotocore versions might depend on different botocore versions (which @shcheklein reported).
> setup: freeze aiobotocore/botocore/boto3 versions

- dvc/fs/git.py
- dvc/fs/local.py
- dvc/ignore.py
- tests/unit/test_ignore.py
`fs_root` no longer makes sense after decoupling `fs` and `dvcignore` and needs to go for fsspec migration.
> fs: get rid of fs_root

- dvc/rwlock.py
A minor typo fix.
`If there are no processes with such PIDs, you can manually remove'.dvc/tmp/rwlock' and try again.` 
->
`If there are no processes with such PIDs, you can manually remove '.dvc/tmp/rwlock' and try again.` 
> rwlock: add missing space to the message

- setup.py
- tests/conftest.py
- Related to https://github.com/iterative/dvc/issues/2215
- Will close https://github.com/iterative/dvc/issues/5684
- Will close https://github.com/iterative/dvc/issues/5638
> git: update dulwich to 0.20.22

- setup.py
> setup: bump fsspec/s3fs/gcsfs to 2021.5.0

- dvc/command/checkout.py
- dvc/ui/__init__.py
- tests/func/test_checkout.py
- tests/func/test_data_cloud.py
- tests/unit/command/test_checkout.py
This PR adds a `styled=True` arg, which will use `rich` for printing, which means we can use it to format the string segments with `[red]` kind of syntax (see the changes in the checkout). 
Though I am still not sure that much of this PR, on whether this should be a special API (`printf`? 😄) or just the way it is in this PR.
I am just putting this out there, so any suggestions/feedback will be welcomed.
> [RFC] ui: write gets a styled param with rich console printing

- dvc/command/stage.py
- tests/unit/command/test_stage.py
We get the `cmd --flag ""` as `["cmd", "--flag", ""]`, so we have to parse the empty string back to the. double quotes.
Fixes #6072
> fix empty string parsing for the command

- dvc/command/run.py
- tests/unit/command/test_run.py
- tests/unit/command/test_stage.py
- tests/utils/asserts.py
We are already at 27 arguments that are passed to the `Repo.run`.
> use kwargs when passing command line args to run

- .pylintrc
- dvc/checkout.py
- dvc/command/destroy.py
- dvc/command/experiments.py
- dvc/command/gc.py
- dvc/fs/http.py
- dvc/fs/ssh/__init__.py
- dvc/logger.py
- dvc/output.py
- dvc/path_info.py
- dvc/progress.py
- dvc/repo/get_url.py
- dvc/stage/__init__.py
- tests/unit/command/test_experiments.py
- tests/unit/command/test_repro.py
- tests/unit/test_daemon.py
`astroid==2.5.7` has improved inference and was throwing
errors that were false negatives before. Fixing these
and ignoring some.
Also opened https://github.com/PyCQA/pylint/issues/4527 for discussion on keeping `astroid` pinned in the `pylint` to avoid surprises.
Closes #6080.
> fix errors raised by pylint

- setup.py
2.1 is more than 3 years old, whereas the latest version 2.5 was released in Aug, 2020.
I am a bit hesitant to add an upper bound here as networkx seems to be requiring a lot of dependencies from the next version onwards.
2.1-2.3 versions were probably not compatible with Python3.9. 
Discord context: https://discord.com/channels/485586884165107732/485596304961962003/848943242481369088
> pin networkx to 2.5

- dvc/fs/azure.py
- tests/unit/fs/test_azure.py
Part of #5797. Implements the `allow_anonymous_option` and support for anonymous logins.
> azure: better error messages / allow_anonymous_login option

- dvc/fs/azure.py
- dvc/fs/oss.py
- tests/remotes/azure.py
- tests/remotes/oss.py
Currently, we have a bit of a mess, where s3 and gs don't create buckets automatically, but azure and oss do. The safe approach here is to simply not create buckets in any of the filesystems. Local/ssh and others are a bit different, as there is no such thing as bucket there, and nonexistend directories are logically part of the path/prefix and not a standalone resource like buckets are.
Pre-requisite for getting rid of fs.path_info.
Fixes #2101
> fs: don't automatically create buckets

- dvc/config_schema.py
- dvc/fs/s3.py
- tests/unit/fs/test_s3.py
- tests/unit/test_config.py
`botocore` allows a path to a custom CA bundle either by passing a path to the CA bundle file into the verify argument of `boto3.session.Session.client` (see https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html) or passing `None` (the default) which will fall back to the AWS config. Previously, the DVC config only accepted a
boolean into the `ssl_verify` option in the remote S3 config. This changes the DVC config to accept both string and `None` in addition to boolean and defaults to `None`. I also changed the default for `ssl_verfiy` to `None` in `BaseS3FileSystem`. Thus, if `ssl_verify` is not provided, `botocore` will fall back to the AWS config.
Unit tests to cover the changes to the config schema and additional `ssl_verify` types that will be passed …
> config, remote: Made S3 CA bundle customizable

- dvc/fs/fsspec_wrapper.py
- dvc/objects/db/base.py
- tests/func/test_data_cloud.py
This is a temporary fix for #6089. It disables the partial prefix (`00/0`) search optimization entirely for all fsspec implementations and does it in the regular way (with only listing the full path of `00/`). This API is not actually supported to be optimized on the fsspec side so we will wait for all the clouds we support (s3, azure, google cloud) and then turn on the optimization (In the `ObjectFSWrapper`) this time with just fixing the custom `find()` method in the subclass.
> fs: temporarily disable prefix-based search for fsspec-implementations

- dvc/fs/webdav.py
- setup.py
- tests/remotes/webdav.py
- tests/unit/remote/test_webdav.py
Here's the fetch speed comparison between the two libraries:
[![asciicast](https://asciinema.org/a/dSrJbWLziKcBgvGvU2DZqCScU.svg)](https://asciinema.org/a/dSrJbWLziKcBgvGvU2DZqCScU)
[![asciicast](https://asciinema.org/a/fReef1N6FsTZw8tv1WEHFgz7h.svg)](https://asciinema.org/a/fReef1N6FsTZw8tv1WEHFgz7h)
TODO:
Additionally, while we are at it, it'd be great to support:
> webdav4: migrate to new library 

- dvc/utils/__init__.py
- tests/unit/utils/test_utils.py
Since python 3.8 os.path.realpath has resolved windows network shares
to UNC paths. This breaks the logic for relpath as the UNC and mapped
drive paths don't have an obvious common prefix. As it is not easy to go
back to the mapped drive path from UNC path, this is resolved by always
using the UNC paths for calculating relative paths in windows.
Fixes #5832
> add: prevent crash while getting relpath

- dvc/config_schema.py
- dvc/fs/webdav.py
- tests/unit/remote/test_http.py
- tests/unit/remote/test_webdav.py
https://github.com/iterative/dvc.org/pull/2547
Similar to `ssl_verify` done in https://github.com/iterative/dvc/pull/6018 for s3.
> http/webdav: support specifying custom certs in `ssl_verify`

- dvc/fs/__init__.py
- dvc/fs/webdav.py
- dvc/fs/webdavs.py
- setup.py
- tests/unit/remote/test_webdav.py
- Added timeout config back.
- Brings back the support for specifying user in the URL itself.
- Keep the Webdavs in the same file.
- Improves upload by as much as 20%, just by removing `exists` calls during upload.
> webdav: minor updates

- dvc/fs/base.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/gdrive.py
It was turned off due to not all providers supporting `find(<something>, prefix=<something>)` but now it is safe to turn that back on. Resolves #6089.
> s3, gs, azure: re-enable prefix-based search optimization

- dvc/utils/serialize/_common.py
- tests/unit/utils/serialize/test_yaml.py
Fixes https://github.com/iterative/dvc/issues/6192
This ensures that any `UnicodeDecodeError`s that can be raised by `file.read()` are raised in a more structured manner. Additionally, expose the path that the exception was raised in. This will help us handle problems with files like this in Studio.
Please let me know if you'd like to have a different exception name or there is anything else that needs to be considered here :)
(Also, apologies if I asked for the wrong people to review this. I used GitHub's reviewer suggestions)
> serialize: Wrap `UnicodeDecodeError`s

- dvc/repo/move.py
- tests/func/test_move.py
Fixes #6200 
copy meta from src file stage to target file stage
> repo: preserve meta field on move

- dvc/fs/base.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/gdrive.py
- dvc/fs/hdfs.py
- dvc/fs/http.py
- dvc/fs/local.py
- dvc/fs/oss.py
- dvc/fs/ssh/__init__.py
- dvc/fs/webdav.py
- dvc/fs/webhdfs.py
- dvc/objects/stage.py
- setup.py
This allows us to select between chunked and non-chunked uploading in Webdav, and hopefully in the HTTP itself in the future.
As an effect of this change, straight-to-remote will work even if the http/webdav server does not support chunked encoding over PUT.
This PR makes me think that if we should introduce `chunk`/`no_chunk` option, rather than always defaulting to `Content-Length` based uploads. 
See https://github.com/iterative/dvc/pull/6162#discussion_r651647741 for more information.
> pass size to upload_fobj

- dvc/objects/stage.py
- tests/func/test_data_cloud.py
The first step in removing redundant `exists()` calls, since our filesystems now can just raise an appropriate `FileNotFoundError` instead.
> obj: staging: remove redundant exists() call

- dvc/utils/fs.py
- tests/unit/utils/test_fs.py
> utils: normalize case in path_isin functions

- dvc/output.py
- tests/func/test_import_url.py
Resolves #6237 and #5998. This is also a pre-requisite to resolve #4693
>  output: don't lower the etag field on the schema when deserializing 

- setup.py
Resolves #6102
In general modules with pinned requirements are difficult to integrate into existing systems.
Of course there is a benefit to pinning versions, you are sure your code works, but you also prevent someone from installing your package alongside other code that may require slightly newer versions.
Specifying a minimum version is always good practice, but specifying a maximum version should be done very sparingly and only when needed.
My other projects are failing to integrate with dvc because of incompatibilities in the pygtrie and fsspec packages. I'm not sure if there is a good reason why they are pinned to a maximum version. Submitting this PR to loosen them and see if the CI passes.
> Loosen versions for fsspec and pygtrie

- dvc/repo/stage.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- tests/func/test_scm.py
- tests/func/test_stage.py
Closes https://github.com/iterative/dvc/issues/5748
When querying `dulwich` to check if a directory is gitignored, the path we query should include the trailing slash:
https://github.com/dulwich/dulwich/blob/76dd8356f9d8870f44226e4232c24fbc1e573e93/dulwich/ignore.py#L228-L231
Without it, we get "false positives" and effectively ignore some `.dvc` files that should not be ignored (see issue for details)
Remaining issues:
1. Is it reasonable to write unit tests for this? Can existing machinery for testing handle "un-ignores" (corresponding to gitignore lines prefixed with `!`)?
2. `is_ignored` [was type-hinted as expecting string-typed paths](https://github.com/tpietruszka/dvc/blob/master/dvc/scm/git/backend/dulwich.py#L281); I assumed that type, but 2 unit tests failed, as they were …
> git: Keep trailing slash when checking if directory is gitignored

- dvc/dependency/repo.py
- tests/func/test_import.py
Closes #6207
This is a quite simple simplest solution for the problem that avoids a larger refactor of the actual code. 
I just extended [test_import_non_existing](https://github.com/iterative/dvc/blob/master/tests/func/test_import.py#L349) with a simple test that tries to import a non-existent file from dvc repo so I could test this. 
```python
def test_import_non_existing(erepo_dir, tmp_dir, dvc):
with pytest.raises(FileNotFoundError):
tmp_dir.dvc.imp(os.fspath(erepo_dir), "invalid_output")
with pytest.raises(FileNotFoundError):
tmp_dir.dvc.imp(os.fspath(erepo_dir), "/root/", "root")
with pytest.raises(NoOutputInExternalRepoError):
dvc.imp("https://github.com/iterative/dvc.git", "non-existent")
```
I am not adding the test to the PR since it requires to download a GH repo and I am not …
> import: error message when imported file does not exist 

- dvc/command/experiments.py
Made a mistake during refactoring on styling before. Noticed while reviewing #6174.
- metrics were left-aligned, whereas now it's right-aligned
- also fixed the mistake `params` as justify.
> push params in the experiments table to the right

- dvc/fs/fsspec_wrapper.py
- dvc/fs/gs.py
- tests/func/test_data_cloud.py
> fsspec: loosen the prefix check to cover both None and False

- dvc/repo/add.py
- dvc/utils/collections.py
- tests/unit/utils/test_collections.py
Just experimenting 🧪 with this, let me know what you think. 
The `validate` decorator can be used to validate and transform arguments and results from function calls (if `post=True`). Multiple validators can be provided, and the validators will get access to a dictionary that also supports dot-notation.
```python
def validator(args):
assert args["x"] == args.x
```
Inside the validators, the arguments can also be modified/transformed, so it also acts as a converter/transformer.
Note that, there is one small difference. So, if you are calling it without default arguments, the function will receive the default arguments too.
i.e. calling function with signature `func(x, y, z=3)` as `func(x, y)` will call the function as `func(x, y, z=3)`.
It could be done, but I didn't want to complicate it. …
> separate validation and transformation of args from the add func

- dvc/fs/base.py
- dvc/fs/dvc.py
- dvc/fs/git.py
- dvc/fs/local.py
- dvc/fs/repo.py
- dvc/output.py
A few leftovers from recent temporary odb changes. On 700K dataset, this shaves off around 22seconds.
Still a long way to go and a lot of additional stuff could be done (including maybe pbar), but this should mitigate it for now.
Related to #6276
> output: optimize obj collection

- dvc/fs/ssh/__init__.py
- dvc/objects/db/ssh.py
> ssh: don't use path_info for connections

- dvc/repo/add.py
- tests/func/test_add.py
Because of the way we collect stages and cache them, we were not able to
collect them for the `add` without removing them from the workspace.
As doing so, we'd have two same/similar stages - one collected from the
workspace and the other just created from the `dvc add` in-memory.
This would raise errors during graph checks, so we started to delete them
and reset them (which is very recently, see #2886 and #3349).
By deleting the file before we even do any checks, we are making DVC
fragile, and results in data loss for the users with even simple mistakes.
This should make it more reliable and robust.
And, recently, we have started to keep states of a lot of things, that by
resetting them on each stage, we waste a lot of performance, especially
on gitignores. We cache the Dulwich's …
> add: do not delete stage files before add

- dvc/repo/add.py
- dvc/stage/__init__.py
- dvc/ui/__init__.py
- tests/func/test_add.py
- Change in behaviour: Previously, `dvc add` would recursively find all files and then expand upon it with glob.
This changes to first glob, and then recursively find all files, which matches with what the shell would do.
- Fixes progress bar for globbed targets (previously the no. for them was not accounted for).
- Reduces progress bars to 2. I have merged targets collection and stage creation into the same generator pipeline and hence replaced by a single progress bar. The other progress bar is during `Adding`.
- Also adds spinners while collecting cache and checking for graph correctness.
- Simplifies large dir recursive add warning
i.e. removes the hint to remove the generated file. As I think if a user makes a mistake, they will cancel the operation in the middle, so no need to …
> cleaning up add, progress bars and status

- dvc/ui/__init__.py
[![asciicast](https://asciinema.org/a/7jNT179lBY6mastJsBl5Y04F6.svg)](https://asciinema.org/a/7jNT179lBY6mastJsBl5Y04F6)
[![asciicast](https://asciinema.org/a/XyiXXKqSDteLmqTMchtnxe5cy.svg)](https://asciinema.org/a/XyiXXKqSDteLmqTMchtnxe5cy)
Note that I haven't been able to figure out adding support for `rich`'s console, so mixing `console` might interleave other outputs (though not with the tqdm itself thanks to this PR).
Related to #6224.
> ui: Prevent tqdm from breaking on output

- dvc/objects/file.py
- dvc/objects/tree.py
- tests/unit/objects/test_tree.py
Resolves #6283. I am still not quite sure to whether we should keep `getsize()` logic at all, or not since this information should be propagated from an upper level (e.g staging, in this case fills HashInfos). Lazily retrieving this is very bad for performance, especially when you have a lot of files.
> objects: hash_file: retrieve size from hash_info

- dvc/command/diff.py
- tests/unit/command/test_diff.py
Fixes: https://github.com/iterative/dvc/issues/6205
> Fix #6205: Fixed diff summary to only show states with values.

- .pre-commit-config.yaml
- README.rst
- dvc/dagascii.py
- dvc/fs/azure.py
- dvc/fs/fsspec_wrapper.py
- dvc/repo/experiments/__init__.py
- dvc/scm/git/backend/base.py
- scripts/innosetup/setup.iss
- tests/func/plots/test_show.py
- tests/func/test_status.py
- tests/unit/test_updater.py
This PR was created with the command [`codespell --ignore-words-list="ba,datas,fo,uptodate" -w`](https://github.com/codespell-project/codespell)
> Fix typos discovered by codespell

- dvc/fs/http.py
- dvc/info.py
- setup.py
- tests/func/test_version.py
- tests/unit/test_info.py
Resolves #6248
Previous output:
```
DVC version: 2.4.3+ce45ec 
---------------------------------
Platform: Python 3.8.5+ on Linux-5.4.0-77-generic-x86_64-with-glibc2.29
Supports: s3, gs, http
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: ext4 on /dev/sda7
Repo: dvc, git
```
Current output:
```
DVC version: 2.4.3+fc7409 
---------------------------------
Platform: Python 3.8.5+ on Linux-5.4.0-77-generic-x86_64-with-glibc2.29
Plugins:
gs (gcsfs = 2021.6.1),
http (requests = 2.25.1),
s3 (s3fs = 2021.6.1, boto3 = 1.17.49),
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: ext4 on /dev/sda7
Repo: dvc, git
```
Current output of all remotes:
```
DVC version: 2.4.3+fc7409 …
```
> doctor: show versions for fs requirements

- dvc/fs/dvc.py
- dvc/fs/gdrive.py
- dvc/fs/git.py
- dvc/fs/hdfs.py
- dvc/fs/http.py
- dvc/fs/local.py
- dvc/fs/ssh/connection.py
- dvc/fs/webhdfs.py
- dvc/objects/stage.py
- tests/unit/remote/test_http.py
We do 2 `.exists()` and `.isdir()` call for the same path in the same context, so we can reduce them into a single `info()` call and retrieve all information we need in one go. If the file is not there, it will raise an FileNotExistsError too.
> staging: optimize the number of info() calls

- dvc/fs/repo.py
- tests/unit/fs/test_repo.py
> fs: repo: handle directories with multiple artifacts

- dvc/repo/add.py
- dvc/ui/__init__.py
- tests/func/test_add.py
```console
$ dvc add foo foo
ERROR: output 'foo' is already specified in stages:
```
> add: ignore duplicated targets?

- dvc/command/experiments.py
- dvc/compare.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/executor/local.py
- dvc/repo/experiments/show.py
- tests/func/experiments/test_show.py
Will close #5965
- For the DVC UI, this PR adds `State` column that will currently be Running, Queued or empty
- If the table has no running or queued experiments the column will not be displayed
- If `State` is `Running`, an additional `Executor` column will be displayed noting where the experiment is being run, currently this is limited to `local (workspace)` or `local (background)`
- For `--show-json` (VSCode), experiment dicts now have a `running` key that will be true or false, and an `executor` key which will be an optional string executor name
- Fixes bug where main repo would be locked during `--temp` or `--queue/--run-all` runs (related to #5739) which prevented `exp show` from being usable
Regular …
> exp show: display running/queued state for experiments

- setup.py
- tests/docker-compose.yml
- tests/func/test_import_url.py
> azure: support directory imports with azure

- .github/workflows/tests.yaml
- dvc/fs/oss.py
- dvc/objects/db/__init__.py
- dvc/objects/db/oss.py
- setup.py
- tests/func/test_data_cloud.py
- tests/remotes/oss.py
- tests/unit/remote/test_oss.py
Fix #6177, migrate to ossfs
come from #6178 
Performance summary: 
> The latest version runs 1.5 times faster  in `gc` and `push` than the version we are using, and more than 2 times in `pull`.
| time cost \ version| current version | last week version | reuse session version  | dircache version (latest) |
|:--:|:--:|:--:|:--:|:--:|
| gc | 100% |  +115% | 70% |  68% |
| pull | 100% | 171% |  118% | 36% |
| push | 100% | 97% | 64% |  72 %|
The results from the current version compare to reuse of sessions optimization.
The results from the current version compare to reuse of sessions optimization.
> oss: migrate to ossfs

- dvc/fs/base.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/hdfs.py
- dvc/fs/local.py
- dvc/fs/ssh/__init__.py
- dvc/fs/webdav.py
- tests/func/test_fs.py
Since we start adding non-object systems (e.g webdav, ssh) there is now a requirement for `makedirs()` calls before `upload`/`upload_fobj`/`copy` operations. Also the `_with_bucket`, and `_strip_bucket` functions are closely tied with the object filesytems so they are moved under the `ObjectFsWrapper`.
> fsspec: create directories on upload/upload_fobj

- dvc/fs/azure.py
- tests/unit/fs/test_azure.py
> azure: move to default fsspec loop

- dvc/istextfile.py
- dvc/utils/stream.py
- tests/unit/utils/test_stream.py
If we assume the block size that we use in `upload_fobj` is always greater than `512 bytes` (which is the case for all remotes as far as I can see), we could imitate just limit our chunk at that point. If we want to be more precise, we might need to create an additional buffer to pre-read the first 512 bytes into and a custom logic to dispatch those in the regular read which seems tricky (more details are on issue). Resolves #6160
> import-url: use the same chunk size for istextblock() calls

- setup.py
The previous release got yanked on the PyPI, due to it containing backwards incompatible changes.
> setup: upgrade adlfs to 2021.7.1

- dvc/data_cloud.py
- dvc/fs/gdrive.py
- dvc/objects/transfer.py
> objects: fix gdrive CI issue

- dvc/ui/__init__.py
I mistakenly set the `styled` parameter default value in the `error_write` to `True`, which was printing using `rich` by default. This caused the messages to also include the ANSI codes to display.
```console
$ dvc add foo
100% Adding...|████████████████████████████████████████|1/1 [00:00, 76.95file/s]
Some targets could not be linked from cache to workspace.
See <[36mhttps://dvc.org/doc/user-guide/troubleshooting#cache-types[39m> for 
more information.
To re-link these targets, reconfigure cache types and then run:
dvc checkout foo.dvc
git add foo.dvc
```
> do not print in style by default for errors

- setup.py
My [latest PR](https://github.com/ianlini/flatten-dict/pull/44) to flatten-dict should shave about 0.5 seconds on very complex environments for us, so upgrading it to 0.4.1. Resolves #6349
> setup: bump flatten-dict to 0.4.1

- dvc/repo/plots/data.py
- setup.py
- tests/func/plots/test_show.py
- tests/unit/repo/plots/test_data.py
> plots: cleanup data extraction

- dvc/fs/fsspec_wrapper.py
- dvc/fs/oss.py
Our `remove()` is actually `rm_file()` since it is only responsible with removing an individual file. `fsspec`'s `rm()` is a little bit more powerful, with recursive functionality etc. but more expensive in terms of target expanding. s3fs was the only filesystem which didn't support this, though with 2021.7.0 it is now supporting it (https://github.com/dask/s3fs/pull/499).
> fsspec: use rm_file()

- dvc/config_schema.py
- dvc/fs/azure.py
add additional excludes to DefaultAzureCredential
which are needed in a Windows Environment to
use az cli provided credentials, etc.
> remote: add excludes for AzureDefaultCredentials

- dvc/output.py
A quick naive fix that reduces `dvc diff` from hours to around ~20sec for a dataset of dozens of thousands of files. That is still bad, but in order to speed it up more, we need to revisit our `.dir` storage and switch to using staging in `get_dir_cache`. That will be revisited after followups for https://github.com/iterative/dvc/pull/6308 
Related to #6173
> output: cache loaded tree objects

- dvc/objects/db/base.py
- tests/func/objects/db/test_index.py
- tests/func/test_external_repo.py
- tests/func/test_import.py
- tests/func/test_remote.py
- tests/func/test_update.py
In the old remote logic, for transfering to remotes we used `upload()` instead of `upload_fobj()` which on some backends defaulted to `upload_fobj` and on some others used the native transfer libraries logic. For some backends like oss / ssh etc. this is faster than the `upload_fobj`, so this patch adds an extra check to the ODB to match against whether the source file system is local or not. If it is the local filesystem, we can safely use `_upload()` if not we can still fallback to `_upload_fobj()`.
> odb: use regular upload() when the source filesystem is local

- setup.py
> setup: relax aiobotocore requirements

- dvc/fs/fsspec_wrapper.py
- setup.py
From https://github.com/iterative/dvc/pull/6295#issuecomment-888495315. There are 2 primary issues, one is that we used to max out all the sessions with SFTP channels, so after a certain amount of operations there wasn't any channels to use for SSH. Now we allocate 2 channels for it. The second issue is that, `AsyncFileSystem` that fsspec offers overrides the `move()` command with it's own `copy()`+`remove()` implementation. Now that is also temporarily fixed on the sshfs, and will submit a patch against fsspec upstream.
> ssh: handle concurrency issues for raw command execution

- setup.py
Temporary fix for #6374 Kudos @skshetry
> setup: limit python-benedict version

- dvc/config.py
- dvc/fs/__init__.py
- tests/unit/fs/test_fs.py
A simple temporary fix for studio. A proper fix would be to make metrics/plots/etc lazy and detached from dag build, so that this error is not even triggered. That will likely happen after #6300
Fixes #6082
> fs: get_fs_config: raise RemoteNotFoundError

- dvc/repo/experiments/__init__.py
- dvc/utils/collections.py
- setup.py
- tests/unit/utils/test_collections.py
The recent release of python-benedict==0.24.1 started ignoring empty dictionaries
during the merge. The way we expected to work was questionable and also how
benedict itself tries to handle the references to an empty dictionary is
also questionable.
I consider this to be a proper way to handle this even if this gets fixed
on the benedict side.
To demonstrate the problem with referencing an empty dictionary:
```pycon
>>> x = {}
>>> y = dict(x)
>>> y.update({"foo": "bar"})
>>> x
{}
>>> y
{'foo': 'bar'}
```
Benedict tries to handle in-place updates, so it's tricky for it to handle this case of empty dictionaries as the references are not preserved. And, since `modify_data` requires updating things in-place, we require references to be preserved. So, it seems it's our duty to try to preserve …
> Fix merging of params when empty

- dvc/utils/collections.py
- tests/unit/utils/test_collections.py
Minor cleanups to yesterday's PR: #6378 
Also, I was not able to see how to fix this upstream as it's quite tricky.
And adding a test for the syntax when having empty params.
> benedict: cleanup code and add tests

- tests/func/test_init.py
- tests/func/test_scm.py
Part of #1819 
PR doesn't require documentation updates.
> Unittest to pytest: moved few unittest tests to pytest 

- dvc/command/dag.py
- dvc/command/stage.py
- dvc/command/status.py
- dvc/objects/__init__.py
- dvc/output.py
- dvc/repo/__init__.py
- dvc/repo/add.py
- dvc/repo/checkout.py
- dvc/repo/collect.py
- dvc/repo/destroy.py
- dvc/repo/diff.py
- dvc/repo/imp_url.py
- dvc/repo/index.py
- dvc/repo/params/show.py
- dvc/repo/reproduce.py
- dvc/repo/run.py
- dvc/repo/stage.py
- dvc/stage/utils.py
- dvc/utils/__init__.py
- dvc/utils/fs.py
- tests/dir_helpers.py
- tests/func/conftest.py
- tests/func/test_add.py
- tests/func/test_dvcfile.py
- tests/func/test_repo_index.py
- tests/func/test_repro.py
- tests/func/test_stage_load.py
- tests/unit/command/test_dag.py
- tests/unit/command/test_status.py
- tests/unit/repo/test_repo.py
>  introduce index

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/show.py
- tests/func/experiments/test_show.py
> Show name of experiments in the queue

- dvc/repo/index.py
- dvc/repo/run.py
- tests/func/test_repo_index.py
> cleanup index, and add test for used_objs

- dvc/objects/db/base.py
- dvc/objects/db/reference.py
Caching ref objects to avoid wasting lots of time on loading in [_get_file_obj](https://github.com/iterative/dvc/blob/fd76e0991f6dd47e554b874c2efb8c280dee96c0/dvc/objects/stage.py#L93). Overall this brings back the lost parity between import and pull performance.
Followup for #6360.
> refodb: cache ref objects

- dvc/fs/gdrive.py
- setup.py
- tests/func/test_data_cloud.py
- tests/func/test_fs.py
- tests/remotes/gdrive.py
- tests/unit/remote/test_gdrive.py
> gdrive: migrate to pydrive2.fs

- dvc/fs/dvc.py
- dvc/fs/git.py
- dvc/fs/repo.py
This makes `dvc get` work just as fast as `import/pull`. The reason is that `open()` is harder to make fast (e.g. we need to know what block size to use, etc, for which we don't yet have a very good internal infrastructure), and it is much easier to just use native `fs.download` method that has been already tuned for maximum performance.
Related to #5546
Fixes #6019
> repofs: use underlying fs.download to download files

- dvc/scm/git/backend/pygit2.py
- tests/unit/scm/test_git.py
Will fix https://github.com/iterative/dvc/issues/6403
> pygit: account for locked dirs on windows during checkout

- dvc/analytics.py
- tests/func/test_analytics.py
When sending analytics, we are not flushing the data to the temp file
which causes failure at times, especially on Windows.
> Fix issue while sending analytics report

- dvc/command/experiments.py
- dvc/repo/experiments/remove.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_remove.py
fix #6157
1. dvc exp remove not accept queued experiments name
2. add some tests for this feature
> Remove a special queued experiments

- dvc/fs/fsspec_wrapper.py
- setup.py
- tests/func/test_fs.py
In the following statement we try to access the first index, which is not possible when using `dict.values()`.
> fs: find(..., detail=True) now casts values properly

- dvc/command/base.py
- dvc/command/version.py
We've used updater for years now to notify our users ASAP about new
releases. These days dvc is more stable and we've actually been
receiving numerous complains about updater being too annoying and
even introduced a config flag to turn it off, which a lot of people do
and which defeats its purpose. Instead of introducing some complex logic
that would notify more rarely and once for the user instead of once for
every dvc project they have - this PR just turns it off for everything,
except `dvc doctor/version`, which is the command that people use when
they are running into issues and that will give them a hint to just try
out the newest version first, as it might be already fixed.
This PR is a more of a compromise, to get the most out of updater while
removing a pain point of it being too …
> updater: only notify in dvc doctor

- dvc/utils/html.py
* [N/A] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.
The current version of Vega included in the plots template page is quite outdated. Many of the features mentioned in the Vega Lite documentation are Vega-Lite 5.0 only, and thus fail to work on the 4.0 version included by DVC. I submitted this change that simply changes the version numbers to the latest versions released as of now.
One idea to consider is omitting the version entirely and allowing jsDelivr to pick the latest version it has available. Vega plots all require a `$schema` parameter that specifies the version of the Vega specification to adhere to when displaying, so even breaking …
> plots: upgrade to latest Vega library versions

- dvc/command/version.py
- dvc/updater.py
- tests/unit/test_updater.py
On top of https://github.com/iterative/dvc/pull/6247.
Related to #5912.
<details>
<summary>Screenshots</summary>
1. Git installed, or unknown package:
2. Non-binary packages
3. Binary packages
</details>
I still have some doubts about the link in blue, could also color it in yellow. Please see if the messages are clearer too.
Also note that the ui messages only appear in `dvc version`.
> Change ui message for the updater

- dvc/repo/fetch.py
- tests/func/test_data_cloud.py
Resolved #6435. If `item[0]` is `None`, python will shortcut at the `and` operator and use it's result (`None`) instead of `False` which would make the items unsortable. With adding an explicit check against `None`, it now returns either `False` or `True`.
> fetched: correctly order mixed odbs

- dvc/repo/experiments/executor/base.py
- tests/func/experiments/test_experiments.py
> exp run: pass recursive args to checkout

- dvc/command/experiments.py
- dvc/repo/experiments/remove.py
- tests/func/experiments/test_remove.py
- tests/unit/command/test_experiments.py
fix #5676
1. remove all the experiments in workspace
2. add tests for it
> Remove all of the experiments in the workspace

- dvc/fs/base.py
- dvc/fs/http.py
- dvc/utils/http.py
> [6478] Fix 401 unauthorized for directories in basic auth protected http remote

- setup.py
It is breaking the pattern of setting up a development environment for DVC (`pip install -e ".[all,tests]"`) as suggested in the [Contributing Guide](https://dvc.org/doc/user-guide/contributing/core#development-environment).
> add terraform to tests dependencies

- test_requirements.txt
> restrict google-crc32c for Python3.10

- dvc/command/machine.py
- dvc/machine/__init__.py
- dvc/machine/backend/base.py
- dvc/machine/backend/terraform.py
- setup.py
- tests/unit/command/test_machine.py
- tests/unit/machine/test_terraform.py
Will close #6483
* Adds `dvc machine ssh` command to connect to `dvc machine create`ed remote machine instances - shell/PTY session is done via asyncssh and does not require the user to have a separate OpenSSH/putty/etc SSH client on their machine (meaning it should work from Windows hosts out of the box as long as `dvc[terraform]` is installed)
* Adds `ssh` requirements to the `terraform` install extras - eventually `ssh` may need to be added to the default installed remotes if/when `dvc machine` has basic functionality independent of terraform
> machine: add `dvc machine ssh`

- dvc/fs/ssh.py
- tests/unit/fs/test_ssh.py
> ssh: support multiple keys

- .github/workflows/tests.yaml
Simplifies development for all contributors. Thanks to great work by @skshetry we have reasonable remote test defaults and so there is really no need to limit gha to master branch anymore.
> gha: allow running tests on other branches

- dvc/config_schema.py
- dvc/fs/s3.py
This patch adds a new option (`cache_regions`) to enable bucket region caching in s3fs (https://github.com/dask/s3fs/pull/495). This basically caches regions for each buckets in-memory during the program's runtime. If you don't specify any region in your config, then you end up with resolving the same bucket's region over and over which comes with a burden for small running programs.
For `info()` calls on the same bucket, this was the stats I was able to gather without the bucket region caching:
```
total invocations: 1, total time: 2.765854, time/invoc: 2.765854
total invocations: 2, total time: 3.100261, time/invoc: 1.550131
total invocations: 3, total time: 4.330655, time/invoc: 1.443552
total invocations: 4, total time: 5.416423, time/invoc: 1.354106
total invocations: 5, total time: …
```
> s3: inline bucket region caching

- tests/func/test_live.py
See https://github.com/iterative/dvc/runs/3515886615#step:12:9305.
Making sure that script takes a bit more time than the await time
I am not really sure this was the cause though, will monitor after this is merged.
Also the tests are flaky only in MacOS, but I haven't been able to reproduce.
> try to fix flaky dvclive test

- dvc/fs/__init__.py
- dvc/fs/utils.py
- dvc/objects/db/base.py
> extract transfer related logic from odb to fs.utils.transfer

- dvc/config.py
- dvc/config_schema.py
- dvc/machine/__init__.py
* `instance_size` should be any string `instance_size` accepted by terraform-provider-iterative
* `startup_script` should be (config-relative) path to a shell script file (rather than the raw string used in terraform-provider-iterative)
> machine: support instance size & startup script config

- .github/workflows/tests.yaml
- setup.cfg
The jobs in CI are getting frozen sometimes, either of an issue with `pytest-xdist` or pip resolver due to some weird constraints set by us or one of our dependencies.
The default timeout is 360 minutes (6hrs), but our test completes on ~18 minutes at maximum, so I think 30mins should be enough to account for occasional CI slowdown.
Also keeping the total test job timeout at 45 mins, we usually require just 4 mins of extra time to do installation and setup but giving it 11 more minutes just in case.
Similarly, `lint` completes in <5 mins usually, but giving it a 10 mins timeout.
This should give us early feedback on the issue.
> Set timeout for jobs in Github Actions

- dvc/fs/fsspec_wrapper.py
- dvc/fs/http.py
- setup.py
- tests/func/test_fs.py
- tests/unit/remote/test_http.py
Resolves #6413
Differences compared to the old HTTPFileSystem (requests based):
- We no longer have `digest` authentication since it is not supported by the aiohttp, at least not yet. (there is an old PR, ~3 years old that is still open). Instead of a deprecation period, now the config option `auth` with the value `digest` will raise an error saying that the option is not available. In the future, if this feature gets accepted to the aiohttp we could bring back the support, but it doesn't seem to be going to happen anytime soon.
> http: migrate to fsspec & aiohttp

- dvc/machine/backend/base.py
- dvc/machine/backend/terraform.py
The upstream package doesn't need an ABC (https://github.com/iterative/tpi/pull/5 <- https://github.com/iterative/tpi/issues/4). This PR reintroduces `dvc.machine`'s `BaseMachineBackend` spec.
> remove `tpi.base` dependency

- dvc/command/experiments.py
- dvc/compare.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_experiments.py
fix #5446 
1. add --show-csv to dvc exp show
2. add tests for dvc exp show --show-csv
> Show csv format of experiments

- dvc/state.py
This is no longer used since the separation of dvcignore.
> state: get rid of self.fs

- dvc/fs/ssh.py
- tests/unit/fs/test_ssh.py
Seems like unlike [paramiko](http://docs.paramiko.org/en/stable/api/client.html#paramiko.client.SSHClient.connect), [asyncssh](https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SSHClientConnectionOptions) has a separate option to store `passphrase`. Resolves #6561
> ssh: support passphrases for private keys

- requirements/default.txt
- setup.py
> Move install requires to requirements/default.txt

- dvc/fs/base.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/gdrive.py
- dvc/fs/hdfs.py
- dvc/fs/local.py
- dvc/fs/ssh.py
- dvc/fs/utils.py
- dvc/fs/webdav.py
- dvc/fs/webhdfs.py
- dvc/objects/db/reference.py
- dvc/objects/stage.py
- tests/func/test_fs.py
> fs: merge upload_fobj and upload

- tests/remotes/gdrive.py
Using `CloudURLInfo`, it makes this following path parsing fail:
https://github.com/iterative/dvc/blob/1a1294848b5f9b574e40f69b31022da353f0d34b/dvc/fs/gdrive.py#L295-L297
> Use GDriveURLInfo instead of CloudURLInfo

- dvc/fs/azure.py
- dvc/fs/base.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/gs.py
- dvc/fs/hdfs.py
- dvc/fs/local.py
- dvc/fs/s3.py
- dvc/fs/ssh.py
- dvc/fs/webhdfs.py
- dvc/progress.py
- dvc/utils/fs.py
- tests/func/objects/db/test_index.py
- tests/func/test_fs.py
- tests/unit/remote/test_remote_tree.py
Also removes _upload methods in other fses, and replaces them
with fsspec-compatible put_file which supports fsspec callback
even if they are not fsspec based filesystem.
> fs.upload: add support for optional callback

- dvc/fs/azure.py
- dvc/fs/base.py
- dvc/fs/dvc.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/gdrive.py
- dvc/fs/git.py
- dvc/fs/gs.py
- dvc/fs/hdfs.py
- dvc/fs/http.py
- dvc/fs/local.py
- dvc/fs/oss.py
- dvc/fs/repo.py
- dvc/fs/s3.py
- dvc/fs/ssh.py
- dvc/fs/webhdfs.py
- dvc/progress.py
- tests/func/test_fs.py
- tests/unit/remote/test_http.py
With this, we won't have any progress bars in our filesystem, except on `base.py` where we have 3 progress bars on `upload`, `download_file`, and `download_dir`. `download_dir` requires nested/branched callback, so it has been tricky to remove those right away. Will be fixed in upcoming PRs.
With this PR, all the filesystems will use `get_file` irrespective of being fsspec-based or not to download files, and has callback support.
> fs.download: add callback support

- dvc/output.py
- tests/func/test_data_cloud.py
> output: use remote kwarg instead of odb

- tests/func/experiments/test_show.py
related to ci failures, and related to #6468 
The current ci failure was caused by wrong order of the experiments.
Because our test script runs so fast that they might share the same
commit timestamp, that makes them in an uncertain order. And then gives
a wrong branch_base.
> Fix ci failures

- dvc/command/machine.py
- dvc/config_schema.py
- tests/func/machine/test_machine_config.py
- tests/unit/command/test_machine.py
fix #6480 
1. add new command `dvc machine list`
2. complete `dvc machine modify`
3. add new unit tests for this two commands to ensure the call.
4. add functionality tests for two commands
> machine: add `machine list`&`machine modify`

- dvc/fs/gdrive.py
- tests/func/test_fs.py
This was giving me the entries such as `root/root/dir/{foo,bar}` instead of just `root/dir/{foo,bar}`. Though I am not sure if this has any effects on existing users.
> gdrive: strip bucket

- dvc/fs/base.py
Since we don't use this `copy` between same filesystems, it's better we remove it. It'd be tricky to implement callbacks here, so it's best to just get rid of it, while we can. `fs.utils.transfer` is the one that we should use.
> fs.download: remove unused copy between same fs

- dvc/fs/ssh.py
- tests/unit/fs/test_ssh.py
Resolves [the following error](https://discuss.dvc.org/t/how-do-i-use-dvc-with-ssh-remote/279/21?u=isidentical)
> ssh: ask password before setting it

- requirements/tests.txt
- setup.cfg
Trying to see if getting rid of this dependency, our issue with the timeout
gets solved or not.
We use timeout-minutes anyway on GHA, so we probably don't need it.
Locally, users can monitor this themselves.
> get rid of pytest-timeout

- dvc/render/utils.py
- tests/unit/render/test_render.py
- tests/unit/test_plots.py
Close https://github.com/iterative/dvclive/issues/53
The plots rendered in `html` are _arbitrarily_ ordered on different calls as they depend on `RepoFyleSystem.walk_files` and on `dvc.render.utils.get_files` (which uses a `set` to return values).
This P.R. forces a sorted return in `dvc.render.utils.get_files` which ensures that the rendered plots are _equally_ ordered on different calls.
> Force sorted order in plots rendering

- dvc/command/experiments.py
- tests/func/experiments/test_init.py
Simpler, initial implementation for `exp init`.
Closes https://github.com/iterative/dvc/issues/6441.
Part of https://github.com/iterative/dvc/issues/6446.
> exp init: add simple dvc exp init command

- requirements/gdrive.txt
- tests/func/test_fs.py
Gdrive will fail unless the `pydrive2` is updated.
Added a few more remotes for tests of the callbacks as well.
> tests: additional callbacks test for remaining filesystems

- dvc/fs/base.py
- dvc/fs/fsspec_wrapper.py
- dvc/progress.py
When an async filesystem (fsspec-level) makes a call to `set_size()` callback with `None` (the size is not inferrable), we call the `info()` on the dvc-level sync filesystem which delates this call to fsspec's async function run in a separate loop. This situation is creating a deadlock where we make a call from an async function (e.g `_get_file`) to another async function (`_info`) with a wrapped sync execution (`info()`) between them.
For the simplicity, this patch drops the current behavior of consulting to `info()` on `set_size(None)`.
> progress: do not block on async filesystems

- dvc/checkout.py
- dvc/fs/webhdfs.py
- dvc/objects/diff.py
- tests/func/test_add.py
First steps in migrating checkout to object-based workflow. Introduces `dvc.objects.diff` that can be used in other applications (e.g. in `dvc diff`) later. Allows us to stage existing target first(multithreaded, benefiting from all current and future improvements in `dvc.objects.stage`), then compare the resulting object with the end result that we are trying to achieve and use that diff to only apply actual changes.
`diff()` has some pre-requisites for supporting granular `Tree`s in the future, but for the most part this is trying to carry over legacy things, that will be revisited in the followups.
Pre-requisite for #6594
Todo:
> checkout: start switching to obj-based workflow 

- dvc/dvcfile.py
- dvc/stage/exceptions.py
- dvc/utils/strictyaml.py
- tests/func/test_dvcfile.py
- tests/func/test_lockfile.py
- tests/unit/test_dvcfile.py
Closes https://github.com/iterative/dvc/issues/6290.
To solve #6285 and #5371 (i.e. better error messaging from schema errors and yaml syntax errors), I reckoned that we need to combine both yaml parsing and schema validation into one single pipeline. So, this merges both `parse_yaml` and `validate_schema` into one `strictyaml.load()` and may help us in providing better error messages. This is really useful for  loading `dvc.yaml`/`dvc.lock` and `.dvc` files as they are validated YAML files.
Moves previous changes from #6654 into strictyaml.
Schema error messaging is not in this PR, which will come after this gets merged. #6290 has been fixed by this change, as it now raises proper `EncodingError`. 
> merge yaml parsing and schema validation into one, aka strictyaml.load

- requirements/ssh.txt
It seems like some of the cases bcrypt is required for the SSH key decoding, and from what I can see paramiko was already coming bundled with `bcrypt` by default. For AsyncSSH, it is an extra dependency. See https://discord.com/channels/485586884165107732/485596304961962003/890347398918971412 for more context
> ssh: bundle bcrypt by default

- dvc/system.py
- requirements/default.txt
`speedcopy` only patches `shutil.copyfile`, which we don't even use
anywhere because it lacks callbacks/progress and we instead use
our own `copyfile` implementation, so this is totally useless for
us and can be removed.
> system: get rid of speedcopy

- dvc/command/ls/__init__.py
- tests/unit/command/ls/test_ls.py
cli: added alias for 'ls' for dvc list
Fixes #6651 
> add alias ls for dvc list

- dvc/command/experiments.py
- tests/func/experiments/test_init.py
This PR adds support for `--interactive` and `--explicit` options. This does not have support for templates, which still requires some thought. This change also makes `dvclive` optional, it'll be only applied if the `--live` flag is used or the user responds interactively (where it'll still be asked for by default).
Also adds the `--force` flag to mirror `dvc stage add`.
This includes stuff we have discussed in https://github.com/iterative/dvc/pull/6637#issuecomment-924897599 so far.
If we still need templates, it could be done over this.
Supersedes #6630 and #6637.
> exp init: support interactive and explicit options

- dvc/command/experiments.py
This PR:
* hides the heading if the dvc.yaml file already exists.
* errors out before asking interactively if the stage already exists.
* displays `interrupted by user` on a separate line.
Related: https://github.com/iterative/dvc/issues/6446
> exp init: show heading based on the presence of dvc.yaml file

- dvc/command/ls/__init__.py
- dvc/ui/__init__.py
- requirements/default.txt
1. update ls __init__.py to handle --show-pretty-json
2. introduce pygments into requirements/default.txt
Closes https://github.com/iterative/dvc.org/issues/2838
> command: Show dvc list output in pretty JSON format

- requirements/default.txt
> deps: add contextvars as a dependency for Python3.6

- dvc/utils/_benedict.py
- dvc/utils/collections.py
- requirements/default.txt
- tests/unit/utils/test_collections.py
Fixes #6476, fixes #6423 and closes #6484.
> benedict: monkeypatch, performance improvements, bugfixes

- dvc/command/experiments.py
This flag will select the different mode of outputs of stage.
With `--with=live`, it'll enable `live` setting in the stage.
On interactive mode, it'll always ask user if they want to
use live (unless `--with=live` is specified), and then it'll
skip metrics/plots question and moves on to ask for path to
dvclive path.
Also, if live setting is enabled in the stage, it'll set the
`models` to be a checkpoint output.
> exp init: introduce `--with={default,live}` flag

- dvc/fs/http.py
Beside the server-side errors like timeouts, also retry stuff that is happening on the client (e.g internet connection drop for a second).
> http: explicitly retry all http-related errors

- dvc/stage/__init__.py
- tests/func/test_live.py
Closes https://github.com/iterative/dvclive/issues/169
`DVCLIVE_PATH` env var was not taking into account the stage's workdir causing `dvclive` to write outputs to the wrong path on some occasions (i.e. when running `dvc repro "subdir"`)
> Fix dvclive running subdir

- .github/workflows/benchmarks.yaml
Qucik&dirty way to run dvc-bench for our PRs to help with things like #6707
Need to clarify that this is not all-in-one regression detection, but rather this is specific to test regressions within one PR. We need a similar thing for specific dvc versions to detect slow regressions that accumulate over a long period of time, but that is out of scope for this PR.
> gha: run benchmarks on PRs

- .github/workflows/benchmarks.yaml
> gha: benchmarks: fix pytest flags

- tests/remotes/hdfs.py
From now on, pyarrow is optional for the tests.
I am adding this PR before fixing https://github.com/iterative/dvc/issues/6878 to check whether we can depend on it in the future (eg: when we will be adding 3.11 support). I will remove requirements for python version on the next PR.
> tests: skip based on conditional import on pyarrow

- setup.cfg
Pyarrow 6 is now available for Python 3.10. Fixes https://github.com/iterative/dvc/issues/6878.
> dependencies: remove python 3.10 restriction for pyarrow

- setup.cfg
Looks like azure-core is dependent on a dependency `chardet` that aiohttp brought it with, which has been replaced with `charset_normalizer`.
But azure-core depends on internal of aiohttp and looks like it tries to set it's own encoding parser, `chardet` which is now not available.
See if this fixes https://github.com/iterative/dvc/issues/6899.
> deps: require chardet as a dependency for azure

- setup.cfg
Reverts iterative/dvc#6902.
This has now been fixed upstream: https://github.com/Azure/azure-sdk-for-python/issues/21516.
Related: https://github.com/iterative/dvc/issues/6899
> Revert "deps: require chardet as a dependency for azure"

- dvc/repo/experiments/init.py
- dvc/scm/base.py
Part of https://github.com/iterative/dvc/issues/6446
> exp init: autostage .gitignores, dvc.yaml and params file

- scripts/build-requirements.txt
This was added for fixing https://github.com/iterative/dvc/issues/5012 on Windows. But it has been fixed for a long time now, so it should be okay to remove this. But we'll find out on the next release 😅.
> build: remove numpy restriction

- dvc/repo/experiments/init.py
This changes the ordering of prompts, now it'll ask for command first before showing the workspace tree and prompts for the paths.
This is an RFC PR. I find it a bit confusing as it seems to break the linear flow of the prompts. I have yet another suggestion to move this prompt to the end. cc @dberenbaum @daavoo 
Part of https://github.com/iterative/dvc/issues/6446.
[![asciicast](https://asciinema.org/a/RU9HNkdfuq40zKvSsAOgYTygg.svg)](https://asciinema.org/a/RU9HNkdfuq40zKvSsAOgYTygg)
[![asciicast](https://asciinema.org/a/2NmpIbMDJpzYe39iI7ei8LeGX.svg)](https://asciinema.org/a/2NmpIbMDJpzYe39iI7ei8LeGX)
[![asciicast](https://asciinema.org/a/lrRFXb0OfBmjHnPGRCc5nx07B.svg)](https://asciinema.org/a/lrRFXb0OfBmjHnPGRCc5nx07B)
> exp init: ask for command before paths

- dvc/repo/experiments/init.py
On `--explict`, it displayed no worktree at all, as `exp init` does not know about default paths:
```console
$ dvc exp init -if --explicit
This command will guide you to set up a default stage in dvc.yaml.
See https://dvc.org/doc/user-guide/project-structure/pipelines-files.
Command to execute: test
Enter the paths for dependencies and outputs of the command.
DVC assumes the following workspace structure:
Path to a code file/directory [n to omit]:
```
The message "DVC assumes ..." won't be shown now on the explicit mode. 
> exp init: hide message about workspace tree on --explicit

- dvc/command/machine.py
fix #6863 
1. include instance_type and instance_gpu in the output.
2. rerange the field by importance.
> machine status: include two new field in the output

- dvc/config_schema.py
- dvc/fs/webhdfs.py
- setup.cfg
- tests/unit/remote/test_webhdfs.py
This will re-enable some of the functionality lost after #6662.
I have not created a documentation pull request for this yet, since I expect there may be some discussion around the naming or organization of these options, since this is my first contribution to this repo and I'm not sure about all the conventions.
Once the naming is settled I will of course create a documentation PR as well.
Note that I have renamed `webhdfs_token` to `token` since that is what is indicated in the current docs.
Please let me know if you want the naming convention of these to be changed.
Fixes #6935
> webhdfs: expose kerberos and https options

- dvc/command/experiments.py
- dvc/compare.py
- tests/func/experiments/test_show.py
- tests/unit/test_tabular_data.py
`dvc.org` P.R: https://github.com/iterative/dvc.org/pull/2966
Closes #5966 
Also, pre-requisite for #4455 
---
Demo:
```dvc
$ dvc exp show
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Experiment            ┃ Created      ┃     auc ┃ featurize.max_fea… ┃ featurize.ngrams ┃ prepare.seed ┃ prepare.split ┃ train.n_estimators ┃ train.seed ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ workspace             │ -            │ 0.61314 │ 1500               │ 2                │ 20170428     │ 0.2           │ 50                 │ 20170428   │
│ 10-bigrams-experiment │ Jun 20, …
```
> exp show: Add `--only-changed` option

- dvc/fs/base.py
- dvc/fs/local.py
- dvc/fs/path.py
- dvc/objects/stage.py
- dvc/output.py
- dvc/utils/__init__.py
fs.path is meant to be lightweight, and we should try to avoid using os.path.
Leftover from #6946
> localfs: remove LocalPath

- .github/workflows/tests.yaml
- dvc/command/experiments.py
- dvc/command/run.py
- dvc/command/stage.py
- tests/func/test_cli.py
- tests/unit/command/test_experiments.py
Recent bugfix in 3.9 release: https://bugs.python.org/issue45235
Has caused a regression. There were 2 problems:
1. we used to override `cmd` value for commands like `run`, `stage` and `exp init`. This one is on us, and while the proposed workaround does not require it, I renamed stage-related `cmd` into `command` so it does not clash with `dvc {cmd}` commands.
2. The fix has caused some other problems, for example: `dvc status -q` would not pass `-q` down to the status command, while `dvc -q status` would. I tried resolving the problem but today was not enough. Since the bugfix in question is most likely to get [scrapped](https://bugs.python.org/msg406123) I want to limit the python version to an unaffected …
> argparse: dont override cmd

- dvc/fs/utils.py
- dvc/objects/checkout.py
Fixes #6962, where GDdrive mounted on Colab was failing when trying to hardlink
with the message that the 'Function not implemented'.
> hardlink: fallback to other link methods if "Function not implemented" is raised

- dvc/repo/experiments/init.py
> exp init: hide metrics/plots from worktree on --type=live

- dvc/repo/experiments/init.py
Fixes issue of showing `plots` in non-interactive mode in `exp init`, mentioned in https://github.com/iterative/dvc/issues/6969.
> exp init: suppress plots if live is selected as a stage type

- dvc/command/experiments.py
- tests/unit/command/test_experiments.py
For consistency (https://github.com/iterative/dvc/issues/5515) with output format of other `diff_table` uses.
Docs P.R: https://github.com/iterative/dvc.org/pull/2988
---
Before:
```
$ dvc exp diff exp-1dad0 exp-1df77
Path         Metric    Value    Change
scores.json  auc       0.51676  -0.060799
Path         Param                   Value    Change
params.yaml  featurize.max_features  500      -1500
```
After: 
```
$ dvc exp diff exp-1dad0 exp-1df77
Path         Metric  exp-1dad0  exp-1df77  Change
scores.json  auc     0.577559   0.51676    -0.060799
Path         Param                   exp-1dad0  exp-1df77  Change
params.yaml  featurize.max_features  2000       500        -1500
```
> exp diff: Remove `--old` option.

- dvc/render/__init__.py
- dvc/render/base.py
- dvc/render/html.py
- dvc/render/image.py
- dvc/render/utils.py
- dvc/render/vega.py
- dvc/repo/plots/__init__.py
- dvc/repo/plots/template.py
- tests/func/plots/test_show.py
- tests/unit/render/test_html.py
- tests/unit/render/test_vega.py
Pre-requisite for #6840 -> #4455 
These changes *should* not break any existing behavior. 
Refactored existing `render` / `plots.template` logic in order to make it more "plugin" friendly so it's easier to add new renderers (i.e. plotly / parallel coordinates plot).
Open questions:
- Should `ImageRenderer` implement `as_json` (meaning a machine-shareable representation of the "plot"). Maybe we should use base64 for that (potentially even internally as `src`). 
- Should `ImageRenderer` be, somehow, template-based?. It looks that it could be generalized to follow a similar logic as `VegaRenderer` where DVC provides "anchor" data (the `src` in `<img>`) and the template can customize how to insert that data in the HTML. 
- Is there a reason to have `templates` in `dvc.repo.plots`? It looks …
> dvc render: Add RENDERERS registry.

- dvc/utils/serialize/_py.py
- tests/unit/utils/serialize/test_python.py
Add unit tests for `parse_py`
Closes  #6953
`dvc.org` P.R: https://github.com/iterative/dvc.org/pull/3014
> params: Use `ast.literal_eval` for python params.

- dvc/fs/local.py
- dvc/fs/utils.py
- dvc/info.py
- dvc/objects/checkout.py
- dvc/objects/db/base.py
- dvc/objects/db/slow_link_detection.py
- tests/func/test_add.py
- tests/unit/remote/test_slow_link_detection.py
All three of those use more or less the same logic for testing different
link types and maybe then using them. So now instead of having 3
implementations, we'll have just one.
Filesystem `transfer` now will not try to catch particular errno's, but
instead will just ignore any OSError and move down to the next link type
to try out, and if the last one fails - it will raise the last exception,
so if it is a common problem - we'll be able to see it.
This patch also removes `odb.confirmed_cache_type`, as it was caching
link type that is not really a cache-level thing, but rather a checkout thing,
that should only be cached for particular objects we are linking, as multiple
objects could be linked to different filesystems from the same odb (e.g.
external local output on hdd and local data on …
> dvc: use transfer in checkout/doctor/odb

- dvc/scm/git/__init__.py
Adds hint (when reminding to track files) to set core.autostage.
Related to #6929 and https://github.com/iterative/dvc.org/issues/2969.
Thoughts on this?
> scm: hint to autostage

- dvc/render/base.py
- tests/unit/render/test_renderer.py
Fixes: #6894
Cannot test it for now. Marking as [WIP] until I can do that or get confirmation its working on windows.
> plots: special chars handling for vega plots paths

- dvc/command/machine.py
- tests/func/machine/test_machine_status.py
- tests/unit/command/test_machine.py
fix #6838 
1. make machine status name optional.
2. show all machine status if no name provide.
3. add a new test for it.
An example of it.
> machine status: Make name argument optional

- dvc/command/machine.py
- tests/unit/command/test_machine.py
fix: #6940
`--global/system/project/local` help message are in some irrelevant
command `status`, `ssh`, `create`, `destroy`. These commands are more
related to running instances rather than `machine config`, level
options didn't work for them.
1. Remove `--global/system/project/local` options in `status`, `ssh`,
`create`, `destroy`.
2. Add a test for it.
> machine:remove help text for irrelevant commands

- dvc/scm/git/backend/dulwich/asyncssh_vendor.py
- tests/unit/scm/test_git.py
> dulwich: fallback to default SSH keys in asyncssh vendor

- dvc/command/machine.py
- dvc/compare.py
- dvc/config_schema.py
- dvc/ui/table.py
- tests/func/experiments/test_show.py
- tests/func/machine/conftest.py
- tests/func/machine/test_machine_config.py
- tests/func/machine/test_machine_status.py
- tests/unit/command/test_machine.py
- tests/unit/test_tabular_data.py
- tests/utils/__init__.py
fix #6892 
use table for the machine list outputs
Now the outputs looks like
```
$  dvc machine list
┏━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ name  ┃ cloud ┃ spot_price ┃ instance_hdd_size ┃ instance_type ┃ ssh_private ┃ instance_gpu ┃
┡━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ new   │ aws   │            │ 20                │               │ ***         │              │
│ myaws │ aws   │ 100.00000  │ 10                │ l             │             │ k80          │
└───────┴───────┴────────────┴───────────────────┴───────────────┴─────────────┴──────────────┘
$ dvc machine status foo
┏━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ name ┃ instance ┃ …
```
> Machine: use table for machine list and status outputs 

- dvc/repo/experiments/init.py
- dvc/ui/prompt.py
- tests/unit/ui/test_prompt.py
Some fixes along the way to make it more generic, but it still has
lots of features tied with exp init.
> ui.prompt: move prompts from exp init to ui.prompt

- setup.cfg
This version uses bumps asyncssh to a version that supports ProxyJump. This fixes the issue reported on discord: https://discord.com/channels/485586884165107732/485596304961962003/910866142594203689
*(With the exception that I haven't created a Github Issue, since we have already discussed this on the discord server)*.
> build: bump sshfs from 2021.8.1 to 2021.11.2

- .github/workflows/tests.yaml
- setup.cfg
pygit2 wheels should be now available.
Had to skip pytest-docker for Windows + Python 3.10 due to a dependency issue, see: docker/docker-py#2902.
> tests: run on Windows with Python 3.10

- setup.cfg
- tests/func/experiments/test_init.py
The `exp init` tests may just keep waiting on the prompts blocking tests.
The blocking of prompts is likely a failure in tests setup or a bug
in the implementation. It's hard to find out these failures or avoid it.
If they take longer than 1 second, they most likely have failed as
most of the tests take 0.25 seconds at max in Windows. So, using `pytest-timeout` is the
easiest approach here.
> exp init: timeout prompts' test

- dvc/repo/live.py
- tests/func/test_live.py
> live: Call webbrowser.open

- dvc/repo/__init__.py
- dvc/scm/base.py
- tests/func/test_repo_index.py
There is no `scm_context.ignore_list`. Instead of adding APIs, I am removing its use and replacing it with a loop (which is what it really did).
Looking at the code, I think we should really stop having side effects by just initializing a `Repo` instance:
https://github.com/iterative/dvc/blob/318b269ad118f198bb97b203e151529398da0f54/dvc/repo/__init__.py#L206-L219
> scm: remove ignore list

- tests/func/experiments/test_init.py
Sometimes, `tmp_dir` fixtures take longer than a second. Using `func_only`
makes it only consider the duration of test function run, excluding fixtures
duration.
> tests: timeout only on functions, excluding tests fixtures

- dvc/repo/experiments/__init__.py
> exp: respect repo `hardlink_lock` config for the exp scm lock

- dvc/exceptions.py
- dvc/repo/install.py
- dvc/scm/exceptions.py
- dvc/scm/git/__init__.py
- tests/func/test_install.py
Also introduces `dvc.scm.exceptions.SCMError` which is going to be an internal exception which all of the exceptions in `scmrepo` are going to inherit from. `dvc.scm.base.SCMError` will be renamed in the future after we extract `scmrepo`.
> scm: remove dependency from DvcException

- dvc/external_repo.py
- dvc/repo/__init__.py
- dvc/repo/brancher.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/apply.py
- dvc/repo/experiments/branch.py
- dvc/repo/experiments/diff.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/ls.py
- dvc/repo/experiments/push.py
- dvc/repo/experiments/remove.py
- dvc/repo/experiments/show.py
- dvc/repo/experiments/utils.py
- dvc/repo/scm_context.py
- dvc/scm/__init__.py
- dvc/scm/base.py
- dvc/scm/exceptions.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich/__init__.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- dvc/scm/git/stash.py
- tests/unit/scm/test_git.py
This PR splits scm-related exceptions into two kinds:
1. Internal scm exceptions that are in `dvc.scm.exceptions` and likely going to be available as `scmrepo.exceptions`.
2. External DVC-related exceptions in `dvc.scm.base` that is required for UI and dvc's API to work.
This will be available in `dvc.scm` when we migrate.
So, due to 2, there are some exceptions with the same name in both 1 and 2, but they serve a different purpose and are just reraised from one to another.
This PR is still incomplete, in that we have to decide what to do with raised `SCMError` exceptions. As DVC is unaware of these exceptions, places where we are checking for `DvcException` or where we just exit from the `main`, it will throw errors with:
```
Having any troubles? Hit us up at https://dvc.org/support, we …
```
> dvc.scm: refactor exceptions

- dvc/repo/experiments/executor/local.py
- dvc/repo/experiments/executor/ssh.py
- dvc/repo/experiments/pull.py
- dvc/repo/experiments/push.py
- dvc/repo/experiments/remove.py
- dvc/scm/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich/__init__.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- dvc/scm/progress.py
- tests/func/test_external_repo.py
This adds a support for reporting progress from Git in a structured
format. The gitpython already provides somewhat structured progress
reporting, dulwich on the other hand only provides git-like line
messages.
As gitpython uses git binary, it already parse this line format
in a structured way. This PR makes dulwich use the same machinery
to unify progress reporting for both dulwich and gitpython python.
This does add a dependency on gitpython even on dulwich backend,
so I am iffy if we should do this.
The alternative is to translate gitpython's progress reports to
string, and just use string messages as progress reports on both
dulwich and gitpython.
> scm: unified progress reporting in a structured way

- dvc/analytics.py
- dvc/dvcfile.py
- dvc/external_repo.py
- dvc/info.py
- dvc/repo/__init__.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/apply.py
- dvc/repo/experiments/branch.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/ls.py
- dvc/repo/experiments/remove.py
- dvc/repo/experiments/show.py
- dvc/repo/experiments/utils.py
- dvc/repo/init.py
- dvc/repo/metrics/show.py
- dvc/repo/params/show.py
- dvc/repo/scm_context.py
- dvc/scm/__init__.py
- dvc/scm/base.py
- dvc/scm/noscm.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_remote.py
- tests/func/test_diff.py
- tests/func/test_ls.py
- tests/func/test_scm.py
Makes it easier to decouple, we'd only need to rename
`dvc/scm/__init__.py` to `dvc/scm.py`.
As this reorder imports, this may be considered a minor breaking change.
> scm: restructure scm

- dvc/repo/scm_context.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/dulwich/__init__.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
This removes dependency from dvc.utils and dvc.types from DVC.
Some utils like fix_env, is_binary have been reimplemented.
Regarding fix_env and is_binary, I think eventually this
should be a responsibility of DVC itself to set.
relpath implementation in DVC also works with paths in
different drives in Windows. I have changed this to use
os.path.relpath for now.
> scm: remove dependency from dvc's utils in scm

- .pre-commit-config.yaml
- dvc/fs/git.py
- dvc/fs/scm.py
- dvc/repo/__init__.py
- dvc/repo/brancher.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/dulwich/__init__.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- dvc/scm/utils.py
- tests/func/experiments/test_experiments.py
- tests/func/test_fs.py
- tests/func/test_ignore.py
Also adds a wrapper for DVC to use as GitFileSystem in dvc.fs.scm.
This is temporary, and will be renamed back to dvc.fs.git after the
split.
Note that this filesystem is not fully compliant, it's only
meant to be compatible with our previous implementation.
> fs.git: refactor GitFileSystem to be fsspec compliant

- dvc/repo/experiments/__init__.py
- dvc/scm/git/__init__.py
This commit removes dvc specific message hardcoded in
scm.detach_head. Now that we are decoupling scm, we are
adding `client=` kwarg to be set by the caller.
> scm: remove dvc specific message; add client kwarg

- dvc/repo/init.py
- dvc/repo/scm_context.py
- dvc/scm/exceptions.py
- dvc/scm/git/backend/gitpython.py
This PR:
1. Moves warning from scm to `SCMContext`. The `scm` throws a `UnsupportedIndexFormat` which is caught on `SCMContext.add` and is swallowed after a warning.
2. The warning message is improved, since we promote `autostage` these days (https://github.com/iterative/dvc/pull/6985).
```console
WARNING: failed to add, add manually using:
git add .dvc/config .dvcignore .dvc/plots
See https://github.com/iterative/dvc/issues/610 for more details.
```
3. Make `Repo.init` use the same `scm_context` as the rest of the code does, and avoids using `scm.add` directly.
> scm: move warning on unsupported index to scmcontext

- .github/workflows/tests.yaml
Closes: #6975
Seems like 3.9.9 got released yesterday. So the argparse should be back to previous behavior.
> gha: allow builds for new 3.9 releases

- dvc/proc/exceptions.py
- dvc/proc/manager.py
- dvc/proc/process.py
- tests/unit/proc/test_process.py
Related to https://github.com/iterative/dvc/issues/6267
Local prerequisite for https://github.com/iterative/dvc/discussions/7002
- Adds `dvc.proc` module for managing background processes
- Process state information is kept within the manager directory
- Processes are backgrounded and output is redirected to a file (stdin interactivity is not currently supported)
- Backgrounding is handled through `multiprocessing.Process(daemon=True)`
Functionality is not used anywhere else in DVC yet (exp tempdir/queue runs will be the first place it gets added)
Python shell demo:
[![asciicast](https://asciinema.org/a/K5DA7pbbrRH1LBHcHLbTNqBje.svg)](https://asciinema.org/a/K5DA7pbbrRH1LBHcHLbTNqBje)
> proc: initial (local) process manager implementation

- dvc/proc/exceptions.py
- dvc/proc/manager.py
- dvc/proc/process.py
- tests/unit/proc/test_manager.py
fix: #7062 
1. Add `send_signal`, `kill`, `terminate` to ProcessManager.
2. Add tests for each of them.
> proc: implement process signaling(#7062)

- dvc/command/plots.py
- dvc/repo/live.py
- dvc/ui/__init__.py
- tests/unit/command/test_plots.py
Use `webbrowser.open` and resolve relpath for non WSL plattforms.
For reusing in #6913 and #6933
> ui: Add `open_browser`.

- dvc/repo/plots/__init__.py
- dvc/repo/plots/template.py
- tests/unit/render/test_vega.py
Fixes: #6911
Reverts: a1b146669c9d9241d424e10cc8266e0c5fdebf94
In #6550 we introduced templates in packages. While utilizing `importlib.resources` and including templates with our package makes sense for other types of builds, in the case of our binary packages and `pyinstaller` we cannot include package data, because of https://github.com/pyinstaller/pyinstaller/issues/2697.
What we could do with pyinstaller would be to create `resources` directory alongside `dvc` and include the templates there. That would require us to load our templates differently depending on whether we can load data from package (other builds) or `pyinstallers` `sys._MEIPASS` when using binary packages.
This seems much more error-prone …
> plots: revert templates in packages change

- dvc/objects/db/base.py
- tests/unit/remote/test_base.py
These are not used anywhere outside of odb, so we can make them private
to reduce the scope for the upcoming refactoring.
> odb: make some listing methods private

- dvc/fs/base.py
- dvc/objects/db/__init__.py
- dvc/objects/db/base.py
- dvc/objects/db/index.py
- tests/unit/remote/test_base.py
- tests/unit/remote/test_index.py
These are leftovers from old remotes, that clearly have nothing
to do with filesystems.
> fs: get rid of CHECKSUM_DIR_SUFFIX and is_dir_hash

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/base.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/executor/local.py
- dvc/repo/experiments/executor/manager.py
- dvc/repo/experiments/executor/ssh.py
- dvc/repo/experiments/gc.py
- dvc/repo/experiments/remove.py
- dvc/repo/experiments/show.py
- tests/func/experiments/executor/test_ssh.py
- tests/func/experiments/test_show.py
This does not change any user-facing DVC behavior, other than exp pidfile location (which was undocumented/for internal use only)
related to: https://github.com/iterative/dvc/issues/6440
prerequisite for: https://github.com/iterative/dvc/issues/6267
Currently in the experiments API, we have a clear separation between queuing/staging an experiment (generating a stash commit with the desired changes), and execution/reproduction. The problem right now is that "execution" includes other operations that should not be part of the "execution" step. Essentially both populating the temporary workspace and calling `Repo.reproduce` must always be done as a single operation right now. This is OK in the current local …
> exp: refactor (local) executors to start using process manager

- dvc/command/experiments/show.py
- dvc/compare.py
- dvc/render/plotly.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_experiments.py
- tests/unit/render/test_parallel_coordinates.py
- tests/unit/test_tabular_data.py
Closes #4455
Introduces the following new arguments / behavior to `dvc exp show`:
- `--html` 🤷
- `--sort-by {foo}` Defines the column to create colorscale from (Uses `Experiment` as default) 
- `--out {foo}`
- `--open`
- 
Using https://github.com/iterative/demo-fashion-mnist
- Interactivity
https://user-images.githubusercontent.com/12677733/144048287-4baa1784-08c0-4b74-8704-1bb5345f0af8.mp4
- Default: `dvc exp show -T --html`
- Customize color: `dvc exp show -T --html --sort-by accuracy`
- Interaction with other options: `dvc exp show -T --html -sort-by accuracy --exclude-metrics loss`
> exp show: Add parallel coordinates plot.

- dvc/fs/repo.py
> fs: repo: raise proper FileNotFoundError in metadata

- setup.cfg
Hoping to fix `dvc[s3]` installations in pipenv. Pipenv's resolver is in loop, backtracking ruamel.yaml from 0.17.17 to 0.17.11 continuously. I think this has to do more with `s3`'s dependency than `ruamel.yaml` as it only fails here. And, we are specifying dependency in 1.0.1 whereas aiobotocore has released 2.0 versions which is what is being installed, so it's redundant anyway. I am hopeful that this may help resolver with the simplification in constraints.
https://github.com/iterative/dvc-e2e/runs/4558989596?check_suite_focus=true#step:6:77
https://github.com/iterative/dvc-e2e/runs/4579223801?check_suite_focus=true
> s3: remove explicit dependency on aiobotocore; simplify constraints

- dvc/fs/hdfs.py
- tests/unit/fs/test_hdfs.py
See https://discord.com/channels/485586884165107732/485596304961962003/922875662694510663
```console
pip install git+https://github.com/skshetry/dvc.git@fix-hdfs-unstrip#egg=dvc[hdfs]
```
cc @ashimko
> fs.hdfs: skip port if not available

- setup.cfg
`krb5` does not provide wheels for Linux and Windows and needs to install system libraries for the wheel to be built/installed. This fails `dvc[all]` and `dvc[webhdfs]` installations in Linux and on Windows.
> deps: remove requests-kerberos from `webdhfs`; provide it via `webdhfs_kerberos`.

- dvc/config_schema.py
- dvc/objects/db/__init__.py
- dvc/objects/db/gdrive.py
- dvc/objects/db/oss.py
- tests/func/test_config.py
- tests/func/test_remote.py
These options are part of the default config for each particular remote.
Plugins will define their default config on their own, but for now, we keep
those in one config schema.
> odb: move verify option to config

- dvc/command/experiments/show.py
The function `_raise_error_if_all_disabled` is copyed wrongly to this
place during sub command refactoring. It used to be used in `exp gc`,
can be deleted from this function.
> exp show: remove a useless function

- dvc/repo/plots/__init__.py
- tests/func/plots/test_show.py
Fixes: iterative/cse#4
In the case of `dir` plots, when RepoFileSystem is unable to fetch the `dir` (eg no data in remote) plots collection will fail for the whole revision. We need an additional step that will "unpack" particular files from the dir, and add error for `dir` path to the result instead of failing the whole branch.
> plots: dir: handle no data in cache/remote

- dvc/command/experiments/show.py
- dvc/compare.py
- tests/unit/test_tabular_data.py
- TabularData: Add ignore_empty flag to drop_duplicates
- TabularData: Fix drop_duplicates for rich_text NaN
> TabularData: Add ignore_empty flag to drop_duplicates.
