iterative/dvc

- dvc/command/remote.py
> Fix typo in `dvc remote modify` output

- dvc/updater.py
> updater: Remove unnecessary `(` in logging

- setup.py
> completion: bump shtab

- dvc/repo/experiments/__init__.py
- tests/func/experiments/test_show.py
Should fix #4401.
* Locks experiments workspace when doing git operations
* minor test fixes
> experiments: fix flaky tests

- tests/func/experiments/test_experiments.py
It is for short period of time till it gets resolved.
See: #4401
> Mark test_new_simple as flaky

- dvc/output/local.py
- tests/dir_helpers.py
- tests/func/test_run_single_stage.py
> metrics: don't raise on dir during collection

- dvc/repo/experiments/__init__.py
- tests/func/experiments/test_experiments.py
> experiments: fix bug where wrong git branch checked-out before pull

- dvc/repo/experiments/show.py
- tests/func/experiments/test_show.py
> experiments: only show queued experiments for the current commit

- tests/func/test_install.py
Before, we were installing hooks at the start which was making checkouts
slower. With this change, it should improve these tests by twice as much. (previous 12s to ~4s).
Also, looks like these hooks are not that predictable, so they sometimes take as much as 15s for a single test. This could well be due to issues with GitPython.
> tests: install hook just before using it

- dvc/cache/local.py
- dvc/data_cloud.py
- dvc/tree/dvc.py
- dvc/tree/repo.py
- tests/unit/tree/test_dvc.py
- tests/unit/tree/test_repo.py
> external: avoid unnecessary hash computation

- dvc/command/experiments.py
- dvc/command/metrics.py
- dvc/repo/reproduce.py
- dvc/utils/diff.py
- dvc/utils/flatten.py
- scripts/hooks/hook-dvc.utils.flatten.py
- setup.py
> dvc: use flatten-dict instead of flatten-json 

- dvc/api.py
- dvc/cache/base.py
- dvc/cache/local.py
- dvc/external_repo.py
- dvc/hash_info.py
- dvc/output/base.py
- dvc/repo/diff.py
- dvc/stage/cache.py
- dvc/tree/base.py
- dvc/tree/dvc.py
- tests/func/remote/test_index.py
- tests/func/test_add.py
- tests/func/test_cache.py
- tests/func/test_checkout.py
- tests/func/test_data_cloud.py
- tests/func/test_gc.py
- tests/func/test_remote.py
- tests/func/test_repro.py
- tests/func/test_run_single_stage.py
- tests/func/test_tree.py
- tests/unit/output/test_local.py
- tests/unit/output/test_output.py
- tests/unit/stage/test_loader_pipeline_file.py
Related to #4144 , #3069 , #1676
> dvc: use HashInfo to interact with cache

- dvc/command/repro.py
> experiments: suppress repro --params option by default

- dvc/tree/repo.py
- tests/func/test_get.py
- tests/func/test_import.py
- tests/unit/tree/test_repo.py
Kudos @skshetry for catching this one and providing tests. :pray: 
Fixes #4510
> get/import: fix bug when working with mixed dirs

- dvc/repo/plots/__init__.py
- tests/func/plots/test_plots.py
Encountered this in viewer but also possible in the wild, see a test.
> Skip no data plots while rendering

- dvc/tree/__init__.py
- tests/unit/tree/test_tree.py
> tree: resolve deep remote:// urls

- dvc/cache/__init__.py
- dvc/tree/__init__.py
- dvc/tree/base.py
- tests/unit/remote/test_remote.py
- tests/unit/tree/test_tree.py
Kudos to @PeterFogh for catching this one :pray: 
> tree: validate resolved remote:// sections

- .github/workflows/tests.yaml
- .travis.yml
- setup.py
- tests/func/test_add.py
- tests/func/test_api.py
- tests/func/test_cache.py
- tests/func/test_import_url.py
- tests/func/test_run_multistage.py
- tests/func/test_update.py
- tests/remotes/__init__.py
- tests/unit/output/test_local.py
> github actions tests: initial

- tests/func/test_gc.py
- tests/func/test_import_url.py
Temporary fix for hdfs issue. See https://github.com/iterative/dvc/issues/4418
> tests: allow failure for hdfs tests

- dvc/repo/plots/__init__.py
- tests/func/plots/test_plots.py
> plot: accept any viable target in dvc repo

- dvc/stage/cache.py
- tests/unit/stage/test_cache.py
> run-cache: respect cache.shared config option

- setup.py
Kudos to @skshetry for catching this one in https://github.com/iterative/dvc/pull/4606
> setup: remove wheel from install_requires

- dvc/repo/experiments/__init__.py
- tests/func/experiments/test_experiments.py
> experiments: support cloning parent in detached-head state

- dvc/repo/brancher.py
- dvc/repo/experiments/show.py
Will fix #4587.
* Adds `sha_only` flag for brancher for cases where we only need the sha to be returned (as opposed to the comma separated list of sha + branch/tag names)
> experiments: fix --all-tags/--all-branches bug

- dvc/command/imp.py
- dvc/repo/imp.py
- tests/unit/command/test_imp.py
Fixes #4093
https://github.com/iterative/dvc.org/pull/1816
> import: add '--file' option

- dvc/remote/index.py
- dvc/repo/__init__.py
- dvc/repo/experiments/executor.py
- tests/unit/remote/test_index.py
> repo: move index_dir to RemoteIndex

- dvc/tree/hdfs.py
- tests/func/test_data_cloud.py
A user on ODS ran into this :slightly_frowning_face:
> hdfs: add a progress bar

- dvc/scm/git.py
scm:  Git: _add_entry_to_gitignore: writes unique entry to .gitignore
Fixes #4327
* [*] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.
* [*] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.
> application_process: scm: Git: _add_entry_to_gitignore: writes unique entry to .gitignore

- dvc/command/run.py
> completions: fix run command dependencies autocompletion

- dvc/main.py
> dvc: print version to debug log

- tests/unit/output/test_local.py
> test_str_workdir_outside_repo: roll back skip on windows

- dvc/cache/__init__.py
- dvc/command/base.py
- dvc/lock.py
- dvc/repo/__init__.py
- dvc/repo/init.py
- dvc/repo/plots/template.py
- tests/func/metrics/test_show.py
- tests/func/plots/test_plots.py
Still a semi-hacky approach that is a pre-requisite for using this in external repos as well.
> repo: don't create .dvc in read-only repos

- dvc/repo/experiments/__init__.py
- dvc/repo/reproduce.py
> experiments: fix checkpoints callback bug when pipeline includes data stages

- dvc/external_repo.py
Pre-requisite for #3590 and related.
> dvc: get rid of ExternalGitRepo

- dvc/repo/ls.py
> ls: pass repo_tree instead of repo

- .github/workflows/tests.yaml
> Use released version of Python3.9 on CI

- .github/workflows/packages.yaml
> github actions: windows: fix packaging

- tests/func/test_remote.py
> tests: fix test_remote::test_push_order

- tests/func/experiments/test_experiments.py
Mark test as flaky until #4717 is resolved
> tests: mark test_extend_branch as flaky

- tests/func/test_api.py
- tests/remotes/ssh.py
> tests: cloud: ssh: assert test execution on same drive as cache

- dvc/repo/experiments/__init__.py
- tests/func/experiments/test_experiments.py
> experiments: fix git stash mtime race condition

- dvc/command/version.py
Fix #3185
Documentation PR [here](https://github.com/iterative/dvc.org/pull/1866)
This PR will also form part of a forthcoming job application
> Added 'doctor' as an alias for 'version'

- tests/func/test_data_cloud.py
- tests/remotes/__init__.py
- tests/remotes/oss.py
- tests/remotes_env.sample
the new test suggests #4633 is a bug in the emulator.
> tests/remote: adding tests for real oss

- dvc/repo/__init__.py
- dvc/repo/experiments/__init__.py
> checkpoints: create final checkpoint commit after repro when needed

- dvc/path_info.py
- dvc/stage/cache.py
- tests/unit/test_path_info.py
> make pull --run-cache work with local remote having relative path

- .github/workflows/tests.yaml
- setup.py
https://flaky-dashboard.web.app
More info: https://github.com/GoogleCloudPlatform/flaky-service
> Track flaky tests using Google's service

- dvc/command/plots.py
> plots: don't allow  in non-dvc repo

- .github/workflows/tests.yaml
- setup.py
Reverts iterative/dvc#4749, it is failing quite a lot.
> Revert "Track flaky tests using Google's service"

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- tests/func/test_stage_resolver.py
- tests/unit/test_context.py
* Improve merging of vars and imported params, improve tracking
* Resolve paths correctly for params
> Add tests for resolving stage data

- dvc/command/experiments.py
Rich interprets certain braces in strings as markup tags, params/metrics fields should be wrapped with `rich.Text()` so that braces are escaped properly.
> experiments: fix list/dict params and metrics being displayed as empty string

- dvc/tree/gdrive.py
- setup.py
> [WIP] gdrive: get rid of empty file hack

- .github/workflows/tests.yaml
> gha: add aws creds

- dvc/repo/plots/__init__.py
> plot: fix no metrics data detection

- dvc/external_repo.py
- tests/unit/test_external_repo.py
fix #4692
Now, jobs honored for imported data. Some tests for these changes are still needed.
> `--jobs` now takes effect on imported data

- setup.py
> pyarrow: upgrade to 2.0.0

- dvc/repo/diff.py
> diff: handle empty output status

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/parsing/interpolate.py
- tests/unit/test_interpolate.py
> refactor context: provide interpolation through Context API

- scripts/build_windows.cmd
> build: test built binary

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/parsing/interpolate.py
> refactor: move interpolation logic inside the Context

- dvc/cache/base.py
> cache: refactor dir_info conversion

- dvc/tree/gs.py
> gs: don't forget to include file size

- .codecov.yml
> codecov: add target coverage, and threshold for patch and project

- dvc/tree/webdav.py
- setup.py
- tests/func/test_api.py
- tests/func/test_data_cloud.py
- tests/remotes/__init__.py
- tests/remotes/webdav.py
- tests/unit/remote/test_webdav.py
- tests/utils/httpd.py
> Add test server and tests for webdav

- dvc/dvcfile.py
- dvc/repo/experiments/__init__.py
> experiments: fix checkpoint/persist related checkout issues

- tests/remotes/s3.py
> tests: real_s3 fixture: use specific path

- .github/workflows/tests.yaml
> ci: add macos-11 @ py3.8, py3.9 to build matrix

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
- dvc/repo/experiments/show.py
- tests/func/experiments/conftest.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_show.py
Will close #4821.
* `dvc exp resume -r <checkpoint_rev> --params <new_params>...` can be used to start a new checkpoint branch from the specified intermediate checkpoint
> experiments: support branching w/modified params from intermediate checkpoint

- dvc/dvcfile.py
- dvc/parsing/__init__.py
- dvc/stage/loader.py
- tests/func/test_feature_flags.py
- tests/unit/stage/test_loader_pipeline_file.py
> parametrization: Move resolver to StageLoader from `Dvcfile`

- dvc/parsing/context.py
- tests/unit/test_context.py
> parametrization: raise appropriate error message on merge error

- dvc/parsing/context.py
- tests/func/test_stage_resolver.py
- tests/unit/test_context.py
> parametrization: improve key error message

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- tests/unit/test_context.py
- tests/unit/test_stage_resolver.py
> parametrization: improve set error message

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- tests/unit/test_context.py
* Catches MergeError
* Catches params file not existing error
> parametrization: improve 'vars' error message

- dvc/parsing/__init__.py
- tests/func/test_stage_resolver.py
> parsing: improve error messages when resolving keys of the stages

- dvc/parsing/__init__.py
> parametrization: improve error messages on foreach loop

- dvc/parsing/context.py
- tests/func/test_stage_resolver_error_msg.py
- tests/unit/test_context.py
> tests: add error message tests for resolving stages

- dvc/parsing/__init__.py
- dvc/schema.py
- tests/func/test_stage_resolver.py
- tests/func/test_stage_resolver_error_msg.py
> change foreach...in to foreach...do

- dvc/parsing/__init__.py
- tests/func/test_stage_resolver.py
- tests/func/test_stage_resolver_error_msg.py
> parametrization: change foreach stage name joiner from "-" to "@"

- tests/unit/tree/test_repo_metadata.py
I ran it this way before, to make it run fast. But, it's not ideal
for running with `xdist`.
> Fix metadata tests running with module-scoped fixtures

- dvc/tree/repo.py
This one was missed for some reason.
> tree.repo: use PathStringTrie consistently

- dvc/repo/__init__.py
- dvc/repo/get.py
- dvc/repo/get_url.py
- dvc/repo/ls.py
> types: fix typechecking errors in dvc/repo

- dvc/cache/base.py
- dvc/external_repo.py
- dvc/hash_info.py
- dvc/path_info.py
- dvc/scm/base.py
- dvc/scm/git.py
- dvc/stage/__init__.py
- dvc/stage/serialize.py
> types: fix typechecking errors around a few random places

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
> types: fix type checking errors in dvc.experiments

- dvc/repo/collect.py
- dvc/types.py
> types: fix type errors on dvc.collect

- dvc/tree/base.py
- dvc/tree/dvc.py
- dvc/tree/local.py
- dvc/tree/repo.py
> types: add types to dvc/tree

- dvc/command/dag.py
- dvc/command/experiments.py
- dvc/dependency/base.py
- dvc/output/base.py
- dvc/output/gs.py
- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/remote/local.py
- dvc/remote/slow_link_detection.py
- dvc/repo/params/show.py
- dvc/repo/plots/template.py
> types: fix typechecking errors (2)

- dvc/parsing/interpolate.py
- dvc/utils/__init__.py
- tests/func/test_stage_resolver_error_msg.py
This is what it looks like on a dark terminal:
And, on a light terminal:
> parametrization: print pretty interpolation errors

- .pre-commit-config.yaml
- tests/remotes/__init__.py
> pre-commit: update hooks

- dvc/command/data_sync.py
- dvc/command/remove.py
per https://github.com/iterative/dvc.org/pull/1971#pullrequestreview-538749492
and https://github.com/iterative/dvc.org/pull/1978#pullrequestreview-540445147
> cmd: matching help output to docs

- dvc/command/metrics.py
- tests/func/test_repro.py
- tests/unit/command/test_metrics.py
> Organize metrics as table

- .github/workflows/packages.yaml
> snap: publish to v1 channel

- dvc/command/experiments.py
- dvc/config.py
- dvc/repo/__init__.py
- dvc/repo/experiments/__init__.py
- dvc/repo/plots/diff.py
- tests/func/experiments/test_experiments.py
- tests/unit/command/test_experiments.py
> experiments: enable by default, support no_scm

- dvc/command/experiments.py
- dvc/command/repro.py
- tests/func/test_repro.py
Fixes https://github.com/iterative/dvc/issues/2988
https://github.com/iterative/dvc.org/pull/2011
> repro: remove deprecated --cwd

- dvc/tree/oss.py
> remote: fix pull error for large file with aliyun-oss

- scripts/build-requirements.txt
Backport of https://github.com/iterative/dvc/pull/5055 that tries fixing https://github.com/iterative/dvc/issues/5012
> [1.11] [BACKPORT] pin numpy for windows build

- scripts/build-requirements.txt
> pin numpy for windows build

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
> experiments: fix mypy errors

- dvc/scm/git/__init__.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
> git: fix mypy errors

- dvc/command/experiments.py
- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/utils/__init__.py
> misc: fix remaining mypy errors

- dvc/command/config.py
- dvc/config.py
- tests/func/test_cli.py
- tests/func/test_config.py
- tests/unit/command/test_config.py
> Implement dvc config --list

- dvc/system.py
> [1.11] [BACKPORT] system: _reflink_darwin: use fsencode for path

- dvc/tree/pool.py
- dvc/tree/ssh/__init__.py
> fix making too many ssh connections when pushing run cache (#4732)

- dvc/parsing/__init__.py
Related to #5101. Soon, the `key/item` might just be a default value rather than a special one.
> remove key/value magic/special string

- dvc/parsing/context.py
> Prevent loading non-dictionary based params/vars file

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor.py
- dvc/repo/reproduce.py
- dvc/scm/git/backend/dulwich.py
- dvc/stage/run.py
- tests/func/experiments/test_experiments.py
> experiments: handle `exp run` from within subdirs/subrepos

- dvc/repo/reproduce.py
- tests/func/test_repro_multistage.py
- tests/unit/repo/test_reproduce.py
Fixes #5082
Fixes (likely) #4893
> repro: simplify the logic for frozen stages

- dvc/scm/git/__init__.py
- dvc/scm/git/backend/pygit2.py
- setup.py
Implements stuff we need for the tree, but this is more to start filling
up pygit2 with something useful.
> git: add pygit2 skeleton

- dvc/command/data_sync.py
- dvc/repo/add.py
- dvc/repo/pull.py
- dvc/utils/__init__.py
- tests/func/test_import.py
Related: #4816
Signed-off-by: Ioana Grigoropol <ioana.grigoropol@gmail.com>
> pull: add glob option

- dvc/tree/local.py
Non-lazy logging, fspath, redundant exist check, etc.
> tree: local: remove misc redundant logic

- dvc/parsing/__init__.py
- dvc/parsing/context.py
> parametrization: move comment, fix exception error msg

- dvc/scm/git/backend/dulwich.py
* git push/fetch progress will be displayed with git cli equivalent status messages during dulwich push/fetch operations
i.e.:
```
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.01 KiB | 343.00 KiB/s, done.
Total 7 (delta 6), reused 0 (delta 0), pack-reused 0
```
Will be displayed on a single line via a no-total progress bar during `dvc exp push/pull`
> git: show progress when pushing/fetching git refs

- dvc/command/experiments.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/apply.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/executor/local.py
Will close https://github.com/iterative/dvc/issues/5105.
> experiments: cleanup minor UI issues

- dvc/scm/git/__init__.py
- tests/func/test_remove.py
- tests/func/test_scm.py
- tests/unit/scm/test_git.py
- tests/utils/__init__.py
modified behavior to unlink empty .gitignore files.
added corresponding unit & func test cases.
updated failing test cases.
no failing tests
Fixes #4962
* [] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.
> remove: delete .gitignore file if empty

- dvc/output/base.py
- dvc/repo/get_url.py
- tests/func/test_get_url.py
> dvc/tree/local: fix it for no repo/cache case

- dvc/command/data_sync.py
- dvc/repo/push.py
- tests/func/test_import.py
- tests/unit/command/test_data_sync.py
Related: #4816
Signed-off-by: Ioana Grigoropol <ioana.grigoropol@gmail.com>
> api: add globbing option for pushing

- dvc/repo/experiments/executor/base.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- setup.py
- tests/unit/scm/test_git.py
Will fix #5076.
WIP until upstream dulwich PR is released: https://github.com/dulwich/dulwich/pull/819
> experiments: commit with --no-verify in executors

- README.rst
Sourcerer is gone: https://github.com/sourcerer-io/sourcerer-app/issues/632
> Remove Sourcerer's hall of fame

- dvc/config.py
- dvc/external_repo.py
- dvc/repo/__init__.py
- tests/unit/test_external_repo.py
A more explicit way to deal with cache/remote adjustments that we do for external repos.
Pre-requisite for #3590 and #4604
> erepo: make repo configuration explicit

- dvc/command/metrics.py
- tests/unit/command/test_metrics.py
Fixes #4770.
Related PR for dvc.org: https://github.com/iterative/dvc.org/pull/2057
> cmd: implement '--show-md' flag for 'dvc metrics show' (#4770)

- tests/func/plots/test_show.py
Fixing my mistakes introduced during #4446
> tests: plots: fix plots call

- dvc/_debug.py
Otherwise, `continue` etc. would fail. 
> Reraise exception after pdb.post_mortem()

- dvc/_debug.py
I had to keep providing default value before when profiling
simple functions as an API. I added a default now, and
also made `debugtools` customizable so that you could
edit the code to, for example, have `pdb` enabled by default.
> debug functions: have a good default value

- dvc/cache/base.py
> Remove redundant comment

- dvc/scm/git/__init__.py
- dvc/scm/git/backend/pygit2.py
> scm: lazily load Git backends

- dvc/repo/diff.py
- tests/func/test_diff.py
> diff: account for deleted workspace data

- dvc/analytics.py
Startup time before and after this fix for `dvc stages -s` in `example-get-started` (not that big difference though, but for completion it is):
```console
$ time dvc stages -s
prepare   Produces data/prepared         
featurize Produces data/features         
train     Train *model*                  
evaluate  Generates scores.json, prc.json
dvc stages -s  0.44s user 0.04s system 99% cpu 0.477 total
```
```console
$ time dvc stages -s
prepare   Produces data/prepared         
featurize Produces data/features         
train     Train *model*                  
evaluate  Generates scores.json, prc.json
dvc stages -s  0.40s user 0.06s system 99% cpu 0.453 total
```
> analytics: lazily import

- dvc/command/config.py
I don't see any difference that much while doing `time`, as I think the `dvc.config` modules are loaded eventually anyway, but the startup time has improved.
We need to split the schema for the config and the `Config` class so that they are not compiled when importing.
> config command: lazily import

- dvc/command/add.py
- dvc/command/dag.py
- dvc/command/experiments.py
- dvc/command/repro.py
- dvc/command/version.py
- dvc/dvcfile.py
- dvc/exceptions.py
- dvc/utils/flatten.py
> Move misc. imports from command, make them lazy

- dvc/command/plots.py
- dvc/command/remote.py
- dvc/repo/__init__.py
> Misc imports lazy

- dvc/cache/base.py
- tests/func/test_checkout.py
> checkout: fix partial file checkouts in the same directory

- dvc/exceptions.py
- dvc/repo/add.py
- dvc/repo/brancher.py
- dvc/repo/commit.py
- dvc/repo/get_url.py
- dvc/repo/reproduce.py
- dvc/repo/run.py
- dvc/repo/update.py
- dvc/updater.py
> lazy imports on misc. repo command

- dvc/repo/experiments/__init__.py
- dvc/scm/git/__init__.py
- dvc/stage/__init__.py
- dvc/stage/utils.py
> Misc. imports made lazy: scm,experiments,stage

- dvc/repo/collect.py
- dvc/repo/plots/__init__.py
- dvc/repo/plots/template.py
> Make some imports lazy for plots

- dvc/cache/base.py
- dvc/output/base.py
- dvc/repo/commit.py
- dvc/stage/__init__.py
- tests/func/test_commit.py
> commit: support granularity (#4297)

- dvc/utils/serialize/_common.py
- dvc/utils/serialize/_toml.py
- dvc/utils/serialize/_yaml.py
> utils.serialize: lazy imports

- dvc/command/check_ignore.py
- dvc/command/checkout.py
- dvc/command/commit.py
- dvc/command/data_sync.py
- dvc/command/destroy.py
- dvc/command/diff.py
They are not a major pain point though. Just trying to push `dvc --version` a bit.
> cmd: imports lazy

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/parsing/interpolate.py
> parsing: make imports lazy

- dvc/repo/__init__.py
- dvc/repo/fetch.py
- dvc/repo/get.py
- dvc/repo/live.py
- dvc/repo/plots/__init__.py
- dvc/repo/run.py
- dvc/repo/stage.py
> Make imports on dvc.repo and dvc.repo.plots lazy

- dvc/_debug.py
- dvc/data_cloud.py
- dvc/rwlock.py
- dvc/stage/cache.py
- dvc/state.py
- dvc/utils/__init__.py
- dvc/utils/fs.py
- dvc/utils/html.py
> Misc. imports lazy on utils,stage.cache and dvc.*

- .pre-commit-config.yaml
- dvc/repo/add.py
- dvc/repo/params/show.py
- dvc/repo/plots/__init__.py
- dvc/stage/__init__.py
- dvc/types.py
- dvc/utils/collections.py
- setup.cfg
> fix mypy errors; add mypy precommit hooks

- dvc/command/diff.py
- dvc/repo/diff.py
- tests/func/params/test_diff.py
- tests/func/test_diff.py
- tests/unit/command/test_diff.py
This PR is my application for a job
fixes https://github.com/iterative/dvc/issues/5150
> dvc.command.diff: add renamed detection feature

- dvc/cache/base.py
- dvc/dependency/repo.py
- dvc/external_repo.py
- dvc/repo/fetch.py
- dvc/repo/get.py
- dvc/tree/base.py
- dvc/tree/repo.py
- dvc/utils/__init__.py
- tests/func/test_external_repo.py
- tests/func/test_get.py
- tests/func/test_get_url.py
- tests/func/test_import.py
- tests/func/test_import_url.py
- tests/func/test_repro.py
- tests/unit/test_external_repo.py
- tests/unit/tree/test_repo.py
> erepo: refactor download/fetch logic

- dvc/config_schema.py
- dvc/tree/s3.py
- tests/unit/tree/test_s3.py
> s3: Allow authentication using session token

- dvc/repo/experiments/run.py
- dvc/repo/run.py
- dvc/utils/__init__.py
- dvc/utils/cli_parse.py
- dvc/utils/collections.py
- tests/unit/test_run.py
- tests/unit/utils/test_cli_parse.py
- tests/unit/utils/test_collections.py
Trying to reduce code duplication for making way for #5253.
> move parsing params to utils

- dvc/cache/__init__.py
- tests/unit/repo/test_repo.py
> cache: don't initalize cloud cache until its needed

- dvc/tree/hdfs.py
- dvc/tree/webhdfs.py
Regression from #4973 and #4747
> hdfs: copy: don't read everything into memory

- dvc/info.py
- scripts/build-requirements.txt
- setup.py
> add  psutil to install requirement

- tests/unit/test_info.py
Leftover from https://github.com/iterative/dvc/pull/5232
> tests: remove psutil checks

- .pylintrc
- dvc/cache/base.py
- dvc/command/experiments.py
- dvc/ignore.py
- dvc/parsing/context.py
- dvc/parsing/interpolate.py
- dvc/pathspec_math.py
- dvc/repo/plots/data.py
- dvc/repo/stage.py
- dvc/scm/git/backend/gitpython.py
- tests/func/test_repro.py
From https://github.com/iterative/dvc/pull/5270#discussion_r559440586
> pylint: enable no-else-return

- dvc/external_repo.py
> erepo: separate caching and repo

- dvc/external_repo.py
- dvc/repo/__init__.py
> erepo: move misc stuff out of erepo

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/parsing/interpolate.py
Mostly types, and a few others
> Fix code-style issues in the parsing module

- setup.py
We've stopped using it a long time ago.
> reqs: tests: remove awscli

- dvc/external_repo.py
- dvc/repo/__init__.py
- dvc/tree/repo.py
- tests/unit/test_external_repo.py
- tests/unit/tree/test_repo.py
> dvc: get rid of ExternalRepo

- dvc/remote/base.py
This patch basically rewrites the pushing logic's multitasking system to work gradually instead of pre-allocating all tasks. Some results (3x10k (3 different targets being pushed with 10k files in them each), 50k, 250k) (blue is the master) (these graphs are constructed from the data taken in every 4 seconds and compares the RSS)
> push: Optimize pushing behavior for big datasets

- dvc/repo/collect.py
- dvc/repo/params/show.py
- dvc/repo/plots/__init__.py
- tests/conftest.py
- tests/unit/test_collect.py
- tests/unit/test_metrics.py
- tests/unit/test_params.py
- tests/unit/test_plots.py
Related to #5009 
Since viewer is going to rely on this behaviour I decided to write tests for it.
EDIT:
Introduced tests also verify that use case described [here](https://github.com/iterative/dvc/issues/4446#issuecomment-757373208) is avialable.
> metrics/plots/params: return ordered

- dvc/hash_info.py
> hash_info: add __str__

- dvc/repo/__init__.py
> repo: remove unused find_out_by_relpath

- tests/unit/scm/test_git.py
> unit.scm.test_git: use pytest instead of unittest

- tests/remotes/azure.py
- tests/unit/remote/test_azure.py
> tests: azure directory generation

- dvc/external_repo.py
- dvc/repo/__init__.py
- dvc/repo/ls.py
> list: don't clone local repos

- .github/workflows/tests.yaml
> cache pip directory on github actions

- dvc/dvcfile.py
- tests/unit/test_params.py
> params: support unicode characters

- dvc/remote/base.py
(250k files, master=blue), It is safe to assume that 750mb~ is the total memory consumption up to the point of future object creation. After that (750-1.3 GB) is the real part that is being optimized away. Generalizes the same approach used to optimize `push` in my previous PR.
> pull, fetch: optimize memory consuption by ~%35

- dvc/tree/ssh/connection.py
Thank you for the contribution - we'll try to review it as soon as possible. 🙏 Fixes #4277
> ssh: show total-size when uploading/downloading on ssh remote

- dvc/command/get.py
- dvc/command/get_url.py
- dvc/repo/get.py
- dvc/repo/get_url.py
- tests/unit/command/test_get.py
- tests/unit/command/test_get_url.py
> get, get-url: add --jobs option

- setup.py
- tests/__init__.py
- tests/func/test_output.py
- tests/remotes/hdfs.py
- tests/unit/dependency/test_hdfs.py
- tests/unit/output/test_hdfs.py
Pyarrow3.0.0 has now support for Python3.9
> pyarrow support for Python3.9

- dvc/repo/trie.py
> repo: remove unneeded filter

- dvc/command/config.py
- tests/func/test_cache.py
- tests/func/test_config.py
Per https://github.com/iterative/dvc.org/pull/2064
Not changing the internal terminology because we stick to Repo in a lot
of places there and adjusting all of it would be wasteful. Maybe in the
future.
> cli: config: rename --repo to --project

- .github/workflows/tests.yaml
Thank you for the contribution - we'll try to review it as soon as possible. 🙏  Part of #4468
> gha: switch to pre-commit/action for caching

- dvc/api/__init__.py
- dvc/repo/__init__.py
> api: use Repo.open

- dvc/repo/experiments/gc.py
> exp gc: prune any exp/exec refs which point to gc'd experiments

- dvc/tree/gs.py
> gs: fix test failures caused by .ls()

- setup.py
Related to https://github.com/iterative/vscode-dvc/issues/90
> git: update dulwich dependency to 0.20.18

- dvc/cache/base.py
This makes all cache objects go through the same logic, so that all of
the appropriate rules are applied to them (e.g. proper permissions).
In the end our save/transfer logic should be outside of cache (same as
checkout) and should build appropriate objects and then just save them
into cache (aka odb) with `cache.add()`(aka `odb.add_object()`).
Pre-requisite for #5337
> cache: use add() to add objects to cache

- dvc/checkout.py
- dvc/tree/local.py
- dvc/tree/repo.py
- dvc/utils/__init__.py
- tests/func/test_add.py
- tests/func/test_install.py
- tests/func/test_repro.py
- tests/func/test_run_single_stage.py
- tests/func/test_state.py
- tests/func/test_utils.py
- tests/unit/utils/test_stream.py
> utils: don't use unnecessary exists() calls

- dvc/repo/experiments/executor/local.py
> exp: cleanup executor temp directories ourselves

- dvc/command/stage.py
- dvc/repo/run.py
- dvc/repo/stage.py
- dvc/stage/utils.py
- dvc/utils/cli_parse.py
- tests/conftest.py
- tests/unit/command/test_stage.py
- tests/unit/test_metrics.py
- tests/unit/test_params.py
- tests/unit/test_plots.py
- tests/unit/utils/test_cli_parse.py
> stage: implement add/create methods in stage loader

- dvc/cache/base.py
- dvc/cache/local.py
- dvc/checkout.py
- dvc/dependency/repo.py
- dvc/objects.py
- dvc/output/base.py
- dvc/repo/fetch.py
- dvc/tree/base.py
- dvc/tree/dvc.py
- dvc/tree/memory.py
- setup.py
- tests/func/test_add.py
- tests/func/test_cache.py
- tests/func/test_checkout.py
- tests/func/test_commit.py
- tests/func/test_external_repo.py
- tests/unit/output/test_local.py
- tests/unit/test_external_repo.py
- tests/unit/tree/test_dvc.py
- tests/unit/tree/test_repo.py
Pre-requisite for #5337 and #829
> dvc: introduce File/Tree cache objects

- dvc/cache/base.py
- dvc/dependency/repo.py
- dvc/objects.py
- dvc/output/base.py
- dvc/repo/fetch.py
- tests/func/test_external_repo.py
- tests/unit/test_external_repo.py
> cache: move save() to objects

- dvc/cache/base.py
- dvc/objects.py
Unnatural leftover from previous PRs
> cache: add: accept object id and it's path

- dvc/repo/update.py
- dvc/stage/imports.py
- tests/unit/command/test_update.py
> update: support --jobs even without --to-remote

- dvc/cache/base.py
- dvc/cache/local.py
- dvc/cache/ssh.py
- dvc/checkout.py
- dvc/data_cloud.py
- dvc/objects.py
- dvc/output/base.py
- dvc/remote/base.py
- dvc/tree/base.py
- dvc/tree/dvc.py
- tests/func/test_cache.py
- tests/func/test_checkout.py
- tests/func/test_gc.py
- tests/func/test_remote.py
> cache: misc cleanups

- .github/workflows/tests.yaml
- tests/__main__.py
> tests: use -n=auto and --dist loadscope

- dvc/output/base.py
- tests/func/test_checkout.py
> output: handle missing hash_info.nfiles

- dvc/ui/__init__.py
- dvc/utils/__init__.py
Related to https://github.com/iterative/dvc/issues/5347
> introduce dvc.io module to consolidate io utilities

- dvc/api/__init__.py
- dvc/checkout.py
- dvc/dependency/repo.py
- dvc/objects.py
- dvc/output/base.py
- dvc/repo/diff.py
- dvc/tree/azure.py
- dvc/tree/base.py
- dvc/tree/dvc.py
- dvc/tree/gdrive.py
- dvc/tree/gs.py
- dvc/tree/hdfs.py
- dvc/tree/http.py
- dvc/tree/local.py
- dvc/tree/memory.py
- dvc/tree/repo.py
- dvc/tree/s3.py
- dvc/tree/ssh/__init__.py
- dvc/tree/webdav.py
- dvc/tree/webhdfs.py
- tests/func/test_remote.py
- tests/func/test_tree.py
- tests/unit/remote/test_azure.py
- tests/unit/remote/test_remote_tree.py
- tests/unit/tree/test_dvc.py
- tests/unit/tree/test_repo.py
> tree: get_hash: accept explicit hash name

- dvc/tree/gdrive.py
- setup.py
- tests/func/test_tree.py
- tests/remotes/gdrive.py
- tests/unit/remote/test_gdrive.py
> gdrive: Implement .ls() protocol / proper tree walking with .walk_files()

- dvc/dependency/__init__.py
- dvc/fs/__init__.py
- dvc/fs/base.py
- dvc/info.py
- dvc/output/__init__.py
- dvc/output/base.py
> fs/outs/deps: remove supported() logic

- dvc/fs/gs.py
> gs: ls: add etag

- scripts/build_posix.sh
Kudos to @DavidGOrtega for finding and reporting this issue in CML.
> build: deb/rpm: require git >= 1.7.0

- dvc/fs/base.py
- setup.py
> fs: remove unused use_state decorator

- dvc/api/__init__.py
- dvc/checkout.py
- dvc/dependency/repo.py
- dvc/objects/__init__.py
- dvc/objects/stage.py
- dvc/output/base.py
- dvc/repo/diff.py
- dvc/repo/fetch.py
- tests/func/test_add.py
- tests/func/test_data_cloud.py
- tests/func/test_external_repo.py
- tests/func/test_remote.py
- tests/unit/fs/test_dvc.py
- tests/unit/fs/test_repo.py
- tests/unit/test_external_repo.py
Initial pre-requisites for getting rid of `get_hash`.
> objects: separate staging

- dvc/parsing/interpolate.py
- tests/unit/test_interpolate.py
> parametrization: remove support for double braces

- setup.py
> Update requirements of dulwich to 0.20.19

- dvc/dvcfile.py
- tests/unit/test_lockfile.py
> dvc.lock: raise error if the file is gitignored

- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- tests/unit/scm/test_git.py
Related to https://github.com/iterative/dvc/issues/2215
> git: implement dulwich add --update

- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/pygit2.py
> pygit: implement get_refs_containing

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/show.py
- dvc/repo/experiments/utils.py
- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- dvc/scm/git/objects.py
> pygit: implement resolve_commit

- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/pygit2.py
> pygit/dulwich: implement create branch

- setup.py
- tests/func/test_live.py
> live integration: turn on tests

- dvc/command/stage.py
* Replaced 'Produces' with 'Outputs'
* Replaced 'Stage depends on' with just 'Depends on'
* Changes help text of --names-only and --fail
Addressing some of the review comments from https://github.com/iterative/dvc/pull/5282#pullrequestreview-571831191.
> stage:list: update output and help text

- .pylintrc
- dvc/config_schema.py
- dvc/fs/azure.py
- setup.py
- tests/unit/remote/test_azure.py
> azure: migrate AzureFileSystem to fsspec

- dvc/fs/azure.py
Resolves the regression mentioned in https://github.com/iterative/dvc/pull/5463#issuecomment-783314506 
Original (before adlfs):
```
+ dvc push bigfile                                                                                                                  
real    2m11,028s                                                                                                                   
user    0m1,697s
sys     0m0,419s
```
Current master:
```
+ dvc push bigfile                                                                                                                  
real    4m39,079s                                                                                                                   
user    0m1,822s
sys     0m0,636s
```
This PR:
```
+ dvc push bigfile …
```
> azure: transfer bigger chunks of data

- dvc/utils/stream.py
- tests/unit/utils/test_stream.py
I believe this resolves #5506 though I wasn't able to reproduce it locally (or with s3)
> utils: proper file interface for HashedStreamReader

- dvc/fs/azure.py
> azure: support service principal in error messages as login_method

- dvc/repo/experiments/show.py
> exp show: fix bug where already collected experiment results could be dropped

- dvc/stage/imports.py
Thank you for the contribution - we'll try to review it as soon as possible. 🙏 From @jorgeorpinel's suggestion in https://github.com/iterative/dvc/pull/5475#issuecomment-784876723
> update: clear error message for updating repo imports

- dvc/command/completion.py
- dvc/command/experiments.py
- tests/unit/command/test_experiments.py
Will close https://github.com/iterative/dvc/issues/5518
Adds bash completion for commands which take experiment names
> exp: bash tab completion

- setup.py
> setup: move google-cloud-storage to test requirements

- dvc/repo/experiments/diff.py
Related to #5530
Fixes issue where short experiment names would not be resolved in `dvc exp diff`
> exp diff: fix unresolved experiment names bug

- setup.py
Will close https://github.com/iterative/dvc/issues/5471.
> dulwich: update to 0.20.20

- dvc/dependency/repo.py
- dvc/fs/s3.py
- dvc/objects/stage.py
- tests/unit/test_external_repo.py
Related to https://github.com/iterative/dvc-bench/issues/234
> dependency: repo: try to fetch before staging

- dvc/version.py
- setup.py
> setup: rename azure.indentity to azure-identity

- dvc/state.py
Kudos @skshetry for the discovery, research and fix.
Fixes #5563
> state: use pickle v4

- dvc/scm/git/__init__.py
- dvc/scm/git/backend/base.py
- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/gitpython.py
- dvc/scm/git/backend/pygit2.py
- dvc/scm/git/stash.py
- setup.py
- tests/func/test_scm.py
- tests/unit/scm/test_git.py
> pygit/dulwich: implement stash functionality

- README.rst
> Add Barrak, Eghan & Adam citation

- README.rst
> Add a link to Barrak&Adams citation

- .pylintrc
- setup.py
Started having some issues with pylint-pytest on CI after a new release.
Refer to log for more info: https://github.com/iterative/dvc/pull/5602/checks?check_run_id=2084322100
Opened an issue in the `pylint-pytest` repo as well, see https://github.com/reverbc/pylint-pytest/issues/13.
> update pylint and pin dependencies

- dvc/fs/http.py
- tests/unit/remote/test_http.py
Closes https://github.com/iterative/dvc/issues/5564
> http: fix info() if there is no content-length header

- .github/ISSUE_TEMPLATE/bug_report.md
Adding some links to help user gather more information regarding the issue.
> Add a link to help debugging more information regarding the issue

- dvc/command/stage.py
Related to https://github.com/iterative/dvc.org/issues/2253
docs PR: https://github.com/iterative/dvc.org/pull/2290
> stage add: unsuppress -c/--checkpoints help text

- setup.py
> setup: remove duplicate 'pytest-cov' dependency

- dvc/stage/imports.py
> update: use unresolved path with --to-remote calls

- dvc/fs/fsspec_wrapper.py
- tests/func/test_fs.py
> fsspec: support raw buckets on path splitting

- dvc/logger.py
- tests/unit/test_logger.py
> Using existing logging level if defined in addLoggingLevel

- setup.py
See https://github.com/reverbc/pylint-pytest/issues/13
> Update pylint-pytest to 1.0.3

- .github/workflows/packages.yaml
- scripts/build-requirements.txt
- scripts/pyinstaller/hooks/hook-googleapiclient.model.py
> build: upgrade pyinstaller to 4.2

- .github/workflows/packages.yaml
- scripts/build.py
- scripts/fpm/notarize.py
- scripts/fpm/sign.py
- scripts/pyinstaller/entitlements.plist
- scripts/pyinstaller/sign.py
> build: add osx signing/notarization

- .github/dependabot.yml
- .github/workflows/tests.yaml
> Add dependabot to update github-actions and python requirements

- dvc/fs/base.py
- dvc/remote/base.py
- tests/func/test_external_repo.py
> pull: skip isdir() checks on downloading files

- .github/workflows/tests.yaml
- test_requirements.txt
We are not using this plugin since we remove flaky-service.
> test requirements: remove pytest-tap

- test_requirements.txt
> dependencies: pin urllib3 to 1.26.4

- MANIFEST.in
> Add test_requirements.txt to the manifest

- setup.py
> git: update dulwich to 0.20.21

- scripts/fpm/build.py
Will fix https://github.com/iterative/dvc/issues/5738
> build: fix fpm build zsh-completion path

- dvc/ignore.py
- tests/func/test_ignore.py
Will fix #5740
See https://github.com/iterative/dvc/issues/5740#issuecomment-810849234 for explanation
> dvcignore: ignore file '.git' by default

- dvc/command/experiments.py
> exp show: fix queued exp display

- dvc/scm/git/backend/dulwich.py
- dvc/scm/git/backend/pygit2.py
Will close https://github.com/iterative/dvc/issues/5627
> git: better error message if commit user is not configured

- setup.py
> setup: bump adlfs to 0.7

- dvc/repo/experiments/show.py
> exp show: fix bug where params from commits were merged with workspace values

- dvc/repo/experiments/executor/base.py
> exp run: suppress "finished run" output on --dry

- dvc/external_repo.py
> get rid of disutils

- dvc/command/data_sync.py
- dvc/command/experiments.py
- dvc/command/gc.py
- dvc/command/metrics.py
Consistency with `exp show`
WAITING FOR APPROVAL
> dvc: add -A flag for * --all-commits

- dvc/config_schema.py
- dvc/fs/hdfs.py
Closes https://github.com/iterative/dvc/issues/5645
I have tested the kereberos authentication on my local Ambari hadoop cluster. I haven't written any unit test cases as there was no existing test cases for the HDFS connection. I think may be because of remote connections.
Edit: These failed tests doesn't seem to be specific to my changes. Can you please help me with some pointer here?
> Add support for kerberos token based auth

- dvc/command/stage.py
> cmd: stage list: use ui.table

- .coveragerc
- dvc/compare.py
- dvc/ui/table.py
- tests/unit/test_tabular_data.py
This PR combines the earlier `ui.table()` that we had, and provides a nice interfaces around the table as a part of the data structure. Please take a look at how we use this in #5872.
> ui: tabular data

- dvc/command/experiments.py
One visible change here is that now baseline rows are styled as bold.
> refactor exp show: use new abstractions

- dvc/command/diff.py
- dvc/utils/diff.py
- tests/unit/command/test_diff.py
Last PR for the table refactor.
> diff: use ui.table for --show-md

- test_requirements.txt
Reverts iterative/dvc#5850
Latest version is failing: https://github.com/iterative/dvc/pull/5889/checks?check_run_id=2448142929#step:7:242
> Revert "build(deps): bump pylint-pytest from 1.0.3 to 1.1.2"

- dvc/output/local.py
- dvc/scm/git/__init__.py
- tests/func/test_add.py
Fixes #5870 + improves internal exc message.
> output: relative paths outside of repo

- dvc/command/experiments.py
Still trying to get rid of `tree` from the `collect_rows`. I will follow up more in the upcoming PR, and also move the `[[bold]]` with the `rich.text` format as it messes up the output for other kinds of tables.
Please do review the changes correctly, I tried to have it equivalent, but might have missed something.
> simplify experiments row collection logic

- dvc/command/ls/__init__.py
- tests/unit/command/ls/test_ls.py
> list: add --show-json option

- dvc/command/metrics.py
- dvc/compare.py
- tests/func/metrics/test_diff.py
- tests/unit/command/test_metrics.py
- tests/unit/test_compare.py
> metrics diff/show: rollback to rounding fractional digits with precision

- dvc/command/experiments.py
Trying to remove tree and the bold/row-styling part even more
> exp show: decoupling tree and styling from row collection

- .github/workflows/tests.yaml
> notify on slack for CI failures

- dvc/fs/s3.py
- tests/unit/fs/test_s3.py
Something I missed on the migration PR.
> s3: respect credentialpath/configpath

- .github/workflows/tests.yaml
- tests/dir_helpers.py
> run gdrive tests in a single job, run all on schedule

- dvc/utils/fs.py
- tests/dir_helpers.py
> tests: skip copying sqlite files in test directories

- dvc/repo/plots/__init__.py
- tests/func/plots/test_show.py
Studio ran into it for `dvclive` directory. CC @Suor 
https://sentry.io/organizations/iterative/issues/2382799173/?project=5220519&referrer=slack
> plots: handle NoRemoteError for dirs

- dvc/ignore.py
- tests/unit/test_ignore.py
Slight adjustments to make it cleaner. Followup for #6000 
> dvcignore: refactor from_file(s)

- dvc/command/ls/__init__.py
- tests/func/test_ls.py
- tests/unit/command/ls/test_ls.py
- tests/unit/command/ls/test_ls_colors.py
> ls: use ui.write

- dvc/stage/__init__.py
- tests/unit/stage/test_stage.py
> stage: allow duplicate values in _read_env

- dvc/command/cache.py
- dvc/command/check_ignore.py
- tests/func/test_check_ignore.py
- tests/func/test_odb.py
- tests/unit/command/test_cache.py
> ui: migrate cache:dir and check-ignore to ui.write

- dvc/command/checkout.py
- tests/func/test_checkout.py
- tests/func/test_data_cloud.py
- tests/unit/command/test_checkout.py
> ui: migrate checkout to ui.write

- dvc/command/completion.py
> ui: migrate completion to ui.write

- dvc/fs/dvc.py
- tests/unit/fs/test_dvc.py
> dvcfs: open: raise FileNotFoundError on missing version info

- dvc/command/dag.py
> ui: migrate dag to ui.write

- setup.py
> setup: bump dulwich to 0.20.23

- dvc/compare.py
Locally, mypy was raising these errors which were not being raised in pre-commit (as it hadn't changed at all). We should be using nox/tox for this purpose (I am creating a PR).
> fix mypy errors

- dvc/dependency/__init__.py
- dvc/output.py
Noticed that we were building schema in a convoluted way when reviewing https://github.com/iterative/dvc/pull/6054.
> output/dep: specify schema as a dictionary

- README.rst
> AirFlow integration link

- .pre-commit-config.yaml
I added it for the `autoupdate`, we are already running them in Github actions. 
> try skipping local pre-commit hooks

- .github/workflows/packages.yaml
> ci: move to ubuntu-18 from ubuntu-16

- dvc/repo/ls.py
- tests/func/test_ls.py
> ls: specify rev as kwarg

- README.rst
> Add Studio to the related technologies list

- dvc/stage/monitor.py
- tests/func/experiments/test_checkpoints.py
> stage: monitor: don't forget to unprotect outs

- dvc/fs/webdav.py
- tests/unit/remote/test_webdav.py
- tests/utils/__init__.py
- tests/utils/asserts.py
Most of the tests are regarding auth mechanisms.
> fix webdav tests and then add some

- dvc/config_schema.py
- dvc/fs/azure.py
Follow up on https://github.com/iterative/dvc/pull/5833#discussion_r653374061
> azure: add allow_anonymous_login option to the schema

- dvc/command/config.py
- dvc/command/data_sync.py
- dvc/command/destroy.py
- dvc/command/diff.py
- dvc/command/experiments.py
- dvc/command/gc.py
- dvc/command/get.py
- dvc/command/init.py
- dvc/command/live.py
- dvc/command/metrics.py
- dvc/command/params.py
- dvc/command/plots.py
- dvc/command/remote.py
- dvc/command/repro.py
- dvc/command/root.py
- dvc/command/status.py
- dvc/command/version.py
- dvc/ui/__init__.py
- tests/func/plots/test_show.py
- tests/func/test_config.py
- tests/func/test_data_cloud.py
- tests/func/test_root.py
- tests/func/test_version.py
- tests/unit/command/test_diff.py
- tests/unit/command/test_get.py
- tests/unit/command/test_metrics.py
- tests/unit/command/test_params.py
- tests/unit/command/test_plots.py
- tests/unit/command/test_status.py
> ui: migrating rest to the ui.write

- dvc/fs/local.py
- setup.py
> Bump fsspec version

- dvc/fs/local.py
- setup.py
> setup: update fsspec to 2021.6.1

- dvc/scm/git/backend/pygit2.py
- tests/unit/scm/test_git.py
> pygit: handle annotated tags in resolve_refish

- dvc/command/experiments.py
> `run`: update `-h` message

- dvc/progress.py
- dvc/repo/add.py
I broke the progress bar for a single target on yesterday's refactoring. Just trying to fix it now.
> add: fix progress bar on single target

- dvc/repo/add.py
Very small optimization that won't have much effect, but cleans up the code a bit.
> add: reduce os.fspath calls on recursive add

- dvc/fs/s3.py
S3: SSL Certificate Error
Fixes #5972 .
> fs: s3: don't forget to pass verify option

- scripts/build_package.sh
- scripts/pypi_upload.sh
- setup.cfg
Kudos @skshetry for discovering that we've been publishing py2.py3
wheels on pypi and researching the cause.
Co-authored-by: Saugat Pachhai <suagatchhetri@outlook.com>
> pkg: don't build universal wheels

- dvc/repo/imp_url.py
- tests/func/test_import_url.py
> import-url: compute the stage hash in --to-remote

- setup.py
> update webdav4 to latest fsspec version

- tests/func/test_data_cloud.py
see https://github.com/iterative/dvc/issues/6347
> ci: temporarily mark gdrive xfail

- tests/unit/test_daemon.py
- tests/unit/test_prompt.py
Part of #1819 
PR doesn't require documentation updates.
> tests: moved few unittest tests to pytest

- dvc/fs/fsspec_wrapper.py
- dvc/fs/oss.py
- dvc/progress.py
[![asciicast](https://asciinema.org/a/NJlF0wwd2hSLb3yPqe7jg1N9C.svg)](https://asciinema.org/a/NJlF0wwd2hSLb3yPqe7jg1N9C)
>  fsspec: implement callback mixins 

- dvc/command/experiments.py
> exp gc: fix `--queued` warning message

- scripts/build-requirements.txt
- scripts/pyinstaller/build.py
- scripts/pyinstaller/hooks/hook-dvc.py
Fixes https://github.com/iterative/cml/issues/692
> pyinstaller: build: check dvc doctor output

- dvc/repo/experiments/__init__.py
> Update `dvc exp branch` help

- dvc/utils/serialize/_yaml.py
- setup.py
- tests/unit/utils/serialize/test_yaml.py
New `ruamel.yaml` version fixes base class for DuplicatedKeyError :
https://sourceforge.net/p/ruamel-yaml/tickets/389/
Fixes recent build failures.
EDIT:
huh, didn't know sourceforge has ticketing mechanism. We could have report that.
> ruamel.yaml: adjust to new DuplicatedKeyError

- setup.py
> restrict typing_extensions version for py3.10

- .github/workflows/packages.yaml
- dvc/machine/backend/terraform.py
- dvc/tpi/__init__.py
- tests/unit/machine/test_terraform.py
Also removes `terraform` from the package installations, except for `pip` where it will be installed as a part of the `tests` extra
> tpi: lazily import python_terraform

- setup.py
- test_requirements.txt
Close https://github.com/iterative/dvclive/issues/149 
Close https://github.com/iterative/dvclive/issues/32
> Added dvclive to tests

- README.rst
Also stopping from misleading users with always green badge.
> Remove travis ci badge

- scripts/pyinstaller/hooks/hook-dvc.py
See https://github.com/iterative/dvc/runs/3535516030.
> build: copy fs.http dependencies 

- .github/workflows/packages.yaml
> Allow running package build manually on other PRs

- README.rst
Replaces the old https://github.com/sourcerer-io/sourcerer-app/issues/632
preview: https://github.com/iterative/dvc/pull/6552/files?short_path=7b3ed02#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168f or https://github.com/casperdcl/dvc/tree/contrib-avatars#contributing
/CC @jendefig
> add contrib avatars

- setup.py
> bump webdav4 to 0.9.1

- dvc/fs/http.py
- tests/unit/remote/test_http.py
> http: pass prepared filesystem arguments

- requirements/tests.txt
`beautifulsoup4` was used in initial version of plots, later the tests were changed, we don't use it anymore
> tests: requirements: remove beautifoulsoup4

- dvc/repo/diff.py
Also no longer using `repofs` for staging. Significantly speeds up `dvc diff`:
Before:
```
$ pytest tests/benchmarks/cli/commands/test_diff.py --size large
test_diff-diff-noop     13.3057
test_diff-diff          43.4180
```
After:
```
$ pytest tests/benchmarks/cli/commands/test_diff.py --size large
test_diff-diff-noop      2.6598
test_diff-diff          30.0593
```
Really, this is more of a temporary mitigation before https://github.com/iterative/dvc/issues/6594
> diff: don't forget to use dvcignore and state

- dvc/command/config.py
- dvc/config.py
- tests/func/test_config.py
dvc cli: fixed error in 'dvc config --list' in non repo dir
Fixes #6496
> dvc cli: fixed error in 'dvc config --list' in non repo dir

- .github/workflows/tests.yaml
Looks like we are running into timeouts from time to time, need to investigate what's going on.
> gha: increase timeouts

- dvc/dvcfile.py
- dvc/exceptions.py
- dvc/logger.py
Proposing a `__pretty_exc__` data model for exceptions that can provide prettier exceptions. 
With an example on #5371, the whole thing is a bit fragile though.
Also related: https://github.com/iterative/dvc/issues/6285
---
> exceptional exceptions

- dvc/_debug.py
0. `pip install yappi`
1. add `--yappi` at the end of any command.
2. Install `kcachegrind`/`qcachegrind`.
3. Open the file, which is in the form of `callgrind.dvc-{id}.out`format with `{k,q}cachegrind`.
I haven't really used this that much, so you'd have to see how this works. :)
Related: https://github.com/iterative/dvc/issues/6627 (not closing it yet, let's see how this works).
> debug: add yappi, callgrind output support

- tests/conftest.py
- tests/docker-compose.yml
- tests/remotes/__init__.py
- tests/remotes/ssh.py
> ssh: use a docker-based testing environment

- dvc/fs/ssh.py
- tests/unit/fs/test_ssh.py
> ssh: fix path normalization on windows

- dvc/state.py
Pre-requisite for making state work with other filesystems.
> state: cleanup redundant or localfs-specific logic

- dvc/fs/http.py
> http: allow reading proxies from the current environment;

- dvc/config_schema.py
- dvc/fs/s3.py
Fixes #6241
https://github.com/iterative/dvc.org/issues/2834
> remote: add support for Amazon S3 timeout configuration

- LICENSE
> add licence year + company

- setup.cfg
- setup.py
> Move static metadata to setup.cfg

- setup.cfg
Signed-off-by: Pablo Woolvett <pablowoolvett@gmail.com>
> build(setup): avoid leaking tests package into site-packages

- requirements/default.txt
> Bump typing_extensions to >=3.7.4

- .github/workflows/tests.yaml
> Run on Python3.10

- dvc/command/diff.py
- dvc/command/experiments.py
- dvc/command/metrics.py
- dvc/command/params.py
- dvc/command/status.py
- dvc/ui/__init__.py
- tests/unit/ui/test_console.py
1. update diff.py,experiments.py,metrics.py,params.py,status.py to
print prettify json
2. rewrite write_json in __init__.py to accept default function
3. Fix #6712
> command: output prettify json in tty

- dvc/repo/experiments/init.py
[![asciicast](https://asciinema.org/a/MTQXA9d3lm7Lsbi7DUMhG85NF.svg)](https://asciinema.org/a/MTQXA9d3lm7Lsbi7DUMhG85NF)
> exp init: make confirmation prompt at the end similar to others

- dvc/repo/plots/template.py
- tests/unit/render/test_vega.py
> plots: fix resolve template path bug

- dvc/repo/experiments/init.py
> exp init: fix --explicit failing with KeyError

- dvc/repo/experiments/init.py
> exp init: don't try ignoring params file if they have been skipped

- dvc/repo/experiments/init.py
On top of 6909, see 77594d20 for the change/code review.
[![asciicast](https://asciinema.org/a/KTcttQbjZdBuv1LAxR1CzGi9Z.svg)](https://asciinema.org/a/KTcttQbjZdBuv1LAxR1CzGi9Z)
Part of https://github.com/iterative/dvc/issues/6446.
> exp init: warn for code/data if they don't exist

- dvc/objects/stage.py
> ostage: don't forget to convert https etags

- setup.cfg
- tests/func/test_live.py
> live: Add test for logging images with dvclive

- dvc/repo/experiments/init.py
> exp init: interactive mode refactor and simplification

- dvc/fs/base.py
- dvc/fs/dvc.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/git.py
- dvc/fs/local.py
- dvc/fs/repo.py
- dvc/fs/utils.py
- dvc/ignore.py
- dvc/objects/db/base.py
- dvc/objects/db/reference.py
- dvc/objects/file.py
- dvc/objects/reference.py
- dvc/objects/stage.py
- dvc/repo/__init__.py
- dvc/repo/index.py
- dvc/utils/serialize/_common.py
- dvc/utils/strictyaml.py
- tests/unit/fs/test_base.py
- tests/unit/remote/test_base.py
Following fsspec conventions and new object conventions.
> fs: BaseFileSystem -> FileSystem

- dvc/repo/experiments/init.py
- tests/func/experiments/test_init.py
- tests/func/test_analytics.py
- tests/unit/command/test_experiments.py
- tests/utils/__init__.py
> tests: cover exp init

- dvc/ui/prompt.py
- tests/unit/ui/test_prompt.py
> exp init: show 'n to omit' on --explicit mode

- dvc/repo/plots/__init__.py
> plots: collect: provide callable for data resolution

- dvc/repo/metrics/show.py
- dvc/repo/params/show.py
instead of catching a broad exceptions, NoSCMError should work here.
> metrics/params diff: catch NoSCMError instead of a broad exception

- dvc/repo/live.py
- tests/conftest.py
Prevent tests from opening browser windows.
Closes #7014
> tests: patch webbrowser.open

- dvc/repo/experiments/show.py
- dvc/scm/__init__.py
- dvc/scm/git/__init__.py
- tests/func/experiments/test_experiments.py
> scm: remove exp related behaviours from scm.resolve_rev

- .github/workflows/tests.yaml
> gha: remove remote leftovers

- tests/unit/proc/test_manager.py
We didn't mock `os.kill` in `test_dead_process` and the pid it
kills might coincidentlly be the same with some real process.
1. Add a mocker to mock out `os.kill` in `test_dead_process`.
2. Use reset_mock to replace setting it again.
> ci: fix ci failure

- dvc/render/image.py
Going from:
To:
(Duplicated few images in new view to show scroll)
> render: image: make html less ugly

- dvc/proc/manager.py
- tests/unit/proc/test_manager.py
fix: #7063
Add `cleanup` and `removal` function to ProcessManager
> proc: implement cleanup/removal  (#7063)

- dvc/command/experiments.py
- dvc/repo/experiments/init.py
- tests/func/experiments/test_init.py
- tests/unit/command/test_experiments.py
Related to https://github.com/iterative/dvc/issues/6446#issuecomment-983925336.
> exp init: change type to --type=live to --type=dl

- dvc/command/experiments.py
- dvc/repo/experiments/init.py
- tests/func/experiments/test_init.py
- tests/unit/command/test_experiments.py
> exp init: rename stage name

- dvc/command/experiments.py
- dvc/repo/experiments/init.py
- tests/unit/command/test_experiments.py
> exp init: minor refactoring

- dvc/command/experiments.py
- dvc/repo/experiments/init.py
- tests/unit/command/test_experiments.py
Requires https://github.com/iterative/dvc.org/pull/3067.
> exp init: use shortlinks for doclinks

- dvc/command/experiments.py
> exp init: unhide from `dvc exp --help`

- dvc/fs/path.py
This is less error-prone than implementing these methods ourselves.
I think we can still do better generalizing this for fsspec, but this should work reliably in the meantime.
A downside here is that we don't get speedups from doing pure string manipulation instead of `os.path.join`.
Followup for #6976
> fs: path: use ntpath/posixpath

- setup.cfg
Related: #7053
Fixes dependency inconsistencies which are failing the build: https://github.com/iterative/dvc/commit/ea49fb95f7a493dc888751b8343777df51951871/checks
> setup: bump gcsfs

- .git_archival.txt
- .gitattributes
- setup.cfg
> install: fix archives

- tests/basic_env.py
- tests/func/test_fs.py
Also refactored unittest-based tests for LocalFileSystem to pytest.
> tests: get rid of GitFS related tests

- dvc/command/live.py
- dvc/command/plots.py
- dvc/render/base.py
- dvc/render/image.py
- dvc/render/utils.py
- dvc/render/vega.py
- dvc/repo/live.py
- tests/unit/command/test_compat_flag.py
- tests/unit/command/test_plots.py
- tests/unit/render/test_image.py
- tests/unit/render/test_render.py
- tests/unit/render/test_vega.py
> plots: introduce --json option

- dvc/fs/path.py
- dvc/repo/diff.py
- tests/func/test_diff.py
Regression from path_info removal.
Also partially fixes #7147
> diff: use relpaths

- dvc/command/experiments/show.py
- dvc/ui/table.py
- tests/func/experiments/test_show.py
Closes #7128 
Kind of tricky to get a visually pleasant style (related https://github.com/willmcgugan/rich/discussions/363)
Here is the current state:
> exp show: Alternate row background color

- setup.cfg
Trying to fix https://github.com/iterative/dvc/issues/6886.
> ssh: specify bcrypt explicitly

- setup.cfg
See https://github.com/python-poetry/poetry/issues/4683.
> deps: explicitly specify pyarrow for hdfs

- dvc/command/experiments/show.py
Closes https://github.com/iterative/dvc/issues/7194
Background discussion https://github.com/iterative/dvc/pull/7202
> exp show: Remove alternating background

- dvc/data/gc.py
- dvc/objects/db.py
- dvc/repo/gc.py
Part of data and objects separation.
> odb: move gc into a separate function

- tests/func/experiments/test_init.py
> tests: increase timeout for exp init tests

- dvc/commands/experiments/init.py
> Matches https://github.com/iterative/dvc.org/pull/3071
See https://github.com/iterative/dvc.org/pull/3071#discussion_r783512996
> update exp init help text

- README.rst
* [ x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.
* [ x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.
> Fix 3 README links so that they render in GitHub

- dvc/scm.py
> Doc URL correction for GitAuthError

- dvc/commands/experiments/show.py
- tests/func/experiments/test_show.py
> `exp show`: Sort `deps` columns.

- dvc/fs/repo.py
Using outs directly breaks isolation and makes it really hard to understand
what's going on.
Redundant abspaths will go away in followups when moving to relpaths.
> repofs: don't use outs

- dvc/ignore.py
- dvc/repo/destroy.py
- tests/func/test_repo.py
> remove .dvcignore on destroy

- dvc/commands/add.py
- dvc/commands/data_sync.py
- dvc/commands/gc.py
- dvc/commands/get.py
- dvc/commands/get_url.py
- dvc/commands/imp.py
- dvc/commands/imp_url.py
- dvc/commands/update.py
`dvc.org` P.R. https://github.com/iterative/dvc.org/pull/3255
> Remove outdated SSH default jobs.

- dvc/stage/__init__.py
- tests/func/test_add.py
> Fix dvc add -o issue #7357

- dvc/repo/install.py
> fix: hooks install alongside pre-commit tool

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/local.py
- dvc/repo/experiments/queue/tasks.py
- dvc/repo/experiments/show.py
- setup.cfg
Related to https://github.com/iterative/dvc/issues/7418
Requires https://github.com/iterative/dvc-task/pull/9
> exp: support status querying in celery queue

- dvc/external_repo.py
- dvc/repo/experiments/apply.py
- dvc/repo/metrics/show.py
- setup.cfg
- tests/func/test_api.py
- tests/func/test_external_repo.py
- tests/func/test_get.py
- tests/func/test_import.py
> scmrepo: update to 0.0.13

- dvc/commands/experiments/run.py
- dvc/repo/experiments/base.py
- dvc/repo/reproduce.py
> exp: remove mentions of resume

- dvc/commands/experiments/push.py
related to the first question in #7448.
> UI problem in `dvc exp push`

- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/local.py
- dvc/repo/experiments/remove.py
- setup.cfg
> exp: support remove from celery queue

- dvc/fs/webdav.py
> odb: set fs_path to be "" (root) for webdav 

- setup.cfg
> scmrepo: update to 0.0.16

- dvc/repo/experiments/__init__.py
- setup.cfg
- Temporarily pins kombu and dvc-task to source versions (pending upstream kombu release)
> exp: autostart queue worker

- .pre-commit-config.yaml
Extracted from https://github.com/iterative/dvc/pull/7524#pullrequestreview-927015603
> pre-commit: fix black/ click incompatibility issue

- setup.cfg
Hopefully will reduce some dependabot traffic.
> setup.cfg: tests: remove unnecessary dependencies

- .github/workflows/tests.yaml
- pyproject.toml
- setup.cfg
- tests/func/test_live.py
> setup.cfg: tests: try to remove more dependencies

- dvc/commands/remote.py
> lint: fix variable reassignment bug while iterating from flake8

- dvc/fs/__init__.py
- dvc/fs/webdav.py
Remove _strip_protocol, moves to get_cloud_fs loading stage.
> webdav: consider path to be root

- dvc/commands/experiments/show.py
- tests/func/experiments/test_show.py
> `exp show`: `pcp`: Allow to --drop Experiment

- dvc/repo/experiments/show.py
> exp show: prefer exp names for experiments

- dvc/fs/fsspec_wrapper.py
- dvc/fs/http.py
> fs: move NoDirectoriesMixin to http filesystem

- tests/func/test_api.py
- tests/func/test_used_objs.py
> gitfs: add regression test for broken stage.collect on gitfs when cwd != repo_root

- dvc/data/stage.py
- dvc/data/tree.py
- dvc/fs/base.py
- dvc/fs/utils.py
- dvc/utils/__init__.py
- tests/func/test_fs.py
> fs: rename getsize to size

- dvc/data/_progress.py
> build: try fixing exe package

- dvc/fs/base.py
Fixes the issue like https://github.com/iterative/dvc-http/runs/6168112233?check_suite_focus=true
> fs: do not pass size to underlying fs.put_file method

- dvc/scm.py
Before, as we were not passing `total`, the Tqdm progress bar would not
show the bar. As we get that value lazily, we should force it to always show the bar (done via setting `self.bar_format`).
Also updated the progress bar to say which repo is being cloned, and made the progress bar more responsive(?).
> scm: fix progress bar, show progress and repo being cloned

- .dvcignore
- .gitignore
- dvc/repo/index.py
- dvc/repo/stage.py
See https://github.com/iterative/dvc/pull/7393#discussion_r854114575.
> dvc.stage: log time duration on stage collection walk in verbose mode

- dvc/fs/http.py
- dvc/fs/ssh.py
> fs.put_file: fix function signature for size

- dvc/data/checkout.py
- dvc/data/stage.py
- dvc/fs/base.py
- dvc/fs/local.py
- dvc/fs/ssh.py
- dvc/fs/utils.py
- dvc/objects/db.py
- dvc/repo/experiments/executor/ssh.py
- dvc/stage/cache.py
- tests/func/objects/db/test_index.py
- tests/func/test_fs.py
- tests/func/test_remote.py
Temporarily reverts iterative/dvc#7649 because of #7666
> Revert "fs.utils: add atomic upload function"

- dvc/fs/_callback.py
- dvc/fs/base.py
- dvc/fs/utils.py
- dvc/output.py
- dvc/repo/get.py
- tests/func/test_external_repo.py
- tests/func/test_fs.py
- tests/func/test_repro.py
Note that this removes atomic file downloads for `get/get-url`.
> fs: remove download

- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/local.py
- dvc/repo/experiments/queue/tasks.py
- tests/unit/repo/experiments/conftest.py
- tests/unit/repo/experiments/queue/test_local.py
prerequisite for https://github.com/iterative/dvc/issues/7589
> exp: implement celery queue shutdown

- dvc/fs/_callback.py
- dvc/fs/base.py
Currently, the `recursive` kwarg is not supported, it defaults to `recursive=True` if passed a single path, and non-recursive on list of paths.
`put` needs to be implemented with similar workings for `transfer` to support transferring multiple files/objects at once. :)
> fs.get: use async implementation when supported by the filesystem

- dvc/repo/ls.py
- tests/func/test_ls.py
> dvc ls: not raise PathMissingError on empty dir.

- dvc/commands/dag.py
- tests/unit/command/test_dag.py
Closes https://github.com/iterative/dvc/issues/7676
> dag: fix dot file rendering order.

- README.rst
This is a first draft to update the intro of the readme (to be followed by other updates to the readme).
Goals of the proposed changes:
* Clarify what DVC is and why it's useful.
* Focus on user perspective and workflows over features.
This is a starting point for discussion, so please share your feedback 🙏 
Edit: @iterative/dvc PTAL and let me know if it aligns with what you think about DVC.
> README: update introductory value prop

- dvc/api.py
- dvc/data/reference.py
- dvc/dependency/repo.py
- dvc/fs/dvc.py
- dvc/repo/__init__.py
- dvc/repo/collect.py
- dvc/repo/diff.py
- dvc/repo/get.py
- dvc/repo/ls.py
- dvc/repo/metrics/show.py
- dvc/repo/plots/__init__.py
- dvc/repo/reproduce.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_experiments.py
- tests/func/test_api.py
- tests/func/test_external_repo.py
- tests/func/test_fs.py
- tests/func/test_get.py
- tests/func/test_import.py
- tests/func/test_update.py
- tests/unit/fs/test_data.py
- tests/unit/fs/test_dvc.py
- tests/unit/fs/test_dvc_info.py
- tests/unit/test_external_repo.py
Followup for #7732
Pre-requisite for #5162
> fs: rename RepoFileSystem to DvcFileSystem

- dvc/fs/__init__.py
- dvc/fs/git.py
- dvc/objects/fs/__init__.py
This is more of a DVC thing than objects.
> fs: move GitFileSystem out of dvc.objects.fs

- dvc/cli/__init__.py
- dvc/objects/fs/base.py
- dvc/objects/fs/generic.py
- dvc/output.py
- tests/unit/cli/test_main.py
- tests/unit/fs/test_base.py
- tests/unit/output/test_output.py
* Refactor check_requires, move UI messages to dvc.cli
* Refactor link related error
> fs: do not use DvcException in filesystems

- dvc/objects/fs/path.py
These days we have `self.flavour` that is more efficient and more simple.
> fs: path: don't overuse parts

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/run.py
- tests/func/experiments/conftest.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_show.py
> exp: use pytest-celery in exp func tests

- dvc/repo/experiments/queue/local.py
- setup.cfg
> dvc-task: bump to 0.0.9

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/local.py
- dvc/repo/experiments/queue/tasks.py
- dvc/repo/experiments/show.py
- setup.cfg
- tests/unit/repo/experiments/queue/test_local.py
> exp: unify exp tasks into single celery chain

- setup.cfg
See https://github.com/iterative/scmrepo/pull/87
Fixes #7824
> setup: bump scmrepo to 0.0.24

- dvc/repo/experiments/queue/local.py
- dvc/repo/experiments/queue/tasks.py
- setup.cfg
- tests/unit/repo/experiments/queue/test_local.py
> exp: use single atomic task for celery runs

- dvc/commands/checkout.py
* [ x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.
closes [3484](https://github.com/iterative/dvc/issues/3484)
> checkout: --relink show helpful message on completion

- setup.cfg
Fixes https://github.com/iterative/dvc/issues/7174
Fixes https://github.com/iterative/dvc/issues/7656
> sshfs: bump min ver to 2022.6.0

- .github/FUNDING.yml
- README.rst
See https://github.com/iterative/dvc/pull/7859#pullrequestreview-998911416. Donate badges/buttons seem unnecessary and might not be well received since DVC is developed and maintained by a for-profit org.
> readme: remove donate requests

- dvc/repo/experiments/queue/local.py
fix: #7884
The complete task restored back to the queue causing a task duplication.
Might related to a bug from the celery celery/celery#5663
Follow what in https://github.com/celery/celery/issues/5663#issuecomment-734871162
Disabled the restore_at_shutdown
> queue worker shutdown: disable restore

- setup.cfg
> dvc-task: bump to 0.1.0

- scripts/build-requirements.txt
Per https://github.com/iterative/dvc/issues/7949#issuecomment-1170927010
> build: Downgrade pyinstaller

- dvc/api/params.py
- tests/func/api/test_params.py
> api: params_show: Raise exception if no params found.

- dvc/cli/__init__.py
- dvc/dependency/repo.py
- dvc/output.py
- dvc/repo/diff.py
- setup.cfg
- tests/func/test_add.py
- tests/func/test_external_repo.py
- tests/func/test_ignore.py
- tests/func/test_remote.py
- tests/unit/cli/test_main.py
- tests/unit/data/db/test_local.py
- tests/unit/fs/test_data.py
- tests/unit/fs/test_dvc.py
> deps: bump dvc-data to 0.0.20

- README.rst
Re-do of https://github.com/iterative/dvc/pull/7917 @dberenbaum 
* ~~If this PR requires [documentation](https://dvc.org/doc) updates~~ This is documentation.
> readme: How it works (2)

- dvc/config_schema.py
- setup.cfg
Fixes https://github.com/iterative/dvc/issues/7832
> fs: gdrive: add gdrive_acknowledge_abuse

- dvc/commands/experiments/branch.py
per https://github.com/iterative/dvc.org/pull/3780#pullrequestreview-1043024878
* ~~📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.~~
> exp branch: update -h stdout

- dvc/commands/plots.py
- setup.cfg
- tests/integration/plots/test_plots.py
> project: update dvc render and dvclive test dependencies

- dvc/repo/plots/__init__.py
> plots: account for wdir in stage plots

- dvc/config_schema.py
- tests/func/test_config.py
> Add GDrive remote profile field to config

- README.rst
Added some exp commands to the quickstart
> readme: add exps to quickstart

- scripts/pyinstaller/hooks/hook-celery.py
- scripts/pyinstaller/hooks/hook-dvc_task.py
Fixes https://github.com/iterative/dvc/issues/8051
> build: add pyinstaller hooks for dvc-task and celery

- dvc/commands/plots.py
Related: https://github.com/iterative/dvc.org/pull/3691
> cmd: plots: update messaging

- dvc/output.py
* [ x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.
Fixes: https://github.com/iterative/dvc/issues/7988
> plots: remove legacy code from verify_metrics

- setup.cfg
> dvc-task: update to 0.1.2

- dvc/output.py
Leftover from https://github.com/iterative/dvc/pull/8091
> output: resolve relative to stage.wdir only on the same fs

- setup.cfg
Fixes https://github.com/iterative/dvc/issues/8100
> deps: bump dvc-data

- dvc/config_schema.py
https://github.com/iterative/dvc-objects/pull/119
> gs: add endpointurl

- dvc/commands/plots.py
> plots: show-vega: adjust renderers before show vega

- .github/workflows/packages.yaml
- scripts/build.py
This now uses the matrix to build executables from same jobs definition.
See https://github.com/iterative/dvc/actions/runs/2897468937.
> ci: refactor binary executable building workflow

- dvc/commands/data.py
- tests/unit/command/test_data_status.py
See https://github.com/iterative/dvc.org/pull/3812#discussion_r936625617.
> data status: fix not-in-cache hint

- setup.cfg
These are the same packages but with correct versions to sync up with existing packages that we generated in conda over the years.
> deps: bump dvc-* plugins to 2.19.0

- tests/func/experiments/test_queue.py
> tests: mark exp queue func tests xfail

- scripts/pyinstaller/build.py
- scripts/pyinstaller/hooks/hook-dvc.py
> pyinstaller: don't forget dvc_* plugins

- dvc/repo/plots/__init__.py
> plots: support dirs in top level definitions

- dvc/commands/data.py
- dvc/repo/data.py
- tests/func/test_data_status.py
- tests/unit/command/test_data_status.py
As discussed in https://github.com/iterative/dvc/pull/8170#discussion_r955074598.
> data status: remove --withdirs, show unknowns in CLI

- dvc/commands/data.py
- tests/unit/command/test_data_status.py
> data status: update hints to include fetch and checkout

- dvc/repo/fetch.py
- dvc/stage/__init__.py
- dvc/stage/imports.py
> fetch: do not checkout partial imports

- dvc/commands/data.py
- tests/unit/command/test_data_status.py
Just fixing one quote that was missing
> data status: fix quoting on command hints for untracked files

- dvc/info.py
- tests/func/test_version.py
Fix current CI failures on `Build packages`:
https://github.com/iterative/dvc/actions/runs/2954297410
> info: skip missing subprojects

- setup.cfg
> typo in setup config causing versioning errors in poetry

- dvc/dependency/param.py
- dvc/fs/git.py
- dvc/output.py
- dvc/stage/loader.py
- setup.cfg
- tests/func/test_import_url.py
- tests/unit/output/test_output.py
Note: windows tests were broken before, will handle them separately.
> deps: bump dvc-data to 0.6.3

- dvc/config_schema.py
- dvc/data_cloud.py
- dvc/repo/fetch.py
- dvc/repo/index.py
- dvc/repo/push.py
Experimental functionality for the POC cloud versioning. Hidden under an undocumented flag. Will be worked on top.
> dvc: cloud versioning POC

- dvc/fs/dvc.py
More optimisations for `dvc ls --recursive`. According to my informal local benchmark, it brings its run time from 38s to 20s.
> Optimise dvc ls -R

- dvc/fs/dvc.py
> dvcfs: remove config

- dvc/repo/experiments/run.py
- dvc/utils/hydra.py
- tests/func/experiments/test_set_params.py
- tests/func/utils/test_hydra.py
Requires `--queue` to be used alongside `--set-param`.
Doesn't strictly require `hydra.config.enabled`.
Add `get_hydra_sweeps` to `dvc/utils/hydra.py`.  Uses hydra `BasicSweeper` to generate the different sweeps.
`glob` syntax for sweeps is not supported in this P.R.
Closes https://github.com/iterative/dvc/issues/8083
---
Using setup from https://hydra.cc/docs/tutorials/basic/your_first_app/composition/ :
```console
$ dvc exp run -S "db=mysql,postgresql" -S "schema=warehouse,school" --queue
Queueing with '{'params.yaml': ['db=mysql', 'schema=warehouse']}'.
Queued experiment '5ab98b8' for future execution.
Queueing with '{'params.yaml': ['db=mysql', 'schema=school']}'.
Queued experiment '57c2fb6' for future execution.
Queueing with '{'params.yaml': ['db=postgresql', 'schema=warehouse']}'. …
```
> exp run: Support hydra basic sweeper.

- dvc/fs/dvc.py
fsspec filesystems default to binary mode.
> dvcfs: default open to binary mode

- dvc/schema.py
Trying to keep in sync with https://github.com/iterative/dvcyaml-schema/pull/19.
> schema: add strict schema validation for top-level plots

- .github/workflows/tests.yaml
Trying to see if we can improve CI runtime speed.
> try to split testsuites into two

- dvc/output.py
- dvc/repo/index.py
> index: use tree obj if using inline files

- dvc/stage/loader.py
Leftover from #8273
Fixes #8300
> loader: don't forget to set meta.isdir

- setup.cfg
> deps: bump dvc-azure to 2.20.4

- dvc/analytics.py
- setup.cfg
- tests/unit/test_analytics.py
Towards a company goal of having unified user_id.
> analytics: use iterative-telemetry for user_id lookup

- .github/mergify.yml
> remove mergify

- .github/workflows/benchmarks.yaml
- .github/workflows/tests.yaml
> use native concurrency

- setup.cfg
See https://github.com/PyCQA/pylint/issues/7488. Pylint is failing on our codebase.
> lint: pin astroid version

- setup.cfg
> deps: bump dvc-data to 0.10.1

- .pre-commit-config.yaml
- dvc/repo/plots/__init__.py
- tests/unit/command/test_run.py
updates:
- [github.com/codespell-project/codespell: v2.1.0 → v2.2.1](https://github.com/codespell-project/codespell/compare/v2.1.0...v2.2.1)
> deps: bump codespell

- dvc/commands/checkout.py
- dvc/commands/commit.py
- dvc/commands/dag.py
- dvc/commands/data_sync.py
- dvc/commands/repro.py
`repro` is verbose, so any suggestions on it would be great.
Docs PR: https://github.com/iterative/dvc.org/pull/3989
> cli: add help for foreach

- dvc/commands/data_sync.py
Fixes #8188
Docs PR: https://github.com/iterative/dvc.org/pull/3972
> pull: hide glob option

- dvc/fs/__init__.py
- dvc/info.py
- tests/unit/fs/test_fs.py
Add some tests for `get_fs_config()`/`get_cloud_fs()` and avoid passing around the `repo` argument unnecessarily.
> fs: test and slightly refactor get_fs_config()

- dvc/config.py
- tests/unit/test_config.py
> config: wrap UnicodeDecodeErrors on load

- dvc/commands/checkout.py
- dvc/commands/commit.py
- dvc/commands/dag.py
- dvc/commands/data_sync.py
- dvc/commands/repro.py
Follow up to https://github.com/iterative/dvc.org/pull/3989#discussion_r978501775.
> cli: remove foreach-group from help text

- dvc/repo/push.py
- setup.cfg
> deps: bump dvc-data to 0.14.0

- dvc/repo/index.py
- dvc/repo/stage.py
- tests/func/test_stage.py
> repo: fix crash while collecting stages with symlinks

- dvc/utils/hydra.py
- tests/func/utils/test_hydra.py
> hydra: Fix append and remove sweeps.

- dvc/logger.py
> logger: init logging config before colorama

- setup.cfg
> deps: bump dvc-data to 0.17.1

- dvc/ignore.py
- tests/func/test_ignore.py
Needed for use in `dvc-data`'s `DataIndex` but is also more generally correct, since `detail=True` could be passed to the `fs`.
> ignore: walk: support detail=True

- dvc/fs/callbacks.py
- dvc/output.py
- dvc/repo/checkout.py
- setup.cfg
- callbacks: update to dvc-data 0.18.0 behavior
> deps: bump dvc-data to 0.18.0

- dvc/config_schema.py
- setup.cfg
- tests/unit/fs/test_ssh.py
> config: ssh: Add `passphrase`, `ask_passphrase`

- dvc/testing/api_tests.py
Please see the discussion in https://github.com/iterative/dvc/pull/8314#discussion_r973182966.
> testing.api_tests: remove comment from fixture

- dvc/_debug.py
Adds a `--show-stack`/`--ss` flag that will print a traceback if/when dvc seems frozen. In macOS, it's Ctrl + T, In Linux, it's `Ctrl + \` repurposed to show traceback instead of `SIGQUIT`.  No support on Windows.
Inspired by `showstack` extension from https://www.mercurial-scm.org/repo/hg/file/default/contrib/showstack.py (GPL), and rewritten for our usecase/environment.
Will add to the wiki if this gets merged. :)
> debug: add --show-stack/--ss flag

- dvc/repo/experiments/queue/base.py
fix: #8417
1. Give the executor initialization and result collection more time for acquiring locks.
> Give lock acquiring more time in concurrency situation.

- dvc/repo/index.py
stage_infos might contain the same stage multiple times, but with different filter_info, so we shouldn't convert it to dict, as that makes us lose all but one filter_info.
> index: support multiple targets within output in IndexView

- .github/workflows/tests.yaml
> ci: cache lint deps, decrease test timeout

- setup.py
See https://github.com/orgs/community/discussions/6456
> set name so that dependency graph works

- tests/basic_env.py
- tests/func/test_gc.py
> tests: remove TestDir

- .dvcignore
- bin/dvc
- bin/dvc.bat
- tests/__main__.py
> chore: remove bin dir and simplify tests.__main__

- dvc/repo/experiments/run.py
> exp run: catch hydra import in 3.11

- README.rst
> readme: show downloads badge

- .github/workflows/benchmarks.yaml
> ci: bench: use 3.11 in benchmarks

- .github/workflows/tests.yaml
> ci: test with 3.11 on all OSes

- dvc/repo/experiments/run.py
- tests/func/experiments/test_set_params.py
Context https://iterativeai.slack.com/archives/CB41NAL8H/p1668370937889539
> hydra: Raise error when `name` and `sweeps`.

- pyproject.toml
- scripts/pyinstaller/hooks/hook-pydrive2.py
requires https://github.com/iterative/PyDrive2/pull/243 and dvc-gdrive update
will close https://github.com/iterative/dvc/issues/7949
> pyinstaller: use pydrive2 package hooks

- dvc/parsing/interpolate.py
- tests/func/parsing/test_interpolated_entry.py
Use subprocess.list2cmdline (windows) / shlex.quote
Closes https://github.com/iterative/dvc/issues/8203
Closes https://github.com/iterative/dvc/issues/8370
> parsing: Escape str interpolation in dict unpacking.

- pyproject.toml
will close https://github.com/iterative/dvc/issues/8593
> deps: bump dvc-data, dvc-azure

- dvc/ui/__init__.py
- tests/unit/command/test_plots.py
Not sure when this changed I am pretty sure the old check used to work
> ui: Fix WSL check in `open_browser`

- dvc/testing/api_tests.py
> testing: api: test opening a file in subdir

- pyproject.toml
> deps: bump dvc-data to 0.28.1

- dvc/repo/index.py
> index: skip data index load on empty view

- pyproject.toml
> deps: bump dvc-data to 0.28.2

- dvc/render/converter/vega.py
- tests/unit/render/test_vega_converter.py
Fixes https://github.com/iterative/dvc/issues/8636
> plots: fix multi-file plots

- pyproject.toml
> deps: bump dvc-data to 0.28.3

- dvc/repo/fetch.py
- dvc/repo/push.py
- dvc/repo/worktree.py
Will fix https://github.com/iterative/dvc/issues/8664
Will fix https://github.com/iterative/dvc/issues/8665
> cloud versioning: push/fetch behavior cleanup

- dvc/repo/index.py
- pyproject.toml
> deps: bump dvc-data to 0.28.4

- .github/workflows/tests.yaml
> GHA: remove unused env from tests workflow

- .github/workflows/tests.yaml
- tests/func/test_repro.py
> gha: remove env vars SHELL

- pyproject.toml
> deps: bump dvc-data to 0.28.6

- dvc/commands/imp_url.py
Per https://github.com/iterative/dvc.org/pull/3934
> `import-url`: Update options order

- dvc/_debug.py
- dvc/commands/get.py
- dvc/commands/get_url.py
- dvc/commands/queue/status.py
- dvc/repo/add.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/executor/local.py
- dvc/repo/experiments/executor/ssh.py
- dvc/repo/experiments/push.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/queue/tasks.py
- dvc/repo/experiments/queue/tempdir.py
- dvc/repo/experiments/queue/utils.py
- dvc/repo/experiments/queue/workspace.py
- dvc/repo/experiments/utils.py
- dvc/repo/imp_url.py
- dvc/repo/move.py
- dvc/repo/push.py
- dvc/repo/reproduce.py
- dvc/repo/update.py
- dvc/stage/__init__.py
- dvc/stage/loader.py
- dvc/stage/serialize.py
- dvc/stage/utils.py
- dvc/utils/__init__.py
- dvc/utils/pkg.py
- pyproject.toml
- tests/func/experiments/test_set_params.py
- tests/ruff.toml
> ruff: ban relative parent/grandparent imports

- dvc/repo/__init__.py
- dvc/repo/add.py
- dvc/repo/imp_url.py
- dvc/repo/stage.py
Using simple API as suggested by @efiop.
> repo.check_graph: rename method

- dvc/repo/experiments/executor/base.py
- tests/func/experiments/test_experiments.py
> exp run: Fix `--dry` option.

- pyproject.toml
Fixes https://github.com/iterative/dvc/issues/8837
Closes https://github.com/iterative/dvc/issues/8774
May fix https://github.com/iterative/dvc/issues/8836
> deps: bump dvc-data to 0.34.0

- dvc/_debug.py
From https://github.com/iterative/dvc/issues/8836#issuecomment-1398609193. You can use it like `dvc ... --viztracer-async`.
> add viztracer async option

- dvc/api/data.py
- pyproject.toml
- tests/func/test_ignore.py
- tests/func/test_state.py
> deps: bump dvc-data to 0.35.1

- dvc/repo/data.py
- dvc/repo/index.py
> data: status: use data index

- pyproject.toml
- tests/func/test_data_status.py
Per https://github.com/iterative/dvc/pull/8878#discussion_r1086346424
> deps: bump dvc-data to 0.36.0

- dvc/testing/fixtures.py
- dvc/testing/remote_tests.py
- adds the required dvc.testing fixtures and basic push/pull tests for version_aware and worktree remotes
Related: https://github.com/iterative/dvc/issues/8850
> testing: add initial basic cloud versioning tests

- dvc/data_cloud.py
- pyproject.toml
- bump dvc-data (fixes worktree push issue)
- fix remote config check (fixes worktree remote not properly setting `version_aware` on filesystems)
> worktree: bug fixes from testing

- dvc/output.py
- dvc/schema.py
- dvc/stage/loader.py
> serialize: fix loading of cloud metadata from .dvc/dvc.lock files

- tests/func/test_gc.py
Bug from https://github.com/iterative/dvc/pull/8880
> tests: gc: use timedelta

- pyproject.toml
Fixes bug where version-aware `import-url`/`update` did not work with `remote://`
> deps: bump dvc-gs to 2.21.1

- tests/func/test_gc.py
> tests: gc: use timedelta again

- dvc/repo/index.py
- tests/func/test_data_status.py
Fixes https://github.com/iterative/dvc/issues/8958
> index: build_data_index: handle empty dirs

- dvc/logger.py
Otherwise, tty detection does not work as `colorama.init()` mutates sys.stdout/sys.stderr, and after `dictConfig()`, the handlers will hold on to the stream.
Consider this as a hotfix for now. We need to think of better ways to avoid depending on `colorama` for stripping out ansi escape codes in the future.
This PR tries to detect if it's running inside jupyter or not, and then decides whether to defer calling `colorama.init()` or not.
Closes #8957.
> logging: defer calling colorama.init() in jupyter, otherwise initialize immediately (#8969)Closes https://github.com/iterative/dvc/issues/8957

- dvc/testing/remote_tests.py
> testing: mark 00 prefix tests xfail on fs without find()

- dvc/output.py
- dvc/repo/index.py
In preparation for migration to https://github.com/iterative/dvc-data/pull/304
Related https://github.com/iterative/dvc/pull/8987
> output: rename odb -> cache

- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/queue/remove.py
Required from new PRs which modify typing.
> Fix some mypy error.

- dvc/repo/data.py
- dvc/repo/imports.py
- dvc/repo/index.py
- dvc/repo/worktree.py
- pyproject.toml
Mostly migrating to things introduced in https://github.com/iterative/dvc-data/pull/313
> deps: bump dvc-data to 0.40.1

- dvc/config_schema.py
- tests/func/test_add.py
fixes #8773 issue
* [ x] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.
> Handle filenames which has ":" 

- dvc/repo/index.py
> index: build_data_index: use dvcignore

- dvc/repo/data.py
> data: status: misc fixes

- dvc/repo/data.py
> data: status: fix typo

- dvc/cachemgr.py
- dvc/config_schema.py
- dvc/repo/__init__.py
Reverts iterative/dvc#9044
Something went wrong during package build. Reverting until investigation is done. https://github.com/iterative/dvc/actions/runs/4206277700/jobs/7300749563
> Revert "repo: enable data index caching by default"

- pyproject.toml
I haven't added pyproject-fmt to pre-commit hook because of two reasons:
1. There is a bug that keeps adding empty lines after `[[tool.mypy.overrides]]`. See https://github.com/tox-dev/pyproject-fmt/issues/69.
2. The list gets exploded to multiple lines. However, this is a minor issue.
> pyproject: format using pyproject-fmt

- dvc/data_cloud.py
This hasn't been released, so we are not breaking anything.
> remote: rename index prefix from remotes to remote

- dvc/commands/data.py
- dvc/repo/data.py
- tests/func/test_data_status.py
- tests/unit/command/test_data_status.py
Slow POC implementation.
#8761
> data: status: introduce --not-in-remote

- dvc/commands/data.py
- dvc/repo/data.py
- pyproject.toml
- tests/func/test_data_status.py
- tests/unit/command/test_data_status.py
> data: status: introduce --remote-refresh

- dvc/repo/experiments/show.py
Related to https://github.com/iterative/dvc/issues/8787
In `exp show` we use `scm.iter_refs()` multiple times. This is a relatively expensive operation since it requires listing every ref in the git repo (which requires walking `.git/refs` as well as loading any packed refs in the repo). After this PR we cache the result of `iter_refs()` per call to `experiments.show()`.
> exp show: cache git refs per show() call

- dvc/repo/__init__.py
- tests/unit/remote/test_remote.py
> repo: use local root when determining state/index db dirname

- dvc/dependency/param.py
- dvc/fs/callbacks.py
- dvc/output.py
- dvc/repo/__init__.py
- dvc/repo/imports.py
- dvc/repo/index.py
- dvc/repo/worktree.py
- dvc/stage/serialize.py
- dvc/utils/serialize/_common.py
> remove typing.cast

- dvc/testing/fixtures.py
> Revert "testing: fixtures: fix docker regression"

- tests/func/experiments/test_apply.py
> tests: unmark exp celery tests as xfail

- dvc/info.py
- pyproject.toml
See https://github.com/iterative/dvclive/pull/481
> deps: Drop dvclive.

- dvc/repo/experiments/show.py
> exp show: fix cached running checkpoint state bug

- dvc/repo/experiments/executor/base.py
- pyproject.toml
- tests/integration/test_studio_live_experiments.py
Closes #9026 
Requires https://github.com/iterative/studio/pull/5127
> studio: Send `metrics` on `done` event.

- dvc/daemon.py
- dvc/stage/cache.py
- pyproject.toml
> tests: error on ResourceWarning

- tests/unit/test_ignore.py
Original from
https://github.com/iterative/dvc/pull/8767#discussion_r1070778749
* [] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.
> Add back an dvc ignore test

- dvc/output.py
- tests/unit/output/test_output.py
Fixes https://github.com/iterative/studio/issues/5261
> output: suppress cloud.pull errors on cache collection

- dvc/commands/experiments/clean.py
- dvc/commands/experiments/diff.py
- dvc/commands/experiments/gc.py
- dvc/commands/experiments/save.py
Minor cleanup after https://github.com/iterative/dvc.org/pull/4347#discussion_r1130522875
--------
> fix(exp): cleanup help messages

- dvc/repo/__init__.py
- dvc/repo/index.py
Makes for a much simpler resource management elsewhere.
> repo: data_index: fallback to in-memory

- tests/conftest.py
> tests: remove gc.collect() from windows

- dvc/repo/experiments/queue/base.py
- tests/func/experiments/test_experiments.py
> exp: Include `STUDIO_REPO_URL` in run_env.

- dvc/repo/install.py
> install: pre-commit: install all deps by default

- dvc/repo/__init__.py
> repo: create site_cache_dir with proper perms

- dvc/ui/__init__.py
See https://github.com/iterative/dvc/pull/9186#issuecomment-1473140793
> ui: flush stdout/stderr before colorama re-init

- .github/ISSUE_TEMPLATE/epic_story.md
> Add template for epic/story issues

- dvc/parsing/__init__.py
- tests/func/parsing/test_foreach.py
> parsing: fix foreach resolution with int keys

- dvc/utils/hydra.py
- tests/func/utils/test_hydra.py
> hydra: resolve OmegaConf interpolations.

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/queue/celery.py
- tests/func/experiments/test_apply.py
- tests/func/experiments/test_queue.py
- tests/func/experiments/test_show.py
> exp: enforce waiting for celery task completion in CI

- tests/func/experiments/test_apply.py
- tests/func/experiments/test_queue.py
- tests/unit/repo/experiments/queue/test_celery.py
see https://github.com/iterative/dvc/issues/9143#issuecomment-1480655704
> tests: remark flaky queue tests as xfail on windows

- dvc/fs/dvc.py
- dvc/repo/plots/__init__.py
- pyproject.toml
Related https://github.com/iterative/dvc/issues/8789
> dvcfs: handle broken symlink/TreeError

- tests/func/experiments/test_queue.py
> exp: mark q remove test as flaky

- dvc/dependency/repo.py
- dvc/repo/graph.py
- dvc/utils/strictyaml.py
- pyproject.toml
Related https://github.com/iterative/dvc/issues/8789
> deps: bump dvc-data to 0.46.0

- dvc/repo/experiments/push.py
- tests/unit/repo/experiments/test_push.py
Reverts iterative/dvc#9240.
Waiting for Studio to be deployed.
> Revert "exp push: add trailing slash to the endpoint url"

- dvc/utils/studio.py
- tests/unit/utils/test_studio.py
Pre-requisite for returning URL to the project.
> utils.studio: refactor to return json response

- dvc/commands/experiments/push.py
- dvc/repo/experiments/push.py
- tests/func/experiments/test_remote.py
Need to wait for Studio to be deployed.
> exp-push: show url to the Studio project

- dvc/commands/experiments/push.py
- dvc/repo/experiments/push.py
- tests/func/experiments/test_remote.py
Reverts iterative/dvc#9278
Accidentally merged
> Revert "exp-push: show url to the Studio project"

- dvc/repo/experiments/executor/local.py
- tests/func/experiments/test_experiments.py
> exp run: Propagate `.dvc/config.local` in `TempDirExecutor`.

- dvc/commands/plots.py
- tests/unit/command/test_plots.py
Note that we fallback if any `dvc.yaml` in the revision is broken to older commits.
DVC may find definitions for plots in other commits and might perfectly work.
Also, I want to emphasize that even if there are multiple dvc.yaml files and even if one is broken, it'll fallback. So at the moment, there will be only one error from each revision regarding broken dvc.yaml files. 
This behaviour is a part of a larger discussion, but at least it returns a correct reason why it fallbacks.
The error message will have `rev`/`type`/`msg`, only `name` will be missing since it's not a renderer-related error.
> plots json: return definition errors unrelated to renderers

- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/utils.py
- dvc/repo/reproduce.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_save.py
- tests/unit/repo/experiments/test_utils.py
> exp run/save: track top level files

- dvc/repo/experiments/executor/base.py
- tests/func/experiments/test_save.py
> exp save: include untracked dvclock

- dvc/repo/experiments/push.py
- dvc/utils/studio.py
> notify_refs; rename studio_url to base_url

- dvc/api/data.py
- dvc/external_repo.py
- tests/func/api/test_data.py
Fixes #9139
Fixes #7341 (see https://github.com/iterative/dvc/pull/7363#issuecomment-1032959843)
> api: data: set default remote instead of using it directly

- dvc/config_schema.py
- pyproject.toml
Closes https://github.com/iterative/dvc-ssh/issues/16
- Adds support for configuring `max_sessions` in SSH remotes
> deps: bump dvc-ssh to 2.22.1

- dvc/repo/imp_url.py
- tests/unit/command/test_imp_url.py
See https://github.com/iterative/dvc.org/pull/4468
> import-url: make version-aware and to-remote exclusive

- dvc/repo/experiments/executor/base.py
- dvc/repo/reproduce.py
> exp run: do not autostage on dvc repro

- dvc/repo/experiments/executor/base.py
- dvc/repo/reproduce.py
Callback was added for working around scm_context, since we don't use it, we don't need callback now.
> reproduce: remove callback

- tests/func/experiments/test_apply.py
- tests/func/experiments/test_queue.py
> exp: mock celery when needed in queue tests

- dvc/info.py
Minor cleanup of an old leftover.
> info: replace self -> repo

- dvc/info.py
Useful during debugging. Seems like people were asking about these obscure locations quite often in the recent past.
> doctor: add system/global config location

- dvc/api/experiments.py
Per https://github.com/iterative/dvc/pull/9356#discussion_r1180782320
> api: exp_show: Cleanup flags.

- dvc/repo/experiments/push.py
Closes https://github.com/iterative/dvc/issues/9342.
Check the following commits for easier reviewing:
- 5761f1b01633664c37169bd696973163691cd385: notifies studio even when cache push fails
- 9b97b2cf70cc6606d0b4f8cbf6121d6324930234: extract exp refs resolving logic, as the `push` function was getting complex
> exp push: notify studio even if cache push fails

- dvc/repo/add.py
- tests/func/test_add.py
This might change completely with #4657, but when testing out how it works now, I found it was giving misleading messages when trying to add the parent directory of a tracked output.
Also drops absolute paths. @skshetry Is there a reason to use absolute paths here?
Before this PR:
```
$ mkdir dir
$ echo foo > dir/foo
$ dvc add dir/foo
$ dvc add dir
ERROR: Cannot add '/Users/dave/repo/dir/foo', because it is overlapping with other DVC tracked output: '/Users/dave/repo/dir'.
To include '/Users/dave/repo/dir/foo' in '/Users/dave/repo/dir', run 'dvc commit dir.dvc'
```
After this PR:
```
$ mkdir dir
$ echo foo > dir/foo
$ dvc add dir/foo
$ dvc add dir
ERROR: Cannot add 'dir', because it is overlapping with other DVC tracked output: 'dir/foo'.
To include 'dir/foo' in 'dir', run 'dvc remove …
```
> add: msg for overlapping parent

- dvc/testing/benchmarks/fixtures.py
- dvc/testing/benchmarks/plugin.py
related: https://github.com/iterative/dvc/issues/9108
> testing.benchmarks: support installing remote deps in benchmark venv

- pyproject.toml
Temporary workaround for https://github.com/iterative/dvc/issues/9397
> deps: temporarily pin ruamel.yaml

- pyproject.toml
- tests/func/test_lockfile.py
> deps: unpin ruamel.yaml

- dvc/api/experiments.py
- tests/func/api/test_experiments.py
Makes it easier to manipulate when converting to pandas DataFrame.
> api: exp_show: Postprocess empty strings as None.

- dvc/repo/__init__.py
Use repo.index.stages instead.
> drop Repo.stages

- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/queue/base.py
restores some imports that got removed in the 3.0 checkpoints PR that were not preserved after rebasing #9496
> exp: fix rebased imports

- .github/mergify.yml
> remove original PR from backport PR title

- dvc/commands/add.py
- dvc/repo/add.py
- tests/unit/command/test_add.py
> add: rename jobs to remote-jobs

- pyproject.toml
Closes #9506 via https://github.com/iterative/dvc-azure/pull/48
> deps: bumps dvc-azure>=2.21.2

- dvc/stage/imports.py
- tests/func/test_update.py
Found during https://github.com/iterative/dvc/pull/9444
Fixes https://github.com/iterative/dvc/issues/8193
> update: make sure we update hashes/checksums on --to-remote

- dvc/repo/add.py
- tests/func/test_add.py
- tests/func/test_move.py
> add: remove `file`

- dvc/repo/checkout.py
- tests/func/test_checkout.py
> checkout: don't validate cache

- tests/func/test_checkout.py
> tests: checkout: fix test_checkout_relink_protected on windows

- dvc/repo/commit.py
> repo: commit: don't require target

- pyproject.toml
(Changing file to retrigger release).
> pyproject.toml: reformat project table

- dvc/_build.py
- dvc/build.py
The modification on this git-tracked file was making the repo dirty, making version to be `patch + 1`.
> remove dvc._build

- dvc/repo/diff.py
- tests/func/test_diff.py
> diff: handle revisions pointing to the same sha

- dvc/testing/benchmarks/cli/commands/test_exp_show.py
see https://github.com/iterative/dvc-bench/actions/runs/5273962844/jobs/9537970615
> benchmarks: update min dvc version for test_exp_show

- dvc/output.py
Fixes #9621
Closes https://github.com/iterative/dvc/pull/9622
> outputs: is_in_repo: don't try to realpath fs_path

- dvc/parsing/__init__.py
- dvc/schema.py
- tests/func/parsing/test_errors.py
- tests/func/parsing/test_foreach.py
- tests/func/parsing/test_interpolated_entry.py
- tests/func/parsing/test_resolver.py
Reverts iterative/dvc#9556.
Closes #9639.
Closes #9630.
Closes iterative/dvcyaml-schema#38.
> Revert "drop stage-level vars"

- dvc/schema.py
https://github.com/iterative/dvc/issues/9630#issuecomment-1602599796
> Bring back checkpoint to schema

- dvc/repo/checkout.py
Typo during recent changes 🤦 
Related https://github.com/iterative/dvc/issues/9658
> checkout: use single tics instead of curly braces

- dvc/repo/experiments/collect.py
- tests/unit/repo/experiments/test_collect.py
> Stable experiment range sorting

- dvc/repo/experiments/executor/ssh.py
- dvc/repo/experiments/pull.py
discord context: https://discord.com/channels/485586884165107732/485596304961962003/1122745985903362120
> exp pull: update for index fetch

- .dvc/.gitignore
This makes it easier to test/experiment while developing.
> make it a dvc repo

- dvc/output.py
Better error for #9621
Related to https://github.com/iterative/dvc.org/issues/4655
> output: save: error out on cached external outputs

- dvc/stage/cache.py
One of our users ran into this during `dvc exp run --pull`
> stage: cache: catch CollectCacheError

- dvc/repo/reproduce.py
This was confusing, with all the unnecessary states that we don't even need.
> repro: simplify _reproduce_stages

- dvc/commands/data_sync.py
- dvc/repo/fetch.py
- dvc/repo/index.py
- tests/unit/command/test_data_sync.py
Needed for iterative/studio#4782
> fetch: introduce --max-size

- dvc/repo/graph.py
- dvc/repo/reproduce.py
- tests/unit/repo/test_graph.py
Emphasizing on building the graph correctly, and preparing for being able to work with graph directly.
> repro: move code around

- dvc/output.py
Regression from https://github.com/iterative/dvc/pull/9673.
> output: checkout: use f-string

- dvc/output.py
Regression from https://github.com/iterative/dvc/pull/9715
> output: fix formatting

- dvc/repo/fetch.py
https://github.com/iterative/studio/pull/6541
Need to do the same in `push` and other operations later on. Will add a test along with those.
> fetch: catch collection errors in revisions

- dvc/stage/cache.py
> stage.cache: override both legacy+local cache link types on save/commit

- dvc/commands/get.py
- dvc/commands/imp.py
- dvc/commands/ls/__init__.py
Leftover from https://github.com/iterative/dvc/pull/9747
> cli: ls/import/get: fix help

- dvc/repo/experiments/collect.py
Fixes https://github.com/iterative/vscode-dvc/issues/4317
> exp.collect: strip metrics from queued experiments

- dvc/repo/fetch.py
For now not exposing it in CLI since there is no need/use yet.
Requirement for https://github.com/iterative/studio/pull/6541
> fetch: support passing config

- dvc/commands/commit.py
This PR fixes the description of `dvc commit` to be inline with the documentation https://dvc.org/doc/command-reference/commit#options
> `dvc commit` update description

- dvc/repo/__init__.py
- dvc/repo/cache.py
Basic helper to check the missing cache for a revision or workspace. For now internal API only, more stuff in a follow-up.
Related https://github.com/iterative/studio-support/issues/81
> repo: add basic cache_check_missing

- dvc/repo/cache.py
Related https://github.com/iterative/dvc/pull/9815
> repo: cache: support some view options

- dvc/repo/index.py
`_plot_sources` is messed up and needs a rewrite hard, but this will do for now for studio purposes.
Rewrite and tests later on in a followup.
> index: plot_keys: relparts -> parts

- dvc/config.py
- dvc/repo/fetch.py
Update will replace sections instead of merging them together, which
is not desirable here.
> fetch: merge config instead of updating

- dvc/dependency/repo.py
https://discord.com/channels/485586884165107732/485596304961962003/1141530399982485574
Kudos @sjawhar 🙏
> dep: repo: handle dict as config

- dvc/dependency/repo.py
- dvc/repo/imp.py
- tests/func/test_import.py
From https://github.com/iterative/dvc/pull/9853#issuecomment-1682797083
Again kudos @sjawhar 🙏
> import: set core.remote when both --remote and --remote-config are specified

- dvc/commands/experiments/save.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/executor/local.py
- tests/unit/command/test_experiments.py
- tests/unit/repo/test_scm_context.py
Closes #9239 
Not sure if we need additional tests for this
> exp: make run/save less noisy

- tests/unit/command/test_help.py
i.e. remove metafunc/pytest_generate_tests complexity
> tests: simplify test parametrization

- tests/unit/command/test_help.py
Otherwise this may end up generating 0 or not enough commands, and passing tests
> assert that the test is getting parametrized correctly

- dvc/commands/ls/__init__.py
- dvc/utils/humanize.py
- pyproject.toml
Per https://github.com/iterative/dvc/pull/9857#issuecomment-1683185006
> ls/ls-url: use tqmd instead of humanize.naturalsize

- dvc/rwlock.py
closes #9920
~* [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.~
> Typo dvc/rwlock.py#107 Remove -> Removed

- dvc/api/show.py
- dvc/commands/metrics.py
- dvc/commands/params.py
- dvc/dependency/__init__.py
- dvc/dependency/param.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/serialize.py
- dvc/repo/metrics/diff.py
- dvc/repo/metrics/show.py
- dvc/repo/params/diff.py
- dvc/repo/params/show.py
- dvc/stage/__init__.py
- dvc/utils/__init__.py
- tests/func/api/test_show.py
- tests/func/metrics/test_diff.py
- tests/func/metrics/test_show.py
- tests/func/params/test_diff.py
- tests/func/params/test_show.py
- tests/unit/command/test_metrics.py
- tests/unit/command/test_params.py
Closes https://github.com/iterative/dvc/issues/9452.
Closes https://github.com/iterative/dvc/issues/9478.
Also addresses https://github.com/iterative/studio/issues/4912.
TODO
> metrics/params: support reading from cached files and directories, use repo-relative path consistently

- dvc/fs/dvc.py
- tests/unit/fs/test_dvc.py
Followup for https://github.com/iterative/dvc/pull/9923
> dvcfs: add tests for fsid

- dvc/commands/experiments/run.py
- dvc/repo/experiments/run.py
- tests/func/experiments/test_experiments.py
> make exp run --dry imply --temp

- dvc/fs/dvc.py
Closes #9943
Should fix https://github.com/huggingface/datasets/issues/6203
> api.DVCFileSystem: fix fsspec compliance

- dvc/output.py
- dvc/repo/gc.py
> gc -c: always gc both 2.x and 3.x remote ODBs

- pyproject.toml
> Revert "build: temporarily pin setuptools-scm"

- dvc/repo/__init__.py
This will ensure that we won't be using index cache if you delete your repo and start/clone fresh.
On Linux python is lacking behind and doesn't expose an easy way to get stx_btime or statx results generally, so it will require some work to support it. See [1] and [2]
[1] https://github.com/torvalds/linux/blob/master/samples/vfs/test-statx.c
[2] https://github.com/ckarageorgkaneen/pystatx/blob/master/statx/__init__.py
> site_cache_dir: use .dvc/tmp/btime and fallback to st_birthtime

- dvc/commands/experiments/run.py
- dvc/commands/experiments/save.py
- tests/unit/command/test_experiments.py
Graceful obsoletion.
Followup for #10005
> exp: preserve hidden alias -M for --message

- dvc/repo/experiments/rename.py
- tests/func/experiments/test_rename.py
Fixes: https://github.com/iterative/dvc/pull/9812#discussion_r1342192386
> exp rename: verify exp name follows ref format

- dvc/repo/experiments/__init__.py
- dvc/repo/stage.py
- dvc/utils/__init__.py
- tests/func/repro/test_repro.py
- tests/func/repro/test_repro_pull.py
- tests/unit/repo/experiments/test_executor_status.py
- tests/unit/repo/test_repo.py
Hi, this is my first PR to the project. It fixes some minor typos.
> chore: fix typos

- dvc/repo/worktree.py
- dvc/testing/fixtures.py
- dvc/testing/remote_tests.py
- dvc/testing/scripts.py
- tests/dir_helpers.py
- tests/func/experiments/test_experiments.py
- tests/scripts.py
Otherwise, changes might not take effect.
Related https://github.com/iterative/dvc/pull/9807
> worktree: don't modify index entries in place

- tests/func/test_daemon.py
makes it thread-safe if we need in the future. Also looks a bit clean.
> refactor: use int as the factory

- dvc/commands/gc.py
See https://github.com/iterative/dvc/issues/9330#issuecomment-1787255984
> gc: don't prompt during dry run

- README.rst
> fix(readme): link to VS Code extension

- dvc/repo/artifacts.py
Fixes https://github.com/iterative/dvc/issues/10077
> artifacts get: fix issue where global/system config could be ignored

- .flake8
- .pre-commit-config.yaml
- dvc/commands/data.py
- dvc/repo/experiments/apply.py
- dvc/repo/experiments/executor/local.py
- dvc/testing/fixtures.py
- dvc/testing/scripts.py
- dvc/utils/table.py
- pyproject.toml
- tests/func/test_init.py
- tests/func/utils/test_strict_yaml.py
- tests/scripts.py
Replaces black with ruff-formatter, and isort with ruff.
> use ruff formatter

- dvc/commands/imp_db.py
- dvc/database/serializer.py
- dvc/dependency/db.py
- dvc/ui/_rich_progress.py
- fixes `test-db` command help message
- Add a progressbar to show no. of rows downloaded.
> database: fix ui issues

- .github/workflows/codeql.yml
> add security-extend to codeql queries

- dvc/testing/benchmarks/plugin.py
Useful for sanity checks in logs.
> testing: bench: add pytest_report_header

- dvc/testing/benchmarks/plugin.py
Need to move the data into dvc at some point.
> testing: bench: add openorca

- .github/workflows/tests.yaml
> run test on 3.12

- dvc/_debug.py
Even if a command failed, it might still be useful to look at the profiler report.
> cli: debug: finalize profiler reports on errors

- dvc/repo/push.py
Same as we do in pull/fetch/checkout.
> push: leave ui messages

- dvc/repo/push.py
We only need particular files within the output directory, not all files.
> push: only collect needed files when updating version_ids

- dvc/repo/push.py
From https://github.com/iterative/dvc/pull/10191
> push: use set_size instead of set_total

- dvc/repo/push.py
Leftover from https://github.com/iterative/dvc/pull/10190
> push: set desc explicitly

- dvc/repo/push.py
Per https://github.com/iterative/dvc/pull/10191#issuecomment-1870716262
Kudos @indigoviolet
> push: don't try to update meta for non versioned remotes

- dvc/repo/index.py
Fixes #10173
There will be tests for cloud versioning in a separate PR.
> index: load files from import

- dvc/repo/imp_url.py
- tests/func/test_import_url.py
> imp_url: gitignore during to_remote op

- dvc/commands/imp_db.py
Reverts iterative/dvc#10226
No longer needed since #10227.
> Revert "import-db: fix metavar"

- dvc/cli/parser.py
- dvc/cli/utils.py
- dvc/commands/artifacts.py
- dvc/commands/cache.py
- dvc/commands/daemon.py
- dvc/commands/data.py
- dvc/commands/experiments/__init__.py
- dvc/commands/git_hook.py
- dvc/commands/metrics.py
- dvc/commands/params.py
- dvc/commands/plots.py
- dvc/commands/queue/__init__.py
- dvc/commands/remote.py
- dvc/commands/stage.py
- dvc/commands/studio.py
It does not look like we need this.
> cli: remove fix_subparsers

- dvc/config_schema.py
Kudos @dberenbaum https://github.com/iterative/dvc/issues/10245#issuecomment-1898435806
Fixes #10245
> config: azure: don't forget Coerce() for timeouts

- pyproject.toml
> Revert "build(deps-dev): update pytest requirement from <8,>=7 to >=7,<9"

- dvc/commands/studio.py
Related: https://github.com/iterative/dvc-studio-client/pull/152
[![asciicast](https://asciinema.org/a/T1MUuHg2sOOrRXNOueNMy7J3U.svg)](https://asciinema.org/a/T1MUuHg2sOOrRXNOueNMy7J3U)
> simplify message in studio login/logout flow

- dvc/commands/dataset.py
- dvc/repo/__init__.py
- dvc/repo/datasets.py
- dvc/repo/index.py
- tests/func/test_dataset.py
- tests/unit/command/test_dataset.py
- tests/unit/test_dataset.py
Changes in the code are cosmetic changes, or done to make it easier to mock in the tests or make assertions easily.
> tests: add tests for datasets

- dvc/fs/dvc_path.py
- pyproject.toml
> experimental upath implementation for dvcfilesystem

- dvc/testing/fixtures.py
To unblock:
- https://github.com/iterative/dvc-webhdfs/pull/25
- https://github.com/iterative/dvc-ssh/pull/62
> support newer pytest-docker

- CITATION.cff
Similar to what is shown at the right-hand sidebar of [pandas](https://github.com/pandas-dev/pandas).
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files.
> add CITATION file so that users can cite dvc

- tests/func/test_data_cloud.py
Regression test for https://github.com/iterative/dvc/issues/10309
I accidentally merged the base PR #10368 before merging #10367, so I had to open another one.
> add a regression test for #10309

- dvc/commands/studio.py
- dvc/fs/__init__.py
- dvc/repo/artifacts.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/queue/base.py
- pyproject.toml
- tests/integration/test_studio_live_experiments.py
- tests/remotes/git_server.py
- tests/unit/command/test_studio.py
- tests/unit/fs/test_fs.py
- tests/unit/output/test_load.py
- tests/unit/remote/test_remote.py
- tests/unit/remote/test_webdav.py
- tests/unit/remote/test_webhdfs.py
dvc_studio_client, dvc_http, dvc_ssh, etc. were not properly sorted.
> sort imports for all libraries starting with dvc_ as a first party

- tests/integration/plots/test_plots.py
Fixes tests for https://github.com/iterative/dvc-render/pull/160
I don't see any issues in VS Code initially. @mattseddon Any idea whether this would cause problems there or in Studio?
> fix test for dvc-render updates to plots title anchor

- dvc/config_schema.py
[Pr for updating doc](https://github.com/iterative/dvc.org/pull/5226)
This PR will fixes #10394.
> add replication factor argument for hdfs in config schema

- dvc/dependency/repo.py
- tests/func/test_import.py
Fixes #10426
---
Hi, first time contributing here, so apologize i in advance for any silly mistake.
I believe the changes here are enough for the most basic cases, but a more complete solution is described in the bug report.
Since I'm pretty new to the code base, I thought it would be best to not try to update `dvc-data` in this change set.
Let me know if any additional changes are needed.
o/
> fix(pull): normalize dependency path

- dvc/testing/remote_tests.py
> skip stage cache push/pull test for http

- dvc/commands/data_sync.py
- dvc/commands/experiments/pull.py
- dvc/commands/experiments/push.py
Reverts #10433 and closes #10449
> revert to --no-run-cache default for push/pull/fetch

- dvc/dependency/db.py
- dvc/repo/experiments/serialize.py
- dvc/stage/run.py
I am not sure how to write a test for this.
Fixes #10496.
> import_db: set dependency.is_in_repo to false

- README.rst
> add datachain link

- dvc/testing/benchmarks/fixtures.py
- pyproject.toml
> use uv for benchmark tests while installing/creating virtualenv

- .github/workflows/tests.yaml
> ci: use pytest-split based on least_duration

- .pre-commit-config.yaml
- dvc/commands/dag.py
- dvc/info.py
- dvc/render/converter/vega.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/pull.py
- dvc/repo/experiments/push.py
- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/queue/utils.py
- dvc/repo/experiments/remove.py
- dvc/stage/utils.py
- dvc/testing/path_info.py
- dvc/testing/tmp_dir.py
- dvc/utils/__init__.py
- pyproject.toml
- tests/func/test_daemon.py
> update ruff to 0.6

- .github/workflows/benchmarks.yaml
- .github/workflows/build.yaml
- .github/workflows/plugin_tests.yaml
- .github/workflows/tests.yaml
> ci: use uv's official action, and uv build command

- .github/workflows/build.yaml
> chore: ci: disable caching

- tests/unit/command/test_dag.py
> fix tests with the new pydot release

- dvc/commands/gc.py
Closes  #10590
Corrected warning message
> Update warning message gc.py

- tests/func/test_merge_driver.py
- tests/unit/command/test_dataset.py
> fix implicit concatenated strings

- .github/workflows/benchmarks.yaml
- .github/workflows/build.yaml
- .github/workflows/plugin_tests.yaml
- .github/workflows/tests.yaml
- pyproject.toml
- tests/unit/test_logger.py
- tests/unit/ui/test_pager.py
> tests: try to make tests pass on Python 3.13 on unix platforms

- .github/workflows/tests.yaml
- dvc/config.py
- dvc/fs/dvc.py
- tests/unit/test_ignore.py
> 3.13 support for Windows

- README.rst
> remove banner in README

- README.rst
> Bring the banner back

- .pre-commit-config.yaml
> Revert "pre-commit: set autoupdate schedule to monthly"

- dvc/config_schema.py
- https://github.com/iterative/dvc-gs/pull/115
- https://github.com/iterative/dvc/issues/5797
> fs(gs): allow configuring anonymous login

- dvc/testing/benchmarks/cli/stories/use_cases/test_sharing.py
> tests(bench): remove allow_anonymous_login config use from dvc<3.59.3

- .github/workflows/build.yaml
> release(env): set dynamic url

- .github/workflows/build.yaml
> release(test-pypi): set dynamic url

- pyproject.toml
Fixes https://github.com/iterative/dvc/issues/10767. 
Related:
- https://github.com/iterative/dvc-s3/pull/129
- https://github.com/iterative/dvc/discussions/10768
> deps: bump dvc-s3 to >=3.2.1

- tests/dir_helpers.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_queue.py
- tests/func/experiments/test_remote.py
- tests/func/experiments/test_save.py
- tests/func/experiments/test_show.py
- tests/func/test_checkout.py
- tests/func/test_import.py
- tests/func/test_install.py
- tests/func/test_repo.py
- tests/func/test_scm.py
- tests/func/test_status.py
- tests/func/test_update.py
- tests/unit/repo/experiments/test_utils.py
- tests/unit/utils/test_studio.py
> stop using gitpython in tests

- dvc/repo/experiments/queue/celery.py
Fixes #10779.
Fixes #9616.
We'll now show a hint to check celery logs if there are no logs found for the given experiment, but has a failed status.
This may happen when the experiment fails during setup phase, due to some errors in dvc code or in celery.
```console
$ dvc queue logs hilly-coos
ERROR: No output logs found for experiment 'hilly-coos'
Experiment likely failed during setup. Check the celery logs for more details:
cat ./dvc/.dvc/tmp/exps/celery/dvc-exp-worker-1.out
```
> queue: show a hint to check celery logs if logs are missing and is a failed experiment

- tests/func/utils/test_strict_yaml.py
> try to fix test with new rich

- dvc/commands/data.py
- dvc/repo/data.py
- tests/func/test_data_status.py
- tests/unit/command/test_data_status.py
> data status: add --remote option to check files against a different remote
