build.cmd, innosetup/addSymLinkPermissions.ps1, innosetup/dvc.bat, innosetup/setup.iss
This will allow us to make our installer ~4 times smaller(120MB ->
30MB). This patch also has fix for PATH bug and installs dvc to whatever
direstory user specified.
=> build: use winpython and fix bugs

innosetup/addSymLinkPermissions.ps1
This will fix CreateSymLinkPermission modification in systems with
locale that is other than english.
=> build: use well-knows SID instead of "Everyone"

dvc/main.py
Currently dvc prints "Unimplemented or unrecognized command: --help"
and returns error code when calling dvc --help.
Fixes #71
Signed-off-by: Ruslan Kuprieiev <rkuprieiev@cloudlinux.com>
=> dvc: fix --help

dvc/command/base.py, dvc/logger.py, dvc/runtime.py, requirements.txt, setup.py
This pull request fixes usage output, replaces our print's with standard logging module, colorizes output and adds --verbose and --quiet options for cmdline.
=> Logging, color and usage

dvc/logger.py
It is fine to not call it in Linux and MacOs, but in windows it results in colors not working in vanilla cmd  prompt.
=> logger: don't forget to call colorama.init()

.gitignore, build_linux.sh, hooks/hook-google.cloud.py, hooks/hook-google.cloud.storage.py
This patch-set allows us to build deb and rpm packages for linux with standalone dvc binary in them.
It was made possible by using PyInstaller, troubleshooting it's errors for google modules and introducing custom hooks to resolve them. I also created a pull request for PyInstaller [1], so I hope that one day PyInstaller is going to be able to build dvc without additional hooks.
[1] https://github.com/pyinstaller/pyinstaller/pull/2637
=> Build rpm and deb packages using PyInstaller and FPM

build_linux.sh
Wrong INSTALL_DIR resulted in dvc being installed into /build/usr/bin.
=> build_linux: hotfix for build

dvc/command/import_file.py, dvc/progress.py
This one is a bit like the one you see in yum/dnf.
It has one single line updating current progress
for different targets and once they are finished
prints them as standalone line. So it looks smth
like this:
$ dvc import https://foo.bar/one.data \
https://foo.bar/two.data \
https://foo.bar/three.data
(1/3): [########################################] 100% one.data
(2/3): [#########################                              ] 60% three.data
=> progress: add progress bar to 'import'

dvc/data_cloud.py, dvc/utils.py
I.e. if network is gone for some reason, report that we're
able to sync some targets instead of just throwing exceptions
about broken pipe or something.
=> sync: handle exceptions

innosetup/setup.iss
=> innosetup: fix setup.iss semicolons

.travis.yml
Travis is able to automatically build and upload releases
to github, so when we will release next dvc version, travis
will automatically upload deb and rpm packages to github.
=> travis: publish dvc rpm and deb installers on releases

appveyor.yml
Same as with travis, appveyor will push dvc installer
for windows, when new dvc is being released on github.
=> appveyor: deploy dvc windows installer

dvc/cli.py, dvc/command/run.py, tests/test_cmd_run.py
Adding metavar='' is a legacy from previous design and should
be removed to achieve better help msgs.
'run' should have 'command' as a positional and _required_ argument and 'args'
as a remainder.
'repro' had CmdRun triggered when called from cli.
'sync' should have 'targets' as a positional and _required_ argument.
Fixes #136.
=> cli: fix help, 'run', 'repro' and 'sync'

.travis.yml, build_macos.sh
Travis doesn't natively support python builds on Mac yet,
so we need to workaround it by installing everything ourselves.
Luckily, there are third-party scripts that will make it much
easier for us.
Fixes #133.
=> travis: add workaround for mac build

dvc/cli.py, dvc/command/import_file.py
Download to .part file first and rename at the very end,
so if we lose connection we could resume download.
Note: not all servers support 'Range' header, so this
feature is not going to work everywhere.
This feature is activated by -c/--continue cmdline option.
Fixes #108
=> import: resume download

dvc/settings.py
testing for using == and != can be buggy when testing for None
specifically got exceptions with the args object, where the overloaded eq operator didn't handle None
=> replace eq\neq to is is not none

dvc/cli.py, dvc/command/config.py, dvc/command/init.py, dvc/config.py, dvc/git_wrapper.py, functest/test-init.sh, tests/basic_env.py, tests/test_cmd_gc.py, tests/test_cmd_run.py, tests/test_cmd_target.py, tests/test_data_file_obj.py
This is a more natural way to store dvc-related files and dirs
and follows git-logic much better.
Fixes #200
=> dvc: move config/cache/state/target to .dvc

dvc/command/common/base.py
For now we were able to work only in root dvc directory.
This patch emulates git behaviour by walking up the tree
to find repository root.
=> dvc: find dvc root

tests/test_data_cloud.py
I've setup a cleanup rule on s3 to remove old files, so
there is no need to clean them up manually.
Fixes #374
=> test: use unique aws s3 repo name

dvc/output.py
yaml is extremely slow without CLoader, which caused our checkout()
and similar functions to take way too long to process dir cache files.
These files are not really meant to be read by the users, so we can
sacrifice the readability of yaml for a better performance of json module.
E.g. checkout for 30K files used to take 30sec and after this patch only
takes 6sec, which is still quite slow, but much more bearable.
=> dvc: switch from yaml to json for dir cache file

dvc/output.py, dvc/system.py
=> dvc: calculate 'effective inode' from getfileinfo() on windows

dvc/output.py, dvc/project.py, tests/test_add.py, tests/test_checkout.py, tests/test_data_cloud.py, tests/test_fsck.py, tests/test_repro.py, tests/test_state.py
Since we can now detect cache corruption, we don't need
to force any permissions on our data files.
=> dvc: don't change mode of files

tests/__main__.py
Previous method of calling nose.main() didn't really work on windows.
=> test: call nosetests directly

dvc/project.py, tests/test_add.py
* test for adding single level directory with forward slash in the end
* normalizing the path that is passed to the add method
When executing 'dvc add directory/' (the slash in the end is the problem), dvc was adding the directory to the data repo but the dvc file that it was creating was named '.dvc' instead of 'directory.dvc'.
=> Proper adding of 'directory/'

dvc/stage.py, tests/test_repro.py
This allows as to define conditional stages in the dependency graph.
Fixes #646
Fixes #648
=> dvc: reproduce stage if it has no dependencies and has cmd

dvc/binary_file_extensions.py, dvc/remote/local.py, dvc/state.py, dvc/utils.py
There are 2 bottlenecks:
- LinkState.update repeatedly saves a large json blob, which generates O(n^2) disk I/O cost where n is number of files being added
- binaryornot.check.is_binary is slow for large number of small files. This change fixes it in case of binary files - checks extension first and if it is binary, don't call the is_binary function.
=> Fix bottlenecks related to large number of files.

dvc/cli.py, dvc/command/remote.py, tests/test_remote.py
=> dvc: add -d|--default option for `dvc remote add`

tests/test_repro.py
=> test: use GOOGLE_APPLICATION_CREDENTIALS when running GS repro test

dvc/config.py, dvc/remote/s3.py
Add config for `endpoint_url` on initializing `boto3` client. 
This allows us to use AWS-compatible cloud storage (e.g. OpenStack).
See also [boto3's reference](https://boto3.readthedocs.io/en/latest/reference/core/session.html#boto3.session.Session.resource).
=> RFP: Add endpoint url config for AWS

README.rst, dvc/data_cloud.py, dvc/remote/__init__.py, dvc/remote/azure.py, requirements.txt, setup.py, tests/test_data_cloud.py
This change adds a new cloud remote based on [Azure Blob Storage](https://azure.microsoft.com/en-us/services/storage/blobs/) and the [azure-storage-blob SDK](https://github.com/Azure/azure-storage-python).
The implementation closely follows the patterns laid out by the existing cloud remotes (AWS and GCP). Notable differences include:
- No use of a lock in the progress-bar callback and no requirement to look up total transfer size ahead of time: the Azure Storage SDK provides the total transfer bytes and current transfer offset in its progress callback.
- When `exists` is called, check the existence of every blob instead of listing the entire container. Container list operations can be expensive so unless the number of checked files is very large, making separate requests is likely going …
=> Add Azure Blob Storage remote

.appveyor.yml, dvc/remote/azure.py, scripts/ci/before_install.sh, scripts/ci/install_azurite.sh, tests/__main__.py, tests/test_data_cloud.py
This is a follow-up to https://github.com/iterative/dvc/pull/868.
The main change of this pull request is to set up the Azure Storage emulator [Azurite](https://github.com/Azure/Azurite) on the Travis CI machine via Docker and runs the Azure integration tests against the emulator (fcd0e34). An example of a successful build with this configuration on Travis can be found [here](https://travis-ci.org/CatalystCode/dvc/builds/402397620).
The pull request also contains a number of related functional fixes:
- Make the Azure remote compatible with Python 2 (8a32292).
- Switch the exists implementation of the Azure remote to the same list-then-check logic as S3 (a438f77).
- Make the Azure environment variables consistent between test and prod (581132b).
- Add the Azure remote to an additional test …
=> Add integration tests for Azure Remote

dvc/command/base.py
The original _find_root does not check whether the mount point itself has a .dvc folder. This causes a problem when I mount the dvc repository as a volume inside a docker container.
=> Fix _find_root in base.py

.travis.yml
flake8 testing of https://github.com/iterative/dvc on Python 3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./dvc/scm.py:86:16: F821 undefined name 'InvalidGitRepositoryError'
except InvalidGitRepositoryError:
^
./dvc/command/destroy.py:16:36: F821 undefined name 'err'
raise DvcException(err)
^
./dvc/remote/gs.py:63:19: F821 undefined name 'DvcException'
raise DvcException('{} doesn\'t exist in the cloud'.format(from_info['key']))
^
3     F821 undefined name 'err'
3
```
=> Travis CI: Flake8 spots some missing imports

dvc/progress.py, dvc/utils.py
=> dvc: print info when computing md5 of a large file

dvc/state.py
This is actually 10 times faster, because everything is stored in the
memory.
=> state: use json.dumps() instead of dump()

dvc/stage.py, tests/test_repro.py
=> repro: don't check for missing dependencies when running with `--dry`

requirements.txt, setup.py
The latest version is 2.2 (https://pypi.org/project/networkx).
Updating it to prevent collisions with some package managers already
using the latest one.
=> Update networkx package (== 2.1, >= 2.1)

scripts/completion/dvc.bash, scripts/completion/dvc.zsh
Copy the `dvc.zsh` file into a directory included `$fpath`, the file should be named `_dvc`.
```bash
docker run --rm -ti alpine
apk update && apk add  zsh
wget https://raw.githubusercontent.com/iterative/dvc/31b7a5766fcde68c32aae2b8f0e7d841ecb0dfd6/scripts/completion/dvc.zsh
mv dvc.zsh /usr/share/zsh/site-functions/_dvc
zsh
autoload -U compinit && compinit
```
_NOTE: it looks great if you add the following to your Zsh_
```zsh
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:corrections' format ' %F{green}-- %d (errors: %e) --%f'
zstyle ':completion:*:descriptions' format ' %F{yellow}-- %d --%f'
zstyle ':completion:*:messages' …
```
=> Add DVC shell completion for Bash and Zsh

README.rst
`dvc core.remote myremote` --> `dvc config core.remote myremote`
=> dvc: Fix typo in README.rst

dvc/logger.py
dvc/logger.py:113: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
=> logger: Remove deprecation warning reported by pytest

dvc/cli.py, dvc/command/gc.py, dvc/project.py, tests/test_cli.py, tests/test_gc.py
Adds an optional ``projects`` argument to the ``Project.gc()`` method. Expects a list of paths to other dvc-projects. If any paths are given, used cache is collected from all of them.
The ``gc`` cli has an optional ``-p`` argument, where multiple paths can be passed.
Fixes #1300
=> gc: support used cache collection for several repositories using the same remote storage

dvc/stage.py
=> stage: When loading an empty Dvcfile default to dict()

dvc/remote/local.py, tests/test_checkout.py
=> remote local: Check value before using it in `self.changed_cache`

dvc/command/run.py, tests/test_run.py
=> run: use quotes to wrap arguments with spaces in them

dvc/cli.py, dvc/command/run.py, dvc/project.py, dvc/stage.py, dvc/system.py, tests/test_run.py
Tests currently failing. I'm not familiar with the test tooling to diagnose the situation.
Related to https://github.com/iterative/dvc/issues/1234
=> Add dvc run --deterministic option.

dvc/daemon.py, dvc/utils.py, scripts/build_posix.sh, scripts/build_windows.cmd, scripts/innosetup/setup.iss
When running from the binary, we need to fixup environment variables
before launching new processes. We also need to detach from the parent's
tty, because otherwise, it causes problems for PyInstaller.
Plus, when binary is built as --onefile it still creates pop-up terminal
on windows, so we need to switch to --onedir. Also, as an added bonus,
binaries built with --onedir have a much better performance(e.g. startup
time), which is crucial for CLI user experience.
Fixes #1446
Fixes #1444
=> daemon: fix daemon when running in binary mode

dvc/stage.py, tests/unit/stage.py
A regression from #1508 , that wasn't caught because we didn't have a test for this earlier. Now we do :slightly_smiling_face: 
Currently, md5 for the stage file itself is incompatible with the one produced in earlier versions of dvc, causing unnecessary `dvc repro`s, since it marks stages as changed.
=> stage: don't exclude md5s for deps/outs

dvc/remote/http.py, tests/test_repro.py, tests/utils/httpd.py
=> remote http: use Content-MD5 header if there is not ETag available

dvc/exceptions.py, dvc/prompt.py, dvc/remote/base.py, tests/test_checkout.py, tests/unit/prompt.py
This bug was reported by @AlJohri  on (Al) discord. When using `dvc checkout` in a git post-checkout hook(installed with `dvc install`), dvc would throw an error when it coudn't receive a confirmation for modified directory removal:
```
$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
Data '{'scheme': 'local', 'path': '/Users/atul/Development/taxonomy-analysis2/experiments/ovr_svm_tfidf_ne_np/ml_model_parameter_search'}' didn't change.
...
....
Checking out '{'scheme': 'local', 'path': '/Users/atul/Development/taxonomy-analysis2/experiments/ovr_svm_tfidf_unigrams_bigrams/rule_model_parameter_search'}' with cache '4bb62290664603eb8095ccf29659bc04.dir'.
Linking directory 'experiments/ovr_svm_tfidf_unigrams_bigrams/rule_model_parameter_search'. …
```
=> checkout: handle EOFError when running in a git hook

dvc/command/imp.py, dvc/output/base.py, dvc/project.py, dvc/remote/azure.py, dvc/remote/base.py, dvc/remote/gs.py, dvc/remote/hdfs.py, dvc/remote/http.py, dvc/remote/local.py, dvc/remote/s3.py, dvc/remote/ssh.py, dvc/stage.py, tests/test_import.py, tests/utils/httpd.py
=> Resume import

dvc/data_cloud.py, tests/test_remote.py
=> data cloud: lowercase remote name to match config values

.appveyor.yml, dvc/config.py, dvc/remote/gs.py, tests/test_data_cloud.py, tests/unit/remote/gs.py
Adds feature requested in #1562 :
Add option to set `GOOGLE_APPLICATION_CREDENTIALS` environment variable in `.dvc/config`, so that it can be done in a more flexible way than using a manual `export`
Test and documentation are not updated yet
=> Add GCP credentials environment variable to config

dvc/project.py, tests/test_add.py
Cached stages are already saved, so there is no need to try to save them
once again.
Fixes #1581
=> add: don't try to save cached stages

dvc/cli.py, dvc/command/data_sync.py
I'm trying to overwrite the `--quiet` message on status to display something different than "Be quiet." but I couldn't manage to do it; adding an argument with the same name throws the following error: `argparse.ArgumentError: argument -q/--quiet: conflicting option strings: -q, --quiet`
```
status_parser.add_argument(
'-q',
'--quiet',
action='store_true',
default=False,
help=('Suppresses all output.'
'Exit with 0 if pipeline is up to date, otherwise 1.'))
```
I've also tried with the [conflict handler](https://docs.python.org/3/library/argparse.html#conflict-handler) option but it has some weird behavior, moving `---quiet` to a positional argument...
=> status: update --quiet help message

.pre-commit-config.yaml, dvc/command/run.py, dvc/exceptions.py, dvc/logger.py, dvc/project.py, dvc/prompt.py, dvc/stage.py, tests/__main__.py, tests/test_metrics.py, tests/test_run.py
* Fixes https://github.com/iterative/dvc/issues/1590
* Adds ability to run a specific test from a scope:
```
python -m tests tests/test_run.py:TestCmdRunCliMetrics
```
or 
```
python -m tests tests/test_run.py:TestCmdRunCliMetrics:test_not_cached
```
* Fixes some warnings from PyCharm's linter
* Fixes a few error messages and edge case tests
=> Cached metrics

dvc/updater.py, tests/unit/updater.py
Otherwise we get this on python2:
```
======================================================================
ERROR: test_fetch (tests.unit.updater.TestUpdater)
----------------------------------------------------------------------
File "/home/efiop/.pyenv/versions/2.7.15/envs/2.7.15-dvc/local/lib/
python2.7/site-packages/mock/mock.py", line 1305, in patched
return func(*args, **keywargs)
File "/home/efiop/git/dvc/tests/unit/updater.py", line 34, in test_fetch
self.dvc.updater.fetch(detach=False)
File "/home/efiop/git/dvc/dvc/updater.py", line 77, in fetch
self._with_lock(self._get_latest_version, "fetching")
File "/home/efiop/git/dvc/dvc/updater.py", line 39, in _with_lock
func()
File "/home/efiop/git/dvc/dvc/updater.py", line 91, in _get_latest_version …
```
=> updater: don't use io.open when working with json

dvc/repo/reproduce.py, tests/test_repro.py
@robogeek has discovered that `dvc repro --ignore-build-cache` actually
force-reproduced ascendants of a changed stage instead of only
reproducing descendants. That bug was caused by a typo in an if
condition plus improper test.
=> repro: fix --ignore-build-cache logic

dvc/command/remote.py, dvc/repo/checkout.py, dvc/repo/imp.py, dvc/repo/status.py
Currently `dvc` takes ~0.7sec to finish. After this patch: 0.17sec.
Profiling has been done using:
python -X importtime -m dvc 2> log.log
tuna log.log
Caugth by https://travis-ci.com/iterative/dvc-test .
=> dvc: optimize imports

dvc/cli.py, dvc/command/add.py, dvc/command/commit.py, dvc/command/repro.py, dvc/command/run.py, dvc/command/status.py, dvc/output/base.py, dvc/output/local.py, dvc/remote/base.py, dvc/remote/hdfs.py, dvc/remote/local.py, dvc/remote/s3.py, dvc/remote/ssh.py, dvc/repo/__init__.py, dvc/repo/add.py, dvc/repo/commit.py, dvc/repo/reproduce.py, dvc/repo/run.py, dvc/stage.py, tests/test_add.py, tests/test_commit.py, tests/test_repro.py, tests/test_run.py
=> Introduce `dvc commit`

dvc/command/metrics.py, dvc/logger.py, dvc/output/base.py, dvc/output/local.py, dvc/repo/__init__.py, dvc/repo/metrics/modify.py, dvc/repo/metrics/show.py, tests/test_metrics.py
* `dvc metrics *` CLI help cleanup.
* Remove deprecated `*-path` commands and related stuff.
* Apply lower() and check metrics type in metrics modify/add, metrics show.
* Change `error` -> `warning` in metrics show when it fails to read a file. 
* Make CSV and TSV path specification and implementation consistent with documentation and general conventions - first always come ROW index, then COLUMN (index, or name).
* Minor cleanup (unused imports, etc)
=> Cleanup metrics

tests/__main__.py, tests/test_data_cloud.py, tests/test_import.py, tests/test_logger.py, tests/test_metrics.py, tests/utils/httpd.py, tests/utils/logger.py
Fixes the outputs issue from #1598
Kudos to @mroutis for pointing to `--logging-clear-handlers` option.
=> Suppress outputs in tests

dvc/utils/compat.py
With this commit, `makedirs` will behave as expected:
```python
>>> makedirs('/system32/system32', exist_ok=True)
File "<stdin>", line 1, in <module>
File "dvc/utils/compat.py", line 49, in _makedirs
raise e
OSError: [Errno 13] Permission denied: '/system32'
```
Kudos to @shcheklein for pointing that out in a review: https://github.com/iterative/dvc/pull/1637#issuecomment-465249883 (great catch, btw.)
=> py2: raise OSErrors on makedirs

dvc/stage.py, tests/unit/stage.py
Sometimes it is handy to manually update the stage MD5 checksum after some non-breaking changes were made (e.g. renaming an output file). Logging the computed md5 hash in verbose mode can help experienced users to fix this problem.
=> Log computed stage MD5 in verbose mode

dvc/config.py, dvc/remote/s3.py
Optionally use list_objects, useful for ceph and other s3 emulators
fixes: #1476 
Note:  difficulties locating a useful test to extend for this use case?
=> remote: adds support for s3.list_objects

dvc/repo/__init__.py, dvc/repo/add.py, dvc/repo/imp.py, dvc/repo/move.py, dvc/repo/reproduce.py, dvc/repo/run.py, dvc/scm/__init__.py, dvc/scm/base.py, dvc/scm/git.py, dvc/stage.py, tests/test_add.py, tests/test_scm.py, tests/unit/scm/scm.py, tests/utils/__init__.py
=> add: cleanup .gitignore decorator

dvc/__init__.py
Ignore paramiko's warning: https://github.com/paramiko/paramiko/issues/1386.
This only affects paramiko 2.4.2 and should be fixed in the next version.
Cryptography developers decided that it is a brilliant idea not to inherit
from DeprecationWarning https://github.com/pyca/cryptography/blob/2.6.1/src/cryptography/utils.py#L14  because it is invisible by default, and decided
to spam everyone instead. So it is their fault and not paramiko's.
=> dvc: ignore cryptography's warnings

dvc/remote/ssh/connection.py
I found more mixups of Posixpath and os.path in the download and upload-functions. Should finally fix issue #1701.
=> Fixing mixup of Posixpath and os.path

dvc/repo/unprotect.py
It is better to make a file copy before moving it, since move is a nearly-atomic operation and copy is a long one.
Also the biggest problem here is that if some application would access the file during the process of `copyfile` then it would get the part of file.
=> unprotect: copy should preceed the move

dvc/remote/local.py, dvc/repo/unprotect.py, dvc/utils/__init__.py, tests/test_checkout.py
=> RFC: remote local, repo: use walk_files instead of os.walk

dvc/__init__.py, dvc/repo/__init__.py, dvc/repo/brancher.py, dvc/repo/init.py, dvc/repo/metrics/show.py, dvc/repo/tree.py, dvc/scm/__init__.py, dvc/scm/base.py, dvc/scm/git/__init__.py, dvc/scm/git/tree.py, dvc/stage.py, dvc/utils/__init__.py, tests/basic_env.py, tests/test_add.py, tests/test_install.py, tests/test_metrics.py, tests/test_repo.py, tests/test_scm.py, tests/test_tree.py, tests/unit/scm/test_scm.py, tests/utils/__init__.py
This pull-request implements the access to Stage objects via the Git interface to give the possibility to work with them directly without executing the `git checkout`.
Fixes #1688, fixes #1552 and fixes #1009.
Todo:
=> Brancher refactor

dvc/command/pipeline.py, requirements.txt, setup.py, tests/test_pipeline.py
Add option to unfold dependencies into a tree.
Fixes #1038
=> cli: add pipeline show --tree

dvc/stage.py, tests/test_run.py
Related #1786 
This change is supposed to make `run` command respect `persist` flag for outs.
=> run: make run respect persist flag

dvc/remote/ssh/connection.py
Currently SSH remote leaves the user with uninformative "No such file" error on e.g. `dvc push` when remote directory doesn't exist. This PR adds a description to such errors.
=> ssh: walk_files error description

dvc/remote/local.py, dvc/stage.py, tests/test_import.py, tests/test_run.py
Related to:
https://github.com/iterative/dvc/commit/bf68fbffec0954c9b39af993c43518970bad89ab#r32942088
minor fixes:
- progress bar for unprotect
- iterating over file lines in test
=> stage: remove outs upon import

dvc/command/metrics.py, dvc/repo/metrics/show.py, dvc/utils/compat.py, tests/test_metrics.py
Close #1716
----
How things should look like:
```
❯ dvc metrics show
metrics.tsv:
value_mse   deviation_mse   data_set
0.421601    0.173461        train
0.67528     0.289545        testing
0.671502    0.297848        validation
metrics.csv:
value_mse   deviation_mse   data_set
0.421601    0.173461        train
0.67528     0.289545        testing
0.671502    0.297848        validation
metrics.txt:
ROC_AUC:   0.64
KS:        78.9999999996
F_SCORE:   77
metrics.json:
{
"deviation_mse": [
"0.173461",
"0.289545",
"0.297848"
],
"data_set": [
"train",
"testing",
"validation"
],
"value_mse": [
"0.421601",
"0.67528",
"0.671502"
]
}
```
=> metrics: shows formatted multiline metrics

dvc/command/remote.py, dvc/exceptions.py, tests/test_remote.py
Now, `dvc remote add` requires user confirmation in case of overwriting of an already existing remote.
Fixes #1760 
Looks like:
```bash
$ dvc remote list
dvc	s3://dvc-share/dvc/
$ dvc remote add dvc s3://something/new
Error: unable to remove or overwrite 'remote "dvc"' without a confirmation from the user. Use '-f' to force. - unable to remove or overwrite 'remote "dvc"' without a confirmation from the user. Use '-f' to force.
Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
$ dvc remote add -f dvc s3://something/new
$ dvc remote list
dvc	s3://something/new
```
=> cli: fix overwriting remotes in `dvc remote add`

dvc/stage.py, tests/test_add.py
=> dvc: exclude `persist` when computing md5 for the stage

dvc/cli.py, dvc/command/diff.py, dvc/repo/__init__.py, dvc/repo/diff.py, dvc/scm/base.py, dvc/scm/git/__init__.py, dvc/utils/collections.py, requirements.txt, setup.py, tests/test_diff.py
Some summary statistics regarding the folder/file.
How many files were added/deleted/modified. How the size was changed.
TO DO things:
1)To  add support for detecting diff after `dvc move`
command.
2)To add unit tests.
=> dvc: add support for dvc diff command

dvc/output/base.py, dvc/output/local.py, dvc/stage.py, tests/unit/test_stage.py
When adding a remote file with
```
$ dvc add s3://bucket/path
```
it results in
```
Error: failed to add file - is local is not supported for s3
```
=> add: check if output is local when generating stage name

setup.py
`python_requires` helps pip install the right version of the library for the user's running Python.
Explicit version classifiers makes it on PyPI what versions are supported.
This is especially useful after dropping Python 2.7 (https://github.com/iterative/dvc/issues/1818) and also useful now.
---
Python 3.4 reached EOL on 2019-03-16, perhaps drop that now?
https://en.wikipedia.org/wiki/CPython#Version_history
Here's the pip installs for dvc from PyPI for March 2019:
| category | percent | downloads |
|----------|--------:|----------:|
|      3.6 |  42.39% |     3,621 |
|      3.5 |  20.21% |     1,726 |
|      2.7 |  17.51% |     1,496 |
|      3.7 |  11.33% |       968 |
| null     |   8.49% |       725 |
|      3.4 |   0.06% |         5 |
|      2.6 |   0.01% |         1 |
| Total    | …
=> Add python_requires and version classifiers

dvc/cache.py, dvc/command/remote.py, dvc/config.py, dvc/dependency/__init__.py, dvc/output/__init__.py, tests/test_cache.py, tests/test_remote.py, tests/test_stage.py
**Test scenario**:
```bash
sudo systemctl start sshd
dvc init --no-scm --force
dvc remote add ssh ssh://localhost
dvc remote modify ssh ask_password true
dvc remote add text-files remote://ssh/tmp/text-files
dvc remote add dvc-storage remote://ssh/tmp/dvc-storage
dvc config cache.ssh dvc-storage
mkdir -p /tmp/{text-files,dvc-storage}
echo "hello" > /tmp/text-files/hello
dvc import remote://text-files/hello
test -f hello
dvc run -o remote://text-files/derp 'echo "derp" > /tmp/text-files/derp'
test -f /tmp/text-files/derp
test -f /tmp/dvc-storage/b2/c3e317682929a3255a5e6433ccc5be
```
----
Close #1614
=> config: allow cross-referenced remotes

dvc/command/repro.py
This was the only instance I found that was not passing a message to the logger.
```bash
rg -t py "logger\.\w+\(\)"
```
Close #1858
=> logger: don not log without a message

dvc/remote/http.py, dvc/remote/local.py, dvc/remote/s3.py, dvc/remote/ssh/__init__.py
The problem was happening because `logger.error` doesn't include any
`exc_info`, and the `parse_exc` logic was previously to rely on the log
record's `exc_info` instead of the global stack trace.
There's still use cases when you want to just `log` an error without
printing the stack trace, those are left untouched.
You can search for them with: `grep -R 'logger.error' dvc/`
---
Fix #1869
=> logger: use exception instead of error

tests/unit/test_logger.py
We are facing a flaky test with our logs, I don't know why this is happening, but this PR would not rely an any global thingy, for example, each test case explicitly specify the log level that is required and it is not modifying the logger configuration.
I don't know if it will solve the problem at #1873 but at least I tried :man_shrugging:
=> tests: be paranoic with caplog

dvc/remote/local.py, tests/test_cache.py, tests/test_checkout.py, tests/test_repro.py, tests/test_run.py
=> cache: maker reflink, copy, default links

dvc/ignore.py, dvc/repo/__init__.py, dvc/repo/brancher.py, dvc/scm/git/tree.py, dvc/scm/tree.py, dvc/utils/__init__.py, dvc/utils/compat.py, dvc/utils/fs.py, requirements.txt, setup.py, tests/test_ignore.py, tests/test_repo.py, tests/unit/test_ignore.py, tests/unit/utils/test_fs.py
Fixes #1499 
Related to #1863 
Note: This implementation allows to ignore files via `.dvcignore` file placed in same directory as ignored file, or any parent directory. This behaviour is consistent with [`.gitignore` ignore rules](https://git-scm.com/docs/gitignore).
=> ignore: introduce .dvcignore

dvc/command/add.py, dvc/command/imp.py, dvc/command/run.py, dvc/repo/imp.py, tests/func/test_import.py
This PR add the '--file' option for `dvc import`
=> import: support the '--file' option

dvc/command/tag.py, dvc/exceptions.py, dvc/repo/metrics/show.py, dvc/stage.py, dvc/utils/__init__.py, dvc/utils/collections.py, dvc/utils/compat.py, dvc/utils/stage.py, requirements.txt, setup.py, tests/basic_env.py, tests/conftest.py, tests/func/test_add.py, tests/func/test_checkout.py, tests/func/test_commit.py, tests/func/test_data_cloud.py, tests/func/test_move.py, tests/func/test_repro.py, tests/func/test_run.py, tests/func/test_stage.py, tests/func/test_tag.py, tests/unit/utils/test_collections.py, tests/utils/__init__.py
This PR does several things:
- ensures comments and custom string layout in stage files are retained in the load/dump cycle.
- replaces `PyYAML` with `ruamel.yaml`
- fixes broken abstraction of saving/loading dvc files directly via yaml lib, mostly in tests. Now `load_stage_file()` and `dump_stage_file()` is used everywhere.
- adds pytest like fixtures to write functional tests with test dir 
- ensures utf-8 is always used in stage files regardless of OS default encoding
- ensures stage files are always properly closed 
**NOTE:** This does not include support for custom fields in stage files. That would go in separate PR.
=> dvc: retain formatting and comments in .dvc files

dvc/stage.py, tests/func/test_stage.py
Add `meta` key to stage files to store arbitrary user data.
This is second part of #1799.
This should be merged after #1885.
=> dvc: meta in stage

dvc/scm/git/tree.py, dvc/scm/tree.py, tests/func/test_metrics.py, tests/func/test_tree.py
=> tree: walk: operate on tree absolute root

dvc/utils/collections.py, tests/conftest.py
This fixes after-review of #1885.
=> Dvc formatting review

dvc/stage.py, tests/func/test_run.py
=> repro: persisting outputs invalidates build cache

dvc/command/repro.py, dvc/repo/__init__.py, dvc/repo/reproduce.py, scripts/completion/dvc.zsh, tests/func/test_repro.py, tests/requirements.txt, tests/unit/command/test_repro.py
https://github.com/iterative/dvc.org/issues/271
-----
Close #1555
=> repro: implement downstream option

dvc/system.py, dvc/utils/__init__.py, tests/basic_env.py, tests/conftest.py, tests/func/test_checkout.py, tests/func/test_import.py, tests/func/test_run.py, tests/func/test_system.py, tests/func/test_tree.py
Closes #1770. Partially does #1888.
=> test: clean up test dirs

dvc/repo/metrics/show.py, requirements.txt, setup.py, tests/func/test_metrics.py
=> dvc metrics show: implement jsonpath-ng

tests/conftest.py
Because yield_fixture() is deprecated since pytest 3.0 [1]. It is
not recommend to use the decorator instead of fixture().
[1] https://docs.pytest.org/en/latest/yieldfixture.html
=> Replace yield_fixture()

dvc/config.py, dvc/remote/local/__init__.py, dvc/remote/local/slow_link_detection.py, tests/unit/remote/test_slow_link_detection.py
-----
Fixes #1890 
Example:
https://asciinema.org/a/2XsHkAUcUfx1aHfmUV7atnpoJ
=> repo: different cache link types info on long lasting operations

dvc/repo/metrics/show.py, tests/func/test_metrics.py
=> metrics: show: do not throw on no metric present on branch

dvc/main.py, tests/__main__.py, tests/basic_env.py, tests/conftest.py
=> test: fix tests being dependent on log level and abandon default DEBUG level

dvc/progress.py, dvc/remote/base.py, tests/func/test_remote.py
Added an easier way to show progress bar over for loops as part of this. 
BTW, why don't you use [tqdm](https://github.com/tqdm/tqdm)?
=> dvc: add progress bar when hashing a large dir

dvc/config.py, dvc/repo/__init__.py, tests/func/test_init.py
=> repo: get default logger level from logger

dvc/repo/add.py, dvc/utils/compat.py, tests/func/test_add.py
=> add: warn when recursively adding large files

tests/__main__.py, tests/conftest.py
Previously that was only the case when running tests via `python
-mtests` wrapper.
Part of #1888.
=> test: never run updater nor analytics in tests

dvc/scm/git/__init__.py, tests/func/test_install.py
=> install: add pre-push hook, refactor test

dvc/remote/base.py, tests/func/test_remote.py
-----
After change https://github.com/iterative/dvc/pull/1892/commits/00cfb04fea046946c0604985b3336e35bf7afd56
we did not dump directory info as json sorted by keys (as we used to), which resulted with different checksums calculation. That could lead to situation where user:
- `git checkout && dvc pull` 
- `dvc status` returning "repo changed", if repo was created before mentioned commit. (E.g: our sample project: https://github.com/iterative/example-get-started)
=> remote: base: dump dir_info json with sorted keys

dvc/remote/ssh/__init__.py, tests/requirements.txt, tests/unit/remote/ssh/test_ssh.py
least opened an issue for it? If so, please add a link to it. Created PR [dvc.org#290](https://github.com/iterative/dvc.org/pull/290)
-----
Fixes #1613
Add parsing user ssh config for username and port. However settings from remote url has the priority over ssh config.
=> remote: add support for ssh config

dvc/remote/local/__init__.py
=> status: optimize the _fill_statuses method

requirements.txt, scripts/hooks/hook-Crypto.py, scripts/hooks/hook-aliyunsdkcore.py, scripts/hooks/hook-google.api.py, scripts/hooks/hook-google.cloud.py
This version added support for oss as a remote, which has caused some
issues when building the binary package. To fix those, we need two
pyinstaller hools:
1) hook-Crypto.py
This one has been added to PyInstaller's upstream, but wasn't
released yet, so we are using an upstream hook for now.
2) hook-aliyunsdkcore.py
This one is a new one. Sent it to PyInstaller's team in a PR [1].
[1] https://github.com/pyinstaller/pyinstaller/pull/4228
-----
=> pyinstaller: fix build for oss2

dvc/remote/base.py, tests/func/test_add.py
Fixes #1991
We do a similar thing on save, where we set cache checksum from already
computated ones for actual data. This patch does the same thing but in
revers: on checkout we know cache checksums, so we can set data       
checksums from it without having to re-calculate it.                  
-----
=> remote: checkout: save checksums without re-computation

dvc/remote/base.py, dvc/remote/local/__init__.py
Defining `_changed_cache_dir` for the sole purpose of executing
code before `_changed_dir_cache` was not that clear.
Now, it overwrites `_changed_dir_cache` but reference the
base method.
-----
=> refactor: rely on RemoteBasic._changed_dir_cache

dvc/path/local.py, tests/conftest.py, tests/func/test_add.py
=> cache: test: allow cache to be on different drive

tests/conftest.py, tests/func/test_add.py, tests/func/test_commit.py, tests/func/test_dependency.py, tests/func/test_install.py, tests/func/test_metrics.py, tests/func/test_output.py, tests/func/test_remote.py, tests/func/test_repro.py, tests/func/test_stage.py, tests/unit/command/test_repro.py, tests/unit/command/test_version.py
-----
Currently, dvc test fixture is named `dvc` just like our package, this might cause problems, for example when mocking.
=> [RFC] tests: rename dvc repo fixture

dvc/api.py, dvc/data_cloud.py, dvc/path/hdfs.py, dvc/repo/__init__.py, dvc/repo/gc.py, tests/basic_env.py, tests/func/test_api.py, tests/func/test_data_cloud.py, tests/remotes_env.sample
No streaming so far. Everything is added to `dvc.api`, I can move to somewhere else something if wring with that.
Also a part of this PR:
- simplified google creds handling.
- tests parametrized by remotes - if approach is accepted I will refactor the rest of the tests in `test_data_cloud.py`
- added `Repo.get_remote()` as a first step to dropping `DataCloud`.
- fixed `PathHDFS` stringification.
=> Add initial get_url()/open() api implementation

dvc/config.py, dvc/data_cloud.py, dvc/remote/local/slow_link_detection.py, dvc/repo/__init__.py, tests/func/test_data_cloud.py
This is a quick fix. DataCloud is definitely ugly and will be refactored within https://github.com/iterative/dvc/issues/2056 . 
Fixes #2066
-----
=> remote: support remote:// notation for push/pull/gc

dvc/command/remove.py, dvc/scm/git/__init__.py, scripts/completion/dvc.bash, scripts/completion/dvc.zsh
* N/A Does your PR affect documented changes or does it add new functionality
-----
As identified in https://github.com/iterative/dvc/pull/2003#issuecomment-496613212
=> update zsh autocomplete script with current command help messages +

dvc/command/add.py, dvc/command/checkout.py, dvc/command/commit.py, dvc/command/data_sync.py, dvc/command/destroy.py, dvc/command/imp.py, dvc/command/lock.py, dvc/command/move.py, dvc/command/pipeline.py, dvc/command/remove.py, dvc/command/repro.py, dvc/command/run.py, dvc/command/tag.py, dvc/repo/__init__.py, dvc/repo/checkout.py, dvc/repo/reproduce.py, dvc/repo/status.py, dvc/stage.py, scripts/completion/dvc.zsh
"DVC file(s)" an similar -> "DVC-file(s)"
E.g. in `dvc remove -h` and `dvc repro -h` output~~. Anywhere else?~~ and in many more places!
Companion to https://github.com/iterative/dvc.org/issues/321
---
-----
=> dvc: standard way to refer to DVC-files

dvc/config.py, dvc/remote/azure.py, dvc/remote/base.py, dvc/remote/gs.py, dvc/remote/hdfs.py, dvc/remote/http.py, dvc/remote/local/__init__.py, dvc/remote/oss.py, dvc/remote/s3.py, dvc/remote/ssh/__init__.py
Close #1762
----
`push`/`pull` depends on `status` (cloud) to figure out the difference
between the _local_ and _remote_ cache. It compares them by getting a list
of _outputs_ from the targeted stage files, and a list of files from both
caches.
```bash
dvc init --no-scm --force
rm -rf /tmp/dvc-storage && mkdir /tmp/dvc-storage
dvc remote add -d ssh ssh://localhost/tmp/dvc-storage
dvc remote modify ssh ask_password true
echo "hello" > hello
dvc add hello
echo "goodbye" > goodbye
dvc add goodbye
dvc push
#
```
The first approach works when: _local_ is **huge** but _remote_ is **small**.
The second approach works when: _local_ is **small** but _remote_ is **huge**.
This is because their opperations are proportional to the number of files.
Currently, we are using the former approach, and have …
=> remote: add other way to perform `cache_exists`

dvc/command/base.py, dvc/command/diff.py, dvc/repo/__init__.py, tests/func/test_diff.py, tests/func/test_updater.py, tests/unit/test_updater.py
Fixes #2039
Required by #2012 to be able to fetch data through the API without
interuption from updater.
-----
=> dvc: move Updater out of Repo()

dvc/command/pkg.py, dvc/pkg.py, tests/func/test_pkg.py, tests/unit/command/test_pkg.py
Fixes #1773
https://github.com/iterative/dvc.org/issues/385
-----
=> pkg: introduce `-f|--force` for `pkg install`

dvc/ignore.py, setup.py, tests/func/test_ignore.py, tests/unit/test_ignore.py
-----
related to #1876 
Edit:
When (if) this change is approved, we should create issue to optimize pathspec usage. Now, during dvc_walk we check files one by one, while pathspec allows to check set/list of paths against spec.
Edit 2:
But first it might be better to do some performance testing if its worth our time
=> ignore: remove dulwich in favour of pathspec

dvc/stage.py, tests/func/test_run.py
closes #1593
follow up on #2152
=> dvc: handle sigint when running a command with `dvc run`

dvc/logger.py, dvc/main.py, dvc/remote/ssh/__init__.py, dvc/remote/ssh/connection.py, dvc/utils/compat.py
-----
- SSH number of jobs increased from 4 to 8.
- `batch_exists` now opens all the SFTP sessions available to
distribute the work between them. Number of sessions is restricted
by the `MaxSessions` option configurable by the `sshd_config`.
- Fix #2104
With the optimizations mentioned above, we increased the speed by 8x
(using the default `MaxSessions` configuration -- 10).
Shout-outs to @efiop, @shcheklein, and @dmpetrov for suggesting the
optimization techniques.
=> ssh: increase jobs and parallelize batch_exists

dvc/external_repo.py, dvc/repo/destroy.py, dvc/repo/get.py, dvc/repo/init.py
Our `remove()` is able to handle read-only files which we or git
sometimes leave behind.
-----
=> dvc: use remove() instead of shutil.rmtree()

dvc/command/pipeline.py, dvc/logger.py, tests/func/test_add.py
Fixes #2170 
Introduces custom logger handler to propagate logging exceptions that are swallowed by default: 
https://docs.python.org/3/library/logging.html#logging.Handler.handleError
=> Fix 2170: pipeline show command does not work

dvc/__init__.py, setup.py
Fixes #2155
No longer need to explicitly ignore paramiko warnings.
Big thanks to @cowlinator for the heads-up!
-----
=> dvc: update paramiko requirements

dvc/utils/__init__.py, tests/unit/utils/test_fs.py
Closes #2188.
Also fixes a bug in `relpath()`, which is not in use yet)
=> Fix relpath() with PathInfo

dvc/remote/s3.py
Changes the priority of different ways users can provide AWS settings:
1. DVC config (with a usual priority local/repo/global) - this would be similar to someone using a direct `aws` command line option (like `--profile`). Internally it means we pass those to the Session object. It means, for example, that env vars are ignored, etc.
2. Other regular ways to provide in their regular order - env, files, etc.
* [X ] Have you followed the guidelines in our
-----
=> fix s3 credential handling: DVC config overrides environment

dvc/command/cache.py, dvc/command/config.py, dvc/command/data_sync.py, dvc/command/diff.py, dvc/command/gc.py, dvc/command/run.py, scripts/completion/dvc.bash, scripts/completion/dvc.zsh
-----
See also https://github.com/iterative/dvc/pull/2112#pullrequestreview-255013079
=> import: add import and get to autocomplete scripts; et al

dvc/path_info.py, dvc/remote/base.py, dvc/remote/ssh/connection.py
These were broken in two ways:
- remove_file may fail from time to time
- any in dir relative paths calculations were broken
=> Fix ssh dir outputs

dvc/remote/base.py
This fixes the issue. The question on  whether we should raise in `.load_dir_cache()` still stands, now it might be masking some errors, while maybe simultaneously letting users to go through with their work.
=> dvc: fix #2219

dvc/path_info.py
This will use cached `_path`, which will use cached `_cparts`. Saves
some time skipping repetitive parsing.
=> remote: optimize UrlInfo.isin()

dvc/api.py, dvc/cli.py, dvc/command/update.py, dvc/dependency/__init__.py, dvc/dependency/base.py, dvc/dependency/repo.py, dvc/external_repo.py, dvc/repo/__init__.py, dvc/repo/get.py, dvc/repo/imp.py, dvc/repo/imp_url.py, dvc/repo/update.py, dvc/scm/git/__init__.py, dvc/stage.py, scripts/completion/dvc.bash, scripts/completion/dvc.zsh, tests/func/test_update.py, tests/unit/command/test_update.py, tests/unit/test_stage.py
https://github.com/iterative/dvc.org/issues/474
-----
=> introduce `dvc update` for ext repos

dvc/stage.py
No point in calculating checksums when using force.
=> dvc: skip unused checks in repro -f

tests/func/test_import_url.py, tests/func/test_repro.py, tests/utils/httpd.py
This patch doesn't change the logic behind the tests, focusing on just using random port instead.
Fixes #1878
-----
=> test: http: use random port

dvc/remote/base.py
We were resolving futures after `ThreadPoolExecutor` exited and finished
everything.
=> remote: fix collect dir progress

dvc/stage.py
Signal mask is inherited by the child, so when we set it up before
Popen, our child ignores SIGINT, which is wrong. What we should've
done ideally, is to setup the signal handler after fork() but before
exec(). That is pretty much what preexec_fn is used for in Popen, but
unfortunately for us, it is not available on windows, so we can't use
it. What we will do instead is just setup signal handler after Popen()
but before communicate(), which would leave a slight gap where we might
also get affected by SIGINTS meant for the child, but that is the best
we can do.
Fixes https://github.com/iterative/dvc/issues/2272
that should be documented? If yes, have you created a PR …
=> stage: don't ignore SIGINT in the child

dvc/remote/ssh/connection.py
Work around `md5sum` not having `--tag` in Red Hat 6.3 and friends.
Fixes #2242.
=> remote: support older linuxes as ssh remotes

dvc/scm/git/tree.py, tests/func/test_tree.py
GitPython creates submodules nodes during tree iterate without explicit
passing name attribute. This path replaces such submodules with new
instances with filled name attribute.
Fixes: #1898
-----
=> Fix submodule names issue

.travis.yml
Windows and OSX builds don't use the pip cache because its location is
different from ~/.cache/pip.
-----
=> ci: unify pip cache location for all platforms

dvc/main.py, dvc/remote/ssh/pool.py, tests/conftest.py, tests/func/test_data_cloud.py, tests/unit/remote/ssh/test_pool.py
This helps with #2280 - stops hiding an error and removes confusing but harmless extra error messages in the end.
We might still want to wrap a "can't open any SFTP" error into some friendlier message, as it could be a relatively common user configuration issue, this is to be discussed. 
@efiop nice commits here, don't squash)
=> remote: pool fixes

scripts/ci/install.sh, setup.py, tests/func/test_s3.py
Fixes #1889
Test time decreased from 10s to 0.5s.
-----
=> tests: s3: use moto for multipart test

dvc/command/data_sync.py, dvc/command/repro.py, dvc/command/status.py, scripts/completion/dvc.zsh
Fix #2158
least opened an issue for it?
---
Doc update: https://github.com/jorgeorpinel/dvc.org/commit/76f08e8
=> help: finish pluralizing "the pipeline" term in output

dvc/main.py, dvc/path_info.py, dvc/remote/hdfs.py, dvc/remote/pool.py, dvc/remote/ssh/__init__.py, setup.py, tests/func/test_output.py, tests/unit/dependency/test_hdfs.py, tests/unit/output/test_hdfs.py, tests/unit/remote/ssh/test_pool.py
Related to #1629
Speeds up HDFS tests significantly. E.g.
TestReproExternalHDFS from 600sec to 190sec (we are still using hadoop cli there to get checksum).
test_open_external[HDFS] from 160sec to 3sec.
-----
=> remote: hdfs: use pyarrow and connection pool

dvc/command/pipeline.py, dvc/command/update.py, dvc/remote/local/__init__.py, scripts/completion/dvc.bash, scripts/completion/dvc.zsh, tests/func/test_remote.py
Continuation of https://github.com/iterative/dvc/pull/2281#issuecomment-513053199
-----
Doc update: https://github.com/iterative/dvc.org/pull/490/commits/3dc54890cee4b9fec6e97134a46a47693dba14c1
=> output: remove a couple more "(s)" left

dvc/dependency/base.py, dvc/repo/imp_url.py, dvc/stage.py, tests/func/test_repro.py, tests/func/test_update.py
Fixes #2238
https://github.com/iterative/dvc.org/issues/496
-----
=> import-url: lock by-default

dvc/scm/git/__init__.py, tests/func/test_install.py
In a branch where DVC hasn't been initialized (as detected by `git ls-files .dvc` not listing any files), don't invoke dvc in the git hooks. This avoids trouble when switching between branches with and without dvc initialized.
Fixes #2208
Doc issue link: https://github.com/iterative/dvc.org/issues/506
=> dvc: hooks only act in branches where dvc active

dvc/external_repo.py, dvc/remote/base.py, dvc/remote/local/__init__.py, dvc/repo/__init__.py, dvc/repo/get.py, dvc/state.py
=> get: use StateBase

dvc/cache.py, dvc/config.py, dvc/remote/base.py, dvc/remote/local/__init__.py, dvc/utils/__init__.py, tests/func/test_cache.py
https://github.com/iterative/dvc.org/issues/497
Fixes https://github.com/iterative/dvc/issues/2287
-----
=> dvc: support `group` cache mode 

dvc/remote/azure.py, dvc/remote/base.py, dvc/repo/__init__.py, dvc/utils/http.py, setup.py, tests/unit/utils/test_http.py, tests/utils/httpd.py
This employs generating temporary signed public url and then streaming
from it. The bulk of the code might be reused for other remotes.
Url streaming does resume on connection error using "Range" header and
regenerates public url too.
If remote class doesn't provide .open() then this falls back to pulling
a file and opening it locally.
=> api: make .open() stream data for Azure

dvc/remote/base.py, dvc/remote/local/__init__.py
Remotes like s3/gs/etc don't need to create dirs in advance.
-----
=> remote: base: call makedirs in move

dvc/remote/azure.py, dvc/remote/base.py, dvc/remote/gs.py, dvc/remote/http.py, dvc/remote/oss.py, dvc/remote/s3.py, dvc/remote/ssh/__init__.py, dvc/remote/ssh/connection.py
=> remote: gs/s3: remove batch_exists

dvc/remote/azure.py, dvc/remote/base.py, dvc/remote/gs.py, dvc/remote/oss.py, dvc/remote/s3.py
Employ the same sign url and use resumable download approach tested for
Azure.
=> api: stream data in api.open() for S3, GS and OSS

dvc/scm/git/__init__.py, tests/func/test_install.py
=> fix: don't dvc checkout on git file checkout

tests/func/test_run.py, tests/unit/test_stage.py
Current test is testing for signal handler restoration in an obscure
way. As a result, the test wasn't actually testing anything, because
KeyboardInterrupt is raised by default_int_handler, and so raising it
in a mock won't be caught by signal handlers, because they are dealing
with real singnals.
Fix #2406
-----
=> test: run: refactor signal handler tests

dvc/config.py, dvc/remote/ssh/__init__.py, setup.py, tests/unit/remote/ssh/test_ssh.py
This is my proposed implementation of #2327.
If the user has a valid kerberos ticket (generated with [`kinit`](https://web.mit.edu/kerberos/krb5-1.12/doc/user/user_commands/kinit.html)), this feature allows `dvc` to interact with the remote machine without asking the user to type in their password or hard code their password in `.dvc/conf`.
After reading a bit more about kerberos, passing the keytab file no longer made sense to me.  I did not include the `gss_kex` option for paramiko, as I imagine users will trust the server they specify and I did not deem it necessary.  However, I do not fully understand GSS-API key exchange and someone with more knowledge may know better.  
I included a simple unit test, however, it is not clear to me how to write a functional test for this feature.  If …
=> ssh: add gss_auth option

dvc/progress.py, dvc/remote/azure.py, dvc/remote/base.py, dvc/remote/http.py, dvc/remote/local/__init__.py, dvc/remote/oss.py, dvc/remote/s3.py, dvc/remote/ssh/__init__.py, dvc/remote/ssh/connection.py, dvc/repo/checkout.py, dvc/utils/__init__.py, setup.py
Post-merge of #2333, sort out a few issues (both new and pre-existing)
+ [x] fix bar width (https://github.com/tqdm/tqdm/issues/623)
+ [x] truncate ~~and/or justify file names (right align? max truncation len? prefix ellipsis? multi-line (https://github.com/tqdm/tqdm/issues/630)?)~~ description (from right) to fit into terminal width
+ [x] still auto-detect `ncols` (fill space with whitespace rather than variable bar width?)
+ [x] add `level=INFO` (when `disable=None`)
+ [x] ~~add `leave_level=DEBUG` (when `leave=None`)~~ add `leave=False`
+ [x] get rid of `progress.Tqdm.update_desc("", 0)`
+ [x] get rid of `progress.Tqdm.set_description_str()`
+ - [x] bar descriptions such as `Querying cache in .dvc/cache` and `Querying cache in s3://mybucket/mypath`
- fixes #2434 …
=> progressbar cleanup

dvc/exceptions.py, dvc/repo/get.py, tests/conftest.py, tests/func/test_get.py
=> repo: get: intercept and convert NotDvcRepoErro to UrlNotDvcRepoError

dvc/exceptions.py, dvc/repo/get.py
Improve error message.
Close https://github.com/iterative/dvc/issues/2430
=> get: no relpath on output not found

dvc/external_repo.py, dvc/repo/__init__.py, dvc/scm/__init__.py, dvc/scm/base.py, dvc/scm/git/__init__.py
=> erepo: fix environment before running git

dvc/command/run.py, dvc/stage.py, tests/unit/command/test_run.py, tests/unit/test_stage.py
This is an extension of our callback stages (no deps, so always
considered as changed) for stages with dependencies, so that these
stages could be used properly in the middle of the DAG. See attached
issue for more info.
Related to #2378
Doc PR is coming soon.
-----
=> run: introduce --always-changed

dvc/scm/base.py, dvc/scm/git/__init__.py, tests/func/test_scm.py
Leftover code was causing problems when working with symlinks, because
it tried to use `realpath` on symlinks to further use it to determine
parent directory.
Fixes #2476
-----
=> scm: remove `pkg install` leftovers

dvc/repo/move.py, tests/func/test_move.py
=> move: use relpath to find target path

dvc/analytics.py, dvc/lock.py, dvc/logger.py, dvc/repo/__init__.py, dvc/state.py, dvc/updater.py, dvc/utils/compat.py, setup.py, tests/func/test_lock.py
This locks employs hardlink trick, which works on NFS and alike unlike
fcntl/open locks.
Closes #1918.
=> dvc: switch to flufl lock

dvc/dependency/base.py, dvc/output/base.py, tests/func/test_run.py, tests/unit/test_stage.py
=> output: prevent stage file from being used as output

dvc/utils/compat.py, tests/utils/httpd.py
It is only used in tests. Shaves out 30ms startup time for me.
=> perf: do not import http.server each run

dvc/exceptions.py, dvc/scm/git/__init__.py, tests/func/test_install.py
=> install: verify no hooks colliding with dvc exist

dvc/command/base.py, dvc/command/destroy.py, dvc/command/install.py, dvc/main.py, dvc/repo/__init__.py, dvc/repo/add.py, dvc/repo/checkout.py, dvc/repo/commit.py, dvc/repo/diff.py, dvc/repo/fetch.py, dvc/repo/gc.py, dvc/repo/imp_url.py, dvc/repo/lock.py, dvc/repo/move.py, dvc/repo/pull.py, dvc/repo/push.py, dvc/repo/remove.py, dvc/repo/reproduce.py, dvc/repo/run.py, dvc/repo/status.py, dvc/repo/update.py
For the longest time we've had `repo.lock`, but were only using it from
CLI when running specific command, instead of simply properly taking it
on API operations. This patch takes care of that.
Related to #755 
-----
=> dvc: move repo lock from CLI to API

dvc/config.py, dvc/data_cloud.py, dvc/dependency/repo.py, dvc/exceptions.py, dvc/output/base.py, dvc/remote/local/__init__.py, dvc/repo/__init__.py, dvc/repo/fetch.py, tests/func/test_import.py
=> pull: download data from imported stages

dvc/daemon.py
This way dvc will actually launch the same script that it is running
from and not installed dvc module, that might not match.
-----
=> daemon: use `sys.argv[0]` instead of `-m dvc`

dvc/utils/__init__.py, tests/unit/utils/test_utils.py
Unlike PyInstaller, pyenv doesn't leave backups of original env vars
when it modifies them. If we look into the shim, pyenv and pyenv-exec,
we can figure out that the PATH is modified like this:
PATH=$PYENV_BIN_PATH:${bin_path}:${plugin_bin}:$PATH
where
PYENV_BIN_PATH - starts with $PYENV_ROOT, see pyenv-exec source code.
bin_path - might not start with $PYENV_ROOT as it runs realpath on
it, see pyenv source code.
plugin_bin - might contain more than 1 entry, which start with
$PYENV_ROOT, see pyenv source code.
So having this, we can make a rightful assumption about what parts of the PATH
we need to remove in order to get the original PATH.
Fixes #2506 …
=> dvc: remove PATH prefixes appended by pyenv

dvc/cache.py
The older code instantiates non-local cache remotes on Repo creation if
any of those are configured. And remote instantiation loads their API
libs.
=> perf: delay cache creation

dvc/command/pipeline.py, dvc/exceptions.py, dvc/repo/__init__.py, dvc/repo/add.py, dvc/repo/brancher.py, dvc/repo/checkout.py, dvc/repo/destroy.py, dvc/repo/diff.py, dvc/repo/graph.py, dvc/repo/imp_url.py, dvc/repo/metrics/modify.py, dvc/repo/metrics/show.py, dvc/repo/reproduce.py, dvc/repo/run.py, dvc/repo/tag/add.py, dvc/repo/tag/list.py, dvc/repo/tag/remove.py, tests/func/test_checkout.py, tests/func/test_diff.py, tests/func/test_pipeline.py, tests/func/test_repo.py, tests/func/test_repro.py
=> dvc: cache graph/stages/pipelines

dvc/remote/base.py
=> remove unneeded TqdmThreadPoolExecutor

dvc/scm/git/__init__.py, dvc/utils/__init__.py
=> utils: fix_env: dont delete LD_LIBRARY_PATH from env

dvc/stage.py
=> Fix typo in `check_can_commit` message

.pylintrc
Adjust the `max-line-length` option to the same value used by black and `.flake8` file.
-----
=> Use consistent max line length in lint config files

dvc/exceptions.py, dvc/repo/__init__.py, dvc/scm/git/tree.py, dvc/scm/tree.py, tests/func/test_api.py
=> api: open scm controlled files

dvc/repo/__init__.py, dvc/repo/add.py, dvc/repo/checkout.py, dvc/repo/commit.py, dvc/repo/fetch.py, dvc/repo/gc.py, dvc/repo/imp_url.py, dvc/repo/move.py, dvc/repo/push.py, dvc/repo/reproduce.py, dvc/repo/run.py, dvc/repo/status.py, dvc/repo/update.py, dvc/utils/compat.py, tests/func/test_tag.py
We are always loading state when taking a repo lock, so doing it right
in `@locked` decorator simplifies the code for Repo methods.
-----
=> dvc: load state when taking repo lock in @locked

dvc/cache.py, dvc/external_repo.py, dvc/main.py, dvc/repo/__init__.py, tests/func/test_external_repo.py, tests/func/test_import.py, tests/func/test_update.py
Closes #2490
External repos are still created in /tmp. They might be reused until
main() end. If no perfect match is found then a repo with the same url
is copied (not cloned again) and adjusted to fit a request: rev and
cache_dir.
NOTE: test_download_error_pulling_imported_stage() was modified to not
rely on clone error.
=> ui/perf: do not clone same repo multiple times

scripts/completion/dvc.bash
Fixes #2279 
Although I found one potential bug in auto-completion.
This is happening because of `${!options_list}` as `-h` is passed as `option_list`. Since, its variable doesn't exist, it throws this error.
=> Replace hyphen with underscore for command auto-completion

dvc/repo/__init__.py
This depends on filesystem and affects stages collection so must be
reset.
=> dvc: reset dvcignore

dvc/command/version.py, dvc/remote/local.py, tests/func/test_add.py, tests/func/test_cache.py, tests/func/test_repro.py, tests/func/test_run.py, tests/func/test_version.py
Imagine the scenario of shared cache. To set it up, user would do:
```
dvc config cache.dir /path
dvc config cache.shared group
```
Now, when he runs any dvc operation that involves the Repo instance,
RemoteLOCAL will also be initialized and it will currently auto-create
the directory with a regular `os.mkdir`, which is not using group
permissions. To solve that, we can't simply use `self.makdirs` instead,
as it will cause same issues if you run any dvc command before
`dvc config cache.shared group`. So what we should do is create
directories on demand, instead of creating it in advance, same as we do
in other remotes.
The change itself is pretty trivial and involved removing that `mkdir`
line, adjusting tests to not rely on cache dir existence and also
adjusting `dvc version` to create a …
=> remote: local: don't auto-create directory in `__init__`

dvc/repo/get.py, dvc/repo/get_url.py, dvc/repo/imp_url.py, dvc/utils/__init__.py, scripts/ci/before_install.sh, tests/func/test_get.py, tests/func/test_get_url.py, tests/func/test_import.py, tests/func/test_import_url.py
Currently if you run
```
dvc get https://github.com/iterative/example-get-started model.pkl --out .
```
it will nuke your cwd. To fix that we need to properly handle existing
directories, same as usual unix cli utilities do that.
https://github.com/iterative/dvc.org/pull/699
-----
=> get/import/url: handle existing output directory

dvc/repo/brancher.py, dvc/scm/git/__init__.py
This will prevent repetitive cache or metrics collections. Will be especially important for future `--all-commits` flag.
=> dvc: dedup brancher

dvc/cache.py, dvc/data_cloud.py, dvc/output/base.py, dvc/remote/base.py, dvc/remote/local.py, dvc/repo/__init__.py, dvc/repo/fetch.py, dvc/repo/gc.py, dvc/repo/push.py, dvc/repo/status.py, tests/func/test_data_cloud.py, tests/unit/remote/test_local.py
This is a preparation step to make garbage collector work with more
commits. It has a value of its own:
- less exists calls to show cloud status or prepare push/pull
- same names are not repeated in status and pbar texts
=> dvc: dedup used cache

dvc/command/checkout.py, dvc/repo/checkout.py, dvc/repo/pull.py, tests/func/test_checkout.py, tests/func/test_repro.py
Make `Repo.checkout` accept a list of targets, instead of having to feed
it targets one-by-one. This allows us to properly handle checkout
errors.
Fixes #2580
-----
=> checkout: accept multiple targets

dvc/lock.py
This is basically Lock.__init__ copy-paste, except that
instead of using `socket.getfqdn()` we use `socket.gethostname()`
to speed this up. We've seen [1] `getfqdn()` take ~5sec to return
anything, which is way too slow. `gethostname()` is actually a
fallback for `getfqdn()` when it is not able to resolve a
canonical hostname through network. The claimfile that uses
`self._hostname` is still usable, as it uses `pid` and random
number to generate the resulting lock file name, which is unique
enough for our application.
[1] https://github.com/iterative/dvc/issues/2582
Fixes #2582
least opened …
=> lock: skip using slow getaddrinfo

dvc/remote/http.py
This way we are able to properly utilize automatic connection pools and
not create new fds for each request, which overflows ulimit for max fds
very quickly on mac and windows. Kudos @pared for investigating :tada:
Fixes #2600
-----
=> http: reuse requests.Session

dvc/cache.py, dvc/dependency/repo.py, dvc/repo/__init__.py, dvc/repo/fetch.py, tests/func/test_import.py
This prevents same fetches for external artifacts, groups them by source
and fetches in parallel.
=> imp: dedup and parallelize fetching imported deps

dvc/repo/graph.py
We are incorrectly using `simple_cycle` here, `find_cycle` is much more
suitable for this application and much faster too. For example:
```
$ cat test_networkx.py
import networkx as nx
from dvc.repo.graph import check_acyclic
G = nx.scale_free_graph(1200)
list(nx.find_cycle(G, orientation='ignore'))
list(nx.simple_cycles(G))
$ python -mcProfile -scumtime test_networkx.py &> log.log
```
shows ~100s for `simple_cycles` and ~0s for `find_cycle`.
Fixes #2666
-----
=> graph: use find_cycle instead of simple_cycle

dvc/command/add.py, dvc/command/base.py, dvc/exceptions.py, dvc/logger.py, dvc/remote/base.py, dvc/repo/add.py, dvc/stage.py, tests/unit/test_logger.py
`dvc add` output improvements
+ [x] fix/update tests
+ [ ] make sure all other calls to `stage.dump()` do not need this verbosity
old:
[![asciicast](https://asciinema.org/a/m9PX4jUPGZaE1gWp5eWbgEns3.svg)](https://asciinema.org/a/m9PX4jUPGZaE1gWp5eWbgEns3?speed=2)
new:
[![asciicast](https://asciinema.org/a/VC7HfMbG6XxkesVy5sRduHLNN.svg)](https://asciinema.org/a/VC7HfMbG6XxkesVy5sRduHLNN?speed=4)
- #2545
- https://github.com/iterative/dvc/pull/2546#discussion_r337037137
- #2658
=> add: output improvements

dvc/remote/base.py, dvc/remote/local.py, dvc/remote/s3.py, dvc/remote/ssh/__init__.py, tests/unit/remote/test_s3.py
**Fix**: #1654 
**Setup**:
```bash
#!/usr/bin/env bash
set -x
export AWS_ACCESS_KEY_ID='testing'
export AWS_SECRET_ACCESS_KEY='testing'
export AWS_SECURITY_TOKEN='testing'
export AWS_SESSION_TOKEN='testing'
moto_server s3 &> /dev/null &
python -c '
import boto3
session = boto3.session.Session()
s3 = session.client("s3", endpoint_url="http://localhost:5000")
s3.create_bucket(Bucket="dvc-temp")
s3.put_object(Bucket="dvc-temp", Key="fix-1654/")
s3.put_object(Bucket="dvc-temp", Key="fix-1654/cache/")
s3.put_object(Bucket="dvc-temp", Key="fix-1654/empty_dir/")
s3.put_object(Bucket="dvc-temp", Key="fix-1654/empty_file", Body=b"")
s3.put_object(Bucket="dvc-temp", Key="fix-1654/foo", Body=b"foo")
s3.put_object(Bucket="dvc-temp", Key="fix-1654/data/alice", Body=b"alice") …
```
=> s3: support for directories

.deepsource.toml
Hi team,
I just [noticed](https://github.com/iterative/dvc/pull/2548#issuecomment-536255251) that there are could be quite a number of false-positives in `dvc/utils/compat.py` because of, well, the things we have to do for compatibility. I would recommend adding that file to `exclude_patterns` to prevent the noise. I've proposed that in this PR.
We've seen some other projects report this as well, and we're working on proactively suggesting this via the product's UI to make it easier.
Hope this helps!
Best,
Sanket
Founder, DeepSource
=> Exclude compat files from DeepSource analysis

tests/unit/utils/test_fs.py
-----
With reference to #2137
Testing if `get_inode` can take both - Path-like objects and strings.
=> Write test for `get_inode`

dvc/command/gc.py
-----
Resolved https://github.com/iterative/dvc/issues/2681
Commented out `--all-commits` optional argument block
=> Remove --all-commits options from usage output

dvc/lock.py
This bug doesn't affect us during regular dvc CLI commands, but is not
visualy pleasing during API usage.
Fixes #2573
-----
=> lock: add a workaround for a flufl.lock bug

setup.py
`tqdm==4.35.0` was throwing `KeyError` in `tests/func/test_add.py::TestDoubleAddUnchanged::test_dir`.
The stack trace:
```
File "/home/suor/projects/dvc/dvc/main.py", line 43, in main
ret = cmd.run()
File "/home/suor/projects/dvc/dvc/command/add.py", line 24, in run
fname=self.args.file,
File "/home/suor/projects/dvc/dvc/repo/__init__.py", line 33, in wrapper
ret = f(repo, *args, **kwargs)
File "/home/suor/projects/dvc/dvc/repo/scm_context.py", line 4, in run
result = method(repo, *args, **kw)
File "/home/suor/projects/dvc/dvc/repo/add.py", line 60, in add
pbar.bar_format = pbar.BAR_FMT_DEFAULT.replace("|{bar:10}|", " ")
File "/home/suor/.virtualenvs/dvc/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1015, in __exit__
self.close()
File …
```
=> dvc: fix tqdm dep

dvc/repo/checkout.py, dvc/repo/pull.py
Replace generic locked checkout warning with an information report on return when 'dvc pull' is run at import stage.
Related to #2685.
that should be documented?~~ [It does not for both cases.]
-----
The new output, after the minimal steps to recreate as outlined in the Issue to close, is:
```console
$ dvc pull
Data retrieved successfully from DVC remote storage.
```
=> pull, at import stage: replace warning with info report

dvc/output/local.py, dvc/repo/get_url.py, tests/func/test_get_url.py
=> get-url: fix NPE when src non local and dst not absolute

dvc/path_info.py, dvc/remote/s3.py, dvc/remote/ssh/__init__.py
This permites URLInfo construction from parts without building/reparsing
string, which makes it around 20% faster. Code is also simpler and a bit
shorter now.
Other improvements:
- added URLInfo.replace(path=...)
- URLInfo._path now stringifies properly
- protected against passing path not starting with /
- do not allow query, params, fragments and passwords in urls (they were
silently ignored previously)
-----
=> perf: refactor URLInfo to not use ParseResult inside

dvc/remote/ssh/connection.py, tests/unit/remote/ssh/test_connection.py
=> sftp: make move across drives possible

.gitignore, dvc/state.py, dvc/utils/fs.py, tests/unit/utils/test_fs.py
-----
With reference to https://github.com/iterative/dvc/issues/2137 and https://github.com/iterative/dvc/pull/2673#issuecomment-546669793
=> Verify if `get_mtime_and_size` can take both Path objects and strings

dvc/progress.py, dvc/remote/local.py
Fix #2686 
Also change the import to follow PEP8 import rules
-----
=> Remove multi-threaded prefix before progress bar(#2686)

dvc/remote/local.py
=> Rectified simple typos

dvc/remote/local.py, dvc/remote/s3.py
=> typos corrected

dvc/remote/s3.py, dvc/updater.py
dvc/remote/s3.py : Rectified simple typo
dvc/updater.py : Removed "Cask 'dvc' is not installed." error
dvc/remote/s3.py:L148: transfered -> transferred
Delete https://github.com/iterative/dvc/blob/0.66.3/dvc/updater.py#L126 and code block https://github.com/iterative/dvc/blob/0.66.3/dvc/updater.py#L173
Fixes #2680
=> Fixed issue #2680 and Simple typo rectified

dvc/output/base.py
* Have you followed the guidelines in the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) list?
* Check this box if this PR **does not** require
[documentation](https://dvc.org/doc) updates, or if it does **and** you
have created a separate PR in
[dvc.org](https://github.com/iterative/dvc.org)
with such updates (or at least opened an issue about it in that repo).
Please link below to your PR (or issue) in the
[dvc.org](https://github.com/iterative/dvc.org) repo.
below? We consider their findings recommendatory and don't expect
everything to be addresses. Please review them carefully and fix those
that actually improve code or fix bugs.
------------
Fixes the following NPE:
```$ dvc get …
```
=> fix NPE when we do get that does not provide progress callback

dvc/system.py, setup.py
Current implementation is triggering some non-obvious gc bug, that
causes memory leaks. Using win32file simplifies the code and gets rid of
this bug.
To reproduce it, run:
```
from dvc.system import System
while True:
System.inode(__file__)
```
and see your Windows machine run out of memory pretty quickly.
[Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core)
list?
[documentation](https://dvc.org/doc) updates, or if it does **and** you
have created a separate PR in
[dvc.org](https://github.com/iterative/dvc.org)
with such updates (or at least opened an issue about it in that repo).
Please link below to your PR (or issue) in the
[dvc.org](https://github.com/iterative/dvc.org) repo.
below? We consider their findings recommendatory and don't expect
everything to be …
=> system: win: use win32file for _getdirinfo

dvc/remote/ssh/connection.py
Shout-out to @Suor for pointing this out
=> sftp: only remove src after an atomic copy during move

dvc/utils/fs.py, tests/unit/utils/test_fs.py
With reference: #2137 
These changes test if `contains_symlink_up_to` can accept both `str` and `Path` like objects.
<del>I have purposely added the `patch.object` decorator since I wanted to make the symlink true so that it comes out of recursion loop. There can be one addition to this test where we check for this condition as well - https://github.com/iterative/dvc/compare/master...algomaster99:test-arg-types-symlink?expand=1#diff-24be7b52326b428c2569724796020192R72. How to proceed with the latter?</del> Resolved here - https://github.com/iterative/dvc/pull/2740#discussion_r342727237
=> Ensure `contains_symlink_up_to` accept both str and Path-like objects

dvc/remote/local.py, dvc/utils/__init__.py, tests/unit/utils/test_utils.py
With reference: #2137 
- I used `fspath_py35` since all `os.path.*` functions, `open` and `istextfile` accept str and Path like objects.
- `repo_dir` fixture is used because I wanted to compare MD5 digest of a non-empty file. Not using this fixture would have required me to make such file manually.
=> Ensure `file_md5` accept str and Path-like objects

dvc/system.py
A leftover from an old logger refactoring.
=> system: use logging instead of dvc.logger

dvc/remote/local.py, dvc/utils/__init__.py, tests/unit/utils/test_utils.py
=> Ensure `copyfile` accepts str and Path-like objects

dvc/analytics.py, tests/func/test_analytics.py, tests/unit/test_analytics.py
Otherwise this will raise an exception from analytics worker:
```
dvc config cache.type sometypo
```
But running that same command with `--system` or `--global` flag outside
of repo won't raise that.
Also need to better handle ConfigObjError, but that is a separate issue.
=> analytics: don't verify config from repo

dvc/remote/local.py, tests/unit/utils/test_utils.py
=> Ensure `makedirs` accepts str and Path-like objects

tests/func/test_version.py
=> Test for issue #2672 added.

dvc/progress.py, setup.py
- fixes #2766 (from #2697)
- depends on https://github.com/tqdm/tqdm/issues/838 -> https://github.com/tqdm/tqdm/pull/839
=> non-blocking intermediate progress IO

dvc/remote/base.py, dvc/remote/local.py, dvc/utils/__init__.py, dvc/utils/fs.py, tests/unit/utils/test_fs.py, tests/unit/utils/test_utils.py
=> Ensure `move` accepts str and Path-like objects

scripts/ci/install.sh, scripts/ci/install_azurite.sh
Azurite was updated [2] to support new SAS tokens, so we no longer need
to downgrade azure-storage-blob for our tests.
PS: psutil line was removed because we already have it in our test requirements.
[1] https://github.com/iterative/dvc/issues/2387
[2] https://github.com/Azure/Azurite/issues/250
=> test: try using azurite 3.3.0-preview

dvc/lock.py, dvc/main.py
=> Improve `LockError` message

dvc/external_repo.py, dvc/remote/local.py, dvc/repo/destroy.py, dvc/repo/get.py, dvc/repo/init.py, dvc/state.py, dvc/utils/__init__.py, dvc/utils/fs.py, tests/basic_env.py, tests/unit/utils/test_fs.py
With reference: #2137 
P.S. Some tests unrelated to the file changes were failing. I couldn't figure out why.
=> Ensure `remove` accepts str and Path-like objects

tests/unit/utils/test_utils.py
=> Write test for `tmp_fname` to check if it accepts Path-like and str objects

dvc/utils/__init__.py, dvc/utils/compat.py, tests/func/test_utils.py
=> makedirs: fix mode flag is being ignored starting from Python 3.7

dvc/output/local.py, dvc/utils/fs.py, tests/unit/output/test_local.py, tests/unit/utils/test_fs.py
This PR fixes #2605. This will print the relative path of files being downloaded in the console.
=> Display path relative to temporary repo when get/import-ing files

dvc/progress.py
changes `560000/1000023` in progress bars to `560k/1M`
Note that this looses some precision for large numbers but looks nicer. Not sure if this is a good or bad thing.
[![asciicast](https://asciinema.org/a/1frqvezje8S9T8woIDfcpYbSu.svg)](https://asciinema.org/a/1frqvezje8S9T8woIDfcpYbSu?speed=4)
=> use SI prefixes for progress

dvc/remote/gs.py, tests/unit/remote/test_gs.py
=> GS progress for push & pull

dvc/config.py, dvc/remote/gs.py, dvc/remote/local.py, dvc/remote/s3.py
These are remnants from old style remotes configuration
=> dvc: remove unused config paths

dvc/repo/__init__.py, dvc/scm/git/__init__.py, dvc/stage.py, tests/func/test_external_repo.py
Resolves #2823 
~~I did not feel brave enough on `dvc.remote.s3.RemoteS3.exists`.~~
EDIT: `dvc.remote.s3.RemoteS3.exists` cannot be changed, as `path_isin` is os-agnostic, whereas s3 requires posixpath. `dvc/utils/__init__.py:260` has a cyclic dependency problem.
There are few other cases of `startswith`, but are not related with filepaths (except for `dvc/utils/__init__.py` at the end :arrow_double_down:)
```
➜ rg -i startswith dvc tests
dvc/prompt.py
48:    return answer and answer.startswith("y")
dvc/remote/http.py
76:        if etag.startswith("W/"):
dvc/remote/config.py
97:        if remote == RemoteLOCAL and not url.startswith("remote://"):
tests/func/test_repro.py
1076:        assert i.startswith(prefix) and o.startswith(prefix)
1588:    elif line.startswith("cmd: "): …
```
=> Refactor `startswith` with `path_isin` util

.github/PULL_REQUEST_TEMPLATE.md, dvc/data_cloud.py
=> Fix typo and grammar

dvc/command/remote.py, dvc/remote/config.py, tests/func/test_remote.py
remote default command with no arguments now returns default remote instead of
setting default remote to None.
Fixes #2813
=> remote: fix remote default call with no arguments

dvc/exceptions.py, dvc/external_repo.py
Related to #2711 
Original solution (#2777) was passing `cause` of exception resulting in obscure error message:
https://asciinema.org/a/283668
For the sake of UI we [agreed](https://github.com/iterative/dvc/issues/2711#issuecomment-558270517) not to pass the cause, so that we don't end up with this long message.
https://asciinema.org/a/283669
=> RemoteNotSpecifiedInExternalRepoError: dont pass cause of exception

dvc/remote/hdfs.py, dvc/remote/local.py, dvc/remote/ssh/__init__.py
- make all three lazy
- simplify local one
- use deque instead of list for hdfs
=> perf: optimize cache listing for local, ssh and hdfs

tests/func/test_api.py, tests/func/test_get.py, tests/func/test_import.py
https://github.com/iterative/dvc/pull/2837#discussion_r351318487
=> test: refactor & remove redundant test fixtures

dvc/exceptions.py, dvc/remote/http.py, tests/func/test_repro.py, tests/unit/remote/test_http.py, tests/utils/httpd.py
=> remote: http: raise exception when response with error status code

dvc/remote/s3.py, tests/unit/remote/test_s3.py
Fix #2678
https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html
=> s3: ignore empty directories while walking files

dvc/config.py, dvc/remote/__init__.py, dvc/remote/gdrive/__init__.py, dvc/remote/gdrive/utils.py, dvc/scheme.py, setup.py, tests/func/test_data_cloud.py, tests/unit/remote/gdrive/conftest.py, tests/unit/remote/gdrive/test_gdrive.py
Docs update will be tracked under https://github.com/iterative/dvc.org/issues/381
-----
User should create locally GDrive settings file (format expected by PyDrive) and put his/here own Google Project credentials into new created settings file. For test purposes following settings file content might be used:
```
client_config_backend: settings
client_config:
client_id: 719861249063-v4an78j9grdtuuuqg3lnm0sugna6v3lh.apps.googleusercontent.com
client_secret: 2fy_HyzSwkxkGzEken7hThXb
save_credentials: True
save_credentials_backend: …
```
=> GDrive remote support

tests/func/test_api.py
Use `remote_url` fixture first to skip a test before repo dir is created.
=> test: skip non supported remotes fast in api tests

dvc/remote/s3.py, tests/unit/remote/test_s3.py
=> s3: Check for all files in given path to match

dvc/exceptions.py
Related to #2854 
@jorgeorpinel suggestions about `NoRemoteInExternalRepoError` message.
=> NoRemoteInExternalRepoError: fix message

dvc/progress.py
- progress bars now fill the available space
+ unless they're nested, in which case they remain width 10 to align nicely
- fixes #2487
- related #2846 which may remove nested bars altogether
issue:
[![asciicast](https://asciinema.org/a/267948.svg)](https://asciinema.org/a/267948?speed=4)
[![asciicast](https://asciinema.org/a/283771.svg)](https://asciinema.org/a/283771?speed=4)
fix:
[![asciicast](https://asciinema.org/a/Na4RkcFvVFlNruBJJNXFdRugD.svg)](https://asciinema.org/a/Na4RkcFvVFlNruBJJNXFdRugD?speed=4)
=> lengthen bars unless nested/threaded

README.rst
Fix various minor grammatical errors and inconsistencies in the main README.
=> much grammar such fix

dvc/state.py, tests/unit/test_state.py
=> state: quote % in path

dvc/utils/compat.py, tests/conftest.py, tests/dir_helpers.py, tests/func/test_add.py, tests/func/test_api.py, tests/func/test_commit.py, tests/func/test_gc.py, tests/func/test_metrics.py
- `tmp_dir` descends from Path
- convenient template methods to generate files and dirs, add them to
dvc and git and commit to git
- independent of old basic_env structures
- can go in any order
- modular: start with empty `tmp_dir`, initialize git with `scm`, dvc
repo with `dvc` add "repo template" with `repo_template`, ...
=> test: refactor tmp dir helper fixtures

dvc/remote/base.py, dvc/remote/local.py, tests/func/test_add.py, tests/func/test_checkout.py, tests/unit/remote/test_base.py
This fixes #2492, reverts #2358 and fixes #2016 other way.
So now:
- `dvc checkout` does not relink unless out is changed
- `dvc add/run` always relinks, but slow unneeded copy is not made
I left @pared checkout tests and marked them as skipped to be reused later to test `--relink`.
=> dvc: revert checkout to be silly and fast, relink on dvc add though

setup.py
=> setup: fix compatibility errors between dependencies

tests/func/test_add.py
test_add_file_in_dir
test_readding_dir_should_not_unprotect_all
test_should_not_checkout_when_adding_cached_copy
related to #2896 
Started doing whole `test_add`, but iterations will probably be faster in batches, also reviewing 3 changed tests is easier than 20.
=> add: test: convert to dir helpers 1

dvc/remote/base.py
=> remote: base: download: don't walk dir twice

tests/func/test_add.py
test_should_relink_on_repeated_add
test_should_protect_on_repeated_add
=> add: test: convert to dir helpers 2

tests/dir_helpers.py
=> test: write a usage text for dir_helpers

dvc/exceptions.py, dvc/repo/get.py, tests/func/test_get.py
Things changed:
- both no output and no git file result into PathMissingError now
- fail on missing cache or cache download error loudly
- removed sqlite bypass, since we use nolock now anyway
Refactoring:
- streamlined logic and made it similar to Repo.open() one
- moved exclusive exception classes to dvc.repo.get
Things are more complicated here than expected. Still have some issues, things to decide:
- `FileMissingError` has bad message
- should we unify FileMissingError and PathMissingError?
- should we distinguish between?
- neither out nor path is found
- found external out with abs path doesn't use cache 
- abs path for git file
- cache for out is missing
- cache download failed for an arbitrary reason
- how should we treat `dvc get scheme://repo /an/absolute/git/path` when there …
=> get: refactor, clean up and fix `dvc get` implementation

dvc/command/imp_url.py
https://github.com/iterative/dvc/pull/2894
=> import-url: add directories to examples

snap/snapcraft.yaml
Minor non-`classic` cleanup required for https://forum.snapcraft.io/t/classic-confinement-request-for-dvc/14124
> confinement 'classic' not allowed with plugs/slots lint-snap-v2_confinement_classic_with_interfaces https://launchpad.net/bugs/1655369
=> snap: remove plugs (incompatible with classic)

tests/func/test_checkout.py
Skipped tests need to be refactored after #2922
=> checkout: test: refactor to dir helpers

tests/dir_helpers.py
Fixed `erepo_dir` changing current dir, this will help @pared with https://github.com/iterative/dvc/pull/2935.
Also, fixed an unrelated bug in `run_copy`.
=> test: a couple of dir helpers fixes

dvc/command/base.py, dvc/command/daemon.py, dvc/config.py, dvc/lock.py, dvc/repo/__init__.py, dvc/updater.py, dvc/utils/__init__.py, setup.py
As it turned out (see issue numbers down below), we can't really take
hardlinks for granted, so `flufl.lock` is not a panacea for all
filesystems. Considering that the vast majority of filesystems that our
users use support `zc.lockfile`(flock-based) and it has benefits like
more reliable mechanism, auto-delete when process exits, more sturdy
implementation, etc, it makes more sense to bring it back and use by
default again. For filesystems that don't support `flock()`, users will
be able to manually enable `flufl.lock` use through the config option.
It would be ideal if we could auto-detect that flock is not supported,
but in the real world, it turned out to be non-trivial, as it might hang
forever in a kernel context, which makes the implementation way too
complex for our purposes. So …
=> dvc: make flufl.lock opt-in and use zc.lockfile

dvc/lock.py, dvc/path_info.py, dvc/repo/__init__.py, dvc/rwlock.py, dvc/stage.py, dvc/utils/compat.py, tests/func/test_run.py, tests/unit/test_rwlock.py, tests/unit/test_stage.py
Currently only one instance of dvc could run in a particular repo
because of the `.dvc/lock`. That gets furstrating when you are running
some long-running command and blocked from doing anything else.
This PR solved that issue for `dvc run` by releasing the repo lock
while running the command. To protect against conflicts, we now use
rwlock, which keeps the list of readers and writers for particular
paths. The process looks like this:
1) aquire read locks for deps;
2) aquire write locks for outs;
3) release repo lock;
4) run cmd;
5) aquire repo lock;
6) release write locks for outs;
7) release read locks for outs;
We also take rwlocks for operations such as `import`, `add` and `checkout`
to ensure that we won't hit the same files that are being used by
another `dvc run` in the background. …
=> dvc: release locks when running a command

dvc/config.py, dvc/remote/s3.py, tests/unit/remote/test_s3.py
Besides AWS boto3 extra_arg `ACL` (`x-amz-acl` header), there four more
that could be used to grant specific permissions to specific grantees on
the uploaded object.
These headers are:
- `x-amz-grant-full-control` with boto3's extra_arg `GrantFullControl`
- `x-amz-grant-read` with boto3's extra_arg `GrantRead`
- `x-amz-grant-read-acp` with boto3's extra_arg `GrantReadACP`
- `x-amz-grant-write-acp` with boto3's extra_arg `GrantWriteACP`
As `ACL` (`x-amz-acl` header) is limited to be used with predefined canned ACLs,
adding support for the aformentioned headers will help in applying
more customized persmissions solutions according to different project
needs.
References:
- https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#permissions
- …
=> remote: Extend S3 remote support for custom ACL

tests/conftest.py, tests/func/test_add.py
=> temporary_windows_drive fixture: move to dir_helpers

tests/unit/remote/gdrive/conftest.py, tests/unit/remote/test_gdrive.py
Related to https://github.com/iterative/dvc/issues/2865
Have found that available remote tests (`test_azure.py`, `test_s3.py`, `test_oss.py` and others) don't have dvc's API tests, but test only remote specific implementations ( initializing, etc ).
This PR standardize gdrive tests to look similar to other remotes tests.
Test of dvc's APIs for gdrive seems should happen on run of `test_data_cloud.py`. We need to setup Google Project and special account to be used by Travis.
=> Standardize gdrive tests with others remotes

dvc/dependency/repo.py, dvc/exceptions.py, dvc/repo/get.py, dvc/utils/fs.py, tests/func/test_import.py
=> import: allow downloading regular files/dirs tracked by git 

dvc/command/checkout.py
This is the order we use in docs. It also makes sense.
=> ui: reorder checkout options to go from common to rare

tests/func/test_import.py
=> import: test: refactor to dir helpers

tests/func/test_ignore.py
- nested files are ignored
- external dirs are not affected
Testing this to prevent unintended changes to this behavior. Related to #2974.
=> test: test ignore nuances

dvc/command/version.py, tests/func/test_version.py
The issue happens when running `dvc version` with no `psutil` installed.
=> ui: fix extra newline in dvc version

dvc/remote/gdrive.py, tests/unit/remote/test_gdrive.py
Related to https://github.com/iterative/dvc/issues/2865
Addresses issue "Processing of auth exceptions and printing more meaningful error message on failure. [#2551 (comment)](https://github.com/iterative/dvc/pull/2551#discussion_r348182771)"
=> Improve Google Drive auth failure error reporting

dvc/output/base.py, dvc/path_info.py, dvc/remote/base.py, dvc/repo/__init__.py, dvc/repo/checkout.py, dvc/stage.py, tests/func/test_checkout.py, tests/unit/test_repo.py
Using output path or a subdir/subfile path within an output now works
with `dvc push/pull/fetch/status -c` commands. Other commands don't
support the same logic for now, as there are some questions about what
should commands like `dvc remove` do when given a specific output path.
Example:
dvc add data
dvc pull data/subdir # will only pull files within data/subdir
Related to #2458
https://github.com/iterative/dvc.org/issues/886
=> dvc: support granularity for fetch/pull/push/status/checkout

tests/func/test_get.py, tests/func/test_utils.py
=> tests: func: convert test_get.py test_utils.py to new fixtures

scripts/ci/before_install.sh, scripts/ci/check_python.sh, scripts/ci/deploy_condition.sh, scripts/ci/script.sh, setup.py
* Modify `python_requires`, _explicit version classifiers_, and imports in `setup.py`
* Cleanup `ci/scripts` 
Related: https://github.com/iterative/dvc/issues/1818
=> py3: deprecate 2.7

dvc/command/base.py, dvc/istextfile.py, dvc/lock.py, dvc/main.py, dvc/path_info.py, dvc/state.py, tests/func/test_checkout.py
Related: https://github.com/iterative/dvc/issues/1818
=> py3: get rid of is_py checks

dvc/cache.py, dvc/daemon.py, dvc/logger.py, dvc/path_info.py, dvc/repo/metrics/show.py, dvc/rwlock.py, dvc/scm/git/__init__.py, dvc/stage.py, dvc/utils/__init__.py, dvc/utils/compat.py, dvc/version.py, tests/conftest.py, tests/unit/test_version.py
Related: #1818 
Forked from: https://github.com/iterative/dvc/pull/3029 (<-- review this one first) :warning:
=> py3: remove csv_reader and makedirs from utils/compat.py

dvc/repo/metrics/show.py, tests/func/test_metrics.py
=> metrics: don't show working tree if it is clean

dvc/state.py, tests/unit/utils/test_utils.py
=> Ensure `relpath` accepts str and Path-like objects

tests/dir_helpers.py, tests/func/test_api.py, tests/func/test_get.py, tests/func/test_import.py
Will simplify bootstrapping for `erepo_dir`. Closes https://github.com/iterative/dvc/issues/2967.
=> test: add @TmpDir.chdir()

dvc/repo/__init__.py
- no need to normalize paths 
- no need to manipulate with `os.sep`
- use set instead of list
=> dvc: optimize and clean up stages collection

dvc/remote/s3.py, dvc/remote/ssh/__init__.py, dvc/remote/ssh/connection.py, dvc/scm/git/tree.py, tests/remotes.py
Fixed a bug in `GitTree._walk()` not passing `topdown` flag properly along the way.
=> py3: use yield from where appropriate

tests/func/test_data_cloud.py, tests/remotes.py
I tried doing this in a single PR, but, it became fairly large. So, I'm just making a PR with a single change.
After merging all the functions inside `tests/remotes.py`, we could use the {Azure, S3, GCP, etc.} classes as mixins on the `TestCase`s.
Related to #2878.
=> test: Merge _should_test_azure and _get_azure_url inside Azure test helper

dvc/dependency/repo.py, dvc/external_repo.py, tests/func/test_import.py
Fixes #2977
When accessing an `external_repo`, create a '.dvc' directory if
there is not already one there.
=> import: allow importing from non-DVC git repositories

tests/func/remote/test_local.py
=> tests: remote: local: migrate to dir fixtures

dvc/remote/local.py, dvc/scm/tree.py, dvc/utils/fs.py
=> local-related methods should verify that WorkingTree is in use

.travis.yml, README.rst
Finally have approval (https://forum.snapcraft.io/t/classic-confinement-request-for-dvc/14124/8) so can deploy snaps to the snapcraft store!
+ `--edge` <- `master`
+ `--stable` <- tags
Note from approval:
> This snap is using `classic` confinement. The publisher of this snap has been vetted (https://forum.snapcraft.io/t/classic-confinement-request-for-dvc/14124/7) and this snap is now granted use of `confinement: classic`. Note, future uploads may require the snap come from a build on our infrastructure (https://launchpad.net/bugs/1657825) so if you haven't done so already, please configure your builds at https://build.snapcraft.io
=> Snap classic deployment

tests/func/test_api.py
=> tests: api: convert to dir helpers

tests/func/test_cache.py
=> cache: test: migrate to dir helpers

tests/unit/command/test_imp.py, tests/unit/command/test_imp_url.py, tests/unit/remote/test_http.py
=> http/ imp tests - migrate do dir helpers

tests/func/test_data_cloud.py, tests/remotes.py
=> test: merge _should_test_oss and _get_oss_url inside OSS test helper

tests/func/test_data_cloud.py, tests/func/test_repro.py, tests/func/test_s3.py, tests/remotes.py
=> test: merge _should_test_aws and _get_aws_url inside S3 test helper

dvc/remote/base.py, dvc/remote/local.py, tests/func/test_gc.py
In local remote its found that gc does not
remove the unpacked dir. This change set
helps to remove it.
Signed-off-by: Sujith H <sujith.h@gmail.com>
- Fixes https://github.com/iterative/dvc/issues/2946
=> dvc: update gc to remove unpacked dir

.travis.yml
+ ~~seems this is similar to upstream https://github.com/travis-ci/dpl/pull/1122~~ just regenerated the auth token
+ [x] restart & sucessfully complete https://travis-ci.com/iterative/dvc/jobs/272673458
+ seems like because the previous job doesn't run on non-tagged master branch builds, its `stage: deploy` doesn't propagate
- continues #3063
=> fix snap deploy stage

tests/unit/utils/test_utils.py
=> Write test for `walk_files` to check if it accepts Path-like and str objects

dvc/logger.py, dvc/main.py, tests/unit/test_logger.py
https://github.com/iterative/dvc.org/pull/875#discussion_r362920851
Stops showing the exception in non-verbose mode, but shows full
traceback in verbose mode.
Introducing our custom parameter `tb_only` through standard `extra`
logging parameter.
=> ui: don't show exception for "Too many files" error

dvc/exceptions.py, dvc/repo/status.py, tests/func/test_metrics.py
=> ui: warn about ignored options for `dvc status` and a grammar fix

dvc/lock.py, dvc/repo/destroy.py, dvc/stage.py, tests/func/test_repro.py, tests/func/test_run.py, tests/func/test_stage.py, tests/unit/test_stage.py
Mostly a sanity check, but we did have a potential bug in `destroy`,
whcih this PR fixes along the way.
Kudos @shcheklein for catching this one.
=> rwlock: check that .dvc/lock is locked

dvc/logger.py
=> py3: use format_exc instead of print_exception

tests/func/test_install.py
=> install: tests: migrate to dir helpers

tests/func/test_pipeline.py
=> pipeline: test: migrate to dir helpers

tests/func/test_remote.py
=> remote: test: migrate to dir helpers

dvc/main.py, dvc/repo/__init__.py, dvc/stage.py, tests/func/test_ignore.py, tests/func/test_output.py, tests/remotes.py, tests/unit/dependency/test_hdfs.py, tests/unit/output/test_hdfs.py
=> py3: remove code related to py2 limitations

tests/func/test_import_url.py
=> import url: test: migrate to dir helpers

dvc/analytics.py, dvc/remote/base.py, dvc/remote/local.py, dvc/repo/__init__.py, dvc/utils/__init__.py, dvc/utils/fs.py, tests/dir_helpers.py, tests/func/test_checkout.py, tests/func/test_fs.py, tests/func/test_get.py, tests/func/test_get_url.py, tests/func/test_import.py, tests/func/test_import_url.py, tests/func/test_utils.py, tests/unit/remote/test_remote_dir.py, tests/unit/utils/test_fs.py, tests/unit/utils/test_utils.py
This pull request moves all fs utilities to `fs.py` from `__init__.py`.
Fixes #2137
=> Move fs utilities to fs.py from __init__.py

dvc/scm/git/__init__.py
=> dvc: optimize Git.is_tracked()

tests/func/test_repro.py
Some summary:
- replaced ambiguous import commands (default behaviour of run) with `run_copy`
- renamed steps to make structure of `repro_dir` a bit clearer
- add comment explaining how `repro_dir` looks like internally
=> repro: tests: migrate to dir helpers

dvc/system.py
=> py3: use links from os module

tests/func/test_stage.py
=> stage: tests: migrate to dir helpers

tests/func/test_update.py
=> update: tests: migrate to dir helpers

tests/func/test_state.py
=> state: tests: migrate to dir helpers

tests/func/test_run.py
=> run: tests: migrate to dir helpers

dvc/command/get.py, dvc/command/imp.py, dvc/exceptions.py, dvc/external_repo.py, dvc/repo/get.py, tests/func/test_get.py
Allows us to `dvc get` from non-DVC source repositories.
Fixes #3089
Closes #3077
Will send PR for doc site tomorrow. Just need to change some parts which imply that the remote repository needs to be DVC-enabled.
----
docs: https://github.com/iterative/dvc.org/issues/911
=> get: handle non-DVC repositories

dvc/rwlock.py
It is important that we ensure that rwlocked contents are flushed to
disk, because otherwise other rwlock readers might get outdated state.
Kudos @shcheklein for catching this one.
=> rwlock: flush and fsync

dvc/remote/gdrive.py, setup.py, tests/unit/remote/test_gdrive.py
=> gdrive: add support for teamDriveId

tests/func/test_data_cloud.py, tests/func/test_repro.py, tests/remotes.py, tests/unit/remote/ssh/test_ssh.py
=> test: refactor ssh related functions in test helper classes

tests/func/test_data_cloud.py, tests/func/test_repro.py, tests/remotes.py
=> test: move hdfs and gcp functions into helper classes

dvc/version.py, tests/unit/test_version.py
By default, `check_output` returns the data as encoded bytes.
We need to decode it properly to compare them with strings.
Using `bytes` as the return value of `check_output` mock will reflect the behavior correctly.
Close #3127
=> version: decode correctly commands output

tests/func/test_data_cloud.py, tests/func/test_remote.py, tests/remotes.py
=> test: merge local related function in Local helper class

dvc/command/metrics.py, dvc/repo/brancher.py, dvc/repo/metrics/__init__.py, dvc/repo/metrics/diff.py, dvc/repo/metrics/show.py, setup.py, tests/func/test_metrics.py, tests/unit/command/test_metrics.py
This first implementation is based on existing `dvc metrics show`     
functionality, which has `type` and `xpath` support to determine      
specific values in your file that you are interested in. That makes   
comparing pretty straightforward to implement.                        
Related to #2995 
TODO:
------------------------------
https://github.com/iterative/dvc.org/issues/921
=> metrics: introduce `diff`

tests/func/test_data_cloud.py, tests/remotes.py
This is what I had in mind when refactoring #2878. This is still a work in progress at the moment though.
---
=> test: use helper remotes in TestCases

dvc/remote/gdrive.py, setup.py
PyDrive2 is our maintained fork.
=> dvc: use pydrive2 instead of pydrive

dvc/config.py, dvc/remote/base.py, tests/unit/remote/test_gdrive.py, tests/unit/remote/test_remote.py
Close #2920
I would like to suggest to define and use such terms for avoiding ambiguity                                                              
- **config** - global repo config                                                                                                                        
- **settings** - dict of **config** section                                                                                                            
Hence refactor **RemoteBase** from                                                                                                                     
```
def __init__(self, repo, config):  ->  def __init__(self, repo, settings):
```
with all changes as `config -> settings`
Then get some setting as: …
=> remote: config checksum_jobs

dvc/api.py
=> api: identify local repos with os.path.exists

.travis.yml, scripts/ci/deploy_condition.sh
- references
+ https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
+ https://docs.travis-ci.com/user/environment-variables
=> major deploy tidy

dvc/main.py
=> point to troubleshooting guide on too many open files error

tests/conftest.py, tests/func/test_get.py
=> conftest: remove dvc_repo, erepo, git, git_erepo

dvc/dependency/repo.py, dvc/repo/status.py, dvc/stage.py, tests/func/test_status.py, tests/func/test_update.py
This fix only works when the remote is located in your machine. For remote DVC projects, it doesn't work and I'm looking into why.
Also I'm having a lot of trouble writing a unit test for this. The CLI works fine but when I call `dvc.status(with_deps=True)` in the test it reports that nothing changed.
Fixes #2959
------
:point_up: `dvc lock` docs imply that locked files are impervious to `dvc status`.
:point_up: I changed some code which already had DeepSource antipatterns and it re-detected them.
=> status: implement support for imported files

dvc/system.py, setup.py
=> Perf improvement for file copies

dvc/api.py, dvc/command/get.py, tests/func/test_api.py, tests/func/test_get.py, tests/unit/command/test_get.py
Closes #2994. 
From the product requirements, it deviates on the following issue:
1. For now, it does not support showing URLs for multiple paths.
So, we can only do `dvc get <url> <path> --show-url` for a single path, so as 
to make it compatible with `dvc get`.
2. It also does not support specifying remote at the moment, so as to not introduce new flags.
3. It does not work with the file inside of a directory (i.e. `dir/file`). Limitation of `dvc.api.get_url()`. Requires adding directory granularity support.
```sh
➜ dvc get . dir/file --show-url
ERROR: failed to show url - unable to find DVC-file with output 'dir/file'
```
4. How to show path/URL to the directory? Currently, it only shows `.dir` file.
```sh
➜ dvc get . dir --show-url …
```
=> get: implement --show-url to display only url/path to remote

dvc/utils/__init__.py, tests/unit/utils/test_utils.py
=> utils: resolve_output: normpath before extracting basename

dvc/remote/s3.py
When executing `boto3.s3.Client.Copy`, large files are chunked into
multiple parts. The default chunk threshold and size is 8MB. This
caused an issue when caching an object larger than 8M, where the
original object had not been uploaded in multiple parts. The original
object and the cached object would have different ETags, causing an
exception. This fixes the issue by dynamically setting the chunk
threshold to be one byte larger than the size of the original object
therefore avoiding multipart copies.
Fixes #3174
* [:white_check_mark:] ❗ Have you followed the guidelines in the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) list?
* [:white_check_mark:] 📖 Check this box if this PR **does not** require [documentation](https://dvc.org/doc) updates, or if it does …
=> s3: copy large objects without chunking

dvc/remote/s3.py
Kudos to @skshetry for bringing this out during a review: https://github.com/iterative/dvc/pull/3186#discussion_r368209924
This is important, since someone can use DVC without having `boto3` installed.
=> s3: import boto3 inside _copy instead of module level

dvc/dependency/repo.py, tests/func/test_import.py
Fix the import issue when target does not have
remote config.
- Fixes https://github.com/iterative/dvc/issues/2780
Signed-off-by: Sujith H <sujith.h@gmail.com>
=> Fix import issue without remote config in the target

dvc/api.py
=> api: better code documentation

dvc/remote/http.py
The reason for this problem is a 301 without a Location header. In our HTTP remote we can treat this as an error, since we don't know where to actually find the data.
Fixes #2963
-------
=> pull: treat HTTP redirects without Location header as error

dvc/logger.py, dvc/remote/base.py, dvc/rwlock.py, dvc/state.py, dvc/utils/fs.py
Part of #1843 , related to https://github.com/iterative/dvc/issues/3177
As our previous investigations showed, path stringification and stuff
like relpath are taking a very large chunk of time when working with
giant directories. This patch removes `format()`s and uses lazy
formatting provided by logger instead, so stuff like path_info is not
stringified until actually needed (e.g. on `-v`).
Benchmark results coming soon
=> logger: remote: use lazy formatting

.travis.yml, dvc/repo/__init__.py, scripts/build_package.sh, scripts/build_posix.sh, scripts/build_snap.sh, scripts/ci/before_install.sh, snap/snapcraft.yaml
+ [x] `--version`
+ [x] `version`
+ [ ] ~~`get`~~ doesn't work due to unknown CI (travis) issue; will test in https://github.com/iterative/dvc-test/issues/8 instead.
- fixes #2954
- (re) fix #3152
=> add snap tests

dvc/api.py, dvc/dependency/repo.py, dvc/exceptions.py, dvc/external_repo.py, dvc/remote/config.py, dvc/remote/local.py, dvc/repo/__init__.py, dvc/repo/fetch.py, dvc/repo/get.py, tests/func/test_api.py, tests/func/test_external_repo.py, tests/func/test_get.py, tests/func/test_import.py, tests/func/test_status.py, tests/func/test_update.py
Some things are fixed along the way:
- no cache shared between incompatible funcs
- some incosistent exceptions are now consistent
- import updates for git files now works both for dvc and git repos
- "auto-generated-upstream already exists" fixed
- api.open()/read() works with git repos now
- api funcs allow specifying `rev` for local repos now
Fixes #3124, fixes #2976, fixes #3179, and fixes #2824. Closes #3172.
=> external: refactor external_repo() and its users

tests/dir_helpers.py, tests/func/test_add.py, tests/func/test_gc.py
Provides `make_tmp_dir` fixture. A base for simplifying tests where we now remove `.dvc` in erepo. 
Cleaning up that code will conflict with #3190, so waiting for that.
=> test: refactor tmp_dir/erepo_dir

dvc/repo/add.py
=> py2: remove use of `six`

dvc/config.py, dvc/remote/base.py, dvc/remote/gdrive.py, tests/unit/remote/test_gdrive.py, tests/unit/test_config.py
=> gdrive: allow configuring no_traverse

dvc/repo/metrics/diff.py, setup.py
flatten_json has a conda package, while flatten_dict doesn't and I'm not
willing to maintain yet another conda package :)
=> dvc: replace flatten_dict with flatten_json

dvc/dependency/repo.py, tests/func/test_import.py
URL should be required and rev or rev_lock should be optional.
Related to #3087
=> erepo: fix DependencyREPO schema

tests/dir_helpers.py, tests/func/test_get.py, tests/func/test_import.py, tests/func/test_status.py, tests/func/test_update.py
=> test: add git_dir

.travis.yml, scripts/ci/before_install.sh, snap/snapcraft.yaml
+ really it should be automatically picked up and used *correctly*: https://docs.travis-ci.com/user/deployment-v2/providers/snap/#environment-variables. Looks like a travis bug.
+ `dvc --version` => `<tag>+<hash>.mod` rather than `<tag>`
+ because of making tweaks to source while building the snap package? https://github.com/iterative/dvc/blob/aa86eab2cc4acbfc34279312eaa5cf1b8f30558e/snap/snapcraft.yaml#L30-L33
- continues #3173, #3158 <- (re) fixes #3152
- continues #2956 <- (re) fixes #2954
=> fix snap stable & edge release errors

dvc/repo/brancher.py
From https://github.com/iterative/dvc/pull/3207#discussion_r369496309
When if it's a dvc only repo, brancher was failing as `NoSCM` does not have `resolve_rev`.
```sh
$ dvc init --no-scm
$ python -c '
from dvc.repo import Repo
repo = Repo(".")
print(list(repo.brancher(all_branches=True, all_commits=True, all_tags=True)))
'
File "<string>", line 4, in <module>
File "/home/saugat/repos/iterative/dvc/dvc/repo/brancher.py", line 45, in brancher
for sha, names in group_by(scm.resolve_rev, revs).items():
AttributeError: 'NoSCM' object has no attribute 'resolve_rev'
```
=> brancher: do not get tree if there's no revs

.travis.yml, scripts/ci/before_install.sh
Try again to fix snap stable & edge release errors. This time with aggressive debugging so won't need to merge before failures are detected (will need a local branch - status: [![Build Status](https://travis-ci.com/iterative/dvc.svg?branch=snap-deploy)](https://travis-ci.com/iterative/dvc)).
- continues #3209, #3173, #3158 <- (re) fixes #3152
=> another attempt at travis dpl snap

dvc/__main__.py, dvc/api.py, dvc/cache.py, dvc/cli.py, dvc/command/cache.py, dvc/command/daemon.py, dvc/command/get.py, dvc/command/init.py, dvc/command/install.py, dvc/command/metrics.py, dvc/command/pipeline.py, dvc/command/remote.py, dvc/config.py, dvc/exceptions.py, dvc/lock.py, dvc/logger.py, dvc/progress.py, dvc/remote/config.py, dvc/scm/__init__.py, dvc/stage.py, tests/dir_helpers.py, tests/func/test_api.py, tests/func/test_get.py, tests/func/test_remote.py
> Per https://github.com/iterative/dvc/pull/3156#pullrequestreview-345562608
Docs PR already exists: iterative/dvc.org/pull/926
=> get: copy edits aroud --show-url, "dvc", et al.

dvc/scm/git/__init__.py
When running from non-root directory `git ls-files .dvc` will treat it
as a relative path to the current location, so if you run `git checkout`
from a directory that is not a git/dvc root, our hook will think that
it is being run in a non-dvc repo and will do nothing. To fix that, [need
to use `--full-name` flag](https://git-scm.com/docs/git-ls-files#Documentation/git-ls-files.txt---full-name).
=> hooks: checkout: fix incorrect dvc repo detection

tests/func/test_add.py, tests/func/test_data_cloud.py, tests/func/test_import_url.py, tests/unit/utils/test_fs.py, tests/utils/__init__.py
After I'd started, @pared pointed out that it would be best to convert the tests to plain functions as opposed to classes, to better utilise the `mocker` fixture. I ended up having to create a bunch of wrappers just to use this fixture. Let me know if you'd like me to go ahead and convert all of the classes that were using spy into plain pytest function tests.
Fixes #3198
-------
=> tests: replace spy() with pytest-mock spy

dvc/command/version.py, dvc/remote/base.py, dvc/remote/local.py, tests/func/test_version.py
=> dvc: add sanity checks for hard/symlinks

dvc/api.py, dvc/external_repo.py, tests/func/test_api.py
Fixes #3221. Now, it will just fallback to the `external_repo` if `Repo()` could not be instantiated.
Another idea would have been to check for the existence of `.dvc` directory, but, I went with this, as it feels correct and *robust*.
=> api: fallback to external_repo if not a DVC repository

tests/remotes.py
Fixes #3157 
Secure env variable should be set by Travis before this PR is get merged.
=> Update Google Project credentials to run tests

dvc/command/remote.py, dvc/dagascii.py, dvc/exceptions.py, dvc/remote/gdrive.py
Found one wrong link in code, added link formating for some more `man.dvc.org` usages.
=> some doc link fixes

dvc/exceptions.py, dvc/output/base.py, dvc/remote/base.py, tests/func/test_remote.py
Fixes #2647 
[![asciicast](https://asciinema.org/a/295538.svg)](https://asciinema.org/a/295538)
=> remote: verify cache exists on dir checksum

dvc/scm/git/__init__.py
We shouldn't try to automatically checkout in detached HEAD state, as we
might break the rebase process.
Fixes #3107
=> install: post-checkout: run only on branches/tags

dvc/remote/gdrive.py
Related to #2865 
Since PyDrive2 was [updated to newer version](https://github.com/iterative/dvc/commit/2f1224b27b240d0806b927664b99273c384f1573) the usage of `errors.HttpError` is not needed anymore according to https://github.com/iterative/PyDrive2/pull/5
=> Remove usage of google-api-python-client deps

dvc/config.py, dvc/data_cloud.py
This tries to clear up the error message of NoRemoteError in case the user doesn't have any remotes, and provides instructions on how to create a remote, or a default remote. It also clears the extra newline at the end.
Fixes #3121
----
=> push: improve 'no remote specified' hint

dvc/external_repo.py, tests/func/test_external_repo.py
- code moving during git pull won't affect any erepos
- source tag move will work as expected
- source cache dir setting will never break havoc
- cache is reused between all clones from same source
=> erepo: make it better

dvc/config.py, tests/func/test_config.py, tests/func/test_remote.py
=> config: verify before saving a modification

dvc/remote/gdrive.py, setup.py
PR is not yet ready: will require update of PyDrive2 along with this PR.
https://github.com/iterative/PyDrive2/pull/6 should be merged first.
=> Set corpora and driveId params values based on type of remote disk - shared or user's.

dvc/cli.py, dvc/output/base.py, dvc/progress.py, dvc/remote/base.py, dvc/repo/__init__.py, dvc/repo/add.py, dvc/repo/get_url.py
- fixes #2699
- continued in #3060
**Extra progress bar concern:**
We started using an extra progress bar that is counting targets, as described and shown here: #2658 . In most cases though there is a single target - `dvc add file` or `dvc add directory`. That extra progress bar is not needed in those cases. It's needed in case of multiple targets or if `-R` option is specified.
most issues fixed:
[![asciicast](https://asciinema.org/a/kuXz8YYQOoCxsQ0v3zqzOFBQE.svg)](https://asciinema.org/a/kuXz8YYQOoCxsQ0v3zqzOFBQE?speed=4)
large dir fix, no outer bar for single target, more progress output rather than hanging:
[![asciicast](https://asciinema.org/a/1DDfK2DvD41rNk1RJGMOXM7me.svg)](https://asciinema.org/a/1DDfK2DvD41rNk1RJGMOXM7me?speed=4)
recursive: …
=> UI progress cleanup

dvc/scm/git/__init__.py
We should skip running post-checkout hook on rebases and merges to not
accidentally break them in the middle of the process. Git doesn't
provide any native mechanisms for hooks to know whether or not this is a
rebase/merge that we are going through, but we can use
`.git/rebase-merge` existance as a marker.
Previous approach has only accounted for branches and was causing issues
when checking-out tags.
Fixes #3241
=> install: fix post-checkout hook

dvc/api.py, dvc/repo/__init__.py, dvc/scm/git/__init__.py, tests/func/test_api.py
Based on @dmpetrov's https://github.com/iterative/dvc/pull/3238
Another change - removed type python summon support from here, moving it to dvcx, to keep everything there.
=> api: prepare for dvcx summon/publish

dvc/api.py, tests/func/test_api.py
An iteration on summoning (see https://github.com/iterative/dvcx/pull/4):
1. Some minor Summon file format changes and default file name change to `Summon.yaml`.
2. Separating reading objects and pulling data. It is needed for flexibility and especially for data objects with several files like a compound CSV file (see in #2719).
3. Summon object update `update_dobj()`. This is not completed but it does not break current read-only logic.
4. Moving part of the logic to `SummonDesc` class.
=> Summon - next iteration

dvc/repo/__init__.py
The things is we create dirs as needed, so if outs are not checked out a
directory containing nothing but outs may be absent.
=> dvc: do not check for isdir on recursive out collect

dvc/main.py
We used to have this line previously, thinking that it was only a py2
issue, but it turned out that it happens on py3 as well. So bring this
line back for now.
=> remote: bring back manual close_pools()

dvc/stage.py
The prompt shown when committing without `-f` had a missing space between sentences.
------
=> commit: add missing space

dvc/command/pipeline.py, tests/func/test_pipeline.py
This fixes extra nodes edges appearing in `pipeline show --outs`, by using networkx to traverse the graph instead of listing all edges.
I spent a lot of time trying to figure out how to test this, so I thought I'd either leave it untested or take suggestions from the PR review.
Fixes #1744
----
=> pipeline: show: outs: eliminate extra edges in DAG

dvc/rwlock.py
=> rwlock: include actionable in error message

dvc/rwlock.py
Previous implementation allowed incomplete info:
```python
SCHEMA({
"write": {
"file_1": {"pid": 1, "cmd": "exec"},
"file_2": {"pid": 2},
"file_3": {"cmd": "..."},
"file_4": {},
},
"read": {
"file_1": [{"pid": 1}],
}
})
```
=> rwlock: require info keys to be present in schema

dvc/rwlock.py, tests/unit/test_rwlock.py
=> Fix blockers list in rwlock error message

dvc/scm/git/__init__.py, tests/dir_helpers.py, tests/func/test_get.py, tests/func/test_scm.py
git: check if files are handled by root-dir `.gitignore`
When a file is already ignored through the root-dir `.gitignore` file, we don't want to add it to the "local" `.gitignore` file created by dvc
Fixes #1714
=> check root .gitignore in '_ignored'

dvc/remote/gdrive.py
Implements `RemoteGDrive.remove` to support gc functionality.
Related to #2865
=> gdrive: add gc command support

dvc/logger.py, tests/unit/test_logger.py
This better reflects the original logger formatter and is neede for further improvements in the following PRs.
This also fixes annoying redundant newline between traceback and "need
any help" footer.
=> logger: allow exc_info in all record types

dvc/analytics.py, tests/unit/test_analytics.py
Users have been complaining about dvc analytics errors when they are not
connected to the internet.
=> analytics: ignore request.post errors

dvc/command/get.py, dvc/command/imp.py
At least on v `0.82.6`. I created a `--no-scm` project and tried to `get` and `import` from it to other locations, getting:
```
ERROR: failed to get 'data' from '/Users/drbidibombom/DVC-repos/no-scm-aux' - Failed to clone repo '/Users/drbidibombom/DVC-repos/no-scm-aux' to '/var/folders/_c/3mt_xn_d4xl2ddsx2m98h_r40000gn/T/tmpy1o07ch5dvc-clone': Cmd('git') failed due to: exit code(128)
cmdline: git clone --no-single-branch -v /Users/drbidibombom/DVC-repos/no-scm-aux /var/folders/_c/3mt_xn_d4xl2ddsx2m98h_r40000gn/T/tmpy1o07ch5dvc-clone
stderr: 'fatal: repository '/Users/drbidibombom/DVC-repos/no-scm-aux' does not exist
'
Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```
---
Docs update in iterative/dvc.org/pull/931 & iterative/dvc.org/pull/978
Thank …
=> get/import: they don't work with any DVC project, only DVC repos (as well as Git repos)

dvc/exceptions.py, dvc/repo/__init__.py
When Repo is instantiated with invalid urls such as 'http://github.com/iterative/dvc.git',
it does os.path.realpath which is not intelligent enough and just concatenates with current
working directory, which is then traversed outward. It might happen that the outward folder
is a dvc directory which is not really what we want.
So, a check for root to be a directory is added. Otherwise, NotDvcRepoError is thrown with
a custom message.
**TLDR**: `Repo("https://github.com")` and `Repo("not existing directory")` should throw `NotDvcRepoError` even if dvc repo exists outward.
=> repo: raise exception if root_dir is not a directory path

dvc/command/diff.py, dvc/command/metrics.py, dvc/repo/diff.py, dvc/repo/metrics/diff.py, tests/func/test_metrics.py, tests/unit/command/test_metrics.py
=> diff: use `rev` instead of `ref`

dvc/external_repo.py, dvc/scm/git/__init__.py
So we have 3 things cached now separately:
- clean clones, to not ask for creds repatedly
- cache dirs, also shared between erepos with same origin
- checked out clones if they are read only, addressed by (url, hexsha)
Several additions to `Git` along the way:
- Git.is_sha() static method
- .pull() and .push() work with multiple returned records correctly
- .get_rev() and .resolve_rev() work faster
- .resolve_rev() looks for remote branches
- .has_rev()
Fixes #3280.
=> erepo: cache all read only external repos by hexsha

.pre-commit-config.yaml, .restyled.yaml, setup.py, tests/func/remote/test_local.py, tests/func/test_add.py, tests/func/test_commit.py, tests/func/test_gc.py, tests/func/test_stage.py, tests/func/test_status.py, tests/func/test_update.py, tests/unit/repo/test_repo.py, tests/unit/repo/test_reproduce.py
I opened a PR a while ago to update `black` to the latest version: https://github.com/restyled-io/restylers/pull/50
=> black: bump version 19.3b0 -> 19.10b0

dvc/exceptions.py, dvc/repo/__init__.py, dvc/repo/add.py, tests/func/test_add.py
=> add: meaningful message upon adding overlapping paths

dvc/logger.py, tests/unit/test_logger.py
=> logger: log datetime when on debug mode

tests/func/test_data_cloud.py
Client secrets had a typo on tests which were failing CI.
=> tests: fix typo on gdrive_client_secret

dvc/repo/add.py, dvc/repo/imp_url.py, dvc/stage.py, tests/func/test_import_url.py
=> imp_url: make default stage fname accompany import target

.travis.yml, snap/snapcraft.yaml
=> snap: test: add build and deploy checks

dvc/config.py, tests/func/test_config.py
=> dvc: do not set cache dir if it's not a dvc repo

dvc/output/__init__.py, dvc/stage.py, tests/unit/output/test_output.py
This allows editing your dvc-files and using values such as `1111...111`(digit-only md5) and `''`(empty string).
Fixes #3331
=> schema: use a more flexible hash schema

dvc/command/update.py, dvc/dependency/base.py, dvc/dependency/repo.py, dvc/repo/update.py, dvc/stage.py, scripts/completion/dvc.bash, scripts/completion/dvc.zsh, tests/func/test_update.py, tests/unit/command/test_update.py
=> update: support specifying revision when updating

dvc/logger.py, tests/unit/test_logger.py
This PR includes some modifications that I did way back but never pushed them, some problems where already addressed by #3290 
* Remove dead code
* Rename _walk_exc to _causes, simplify it
* Split up stack trace and remove extra \n
* Import traceback only when needed
* Add test `exc_info` in other levels
=> logger: refactor, remove dead code

dvc/external_repo.py, dvc/output/base.py, dvc/utils/fs.py, tests/func/test_get.py, tests/func/test_import.py
=> get/import: retrieve files inside directory outs

dvc/external_repo.py, tests/func/test_external_repo.py
=> external_repo: fix bug in path resolution

dvc/remote/base.py, dvc/remote/gdrive.py, dvc/remote/gs.py
make `no_progress_bar=False` rather than `True`
----
- fixes #3332
- replaces/closes #3334
- depends on #3316
=> ui: fix missing progress & tidy

dvc/repo/__init__.py, dvc/repo/add.py, tests/func/test_add.py, tests/unit/repo/test_repo.py
=> Stage: create: reset repo when removing existing stage

scripts/completion/dvc.bash
+ e.g. `dvc metrics add` would only complete one more argument before
- misc minor tidy
- related: #3360 <- #1923
=> completion: bash: allow multi-arg completion, minor tidy

.zenodo.json, README.rst, setup.py
+ this is a custom "all version" one which is nicer as it always points to the latest release. Yes, that sort of defeats one of the points of a DOI (version pinning) but we have version numbers for that. It's better to promote just one DOI to make it easy to track citations.
+ setup.py
+ GitHib repo
+ Zenodo
- fixes #2978
- related #3233
=> metadata: add Zenodo, tidy badges and keywords

scripts/completion/dvc.bash
+ [x] only autocomplete DVC-files where appropriate
- fixes #3361
- fully fixes #1923
- continues #3360
- related #2985
- `-o nospace` is required (as documented in the code) to avoid an unreasonable rewrite of everything.
- the `snap` package automatically benefits from this PR :)
- I'm tempted to write a test for future use, and perhaps even think of a way to automate based on `argparse` but that way likely lieth a massive independent project moste arcane.
+ have manually tested all current permutations though
I haven't seen any code examples take this approach and don't know why. It looks elegant, maintainable, and efficient to me.
=> completion: bash: properly recurse targets

dvc/config.py, dvc/remote/http.py, tests/conftest.py, tests/func/test_data_cloud.py, tests/remotes.py, tests/unit/remote/test_http.py, tests/utils/httpd.py
iterative/dvc.org/pull/1006
WIP PR for #3247 
* Adds support for POST uploads to http remotes
* Adds support for HTTP Basic and Digest authentication methods (for both upload and download operations)
* `basic_auth` and `digest_auth` boolean options added to the http(s) remote configurations (digest takes precedence if both are set to true)
* When no auth method is specified (or both are set to false), existing behavior is used (no auth method, assumes all HTTP endpoints are public for both upload and download)
* Username/password combinations can be configured in the same way as ssh remotes
* Password can be set in config or prompted on command line via `ask_password` config option
Still TODO:
=> remotes.http: Support dvc push for http remotes

dvc/output/base.py, tests/func/test_stage.py, tests/unit/output/test_output.py
=> Stage: fix used_cache warning on no checksum

dvc/command/gc.py, dvc/exceptions.py, dvc/repo/gc.py, tests/func/test_gc.py, tests/func/test_repro.py
Previous plain `gc` is now not supported. The same behavior can be trigger by
`gc -w` or `gc --workspace`. When `--all-{tags, commits, branches}` are
specified, it will work as if `-w` is also specified (same as before).
https://github.com/iterative/dvc.org/issues/1013
Related to #2325
=> gc: make it safer by only activating by use of certain flags

dvc/api.py
Matches iterative/dvc.org/pull/908
=> api: docstring updates

dvc/command/init.py, dvc/config.py, dvc/ignore.py, dvc/repo/__init__.py, dvc/repo/init.py, dvc/scm/__init__.py, dvc/scm/base.py, dvc/scm/git/__init__.py, tests/dir_helpers.py, tests/func/test_ignore.py, tests/func/test_init.py, tests/func/test_scm.py, tests/func/test_stage.py
=> SCM: allow multiple DVC repos inside single SCM repo

dvc/analytics.py, tests/func/test_analytics.py
=> analytics: fix resolving used scm

dvc/repo/fetch.py
=> pull: fetch: external: respect `--jobs`

dvc/system.py, setup.py
=> Remove Linux pyfastcopy

dvc/external_repo.py, tests/func/test_external_repo.py
=> erepo: fix relative url on default remote (#2756)

dvc/external_repo.py
Added more logging to erepo code, combined with timestamps that we now have this might be used to investigate issues like #3280.
=> erepo: set up more logging

dvc/logger.py, dvc/main.py, tests/dir_helpers.py
very small change that fixes #3344
=> dont disable existing loggers when dvc is set up

README.rst
+ number of users
+ number of potential users <-- I'd recommend this
+ number of desired users
- fixes #3233
- related iterative/dvc.org#904
=> docs: update badges

tests/unit/test_imports.py
We had this missed out repeatedly over time, so I added a check that we don't import any remote related deps on initial load.
Examples of related issues are #3399 and #2445.
=> test: check that no remote backend modules are loaded by default

dvc/command/pipeline.py, tests/func/test_pipeline.py
=> pipelines: fix edges gathering

dvc/repo/__init__.py, setup.py
Use trie structure to efficiently check out, dep and stage paths being
prefixes of each other.
Will help with #2671.
=> dvc: optimize building graph

dvc/config.py, dvc/remote/gdrive.py, setup.py, tests/func/test_data_cloud.py, tests/remotes.py, tests/unit/remote/test_gdrive.py
https://github.com/iterative/PyDrive2/pull/7 should be merged first
Introduces `gdrive_service_account_email`, `gdrive_service_account_user_email` and `gdrive_service_account_p12_file_path` DVC config params to support authorization with Google Service accounts.
Introduced config params are independent from `client_id` and `client_secret` config params
Update:
https://github.com/iterative/PyDrive2/pull/11 should be merged first
Introduces  `gdrive_user_service_account` DVC config param disabled by default.
=> gdrive: support Google Service accounts

dvc/remote/local.py, tests/func/test_add.py
=> add: do not verify hardlink if file is empty

tests/func/test_ls.py, tests/unit/command/test_imp_url.py, tests/unit/test_logger.py, tests/unit/utils/test_utils.py
`mocker` is not expected to work as a context-manager (https://github.com/pytest-dev/pytest-mock/issues/164), and raises a `ValueError` if done so.
Ref: https://github.com/pytest-dev/pytest-mock#note-about-usage-as-context-manager
=> tests: remove use of mocker as context-manager

dvc/command/checkout.py, dvc/command/data_sync.py, dvc/exceptions.py, dvc/external_repo.py, dvc/remote/base.py, dvc/repo/checkout.py, dvc/repo/pull.py, dvc/stage.py, dvc/state.py, tests/func/test_checkout.py, tests/func/test_state.py, tests/unit/command/test_checkout.py
https://github.com/iterative/dvc.org/pull/1054
Resolves #2979.
**TODO**
=> checkout: show summary by default and introduce --show-changes flag

dvc/command/ls/__init__.py, dvc/exceptions.py, dvc/repo/ls.py, scripts/completion/dvc.zsh, tests/func/test_ls.py
Close #3381
Close #2509 again
iterative/dvc.org/pull/1021
=> list: rename target param to path, update docs

.travis.yml, dvc/system.py, scripts/ci/before_install.sh, scripts/ci/install_hadoop.sh, setup.py, tests/func/test_checkout.py
Fixes #3033
PyInstaller does not support Python3.8 yet: https://github.com/pyinstaller/pyinstaller/issues/4311 
- ~~Try to update pyarrow to 0.16.0 for other versions of Python and make them pass.~~
Not possible due to https://issues.apache.org/jira/browse/ARROW-7852.
We should try to be ahead of the `PyArrow` regarding releases. So, we should at-least be able to release non-hdfs packages before/on release of new python versions. We can run tests on `3.9-dev`   without `PyArrow`.
Do we need to support Python3.5? [The number of downloads are already low](https://pypistats.org/packages/dvc) (and, numpy/conda does not support this version at all).
=> dvc: support Python3.8

dvc/repo/diff.py, tests/func/test_diff.py
=> [WIP] cmd: diff: don't load dir cache for diff

dvc/external_repo.py, dvc/logger.py, dvc/remote/base.py, dvc/state.py, dvc/utils/fs.py
Unfortunately overriding `format` is not enough in order to use our own
custom formatting in logger. `Record` uses percent formatting that is
hardcoded inside, so we would also have to override it, which is just
way too much effort that will inevitably break as we discover other
methods that are not ready for non-% formatting. So we are just giving
up and sticking to default %-formatting for lazy log messages.
Fixes #3397
=> logger: use standard lazy formatting

dvc/command/gc.py, dvc/repo/gc.py, tests/func/test_data_cloud.py, tests/func/test_gc.py
=> gc: do not work without specifier when using -c flag

dvc/command/unprotect.py, dvc/config.py, dvc/remote/base.py, dvc/remote/local.py, dvc/remote/ssh/__init__.py, tests/func/remote/test_local.py, tests/func/test_add.py, tests/func/test_api.py, tests/func/test_cache.py, tests/func/test_checkout.py, tests/func/test_data_cloud.py, tests/func/test_diff.py, tests/func/test_external_repo.py, tests/func/test_gc.py, tests/func/test_import.py, tests/func/test_remote.py, tests/func/test_remove.py, tests/func/test_repro.py, tests/func/test_run.py, tests/func/test_unprotect.py, tests/unit/remote/test_local.py
Fixes #3261
Fixes #2041
https://github.com/iterative/dvc.org/pull/1058
=> dvc: use protected mode by default

.github/PULL_REQUEST_TEMPLATE.md
Update PR template to be more succinct; add note about completion scripts.
Fixes? #2985
=> template: pr update

dvc/path_info.py, dvc/remote/http.py, tests/unit/test_path_info.py
Looks like disallowing URLs containing queries happened in b83564d (#2707), i.e. `dvc>0.66.1`... Not sure why. Seems fine to me to remove the `assert not p.query` restriction.
+ [x] add support for params
+ [x] add support for queries
* fixes #3424 `dvc import-url -v https://www.dropbox.com/?test data`
+ [x] add support for fragments
=> import-url: allow queries in URL

dvc/scm/git/tree.py, tests/unit/scm/test_git.py
We are currently using this [0] hack to work around the fact that item.name
is not always a basename. Even though `IndexObject` has it defined that way
[1], but `Submodule` - doesn't [2]. So using `item.name` might cause issues
such as [3], because GitPython doesn't pass name parameter when simply
going through objects [4]. In other places, when working specifically with
submodules, it sets `_name` attribute explicitly [5].
Note that we still don't walk into submodules when walking through a git
repo. Might want to reconsider that later as for now we haven't heard
anything about it from actual users.
Fixes #3481
[0] https://github.com/iterative/dvc/blob/0.90.0/dvc/scm/git/tree.py#L15
[1] https://github.com/gitpython-developers/GitPython/blob/3.1.0/git/objects/base.py#L170
[2] …
=> git: tree: use item.path instead of item.name

dvc/command/version.py, dvc/repo/__init__.py, tests/func/test_version.py
Fixes https://github.com/iterative/dvc/issues/3461
08cfa4f implements the fix when `.git` dir is removed. This PR tries to show information as much as possible, so, if `.git` dir is removed, it tries to open it as non-git dvc repository.
65184a5 implements additional output format if the cwd is a path to `dvc` repo. Examples:
1. When the repo is a subdir:
```sh
DVC version: 0.89.0+65184a
Python version: 3.6.6
Platform: Linux-5.5.2-arch1-1-x86_64-with-arch
Binary: False
Package: None
Repo: dvc (subdir), git
Filesystem type (workspace): ('tmpfs', 'tmpfs')
```
2. When the .git dir is broken, or cannot use `git` operations by dvc:
```sh
DVC version: 0.89.0+65184a
Python version: 3.6.6
Platform: …
```
=> version: fix bug when .git dir is removed, show more info regarding repo

dvc/stage.py
Fixes #3338
b07a982 fixes exception message, i.e. removes `stage working or file path` confusion. It's either of those two now.
=> import: fix output message on not-existing output directory

dvc/external_repo.py, tests/func/test_import.py
This is a good-enough fix for #3451. At the moment, local remote does not work at all and treats it like how it'd be if it was a remote dvc repo. It's not clear if we should support this at all (ref: #2756, #3378)
Fix #3451.
=> external_repo: do not try too hard to fix upstream

dvc/scm/git/__init__.py, tests/unit/scm/test_scm.py
=> git: quote filenames at remind_to_track

dvc/repo/__init__.py, tests/unit/repo/test_repo.py
Will skip modified graph checks on add, run and import. The aim is to
avoid collecting stages and building graph on these commands.
The skip_checks flag is aimed to be private, but let people use dvc on
big repos without monkey patching or writing yaml files themselves.
Closes #2671. For the time being.
=> dvc: add Repo(skip_checks) flag

dvc/remote/base.py, dvc/repo/fetch.py, tests/func/test_data_cloud.py
=> pull: support pulling git-only imports

dvc/repo/metrics/diff.py, tests/func/test_metrics.py, tests/unit/command/test_metrics.py
Partial fix for https://github.com/iterative/dvc/issues/3469
=> metrics: diff: handle deleted/new metric

dvc/dependency/param.py, setup.py, tests/unit/dependency/test_params.py
Currently `dvc run -p angles` is broken when you use it with `params.yaml`
that looks like this:
```
angles:
- 2
- 3
- 100
- 3.2
- 36.2
- 3.6
```
because we are incorrectly using `flatten` instead of simply using some
xpath-like library to access params that are specified.
=> params: use dpath for xpaths

dvc/path_info.py
=> path_info: HTTPURLInfo minor inheritance tweak

dvc/repo/diff.py, tests/func/test_diff.py
=> diff: analyse working tree when dirty

dvc/remote/gs.py, dvc/remote/s3.py, tests/func/test_s3.py, tests/unit/remote/test_remote.py
This resolves #3523. But, we should try not to make directory path objects if we really don't need to.
=> s3/gs: do not try to make directory on top level path

dvc/remote/azure.py, dvc/remote/base.py, dvc/remote/gdrive.py, dvc/remote/gs.py, dvc/remote/hdfs.py, dvc/remote/local.py, dvc/remote/oss.py, dvc/remote/s3.py, dvc/remote/ssh/__init__.py, tests/unit/remote/test_base.py
* During size estimation, status is displayed via `BAR_FMT_NOTOTAL` progress bar, as current # of estimated total remote size
* During threaded traverse, status is displayed via a single progress bar, as # of objects fetched out of the estimated total remote size
Will close #3526
=> remote: use progress bar when paginating

.travis.yml
Because `snapcraft push` hangs on cloud CI.
Imagine if `git push` did the same!
=> deploy: snap: timeout after 10 min

dvc/remote/base.py, tests/unit/remote/test_base.py
=> remote: short-circuit remote size estimation for large remotes

dvc/remote/base.py
`dvc push` and other commands will fail if they find a file that doesn't look like a cache file in the remote. The issue is that we've started using `list_cache_paths` for remote size estimation, which doesn't skip non-cache looking files. We should use `all()` instead.
Discord context: https://discordapp.com/channels/485586884165107732/485596304961962003/694454999492591657
=> remote: skip non-cache looking files when estimating remote size

dvc/remote/ssh/__init__.py
The sock attribute is set to a `paramiko.ProxyCommand` object
if 'ProxyCommand' exists in config to `None` other-wise
(which is the default option in `paramiko.client.SSHClient.connect()`).
FIXES #3560
No tests added, but passes all current tests.
=> remote: ADD sock attribute and pass it to SSHConnection constructor

dvc/command/data_sync.py, dvc/command/diff.py, dvc/command/repro.py, dvc/command/version.py
This fixes a few command help string outputs that were cut short because of a typo: 
```
COMMAND_HELP = "Substring one, "
"substring two."
```
This resulted in the CLI rendering only the first substring in the help section of the root `dvc` command.  
Since this is a small change that doesn't even change the CLI help messages, but rather fixes the existing ones, I haven't created an issue upfront.
I've walked through all the commands one by one, fixed the help strings where I noticed the bug.
=> CLI: Fixed cmds help strings

dvc/remote/base.py, dvc/remote/local.py, dvc/remote/ssh/__init__.py, dvc/repo/gc.py, tests/unit/remote/test_base.py
- `dvc gc -c` now uses the same behavior as `push`/`pull` when fetching checksums from a remote cache
- Progress bar is displayed using the estimated cache size as the total, and checksums are fetched in parallel by prefix
- This also reverts the estimation progress bar total changes as discussed in #3537 - we now just display the running estimated size without using the max limit as total 
Will close #3543
=> remote: use progress bar for remote cache query status during `dvc gc`

dvc/command/metrics.py, tests/unit/command/test_metrics.py
Makes it easier to use in shell scripts. E.g. `-z $(dvc metrics diff)`, which
has the same semantics as `git diff`. Also syncs up with the behaviour       
of `dvc diff`.                                                               
Fixes #3469
=> metrics: diff: don't print "No changes"

dvc/command/data_sync.py, dvc/command/metrics.py, dvc/command/status.py, dvc/repo/fetch.py, dvc/repo/metrics/show.py, dvc/repo/pull.py, dvc/repo/push.py, dvc/repo/status.py, tests/unit/command/test_data_sync.py, tests/unit/command/test_metrics.py, tests/unit/command/test_status.py
First steps for #1691
https://github.com/iterative/dvc.org/pull/1107
=> push/pull/status/metrics: add support for `--all-commits`

dvc/__init__.py, dvc/logger.py, dvc/main.py
The `captureWarnings()` function can be used to integrate logging with the warnings module (that's what GDrive dependency libraries use to write this ugly message below).
We first use this function, then logger is silenced but since it has `py.` prefix.
Eventually, we should probably stop using loggers for the user interface and all WARNINGS should not be silenced, but be visible when I do `-v`? But we need to discuss this, may be we can introduce `-vvv` to show third party logger messages eventually.
--------------------
=> CLI: redirect warnings to logger

setup.py
Fixes an issue with the recent `httplib2` update that is treating 308 http code as a redirect. 308's are used by several Google APIs (Drive, YouTube) for Resumable Uploads rather than Permanent Redirects. This causes: 
`httplib2.RedirectMissingLocation: Redirected but the response is missing a Location: header.`
**More context here:**
https://discordapp.com/channels/485586884165107732/485596304961962003/696086019593732106
**PyDrive2 fix is here:**
https://github.com/iterative/PyDrive2/pull/24
-------------
=> GDrive: use lates PyDrive2 version to fix large file uploads

dvc/remote/gdrive.py
=> GDrive: fix freezing on errors by improving granularity of retries

tests/remotes.py, tests/unit/remote/ssh/test_ssh.py, tests/unit/remote/test_azure.py, tests/unit/remote/test_base.py, tests/unit/remote/test_gdrive.py, tests/unit/remote/test_gs.py, tests/unit/remote/test_oss.py, tests/unit/remote/test_remote.py, tests/unit/remote/test_remote_dir.py, tests/unit/remote/test_s3.py
- update `tests/unit/remote` tests to use pytest style tests
- use the existing pytest dvc repo fixtures instead of None improperly mocked repo objects
Related to #3600
=> tests: convert remote unit tests to pytest

dvc/command/diff.py, dvc/command/init.py, dvc/output/base.py, dvc/scm/__init__.py, dvc/scm/base.py, scripts/completion/dvc.zsh
Followup to https://github.com/iterative/dvc/pull/3566#pullrequestreview-388346350
=> diff: update help output to match docs, et al.

dvc/command/metrics.py, tests/unit/command/test_metrics.py
Texttable will try to detect the column type automatically, which
results in a low precision of the float that it is showing. We need to
disable that auto-formatting and just use `str(val)` instead.
=> metrics: diff: fix float precision formatting

dvc/analytics.py
Shaves off ~0.2 seconds from any dvc command. E.g. for `$ dvc` it goes from ~0.7 to ~0.5sec for me. 
Related to #3475
=> analytics: collect runtime info in the worker

dvc/repo/params/show.py, tests/func/params/test_show.py
=> params: fix bug when collecting multiple params

dvc/command/params.py, tests/unit/command/test_params.py
=> params: diff: sort table

dvc/utils/fs.py, tests/func/test_unprotect.py, tests/unit/remote/test_local.py
=> remove: try deleting before trying to chmod

dvc/repo/add.py, dvc/repo/imp_url.py, dvc/repo/run.py, dvc/stage.py, dvc/utils/__init__.py, tests/unit/test_stage.py
Current logic is extremely complex and messy, hiding a lot of bugs
inside. There are pretty much only 2 scenarios for stage creation:
1) `dvc add/import/etc` when dvcfile is created beside the output file
2) `dvc run` when dvcfile is created at the place of execution
both are transparently affected by `--fname` flag. Since we've removed
`--cwd` complexity already, there is no reason to generalize stage path
resolution for those two scenarios.
This is also useful in preparation for `dvcfile` + `Stage` decoupling.
=> stage: resolve stage path before creating the stage

setup.py
This latest version of PyDrive2 fixes an issue for Google Drive remote management in machines with an old version of httplib2.
=> Updates latest version of PyDrive2

dvc/command/params.py, dvc/repo/params/diff.py, dvc/repo/params/show.py, dvc/utils/diff.py, tests/func/params/test_diff.py, tests/unit/command/test_params.py
Makes `dvc params diff` also show unchanged params.
https://github.com/iterative/dvc.org/pull/1152
=> params: diff: introduce --all

dvc/path_info.py, dvc/remote/base.py
Using it to load dirs takes around 50 sec compared to 0.4 with simple
`replace()`. Path objects are great, but not when you need lots of them.
Related to #3635
=> remote: don't use PathInfo.from_posix

dvc/ignore.py, dvc/repo/ls.py, dvc/repo/tree.py, dvc/scm/tree.py
This is useful as it is in `dvc ls` implementation, but this is also a
prerequisite for `RepoTree` that will combine git(workspace) files and
dvc files into one tree, allowing things like `dvc metrics` and       
`external_repo` to have a universal interface to access whatever      
file/dir they want without cumbersome git/dvc path detection.         
=> dvc: introduce DvcTree

dvc/repo/tree.py, tests/unit/repo/test_tree.py
=> tests: add some DvcTree unit tests

dvc/scm/git/__init__.py
+ [ ] (perhaps even in other places in a different issue)?
[![asciicast](https://asciinema.org/a/l8NoFwah4hVobyT7j6MTbfAJ5.svg)](https://asciinema.org/a/l8NoFwah4hVobyT7j6MTbfAJ5)
=> scm: git: clone: add progress

dvc/repo/brancher.py, dvc/repo/diff.py, dvc/scm/__init__.py, dvc/scm/base.py, tests/func/test_diff.py, tests/func/test_metrics.py
I am not sure if there is any other scm tools besides git going to be supported. 
If so, the error message"only supported for Git repositories" is not proper one,
fix #3605
=> metrics diff error message in --no-scm projects

dvc/output/base.py
=> output: use strings instead of PathInfo for performance reasons

dvc/dagascii.py, tests/func/test_repro.py
Fixes errors from latest flake8 master (`pycodestyle >= 2.6.0a1, < 2.7.0`)
```
[INFO] This may take a few minutes...
black....................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
tests/func/test_repro.py:1558:39: E741 ambiguous variable name 'l'
dvc/dagascii.py:98:41: E741 ambiguous variable name 'l'
beautysh.................................................................Passed
DVC pre-commit...........................................................Passed
- hook id: dvc-pre-commit
- duration: 16.59s
```
=> flake8: fix ambiguous var names

dvc/scm/git/__init__.py, tests/unit/scm/test_git.py
Current implementation doesn't work with directories, which results in
hard-to-debug bugs like #3561. The bug that made us walk through index
manually is now fixed in gitpython, so we can simply use `ls_files` from
now on. Added some tests to prevent this from happening in the future.
Fixes #3561
=> git: is_tracked: use ls_files instead of walking the index

dvc/dependency/__init__.py, dvc/dependency/base.py, dvc/dependency/gs.py, dvc/dependency/hdfs.py, dvc/dependency/http.py, dvc/dependency/https.py, dvc/dependency/local.py, dvc/dependency/param.py, dvc/dependency/repo.py, dvc/dependency/s3.py, dvc/dependency/ssh.py, dvc/repo/params/show.py, dvc/stage/__init__.py, dvc/stage/decorators.py, tests/unit/dependency/test_gs.py, tests/unit/dependency/test_hdfs.py, tests/unit/dependency/test_http.py, tests/unit/dependency/test_local.py, tests/unit/dependency/test_params.py, tests/unit/dependency/test_s3.py, tests/unit/dependency/test_ssh.py, tests/unit/test_stage.py
=> refactor: dvc/dependency class names unification

dvc/remote/base.py, dvc/remote/local.py, dvc/state.py
Should close #3635.
* LocalRemote now uses string paths instead of PathInfo in places where we expect to be dealing with a large number of paths (`status` and `LocalRemote.cache_exists`)
* `_process`/`upload`/`download` pipeline has been left alone for now - in the event that we are pushing or pulling enough files that using PathInfo's becomes noticeably slow, the expectation is already going to be that the operation will be slow, given that we will be uploading/downloading a lot of data.
=> remote: use string paths over PathInfo for performance reasons

dvc/repo/reproduce.py, tests/func/test_repro.py, tests/func/test_repro_multistage.py
Will close #3602.
from original issue:
> Looks like the issue is that for `--downstream`, we are reversing the DAG, and then traversing the reversed graph w/DFS pre-ordered search. In the example case, using pre-ordered search provides no guarantee that `step3` is only visited after `step2`.
> ...
> I think what we should be doing is traversing the reversed graph w/reverse post-ordered search, to ensure that dependencies are run in the correct order.
=> repo: use reverse post-order DFS in repro --downstream

dvc/dependency/__init__.py, dvc/dependency/gs.py, dvc/dependency/hdfs.py, dvc/dependency/http.py, dvc/dependency/local.py, dvc/dependency/s3.py, dvc/dependency/ssh.py, dvc/output/__init__.py, dvc/output/base.py, dvc/output/gs.py, dvc/output/hdfs.py, dvc/output/local.py, dvc/output/s3.py, dvc/output/ssh.py, dvc/stage/__init__.py, tests/func/test_repro.py, tests/func/test_run_single_stage.py, tests/func/test_stage.py, tests/unit/output/test_gs.py, tests/unit/output/test_hdfs.py, tests/unit/output/test_local.py, tests/unit/output/test_output.py, tests/unit/output/test_s3.py, tests/unit/output/test_ssh.py
=> refactor: dvc/output class names unification

dvc/schema.py, dvc/serialize.py, dvc/stage/loader.py, dvc/stage/params.py, tests/func/params/test_diff.py, tests/func/params/test_show.py, tests/func/test_repro_multistage.py, tests/func/test_run_multistage.py
Continuing from #3676 
Part of #1871 
This PR implements params support for pipeline file.
The pipeline file will have following format:
```yaml
params:
-  process.thresh
- process.bow
- params2.yaml:  # notice the format for custom params file
- lr
- train.epochs
```
=> dvc: implement params support for pipeline file

dvc/remote/ssh/connection.py
Will close #3482.
paramiko is loaded lazily, so the paramiko logger is not suppressed in `dvc/logger.py::disable_other_loggers()`. This leads to paramiko emitting expected error messages when we hit the max SFTP channel limit, even though it is not an error condition for DVC. The logger should just be suppressed when we load paramiko, since any actual SSH/SFTP errors will be caught and logged as DvcExceptions.
=> remote.ssh: suppress paramiko logging

setup.py
[WIP]. Attempt to relax upper constraints on the version of python-dateutil, to include 2.8.1 and 2.8.2. 
The original constraint was:
"python-dateutil<2.8.1,>=2.1",  # Consolidates azure-blob-storage and boto3
Requesting to do a CI run, see if new version constraint still works.
Fixes #3701
=> setup: relax python-dateutil pip version constraint to include v2.8.2.  #3701

dvc/config.py, dvc/data_cloud.py, dvc/remote/gdrive.py, tests/func/remote/test_gdrive.py, tests/unit/remote/test_gdrive.py
Address more checkboxes from the #2865.
**Specifically:**
Docs PR: https://github.com/iterative/dvc.org/pull/1192
----------
=> gdrive: fix multi-remote workflow, cont. cleanup

dvc/repo/__init__.py, dvc/repo/reproduce.py, dvc/repo/run.py, dvc/stage/__init__.py, dvc/stage/cache.py, dvc/utils/__init__.py, tests/func/test_gc.py, tests/func/test_repro.py, tests/unit/test_stage.py, tests/unit/utils/test_utils.py
This patch introduces `.dvc/cache/stages` that is used to store previous
runs and their results, which could then be reused later when we stumble
upon the same command with the same deps and outs.
Format of build cache entries is single-line json, which is readable by
humans and might also be used for lock files discussed in #1871.
Related to #1871
Local part of #1234
=> dvc: introduce local stage cache

dvc/serialize.py
`get_checksum()` recomputes the checksum which might not match the
pre-recorded one. `checksum` is the one that was `save()`ed during run
and it is the one that should be used in the lockfile.
=> serialize: use checksums that are already saved

dvc/stage/__init__.py, dvc/stage/exceptions.py, tests/func/test_run_single_stage.py
Unlike old `_check_missing_deps`, this also verifies that we are able to
save more complex dependencies such as parameters, where we not only
care about the config file, but also about the parameters in it.
Fixes #3707
=> run: try to save deps before running the command

dvc/dvcfile.py, tests/func/test_data_cloud.py, tests/func/test_pipeline.py, tests/func/test_repo.py, tests/func/test_stage.py, tests/func/test_status.py, tests/unit/utils/test_utils.py
=> dvc: rename pipelines.yaml -> dvc.yaml

dvc/serialize.py, dvc/utils/stage.py, tests/func/test_lockfile.py
The dump is no longer deterministic/dependent on the pipeline file,
but is sorted based on file names in outs, deps or params.
Also, the params inside each files are also sorted based on name.
However, the objects inside params are not sorted deterministically
as I think it's too much to sort that, and is not easy (considering
the types of objects it might hold, eg: lists, objects, etc).
This will also provide ordered dumps for Python3.5
Fixes #3696
=> dump: deterministic lockfile dump

dvc/progress.py, dvc/remote/base.py, dvc/remote/ssh/__init__.py, dvc/repo/add.py, dvc/repo/checkout.py, dvc/scm/git/__init__.py
+ was (top recording): `Cloning:    [elapsed<remaining]` => `Receiving:    | MBps [elapsed<remaining]` => `Receiving:    [elapsed]`
+ could be (lower recording): `Cloning:    [elapsed<remaining]` => `Cloning:    | Receiving | MBps [elapsed<remaining]` => `Cloning:    [elapsed]`
- fixes #3681
[![much asciinema such rec](https://asciinema.org/a/xLuYWs5szrSLw01uafAzFRLyI.svg)](https://asciinema.org/a/xLuYWs5szrSLw01uafAzFRLyI?speed=3)
[![much asciinema such rec](https://asciinema.org/a/znhzNFbYgvH0lE8w2h93Buvhl.svg)](https://asciinema.org/a/znhzNFbYgvH0lE8w2h93Buvhl?speed=3)
=> progress: add postfix info to avoid overwriting desc

dvc/command/base.py, dvc/command/daemon.py, dvc/lock.py, dvc/repo/__init__.py, dvc/state.py, dvc/updater.py, tests/func/test_diff.py, tests/func/test_lock.py
Moving
```
state
updater
updater.lock
lock
```
from `.dvc/` to `.dvc/tmp/`.
Fixes #3666
https://github.com/iterative/dvc.org/pull/1215
=> dvc: move temporary files to .dvc/tmp

dvc/command/data_sync.py, dvc/command/status.py, dvc/repo/status.py, tests/func/test_status.py, tests/unit/command/test_status.py
Fixes #3720 
> If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here. If the CLI API is changed, I have updated [tab completion scripts](https://github.com/iterative/dvc/tree/master/scripts/completion).
https://github.com/iterative/dvc.org/issues/1217
=> status: --recursive flag

dvc/command/diff.py, dvc/repo/diff.py, tests/func/test_diff.py, tests/unit/command/test_diff.py, tests/unit/test_plot.py
=> diff: make output consistent with other diff commands

dvc/output/base.py, dvc/repo/run.py, tests/func/test_run_single_stage.py
Fixes #3433
https://github.com/iterative/dvc.org/pull/1225
=> run: add to .gitignore on --no-exec

dvc/serialize.py, dvc/stage/__init__.py
On is_cached, we used to compare two dicts: one of current stage in memory
created by `run` and one that's already written to the file.
As `outs` and `dicts` are lists (which is generate by `dumpd`), the
comparison was dependent on the order of outs and deps.
So, the `run` before and now, can be in different order and would fail the comparisons.
Also, given that we can compare without order, we can make pipeline files sorted by outs and deps.
Plus, in the post-pipeline-file world, we don't even need `is_cached`. We could just throw
`DuplicateStage` or `OutputDuplicationError`. It's convenient of course, to be able to `dvc run`
same command many times but, I'm not sure if it's worth the hassle of having `is_cached` for just that.
Thank you for the contribution - we'll try to review it as …
=> Make comparisons in is_cached independent of order

dvc/stage/cache.py, tests/func/test_repro.py
To be consistent with how git does it (e.g. objects/branches/refs) as well as with
future cache structure where we plan on adding `dirs`/`files`/`objects`
subdirs in the future.
=> cache: rename `.dvc/cache/run` to `.dvc/cache/runs`

scripts/completion/dvc.zsh
=> plot: completion for zsh

dvc/command/run.py, dvc/exceptions.py, dvc/main.py, dvc/stage/__init__.py, dvc/stage/exceptions.py
=> ui: simplify/shorten error messages

dvc/command/run.py, tests/unit/command/test_run.py
https://github.com/iterative/dvc.org/pull/1229
=> run: remove deprecated -y|--yes

dvc/command/run.py, dvc/repo/run.py, tests/func/test_add.py, tests/func/test_api.py, tests/func/test_checkout.py, tests/func/test_commit.py, tests/func/test_data_cloud.py, tests/func/test_dvcfile.py, tests/func/test_pipeline.py, tests/func/test_repro.py, tests/func/test_repro_multistage.py, tests/func/test_run_multistage.py, tests/func/test_run_single_stage.py
Adding hidden `--single-stage` to simplify the test migration.
=> run: use multistage dvcfiles by default

.travis.yml, snap/snapcraft.yaml
=> Snap version

dvc/command/checkout.py, dvc/command/data_sync.py, dvc/repo/pull.py, dvc/utils/humanize.py, tests/func/test_checkout.py, tests/func/test_data_cloud.py, tests/unit/command/test_checkout.py, tests/unit/command/test_data_sync.py, tests/unit/utils/test_humanize.py
Closes #3485
1. 
```sh
$ dvc pull
M	bar
A	foo
1 file added, 1 file modified and 2 files fetched
```
2.
```sh
$ dvc push
2 files pushed
```
3.
```sh
$ dvc fetch
1 file fetched
```
=> pull/fetch/push: add stats

dvc/remote/gdrive.py, setup.py
- > Let there be no more in-memory downloads. Let the files stream until the hard drives overfloweth. Let RAM be ignored, and let us answer the call to progress.
- part of #2865
+ related #3408
=> gdrive: download: stream & add progress

dvc/repo/plot/template.py, tests/func/test_plot.py
=> plot: check field exists

dvc/command/base.py, dvc/command/pipeline.py, tests/func/test_repro.py, tests/unit/command/test_repro.py
Note: This does not change default for `pipeline` as
it cannot show multiple DAGs at the same time. If we
are able to show multiple DAGs, we can just default to
`dvc.yaml`.
https://github.com/iterative/dvc.org/issues/1173
=> repro: use dvc.yaml by default

dvc/command/plot.py
Since `plot` allows to plot non-continuous metrics too (eg confusion matrix) it seems to me that we should not include this word (continuous) in help messages to avoid confusing users.
=> plot: fix help messages

dvc/command/data_sync.py, dvc/data_cloud.py, dvc/repo/__init__.py, dvc/repo/fetch.py, dvc/repo/pull.py, dvc/repo/push.py, dvc/stage/cache.py, tests/func/test_data_cloud.py, tests/unit/command/test_data_sync.py
This is the most simple (aka dumb) implementation for this
functionality that is needed to unblock CICD development.
`--run-cache` flags are hidden for now.
This will also need `walk_files` in each remote implementation,
which will be coming separately.
=> push/pull: naively transfer run cache

dvc/repo/__init__.py, dvc/stage/__init__.py, dvc/stage/loader.py
These messages all correpond to expected behaviour, so there is no need
to polute the output with unnecessary warnings.
=> stage: hide unwanted warnings

dvc/command/update.py, dvc/repo/update.py, tests/func/test_repro.py, tests/func/test_update.py, tests/unit/command/test_update.py
Fixes #3511 
> * [ ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here. If the CLI API is changed, I have updated [tab completion scripts](https://github.com/iterative/dvc/tree/master/scripts/completion).
See https://github.com/iterative/dvc.org/issues/1259
=> update: --recursive flag

dvc/data_cloud.py, dvc/repo/__init__.py, dvc/repo/fetch.py, dvc/repo/push.py, dvc/stage/cache.py
Ideally run cache should be a part of NamedCache and transferred as a regular cache through push/pull, but that requires a refactor, so for now we keep doing that manually to unblock CICD.
Fixes #1234
=> push/pull: properly collect run cache

dvc/command/remote.py, dvc/config.py, tests/func/test_config.py, tests/func/test_remote.py
=> Dvc remote default in list validation 

dvc/command/diff.py, dvc/command/metrics.py, dvc/command/params.py, dvc/utils/diff.py, setup.py, tests/unit/command/test_diff.py, tests/unit/command/test_metrics.py, tests/unit/command/test_params.py
Via `--show-md` on `diff`s.
https://github.com/iterative/dvc.org/pull/1266
The `dvc params diff` and similar commands would output header centered. With this change, it will be left-aligned.
Previously:
```sh
$ dvc params diff
Path           Param        Old     New
params.yaml   lr               None   0.0041
params.yaml   process.bow      None   15000
params.yaml   process.thresh   None   0.98
params.yaml   train.epochs     None   70
params.yaml   train.layers     None   9
```
Now:
```sh
$ dvc params diff
Path         Param           Old    New
params.yaml  lr              None   0.0041
params.yaml  process.bow     None   15000
params.yaml  process.thresh  None   0.98
params.yaml  train.epochs    None   70 …
```
=> params/metrics: diff: implement tabulated markdown output (--show-md)

dvc/repo/run.py, dvc/stage/__init__.py, dvc/stage/exceptions.py, tests/func/test_repro.py, tests/func/test_run_multistage.py
except hyphen and underscore
Closes https://github.com/iterative/dvc/issues/3700
=> pipeline file: disallow punctuation characters in stage name

dvc/config.py, dvc/remote/s3.py, tests/unit/remote/test_s3.py
* [X ] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.
* [(will do) ] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here. If the CLI API is changed, I have updated [tab completion scripts](https://github.com/iterative/dvc/tree/master/scripts/completion).
* [X ] ❌ I will check DeepSource, CodeClimate, and other sanity checks below. (We consider them recommendatory and don't expect everything to be addressed. Please fix things that actually improve code or fix bugs.)
---
I added an `sse_kms_key_id` parameter to the S3 …
=> Added S3 SSEKMSKeyId config option

dvc/stage/cache.py, tests/unit/test_stage.py
Currently we only restore `--outs`, but `--outs-no-cache` are also
useful, especially when they are metrics files
(`-M|--metrics-no-cache`). So this PR makes run-cache save uncached
files to our cache and also tries to checkout them back during the
`restore` phase.
=> run-cache: support uncached files

tests/dir_helpers.py, tests/func/test_api.py, tests/func/test_data_cloud.py, tests/func/test_external_repo.py, tests/func/test_gc.py, tests/func/test_get.py, tests/func/test_import.py, tests/func/test_remote.py
Fixes #2888, related to #3416 
The problem:
In #3416 I could reproduce user problems in script, but it seemed that I am unable to write a test for it. 
The problem turned out to be related to the fact that `erepo_dir` has been setting its default remote to be its cache. Due to that, I have been indirectly using cache "read only mode" optimization, while using remote. Because it is the second time i stumble upon this issue (#2888) I decided to fix it.
This issue introduces "setup_remote" fixture, which is intended to be default way to set up the remote for particular `Repo` instance.
=> tests: abstract remote setup to fixture

dvc/command/plot.py, dvc/repo/plot/data.py
=> plot: update some output strings

dvc/repo/plot/__init__.py
Credits to @fabiosantoscode for noticing!
=> plot: add doctype at the beggining of html embedding

tests/func/test_data_cloud.py
Fixes #3570.
As far as I can tell there is nothing wrong with the test as written. I think the issue is related to inodes sometimes being re-used when we delete files in between `pull` calls.
From the logs, inode `2307858` is reused after the file deletion calls. Note that the test failure is due to `foo` not being re-fetched during the second `pull` call after the deletions.
```
...
DEBUG    dvc.utils.fs:fs.py:32 Path 'new_dir/bar' inode '2307858'
...'
DEBUG    dvc.utils.fs:fs.py:32 Path '.dvc/cache/37/b51d194a7513e45b56f6524f2d51f2' inode '2307858'
...
DEBUG    dvc.utils.fs:fs.py:133 Removing 'foo'
DEBUG    dvc.utils.fs:fs.py:133 Removing 'new_dir'
DEBUG    dvc.utils.fs:fs.py:133 Removing …
```
=> tests: mark test_data_cloud::test_pull_git_imports as flaky

dvc/repo/diff.py, dvc/repo/metrics/diff.py, dvc/repo/params/diff.py, dvc/scm/git/__init__.py, tests/dir_helpers.py, tests/func/metrics/test_diff.py, tests/func/params/test_diff.py, tests/func/test_diff.py, tests/unit/scm/test_git.py
`git diff` doesn't throw errors, so we could do the same.
Fixes #3398
=> diff: handle repo with no commits

dvc/serialize.py, dvc/stage/__init__.py, dvc/stage/decorators.py, dvc/stage/exceptions.py, dvc/stage/imports.py, dvc/stage/loader.py, dvc/stage/run.py, dvc/stage/utils.py, tests/func/test_repro.py, tests/func/test_run_single_stage.py, tests/func/test_stage.py, tests/unit/test_stage.py
This PR:
* Extracts some functions from `Stage` to `utils.py`.
* Change name of functions: makes name of the most of the functions to not have `_` prefix 
(at least those that are used outside of the `Stage` class).
* `run` and `import` related functions are on `run.py` and `imports.py` respectively.
* merge some redundant functions (eg: `changed() and _changed()`).
This keeps the bugs and most of the codebases intact, just a small refactor that moves things around.
**TIP:** Look at each commits, that way it might be easy.
Apart from a few methods (eg: `status`, `changed`, etc.), I have splitted the methods from stage on
the basis of "if it modifies outs/deps/cmd". If it does, it stays, otherwise it's extracted …
=> stage: moving things around, refactor

dvc/output/__init__.py, dvc/schema.py, dvc/serialize.py, dvc/stage/loader.py, tests/dir_helpers.py, tests/func/test_lockfile.py, tests/func/test_run_multistage.py
* ~~Fix schema~~ (technical debt, will be handled separately)
* ~~Refactor constant string literals~~ (technical debt will be handled separately)
The dvc.yaml had following kinds of keys for ech stages:
```yaml
evaluate:
cmd: python src/evaluate.py model.pkl data/features auc.metric
deps:
- data/features
- model.pkl
- src/evaluate.py
metrics_no_cache:
- auc.metric
```
This will be changed to:
```yaml
evaluate:
cmd: python src/evaluate.py model.pkl data/features auc.metric
deps:
- data/features
- model.pkl
- src/evaluate.py
metrics:
- auc.metric:
cache: false
```
Similarly, `persist_outs` will have `persist: true` and `persist_no_cache` will have `cache: false and persist: true`. And, this will only happen if …
=> dvc.yaml: remove outs_no_cache, etc. keys, merge inside metrics/outs

dvc/output/base.py, dvc/repo/__init__.py, dvc/repo/tree.py, tests/unit/repo/test_repo_tree.py, tests/unit/repo/test_tree.py
* `RepoTree` now supports all `BaseTree` methods
* Adds support for fetching or streaming DVC outs directly from remote on `RepoTree`/`DvcTree.open()`.
* If an out is already in local cache, it will always be opened from cache.
* For outs which are not in local cache, if `DvcTree` was initialized with `fetch=True` or `stream=True`, the out will be fetched or streamed, otherwise an error will be raised
* `Repo.open_by_relpath()` now uses `RepoTree.open()`
* `RepoTree`/`DvcTree.walk()` now support walking dir contents for dir outs
* If tree was initialized with `fetch=True` or `stream=True`, tree will pull dir cache for dir outs on `walk` when needed
* Otherwise, dir contents will not be walked (same as existing …
=> repo: Support streaming and pulling files on `RepoTree/DvcTree.open()`

dvc/ignore.py, dvc/scm/git/tree.py, dvc/scm/tree.py, dvc/utils/__init__.py, dvc/utils/fs.py, tests/unit/utils/test_fs.py
Miscellaneous improvements to GitTree and utils that will be needed for cache/repo tree changes.
Related to #3811.
=> utils: support use of (GitTree) tree file objects in utils

dvc/command/remote.py, tests/func/test_remote.py
fixed #3599
1. add new command `dvc remote rename <old> <new>`.
2. add tests for this new command.
https://github.com/iterative/dvc.org/issues/1301
=> Add a new rename command 

dvc/cli.py, dvc/logger.py, dvc/main.py, dvc/state.py, tests/unit/test_logger.py
- fixes #2332
- related (maybe fixes?) #2329
> [...] if you are convinced that you need custom levels, great care should be exercised when doing this, and it is possibly *a very bad idea to define custom levels if you are developing a library* [...] if multiple library authors all define their own custom levels [...]
-- https://docs.python.org/3/howto/logging.html#custom-levels
> We already do `disable_other_loggers()` so muhuhu hahaha.
-- @casperdcl
```bash
dvc (logging-counts)$ dvc status -v | wc -l
34
dvc (logging-counts)$ python -m dvc status -v | wc -l
20
```
=> logger: add trace, count --verbose/--quiet

dvc/command/repro.py
=> repro: fix help message for default target

dvc/output/base.py, dvc/remote/base.py, dvc/remote/local.py, dvc/repo/__init__.py, dvc/repo/tree.py, tests/func/test_api.py, tests/func/test_tree.py, tests/unit/repo/test_repo_tree.py, tests/unit/repo/test_tree.py
Related to #3811.
added support for:
* Granular support for `RepoTree`/`DvcTree.open()` (Will close #3541)
* Files inside DVC directory outs can be opened by any function using `RepoTree.open()` (`Repo.open_by_relpath()`, `api.open()`)
* If file is not cached, it will only be opened if tree was initialized with `fetch=True` or `stream=True`
* RepoTree paths can be saved directly to remote (i.e. local cache)
ex:
```py
tree = RepoTree(..., fetch=True)  # stream or fetch must be set to save DVC outs properly
cache = repo.cache.local
cache.save(path_in_tree, None, tree=tree)
```
For saving tree paths, rather than requiring the call to `cache.save_info(...)` to get a destination checksum, for tree paths the checksum …
=> remote: support saving RepoTree objects directly to cache

dvc/output/base.py, tests/func/test_add.py
Fixes: #3678
When file has been already tracked under git, OutputAlreadyTrackedError gets raised.
This commits add git command suggestions to help user to stop tracking file from git,
so in future commits they can use DVC for the file.
=> (OutputAlreadyTrackedError): Add git suggestions to stop tracking files

dvc/command/plots.py
=> plots: point template help info to manual

dvc/stage/__init__.py, tests/func/test_add.py, tests/func/test_commit.py, tests/unit/stage/test_stage.py
This way it won't be included into produced dvcfiles (we don't need it
for `dvc add`).
=> dvc: add: set top level md5 to None

dvc/dependency/repo.py, dvc/external_repo.py, dvc/istextfile.py, dvc/remote/base.py, dvc/remote/local.py, dvc/repo/__init__.py, dvc/repo/fetch.py, dvc/repo/get.py, dvc/repo/ls.py, dvc/repo/tree.py, dvc/utils/__init__.py, tests/func/test_external_repo.py, tests/func/test_get.py
Related to #3811.
Will fix #3611.
Changes:
* erepo: use GitTree instead of `git checkout` for cloned repos (unless dvcx `for_write=True`)
* erepo: use `RepoTree`/`cache.save()` for fetching external DVC+ git files
* erepo: remove `pull_to`
* RepoDependency: use `erepo.fetch_external() -> cache.checkout` with host repo cache
* get: use `erepo.fetch_external() -> cache.checkout()` with erepo tmpdir cache
* `ls`: use RepoTree
=> external_repo: use RepoTree for fetch/import/get

tests/unit/remote/test_azure.py
Quick followup test for https://github.com/iterative/dvc/pull/3852
=> tests: unit: azure: add etag test

README.rst, scripts/ci/before_install.sh
- fixes #3860
Also just rolled back last `stable` to match the new scheme:
```yaml
channels:
latest/stable:    0.94.0              2020-05-23 (388) 104MB classic
latest/candidate: ↑
latest/beta:      1.0.0a4             2020-05-23 (441) 105MB classic
latest/edge:      1.0.0a4-3-g5ab948f8 2020-05-23 (446) 105MB classic
```
=> snap: release non-stable-semver tags to beta

dvc/dvcfile.py, dvc/output/base.py, dvc/repo/reproduce.py, dvc/repo/run.py, dvc/stage/__init__.py, dvc/stage/imports.py, dvc/stage/run.py, tests/unit/stage/test_run.py
```sh
➜ dvc run --name "generate-foo" --outs foo \
"echo 'foo0\nfoo1' > foo"
Running callback stage 'dvc.yaml:generate-foo' with command:
echo 'foo0\nfoo1' > foo
Creating 'dvc.yaml'
Adding stage 'generate-foo' to 'dvc.yaml'
Generating lock file 'dvc.lock'
git add dvc.lock dvc.yaml
➜ dvc run --name split-into-two --deps foo  \
--outs foo0 \
--outs-no-cache foo1 \
"split -dn2 -a1 foo foo"
Running stage 'dvc.yaml:split-into-two' with command:
split -dn2 -a1 foo foo
Adding stage 'split-into-two' to 'dvc.yaml'
Updating lock file 'dvc.lock'
git add dvc.lock dvc.yaml
➜ dvc run -n copy-foo-bar -d foo -o bar "cp foo bar"
Running stage …
```
=> log: reduce log, make it readable/easier

dvc/state.py, tests/func/test_data_cloud.py
PR forces State to always use `WorkingTree` rather than `repo.tree` (since state needs to be able to look up local cache files even if `repo.tree` is a brancher `GitTree`). Once Remote is refactored to use trees, we should also consider making State owned by the local cache and not Repo, so that state always uses the local cache working tree.
Closes #3812, closes #3857.
=> state: always use working trees

dvc/command/pipeline.py, dvc/exceptions.py, dvc/repo/__init__.py, dvc/repo/checkout.py, dvc/repo/commit.py, dvc/repo/lock.py, dvc/repo/remove.py, dvc/repo/reproduce.py, dvc/stage/__init__.py, dvc/stage/exceptions.py, dvc/stage/loader.py, dvc/utils/__init__.py, tests/func/test_checkout.py, tests/func/test_commit.py, tests/func/test_data_cloud.py, tests/func/test_dvcfile.py, tests/func/test_pipeline.py, tests/func/test_repo.py, tests/func/test_repro.py, tests/func/test_repro_multistage.py, tests/func/test_stage.py, tests/func/test_status.py, tests/unit/repo/test_repo.py, tests/unit/utils/test_utils.py
This PR enables users to run/work with stage via their name if they are in dvc.yaml file.
```sh
$ dvc commit stage_name
```
There is a caveat though: what if the output and the stage name clashes?
Currently, there is no way to specify it is an output, but, there is way to indicate it's a stage via:
```sh
$ dvc commit :stage_name  # or,
$ dvc commit dvc.yaml:stage_name
```
The only good workaround is:
```sh
$ dvc checkout ./output-filename-that-clashes-with-stage-name
```
=> addressing: allow stage name addressing without ":"

dvc/ignore.py, tests/func/test_tree.py
* `CleanTree.exists()`/`isfile()`/`isdir()`/etc now work as expected.
* For a given `path` relative to tree root, CleanTree will now check that `path` and its parents are valid and not in our DVC ignores.
Will close #3444.
=> ignore: CleanTree should always check ignores, not just for walk()

dvc/repo/run.py, tests/func/metrics/conftest.py, tests/func/metrics/test_diff.py, tests/func/metrics/test_show.py, tests/func/params/test_diff.py, tests/func/params/test_show.py, tests/func/plots/__init__.py, tests/func/plots/conftest.py, tests/func/plots/test_diff.py, tests/func/plots/test_plots.py, tests/func/test_ls.py, tests/func/test_remote.py, tests/func/test_repro.py, tests/func/test_run_multistage.py, tests/func/test_run_single_stage.py
Previously, `run` used to show misleading `MissingOutputError` when no command was specified.
=> run: raise error when command is not specified

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Check https://github.com/skshetry/dvc/issues/new/choose to see it in action.
* change bug issue template
* auto add labels
* use emojis
* add link to Discord chat
=> modify issue template

dvc/ignore.py, dvc/repo/__init__.py, dvc/repo/brancher.py, tests/func/metrics/test_show.py
Brancher should only yield revisions that contain `repo.repo_root`.
If DVC repo was initialized with `subdir=True`, the DVC repo root directory may not exist at all in git revisions prior to when DVC was initialized. This will cause an exception when we try to `walk(repo.repo_root)` in `_collect_stages()`, since the walked directory doesn't exist.
Regular (non-subdir) DVC repos are not affected by this issue. In this case, even if a yielded git revision is from before DVC was initialized, the end result is that we walk the root git repo directory and do not find any DVC stages in that revision.
Fixes #3821.
=> brancher: only yield git revisions that contain repo_root

dvc/command/plots.py, tests/unit/command/test_plots.py
=> plots: replace --show-json with --show-vega

dvc/remote/ssh/connection.py
I noticed that we were going >1024 on file descriptors. And, as select() does not work with >1024 file descriptors, using `poll` might fix the problem. 
Though, it does not support Windows. So, I have used a higher level API [`selectors`](https://docs.python.org/3.7/library/selectors.html) that will use whatever is most efficient for the current platform. Though, due to lack of `*poll()` in Windows, it will use `select` there.
Closes #3888
=> use `selectors` instead of `select.select()`

dvc/command/plots.py, dvc/output/base.py, dvc/repo/__init__.py, dvc/repo/plots/__init__.py, dvc/repo/plots/show.py, dvc/repo/plots/template.py, dvc/schema.py, tests/func/plots/test_diff.py, tests/func/plots/test_plots.py, tests/unit/command/test_plots.py
Along the way:
- several targets in `dvc plots diff` now work
- fixed inconsistency between CLI and Repo API  (`x` vs `x_field`, `xlab` and `x_title`) 
- fixes some wrong error handling
**NOTE:** several plots per plot data file not supported here. There are at least two design decisions need to be made: how do they interact with `dvc plots add/modify/delete` and how do we collect them when they are inconsistent.
Collecting inconsistent props from different revisions for now solved by using props from first rev mentioned and issuing a warning.
=> Add plots props and `plots modify` params

dvc/command/gc.py, dvc/repo/brancher.py, dvc/repo/diff.py, dvc/repo/metrics/show.py, dvc/repo/params/show.py, dvc/repo/plots/data.py, dvc/repo/plots/diff.py, dvc/repo/plots/show.py, scripts/completion/dvc.zsh, tests/func/metrics/test_show.py, tests/func/params/test_show.py, tests/func/plots/test_diff.py, tests/func/plots/test_plots.py, tests/unit/repo/plots/test_diff.py, tests/unit/repo/test_repo_tree.py, tests/unit/repo/test_tree.py
Fixes #3892
There are only two occurrences of `working tree` in docs:
```
./content/docs/tutorials/pipelines.md:working tree:                                                                     
./content/docs/tutorials/deep/sharing-data.md:references in the <abbr>workspace</abbr> (in the _working tree_ of the Git
```
neither of those need to be changed right now.
=> dvc: rename "working tree" to "workspace"

dvc/command/remove.py, dvc/command/run.py, dvc/dvcfile.py, dvc/repo/remove.py, dvc/repo/run.py, dvc/stage/__init__.py, tests/func/test_dvcfile.py, tests/func/test_gc.py, tests/func/test_remove.py, tests/func/test_repro.py, tests/func/test_run_multistage.py, tests/func/test_run_single_stage.py, tests/func/test_stage.py, tests/unit/command/test_run.py
This PR adds support for removing stage entry for pipeline files and allows overwriting stage entry during `run`.
Backward Incompatible changes:
1. Changes `--overwrite-dvcfile` flag to `--overwrite` so that it makes sense for both kind of files.
2. Removes `--outs` flag from `dvc remove`.
3. `run` will always raise an exception if there already exists a stage, previously it'd prompt to overwrite.
PR will come shortly.
Closes https://github.com/iterative/dvc/issues/3317
=> Implement removing of the stage

dvc/stage/run.py, tests/func/test_repro.py, tests/func/test_repro_multistage.py
Previously, the stage would not rerun if the deps/outs are cached
even if the cmd has changed.
Versions affected: >0.93.0
Fixes #3918
=> bugfix: rerun stage when command is changed

dvc/dvcfile.py, dvc/exceptions.py, dvc/serialize.py, dvc/stage/cache.py, dvc/utils/yaml.py, tests/func/test_add.py, tests/func/test_checkout.py, tests/func/test_commit.py, tests/func/test_data_cloud.py, tests/func/test_dvcfile.py, tests/func/test_lockfile.py, tests/func/test_move.py, tests/func/test_repro.py, tests/func/test_repro_multistage.py, tests/func/test_run_single_stage.py, tests/func/test_stage.py
=> refactor: rename utils.stage to utils.yaml

dvc/repo/__init__.py
We used to go through all stages when updating outs.
=> Fix quadratic behavior in Repo._collect_stages()

dvc/command/add.py, dvc/command/run.py, dvc/repo/add.py, dvc/stage/__init__.py, dvc/stage/cache.py, dvc/stage/exceptions.py, dvc/stage/utils.py, scripts/completion/dvc.bash, scripts/completion/dvc.zsh, tests/func/test_add.py, tests/func/test_gc.py, tests/func/test_get.py, tests/func/test_repro.py, tests/unit/command/test_run.py, tests/unit/stage/test_stage.py
Fixes #1545
Related to #3920
https://github.com/iterative/dvc.org/pull/1387
=> dvc: require `--external` for external outputs

dvc/exceptions.py, dvc/repo/plots/show.py, tests/func/plots/test_plots.py
Consistent with `dvc metrics show/diff` behaviour.
Fixes #3925
=> plots: fix error when there are no plots in repo

tests/func/test_data_cloud.py, tests/remotes.py
=> tests: gdrive: don't cache url

scripts/ci/install.sh, setup.py
This one doesn't allow us to release new pre-releases, because pypi
forbids that:
https://travis-ci.com/github/iterative/dvc/jobs/343343967#L2447
Let's install it separately for now, until there is a new official
mock-ssh-server release.
=> tests: move mock-ssh-server git dependency

dvc/command/run.py, dvc/output/base.py, dvc/output/local.py, tests/func/test_run_single_stage.py
=> Unify metrics behavior with dirs

dvc/remote/gdrive.py, dvc/remote/gs.py
Fixes gdrive + gs build errors introduced by #3946
(https://travis-ci.com/github/iterative/dvc/builds/169685153)
=> remote: fix build errors

dvc/remote/gdrive.py, tests/remotes.py
Fixes build failure from https://travis-ci.com/github/iterative/dvc/builds/169745221
=> remote: fix remaining gdrive build issues

snap/snapcraft.yaml
- related: #3879 (`0.x` branch)
- fixes #3514
- reference https://github.com/snapcore/snapcraft/blob/19393ef36cd773a28131cec10cc0bfb3bf9c7e77/tools/snapcraft-override-build.sh#L18
=> snap: restrict site-package checks

.travis.yml, scripts/ci/before_install.sh, snap/snapcraft.yaml
+ allows `snap refresh --channel=stable/3878 dvc`
* after 30 days (or manual channel closure) will automatically move back to `stable`
- related: #3878 (`1.x` branch)
- fixes #3514
- reference https://github.com/snapcore/snapcraft/blob/19393ef36cd773a28131cec10cc0bfb3bf9c7e77/tools/snapcraft-override-build.sh#L18
=> snap: 0.x: prevent user site package conflicts

dvc/stage/cache.py, tests/unit/stage/test_cache.py
This is more or less a dead code. The params and deps loaded from the stage cache are not used anywhere. I changed the interface when refactoring but missed on changing it here, but as it is an "unused" stuff, it didnot affect run-cache at all. Anyway, I have fixed it, and even though it's an internal API, I have added a test so that we can catch this soon. 
=> Fix loading of params from run cache

dvc/stage/loader.py, dvc/stage/utils.py, tests/unit/stage/test_loader_pipeline_file.py, tests/unit/stage/test_utils.py
=> tests: StageLoader for Pipeline file stages

dvc/dependency/__init__.py, dvc/dvcfile.py, dvc/stage/cache.py, dvc/stage/serialize.py, dvc/stage/utils.py, tests/func/test_lockfile.py, tests/func/test_repro_multistage.py, tests/unit/stage/test_loader_pipeline_file.py, tests/unit/stage/test_serialize_pipeline_file.py
This PR adds sorting for params keys as well. Before, it was only getting sorted for lockfile.
Rest are tests and a bit of refactoring that does not change anything.
Part of #3693
=> tests: serialize pipeline file

dvc/stage/serialize.py, setup.cfg, tests/unit/stage/test_serialize_pipeline_lock.py, tests/unit/stage/test_stage.py
=> tests serializing of stage to lockfile

dvc/stage/__init__.py, dvc/stage/imports.py, dvc/stage/run.py
=> stage: don't consider stage as cached if checksum/cmd changed

.travis.yml, scripts/build_snap.sh, scripts/ci/before_install.sh, snap/snapcraft.yaml
=> snap: build fixes

dvc/command/data_sync.py, dvc/command/status.py, tests/unit/command/test_status.py
Fixes #1406
https://github.com/iterative/dvc.org/pull/1415
=> status: introduce --show-json

dvc/command/plots.py, dvc/output/base.py, dvc/repo/plots/__init__.py, dvc/repo/plots/data.py, dvc/schema.py, tests/func/plots/test_plots.py, tests/unit/command/test_plots.py
Fixes #3996
Added suggestions to https://github.com/iterative/dvc.org/pull/1382/files
=> plots: rename --no-csv-header to --no-header

dvc/repo/plots/__init__.py, tests/func/plots/__init__.py, tests/func/plots/test_plots.py
=> plots modify: complain if template does not exist

dvc/repo/tree.py, tests/func/metrics/test_diff.py, tests/func/params/test_diff.py, tests/func/plots/test_diff.py, tests/func/test_api.py, tests/func/test_update.py, tests/unit/repo/test_repo_tree.py, tests/unit/repo/test_tree.py
Currently `RepoTree.open` will throw FileNotFoundError if you have a
file that is tracked by dvc, but which has no md5 or a cache for which
is missing, even though you have the file itself in your workspace.
This corresponds very nicely to the `--no-commit` or `--no-exec`
scenario, where you might not want to commit your artifacts to cache
just yet.
Fixes #3974
=> RepoTree: work with dirty repos

dvc/repo/fetch.py, dvc/repo/push.py, dvc/repo/reproduce.py, dvc/stage/cache.py, tests/func/test_run_cache.py
Also, I tried to fix #4016, and also fix discrepancies in push/fetch counts.
=> tests: cover run cache with functional tests

dvc/ignore.py, dvc/remote/local.py, dvc/repo/__init__.py, dvc/state.py, tests/func/test_ignore.py, tests/func/test_state.py
Related to #3882
* Local cache/remote always uses its own working tree
* local cache no longer affected by whether `repo.tree` is working or git tree
* State is tied to the local cache working tree rather than `repo.tree`
* CleanTree now ignores paths outside of the DVC tree/repo root
* previously it was used interchangeably with working tree, and was expected to return true for paths outside of the DVC repo root in cases where local cache directory was moved or on a different logical drive
* local cache working tree should now be used for handling all cache paths, not the DVC repo cleantree instance
=> remote: use separate working tree instance for local cache

dvc/cache.py, dvc/dependency/repo.py, dvc/external_repo.py, dvc/output/base.py, dvc/remote/__init__.py, dvc/remote/azure.py, dvc/remote/base.py, dvc/remote/gdrive.py, dvc/remote/gs.py, dvc/remote/hdfs.py, dvc/remote/http.py, dvc/remote/local.py, dvc/remote/s3.py, dvc/remote/ssh/__init__.py, tests/func/remote/test_index.py, tests/func/test_add.py, tests/func/test_checkout.py, tests/func/test_data_cloud.py, tests/func/test_remote.py, tests/func/test_s3.py, tests/func/test_tree.py, tests/unit/output/test_local.py, tests/unit/remote/test_azure.py, tests/unit/remote/test_base.py, tests/unit/remote/test_local.py
Related to #3882
* Supported cloud types now have distinct remote and cache classes (i.e. `S3Remote`, `S3Cache`, `LocalRemote`, `LocalCache`, etc)
* All `get_checksum` related functions are now moved into remote trees
* `cache.save()` now takes an explicit `tree` parameter
* When `tree` is `remote.tree`, save is done via `move()` + `link()`
* For all other trees, save is done by copying object from `tree` into `remote.tree`
=> remote: separate cloud remote and cloud cache classes

tests/func/test_dvcfile.py, tests/unit/test_dvcfile.py
Part of #3693. Added a few unittests, and some fixes along the way for functional tests.
Noticed one test was duplicated, hence removed.
=> tests: unittests for dvcfile and some small fixes

dvc/repo/tree.py, tests/func/test_get.py
The relative path for external git directory was computed relative to
the root of the repo itself, which created a relative path which is
current working directory. So, all of the contents of the erepo to download
was dumped in the pwd rather than inside of it's own directory.
Fix #4033
=> bugfix: `get` dump folder contents in respective output folder

dvc/repo/run.py, tests/func/test_run_multistage.py, tests/func/test_run_single_stage.py
This commit preserves comments, meta and order inside a dvc.yaml
when `-f/--force` is used. But, it does not maintain comments/meta
for .dvc files.
Related: #4014
=> run: maintain order when -f/--force overwrite stage

scripts/ci/before_install.sh
- mac doesn't like `sed -r` (for `snapcraft` version detection)
- the logic is not needed anyway since `snapcraft` runs on linux
- continues #3999
Best to [view the diff ignoring whitespace](https://github.com/iterative/dvc/pull/4037/files?w=1)
=> CI: fix Mac builds

.travis.yml, scripts/ci/before_install.sh
- related: #3999 (and #4037)
1. request a new channel version-prefix (aka track) at https://forum.snapcraft.io/t/track-request-for-dvc/17735 (e.g. `v2`)
+ otherwise attempting to `snapcraft release --channel=v2` will fail
1. create a new legacy-dev git branch (e.g. `1.x-dev`)
1. (optional) give a warning message: cherry-pick 6f0a05adb45526a7334f438b964e7dd4b9b64798. Wait ~30 days before continuing to the next step
+ the idea is to warn & give 2 options: opt-in now, or opt-out permanently. Both options will suppress the warning. Ignoring the warning will result in an auto-upgrade in 30 days
1. uncomment the `echo "unset SNAP_CHANNEL" >>env.sh` line in `scripts/ci/before_install.sh`
=> snap: make future major version upgrades easier

dvc/remote/local.py
#3672 (6d8499ea) extended `LocalRemote::_get_plans` to return
`checksums`. As all of the args from `_get_plans` was passed
down to `download()`, it recognized extra arg of checksum as
`no_progress_bar` due to which it became True and stopped showing
progress bar at all.
Fix #3874
[![asciicast](https://asciinema.org/a/1jLaOc0X1EpyNTJnc6yqnRwt4.svg)](https://asciinema.org/a/1jLaOc0X1EpyNTJnc6yqnRwt4)
=> (bugfix) get/import: fix broken progress bar

dvc/ignore.py, tests/unit/test_ignore.py
=> Performance improvement of dvcignore

dvc/repo/plots/template.py
=> plots: add smooth template

dvc/api.py, dvc/data_cloud.py, dvc/dependency/repo.py, dvc/output/base.py, dvc/remote/azure.py, dvc/remote/base.py, dvc/remote/gdrive.py, dvc/remote/gs.py, dvc/remote/hdfs.py, dvc/remote/http.py, dvc/remote/index.py, dvc/remote/local.py, dvc/remote/s3.py, dvc/remote/ssh/__init__.py, dvc/repo/diff.py, dvc/repo/tree.py, tests/func/remote/test_index.py, tests/func/test_add.py, tests/func/test_cache.py, tests/func/test_checkout.py, tests/func/test_data_cloud.py, tests/func/test_gc.py, tests/func/test_remote.py, tests/func/test_tree.py, tests/unit/remote/test_azure.py, tests/unit/remote/test_base.py, tests/unit/remote/test_index.py, tests/unit/remote/test_local.py, tests/unit/remote/test_remote.py
In DVC, we are really using hashes for identifying files (either MD5 or etags depending on platform/remote/cache) and not checksums. This renames checksum to hash for remote/cache trees to avoid future confusion.
This PR does not modify any existing behavior, or rename "checksum" usage elsewhere in DVC (output/dependency/etc), but we should consider updating these other places in the future.
Related to #3882
=> remote: rename "checksum" -> "hash"

dvc/output/local.py, dvc/remote/local.py, dvc/repo/get_url.py, dvc/stage/imports.py, tests/func/test_get_url.py, tests/func/test_import_url.py
This allows us to properly process the errors like missing target.
Fixes #3897
=> get-url/import-url: save dependency before downloading

dvc/rwlock.py, tests/func/test_repro_multistage.py
Fixes #3653
(146s with 124.9s spent on fsync vs 14.8s cumulative)
Still 5-6 seconds are spent on 178461 `relpath()` calls. Will be handled on a separate PR.
=> optimize: remove `fsync` when dumping rwlock data

dvc/stage/__init__.py, tests/func/test_stage.py
~~On top of #4052~~
A lot of `relpath` calls were being used by `networkx` indirectly through `Stage::__eq__()` and `Stage::__hash__()`. They would call `relpath` and `abspath` calls. This PR caches them.
Compare with #4052 with following:
Related #3653 
=> cache relpath on stage

dvc/remote/gs.py
Fixes #4056
`GoogleStorageTree._generate_download_url` needs to create it's own url signing credentials when the current google auth credentials cannot be used for signing.
=> fix url signing when using GoogleStorage on GoogleComputeEngine

dvc/ignore.py, dvc/repo/ls.py, dvc/repo/tree.py, dvc/scm/git/tree.py, dvc/scm/tree.py, tests/unit/repo/test_repo_tree.py, tests/unit/repo/test_tree.py, tests/unit/scm/test_git.py
`BaseTree.walk` now handles errors the same way as `os.walk`. Errors will be ignored unless `onerror` callback function is provided.
Fixes #4055.
=> trees: handle tree.walk errors the same way as os.walk

dvc/output/base.py, dvc/stage/__init__.py, tests/func/test_remove.py
Fixes #4013 
PR doesn't require documentation updates
=> remove: clean gitignore content

dvc/command/add.py, dvc/command/cache.py, dvc/command/checkout.py, dvc/command/commit.py, dvc/command/daemon.py, dvc/command/data_sync.py, dvc/command/freeze.py, dvc/command/get.py, dvc/command/get_url.py, dvc/command/imp.py, dvc/command/imp_url.py, dvc/command/ls/__init__.py, dvc/command/metrics.py, dvc/command/move.py, dvc/command/plots.py, dvc/command/remove.py, dvc/command/repro.py, dvc/command/unprotect.py, dvc/command/update.py, setup.py
+ `shtab>=1.0.0` https://github.com/iterative/dvc/pull/3921#discussion_r442787136
+ `shtab>=1.0.0` <- https://github.com/iterative/shtab/issues/3
+ `shtab>=1.0.2` <- https://github.com/iterative/shtab/issues/4
- part of #4070
- continues #3921
=> completion: misc fixes

dvc/ignore.py, dvc/remote/base.py, dvc/repo/tree.py, dvc/scm/git/tree.py, dvc/scm/tree.py
GitPython is not threadsafe, which was causing issues when we were
computing hash for a directory.
Fixes #4079
Related to tree generalization #4050
=> git: don't use multithreading for computhing dir hash

dvc/command/run.py, dvc/repo/run.py, tests/unit/repo/test_run.py
Fixes #4084
https://github.com/iterative/dvc.org/pull/1480
=> run: hide and forbid --file for multistage files

scripts/build_posix.sh
We are currently missing url and license metadata:
```
Name        : dvc
Arch        : x86_64
Version     : 0.94.0
Release     : 1
Size        : 172 M
Repo        : installed
From repo   : dvc
Summary     : Data Version Control - datasets, models, and experiments
versioning for ML or data science projects
URL         : http://example.com/no-uri-given
License     : unknown
Description : Data Version Control - datasets, models, and experiments
versioning for ML or data science projects
```
https://github.com/iterative/dvc/issues/4088#issuecomment-648270797
=> rpm/deb/osxpkg: add url and license

dvc/repo/ls.py, dvc/repo/tree.py, tests/func/test_ls.py
Listing a git directory (so we don't have to have access to the remote)                                                                      
```                                                                                               
$ dvc list git@github.com:iterative/private.git                                                   
.gitignore                                                                                        
dataset                                                                                           
dataset.dvc                                                                                       
README.md                                                                                         
images …
```
=> list: add support for tracked directories

.pylintrc, dvc/updater.py, tests/basic_env.py, tests/dir_helpers.py, tests/func/test_add.py, tests/func/test_repro.py, tests/remotes/local.py, tests/remotes/ssh.py, tests/unit/test_updater.py, tests/unit/utils/test_collections.py
Only one error was found in `dvc/updater` which I refactored out and fixed. Also, I added a few unit tests for it. 
On tests, I have tried fixing most of it, but on two occasions, I have silenced it.
=> pylint: enable attribute-outside-init check

dvc/remote/hdfs.py
Clouds that have a non-noop `makedirs` should implement it in their own
method. Hdfs somehow slipped under the radar and had `mkdir` used
explicitly in `copy` and `upload` methods.
=> hdfs: implement makedirs separately

dvc/repo/metrics/show.py, tests/func/metrics/test_show.py
Reverts an issue caused by #4005.
=> metrics: skip missing metrics silently

dvc/repo/tree.py, tests/func/test_get.py
Partial fix for #4131 (resolves the `dvc get` bug only).
=> RepoTree: preserve relative paths in copytree()

dvc/remote/azure.py, setup.py, tests/unit/remote/test_azure.py
=> azure: use CLI config

dvc/remote/azure.py, setup.py
=> azure: use knack directly instead of azure-cli-core

dvc/command/add.py, dvc/command/cache.py, dvc/command/checkout.py, dvc/command/commit.py, dvc/command/completion.py, dvc/command/daemon.py, dvc/command/data_sync.py, dvc/command/freeze.py, dvc/command/get.py, dvc/command/get_url.py, dvc/command/imp.py, dvc/command/imp_url.py, dvc/command/ls/__init__.py, dvc/command/metrics.py, dvc/command/move.py, dvc/command/plots.py, dvc/command/remove.py, dvc/command/repro.py, dvc/command/unprotect.py, dvc/command/update.py, setup.py
- update `shtab>=1.1` to use new cleaner API
- continues #4076
=> completion: update dependency

dvc/remote/azure.py, dvc/remote/base.py, dvc/remote/gdrive.py, dvc/remote/gs.py, dvc/remote/oss.py, dvc/remote/s3.py, tests/unit/remote/test_base.py, tests/unit/remote/test_remote_tree.py
=> s3,gs: don't append "/" to prefixed path when listing objects

tests/dir_helpers.py, tests/func/test_get.py, tests/func/test_import.py, tests/utils/__init__.py
This PR is just a showcase to see how we like it. I've converted a few
tests to it, but there will be much more to come.
```
assert (tmp_dir / "file") == "contents"
assert (tmp_dir / "dir").read_text() == {"subdir": {"file": "hello"}}
```
This approach is nicer because it is basically the same as what we feed
to `TmpDir.gen` and also allows us to use a declaratory asserts instead
of relying on fs files. The problem becomes much more apparent once
you get into remote workspaces, where we `trees_equal` doesn't work.
=> [RFC] tests: make read_text() work with directories

dvc/dependency/repo.py, tests/dir_helpers.py, tests/func/test_get.py, tests/func/test_import.py, tests/func/test_update.py, tests/utils/__init__.py
=> status: pass tree as a kwarg

tests/func/test_api.py, tests/func/test_data_cloud.py, tests/remotes/__init__.py, tests/remotes/azure.py, tests/remotes/gdrive.py, tests/remotes/gs.py, tests/remotes/hdfs.py, tests/remotes/http.py, tests/remotes/oss.py, tests/remotes/s3.py, tests/remotes/ssh.py
Usually we need it to parametrize tests with, so there is no
reason to duplicate the code. I've left `local_remote` fixture
just because it is so convenient and often used in a lot of tests.
=> tests: create `remote` fixture

scripts/ci/before_install.sh
Don't push v0 to default tracks.
This PR does not require a new 0.x tagged release.
This PR is to make sure any future 0.x tagged release (presumably a security fix) doesn't get pushed to >=1.x users.
- fixes #3872 (finally and completely!)
=> snap: deprecate v0

dvc/cli.py
Previous implementation didn't take into account that 2nd and 3rd level commands might have the same name, so we can't use it to identify a proper parser. Now we use cmd class instead, which is reliable.
Fixes #4043
=> cli: show subcommand-specific help

dvc/ignore.py, tests/func/test_ignore.py, tests/unit/test_ignore.py
=> Add more tests according to gitignore

dvc/dependency/param.py, tests/func/test_run_multistage.py, tests/unit/dependency/test_params.py
The falsy values were being skipped when merging params values
from dvc.yaml and dvc.lock, showing the values as always changed.
These values were never added to `info`, but were found in
`self.params` making them appear as changed.
Fixes #4184
=> params: fix skipping of params dvc.lock when it's a falsy value

dvc/config.py, dvc/ignore.py, dvc/repo/__init__.py, dvc/repo/tree.py, dvc/scm/git/tree.py, dvc/scm/tree.py, tests/unit/repo/test_repo.py
=> config: use repo.tree

dvc/command/checkout.py, dvc/command/data_sync.py
I heard about this issue from 2 independent users. They didn't know that dvc support pull for a file.
`-R` option is minor and looks a bit confusing. Let's remove it from the target description.
https://github.com/iterative/dvc.org/pull/1384
=> pull: target message

dvc/dvcfile.py, tests/func/test_dvcfile.py
Fixes #4090 
https://github.com/iterative/dvc.org/issues/1564
=> remove: remove dvc.yaml and dvc.lock if they are empty

scripts/ci/before_install.sh, tests/remotes/__init__.py, tests/remotes/ssh.py
No longer needed, all tests are using mocked ssh already.
=> tests: remove real SSH

dvc/external_repo.py, dvc/repo/tree.py, tests/func/test_ls.py, tests/func/test_tree.py
=> list: support tracked file path as a target

dvc/dependency/__init__.py, dvc/dependency/repo.py, dvc/output/__init__.py, dvc/output/base.py, dvc/output/local.py, dvc/output/ssh.py, dvc/repo/tree.py, tests/func/test_tree.py, tests/unit/dependency/test_local.py, tests/unit/output/test_local.py
Outputs and dependencies don't really care about the remotes, as they
don't do any pushing or pulling. What they really need are the trees,
so let's use them directly.
Part of #4050
=> deps/outs: get rid of remotes in favor of trees

dvc/data_cloud.py, dvc/dependency/repo.py, dvc/output/base.py, dvc/remote/base.py, dvc/remote/local.py, dvc/repo/diff.py, dvc/repo/tree.py, dvc/tree/base.py, tests/func/test_cache.py, tests/func/test_checkout.py, tests/func/test_gc.py, tests/func/test_remote.py, tests/func/test_tree.py
This helps combat the remote/tree/cache confusion.
=> dvc: remove tree-specific wrappers from cache

dvc/tree/base.py
Leftover from remote/tree separation.
=> tree: remove duplicated code

dvc/config.py, dvc/repo/__init__.py, dvc/repo/brancher.py, dvc/scm/tree.py, dvc/state.py, dvc/tree/local.py, dvc/utils/fs.py, tests/func/test_ignore.py, tests/func/test_tree.py, tests/unit/utils/test_fs.py
Working tree is really just a regular local tree and should be
used by outputs when trying to compute a hash for themselves.
We didn't use it previously because local tree was embeded into
the local remote class.
Related to #4050
=> dvc: get rid of WorkingTree

dvc/config.py, dvc/ignore.py, dvc/repo/__init__.py, dvc/repo/add.py, dvc/repo/brancher.py, dvc/scm/git/__init__.py, dvc/scm/git/tree.py, dvc/state.py, dvc/tree/base.py, dvc/tree/local.py, tests/func/test_ignore.py, tests/func/test_tree.py, tests/unit/utils/test_fs.py
CleanTree is a very awkward wrapper that spreads the context across
the codebase and results in unexpected behaviour when using it.
This PR starts moving dvcignore-related logic into the trees themselves
(it makes a lot of sense, kinda like `state`) so they could deal with
it however they like.
There are at least two temporary ugly parts about this PR:
1) dvcignore is used by individual trees and not packed into
tree/base.py yet;
2) `dvcignore_root` argument. This one is caused by the dvcignore trying
to collect everything topdown starting from the certain root dir. What
it should do instead is for a certain path that is being checked look up
the tree through the parents until it finds repo root (.dvc dir) and
then stop. That would handle subrepos as well. At the same time we need
to …
=> dvc: get rid of CleanTree

dvc/dependency/repo.py, dvc/tree/base.py, tests/func/test_commit.py
=> RepoDependency: never changed

dvc/output/local.py, tests/func/test_ignore.py
EDIT:
Fixes #4110 
Fixes https://github.com/iterative/dvc/issues/4197
=> LocalRemoteTree: use repo tree as work_tree with local outputs

.travis.yml, scripts/ci/before_install.sh
```bash
snapcraft release dvc 626 v1/stable  # updates 1.1.7 to 1.1.10
snapcraft release dvc 641 v1/edge    # updates 1.1.7 to 1.1.10-15-g91f3036c
```
fixes https://travis-ci.com/github/iterative/dvc/jobs/360297196#L2901-L2902
```
The store was unable to accept this snap.
- binary_sha3_384: A file with this exact same content has already been uploaded
```
=> snap: deploy: fix major channels not being pushed

.dvc/.gitignore, dvc/cli.py, dvc/command/experiments.py, dvc/command/repro.py, dvc/config.py, dvc/repo/__init__.py, dvc/repo/experiments/__init__.py, dvc/repo/experiments/checkout.py, dvc/repo/experiments/diff.py, dvc/repo/experiments/show.py, dvc/repo/reproduce.py, setup.py, tests/func/experiments/test_experiments.py, tests/func/experiments/test_show.py, tests/unit/command/test_experiments.py, tests/unit/command/test_repro.py
Related to #2799.
Implements initial POC support using a single git clone. UI is rough expected to change a lot.
* `dvc repro -e/--experiment` - creates a new experiment. Experiment is derived from the current HEAD commit in the user's repo and contains any changes in the user's current workspace.
* `dvc experiments show` - show experiment table. By default table includes the user's workspace, the current HEAD commit and any experiments derived from HEAD. `--all-commits/--all-tags/--all-branches` can be used to display more experiments.
* `dvc experiments diff` - diff 2 experiments. Currently just concats the output from `dvc metrics diff` and `dvc plots diff`.
* `dvc experiments checkout <experiment_rev>` - …
=> Experiments proof of concept

dvc/tree/base.py
Continuing #4050 This issue was found in #4242 and doesn't show up in the master, because there is not enough distinction between tree/cache yet.
=> tree: use cache.tree to check if cache file exists
