- dvc/external_repo.py
- dvc/fs/repo.py
- dvc/repo/__init__.py
- tests/unit/repo/test_repo.py
- tests/unit/test_external_repo.py
SCM is used for both reading and writing operations, but in the former case -
as filesystem and in the latter - as actual scm/git. So we should distinguish
those and use fs directly, which follows the overall philosophy of being able
to use Repo on any fs.
Keeping `rev=` option for `Repo` because it is a very convenient way to get
repo instance from local path but for particular branch/tag/etc.
Pre-requisite for git/dvc/repofs refactorings.
> repo: use fs instead of scm

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/base.py
Before it was just left instantiated, but was not raised.
> exp: raise InvalidExpRefError properly

- dvc/repo/index.py
- tests/func/test_repo_index.py
- tests/unit/repo/test_repo.py
`@memoize()` memory lives as long as decorated function lives, which is
permanent in this case. Since `self` is referenced as a memory key no
`Index` will ever be freed.
Changed to use `@cached_property` who's cache lives as long as the
parent instance.
**NOTE:** This is an issue for Studio since we are parsing many commits in a long running process.
> Fix memory leak in Index.build_graph()

- dvc/command/plots.py
- dvc/config_schema.py
- dvc/repo/live.py
- tests/func/test_live.py
- tests/unit/command/test_plots.py
Closes #6091
Closes iterative/dvclive#201
`dvc.org` P.R: https://github.com/iterative/dvc.org/pull/3101
> Add config  option `plots.auto_open` 

- dvc/command/machine.py
- dvc/ui/table.py
From https://github.com/iterative/dvc/pull/6893/files#r777784748
Table rendering does not support `None` for now, and we will change it
back after (#7167).
> ui: remove `None` in CellT type

- dvc/objects/db/index.py
> odb: pin index pickle protocol version

- dvc/repo/experiments/pull.py
- dvc/repo/experiments/push.py
- dvc/repo/experiments/remove.py
- dvc/repo/experiments/utils.py
- dvc/scm.py
- tests/unit/repo/experiments/test_utils.py
fix #7196 
Refactor exp_ref_by_name in `dvc/repo/experiments/utils.py`.
In previous the exp_ref_by_name walk throught all of the references to
match only one exp name. This makes multi exp name seeking to be a job
of `O(mn)` complexity, Walking though the exp ref and return all of the
exp ref with greatly reduce this complexity to `O(n)`
> exp remove: refactor exp utils

- dvc/repo/ls.py
- tests/func/test_ls.py
> ls: handle broken symlink

- dvc/output.py
- tests/func/test_remote.py
As the title says. Had to adjust tests as before we were raising this issue during instantiation which meant we were not checking for `external=True` there, but now stage validation takes priority and needs explicitly `external=True` for the test to work/make sense. 
This is backported from https://github.com/iterative/dvc/pull/6868.
> output: don't raise RemoteCacheRequiredError on instantiation, make it lazy

- .github/workflows/tests.yaml
- dvc/testing/tmp_dir.py
- tests/basic_env.py
- tests/conftest.py
- tests/dir_helpers.py
- tests/func/metrics/test_diff.py
- tests/func/params/test_diff.py
- tests/func/test_diff.py
- tests/func/test_import.py
- tests/unit/fs/test_ssh.py
When the git config has set global `init.defaultBranch` different than master,
a few test cases were failing.
Currently, the test case is assuming the default branch to be set as
master.
This commit will introduce **initial_branch** option to git init call
which will ensure *master* branch is used as default for out test cases.
Fixes https://github.com/iterative/dvc/issues/6043.
> test: fix test failure in case of different default branch

- dvc/command/live.py
- dvc/command/plots.py
- dvc/render/base.py
- dvc/render/data.py
- dvc/render/utils.py
- dvc/render/vega.py
- tests/unit/command/test_plots.py
- tests/unit/render/test_data.py
- tests/unit/render/test_render.py
- tests/unit/render/test_vega.py
- tests/unit/repo/plots/test_templates.py
Fixes: #6943
@Suor I am addressing #6943 here which is a result of our [discussion in iterative/viewer#2657](https://github.com/iterative/viewer/issues/2657#issuecomment-939674364)
`dvc/render/utils.py::to_datapoints` accepts `data` and `props`, so you should be able to provide your own properties, which should allow to address the disrepancies between `dvc` and studio plot properties resolving.
> render: vega: data processing outside of renderers

- dvc/fs/path.py
- tests/unit/fs/test_path.py
> handle paths ending with sep in dvc.fs.path.Path.parts

- dvc/fs/utils.py
`dvc.fs.utils.test_links()` fails with a CacheLinkError if the target `to_path` does not already exist, as is the case when "abc.dvc" exists (referring to a directory object) and we try to run "dvc pull abc/def". To avoid this issue, fully create `to_path` before attempting to create a link in it.
Example error log which this should fix:
```
2022-01-08 00:58:31,286 ERROR: failed to pull data from the cloud - No possible cache link types for '/<REPO>/<OBJECT>/<SUBDIR>'. See <https://dvc.org/doc/user-guide/troubleshooting#cache-types> for more information.
------------------------------------------------------------
File "/usr/local/lib/python3.8/dist-packages/dvc/command/data_sync.py", line 30, in run
stats = self.repo.pull(
File …
```
> fs: test_links: create destination directory first

- dvc/utils/table.py
Rich added `vertical` kwarg in `add_column`, which linter
is now complaining (as it should). But this may keep on breaking
when rich adds/removes args/kwargs in the future.
So, this commit uses (*args, **kwargs) instead of specifying particular
parameters explicitly. This also sets `collapse` directly to the
`rich.table.Column` rather than extending through our one `Column`
implementation.
> rich-table: fix add_column args/kwargs

- dvc/command/experiments/show.py
- dvc/repo/brancher.py
- dvc/repo/experiments/show.py
- dvc/scm.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_experiments.py
- tests/unit/scm/test_scm.py
fix: #7152
1. Add `--rev` flag to `dvc exp show`.
2. Add -1 support for `--num` flag`.
3. Extract revision solving to `utils`.
4. Update command unit test
5. Add a util unit test.
> exp show: add `--rev` flag (#7152)

- dvc/command/plots.py
- tests/unit/command/test_plots.py
`-o` was being required even when renderers don't need output path.
> plots: Fix `--json` requiring `-o`.

- dvc/command/base.py
- dvc/command/experiments/__init__.py
- dvc/command/experiments/exec_run.py
- dvc/command/experiments/run.py
- dvc/config.py
- dvc/config_schema.py
- dvc/machine/__init__.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/executor/local.py
- dvc/repo/experiments/executor/manager/base.py
- dvc/repo/experiments/executor/manager/local.py
- dvc/repo/experiments/executor/manager/ssh.py
- dvc/repo/experiments/executor/ssh.py
- dvc/repo/experiments/pull.py
- dvc/repo/fetch.py
- dvc/repo/pull.py
- dvc/repo/push.py
- tests/func/experiments/executor/test_ssh.py
- tests/unit/command/test_experiments.py
Related to https://github.com/iterative/dvc/issues/6267
- Adds `dvc exp run --machine` for running an experiment on the specified `dvc machine` instance
- Adds machine `setup_script` config option for runtime environment setup (this is separate from the existing `startup_script` which installs system packages at machine boot/startup).
Note: Until the next release, in order to actually use `dvc exp run --machine` you will need to override the default `startup_script` to install DVC from source with your own script:
```
#!/bin/bash
sudo add-apt-repository --yes ppa:deadsnakes/ppa 
sudo apt-get update
sudo apt-get install --yes python3.9 python3.9-dev python3.9-venv python3-pip
sudo -u ubuntu python3.9 -m pip …
```
> exp run: support naive remote execution via `--machine`

- dvc/command/experiments/pull.py
- dvc/command/experiments/push.py
- dvc/repo/experiments/exceptions.py
- dvc/repo/experiments/pull.py
- dvc/repo/experiments/push.py
- dvc/repo/experiments/utils.py
- dvc/types.py
- tests/func/experiments/test_remote.py
- tests/func/experiments/test_remove.py
- tests/unit/command/test_experiments.py
fix #7196 
New feature: now `dvc exp push/pull` can accept a list of experiment names as input.
1. add support to list input for the `exp push/pull`
2. add function tests for the multi `exp push/pull`
3. add unit test for the arg parse
wait #7205
> `exp pull/push`: add multi exp name arg support 

- dvc/repo/plots/templates/linear.json
---
To keep things consistent when we display plots generated from default templates in the VS Code extension, we will be overwriting the default colors (in the same way that Studio does). From initial inspection, it appears that overwriting the colors of plots that are generated by the linear template gives a slightly unexpected result.  The vertical on-hover line gets drawn with the last color that I specify as an override:
After the change:
Let me know if you have any questions or concerns.
Thanks,
Matt
> plots: update linear template so colors can be externally overwritten

- dvc/repo/__init__.py
We used to use that message for special external repo cases, but we don't
need it anymore.
Fixes #7281
Leftover from #7214
> find_root: unify error message

- dvc/exceptions.py
- dvc/repo/reproduce.py
- tests/func/experiments/test_experiments.py
Before it used to say 'failed to reproduce dvc.yaml', which is now changed
to print 'failed to reproduce train' or something similar.
For stages that are in dvc.yaml in the current working directory, it will
just print the stage names. For stages in other dvc.yaml files, it'll print
in <relative_path>:<stage_name>.
```console
$ dvc exp run
ERROR: failed to reproduce 'train': [Errno 2] No such file or directory: '/private/var/folders/xh/trg29z296h70n109kwfk6g800000gn/T/tmp.fJbphlSG/data'
```
Related: https://github.com/iterative/dvc/issues/7137
> repro/exp run: display stage name instead of filepath on failure

- tests/conftest.py
While investigating this failure: https://github.com/iterative/dvc/runs/4735592203?check_suite_focus=true#step:7:4910,
I noticed that we don't clean repos after each test runs, which meant that when some test later on called `main()` function, the function might try cleaning up multiple repositories at the end, which caused timeout for `exp init` tests.
> tests: clean repositories before each test runs

- dvc/commands/live.py
- dvc/fs/_callback.py
- dvc/fs/base.py
- dvc/fs/dvc.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/http.py
- dvc/fs/local.py
- dvc/fs/repo.py
- dvc/fs/s3.py
- dvc/fs/ssh.py
- dvc/progress.py
- dvc/utils/fs.py
fsspec callbacks were making us lose 35ms (~207 ms vs 170ms now).
These are now extracted from dvc.progress to dvc.fs._callback.
```console
$ hyperfine "dvc --help" --warmup 5 --runs 20
Benchmark 1: dvc --help
Time (mean ± σ):     207.2 ms ±   3.0 ms    [User: 171.2 ms, System: 34.1 ms]
Range (min … max):   201.8 ms … 214.8 ms    20 runs
```
vs 
```console
$ hyperfine "dvc --help" --warmup 5 --runs 20
Benchmark 1: dvc --help
Time (mean ± σ):     171.2 ms ±   2.9 ms    [User: 141.3 ms, System: 28.0 ms]
Range (min … max):   165.4 ms … 177.7 ms    20 runs
```
See https://github.com/iterative/dvc/wiki/Debugging,-Profiling-and-Benchmarking-DVC#benchmarking-startup-performance and https://github.com/iterative/dvc/wiki/Debugging,-Profiling-and-Benchmarking-DVC#benchmarking-dvc-commands.
Thank …
> cli: improve startup speed

- dvc/commands/experiments/show.py
- dvc/compare.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_experiments.py
- tests/unit/test_tabular_data.py
---
- Removed `--include-metrics` / `--include-params` and
`--exclude-metrics` / `--exclude-params`.
- Removed `--no-timestamp`  (-> `--drop Created`)
- `--drop` and `--keep` operate directly on the table columns. 
Support regex patterns.
- `--keep` does not perform any filtering. 
It's only used to specify columns to keep despite the other filtering. 
Previous `--include` behavior can be replicated with negative lookahead regex.
Closes #7079
Closes #7080
Closes #7083
Pre-requisite for #6434
---
Example:
<details>
<summary>`dvc exp show`</summary>
```
| Experiment              | Created      | loss    | accuracy   | train.batch_size   | train.hidden_units   | train.dropout   | train.num_epochs   | train.lr   | train.conv_activation   | …
```
> exp show: Add --drop and --keep args

- dvc/commands/experiments/show.py
- dvc/compare.py
- tests/unit/command/test_experiments.py
Update `subset` type hint.
Leftover from #7141
> TabularData: Simplify drop internals.

- dvc/dependency/param.py
- dvc/output.py
- dvc/repo/experiments/init.py
Related to https://github.com/iterative/dvc/issues/7137.
> exp init: handle exception properly on missing parameters file

- dvc/commands/add.py
> add: Update help of `--jobs`

- dvc/data/db/index.py
- dvc/state.py
- dvc/utils/decorators.py
- tests/unit/utils/test_decorators.py
Docs PR: https://github.com/iterative/dvc.org/pull/3205
Generates a better error message w/troubleshooting link for pickle errors in state/odb-index.
Related to https://github.com/iterative/dvc/pull/7222 (see discussion in https://github.com/iterative/dvc/pull/7222#discussion_r789406572)
> utils: add decorator to wrap diskcache pickle errors

- dvc/repo/experiments/executor/manager/local.py
- tests/func/experiments/test_experiments.py
> exp run: do not log message twice on workspace executor

- dvc/_debug.py
- tests/unit/command/test_debug.py
Support https://github.com/gaogaotiantian/viztracer 
I have found it more visually pleasing for multi-thread stuff:
How to use:
- `pip install viztracer`
- `dvc add foo --viztracer --max-stack-depth 5`
- `vizviewer viztracer.dvc-{id}.json`
> debug: Add support for viztracer profiler.

- dvc/repo/scm_context.py
The "adding %s to gitignore" debug statement was always being run because of the `_ignore()` call in `dvc/repo/__init__.py:207`
thanks @pared
> ignore: move debug statetement to the proper location

- dvc/commands/experiments/show.py
- dvc/repo/experiments/show.py
- tests/func/experiments/test_show.py
https://github.com/iterative/dvc.org/pull/3220
---
Use `repo.index.deps` / `repo.index.outs` to collect dependencies / outputss associated with each experiment.
Closes #6434
Currently, anything in `repo.index.deps` that is not a param dependency or an imported `.dvc` (because if the `.dvc` is used in the pipeline it would be a duplicated column). 
Studio filters git tracked files but I think that showing those files (i.e. `src` deps) is also valuable.
I think that more complicated internal filtering (i.e. considering removing intermediate deps) it's not worthy and problematic when considering all use cases. 
The table can get noisy but we provide the `--only-changed` flag (we could consider making it the default) and new improved filtering  #7141 that should make it easy to customize the …
> exp show: Include `deps` and `outs`.

- dvc/data/meta.py
- dvc/data/stage.py
- dvc/fs/base.py
- dvc/fs/dvc.py
- dvc/fs/git.py
- dvc/fs/local.py
- dvc/fs/repo.py
- dvc/output.py
- dvc/schema.py
- dvc/stage/loader.py
- dvc/stage/serialize.py
- dvc/stage/utils.py
- tests/unit/stage/test_loader_pipeline_file.py
- tests/unit/stage/test_serialize_pipeline_lock.py
With our staging process automatically capturing file metadata, we no longer
need to set isexec ourselves.
In followup PRs we will also use meta during checkout, so that we won't need
to use Output.set_exec by hand.
> output: move isexec to meta

- tests/func/utils/test_strict_yaml.py
Due to changes in `rich` `11.1.0`, all text formatted using `rich.syntax.Syntax` is now left-justified (see [0a37fcc](https://github.com/Textualize/rich/commit/0a37fcc93a025fb19821fa9a05a59aa1d3848a20)),
resulting in output padded with whitespace to the size of the tty.
This resulted in broken tests due to mismatching whitespace between actual `dvc.ui` output and test cases.
Stripping whitespace in the ui output in `test_exceptions` solves the broken tests for both `rich` `11.1.0` and `11.0.0`
fixes #7322
> tests: fix test_exceptions

- dvc/commands/plots.py
- dvc/repo/init.py
- dvc/repo/plots/template.py
- tests/unit/command/test_plots.py
- tests/unit/repo/plots/test_templates.py
Fixes: #6389
Changes in this PR:
- `.dvc/plots` will no longer be created upon `dvc init`
- user has to explicitly call `dvc plots templates` to create and populate `.dvc/plots`
TODO
> plots: make templates generation explicit

- dvc/repo/ls.py
ls doesn't support subrepos, so we can simply use dvcfs in --dvc-only.
> ls: don't use outs

- dvc/repo/ls.py
As noted by @skshetry we do actually support subrepos in ls https://github.com/iterative/dvc/commit/27b090709b13bfae42c1d64f49dfa84e4986d5cc
Reverts iterative/dvc#7347
> Revert "ls: don't use outs"

- dvc/data/meta.py
- dvc/data/stage.py
- dvc/data/tree.py
- dvc/fs/dvc.py
- dvc/fs/repo.py
- dvc/repo/diff.py
- dvc/repo/index.py
- tests/func/objects/db/test_index.py
- tests/func/test_ls.py
- tests/func/test_remote.py
- tests/unit/fs/test_repo.py
- tests/unit/fs/test_repo_info.py
Introducing simple repo tree that combines all workspaces into one structure,
and allows us to detach data representation from pipelines.
Pre-requisite for dvc-data extraction and using relpaths in dvcfs/repofs.
> dvcfs: detach from pipeline outputs

- dvc/api.py
- dvc/fs/dvc.py
- dvc/fs/repo.py
- tests/func/test_fs.py
- tests/unit/fs/test_dvc.py
- tests/unit/fs/test_repo.py
Currently we use both absolute and relative (depend on cwd) paths, which is
terrible for an api, as their interpretation depends on external factors.
This PR makes dvcfs accept only paths relative to the repo root for regular
outputs and absolute paths for external outputs.
Pre-requisite for making repofs use same relative paths.
> dvcfs: use paths relative to the repo root

- tests/basic_env.py
- tests/func/test_odb.py
- tests/unit/test_context.py
- tests/unit/utils/test_fs.py
Part of #1819
Changes:
1. Removed `TestGit` in `basic_env.py`.
2. Several `unittest.TestCase` subclasses in `func/test_odb.py` migrated to pytest: `TestCacheLoadBadDirCache`, `TestExternalCacheDir`, `TestSharedCacheDir`, `TestCacheLinkType`, `TestCmdCacheDir`
3. Several `unittest.TestCase` subclasses in `func/test_fs.py` migrated to pytest: `TestMtimeAndSize`, `TestContainsLink`,  
I have followed the checklit. 
This PR doesn't require documentation updates.
> tests: several tests migrated unittest to pytest

- dvc/commands/experiments/show.py
- tests/func/experiments/test_show.py
_extend_row did not consider partially empty `items`, which can occur when metris or params are renamed between commits.
Fixes #7070
> exp show: handle extending/renaming of metrics/params.

- dvc/repo/diff.py
- dvc/repo/experiments/diff.py
- dvc/repo/metrics/diff.py
- dvc/repo/params/diff.py
- dvc/repo/plots/diff.py
- dvc/scm.py
- tests/func/experiments/test_show.py
Fixes #7329
In a previous PR, we introduce a bug which use `HEAD` as the workspace
commit, while if there is a checkpoint is running, the `HEAD` is
actually changing all the time, we should use
`refs/exps/exec/EXEC_BASELINE` instead.
A test is needed for this PR.
1. replace the default `HEAD` in `exp show` with `fix_exp_head`.
2. modify a functional test to simulate the running conditions.
> exp show: show exp when checkpoint is running(#7329)

- dvc/commands/experiments/init.py
- dvc/repo/experiments/init.py
- tests/func/experiments/test_init.py
This PR creates the workspace structure by default. That means that the `code` paths and `data` paths are created if they don't exist. If the path has any extension, the empty file will be created, otherwise, a directory is created. 
Initially, this was to be created for the defaults only, but I have added the magic everywhere, so this is applied to passed arguments, defaults or config values too.
Second thing that PR adds is this output so that users are aware of the changes and their workspace structure:
```
Creating experiment project structure:
├── data
├── metrics.json
├── models
├── params.yaml
├── plots
└── src
```
Closes #7137, closes #7138 and  closes #7139.
> exp init: create workspace structure by default, show workspace tree

- dvc/data/status.py
- dvc/data/transfer.py
- dvc/objects/db.py
- dvc/repo/gc.py
- tests/func/test_data_cloud.py
- tests/unit/remote/test_base.py
`jobs` kwarg was not being passed on properly
Fixes #7319
> fix ignored job count

- dvc/fs/fsspec_wrapper.py
- dvc/fs/git.py
Helps us to concentrate all useful wrappers in one place so we could remove them later in one go.
> fs: git: move isfile/walk to fsspec wrapper

- dvc/fs/base.py
- dvc/fs/dvc.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/local.py
- dvc/fs/repo.py
- dvc/repo/ls.py
- tests/unit/fs/test_dvc.py
- tests/unit/fs/test_repo.py
Makes dvc/repofs and other filesystems comply with fsspec.
> fs: walk: get rid of onerror

- dvc/fs/dvc.py
- tests/unit/fs/test_dvc.py
> dvcfs: handle repo root

- dvc/repo/experiments/init.py
- tests/func/experiments/test_init.py
- Moves workspace tree for interactive mode after prompts. Previously
this was displayed before the prompts.
- Remove the yaml contents and the confirmation prompt in an interactive
mode.
- Simplify `init_interactive()`.
```console
This command will guide you to set up a train stage in dvc.yaml.
See https://s.dvc.org/g/pipeline-files.
Command to execute: true
Enter the paths for dependencies and outputs of the command.
DVC assumes the following workspace structure:
├── data
├── metrics.json
├── models
├── params.yaml
├── plots
└── src
Path to a code file/directory [src, n to omit]:
'src' does not exist in the workspace. "exp run" may fail.
Path to a data file/directory [data, n to omit]:
'data' does not exist in the workspace. "exp run" may fail.
Path to a model file/directory [models, n …
```
> exp init: refactor and simplify interactive mode

- dvc/commands/plots.py
- dvc/render/data.py
- dvc/render/utils.py
- dvc/render/vega.py
- tests/unit/command/test_plots.py
- tests/unit/render/test_data.py
- tests/unit/render/test_vega.py
Usage:
`dvc plots show/diff --json --split`
The results for `vega` will contain additional field `datapoints` and the template will not have the data filled (there will be `<DVC_METRIC_DATA>` in datapoints destination.)
As of now the `datapoints` field will exist no matter whether `--split` has been invoked or not. The only difference is that in case when not providing `--split`, the content of particular vega json will have the data filled.
cc @mattseddon
> plots: json: add datapoints to vega plots

- dvc/commands/stage.py
Per https://github.com/iterative/dvclive/pull/217
> Suppress `--live-no-summary` help.

- dvc/commands/diff.py
- tests/unit/command/test_diff.py
* [N/A] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.
`dvc diff` fails when there is no diff and `hide_missing` is true (`hide_missing` is implied when comparing two revisions) because `CmdDiff.run` tries to delete the `not in cache` info from an empty dict. It seemed easy enough to fix.
Not sure if we need a test for this. Couldn't find any relevant ones specific to the `CmdDiff` logic.
> diff: fix missing key bug (#6720)

- dvc/commands/experiments/__init__.py
- dvc/commands/experiments/ls.py
- dvc/commands/experiments/show.py
- dvc/repo/experiments/ls.py
- dvc/repo/experiments/utils.py
- dvc/scm.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_remote.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_experiments.py
fix: #7153
Unify the flags in `exp list` to `exp show` (including -A/--all-commits
)
Wait #7152 and #7206
1. Add new `-A`,`-n` flags to `exp list` command.
2. Add unit test for the flag parse.
3. unify the revs retrive logic to `exp show`.
4. Add functional test for `exp list`
> exp list: add the new flags  (including -A/--all-commits) (#7153)

- dvc/commands/experiments/pull.py
- dvc/commands/experiments/push.py
- dvc/repo/experiments/pull.py
- dvc/repo/experiments/push.py
- tests/func/experiments/test_remote.py
- tests/unit/command/test_experiments.py
wait for  #7245
exp push/pull: make all the flags in exp show and exp list support pull/push (#7154)
fix: #7154
1. add all flags (A/--all-commits , -a/--all-branches, --all-tags) in `exp show` to the `exp pull/push`
2. add unit and func tests for `exp push/pull`
> exp push/pull: make all the flags in exp show and exp list support pull/push (#7154)

- dvc/commands/experiments/remove.py
- dvc/repo/experiments/exceptions.py
- dvc/repo/experiments/remove.py
- tests/func/experiments/test_remove.py
- tests/unit/command/test_experiments.py
fix: #7155
in `exp remove`
1. rename flags `-A/--all-commits` 
2. add two new flags `rev` and `num` 
3. unify the revision collection
4. add unit and func tests for them
wait for #7245
> exp remove: rename `--all-commits` flag add a new `rev` flag and unify the collection of revs (#7155)

- dvc/commands/experiments/__init__.py
fix: #7444
from the discussion https://github.com/iterative/dvc.org/pull/3187#discussion_r821382100
1. Update the help message of `-n`
> exp show/pull/push/list: help text for -n (#7444)

- dvc/dependency/__init__.py
- dvc/dependency/param.py
- dvc/repo/params/show.py
- dvc/stage/serialize.py
- tests/func/params/test_diff.py
- tests/func/params/test_show.py
- tests/func/test_status.py
- tests/unit/dependency/test_params.py
- tests/unit/stage/test_serialize_pipeline_file.py
- tests/unit/stage/test_serialize_pipeline_lock.py
(will create the docs after #7413)
The syntax for tracking files is:
```yaml
params:
- params.yaml:
- config.yaml:
```
Closes #4112 
[![asciicast](https://asciinema.org/a/PUVxnxZzJqe6RNjXipq0VXUNp.svg)](https://asciinema.org/a/PUVxnxZzJqe6RNjXipq0VXUNp)
> params: allow tracking file

- dvc/dependency/param.py
- dvc/repo/experiments/init.py
- tests/func/experiments/test_init.py
Note that this won't add support for tracking the params file,
it'll only create the params file. Some changes on error and
prompts are made.
> exp init: create params file by default

- dvc/commands/experiments/remove.py
- dvc/repo/experiments/remove.py
- tests/func/experiments/test_remove.py
fix: #7449
`exp remove`: should show the experiments that were removed
1. experiment.remove now returns the experiment list been removed.
2. modify the functional test to these the returned list.
3. use ui to show the removed list.
Co-authored-by:
current behaviour
```bash
$ dvc exp remove aab2130 expqueue # revision and exp-name of queued experiments.
remove experiments: expqueue,aab2130
$ dvc exp remove --rev master
remove experiments: exp0.25,exp0.3
$ dvc exp remove --all
remove experiments: exp0.1,exp-0f3cc,exp0.5,exp0.15,exp0.4
```
> exp remove: show removed experiments #7449

- pyproject.toml
- setup.cfg
A workaround for https://github.com/pypa/setuptools/issues/3196.
We had some benchmarks failure due to a new setuptools release `setuptools==61.0.0`. (eg: https://github.com/iterative/dvc/runs/5689488287?check_suite_focus=true#step:4:1777). Restricting that specific versions here temporarily.
> build: pin setuptools to <61

- dvc/data/db/local.py
- dvc/objects/db.py
- tests/unit/remote/test_base.py
This removes callback from internal APIs: `_list_paths`, `list_hashes`,
and `_hashes_with_limit`. These are all iterators and hence can just be
replaced by wrapping a progress bar over those iterators on the caller
side.
We still have progress bars in `hashes_exist`, `_estimate_remote_size`,
`_list_hashes_traverse` and `list_hashes_exists`, which should gradually
be lifted up and replaced.
I came over to this refactoring when investigating `webdav` issue in #7288, and noticed that `_list_paths` could be simpler.
> objects.db: get rid of callbacks from internal _list_paths API

- pyproject.toml
- setup.cfg
Reverts iterative/dvc#7502, now that setuptools==61.1.0 is released.
> Revert "build: pin setuptools to <61"

- dvc/fs/http.py
When using an https remote (such as in the dvc-bench remote, see https://github.com/iterative/dvc-bench/issues/319), under certain situations, `dvc pull` would freeze and never return. Note that this did not happen 100% of the time, but often enough to make the bench CI always fail (note: CI was running a matrix strategy over ~12 workers, pulling a 25k file dataset on each).
Investigation pointed to network issues (as the issue could not be reproduced locally). I ended up tracking this to a connection being dropped/lost and `aiohttp` not realizing this. Due to our timeout defaults for `aiohttp.ClientSession`:
```python
aiohttp.ClientTimeout(
total=None,
connect=self.REQUEST_TIMEOUT,
sock_connect=self.REQUEST_TIMEOUT,
sock_read=None,
)
```
(note that `sock_read=None`), `aiohttp` would keep …
> fs.http: prevent hangs under some network conditions

- setup.cfg
This adds support for pytest>7.
See https://github.com/avast/pytest-docker/pull/74.
> bump pytest-docker to 0.11.0

- dvc/commands/experiments/init.py
- dvc/repo/experiments/init.py
- tests/func/experiments/test_init.py
- tests/unit/command/test_experiments.py
Closes #7130 and closes #6446.
---
> exp init: change ui prompts structure and output

- dvc/utils/strictyaml.py
- tests/func/utils/test_strict_yaml.py
This is done in a hacky way, so it only works for dvc.yaml/dvc.lock/.dvc for now (unless we fix brancher).
Unfortunately, `brancher` only gives us revision instead of the reference (eg: `HEAD`).
> ui: add revision info on dvc.yaml/dvc.lock/.dvc syntax and schema errors

- dvc/render/convert.py
- tests/unit/render/test_convert.py
In recent rendering lib extraction (#7409) we changed the data type for images, from list to str.
We should keep the structure for `to_json` consistent, vscode relies on this. cc @mattseddon
> plots: image: fix image to_json structure

- dvc/commands/plots.py
- tests/unit/command/test_plots.py
Related: iterative/vscode-dvc#1521
Tests included in this change help only partially, we need to do #7549 to make sure our outputs match vscode team expectations.
> plots: json: show even if no results

- dvc/repo/index.py
- tests/func/test_repo_index.py
Allow access to a stage via `getitem` in addition to iterating over the Index.
It is currently possible to iterate over `dvc.repo.Index` but you can not get a `Stage` by its stagename.
This PR introduces `getitem` supporting the name of the Node as follows:
```py
index = Index()
stage: Stage = index["stagename"]
```
This can be handy for all operations attached to `Stage` such as looking at dependecies, etc.
> Add `getitem` to Index

- dvc/fs/gdrive.py
- tests/unit/remote/test_gdrive.py
`_validate_config()` had a bug: it would not take into account that Google
Drive credentials can also be passed using `GDRIVE_CREDENTIALS_DATA` as
documented here [1].
This patches the validation logic to also accept this environment variable as a
means to provide service account credentials.
Before, commands like `dvc push` would exit with:
```
ERROR: failed to push data to the cloud - To use service account, set
`gdrive_service_account_json_file_path`, and
optionally`gdrive_service_account_user_email` in DVC config
Learn more at <https://man.dvc.org/remote/modify>
```
[1]: https://dvc.org/doc/user-guide/setup-google-drive-remote#authorization
Thanks to @duijf for helping me diagnose.
Co-authored-by: Laurens Duijvesteijn <laurens@iterative.ai>
> fs.gdrive: Fix GDRIVE_CREDENTIALS_DATA for service accounts

- dvc/external_repo.py
- dvc/repo/experiments/utils.py
- dvc/scm.py
- tests/func/experiments/test_remote.py
- include exp refs when cloning/updating full (non-shallow) erepo clones
- add test for `dvc get --rev=<exp>`
Will fix #7169
> erepo: include exp refs in clones

- dvc/output.py
- tests/func/test_data_cloud.py
- tests/unit/output/test_output.py
As described in #6870 when s3 extra missing dvc does not always raise the informative message that it should be installed. This has to do with catching a generic DvcException and adding a debug message which I am overwriting here in that case to allow the Exception to propagate.
I am not sure this is the right place to catch the exception and additionally this might affect other cases as well which I am happy to address like non directory based hashes. Assuming this is the right place to catch the exception, happy to work on adding a test for this.
Fixes #6870 ? 
> Raise informative missing s3 extra

- dvc/api.py
- dvc/data/reference.py
- dvc/dependency/repo.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/git.py
- dvc/fs/local.py
- dvc/fs/path.py
- dvc/fs/repo.py
- dvc/ignore.py
- dvc/output.py
- dvc/repo/__init__.py
- dvc/repo/collect.py
- dvc/repo/diff.py
- dvc/repo/get.py
- dvc/repo/ls.py
- dvc/repo/metrics/show.py
- dvc/repo/plots/__init__.py
- dvc/repo/reproduce.py
- dvc/utils/__init__.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_experiments.py
- tests/func/test_external_repo.py
- tests/func/test_fs.py
- tests/func/test_ls.py
- tests/unit/fs/test_repo.py
- tests/unit/fs/test_repo_info.py
- tests/unit/test_external_repo.py
Initial migration to fsspec.
repofs is meant to only accept correct posix paths relative to the root of the repo, but I've left some logic to allow for abspath and ntpath support to have a bit more flexibility for users.
Future improvements:
* split repofs into overlayfs(fs + dvc) and subrepofs
* cleanup `__init__` logic
Fixes #7384
> repofs: base on fsspec

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/repo/params/show.py
- tests/func/parsing/test_foreach.py
- tests/func/parsing/test_interpolated_entry.py
- tests/func/test_import.py
- tests/unit/test_context.py
`parsing.Context` now only expects the path to always be relative path. To clarify, it's relative if it's a `LocalFileSystem` and relatively-absolute (relative to the root of the repo) in GitFileSystem, as opposed to being absolutely-absolute paths.
This expectation for Context to always get a relative path is managed in `DataResolver` for now, as changing anything in higher level may not be trivial.
This change, that it uses the relative path in `LocalFileSystem` and relatively-absolute paths in `GitFileSystem` does affect `dvc.params.diff()`. Before we were using same relative/absolute paths, which worked for both filesystems, but now we will receive the data in something like following format:
```json
{
"workspace": {
"data": {
"../test_params.yaml": {  # relative path from LocalFS …
```
> parsing: use relative paths; force absolute paths to relative

- dvc/fs/azure.py
- dvc/fs/fsspec_wrapper.py
- dvc/fs/gs.py
- dvc/fs/hdfs.py
- dvc/fs/webhdfs.py
No longer needed, as all of those filesystems already support callbacks.
Kudos @skshetry for pointing this out
> fs: get rid of CallbackMixin in azure/gs/hdfs/webhdfs 

- dvc/commands/completion.py
`dvc exp list` does not have `--all` or `-a` flag.
> completion: fix dvc exp completion on zsh/bash

- setup.cfg
Bumping PyDrive2 after a critical fix here https://github.com/iterative/PyDrive2/pull/164
I haven't seen people complaining about this in DVC, but it's not that easy even to connect a random "push stalls after one hour" with this issues. In PyDrive2 MT was in bad shape and after one hour when token update is happening multiple threads were reading / writing the same file or potentially leaving locks locked (thus making other threads locked forever -> performance gradually was degrading or going down to 0).
> bump pydrive: improves and fixes thread safety

- dvc/fs/local.py
- dvc/fs/path.py
- dvc/ignore.py
- tests/func/test_ignore.py
- tests/unit/test_ignore.py
We've been trying to avoid using `os.path.abspath` before, but we actually do need it in dvcignore for path normalization. So instead, we are introducing a primitive notion of `cwd` into our filesystems, that will be useful in other applications.
Note that even though fsspec doesn't officially support `cwd`, localfs does support it but in implicit manner, which requires us to have odd checks here and there around the code, which `Path.getcwd` will reduce in the future.
> dvcignore: use fs.path instead of os.path

- dvc/commands/experiments/ls.py
- dvc/commands/stage.py
- tests/unit/command/test_compat_flag.py
- tests/unit/command/test_experiments.py
Fixes #7570.
I think changing docs right now will make it more confusing, especially for users in old versions. So I'm proposing for not merging this for a few versions in https://github.com/iterative/dvc.org/pull/3453.
> stage/exp list: alias `--names-only` to `--name-only`

- dvc/commands/experiments/show.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/show.py
- tests/unit/command/test_experiments.py
Closes https://github.com/iterative/dvc/issues/5739
- `exp show` no longer requires acquiring the repo lock
- Add internal use `--no-fetch` option to disable fetching of exp refs for temp/queue experiments
- vscode extension triggers `exp show` on any changes to `refs/exps/...`, so `exp show` will end up triggering repeated calls to itself when fetching into `refs/exps`
- After this change vscode can wait for the refs to be updated by the completed `exp run` and then only call `exp show --no-fetch` once at that time (so the infinite recursive calls should be resolved)
Note that using `--no-fetch` disables active ref update for checkpoint runs in vscode. Currently in DVC there is no way to automate updating …
> exp show: lockless behavior

- dvc/repo/experiments/init.py
- tests/func/experiments/test_init.py
> exp init: Replace live section with metrics and plots.

- dvc/utils/threadpool.py
- tests/unit/utils/test_executors.py
Also adds a kwarg `cancel_on_error` on the constructor to support
cancelling futures on `shutdown`. This is not done by default to
be backward compatible with `concurrent.futures.ThreadPool` executor.
One has to opt-in into this by setting `cancel_on_error=True`:
```python
with ThreadPoolExecutor(cancel_on_error=True) as executor:
pass
```
Or, by using `shutdown(cancel_futures=True)`.
See discussion in https://github.com/iterative/dvc/pull/7412#discussion_r853714290.
> executors: add support for cancel_futures=True in Python<3.9

- dvc/commands/dag.py
- tests/unit/command/test_compat_flag.py
- tests/unit/command/test_dag.py
---
Now that `mermaid` [can be embedded in github md](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/):
```bash
dvc dag --md >> dag.md
cml send-comment dag.md
```
> dag: Add `--mermaid` and `--md` option.

- dvc/repo/stage.py
Minor change that adds a debugging log statement. This makes `dvc add -v` list the files it is walking, and makes it easier for a developer to find the folder that is making `dvc add` slow.
Motivating case: I was running `dvc add` on a directory, and it was taking a very long time (hours). The only info I got was that it was collecting stages, even after I ran it with a `-v`. I eventually realized there was a very large, nested folder that was not in my `.dvcignore` file, so `dvc add` was trying to walk that entire directory structure before it did anything else.
I would have realized this much quicker if `dvc add` had more info when `-v` was given. In fact, I wasn't originally sure what the issue was, I was tracking through the DVC code to see why `add` would be slow, and found this …
> Add log statement to collect repo

- tests/func/test_api.py
> tests: add test for dvc.api.open with remote

- dvc/fs/fsspec_wrapper.py
- dvc/fs/local.py
- tests/func/test_add.py
It is not completely fsspec compliant, but it's upto the level
required by our FSSpecWrapper.
Next thing to tackle would be to merge `fs.base.FileSystem`
and `fs.fsspec_wrapper.FSSpecWrapper` into one filesystem
that is lazily-loaded and is itself fsspec-compliant.
> fs: make localfs fsspec-compliant

- dvc/render/match.py
- tests/unit/render/test_match.py
> render.match: Skip errored revisions in `get_files`

- dvc/data/_progress.py
- dvc/data/db/local.py
- dvc/data/gc.py
- dvc/data/status.py
- dvc/objects/db.py
- tests/unit/remote/test_base.py
This PR gets rid of Tqdm progress bars inside `dvc.objects`.
Those are replaced with multi-phase callback in `hashes_exist`, and
simple callable that takes `completed` value in
`odb._estimate_remote_size()`.
The `odb.list_hashes_exists()` and `odb.all()` now return iterables,
hence the caller has the responsibility of handling progress.
This is now handled in `dvc.data` by using a custom `Tqdm` progressbar.
This is ugly and is temporary, but my motivation is to remove tqdm from dvc.objects
first. We can gradually get rid of these from `dvc.data` too, but
that requires more knowledge about `dvc.data` and involves more
design work. All in time, I guess. :)
> dvc.objects: add callbacks for listing and estimating hashes

- dvc/data/stage.py
- dvc/fs/_callback.py
- dvc/fs/base.py
- dvc/fs/utils.py
- dvc/progress.py
- dvc/utils/fs.py
1. This PR simplifies `fs.upload`/`fs.download`/`fs.download_file`.
2. Removes unused kwargs.
3. `download` uses `dvc.utils.threadpool.ThreadPoolExecutor` which
supports canceling futures.
4. `download` for directories supports nested/branched callbacks
and progress bars.
Closes #7412.
> fs.upload/download: simplify, remove unused kwargs, callbacks

- dvc/render/convert.py
- setup.cfg
- tests/integration/plots/test_json.py
Changes in dvc-render 0.0.5 caused an error.
In https://github.com/iterative/dvc-render/pull/24 the behavior for get_filled_template changed to return an empty string. Previously it returned a valid dictionary with empty `data` field.
Updated `to_json` logic in `dvc` to not call `get_filled_template` at all if there are no `datapoints`.
> `plots`: Fix repo with removed plots

- dvc/fs/oss.py
This var was never used. It came here when `OSSRemote` was introduced in #1961 by copying certain parts of `AzureRemote`.
https://github.com/iterative/dvc/blob/47400bba6f9de3345f1086fcd85948a071c32957/dvc/remote/azure.py#L42
https://github.com/iterative/dvc/blob/6882a781a4219559cff94a0d1dc6eb6144fb0a05/dvc/remote/azure.py#L97-L108
> fs.ossfs: remove unused var COPY_POLL_SECONDS

- dvc/data/stage.py
- dvc/fs/base.py
There is no support for chunk_size kwarg in `fs.open`.
Also, `upload_fobj` is now able to figure out proper
chunk size from fileobj, so I don't think we need this on `_upload_file`.
> fs: remove unused CHUNK_SIZE var

- dvc/fs/repo.py
- dvc/ignore.py
- dvc/utils/collections.py
PathStringTrie is error prone, as it gives you an illusion that you are working with paths, while it can't really handle important edge cases, which results in obscure bugs.
For example, when one sets `trie["/"] = "foo"`, we often expect `trie.longest_prefix("/path")` to return `"foo"`, while it is not actually like that, because `"/"` gets resolved into `("", "")` internal key, while `"/path"` is resolved into `("", "path")` and thus longest_prefix is `("",)`, which breaks our assumptions.
Instead, we should use regular `Trie` that doesn't create any illusions and forces user to be fully aware of his actions. We switched to `Trie`s long time ago in `scmrepo` and our data tree.
Additional logic change here is that our `Trie` is now based on the keys/paths relative to the repo root in both …
> dvc: use Trie instead of PathStringTrie

- dvc/fs/base.py
Before the function always expected the `size` kwarg to be passed (because it used `.pop()` instead of `.pop(..`, None)`), now it's part of a function signature which makes it clear it is an optional kwarg. 
The `size` kwarg may not always be passed, which would raise Exception here.
> fs.put_file: don't require size to be passed

- dvc/repo/experiments/pull.py
- dvc/repo/experiments/push.py
- dvc/repo/experiments/utils.py
- setup.cfg
- tests/func/experiments/test_remote.py
- tests/unit/repo/experiments/test_utils.py
fix: #7448
Current we skip on those experiments which already existed on both sides, but
do not exclude them from the result list. And if we have diverged experiment,
pulling/pushing them will stop the current progress and raise an exception, but
didn't give any information on the condition of other experiments.
1. Change the exp pull and push to match the new API in `scmrepo`.
2. Handle sync status after `exp pull/push` finished.
Co-authored-by:
Wait https://github.com/iterative/scmrepo/pull/59
> exp pull/push: better result handling in exp sharing(#7448)

- dvc/fs/repo.py
- dvc/repo/ls.py
Closes https://github.com/iterative/dvc/issues/5712.
> repofs: only use dvcfs when --dvc-only is specified

- setup.cfg
The callbacks on _get_file/_put_file was only supported on >2022.02.0.
Fixes #7669.
See https://github.com/fsspec/s3fs/pull/590.
> deps: bump s3fs to >=2022.02.0

- dvc/render/convert.py
- dvc/render/image_converter.py
- tests/integration/plots/test_json.py
- tests/unit/render/test_convert.py
In #7549 we rolled back to the behavior of writing images, instead of encoding them. I made it DVC's responsibility to provide proper path to the renderer. However, without knowing where we create HTML, it is impossible to do that. We need to modify `dvc-render` to be able to evaluate relative paths of the images. Marking as WIP, as we need a fix on `dvc-render` side first and a release.
> plots: image converter return absolute paths

- dvc/fs/base.py
- dvc/fs/local.py
`put`/`from_json`/`to_json` are major APIs that remain now. `open`/`walk`/`find`/`ls`/`info`/`rm` are not yet fsspec-compliant, which I am working on next. :)
> fs: add more fsspec methods

- dvc/output.py
- dvc/repo/imp_url.py
- dvc/repo/stage.py
- dvc/stage/__init__.py
- tests/func/test_add.py
- tests/func/test_commit.py
Fixes partially #7356 -- `dvc move` doesn't preserve many fields (description, remote, comments) but looks like a more involved change.
> dvcfile: preserve 'remote' on add and commit

- dvc/commands/repro.py
- dvc/commands/run.py
- dvc/commands/stage.py
Matching https://github.com/iterative/dvc.org/pull/3345
> `run/repro/stage add`: regroup options/flags

- dvc/fs/base.py
Untested 🌵, non-recursive implementation of `fs.put`. This should allow us to experiment with multiple objects transfer without using ThreadPoolExecutor for most of the _remote filesystems_. 
`recursive` is not really needed for DVC right now (the use case is `put_url` AFAICT). We can implement that after the migration. :)
> fs.put: introduce non-recursive async put

- dvc/fs/base.py
> FileSystem: handle `encoding` via `kwargs`.

- dvc/api.py
- dvc/fs/base.py
- dvc/fs/dvc.py
- dvc/fs/git.py
- dvc/fs/path.py
- dvc/fs/repo.py
- dvc/repo/__init__.py
- dvc/repo/collect.py
- dvc/repo/diff.py
- dvc/repo/get.py
- dvc/repo/ls.py
- dvc/repo/metrics/show.py
- dvc/repo/plots/__init__.py
- tests/unit/fs/test_dvc.py
- tests/unit/fs/test_repo.py
- tests/unit/fs/test_repo_info.py
This makes dvcfs/repofs much easier to work with and allows it to support
isabs/abspath/etc correctly, as previously any full path (with root_marker "")
would be impossible to distinguish from a relative one.
This also detaches external workspaces from the main repo workspace in
DvcFileSystem, which was necessary to be able to distinguish dvcfs abspaths
from local external output paths. Note that currently we still have limited
support for those (e.g. get/api supports them, but import doesn't) and this
change keeps it that way.
Pre-requisite for #7543
> repofs: use / as root_marker

- dvc/fs/_callback.py
Makes progress bar lazy, so this won't instantiate tqdm progress bars right away (unless `set_size`/`relative_update`/`absolute_update` are called).
As we don't use `rich` progressbar and we may lift the place where we create tqdm progress bars, I am not fixing it for now.
https://github.com/iterative/dvc/pull/7597#discussion_r867788542
> TqdmCallback: make it lazy

- dvc/repo/experiments/queue/local.py
- setup.cfg
Use `threads` pool instead of the default `prefork` (multiprocessing) pool in the exp celery worker.
Since we are always using `concurrency=1` (and scaling via worker instances and not pool concurrency), and CPU intensive work (during exp pipeline stage repro) is still done in separate processes, it is safe for us to use threads over multiprocessing. This should be more stable since it allows us to avoid any celery multiprocessing related issues on windows.
> exp: use celery threadpool worker instead of prefork

- dvc/fs/_callback.py
Tqdm supports `__bool__()`, so we should really use `is not None` test
rather than boolean check. This is not used anywhere right now, but
I'd prefer to be correct here.
> TqdmCallback: minor fixup, check for None explicitly

- dvc/data/checkout.py
- dvc/data/stage.py
- dvc/fs/_callback.py
- dvc/objects/db.py
- dvc/output.py
- dvc/repo/get.py
- dvc/stage/cache.py
- dvc/ui/_rich_progress.py
- dvc/utils/fs.py
- tests/func/test_fs.py
Fixes #7704.
1. Simplifies implementation of callbacks, since only `call()` modifies the progress bars now. Progress bars now use the `value`/`size` from `fsspec.Callback` instead of using their own state.
2. Ensures that `None` value in `relative_update`/`absolute_update` does not break callbacks. This means that now we can guarantee that `value` will always be int. This is useful for filesystems that are not very compliant.
3. Gives the same treatment done in #7715, makes rich callbacks lazy. Note that we don't use them anywhere yet.
4. Adds a test for that particular issue.
Note that `size` can be `None`, this has to be handled in respective callbacks, `TqdmCallback` now uses `update_to` which handles them, `RichCallback` also handles those well.
> fs.callbacks: simplify, ensure `None` does not break them, lazy richcallbacks

- dvc/repo/ls.py
- tests/func/test_ls.py
> dvc ls: not raise PathMissingError on empty dir.

- dvc/repo/ls.py
- tests/func/test_ls.py
```
2022-05-11T08:38:52.3563156Z ================================== FAILURES ===================================
2022-05-11T08:38:52.3563536Z ______________ test_ls_repo_with_removed_dvc_dir_with_path_file _______________
2022-05-11T08:38:52.3564566Z [gw0] win32 -- Python 3.8.10 C:\hostedtoolcache\windows\Python\3.8.10\x64\python.exe
2022-05-11T08:38:52.3564805Z 
2022-05-11T08:38:52.3565269Z tmp_dir = WindowsTmpDir('C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_ls_repo_with_removed_dvc_3')
2022-05-11T08:38:52.3566004Z dvc = Repo: 'C:\Users\runneradmin\AppData\Local\Temp\pytest-of-runneradmin\pytest-0\popen-gw0\test_ls_repo_with_removed_dvc_3'
2022-05-11T08:38:52.3566746Z scm = Git: 'C:\Users\runneradmin\AppData\Local\Temp\pytest-of-runneradmin\pytest …
```
> Revert "dvc ls: not raise PathMissingError on empty dir."

- dvc/config.py
- dvc/external_repo.py
- dvc/fs/git.py
- dvc/fs/local.py
- dvc/fs/path.py
- dvc/fs/repo.py
- dvc/ignore.py
- dvc/output.py
- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/pathspec_math.py
- dvc/repo/__init__.py
- dvc/repo/brancher.py
- dvc/repo/collect.py
- dvc/repo/diff.py
- dvc/repo/params/show.py
- dvc/repo/plots/__init__.py
- dvc/repo/stage.py
- dvc/stage/loader.py
- dvc/stage/utils.py
- dvc/utils/__init__.py
- setup.cfg
- tests/func/experiments/test_experiments.py
- tests/func/parsing/test_resolver.py
- tests/func/test_fs.py
- tests/func/test_ignore.py
- tests/func/test_used_objs.py
- tests/unit/stage/test_utils.py
- tests/unit/test_external_repo.py
- tests/unit/test_ignore.py
Our gitfs paths are currently tied to the local path in which the cloned
repository resides in, which results in a lot of hacky assumptions throughout
the code.
This PR detaches gitfs from local paths completely, making dvc work with a
proper fsspec gitfs implementation.
Part of #7543
> dvc: detach gitfs from local paths

- dvc/fs/data.py
- dvc/fs/repo.py
- dvc/repo/__init__.py
- dvc/repo/get.py
- tests/unit/fs/test_data.py
Current naming for `DvcFileSystem` and `RepoFileSystem` is confusing, because
dvc is not only about data and it is much more natural to expect something
named `dvcfs` to include complete view for your whole repo (including git
files), which is what `repofs` is doing right now.
`DvcFileSystem` can provide a view not only for the repo data, but also for
external data (e.g. local external outputs). So it makes more sense to call
it a `DataFileSystem`, since it really represents the data management side
of dvc.
`RepoFileSystem` will be renamed into `DvcFileSystem` separately, to not
make this even more confusing.
Pre-requisite for #5162
> fs: rename DvcFileSystem to DataFileSystem

- dvc/data/stage.py
- dvc/data/tree.py
- dvc/objects/hash_info.py
- tests/func/test_commit.py
- tests/func/test_external_repo.py
- tests/func/test_gc.py
- tests/func/test_odb.py
- tests/func/test_remote.py
- tests/func/test_stage.py
- tests/unit/test_hashinfo.py
When staging a directory, always save a "raw dir object" to the odb. If the corresponding ".dir" object has not been added to the odb, `stage()` calls can load the tree from the raw dir object instead of rebuilding it by walking the directory.
This can lead to significant speed improvements when calling `dvc status` for modified directories.
Fixes #7390
> dvc.data: save and try loading raw dir objects

- dvc/data/db/index.py
- dvc/objects/cache.py
- tests/unit/objects/test_cache.py
It turns out that diskcache.Disk saves passed arguments to the database
and uses that all the time. So this means that we are not forward
compatible as it breaks moving from newer version of DVC to an older
one. We don't promise this, but this breaks our benchmarks which
are probably not isolated enough.
Regarding the use of cache, it is a bit iffy to extend it this way.
We only need this type for error messages (see https://error.dvc.org/pickle). We could consider removing
this, but since the error message is documented and it's not too hard
to extend this 😅, I decided to preserve the message.
Should fix failing test `test-pull` in https://github.com/iterative/dvc-bench/pull/347.
> dvc.objects.cache: set type in a more compatible way

- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/local.py
- dvc/repo/experiments/remove.py
- tests/unit/repo/experiments/queue/test_local.py
fix: #7587
1. Add implement kill method for local queue class
2. Add a test to make sure the following job will be success after the
original job was killed.
> exp: implement internal queue.kill support(#7587)

- dvc/objects/fs/implementations/http.py
- dvc/objects/fs/implementations/ssh.py
Note that this will change the behaviour of DVC to always show
prompt even in --quiet mode, which is what we need.
Previously it'd prompt without any message.
I am trying to reduce dependency in DVC.
> objects.fs: use getpass for prompts

- dvc/cli/__init__.py
- dvc/fs/__init__.py
- dvc/objects/fs/base.py
- dvc/objects/fs/errors.py
- dvc/objects/fs/implementations/azure.py
- dvc/objects/fs/implementations/gdrive.py
- dvc/objects/fs/implementations/hdfs.py
- dvc/objects/fs/implementations/http.py
- dvc/objects/fs/implementations/s3.py
- dvc/objects/fs/utils.py
- tests/unit/fs/test_s3.py
* Introduce ConfigError and AuthError in dvc.objects.fs and raise it
instead of dvc.config.ConfigError.
* Provide hints and links by catching those errors in dvc.cli.main,
i.e decouple UI messages from filesystems for AuthError and
ConfigError.
* Copy flatten/unflatten utils to dvc.objects.fs.utils.
* Avoid `format_link` and `fix_env` in filesystems.
> objects.fs: do not use format_link, DvcException and fix_env from DVC

- dvc/objects/fs/path.py
calling `parts()` to get name requires a lot of unnecessary splitting, which quickly adds up when dealing with large datasets.
> objects.fs: use split in Path.name

- dvc/cli/parser.py
- dvc/commands/queue/__init__.py
- dvc/commands/queue/kill.py
- dvc/commands/queue/remove.py
- tests/unit/command/test_queue.py
fix: #7591
1. Add a new command `dvc queue`
2. Add two sub-command `dvc queue remove` and `dvc queue kill`
3. Add a unit test to test them
wait for #7714
> exp queue: Add two command `queue remove` and `queue kill`

- dvc/commands/queue/__init__.py
- dvc/commands/queue/start.py
- dvc/commands/queue/stop.py
- tests/unit/command/test_queue.py
fix: #7589
1. Add two sub-command `dvc queue start` and `dvc queue stop`
2. Add a unit test to test them
Status is too complex for a CLI PR. Would implement this part later.
> exp queue: Add two command queue start and stop

- dvc/cli/__init__.py
- dvc/data/checkout.py
- dvc/data/stage.py
- dvc/dependency/repo.py
- dvc/exceptions.py
- dvc/objects/_ignore.py
- dvc/objects/state.py
- dvc/objects/utils.py
- dvc/output.py
- dvc/repo/diff.py
- tests/func/test_external_repo.py
- tests/func/test_ignore.py
- tests/unit/cli/test_main.py
This PR:
* defines a `Ignore` protocol in `dvc.objects`, that expects a `find` method.
This will be used in dvc-data and dvc-objects instead of depending on dvc.ignore.
dvcignore is expected to respect this protocol, which it does.
* renames `dvcignore` kwarg to `ignore` in `dvc-data` and `dvc-objects`.
* teaches dvc.cli that `IgnoreInCollectedError` is a known exception
and is logged correctly and adds a test for the behaviour.
I am not happy that we need to hardcode `.dvcignore` in dvc-objects
but I don't see any easy way, since we always try to avoid
staging if the tree contains .dvcignore file, even if .dvcignore
is not passed.
> dvc.objects: use stub ignore in dvc.objects/dvc.data

- dvc/data/db/local.py
- dvc/data/transfer.py
- dvc/data/tree.py
- dvc/data_cloud.py
- dvc/output.py
- tests/func/test_remove.py
transfer raises internal TransferError, merge raises internal MergeError
and local ODB raises ODBError on unprotect.
transfer's error is reraised to FileTransferError back in DataCloud.
> dvc.data: use own internal error instead of DvcException

- dvc/data/db/__init__.py
- dvc/data/reference.py
- dvc/fs/__init__.py
- dvc/objects/fs/__init__.py
- dvc/odbmgr.py
- dvc/repo/__init__.py
- dvc/repo/experiments/executor/ssh.py
- dvc/testing/fixtures.py
- dvc/testing/test_workspace.py
- tests/func/test_add.py
- tests/func/test_get.py
- tests/func/test_import.py
- tests/func/test_odb.py
- tests/func/test_repo.py
- tests/unit/stage/test_cache.py
This moves get_fs_config/get_fs_cloud and ODBManager to DVC as they require DVC related utilities, and we don't need them strictly in dvc-objects/dvc-data.
This also adds support to ReferenceHashFile to load from any filesystem, using it's module name and filename.
Now we can get rid of DVCFileSystem dependency in ReferenceHashFile. This is a temporary solution, we really need a registry.
(I am not quite sure if this works in pyinstaller mode, but I think it should, it's how fsspec does it if I understand correctly. Anyway, I am willing to take risk here.)
> fs/data: move repo related utils to dvc

- dvc/data/_progress.py
- dvc/data/checkout.py
- dvc/data/db/reference.py
- dvc/data/stage.py
- dvc/data/transfer.py
- dvc/fs/_callback.py
- dvc/fs/callbacks.py
- dvc/fs/data.py
- dvc/fs/dvc.py
- dvc/objects/_tqdm.py
- dvc/objects/db.py
- dvc/objects/fs/base.py
- dvc/objects/fs/callbacks.py
- dvc/objects/fs/generic.py
- dvc/objects/fs/implementations/http.py
- dvc/objects/fs/implementations/ssh.py
- dvc/objects/fs/utils.py
- dvc/objects/hash.py
- dvc/output.py
- dvc/repo/get.py
- dvc/stage/cache.py
- dvc/utils/fs.py
- tests/func/test_fs.py
Now dvc.objects and dvc.data uses the implementation from dvc.objects for Tqdm progress bars. This is temporary, until we have callbacks. :)
> objects: use separate Tqdm implementation

- dvc/data/gc.py
- dvc/data/status.py
- dvc/data/transfer.py
- dvc/data/tree.py
- dvc/data_cloud.py
- dvc/objects/db.py
Also introduces a `validate_status` kwarg in `data.transfer`,
which is used in DVC to log for missing version info. Just leaving as is was making some tests flaky in DVC, so I had to engineer this hack. 🥲 
We still have two warnings:
https://github.com/iterative/dvc/blob/82dc67d8909611048ab6839a68475d4c659516ac/dvc/data/checkout.py#L264-L267
https://github.com/iterative/dvc/blob/82dc67d8909611048ab6839a68475d4c659516ac/dvc/objects/fs/implementations/gdrive.py#L149-L154
I have left them out, and was not able to figure out some way to avoid these.
> data/objects: reduce log levels in dvc-objects and dvc-data

- dvc/commands/plots.py
- dvc/render/match.py
- dvc/repo/plots/__init__.py
- pyproject.toml
> formatting/isort: consider dvc-render as a known first party for ordering imports

- dvc/stage/cache.py
- dvc/testing/test_run_cache.py
Source filesystem was being used to transfer file to destination instead of the destination's filesystem.
This was working for LocalFileSystem as they work for any directories/path.
It's hard to test this these days, as we don't have remote tests inside dvc, so it was not caught.
Potentially fixes #7718.
> dvc.stage.cache: fix typo, was using src filesystem to transfer

- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/local.py
- tests/unit/repo/experiments/queue/test_local.py
1. Add some more unit test for `celery_queue.kill`
2. Implement `kill` argument for `celery_queue.shutdown`
> exp: implement `celery_queue.shutdown(kill=...)`

- dvc/commands/experiments/show.py
- dvc/commands/queue/__init__.py
- dvc/commands/queue/attach.py
- dvc/commands/queue/status.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/local.py
- dvc/repo/experiments/remove.py
- tests/unit/command/test_queue.py
fix: #7590
1. Add two new command `queue status` and `queue attach`
2. Add unit test for the CLI
Status is too complex for a CLI PR. Would implement this part later.
> exp queue: monitor queue status

- .github/workflows/benchmarks.yaml
- .github/workflows/packages.yaml
- .github/workflows/tests.yaml
- dvc/commands/experiments/init.py
- dvc/info.py
- dvc/proc/manager.py
- dvc/testing/fixtures.py
- dvc/utils/strictyaml.py
- setup.cfg
- tests/dir_helpers.py
- tests/func/machine/test_machine_config.py
- tests/func/test_ignore.py
- tests/integration/plots/test_json.py
- tests/unit/command/test_experiments.py
- tests/unit/command/test_machine.py
- tests/unit/fs/test_ssh.py
- tests/unit/remote/test_http.py
- tests/unit/test_analytics.py
- tests/unit/utils/test_collections.py
Particularly, we already had to drop it in `dvc-objects` and `dvc-data` because of the overhead of trying to support 3.7 in conda packages.
Also upgraded with `pyupgrade --py38-plus`
Fixes #7708
> dvc: drop python 3.7

- dvc/testing/fixtures.py
See https://docs.python.org/3/library/shutil.html#shutil.copytree. There is `dirs_exist_ok` kwarg in Python >3.8.
> testing: use shutil.copytree with dirs_exist_ok

- dvc/commands/plots.py
- dvc/render/match.py
- dvc/repo/plots/__init__.py
- tests/unit/command/test_plots.py
- tests/unit/render/test_match.py
We were forgetting to pass the default template dir.
Fixes #7817.
> plots: Pass `templates_dir` to `match_renderers`.

- setup.cfg
- tests/func/test_api.py
- tests/func/test_external_repo.py
- tests/func/test_get.py
- tests/func/test_import.py
- tests/func/test_ls.py
- tests/func/utils/test_strict_yaml.py
`scmrepo==0.0.23` includes proper support for windows file:// URLs (https://github.com/iterative/scmrepo/pull/68), so Windows tests relying on file URLs had to be fixed in order to be valid [RFC 8089](https://datatracker.ietf.org/doc/html/rfc8089) file URLs.
Closes #7833.
> bump scmrepo to 0.0.23

- dvc/repo/experiments/apply.py
- dvc/repo/experiments/executor/local.py
- dvc/scm.py
- tests/unit/scm/test_scm.py
Will close #7547 
Depends on https://github.com/iterative/scmrepo/pull/75
```
$ dvc exp run
ERROR: Merge analysis failed: Cannot merge in shallow Git repo. See <https://dvc.org/doc/user-guide/troubleshooting#git-shallow> for more information.
```
> exp: output troubleshooting link on shallow merge failure

- README.rst
Update the package installation guide according to the latest [documentation](https://dvc.org/doc/install/linux#install-from-repository).
> docs: update the package installation guide

- dvc/render/match.py
- tests/func/test_live.py
- tests/unit/render/test_match.py
- tests/unit/test_plots.py
Seems like `dpath.util.search` is really slow. Tried modifying the code to stop using `search` and use `dpath.util.get` instead. There was a significant improvement (4x) but still seemed unreasonably long. Ended up implementing this method myself. 
We are still using `dpath.util.new` but its influence is orders of magnitude smaller than "reading" methods.
test repository:
```bash
#!/bin/bash
set -exu
pushd $TMPDIR
wsp=test_wspace
rep=test_repo
rm -rf $wsp && mkdir $wsp && pushd $wsp
main=$(pwd)
mkdir $rep && pushd $rep
git init
dvc init
echo "numpy" >> requirements.txt
pip install -r requirements.txt
git add -A
git commit -am "init"
echo -e "p: 1" > params.yaml
echo -e "from random import random
import numpy as …
```
> plots: grouping: stop using dpath.util.search

- dvc/repo/brancher.py
- tests/func/test_diff.py
> brancher: use scm.root_dir to determine relative cwd

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/plots/diff.py
When large untracked directories are present in the workspace, a lot of time is spent collecting untracked files in `scm.status` and `scm.is_dirty` (which also calls `status`). `scmrepo==0.0.23` adds `untracked_files=no` flag which avoids collecting untracked files.
> exp: speed up repro execution with untracked directories in workspace

- dvc/commands/experiments/init.py
- dvc/repo/experiments/init.py
- tests/func/experiments/test_init.py
- tests/unit/command/test_experiments.py
Related to https://github.com/iterative/dvc/pull/7740#issuecomment-1127631757.
This PR creates output directories (but not any files) during `dvc exp init`, which accomplishes:
1. Avoiding errors when trying to Git-ignore those outputs.
2. Making it easier for users to generate outputs without needing to generate the parent directories.
```console
$ dvc exp init --metrics eval.json --plots eval/scalars --models models/predict.h5 python train.py
Creating dependencies: src, data and params.yaml
Creating output directories: eval/scalars and models
Creating train stage in dvc.yaml
Ensure your experiment command creates eval.json, eval/scalars and models/predict.h5.
You can now run your experiment using "dvc exp run".
```
> exp init: create output dirs

- dvc/scm.py
`fetch_all_exp()` in `clone()` was called with `url="origin"`, which resulted in the operation being performed with the remote URL defined in the cloned repo's config, which did not include any credentials initially provided to clone.
Fixes #7670
> scm: fix clone

- dvc/stage/cache.py
We were passing paths with '\\' in the filename instead of posix paths to
remote filesystems which were causing failures to upload.
Although in some filesystems, this was failing silently, so upload would seem
to have passed, but the download later would fail.
> run-cache: fix push from Windows to remote filesystems

- dvc/stage/cache.py
- dvc/testing/test_remote.py
Currently, there is no way to find run-cache in HTTP remotes.
In the future, we could use directory listings from supported
webservers to find files.
Temporarily, we are restricting the run-cache uploads. This is a bit
strict, we could have only restricted the downloads, but it might be
more confusing to the users, so I went to categorically restrict
stage cache uploads and downloads for http filesystems.
~~waiting for #7873 to get merged.~~
> run-cache: http: restrict uploads/downloads

- dvc/commands/queue/status.py
- tests/unit/command/test_queue.py
1. use a short rev to represent tasks
2. Add a unit test for the result shown
> queue status: use a short rev to represent tasks

- dvc/commands/queue/remove.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/local.py
- dvc/repo/experiments/remove.py
fix: #7840
Now queue remove can not accept short rev as name.
1. Refactor the queue entry match in `queue remove`
2. Better output if no queue task found for name.
3. short rev on kill can only be work for rev with lens longer than 4
coming from a wrongly closed PR #7841
> queue remove: add remove support for short revs(#7840)

- dvc/repo/experiments/queue/local.py
Currently, all of our celery workers are called `dvc-exp-worker` and
they will write to the same log path.
We give every single worker a unique name and seperate they logs.
> queue start: give every worker a unique name

- README.rst
Combined two paragraphs of intro into one
> readme: consolidate intro

- dvc/repo/experiments/apply.py
- setup.cfg
- tests/func/experiments/test_experiments.py
Untracked files are now preserved on `exp apply`
- With `--force` (default), if a file currently untracked in the workspace exists in the experiment to apply, the experiment version will replace the workspace version. If the untracked file does not exist in the experiment, the workspace version is preserved after applying the experiment.
- With `--no-force`, workspace state for untracked files is preserved (`apply` will fail due to conflicts if the file exists in the experiment)
Fixes #6930
> exp apply: preserve untracked files

- dvc/commands/queue/start.py
- dvc/commands/queue/status.py
- dvc/repo/experiments/queue/local.py
fix: #7950
Currently queue worker status are not show in `queue status` makes it
hard to tell if the worker is still living.
1. add a new method `active_worker` to return the currently running
worker node name.
2. give every worker a unique name.
3. `queue status` will show how much worker running at present.
Some tests are still required for this change.
> queue status: will show the current worker status

- dvc/commands/plots.py
- dvc/config_schema.py
- tests/integration/plots/test_json.py
* [x ] ❗ I have followed the [Contributing to DVC](https://dvc.org/doc/user-guide/contributing/core) checklist.
This PR allows users to set output directory for `dvc plots show` via `dvc config`. I added a test covering this scenario. 
To test run the following script:
```
#!/bin/bash
set -ex
rm -rf repo
mkdir repo
pushd repo
echo '[{"first_val": 100, "val": 2}, {"first_val": 200, "val": 3}]' >> metric.json
dvc config plots.out_dir config_dir
dvc plots show metric.json
dvc plots show -o arg_dir metric.json
```
> dvc plots: allow for setting output directory via config

- dvc/fs/__init__.py
- tests/unit/remote/test_remote.py
Fixes #1626. There was a `core.jobs` option that's not supported by the schema nor documented. I guess it was intended to apply across multiple remotes, but nobody has asked about it, so I'm proposing to remove it and close the issue.
> config: remove core.jobs dead code

- tests/unit/command/test_queue.py
Followed by #7903
Add a new unit test to increase the coverage of test
> queue status: add some unit test to increase the coverage

- dvc/render/image_converter.py
- tests/unit/render/test_image_converter.py
> render: image_converter: Support slash in revision.

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/local.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/queue/tasks.py
- dvc/repo/experiments/queue/tempdir.py
- dvc/repo/experiments/queue/workspace.py
- dvc/repo/experiments/run.py
- dvc/repo/experiments/show.py
- setup.cfg
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_remove.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_queue.py
- tests/unit/repo/experiments/conftest.py
- Separates `--temp` from the celery queue (preserves existing support for one-off standalone exp runs outside of the workspace)
- `exp show`: Running standalone temp directory runs are now labeled as `tempdir` in the `Executor` column (previously was `temp`)
- `exp show`: Running dvc-task/celery queued runs are now labeled as `dvc-task` in the `Executor` column (previously was `temp`)
related: https://github.com/iterative/dvc/issues/7592#issuecomment-1153869162
> exp: support standalone (non-queued) `--temp` runs

- .git_archival.txt
- pyproject.toml
- setup.cfg
setuptools_scm can now work with git archives, so we don't need this plugin.
See https://github.com/pypa/setuptools_scm#git-archives.
> deps: remove setuptools_scm_git_archive

- dvc/commands/update.py
Seems like the help text predated `import-url`, so expanded it to also include `import-url` updates.
> Help text for `dvc update`

- dvc/analytics.py
- dvc/commands/freeze.py
- dvc/commands/get_url.py
- dvc/commands/ls/__init__.py
- dvc/config.py
- dvc/daemon.py
- dvc/data_cloud.py
- dvc/dvcfile.py
- dvc/output.py
- dvc/prompt.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/pull.py
- dvc/repo/experiments/push.py
- dvc/repo/gc.py
- dvc/repo/reproduce.py
- dvc/repo/scm_context.py
- dvc/repo/status.py
- dvc/stage/__init__.py
- dvc/stage/imports.py
- dvc/ui/pager.py
- dvc/updater.py
> logger: use lazy formatting

- dvc/commands/queue/remove.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/queue/remove.py
- dvc/repo/experiments/queue/workspace.py
- dvc/repo/experiments/remove.py
- dvc/repo/experiments/stash.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_queue.py
- tests/unit/command/test_queue.py
- tests/unit/repo/experiments/queue/test_remove.py
Followed from [#7592](https://github.com/iterative/dvc/issues/7592#issuecomment-1157176923) 
1. Seperate `remove` method to a new file.
2. Add `queued`, `failed`, `processed` flags to remove.
3. Add new unit tests for `queue status --queue/fail/success`
4. Implement methods to remove done tasks.
5. add two new unit test for `celery_queue.remove`
6. bump into dvc-task version 0.0.13
A demo for this PR.
[![asciicast](https://asciinema.org/a/PCejdbblayS3hkBmiRZmRTAwB.svg)](https://asciinema.org/a/PCejdbblayS3hkBmiRZmRTAwB)
> queue remove: can remove successed,failed tasks msgs

- dvc/config_schema.py
- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/parsing/interpolate.py
- tests/func/parsing/test_errors.py
- tests/func/parsing/test_interpolated_entry.py
Allow to use dictionaries as values for template interpolation but only inside the `cmd` key.
Given the following params.yaml and dvc.yaml:
```yaml
dict:
foo: foo
bar: bar
```
```yaml
stages:
stage1:
cmd: python script.py ${dict}
```
The dictionary will be unpacked with the following syntax:
```yaml
stages:
stage1:
cmd: python script.py --foo foo --bar bar
```
Closes #6107
> parsing: Support dict unpacking in `cmd`.

- dvc/repo/metrics/show.py
- tests/func/metrics/test_show.py
Fixes #6402
I haven't forbidden `.py` files as suggested there because it just seemed like it would clutter the code more than it would add any real value, but I can do so if requested.
> metrics: support TOML files

- dvc/output.py
- tests/func/test_ignore.py
Fixes #7374
Note that there are many places the `ignore` argument could be added instead. This is the deepest call, right before delegating to `dvc_data`. Not sure if that's the right choice.
Will add tests soon.
> checkout: use dvcignore

- tests/__main__.py
Having 300+ lines reporting durations of `0.X` seconds doesn't feel helpful in the CI context and makes the navigation of the logs cumbersome. 
The flag can still be overridden locally.
> tests: limit printed durations to 50

- setup.cfg
It seems there is a typo in `webhdfs_kerberos` extras.
> Update setup.cfg: typo in `webhdfs_kerberos` extras

- README.rst
Removing table of contents from readme. It takes up too much space at the top and shouldn't be needed if the readme is brief (it probably needs to be shorter) and well organized.
> readme: drop table of contents

- dvc/cli/command.py
- dvc/cli/parser.py
- dvc/commands/data.py
- dvc/repo/__init__.py
- dvc/repo/data.py
- setup.cfg
- tests/func/test_data_status.py
- tests/unit/command/test_compat_flag.py
- tests/unit/command/test_data_status.py
See [Consolidate Repo Status](https://www.notion.so/iterative/Consolidate-repo-status-ed3cd60f706f4fcaba1d3f3cac1498e9).
> introduce new data:status command

- dvc/repo/experiments/executor/local.py
- tests/unit/repo/experiments/queue/test_local.py
fix: #8031
Currently when we use tmp directory to run a experiment, we set
`EXEC_HEAD` , `EXEC_BASELINE` and `EXEC_MERGE` heads locally but forget
to remove it. This cause some problem when we use `exp show`
1. Clean `EXEC_HEAD` , `EXEC_BASELINE` and `EXEC_MERGE` after we pushed
them to tmp_dir
2. Add a unit test for it.
Co-authored-by:
> queue: clean local `EXEC_HEAD` & `EXEC_BASELINE` after we use temp dir to run experiment.

- dvc/cli/__init__.py
- dvc/logger.py
`dvc <command> | head` for example could fail with SIGPIPE and
would print a traceback with BrokenPipeError exception. Now we
redirect do /dev/null in case of error as suggested in Python's
docs: https://docs.python.org/3/library/signal.html\#note-on-sigpipe.
I am not sure how to unit-test this, so moving ahead without one.
> cli/log: handle SIGPIPE errors

- dvc/commands/data.py
- tests/unit/command/test_data_status.py
`--untracked-files` and `--unchanged` coupled with `--granular`
puts a lot of stress on `_show_status`. Currently, with those options,
dvc spends ~26s on `_show_status` function.
Unhappy with the above result, I looked into improving the situation by using
`console.out(highlight=False)`. It did reduce that to 9s but it still felt like a lot.
Then I dropped to good old colorama, which dropped to 3s(term)/1.24(redirected).
I tested with buffering output which dropped this further to ~600ms(term)/~100ms(redirected).
Note that this result was in VSCode which is slower than other terminals.
In gnome-terminal, I get about 175ms, and in kitty, it is around 125ms (undirected).
This may seem like premature optimization, but this was preventing me
from figuring out perf issues in granular outputs, …
> data status: optimize printing status list

- dvc/repo/data.py
`dvc-bench` shows that `diff` is slow (even for noop). The non-granular status takes 5.7634s, so the rest of 19s is from `diff`.
```console
Name (time in s)                                                   Min                Max               Mean            StdDev             Median               IQR            Outliers     OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_data_status-data-noop[2.15.0-all_flags] (0001_test_da)     24.9396 (4.33)     24.9396 (4.33)     24.9396 (4.33)     0.0000 (1.0)      24.9396 (4.33)     0.0000 (1.0)           0;0  0.0401 (0.23)          1 …
```
> data status: add spinners during diff

- dvc/repo/experiments/queue/workspace.py
- tests/func/experiments/test_experiments.py
fix: #8045
Not sure, whether workspace can be `fail`?
> exp run: workspace status wrong

- dvc/repo/experiments/queue/celery.py
> queue: missing `f` format for the error message.

- dvc/output.py
This PR reverts f-strings to  lazy string formatting in the logger call
Related: https://github.com/iterative/dvc/pull/8073
> Revert to lazy formatting introduced in #8073

- dvc/commands/experiments/remove.py
- dvc/commands/queue/remove.py
- dvc/repo/experiments/queue/remove.py
- dvc/repo/experiments/remove.py
- tests/func/experiments/test_queue.py
- tests/unit/command/test_experiments.py
- tests/unit/command/test_queue.py
- tests/unit/repo/experiments/queue/test_remove.py
- tests/unit/repo/experiments/test_remove.py
will 
fix: #8018
fix: #8071
1. Replace the `_clear_queue` function with `celery_queue.clear`
2. Decouple queue clear and remove commands
3. Make a better API for `dvc.repo.experiments.queue.remove.py` ( Unify remove queued and remove done)
4. Make `exp remove` flags and arguments mutually exclusive.
5. Refactor dvc.repo.experiment.remove to make matching exp by name also return queue entry info.
6. Add one line to make `exp remove` can remove failed tasks, and will also delete associated successful tasks
7. Add a new unit test for this behavior.
[![asciicast](https://asciinema.org/a/B4euzD75a9fXOdf0gedqC1S2u.svg)](https://asciinema.org/a/B4euzD75a9fXOdf0gedqC1S2u)
The document also needs some updates later.
> exp remove: support removing failed tasks and associated successful tasks

- dvc/repo/params/show.py
- tests/func/api/test_params.py
Also, fix when `deps=True` and no params in the entire pipeline.
Closes #8064
> api: Fix params_show when stage has no params

- dvc/lock.py
- tests/func/test_lock.py
Fixes  `'NoneType' object has no attribute 'close'` on running multiple `repro` in parallel when they compete for resources and one of them fails to acquire the lock back.
- Double unlock is not allowed and now raises an explicit better `DvcException`. This is aligned with usual lock semantics and we want to keep as much of it as possible so that we detect missing `lock()` calls, or some misplaced unlocks, etc.
- Unlock on an unlocked is allowed _only_ if this lock failed last time we tried to acquire it. This is unfortunate, but should be more or less safe. This is the best we can do considering the way we lock, unlock stuff in stages now.
> fix logic for unlock on unlocked lock calls

- dvc/repo/experiments/queue/celery.py
- tests/unit/repo/experiments/queue/test_local.py
fix: #8014
> ERROR: Invalid experiment '{entry.stash_rev[:7]}'.
This happens when the queue task failed from a scm error.
{"exc_type": "GitMergeError", "exc_message": ["Cannot fast-forward HEAD
to '05100047a341f2fa4a02421289d48f84d8c45e86'"], "exc_module": "dvc.scm"}.
And the failed task neither create a infofile nor create a fail_stash.
1. Didn't raise DvcException if no infofile found for failed tasks.
(success tasks still raise it)
2. Add a new unit test for this.
> queue status: ERROR: Invalid experiment

- dvc/repo/experiments/queue/base.py
- tests/unit/repo/experiments/queue/test_local.py
fix: #8059
1. showing final experiment name in `queue status` for successful tasks.
2. Add a unit test for `celery_queue.status`
> queue status: show final experiment name

- tests/func/test_lock.py
Minor followup cleanup after the #8105
> Lock test name fix

- dvc/repo/data.py
We were only joining paths when `new_obj` was a tree. But technically they could be absent from the workspace or cache which prevented from path joining, hence all of the items inside a tree would show up with the root's name. Now, we check for either-or.
Fixes #8053.
Another tricky thing here that I have ignored for now is, what happens if the old obj was a tree and the new obj is a hashfile? Currently `diff` does not work with non-tree objects (i.e. hashfile), so we'd have to handle that here if we decided to support this (which we should but not here).
> data status: handle path joining properly for tree leaves/items

- dvc/repo/scm_context.py
Make from this:
this:
we don't really use `expandtabs` much, and especially not for these messages
> stage add: fix hint message consistency

- tests/func/experiments/test_queue.py
This is a flaky, the queue tasks status might remain "Running" even if
it had already been completed, beside sometimes I also noticed it raise
a pytest fixture error.
> Add flaky to a queue related test.

- dvc/repo/experiments/__init__.py
Part of #8116:
> * UI / Terminology - I got completely confused with `Reproduced experiment`. I thought this is about run cache, or some existing experiments, etc. Why do we use `reproduced` for a completely new experiment, for example? And when it actually doesn't create a new experiment (since probably detects an existing one) it doesn't say anything at all. cc @dberenbaum
> exp run: ui tweak

- dvc/repo/reproduce.py
- tests/unit/repo/test_reproduce.py
> exp run: account for repo root when staging git-deps

- dvc/rwlock.py
- dvc/stage/decorators.py
- tests/unit/test_rwlock.py
User were getting:
```python
dvc.rwlock.RWLockFileCorruptedError: Unable to read RWLock-file '.dvc/tmp/rwlock'. JSON structure is corrupted
```
when running multiple pipelines in parallel. 
The reason for this is again our `unlocked(cmd)` logic, which fails to acquire the `repo.lock` back if other pipelines are doing some heavy stuff or there are too many of them. It means that, `rwlock` on context manager exit is cleaning up itself while repo is not protected. Multiple processes could write simultaneously.
Overall, proper locking is pretty hard. I don't see good options for Python in terms of IPC or something that would be potentially faster / more reliable (could cleanup itself if process fails). For now I think, it's better to have this as a workaround, until we reconsider this …
> Guard rwlock file to prevent not locked repo edits

- scripts/build-requirements.txt
5.2 didn't fix https://github.com/iterative/dvc/issues/7949
Need to research proper fix for the hook
> pyinstaller: Restrict to 5.0

- dvc/info.py
Registry might raise an `ImportError` if plugin is not installed.
> doctor: ignore missing plugins

- dvc/fs/__init__.py
- dvc/info.py
- setup.cfg
When we get to release 0.1.21, this should be ready. GHA outage is preventing me from making one.
> deps: bump dvc-data to 0.1.21

- .github/workflows/packages.yaml
Package building is failing, see https://github.com/iterative/dvc/runs/7933069474?check_suite_focus=true#step:5:481:
```console
ERROR:  Error installing fpm:
public_suffix requires Ruby version >= 2.6.
```
> build: bump ruby to 2.6

- dvc/commands/data_sync.py
- dvc/commands/imp.py
- dvc/commands/imp_url.py
- dvc/commands/update.py
- dvc/output.py
- dvc/repo/__init__.py
- dvc/repo/fetch.py
- dvc/repo/imp_url.py
- dvc/repo/index.py
- dvc/repo/update.py
- dvc/stage/__init__.py
- dvc/stage/exceptions.py
- dvc/stage/imports.py
- tests/func/test_data_cloud.py
- tests/func/test_import_url.py
- tests/func/test_update.py
- tests/unit/command/test_imp.py
- tests/unit/command/test_imp_url.py
- tests/unit/command/test_update.py
- tests/unit/output/test_output.py
add `--no-download` flag to `dvc import-url`/`dvc import`/`dvc update` to only create/update `.dvc` files without downloading the associated data
Closes #7918
> import-url/update: add --no-download flag

- dvc/fs/dvc.py
- dvc/repo/ls.py
See #8135 for context.
`._get_key()` is quite expensive. The general idea is to avoid flip-flopping between path and "key" representations.
> fs: optimize dvc list --recursive

- dvc/commands/data.py
- dvc/repo/data.py
- setup.cfg
- tests/func/test_data_status.py
~~Depends on https://github.com/iterative/dvc-data/pull/141 and https://github.com/iterative/dvc-data/pull/142. And requires a new version of `dvc-data` to be released.~~
Fixes https://github.com/iterative/dvc/issues/8062 when both of the objects are not in cache.
Eg: let's take a directory, `data` that is dvc-committed and it's dvcfile git-committed. In that case, when we compare `HEAD` to  `index` (i.e. what's in dvcfile), we'll be comparing between the same object, i.e. `old` and `new` are going to be the same.
In case the `.dir` file does not exist, both values are going to be `None` as the cache does not exist. This fixes that, we'll show a shallow diff (as if `--granular` was not used). Providing more granular information is not possible in this case, as we don't have any …
> data status: fix not-in-cache bugs

- dvc/repo/metrics/show.py
- tests/func/metrics/test_show.py
Closes #8020 
This was a regression introduced in #7712.
Calling `repo.metrics.show` from a subdir stopped returning metrics because `fs.isfile(metric)` check returned false.
> metrics: show: Fix show from subdir.

- dvc/repo/params/show.py
- tests/func/api/test_params.py
If an untracked target is provided alongside `stages` or `deps`, don't load the parameters from the target and raise no params found instead.
Closes #8161
> api: Fix `params_show` for untracked targets.

- dvc/repo/remove.py
- dvc/stage/exceptions.py
- tests/func/test_remove.py
Fixes specifically https://github.com/iterative/dvc/issues/5288#issuecomment-1176844757
> Better error message when specifying file as target for remove

- dvc/commands/plots.py
- tests/unit/command/test_plots.py
Fixes #7944 
This was bothering me, so I went ahead and updated the `plots templates` UI. I went with the suggestion from @pared to remove `-o` since it seemed unnecessary now that you don't need them in `.dvc/plots`.
It is a breaking change, but the feature is pretty new and obscure and unlikely to be part of automation.
Edit: docs PR in https://github.com/iterative/dvc.org/pull/3875
> plots templates: change ui to not dump to file

- dvc/api/params.py
- tests/func/api/test_params.py
Explain `stages` syntax for cases where the API is used from a directory different from the one where the `dvc.yaml` is located.
Closes #8162
> api: Add details for`params_show` `stages` syntax.

- dvc/commands/experiments/diff.py
- dvc/repo/data.py
- dvc/repo/experiments/show.py
- dvc/repo/plots/diff.py
- dvc/scm.py
- tests/func/experiments/test_diff.py
- tests/func/experiments/test_show.py
- tests/func/plots/test_diff.py
- tests/unit/test_scm.py
Make it consistent with all the other commands that use `brancher` (i.e. `dvc diff`, `metrics diff`, `params diff`)
Closes #8163
> repo: Handle no commits for `exp show` and `plots diff`.

- .github/workflows/tests.yaml
- dvc/repo/experiments/queue/base.py
- pyproject.toml
- setup.cfg
- tests/conftest.py
- tests/func/utils/test_hydra.py
- tests/unit/fs/test_fs.py
- We don't have aiohttp support yet, due to which we have to install without cythonized extension.
- Similarly, there has been some changes in how dataclasses disallows some mutable arguments to be set as a class property, due to which `hydra.conf` fails to import in 3.11. See https://github.com/python/cpython/pull/29867. For now, have patched the module and avoid importing as a pytest-plugin.
- dvc-hdfs/pyarrow is not there yet, we'll usually see a release 2-3 months after official release. It is skipped in 3.11 in extras_requires.
- `--set-params` will return a nice error message if hydra cannot be imported in 3.11. I decided to only patch that in tests.
Note, if you want to use dvc with 3.11, you can install it with:
```console
AIOHTTP_NO_EXTENSIONS=1 pip install -e ".[dev]"
```
> test on 3.11

- dvc/info.py
- tests/func/test_version.py
- tests/unit/test_info.py
Include a list of versions of internal subprojects. Helpful for support duty and bisecting without going through release notes.
> info: Include subprojects.

- dvc/output.py
In `data status`, for example, a corrupted cache would raise `ObjectFormatError` instead of returning `None`.
> output.get_obj: catch ObjectCorruptedError

- dvc/config_schema.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/run.py
- dvc/utils/hydra.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_set_params.py
- tests/func/utils/test_hydra.py
The feature will be used depending on whether `config.hydra.enabled` is True or False.
Uses https://hydra.cc/docs/advanced/compose_api/ to build the config and dump it to `params.yaml`. The content of the output file will be overwritten.
`config.hydra.config_dir` and `config.hydra.config_name` can be used to customize the values passed to the APIs used from hydra (`hydra.initialize_config_dir` and `hydra.compose`).
Can be combined with `--set-param` overrides.
Closes https://github.com/iterative/dvc/issues/8082
---
> exp run: Support composing and dumping Hydra config. 

- dvc/repo/data.py
- tests/func/test_data_status.py
The path we get from GitFileSystem is posixpath, even on Windows. We need to
convert that posixpath to os.path here.
> data status: fix path for committed changes in Windows

- tests/unit/repo/experiments/conftest.py
Just trying to see if this fixes the problem. See https://github.com/iterative/dvc/runs/8126741445?check_suite_focus=true#step:7:5217.
> tests: set celery ping_task_timeout 3x the default

- dvc/config_schema.py
- dvc/output.py
- tests/unit/output/test_output.py
related to https://github.com/iterative/dvc/pull/8164
This PR does not address import behavior. When using `dvc import-url azure://container/file?versionid=1234`, the pre-existing behavior will still occur, so the resulting import will be permanently pinned to `azure://container/file?versionid=1234`. `dvc update` will not check for a new version of `azure://container/file`.
The only import related change is that the version_id will be captured in the `.dvc` file like:
```yml
md5: b332f7591398ef3d5e32c97f2ff689f9
frozen: true
deps:
- etag: '0x8DA79D118EC7839'
size: 2
version_id: '2022-08-09T06:33:39.9632713Z'
path: azure://test-container/dir/file?versionid=2022-08-09T06:33:06.7654238Z
outs:
- md5: …
```
> output: support version ID

- dvc/output.py
- tests/func/test_dvcfile.py
We were not loading `desc` of the output, and as a result, we were not preserving the desc field over rewrites. Note that the rewrite only happens in select commands for `dvc.yaml`: `freeze`/`unfreeze`/`run`/`stage-add`, so we did not notice this before.
> dvc.yaml: preserve outputs' desc on rewrites/updates to the stage

- dvc/commands/stage.py
- dvc/dvcfile.py
- dvc/repo/remove.py
- dvc/repo/reproduce.py
- dvc/repo/stage.py
- tests/func/test_stage_load.py
Closes #7323.
Notes:
1. `checkout` might fail if any of the hash_info from the foreach group is missing (it'll still checkout). Same with `pull`/`push`/`fetch`.
2. `commit` might fail if the workspace has any output missing from the foreach group (this is a bit annoying).
3. `remove` is not supported as it needs to modify templated `dvc.yaml` file, which we don't support yet. We can skip it for now.  Internally in dvc, we don't have a "foreach group" to remove, it's compiled away, so we only know about individual stages that it generates. So removing a definition for that foreach group requires custom logic to handle foreach group, and then need to imitate whatever behaviour we have for `remove`, i.e unprotect from cache, remove from `dvc.lock` and `dvc.yaml`, remove `.gitignore` entries, …
> add support for foreach target

- setup.cfg
Looks like the new release broke some data status logic.
> deps: temporarily limit dulwich to <0.20.46

- dvc/repo/data.py
- setup.cfg
- tests/func/test_data_status.py
`dulwich>=0.20.46` no longer returns nt-style paths on Windows for untracked files when using `porcelain.status` (https://github.com/jelmer/dulwich/pull/995)
> data status: fix for scmrepo 0.1.0

- dvc/parsing/context.py
- dvc/repo/experiments/executor/manager/base.py
CI is failing due to an update in `flake8-bugbear`, see https://github.com/PyCQA/flake8-bugbear/releases/tag/22.8.23
```console
dvc/repo/experiments/executor/manager/base.py:24:1: B024 BaseExecutorManager is an abstract base class, 
but it has no abstract methods. 
Remember to use @abstractmethod, @abstractclassmethod and/or @abstractproperty decorators.
class BaseExecutorManager(ABC, Mapping):
^
dvc/parsing/context.py:162:1: B024 Container is an abstract base class, but it has no abstract methods.
Remember to use @abstractmethod, @abstractclassmethod and/or @abstractproperty decorators.
class Container(Node, ABC):
^
```
> silence flake8 errors

- dvc/annotations.py
- dvc/commands/add.py
- dvc/commands/imp.py
- dvc/commands/imp_url.py
- dvc/output.py
- dvc/repo/add.py
- dvc/repo/imp_url.py
- dvc/schema.py
- dvc/stage/__init__.py
- dvc/stage/serialize.py
- dvc/stage/utils.py
- tests/func/test_add.py
- tests/func/test_commit.py
- tests/func/test_dvcfile.py
- tests/func/test_import.py
- tests/func/test_import_url.py
- tests/func/test_run_single_stage.py
- tests/func/test_stage.py
- tests/unit/command/test_add.py
- tests/unit/command/test_annotations_flags.py
- tests/unit/command/test_imp.py
- tests/unit/command/test_imp_url.py
- tests/unit/output/test_annotations.py
- tests/utils/asserts.py
Related: #8214, Closes #8243
This PR:
- adds `labels` - a list type, and `type` - a string type to `.dvc` schema.
- adds support for `--type` flag in `add/import/import-url`.
- adds support for `--labels` flag in `add/import/import-url`. You can specify the flag multiple times, and also can specify labels as comma-separated list.
```console
$ dvc add model.pkl --labels model,get-started --labels dataset-registry
```
- `type`/`labels` are preserved on rewrites/overwrites.
```console
$ dvc add model.pkl  --desc "My model" --type model --labels get-started,dataset-registry > /dev/null
$ cat model.pkl.dvc
```
```yaml
outs:
- md5: d3b07384d113edec49eaa6238ad5ff00
size: 4
path: model.pkl
desc: My model
type: model
labels:
- get-started
- dataset-registry
```
> add metadata fields: label, type to data

- dvc/annotations.py
- dvc/cli/actions.py
- dvc/commands/add.py
- dvc/commands/imp.py
- dvc/commands/imp_url.py
- dvc/output.py
- dvc/repo/imp_url.py
- tests/func/test_add.py
- tests/func/test_commit.py
- tests/func/test_import.py
- tests/func/test_import_url.py
- tests/func/test_run_single_stage.py
- tests/func/test_stage.py
- tests/unit/command/test_add.py
- tests/unit/command/test_annotations_flags.py
- tests/unit/command/test_imp.py
- tests/unit/command/test_imp_url.py
- tests/unit/output/test_annotations.py
On top of #8232. Closes https://github.com/iterative/dvc/issues/8245.
Related to #8214.
This adds support for custom metadata in outputs under `meta` key.
Also adds `--meta` flag to `add`/`import`/`import-url` that supports
`key=value` values.
Example:
```console
$ dvc add model.pkl  --meta key=value --meta summary="$(\cat data.csv)" --desc "My model" --type model --label get-started --label dataset-registry
```
```yaml
outs:
- md5: d3b07384d113edec49eaa6238ad5ff00
size: 4
path: model.pkl
desc: My model
type: model
labels:
- get-started
- dataset-registry
meta:
key: value
summary: "Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n1.00    2.25    3.50\
\    3.50    4.75    6.00 "
```
> Add support for custom metadata

- dvc/output.py
- dvc/schema.py
- dvc/stage/serialize.py
- tests/func/test_dvcfile.py
Adds a `meta`/`type`/`labels` field to `outs` in `dvc.yaml` file.
Closes #8244. Part of #8214.
> add metadata support to dvc.yaml

- dvc/commands/add.py
See https://github.com/iterative/dvc/pull/8232#issuecomment-1238583321.
> Finally, do the descriptions all need to end in (optional)? Other options like --file are also optional, but I don't think it needs to be explicitly stated in the help text.
> add/import/import-url: update help message for labels/type/desc

- dvc/cli/actions.py
- dvc/commands/data.py
- dvc/repo/data.py
- tests/func/test_data_ls.py
- tests/unit/command/test_compat_flag.py
- tests/unit/command/test_data_ls.py
Closes #8246. Part of #8214.
```console
$ dvc data ls
Path                            Type   Labels                        Description          
model.pkl                       model  get-started,dataset-registry  desc
scripts/innosetup/dvc.ico       -      -                             -                    
scripts/innosetup/dvc_left.bmp  -      -                             -                    
scripts/innosetup/dvc_up.bmp    -      -                             -                    
```
```console
$ dvc data ls --help
usage: dvc data ls [-h] [-q | -v] [--md] [--type TYPE] [--labels LABELS] [-R] [targets ...]
List data tracked by DVC with its metadata.
Documentation: <https://man.dvc.org/data/ls>
positional arguments:
targets          Limit command scope to these tracked …
```
> data ls: new command to show metadata with outputs

- dvc/dependency/param.py
- dvc/dependency/repo.py
- dvc/dvcfile.py
- dvc/output.py
- dvc/repo/fetch.py
- dvc/repo/index.py
- dvc/repo/push.py
- dvc/schema.py
- dvc/stage/__init__.py
- dvc/stage/serialize.py
- dvc/stage/utils.py
- setup.cfg
requires https://github.com/iterative/dvc-data/pull/171
- adds directory support to the worktree/cloud versioning POC
- directory tree metadata is stored in `out.files` in the .dvc file after push
- directories can be fetched without existing .dir cache (and without a traditional DVC remote configured) as long as `files` entry is present in the .dvc file
[![asciicast](https://asciinema.org/a/PoZURjVidcU5B2YcvLoltTjOE.svg)](https://asciinema.org/a/PoZURjVidcU5B2YcvLoltTjOE)
> worktree push/fetch: support dirs

- dvc/fs/dvc.py
- dvc/testing/test_api.py
These tests will be run in different remotes by default. The test is definitely very long but tests everything that we override/implement directly.
There was a bug with `get()` for directory downloads which has been fixed as well.
Currently, the `size()` seems to be broken as it does not fetch sizes from the remote.
> dvcfs: add fsspec-compliance tests

- dvc/fs/dvc.py
So that we don't accidentally corrupt cache/local files/remote files.
> dvcfs: prevent opening file object in write mode

- dvc/api/__init__.py
- dvc/dependency/repo.py
- dvc/fs/__init__.py
- dvc/fs/dvc.py
- dvc/repo/__init__.py
- dvc/repo/collect.py
- dvc/repo/diff.py
- dvc/repo/ls.py
- dvc/repo/metrics/show.py
- dvc/repo/plots/__init__.py
- dvc/testing/test_api.py
- setup.cfg
- tests/unit/fs/test_data.py
- tests/unit/fs/test_dvc.py
- tests/unit/fs/test_dvc_info.py
As discussed in https://github.com/iterative/dvc.org/pull/3932#discussion_r970378392 and privately in Slack.
Tbh I don't like upper-casing acronyms, but going with the popular vote here as it's a matter of taste. :)
> dvcfs: rename DvcFileSystem to DVCFileSystem

- dvc/testing/test_api.py
- setup.cfg
With a testing group we can easily include all dependencies required for dvc.testing (e.g. in dvc-plugins)
See https://github.com/iterative/dvc/pull/8296#discussion_r972667351
> deps: add testing group for dvc.testing requirements

- dvc/repo/push.py
Otherwise, you get
```
$ dvc push
ERROR: failed to push data to the cloud - cannot dump a parametrized stage: 'data_split'
```
when trying to dump parametrized stages.
> push: use update_pipeline=False for cloud versioning

- dvc/fs/dvc.py
Only documenting `DvcFileSystem.__init__` and `isdvc` for now, because others inherit the docstrings from superclass.
> document dvcfs

- README.rst
Hi,
This PR is just about a link that is pointing to a non existing page in the docs:
- broken link: https://dvc.org/doc/start/data-management/pipelines
- fixed link: https://dvc.org/doc/start/data-management/data-pipelines
Best,
Martino
> fixed link to "get started: pipelines" docs

- dvc/utils/hydra.py
- tests/func/utils/test_hydra.py
Defaults List overrides (`defaults/foo=1,2`) were not working because of the inclusion of the `/` character. Fixed it by updating how we construct the `merged_overrides` and added a regression test.
> hydra: Fix sweeps on Defaults List.

- dvc/stage/__init__.py
- tests/func/test_import_url.py
Files imported with import/import-url were not being added to `.gitignore`
> import/import-url: ignore outs when using --no-download

- dvc/repo/experiments/executor/base.py
fix: #8348
In previous, 
https://github.com/iterative/dvc/blob/c617769a1d4206bfaf0573e5ae9cac6d7fc6f692/dvc/repo/experiments/__init__.py#L475-L483
`on_diverge` was not executed. After this PR, no more `invalid ref`
[![asciicast](https://asciinema.org/a/UWs1KnJD3QPsnbAukPloosPpr.svg)](https://asciinema.org/a/UWs1KnJD3QPsnbAukPloosPpr)
> Solve the on_diverged function not executed error.

- .github/workflows/tests.yaml
- setup.cfg
aiohttp now provides wheel for 3.11.
> aiohttp: remove AIOHTTP_NO_EXTENSIONS envvar

- dvc/commands/git_hook.py
- dvc/dvcfile.py
- dvc/output.py
- dvc/stage/__init__.py
- tests/func/test_merge_driver.py
Fixes #8233 #5151
This adds changes and deletions to the merge driver based on changes in https://github.com/iterative/dvc-data/pull/160 and https://github.com/iterative/dvc-data/pull/178.
There's still one scenario not covered here: where both branches deleted the same file. This is trickier to handle and not that common, so I left it out for now and raise an error stating that DVC is unable to merge where both are deleted.
Docs PR: https://github.com/iterative/dvc.org/pull/3993
> merge-driver: support removes and changes

- dvc/dvcfile.py
- dvc/output.py
- dvc/repo/fetch.py
- dvc/repo/index.py
- dvc/repo/push.py
- dvc/stage/loader.py
- dvc/stage/serialize.py
- setup.cfg
Removes some redundant operations and properly loads/dumps trees in dvc.lock.
> cloud-versioning: better handling for directories

- dvc/commands/plots.py
- dvc/render/convert.py
- dvc/render/converter/vega.py
- tests/integration/plots/test_plots.py
- tests/unit/command/test_plots.py
- tests/unit/render/test_convert.py
- tests/unit/render/test_match.py
- tests/unit/render/test_vega_converter.py
Change required for https://github.com/iterative/vscode-dvc/pull/2403
Related iterative/vscode-dvc#1757
> vscode: support flexible plots

- dvc/testing/api_tests.py
The param was being modified in-place, due to which successive runs would fail.
Since we use run plugins' tests on multiple processes, our CI did not catch this. If you'd run this with plain `pytest`, it'd fail. Noticed when debugging dvc-webdav tests.
> dvcfs tests: copy pytest param instead of in-place update

- dvc/output.py
- dvc/repo/brancher.py
- dvc/repo/index.py
Prerequisite for https://github.com/iterative/dvc/pull/8249
Depends on https://github.com/iterative/dvc-data/pull/195
> index: add IndexView, brancher: support index

- dvc/commands/imp_url.py
- dvc/dependency/base.py
- dvc/output.py
- dvc/repo/__init__.py
- dvc/repo/fetch.py
- dvc/repo/imp_url.py
- dvc/repo/imports.py
- dvc/repo/index.py
- dvc/repo/status.py
- dvc/stage/__init__.py
- tests/unit/command/test_imp_url.py
- Implements cloud versioning support in `import-url`
- When the imported URL contains a version ID, DVC will import that specific version (and the version ID will be capture din the .dvc file).
- When the imported URL does not contain a version ID, DVC will not capture version information unless the `--version-aware` flag is provided (regardless of whether or not the bucket/container has versioning enabled).
- When using `--version-aware` flag, DVC will capture the latest/current version of the imported file.
- Implements support for fetching imports from source
- DVC will first try to fetch/pull imports from a DVC remote
- If there is no remote configured or the imported object failed to be fetched, DVC will …
> import-url: use dvc-data `index.save()` for fetching imports

- dvc/commands/experiments/ls.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/show.py
- setup.cfg
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_show.py
wait for https://github.com/iterative/scmrepo/pull/145 to merge first. 
fix: #8451
nearly five times faster in my local workspace for an `exp show`, no primary time costing method in `exp show` for now.
1. Change the call of scm.describe from individual revision to a collection of them. Accelerate the run speed of `exp show`
> exp show: Use batch call on `scm.describe`

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/show.py
- tests/func/experiments/test_show.py
fix: #8349 
> Tasks status turned to queued for 1 second before turned into success.  
is because in previous the status judgement is using the output of `get_running_exps` in `repo.expereiments` 
https://github.com/iterative/dvc/blob/8c484645fa74db8824c252f21b9311411b47f13e/dvc/repo/experiments/__init__.py#L462
the `get_running_exps` will mark the tasks to be not running because the `info.result` is not None. when entering the collect result progress, 
https://github.com/iterative/dvc/blob/8c484645fa74db8824c252f21b9311411b47f13e/dvc/repo/experiments/executor/base.py#L491-L493
Here we use the output of the celery queue as the universal standard for the tasks status. …
> Use celery status as the exp show status

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/queue/tempdir.py
- dvc/repo/experiments/queue/utils.py
- dvc/repo/experiments/queue/workspace.py
- dvc/repo/experiments/show.py
- dvc/rwlock.py
- tests/func/experiments/test_show.py
fix: #8450
1. Add a new function check_rwlock to check and autocorrect rwlock info.
2. `dvc exp show` will check pid info.
3. Add related tests for it.
> auto solve corrupted rwlock info

- dvc/_debug.py
Creates one callgrind file per thread. Useful when profiling anything with multiple threads. Needed to debug a user issue.
Similar to callgrind's `--separate-threads` option.
Updated https://github.com/iterative/dvc/wiki/Debugging,-Profiling-and-Benchmarking-DVC
> yappi: add --yappi-separate-threads flag

- .github/workflows/packages.yaml
- pyproject.toml
- scripts/build_package.sh
Will help us test package uploads, etc.
Users will be able to install `dvc` as follows:
```console
python3 -m pip install \
--index-url https://test.pypi.org/simple/ \
--extra-index-url https://pypi.org/simple/ \
dvc
```
The version number will be `x.x.y.devN` where `n` is distance (in term of commits) from last git tag, and `y` is `+1` from last tag. If the version is same as tag, it won't have the latter part. Eg: latest upload may be `2.22.3.dev9`.
As a test, I uploaded https://test.pypi.org/project/dvc/2.33.2.dev10/ via GHA.
> ci: push package to test.pypi.org

- pyproject.toml
See https://setuptools.pypa.io/en/latest/deprecated/zip_safe.html. `zip_safe` is not required these days.
> remove zip-safe

- .github/workflows/tests.yaml
`macOS` runners` are very slow to provision.
> ci: run only single macOS job

- dvc/repo/commit.py
> commit: skip changed_entries check on force commit

- .github/workflows/packages.yaml
As 3.11 is now released, let's bump pyinstaller packages to 3.10 (we always keep them 1 version behind).
Note that pyinstaller already supports 3.11 since v5.5.
> build: bump pyinstaller packages python version to 3.10

- dvc/dependency/__init__.py
- dvc/dependency/base.py
- dvc/output.py
- dvc/repo/index.py
- pyproject.toml
Will fix https://github.com/iterative/dvc/issues/8506
> import-url: include `files` entry for cloud versioned dir dependencies

- dvc/repo/experiments/run.py
- tests/func/experiments/test_set_params.py
Queuing without overrides is broken due to referencing `hydra_sweeps` before assignment. Feel free to suggest a different place for the added test.
> fix hydra_sweeps referenced before assignment

- dvc/repo/experiments/diff.py
- dvc/repo/experiments/queue/utils.py
- dvc/repo/experiments/show.py
- tests/func/experiments/test_show.py
fix: #8350
We shouldn't add locks to exp show to prevent race conditions as this command is calling continuously by the extension. So we make a better way to handle all kinds of reference failures.
1. Drop all based experiments if got a SCMError in baseline.
2. Drop all checkpoint experiments if any commit got a SCMError in one of checkpoint commit.
3. Drop the entire experiments if got a SCMError.
4. Add tests for each of the conditions above.
> Make exp show handle errors better

- dvc/repo/plots/__init__.py
- tests/func/plots/test_show.py
Add SVG to parser and parametrize an existing functionality test on SVG as well as JPG.
If needed I can also modify a test in `tests/integration/plots` to check SVG functionality. I haven't done that yet as it would touch quite a few lines.
Fixes #6714.
^ Regarding the documentation check above, I will add SVG to the list under [plots](https://dvc.org/doc/command-reference/plots#description) over in the documentation as needed.
> plots: support svg

- dvc/repo/experiments/show.py
- tests/unit/repo/experiments/test_show.py
The original problem is that the applied/branched experiments have a new name in the workspace. But getting this name only happens for baselines. If we use `-n` flag to traverse to some old commits, they will be shown as experiments instead of baselines, and will cause this problem. 
fix: #8526
1. The current `get_names` will crash if an experiment branch had already been given a new branch name to it.
1. Solve the crash when we getting the name of a newly fixed experiment branch.
2. Add a new unit test to it.
> Solve the crash on getting name of applied experiment branch

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/executor/local.py
- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/run.py
- dvc/repo/experiments/show.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_queue.py
- tests/func/experiments/test_show.py
- tests/unit/repo/experiments/test_executor_status.py
wait for #8349
fix: #8403
1. Make the follow exit after the tasks been finished.
2. remove some of the flaky mark
> Fix some celery queue related ci failure.

- dvc/output.py
Fixes regression introduced in https://github.com/iterative/dvc/pull/8528 (discord context https://discord.com/channels/485586884165107732/485596304961962003/1041260802067415070)
> fetch/pull: fix regression when using targeted fetch in repo containing import-url imports

- pyproject.toml
- tests/func/test_import.py
Co-authored-by: Peter Rowlands <peter@iterative.ai>
> deps: bump dvc-data to 0.26.0

- dvc/output.py
- dvc/repo/__init__.py
- dvc/repo/imp_url.py
- dvc/repo/index.py
- dvc/repo/push.py
- dvc/repo/status.py
- dvc/schema.py
- dvc/stage/__init__.py
- dvc/stage/serialize.py
- tests/func/test_used_objs.py
Will close https://github.com/iterative/dvc/issues/8429
- Outs now support a `push:` param that defaults to `true`
- If `push: false` is used, the given file will be dvc-tracked and cached locally, but will never be pushed to a remote on `dvc push`
- The output will still be included when using `dvc status -c` and `dvc pull` (i.e. we will still try to pull it from a DVC remote when possible, and will report whether or not the file is exists in a DVC remote on `status -c`)
- For `import-url` with cloud-versioned URLs (or explicit `--version-aware` flag), the output will be generated with `push: false`
- If the user overrides this with `push: true` or by removing the `push:` line in the .dvc file (to use the …
> import-url: disable push by default for cloud-versioned imports

- dvc/repo/fetch.py
- dvc/repo/index.py
- dvc/repo/push.py
- dvc/repo/worktree.py
Follow up to #8578.
Related to https://github.com/iterative/dvc/issues/8464.
- Moves worktree push/fetch logic into `dvc.repo.worktree`
- Disables pushing `dvc import` data to worktree remotes
- Disables pushing `push: false` data to worktree remotes
> worktree: support push: false

- dvc/utils/hydra.py
- tests/func/utils/test_hydra.py
Combining `OmegaConf.to_object` with our yaml DUMPER (ruaml.yaml) was not correctly handling strings like 'no'.
`OmegaConf.to_yaml` uses a custom string representer that correctly handles those cases.
Fixes #8583
> hydra: Use `OmegaConf.to_yaml` for dumping `.yaml` output.

- dvc/output.py
- dvc/repo/add.py
- dvc/stage/__init__.py
Fixes https://github.com/iterative/dvc/issues/8293
> wokrtree add: preserve version metadata for unmodified files on `dvc add`

- dvc/cli/parser.py
The issue seems to have been fixed in Python 3.4.
> cli: remove version action

- dvc/render/converter/vega.py
- tests/unit/render/test_vega_converter.py
Fix default x_label
Before:
After:
> plots: set default x label

- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/queue/exceptions.py
- pyproject.toml
- tests/unit/repo/experiments/queue/test_celery.py
fix: #8461
fix: #8473
For now, for those inactive but uncompleted tasks, they still shown as Running in `exp show` and `task queue`, we cannot remove them because they are regarded as running, we cann't kill them because their are no real process behind them.
1. Now we can examine these false running tasks and mark them as failure in `queue kill` command. #8461
2. Better msg handle for initliaizing tasks in `queue kill`#8473
3. Add new unit tests for both cases.
wait for https://github.com/iterative/dvc-task/pull/97 to be merged first.
> queue kill: we can manually mark problematic tasks as failure

- dvc/repo/experiments/queue/tempdir.py
- dvc/repo/experiments/queue/utils.py
- dvc/repo/experiments/show.py
- tests/unit/repo/experiments/test_show.py
fix #7693
The problem was when we gathered experiments, and at the same time, the executor are creating new commits. It will make the checkpoint top/head return by `get_running_exps`/`get_ref`/`branch_revs` not the same one. And cause the problem described in #7693
To solve this we did
1. move the `get_rev` to the beginning of `exp show` to make sure the return results in `branch_revs`
2. Add a new function to move all of the properties that only belong to `head` of the checkpoint from the wrong place to the top.
3. Add a new unit test for it.
4. Force fetch_running_exp to return data.
5. fix a bug in tmp_dir_executor.
> Solve the wrong checkpoint tip info during executor running

- dvc/repo/worktree.py
Closes https://github.com/iterative/dvc/issues/8354
- For files that already have version ID information from a previous push, if that version still exists on the remote we will not push a new version of that file (regardless of whether or not the "latest" version on the remote matches the one we want to push)
- Adds progress bars and fixes reported upload/download file count on worktree push/fetch
> worktree push: do not push existing versions

- scripts/fpm/build.py
These are leaking into our rpm packages.
Related https://github.com/iterative/dvc-s3-repo/issues/86
> build: fpm: don't create .build-id/* files

- dvc/stage/cache.py
- dvc/stage/run.py
- tests/func/test_run_cache.py
- tests/unit/stage/test_run.py
Output of script provided by @pared in [https://github.com/iterative/dvc/issues/8342](https://github.com/iterative/dvc/issues/8342)
The output of `dvc repro --dry` is the same as `dvc repro` but without side effects. this way users will know if the stage is cached. 
```
+ pushd /var/folders/2_/8wzmxgd96lz31gp705ghksnr0000gn/T/
/var/folders/2_/8wzmxgd96lz31gp705ghksnr0000gn/T ~/Documents/dvc_test
+ wsp=test_wspace
+ rep=test_repo
+ rm -rf test_wspace
+ mkdir test_wspace
+ pushd test_wspace
/var/folders/2_/8wzmxgd96lz31gp705ghksnr0000gn/T/test_wspace /var/folders/2_/8wzmxgd96lz31gp705ghksnr0000gn/T ~/Documents/dvc_test
++ pwd
+ main=/var/folders/2_/8wzmxgd96lz31gp705ghksnr0000gn/T/test_wspace
+ mkdir test_repo
+ …
```
> repro dry: show information if the stage is cached

- dvc/commands/experiments/ls.py
- dvc/repo/experiments/ls.py
- dvc/repo/experiments/refs.py
- dvc/repo/experiments/utils.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_remote.py
Followup #8554 (https://github.com/iterative/dvc/pull/8554#discussion_r1023505933)
- Moves the `exp list` "business" logic inside the `repo` API (simplifies testing, makes it easier to use API in the future).
- Simplify the implementation a bit.
- Simplify tests.
- Cleanup `mypy` findings by making ExpInfo stricter.
TODO:
--------------
> exp list: cleanup and move logic inside repo api

- dvc/commands/experiments/__init__.py
- dvc/commands/experiments/save.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/local.py
- dvc/repo/experiments/save.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_save.py
- tests/unit/command/test_experiments.py
copy of https://github.com/iterative/dvc/pull/8408
Makes it possible to save changes in the current workspace as a dvc experiment.
closes https://github.com/iterative/dvc/issues/6746
> exp save: initial implementation

- dvc/repo/experiments/queue/utils.py
- pyproject.toml
fix: #8615
1. This is because, at the end of the tasks, the temp running directly will be deleted
1. Only fetch result during running (not during the result collection)
2. Bump into scmrepo 0.1.4 in which we wrapped `KeyError` into `SCMError`.
> Solve the unexpected error at the end of the queued tasks running

- dvc/data_cloud.py
- dvc/repo/push.py
- dvc/repo/worktree.py
Will close https://github.com/iterative/dvc/issues/8409
- `worktree = true` now implies `version_aware = true` (a config error will be raised if a user explicitly configures a remote with `worktree = true` and `version_aware = false`)
- `version_aware = true` (and `worktree = false`) will result in pushing human-readable filenames to a cloud-versioned remote. DVC will not set DELETE flags and will not update the latest version of a file on the remote if an older version of the file has has already been pushed
- `worktree = true` will force `dvc push` to ensure that the "latest" version of a remote always reflects the pushed workspace. DVC will set DELETE flags for files that do not exist in the current …
> remote: separate `worktree` vs `version_aware` behavior

- dvc/repo/stage.py
Related to https://github.com/iterative/example-repos-dev/issues/153.
Fixes #5802
Not sure where to add a test for this
> stage add: don't fail if unable to create .gitignore

- dvc/commands/update.py
- dvc/repo/index.py
- dvc/repo/update.py
- dvc/repo/worktree.py
Will close https://github.com/iterative/dvc/issues/8382
- When using a `worktree` remote, `dvc update <target>...` will update the specified targets to get the latest modifications from the remote
- If a file is unmodified (and etags match), the version ID from the local .dvc file will not be modified even if the latest remote version ID does not match (to prevent merge conflicts and be consistent with `dvc push` for worktrees)
- For a file output, if the file does not exist in the remote, `dvc update` will output a warning and will not make local modifications
- For a dir output, if the directory does not exist in the remote, or is empty in the remote (and contains no actual files within the dir), `dvc update` …
> `dvc update`: support worktree update

- dvc/data_cloud.py
Disables the use of `gc -c` and `status -c` with a versioned remote
> remote: disable gc/status for versioned remotes

- dvc/data_cloud.py
> worktree: fix default worktree remote/odb exception

- dvc/repo/fetch.py
- dvc/repo/push.py
- dvc/repo/worktree.py
- dvc/stage/cache.py
Will close #8671
- Disables support for `--run-cache` for cloud versioned push/fetch
- Enables support for `--all-branches/tags/commits` in cloud versioned fetch
- Disables support for `--all-branches/tags/commits` in cloud versioned push
> push/fetch: cleanup cloud versioning CLI flags behavior

- dvc/utils/hydra.py
- pyproject.toml
- tests/conftest.py
- tests/func/experiments/test_set_params.py
- tests/func/utils/test_hydra.py
From 1.3.0 onwards. See https://github.com/facebookresearch/hydra/releases/tag/v1.3.0.
> deps: remove 3.11 checks for hydra; has 3.11 support now

- dvc/repo/__init__.py
- dvc/repo/brancher.py
This alone speedups plots collection in certain repos and cases 10x+ (e.g. from 65s+ to 5s or less). 
Fixes repo and brancher to reset `dvcfs`, `data` and other indices.
Otherwise, at the very least if we had a directory with plots in a revision:
```yaml
plots:
- mispredicted
```
where:
```
(.venv) √ Projects/hackathon % tree mispredicted
mispredicted
├── cat
├── croissant
│   └── muffin-16115-13825-26827-1d8e67e0bffdfebcdb3b337787823ab6.jpeg
├── dog
└── muffin
├── croissant-0295ed7610487b3118febb5563bc58fd.jpg
├── croissant-3f488b602f2a668e-3fd6af132b0dceafe014dfcf7809d2ff.jpg
└── dog-bec8602c36317744-1827c47f8ae15e6a3c4ee660035781a4.jpg
```
and would try to collect multiple revisions, where previous one doesn't have the same directory content, or doesn't have `.dir` fine in cache to …
> Reset all indices on the brancher iteration

- dvc/repo/index.py
Keeping this private for now to see if this will be enough for `studio`.
There will be edgecases, if the outputs are tracked as a directory but file are specified in top-level plots or vice versa.
> add index._plot_sources

- dvc/repo/index.py
- dvc/repo/stage.py
- tests/func/test_repo_index.py
These are being used by some users, but removing them for easier refactoring for now.
We are not using it ourselves.
> index: remove unused APIs

- dvc/render/converter/vega.py
- tests/unit/render/test_vega_converter.py
Fixes regressions in https://github.com/iterative/dvc/pull/8421. 
1. Makes plots work again when `y` is a list.
```yaml
plots:
plot1.csv:
y:
- acc
- loss
x: epoch
```
2. Supports `y` lists as one of multiple data sources like:
```yaml
plots:
plot:
y:
plot1.csv:
- acc
- loss
plot2.csv:
- loss
x:
epoch
```
@amritghimire @ssachkovskaya I tested with https://studio.iterative.ai/user/dberenbaum/projects/dvc_plots_tests-cvls4xeliq and 1 looks broken (2 seems okay). Not sure if it will get automatically fixed with this change or if something is needed on your end.
> plots: fix regressions to top-level plots

- dvc/repo/experiments/queue/workspace.py
- pyproject.toml
- tests/func/experiments/test_utils.py
For "Local Studio live metrics" proposal
Requires https://github.com/iterative/studio/pull/4707
Uses https://github.com/iterative/dvc-studio-client
> Add post_to_studio `start` and `done` calls.

- tests/func/experiments/test_show.py
Some of the random exp names could start with `bar`.
https://github.com/iterative/dvc/actions/runs/3757008396/jobs/6383731723#step:5:79
> tests: Fix flaky `test_show_only_changed`.

- dvc/repo/experiments/queue/celery.py
- tests/unit/repo/experiments/queue/test_celery.py
fix: #8702
1. replace simple `proc.kill` in `queue stop --kill` with the same logic as in `queue kill` to make it possible to set false status `running` tasks as faileed.
2. Modified the tests.
> `queue stop --kill` can kill false `running` status tasks

- dvc/repo/experiments/queue/tempdir.py
- dvc/repo/reproduce.py
- dvc/stage/exceptions.py
- dvc/stage/monitor.py
- dvc/stage/run.py
- tests/func/experiments/conftest.py
- tests/func/experiments/test_checkpoints.py
- tests/unit/repo/experiments/conftest.py
fix: #8612
For checkpoint experiments in some cases, users might want to give it an early stopping to reduce variance.  But currently, if we interrupt/kill the experiment it will be marked as failed, and all of the completed checkpoints will be removed as we clean up all the running directly after the process failed.
1. We raise CheckpointKilledError instead of StageCmdFailed error if at least one checkpoint had been committed.
2. Temp_dir executor will continue collecting data if the Checkpoint stage was interrupted.
3. Raise warnings if a checkpoint stage was incomplete and the other stages were not forwarded.
4. Add a new functional test for this
> Make temp dir executed checkpoint experiment return result to workspace.

- dvc/commands/get.py
- dvc/commands/imp.py
- dvc/scm.py
This will show the cause of clone errors. e.g.
```bash
dvc get https://github.com/dberenbaum/example-get-started-cp.git README.md -o deleteme
```
> ERROR: failed to get 'README.md' - SCM error: Failed to clone repo 'https://github.com/dberenbaum/example-get-started-cp.git' to '/tmp/tmp98x3h8g0dvc-clone': No valid credentials provided
related: #8654
> scm: add cause of clone errors

- dvc/commands/experiments/pull.py
- dvc/commands/experiments/save.py
- fix --help for `exp save --force`
- fix --help for `exp pull --force`
> exp save: update --help

- dvc/commands/queue/kill.py
- dvc/repo/experiments/queue/celery.py
- dvc/stage/run.py
- pyproject.toml
- tests/unit/command/test_queue.py
- tests/unit/repo/experiments/queue/test_celery.py
fix: #8624
1. Add a new flag `--force` for `queue kill`
2. Make `SIGINT` to be the default option and `SIGKILL` to be with `--force`
3. Remove `SIGINT` blocking.
4. Add tests for `queue kill`
wait for https://github.com/iterative/dvc-task/pull/101
> Use `SIGINT` as the default signal in `queue kill`

- dvc/repo/experiments/apply.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/remove.py
- tests/func/experiments/test_experiments.py
- tests/unit/repo/experiments/test_remove.py
fix: #8182
1. `exp apply` can apply to failed experiments.
2. `exp apply` can accept exp names as targets.
3. Add a new functional test for it.
4. Move `get_ref_and_entry_by_names` from `exp remove` to `utils` for other commands' usage.
> `exp apply` can accept exp names and failed exps as target

- dvc/dvcfile.py
- dvc/repo/stage.py
- dvc/stage/__init__.py
- dvc/stage/loader.py
- tests/func/test_stage.py
- tests/unit/stage/test_loader_pipeline_file.py
where it makes sense, since it is a part of file rather than "StageLoader".
> internal: hoist resolver/top-level metrics/plots/params data to file level

- dvc/stage/imports.py
- tests/func/test_update.py
- tests/unit/stage/test_stage.py
> update: prevent re-download on every update

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/exceptions.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/save.py
- tests/func/experiments/test_checkpoints.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_save.py
- tests/func/experiments/test_show.py
Following up on https://github.com/iterative/dvc.org/pull/4200#discussion_r1057826738:
> > Or, if nothing
has changed in the workspace, force saving an experiment anyway (identical to
Git `HEAD`).
>
> @dtrifiro I missed this check in https://github.com/iterative/dvc/pull/8690. I don't think `--force` should be needed and it complicates this option. Can we drop it?
>
> Ideally, we want to make `dvc exp run` the same and not worry about creating duplicate experiments (see the discussion in https://github.com/iterative/dvc/pull/8659#issuecomment-1338499979).
> exp: stop checking for unchanged experiments

- dvc/config_schema.py
- pyproject.toml
- `read_timeout` maps to `aiohttp`'s `sock_read` timeout (read timeout while waiting for a new portion of data from the peer)
- `connect_timeout` applies to `aiohttp`'s `connect`,  `sock_connect` timeouts
For more information:
https://docs.aiohttp.org/en/stable/client_reference.html?highlight=clienttimeout#clienttimeout
> config: expose http timeout in config schema

- dvc/fs/dvc.py
- tests/func/test_ls.py
Cuts down `dvc ls . data/mnist/dataset --recursive` for me from ~37 to ~25 seconds.
Note that this also changes behaviour for ls with a broken symlink, as we were not able to see it before because of a failing `info()` call, but now we can follow a normal UNIX ls behaviour more closely.
> dvcfs: ls: don't call info()

- dvc/repo/ls.py
Cuts down `dvc ls . data/mnist/dataset --recursive` for me from ~25 to ~12 seconds.
`relparts` is an expensive operation as it calls `relpath` that calls `abspath`, so we want to avoid calling it as much as possible.
> ls: compute relparts once for every dir

- dvc/repo/metrics/diff.py
- dvc/repo/metrics/show.py
- dvc/repo/params/diff.py
- dvc/repo/params/show.py
- tests/func/metrics/test_diff.py
- tests/func/params/test_diff.py
Before, if you did `dvc metrics diff main` from the `main` branch, you would get:
```
$ dvc metrics diff main
Path                   Metric      main     workspace    Change
training/metrics.json  step        14       -            -
training/metrics.json  test.acc    0.7735   -            -
training/metrics.json  test.loss   0.95962  -            -
training/metrics.json  train.acc   0.7694   -            -
training/metrics.json  train.loss  0.9731   -            -
```
This made it look like the metrics were missing in the workspace and there was some difference from `main` even in a clean repo state.
After this PR, there will be no output from the command above.
> metrics/params: diff: don't show diff if active branch is the same as workspace

- dvc/repo/fetch.py
- dvc/repo/push.py
- dvc/repo/worktree.py
> cloud versioning: fix push/fetch performance

- pyproject.toml
Should also help with https://github.com/iterative/dvc/issues/8359 , as we've sped up meta serialization which is used when writing directories to dvcfiles.
> deps: bump dvc-data to 0.29.0

- dvc/repo/collect.py
- dvc/repo/experiments/show.py
- dvc/repo/metrics/show.py
- dvc/repo/params/show.py
- dvc/repo/plots/__init__.py
- tests/func/metrics/test_show.py
- tests/func/plots/test_show.py
- tests/unit/test_collect.py
Related https://github.com/iterative/dvc/issues/8786
/Users/ivan/Projects/vscode-dvc-demo/.venv/bin/python -m dvc plots diff 11295f0 9aa0603 e29c9be workspace -o .dvc/tmp/plots --split --json - COMPLETED (**53199ms**)
/Users/ivan/Projects/vscode-dvc-demo/.venv/bin/python -m dvc plots diff 11295f0 9aa0603 e29c9be workspace -o .dvc/tmp/plots --split --json - COMPLETED (9404ms)
.. and not a huge change to maintain to my mind.
still very slow though, but I think it now goes into brancher, path collection, etc - which also should be parallelized, indexed and cached.
---------
> perf: remove fs exists check in plots, parallel data collect

- dvc/dvcfile.py
- dvc/repo/__init__.py
- dvc/repo/add.py
- dvc/repo/imp_url.py
- dvc/repo/index.py
- dvc/repo/metrics/show.py
- dvc/repo/params/show.py
- dvc/repo/plots/__init__.py
- dvc/repo/stage.py
- tests/func/test_remove.py
- tests/func/test_repo_index.py
- tests/func/test_stage.py
- tests/func/test_stage_load.py
- tests/unit/command/test_status.py
Haven't made many changes here, but now the Index collection happens eagerly (although index is still created lazily) when `Index.from_repo()` or `Index.from_file()` is called.
* The collection of stages happen inside `Index` rather than as part of `Repo.stage.collect_repo`.
* `repo._skip_graph_checks` was broken, it has been fixed by introducing `Repo.ensure_graph_correctness_with(stages=stages)` API that honors that attribute.
* Stage collection is eager during `Index.from_repo()`.
* Minor cleanups in `Repo`/`StageLoad`/`Index`.
The Index had `stages` cached property, which was lazily loaded. We extended this and added `metrics`/`params`/`plots` property which was also a `cached_property`. It was not possible to collect and fill all of these properties at the same time, but for …
> index/stage: move repo collection logic to index

- dvc/stage/__init__.py
- tests/func/test_run_cache.py
- tests/unit/stage/test_cache.py
> stage: Skip run-cache if any out has cache: false. 

- dvc/config.py
- dvc/data_cloud.py
- dvc/dvcfile.py
- dvc/fs/callbacks.py
- dvc/fs/data.py
- dvc/fs/dvc.py
- dvc/fs/git.py
- dvc/output.py
- dvc/parsing/__init__.py
- dvc/proc/process.py
- dvc/repo/__init__.py
- dvc/repo/data.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/local.py
- dvc/repo/experiments/executor/ssh.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/queue/remove.py
- dvc/repo/experiments/queue/tempdir.py
- dvc/repo/experiments/queue/workspace.py
- dvc/repo/index.py
- dvc/repo/plots/__init__.py
- dvc/stage/__init__.py
- dvc/stage/cache.py
- dvc/stage/loader.py
- dvc/testing/path_info.py
- dvc/ui/__init__.py
- dvc/utils/objects.py
- pyproject.toml
We use `cached_property` a lot.
But, since funcy does not have type hints, we lose types even if the underlying method was typed. `functools.cached_property` is in standard library since Python 3.8 but we cannot use it because of https://github.com/python/cpython/issues/87634.
So, with this PR, the `cached_property` is conditional, as in mypy will see `cached_property` as being from functools, whereas in reality, it will still be from `funcy.cached_property`.
For this, we have to import as `from dvc.utils.objects import cached_property` instead of funcy or functools.
```python
from dvc.utils.objects import cached_property
```
I have also banned the imports of `funcy.cached_property` and it will now raise linter error when doing so.
```console
dvc/repo/plots/__init__.py:23:19: TID251 …
```
> mypy: use typesafe cached_property

- dvc/repo/index.py
- dvc/repo/worktree.py
This is a generally useful function that builds a data index from repo index.
This is currently only used in cloud versioning, but it is going to be used in `status`, `diff` and other data-centric operations.
Pre-requisite for #8761
> index: introduce build_data_index

- .github/workflows/tests.yaml
- dvc/_debug.py
- dvc/daemon.py
- dvc/proc/manager.py
- dvc/testing/fixtures.py
We already have `pre-commit.ci` running for quick feedback. We actually want to run mypy/pylint checks (and others) across multiple python versions and platforms.
So, this PR changes the workflow and makes them run before running tests in all platforms and versions. This does add 3-4 minutes to our jobs.
Also merged the test split that we had before.
> lint: run lint checks on all platforms

- dvc/output.py
- pyproject.toml
- tests/func/test_gc.py
Per changes in https://github.com/iterative/dvc-objects/pull/176
> output.remove: Pass explicit `recursive` flag

- dvc/dependency/param.py
- tests/unit/dependency/test_params.py
> param: Fix status check for Tuples.

- setup.py
GH seems to be able to show dependencies from `pyproject.toml` files. I am not sure if it'll be able to show dependencies without this, but I am removing this to check whether it does or not. Will revert if it does not work. :)
Otherwise, we don't need this file.
> remove setup.py file

- dvc/output.py
- dvc/stage/serialize.py
- tests/func/test_add.py
- tests/unit/output/test_output.py
- tests/unit/stage/test_serialize_pipeline_lock.py
Closes #8357
---
Here is how the `.dvc` file looks for `2.42.0` / `this P.R` at different steps of the workflow (click details to expand):
```
$ dvc import-url --version-aware $VERSIONED_BUCKET/data
$ cat data.dvc
```
<details>
<table>
<tr>
<td> 2.42.0 </td> <td> #8849 </td>
</tr>
<tr>
<td>
```yaml
md5: 677db99135cf82ed1b726b6be7abef49
frozen: true
deps:
- md5: a042035f7fb17fc84a42e33787ae4b6a.dir
size: 13
nfiles: 3
path: s3://diglesia-bucket/data
files:
- size: 5
version_id: dQymcW0EvEqy23qfrksrqo0ni2zGtPMG
etag: 042967ff088f7f436015fbebdcad1f28
relpath: bar
- size: 4
version_id: pd67.5YcvjqDm7jfmiHbpeQsXnprrXtf
etag: d3b07384d113edec49eaa6238ad5ff00
relpath: foo
- size: 4
version_id: 2ruNQaorqjnsFQZ5cinHsZSHEw7cz26J
etag: 7361528e901ca2f2f1952a68ad242d79
relpath: goo
outs:
- md5: …
```
> output: Don't serialize `hash_info` or `meta` in cloud versioning.

- dvc/repo/add.py
- dvc/repo/worktree.py
- dvc/stage/__init__.py
- tests/func/test_commit.py
If we want `add`, `commit` and `move` to work for cloud versioning, the option must be always True so it is the same as not having it.
Closes #8828
(We were not passing `merge_versioned=True` in `dvc commit`)
---
After the first `push`:
```console
$ mkdir data
$ echo bar > data/bar
$ echo foo > data/foo
$ dvc add data
$ dvc push -v
```
Tracking local updates:
```console
$ echo bar2 > data/bar
```
Works as expected with either `dvc add data` or `dvc commit`:
```console
$ dvc add data
$ cat data.dvc
outs:
- path: data
files:
- size: 5
md5: 042967ff088f7f436015fbebdcad1f28
relpath: bar
- size: 4
version_id: Vnu6l9_ECdLGrp6B5iK6YmQTm87UaDzP
etag: d3b07384d113edec49eaa6238ad5ff00
md5: d3b07384d113edec49eaa6238ad5ff00
relpath: foo
```
```console
$ dvc commit
$ cat data.dvc
outs:
- path: data …
```
> stage.save: Remove `merge_versioned` option.

- dvc/data_cloud.py
- dvc/output.py
- dvc/repo/__init__.py
- dvc/repo/worktree.py
- dvc/stage/serialize.py
- pyproject.toml
Requires https://github.com/iterative/dvc-data/pull/280.
Also splits metadata in `files` to cloud vs local. But this happens
during dump/load, so actual behaviour is changed. During runtime,
the metadata is merged and loaded. During dump, the metadata
are split if there is a `remote` set.
The metadata will look as follows:
```yaml
files:
- size: 75570
relpath: 0.txt
md5: c7d28800060176f0438fb0774a00b3be
cloud:
remote1:
version_id: 02e850d5-5dc9-40ee-8969-24c098c99c7e
etag: c7d28800060176f0438fb0774a00b3be
```
> add support for output-specific remotes

- dvc/repo/imp_url.py
> import/import-url: try not to delete dvcfile before import/import-url completes

- dvc/output.py
- tests/unit/output/test_output.py
This will be ignored by filesystems that don't support `version_aware`.
Closes #8853
---
From the initial state:
```console 
$ dvc import-url --version-aware s3://diglesia-bucket/data
$ cat data/goo 
goo
$ cat data.dvc
md5: 3a8c037877cf0a60e34e3a22498d2b7e
frozen: true
deps:
- path: s3://diglesia-bucket/data
files:
- size: 4
version_id: Ce2wcT8cyQY8XvjH2ySVKrtsFsFy.M8a
etag: c157a79031e1c40f85931829bc5fc552
relpath: bar
- size: 4
version_id: 07q_0VQgMOzQU_1l4q_4qVWSmH9KtoaN
etag: d3b07384d113edec49eaa6238ad5ff00
relpath: foo
- size: 4
version_id: VhK8GEPzz9p5TXNtl0gXMMrZTgbR93UY
etag: 7361528e901ca2f2f1952a68ad242d79
relpath: goo
outs:
- md5: bb5c48ab712b680ad28fd8d7bda8fb4f.dir
size: 12
nfiles: 3
path: data
push: false
```
After updating the remote:
```console
$ echo gooupdated > goo
$ …
```
> output: Pass `version_aware=True` to `fs` if `files` is present.

- dvc/compare.py
Issue https://github.com/iterative/dvc/issues/8891
> Fixed typo in _format_field function. issue https://github.com/iterative/dvc/issues/8891

- dvc/analytics.py
- pyproject.toml
- tests/unit/test_analytics.py
This would help to separate CI users in analytics. Depends on https://github.com/iterative/telemetry-python/pull/53.
Also needs a docs update in https://dvc.org/doc/user-guide/analytics.
> analytics: differentiate ci users

- dvc/repo/brancher.py
- dvc/scm.py
- tests/func/test_gc.py
- tests/unit/scm/test_scm.py
- `gc --date` was broken because the wrong attribute was being accessed resulting in an unexpected exception.
- `--date` was being ignored by `brancher` unless one of `--all-branches`, `--all-tags`, `--all-commits`, `--all-experiments` was also provided.
- added test for `--date`
Originally reported on [discord](https://discord.com/channels/485586884165107732/485596304961962003/1067801969214902273)
> gc: fix usage with --date

- dvc/repo/index.py
This is very useful to identify indexes that are built from git revisions and so are describing an immutable state and can be used for caching.
We were already using this for `__repr__`.
> index: expose rev property

- .github/workflows/plugin_tests.yaml
Related to https://github.com/iterative/dvc/issues/8850
- Adds workflow for running remote plugin tests against PR's (useful since the plugin tests are normally only run against DVC main on a cron schedule)
- Currently only runs dvc-s3 tests on ubuntu + py3.10 but this can be expanded later if needed
> ci: run dvc-s3 tests on DVC pull requests

- dvc/repo/imp_url.py
- dvc/testing/remote_tests.py
- dvc/testing/workspace_tests.py
Closes #8850
- Fixes `import-url` bug where version-aware import status would be reported as `changed checksum` due to computing stage checksum before we set `push: false`
- Adds tests for worktree `dvc update`
- Adds tests for version-aware `dvc import-url`, `dvc update`
> testing: add tests for cloud versioned update and import-url

- dvc/cli/__init__.py
```console
$ dvc stage list --all -vv
2023-01-31 13:10:14,052 DEBUG: v2.43.1 (pip), CPython 3.11.0 on Linux-6.1.6-arch1-3-x86_64-with-glibc2.36
2023-01-31 13:10:14,052 DEBUG: command: /home/saugat/projects/iterative/dvc/venv/bin/dvc stage list --all -vv
```
> logging: log pkg version/type, platform info and cli arguments

- dvc/info.py
It was a bit annoying to see the dashes and the version not line up. 😄
> version/info: match dashes' length below DVC version

- dvc/repo/stage.py
- tests/func/test_repo_index.py
Otherwise when using brancher we end up in a strange situation where even though we are collecting targets from `gitfs`, we are still using `localfs` as `self.fs`, which make operations like `self.fs.abspath` in `collect_granular` return invalid paths.
> stage: use repo.fs directly without copying

- dvc/repo/index.py
- tests/func/test_repo_index.py
`data_keys` are similar to `outs`, but they provide more granularity, so we can use them in `build_data_index` to rebuild index views with filtered outputs. E.g. when running `dvc diff dir/file`, workspace index should only have `dir/file` in it.
This also could be used for standalone (non-output) data in the future.
Pre-requisite for #8930
> index: introduce data_keys

- dvc/output.py
- dvc/repo/update.py
- dvc/repo/worktree.py
- dvc/testing/remote_tests.py
- Fixes an issue where `update` would download the updated files but `files:` entries for updated dirs could still contain the old version IDs (even for modified files)
- Also removes support for `--remote` in worktree `dvc update`
> worktree update: fix metadata merge on update

- dvc/testing/workspace_tests.py
- pyproject.toml
Fixes https://github.com/iterative/dvc/issues/8932
> import-url: fix `pull` after `import-url --version-aware` with subdirs

- dvc/testing/remote_tests.py
- pyproject.toml
See https://github.com/iterative/dvc-objects/issues/192
`00/...` prefix traversal tests were lost at some point when we migrated to the current plugins + `dvc[testing]` setup (https://github.com/iterative/dvc/commit/b6f2a8e653d1c6e5a88bacb640e45852d60a5f6a)
> testing: re-add 00 prefix remote traverse tests

- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/queue/workspace.py
- dvc/repo/experiments/utils.py
- tests/func/experiments/test_utils.py
- tests/integration/conftest.py
- tests/integration/test_studio_live_experiments.py
#8951 now works when manually setting `STUDIO_REPO_URL` as an env var.
Still need to find a way to workaround https://github.com/iterative/dvc/issues/8951#issuecomment-1416170130
> studio: Move `post_live_metrics` from `queue` to `executor`

- dvc/repo/experiments/executor/base.py
- pyproject.toml
fix: #8762
partly solve #8787 and #8477
Improve the performance
Wait for https://github.com/iterative/scmrepo/pull/169
The performance improvement are shown in https://github.com/iterative/scmrepo/pull/169. 
For the benchmark because the fetch operation only happens during `temp` or `queue` experiment running progress. We don't have this kind of benchmark and also hard to build one. 
> Use pygit2 backend for fetch_refspecs

- dvc/output.py
- dvc/stage/serialize.py
Fixes partially https://github.com/iterative/dvc/issues/8941. 
I copy-pasted what we do in `dvc-data` for now, as I think the serialization story belongs in dvc, not in `dvc-data`. Also, `obj.as_list()` is probably doing too much than required.
```yaml
outs:
- path: models
files:
- relpath: 0.txt
md5: bd5fe549afd3fa36ca22225a21ab899d
size: 377846
cloud:
minio:
etag: bd5fe549afd3fa36ca22225a21ab899d
version_id: 0f6cece1-574f-40ed-8d7f-9182c39b5908
- relpath: dir0/0.txt
md5: 8adc00306d1db55a12388ca3b9871ea1
size: 417716
cloud:
minio:
etag: 8adc00306d1db55a12388ca3b9871ea1
version_id: 88a7e774-2ae0-4b68-8a45-5e0b027790d7
- relpath: dir0/dir0/0.txt
md5: ed40848698ce65ddb61ecf7e8f94239d
size: 437141
cloud:
minio:
etag: ed40848698ce65ddb61ecf7e8f94239d
version_id: …
```
> serialization: reorder files section metadata (#8950

- dvc/repo/experiments/run.py
- tests/func/experiments/test_set_params.py
This allows naming a batch of experiments when sweeping over parameters. Instead of each having a random name, when setting `--name myname` they'll be called `myname1`, `myname2`, etc.
> Support setting a exp name prefix in hydra sweeps

- dvc/output.py
- dvc/repo/imports.py
- dvc/repo/index.py
- dvc/testing/workspace_tests.py
Fixes https://github.com/iterative/dvc/issues/8954
Should also resolve the "files are downloaded after `dvc update` with no changes" problem in https://github.com/iterative/dvc/issues/8464
> import-url: fix `update` after cloud versioned `import-url --no-download`

- dvc/repo/worktree.py
- pyproject.toml
Fixes https://github.com/iterative/dvc/issues/8824.
Requires https://github.com/iterative/dvc-data/pull/296.
```console
$ dvc push
ERROR: while uploading 'unversioned/foo', support for versioning was not detected
ERROR: failed to push data to the cloud - remote 'minio' does not support versioning
```
> push: check if versioning is supported or not during checkout on cloud versioning (#8949)Fixes https://github.com/iterative/dvc/issues/8824

- dvc/logger.py
…rs/handlers/formatters
dictConfig clears all handlers, and potentially disables existing loggers (we disabled this functionality though). There's much more code than necessary in dictConfig than what we need.
I have tried to keep the setup equivalent to what we had in the config, so I have not tried to cleanup the code.
> [WIP] logging: change from dictConfig to equivalent code for creating logge… (#8985

- dvc/logger.py
- tests/unit/test_logger.py
- Also adds support for printing `stack_info`
- Changed datetime color to be same as log-level color, instead of it always being `GREEN`.
- Simplified code
- Removed line that we used to print as a separation for exception for simplicity. Now, we have similar logic to `StreamHandler`.
> logger: check isatty stream to print colored logs or not instead of depending on colorama (#8993

- dvc/cli/__init__.py
- dvc/logger.py
- dvc/repo/experiments/executor/base.py
- tests/dir_helpers.py
Since we lazy load most of the packages, running this has no effect except to disable tqdm, tqdm.cli, asyncio, aiohttp, dvc-data, and dvc-objects. The former two don't have any impact, the other two are changed to CRITICAL during setup, and dvc-data/dvc-objects are set to log same as dvc's logger.
So, we don't need to disable other loggers here. Also, I am not sure if other loggers output to stderr/stdout, as they are not supposed to by default AFAIK (except when they are warning/error).
Closes #8631.
> logging: do not disable other loggers

- dvc/commands/update.py
Drops worktree from `dvc update` help text.
> update: drop worktree from cli

- dvc/config_schema.py
- dvc/repo/index.py
Putting https://github.com/iterative/dvc-data/issues/208 to use.
Note that this is `experimental` for now and needs to be enabled with `dvc config feature.data_index_cache true`.
For example, sequential run of
```
dvc list . data/mnist/dataset/ --recursive --rev HEAD
```
goes down from ~16sec to ~8sec (2x improvement)
and 
```
dvc list . data/mnist/dataset/ --rev HEAD
```
goes down from ~11sec to ~1.5sec (7x improvement)
> index: experimental persistent data index

- dvc/repo/__init__.py
- dvc/repo/index.py
- tests/func/test_data_cloud.py
Extracting from `index.data` as a "root" data index that contains indexes for different revisions/workspaces.
This is a setup for putting cloud versioning remote indexes and also replacing old state.
> repo: introduce data_index

- dvc/external_repo.py
- dvc/repo/experiments/utils.py
- dvc/scm.py
refspecs uses pygit2 backend by default, which does not support git credential helpers. This PR forces to use dulwich backend during clone/pull operations. Other uses of refspecs (in `experiments` in particular) is broken for users of git credential-helpers though.
Fixes #9016.
> scm: use dulwich backend when fetching exps during clone/pull

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/queue/base.py
- pyproject.toml
- tests/func/experiments/test_stash_exp.py
Closes #8998 
- Detach head after stashing workspace.
- Use reinstate_index from https://github.com/iterative/scmrepo/releases/tag/0.1.10.
> 8998 exp run include new staged files

- dvc/data_cloud.py
- dvc/repo/index.py
- dvc/repo/worktree.py
- pyproject.toml
This allows us to reuse cloud versioning index that we've built in other operations like `data status`.
Note, this only works with `dvc config feature.data_index_cache true` right now.
Also note that index is not populated for regular remotes, it will come in a separate PR as there are some http-related issues to figure out.
Related #8962 https://github.com/iterative/dvc/issues/8761
> repo: cache index for cloud versioning

- dvc/render/convert.py
- dvc/render/converter/vega.py
A low hanging fruit that reduces 20% of runtime when run in [`vscode-dvc-demo`](https://github.com/iterative/vscode-dvc-demo) with:
```console
dvc plots diff $(git log --oneline --pretty=format:"%h")
```
> render: avoid deepcopying

- dvc/cachemgr.py
- pyproject.toml
We used to use it in gdrive before https://github.com/iterative/PyDrive2/pull/211
> cachemgr: don't use tmp_dir

- dvc/cli/__init__.py
- dvc/logger.py
> ui: log footer support message to standard error

- dvc/external_repo.py
- dvc/repo/experiments/utils.py
- dvc/scm.py
Reverts iterative/dvc#9023. Fixed upstream by https://github.com/iterative/scmrepo/pull/189 (that fallbacks to dulwich if users have credential helper set).
Also see #9039 where we bumped scmrepo with the above patch.
> Revert "scm: use dulwich backend when fetching exps during clone/pull"

- dvc/cachemgr.py
- dvc/commands/cache.py
- dvc/config.py
Setting default values is very untypical for all other applications and the info config has is not enough to make a decision on the default cache dir, especially when dealing with gitfs.
Fixes #8705
> config: don't set default cache dir

- dvc/cachemgr.py
- dvc/config_schema.py
- dvc/repo/__init__.py
This moves it to within the repo (.dvc/index/data) and enables it by default.
Previously this was an opt-in and we used to use `appdirs.user_cache_dir`(usually somewhere in ~), which was an attempt at making NFS experience smoother, but it turns out having your home directory on NFS is way too common, so we will have to tweak sqlite either way and, in worst cases, will be forced to use a custom `index.dir`(already used for old remote indexes and state has `state.dir` which will hopefuly soon be dropped).
Related #8962
> repo: enable data index caching by default

- dvc/cachemgr.py
- dvc/repo/__init__.py
Same as https://github.com/iterative/dvc/pull/9044 but without making persistent index enabled by default (should've just reverted last commit, but oh well 🤷 )
See https://github.com/iterative/dvc/pull/9045
> repo: move data_index to .dvc/tmp/index

- pyproject.toml
Improves index view related performance (e.g. `dvc diff`).
> deps: bump dvc-data to 0.40.4

- pyproject.toml
let's try this out, and see how it goes. If there are dependencies that gives us trouble, we can pin them. Will save us from maintenance work from dependabot updates.
> deps (tests): unpin test deps

- pyproject.toml
Looks like we are not using it.
> deps: drop importlib-resources and typing-extensions

- dvc/repo/index.py
Tidying it up, so root of the index will look like this:
```
tree/
remote/
```
This hasn't been released yet, so we are not breaking anything.
> index: store data index under tree prefix

- dvc/repo/experiments/save.py
- tests/func/experiments/test_save.py
> exp save: Use `pathspec` to handle `include_untracked`.

- dvc/commands/experiments/show.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/cache.py
- dvc/repo/experiments/serialize.py
- dvc/repo/experiments/show.py
- tests/func/experiments/test_show.py
- tests/unit/command/test_experiments.py
related to https://github.com/iterative/dvc/issues/8787
- `exp show` data is cached in `.dvc/tmp/exps/cache/...` by git SHA
- `exp show` will prefer loading cached data rather than collecting from git when possible
- workspace data is never cached
- when collecting active/running experiments cached data is ignored and the exp will be re-collected
- `metrics` field is now always returned for consistency, previously `metrics` field was omitted in certain cases (like queued exp commits)
- for queued exps `metrics` will just contain an empty dictionary (this should not affect vscode as far as I can tell)
- adds `exp show -f/--force` option to force exp collection (instead of loading from cache when possible)
> exp show: cache collected experiments by git revision

- dvc/output.py
- dvc/repo/commit.py
- dvc/repo/experiments/queue/base.py
- dvc/stage/__init__.py
During `exp run` we just want to backup the data to cache to be able to use it in experiments and we don't really need to relink the files in the workspace.
With a dir of 8K files `exp run` goes down from ~20sec to ~10sec for me.
Part of #8809
> exp: run: don't relink during commit

- dvc/commands/data_sync.py
- dvc/repo/pull.py
- tests/func/test_data_cloud.py
- tests/unit/command/test_data_sync.py
Allows `pull` to succeed even if some files or directories are missing.
Closes #4746
> pull: Add `allow_missing` flag.

- dvc/testing/fixtures.py
> testing: fixtures: fix docker regression

- dvc/testing/fixtures.py
- pyproject.toml
I wanted to depend on internals of `pytest_docker` as much as possible, but the lifecycle of it makes it very difficult to do so. (and considering we use `pytest-xdist` this makes it much harder).
> dvc.testing: fix lockfile in docker_services fixture

- .github/workflows/packages.yaml
macos-10.15 image has been deprecated for a while, see https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/ and https://github.com/actions/runner-images/issues/5583.
setup-ruby removed the support for these images yesterday: https://github.com/ruby/setup-ruby/pull/467.
which fails our package builds. Now using macos-11 to build packages.
> build: use macos-11 to build package

- dvc/repo/experiments/save.py
Same change as in https://github.com/iterative/dvc/pull/9076 but for `exp save`
> exp save: Don't relink during commit

- dvc/repo/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/queue/tasks.py
Related: https://github.com/iterative/dvc/issues/8787
Queued (celery) tasks open new `repo.Repo` instances per task (since they are run independently), but repo instances were not being explicitly `close()`ed and any open resources from the repo were leaked. This also meant that each `repo.scm` instance was also leaked (since we never called `repo.scm.close()`) which in turn would lead to dulwich/pygit file handles to git object stores not being closed.
This chain eventually causes us to run out of file descriptors given either a long enough worker run (i.e. lots of experiments being run in a single worker) or large enough concurrency (i.e. lots of parallel worker --jobs), which would then cause the celery …
> exp: fix celery run file descriptor leak

- dvc/repo/experiments/executor/local.py
- dvc/repo/experiments/executor/ssh.py
Closes #8844
Gets rid of the remaining `git merge` usage from `exp run` which should allow it to be used in shallow git repos
> exp: use stash-apply instead of merge

- dvc/data_cloud.py
- dvc/testing/workspace_tests.py
- tests/func/test_add.py
- tests/func/test_import_url.py
> remote: set hash_name as md5

- dvc/commands/experiments/__init__.py
- dvc/commands/experiments/clean.py
- dvc/commands/experiments/queue_worker.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/clean.py
- dvc/repo/experiments/queue/celery.py
- pyproject.toml
- tests/func/experiments/test_experiments.py
- tests/unit/command/test_experiments.py
Closes: https://github.com/iterative/dvc/issues/8676
Related: https://github.com/iterative/dvc/issues/8787
- Adds `dvc exp clean` to cleanup unneeded files from `.dvc/tmp/exps`. Currently only does dvc-task/celery garbage collection
- Celery messages are now automatically garbage collected in the background on queue worker exit (when a complete `dvc queue start` or `dvc exp run --run-all` batch finishes)
> exp: support dvc-task/celery message cleanup

- dvc/scm.py
- tests/unit/scm/test_scm.py
Not used after https://github.com/iterative/dvc/pull/9096
> scm: Remove unused GitMergeError.

- dvc/repo/experiments/serialize.py
- dvc/repo/experiments/show.py
Skip caching revs that contain collection errors for now. When we have better error handling and can differentiate between errors that are cacheable (git-committed invalid files) and those that are not (retry-able network errors) we can re-enable this.
See https://github.com/iterative/dvc.org/pull/4346#discussion_r1123566099
> exp show: don't cache collection errors

- dvc/commands/plots.py
- dvc/render/match.py
- dvc/repo/plots/__init__.py
- tests/func/plots/test_show.py
- tests/unit/command/test_plots.py
- [plots: Remove unnecessary OrderedDict usage in load_sv.](https://github.com/iterative/dvc/pull/9072/commits/621b67778296ab8bb2824545c8d6c0d2a0089ef4)
- [plots: Remove --from-config](https://github.com/iterative/dvc/pull/9072/commits/0b146c3bee8c981f992e82438b336b3fdd68837c)
- [plots: Fix match_defs_renderers when plots are defined in nt format.](https://github.com/iterative/dvc/pull/9072/commits/9da193dddd06c99f176db21ff053bc6db42be7f7)
`plots.show` returned `definitions` in native `nt` format but sources in `posixpath` format so the matching was failing.
Closes https://github.com/iterative/dvc/issues/8689
- Add `test_show_plots_defined_with_native_os_path`.
> plots: Fix plots defined with windows syntax

- dvc/config.py
- pyproject.toml
appdirs has been deprecated/unmaintained, platformdirs is now recommended. Closes #9130.
> migrate from appdirs to platformdirs

- dvc/repo/push.py
Allows running `dvc push` in a repo with a config like this (note, no default remote is set):
```
[core]
['remote "production"']
url = s3://dvc-temp/ivan/test-multiple-remotes
['remote "sandbox"']
url = s3://dvc-sandbox-temp/ivan/test-multiple-remotes
```
It's a valid scenario in cases like described here https://github.com/iterative/studio-support/issues/50 - where all outputs are explicitly assigned a remote. E.g. this the modification of the `example-get-started` that I was using to reproduce:
<details>
<summary>dvc.yaml</summary>
```yaml
stages:
prepare:
cmd: python src/prepare.py data/data.xml
deps:
- data/data.xml
- src/prepare.py
params:
- prepare.seed
- prepare.split
outs:
- data/prepared:
remote: production
featurize:
cmd: python src/featurization.py data/prepared data/features …
```
> push: allow no default remote

- dvc/repo/experiments/utils.py
- tests/unit/repo/experiments/test_utils.py
Context: I found this when testing out a https://github.com/iterative/dvclive/pull/464 in a repo with overlapping outputs (tracking the model as both a stage output and in a .dvc file).
Before this PR:
```
$ dvc exp run -f
DVC failed to load some parameters for following revisions: ''.
DVC failed to load some metrics for following revisions: ''.
ERROR: Failed to reproduce experiment '9dc4c70': 'data'
```
After this PR:
```
$ dvc exp run -f
DVC failed to load some parameters for following revisions: ''.
DVC failed to load some metrics for following revisions: ''.
ERROR: output 'model' is already specified in stages:
- train
- model.dvc
```
This still isn't a good UX, but at least now I can see a somewhat more useful error.
> studio: handle revision errors when posting

- dvc/repo/__init__.py
- dvc/repo/brancher.py
- dvc/repo/data.py
- dvc/repo/experiments/show.py
- dvc/repo/experiments/utils.py
- dvc/scm.py
- tests/func/experiments/test_checkpoints.py
- tests/unit/fs/test_data.py
- tests/unit/fs/test_dvc.py
There's several places that we use brancher to switch the repo context to a specific git rev (especially in experiments), but brancher includes a lot of unnecessary overhead since it is designed to iterate over multiple revs and do git branch/tag lookups, etc.
- Adds `brancher.switch`/`repo.switch` (equivalent to `git switch`) to switch repo fs context to a specific revision (as opposed to iterating over all contexts for a range of revs in `brancher.brancher`). Note that this is not equivalent to `brancher([rev], sha_only=True)` because brancher always adds `workspace` to the list of revisions.
> repo: add `brancher.switch`

- tests/func/experiments/conftest.py
- tests/func/experiments/test_apply.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_queue.py
- tests/unit/repo/experiments/conftest.py
- tests/unit/repo/experiments/queue/test_celery.py
Reduces startup/teardown overhead for most exp queue tests. In some cases we still have to use function-scoped workers due to the nature of the test (mainly `tests/func/experiments/test_queue.py` and `tests/unit/repo/experiments/queue/...`)
> tests: use session-scoped exp celery fixtures when possible

- dvc/config_schema.py
- dvc/fs/__init__.py
- tests/unit/test_config.py
A warning is shown to the user for the unsupported/ignored keys, and then ignored. The warning is raised only once per interpreter session.
> config: ignore unspecified keys from `feature` section

- dvc/commands/plots.py
- dvc/ui/__init__.py
I don't think it's worth it to highlight given the size of json output.
Note that highlighting was/is off when the stdout is redirected.
> plots: disable syntax highlighting on plots json output

- dvc/repo/experiments/utils.py
- tests/func/test_gc.py
- tests/unit/scm/test_scm.py
> exp: push/pull: don't include baseline commit

- pyproject.toml
Brings support for cloud versioning and imports to dvcfs.
> deps: bump dvc-data to 0.44.0

- dvc/ui/__init__.py
On a large json output (say ~300MB), this saves about ~6 seconds of time.
> ui: disable colorama on write_json when highlighting is disabled

- dvc/ui/__init__.py
It might affect pytest as it wraps sys.stderr/sys.stdout for capsys fixture. This is a temporary hack, as we might get rid of colorama soon.
> do not disable colorama in tests

- dvc/dependency/repo.py
- dvc/repo/index.py
Stepping stone to simplifying `dvc fetch/pull` by using index.
Fetch handles regular imports through index already, but not repo imports because their processing is much more involved (e.g. chained imports) in the current arch.
With `FileStorage` support introduced into `DataIndex` and `datafs` supporting imports overall, `dvcfs` can now handle repo imports (even chained ones). This will soon allow us to handle repo imports the same way we handle regular ones, improve performance and get rid of a lot of messy code (e.g. DependencyRepo).
Related https://github.com/iterative/scmrepo/issues/207
Related https://github.com/iterative/dvc-data/pull/315
Related https://github.com/iterative/studio/issues/5261
> index: data: support imports

- dvc/dependency/repo.py
Otherwise our wrapper ignores it.
> deps: repo: pass url explicitly to DVCFileSystem

- dvc/repo/__init__.py
- tests/func/test_repo.py
If we are asked to open a potentially unitialized repo, we need to make sure it is not a bare git repo, so that we don't accidentally start putting dvc files inside git control dir.
Discovered while working on #8789
> repo: open: handle bare git repos

- dvc/config_schema.py
- dvc/repo/experiments/push.py
- tests/unit/repo/experiments/test_push.py
Currently blocked, as we don't have any endpoints. We have agreed on the payload for now.
This will be behind a feature flag before the endpoint is stable. You can turn this by following ways:
```console
dvc config feature.push_exp_to_studio true
```
To push experiments, it needs a `STUDIO_TOKEN` envvar set.
And just do `dvc exp push`.
I'll merge this on approval, as everything is behind a feature-flag, and requires `STUDIO_TOKEN` to be set.
Closes https://github.com/iterative/dvc/issues/9163.
> exp push: push experiments revs to studio

- dvc/commands/plots.py
- dvc/render/convert.py
- pyproject.toml
- tests/unit/command/test_plots.py
- tests/unit/render/test_convert.py
Improve performance by removing unnecessary `json.dumps` calls.
See https://github.com/iterative/dvc-render/pull/124
> deps: bump `dvc-render>=0.3.1<0.4.0`.

- dvc/fs/dvc.py
- dvc/repo/plots/__init__.py
- dvc/utils/serialize/__init__.py
- pyproject.toml
Closes https://github.com/iterative/dvc/issues/9030.
Depends on https://github.com/iterative/dvc-data/pull/333.
> dvcfs: support caching remote streams; use that in plots

- dvc/daemon.py
Even though #9202 is not necessary now, I am keeping it to have the same behavior as colorama, as [`colorama` always flushes by default](https://github.com/tartley/colorama/blob/21c4b94fe21ce29c85c896ace828da24b7527641/colorama/ansitowin32.py#L180). Colorama itself does not have any buffers, it just calls wrapped streams.
> flush streams before fork

- dvc/daemon.py
I have been seeing weird perf issue when the output was being redirected:
```console
$ time dvc plots show --json | less
{}
dvc plots show --json  0.38s user 0.06s system 96% cpu 0.452 total
less  0.00s user 0.00s system 0% cpu 1.731 total
$ time DVC_NO_ANALYTICS=true dvc plots show --json | less
{}
DVC_NO_ANALYTICS=true dvc plots show --json  0.33s user 0.04s system 96% cpu 0.393 total
less  0.00s user 0.00s system 0% cpu 0.393 total
```
I could not find an issue why it would take so long, but my suspicion was that the stdin to the `less` was not being closed for some reason. So I tried adding `os.close()` and it was fast again. 
I was not able to find an issue regarding this on Cpython, and I would love if I could get confirmation of the bug from other team members as well.
The `dvc …
> close streams

- dvc/repo/experiments/utils.py
Required for Studio temporarily to allow them to choose backends.
> scm: fetch_all_exps pass kwargs to scm.fetch_refspecs

- dvc/external_repo.py
Repo can manage both of those by itself just fine. This is a leftover explicitness from the times before `rev` support.
Towards unifying `Repo.open` and `external_repo` behavior to get rid of the latter.
> erepo: pass rev instead of fs/scm

- dvc/dependency/repo.py
- dvc/external_repo.py
- dvc/repo/get.py
- tests/unit/test_external_repo.py
Towards unifying `Repo.open` and `external_repo` behaviour to get rid
of the latter.
Related #8789
> erepo: set subrepos/uninitialized explicitly

- dvc/api/data.py
- dvc/commands/get.py
- dvc/data_cloud.py
- dvc/dependency/repo.py
- dvc/exceptions.py
- dvc/external_repo.py
- dvc/repo/__init__.py
- dvc/repo/diff.py
- dvc/repo/ls.py
- tests/func/api/test_data.py
- tests/func/test_diff.py
- tests/func/test_external_repo.py
- tests/func/test_get.py
- tests/func/test_import.py
- tests/func/test_ls.py
These are from back in the very early days of API, where things like `dvc import` didn't exist yet, let alone chained imports.
Note that user facing API does not change at all ([caveat is FileMissingError inconsistency](tests/func/test_external_repo.py::test_external_repo)). We might want to remove the wrappers in 3.0
Towards unifying Repo.open and external_repo behavior to get rid of the latter.
Related https://github.com/iterative/dvc/issues/8789
> erepo: move legacy exceptions to api

- dvc/exceptions.py
- dvc/repo/stage.py
- tests/func/test_stage.py
Fixes #8986
Before this PR:
```
$ dvc stage add -f -n train -d train.py -o model python train.py
ERROR: output 'model' is already specified in stages:
- model.dvc
- train
```
After this PR:
```
$ dvc stage add -f -n train -d train.py -o model python train.py
ERROR: output 'model' is already specified in stage: 'model.dvc'.
Use `dvc remove model.dvc` to stop tracking the overlapping output.
```
> Update duplicate output error msg

- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/executor/local.py
- dvc/repo/experiments/save.py
- tests/func/experiments/test_save.py
Closes #9058
Ensures behavior of `_stash_exp` in `exp run` is matched in `exp save` without duplicating logic.
The simpler implementation ended up being worse for keeping `exp run` and `exp save` behavior in sync.
> exp save: Reintroduce implementation based on `executor`/`queue`.

- dvc/repo/experiments/push.py
- tests/unit/repo/experiments/test_push.py
`/webhook/dvc` redirects to `/webhook/dvc/` where the payload gets lost. So we should be posting to the canonical url.
> exp push: add trailing slash to the endpoint url

- dvc/commands/plots.py
- dvc/render/match.py
- dvc/repo/plots/__init__.py
- tests/func/plots/test_show.py
- tests/integration/plots/test_plots.py
- tests/unit/command/test_plots.py
- tests/unit/render/test_match.py
This PR changes the schema to:
```json
{
"errors": [
{
"name": "<plot_name>",
"rev": "<rev>",
"source": "<source_file>",
"type": "<Type>",
"msg": "<msg>",
},
],
"data": {}
}
```
The existing data is kept inside `"data"` and the new `"errors"` key is introduced where errors are a list of errors.
Closes #9025. 
Closes #7692.
> plots: return errors in json format

- dvc/output.py
Prevents https://github.com/iterative/studio/issues/5172 from happening. A filesystem may not always return size information.
> output: ignore missing size from files when calculating total size

- dvc/repo/experiments/push.py
- dvc/utils/studio.py
- tests/unit/utils/test_studio.py
This is a simple refactoring which makes the caller to choose appropriate token instead of the studio.notify_refs making a decision for them.
> utils.studio: require token

- dvc/repo/experiments/remove.py
- tests/func/experiments/test_remove.py
Before:
```
$ dvc exp remove -g upstream bijou-rues
ERROR: 'bijou-rues' is not a valid experiment name
```
After:
```
$ dvc exp remove -g upstream bijou-rues
ERROR: Experiment 'bijou-rues' does not exist in 'upstream'
```
> exp remove: fix ui for removing from git remotes

- dvc/analytics.py
- dvc/commands/config.py
- dvc/config.py
- dvc/parsing/interpolate.py
- dvc/repo/__init__.py
- dvc/updater.py
- tests/func/test_config.py
- tests/unit/test_config.py
Currently if dvc_dir doesn't exists (e.g. we are creating an uninitialized repo), config will try looking for `.dvc` dir in the current directory, which might be inside of another dvc repository resulting in mixed configs.
Use explicit `from_cwd` method to make `Config` try to find repo configs if available to avoid the usage mixup.
Related https://github.com/iterative/dvc/issues/8789
Related #9246
> config: don't look for .dvc dir implicitly

- dvc/repo/status.py
It's just an alias to the function from itertools.
Closes https://github.com/iterative/dvc/pull/9276 and closes https://github.com/iterative/dvc/pull/9275.
Thanks @srdecny.
> replace funcy.cat with itertools.chain.from_iterable

- dvc/dependency/repo.py
- dvc/exceptions.py
- dvc/output.py
- dvc/repo/imports.py
- dvc/repo/index.py
- dvc/repo/init.py
- pyproject.toml
- tests/func/test_data_cloud.py
- tests/func/test_import.py
Makes `dvc get/import/etc` use `dvcfs`, which already supports cloud versioning, circular imports and other stuff.
Also makes `dvc import` behave more like `dvc import-url`, so that we can use the same existing logic for fetching those using index instead of objects.
Fixes #8789
Related https://github.com/iterative/studio/issues/4782
> dep: repo: use dvcfs

- dvc/config_schema.py
- dvc/repo/__init__.py
Makes repo dirs isolated by user which handles shared server scenarios. But also introduces `core.site_cache_dir` as a last line of defense in case there is some scenario we haven't thought about. Overall we should discourage using this config option as it could be misused (e.g. never put it on NFS/CIFS/etc or other slow filesystems for performance reasons). If you find yourself needing this config option, please let us know about your scenario so we could see if we could make it work out of the box.
Note that `site_cache_dir` name might be confusing in relation to `dvc cache` with which it has absolutely nothing to do with. The name is coming from an internal library platformdirs(former appdirs)'s site_cache_dir.
Fixes #9249
> repo: site_cache_dir improvements

- dvc/utils/studio.py
- tests/unit/utils/test_studio.py
This PR prevents Studio API to return a redirect as the redirect don't work with POST request anyway, and might be more secure.
Also misc naming changes. Renamed `endpoint` to `url` and `url` to `base_url`.
> utils.studio: disallow redirects, misc API refactoring

- dvc/commands/experiments/exec_run.py
- dvc/commands/experiments/run.py
- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/executor/ssh.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/queue/tasks.py
- dvc/repo/experiments/queue/tempdir.py
- dvc/repo/experiments/queue/workspace.py
- dvc/repo/experiments/run.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_queue.py
- tests/func/experiments/test_set_params.py
- tests/unit/command/test_experiments.py
List of paths to copy inside the temp directory. Only used if `--temp` or `--queue` is specified.
Closes #5800
Closes https://github.com/iterative/cse/issues/99
> exp run: Add `--copy-paths` arg.

- dvc/commands/experiments/push.py
- dvc/repo/experiments/push.py
- tests/func/experiments/test_remote.py
Closes https://github.com/iterative/dvc/issues/9280.
> exp push: improve ui

- pyproject.toml
People are still running into `ImportError: cannot import name 'fsspec_loop' from 'fsspec.asyn' ` because of it.
Fixes #9244
> deps: put lower bound on dvc-http

- tests/func/experiments/test_save.py
dvc.run does not expand variables. It is only done when it's actually read from dvc.yaml file. So during dvc run, the shell will try to expand the variable, which does not exist.
I don't think that the intention was to use shell variables. But I don't think we should ever use them, as they will fail on some shells (eg: fish) and should keep the scripts as simple as possible.
> tests: remove unnecessary variable interpolation

- dvc/config_schema.py
- dvc/repo/experiments/push.py
> [DO NOT MERGE] release: remove feature flags for experiment sharing

- dvc/utils/studio.py
This keeps it in symmetry with
https://github.com/iterative/dvc-studio-client/pull/28, and allows setting the base url with path, not just limited to netloc.
This was always intended to work, urljoin with the added slash was causing this bug.
> utils.studio: allow any base url to be set, not just the hostname

- dvc/repo/experiments/collect.py
In #9348, I missed that there was a workspace row for the running experiment in the workspace because it wasn't shown until after all the completed experiments. In general, I think it's better to prioritize all `Running` experiments first, even if it separates them from other experiments with non-empty states.
Before:
```
$ dvc exp show
───────────────────────────────────────────────────────────────────────────────────────>
Experiment                   Created        State     Executor    train.step.loss   tr>
───────────────────────────────────────────────────────────────────────────────────────>
workspace                    -              -         -                         -     >
small                        Apr 11, 2023   -         -                   0.25993     >
├── 492d213 …
```
> exp: show active experiments first

- dvc/commands/add.py
- dvc/commands/get.py
- dvc/commands/get_url.py
- dvc/commands/imp_url.py
- dvc/exceptions.py
- dvc/repo/add.py
- dvc/repo/get.py
- dvc/repo/get_url.py
- dvc/repo/imp_url.py
- dvc/stage/__init__.py
- dvc/utils/__init__.py
- tests/func/test_add.py
- tests/func/test_get.py
- tests/func/test_get_url.py
- tests/func/test_import_url.py
- tests/unit/command/test_add.py
- tests/unit/command/test_get.py
- tests/unit/command/test_get_url.py
- tests/unit/command/test_imp_url.py
Closes #5387
Example:
```sh
❯ python -m dvc get https://github.com/iterative/dvc README.rst -o test.rst
❯ python -m dvc get https://github.com/iterative/dvc README.rst -o test.rst
ERROR: failed to get 'README.rst' from 'https://github.com/iterative/dvc' - The file 'test.rst' already exists locally. 
To override it, re-run with '--force'.
❯ python -m dvc get https://github.com/iterative/dvc README.rst -o test.rst --force
```
> Fix: Prettifying unexpected error on FileExists for get/get-url/imp-url/add and introducing --force

- dvc/commands/experiments/push.py
Rich by default uses linebreaks rather than soft-wrap like `builtins.print()` which breaks link in some terminals (like VSCode).
> exp push: soft wrap link so that the URL does not break

- dvc/info.py
This is not used anywhere outside so should be private like the rest. Likely a leftover from the past.
> info: get_fs_type -> _get_fs_type

- dvc/api/__init__.py
- dvc/api/experiments.py
- dvc/api/scm.py
- dvc/compare.py
- dvc/repo/experiments/show.py
- dvc/ui/table.py
- tests/func/api/test_experiments.py
- tests/func/api/test_scm.py
Closes #8775
Closes #7167
---
```py
import pandas as pd
from dvc.api import exp_show
df = pd.DataFrame(exp_show())
```
```
Experiment        rev            typ       Created parent  ...                       data/train_data                  models/model.pkl                 src/data_split.py                   src/evaluate.py                      src/train.py
0              workspace       baseline          None         ...  c6b5cd86cb58b6f5a2ce4d4a95996bb4.dir  cbc3f65deeb3e17cbc50e572da003f8c  e25f97724df2d2dfdfd05e228b788a58  e2d5d64f6064e95b7661b239b8b20626  ef9d70ee318c6b345ba974af4d2af4e4
1                   main       baseline  Apr 03, 2023         ...  c6b5cd86cb58b6f5a2ce4d4a95996bb4.dir  cbc3f65deeb3e17cbc50e572da003f8c  e25f97724df2d2dfdfd05e228b788a58 …
```
> api: Add `exp_show`.

- .github/workflows/tests.yaml
Trying to see if that will help with encoding error on windows with python 3.11
Temp workaround for #9413
> gha: try setting PYTHONUTF8

- dvc/repo/metrics/show.py
- dvc/utils/diff.py
- tests/func/metrics/test_diff.py
- tests/func/params/test_diff.py
> metrics: support strings

- dvc/commands/data.py
- dvc/repo/data.py
- tests/func/test_data_status.py
- tests/unit/command/test_data_status.py
Fixes https://github.com/iterative/dvc/issues/9410.
Needs a docs PR.
Before this PR:
```
$ dvc data status --help
usage: dvc data status [-h] [-q | -v] [--json] [--granular] [--unchanged]
[--untracked-files [{no,all}]] [--remote-refresh]
...
options:
...
--remote-refresh      Refresh remote index.
```
After this PR:
```
$ dvc data status --help
usage: dvc data status [-h] [-q | -v] [--json] [--granular] [--unchanged]
[--untracked-files [{no,all}]] [--not-in-remote]
[--no-remote-refresh]
...
options:
...
--not-in-remote       Show files not in remote.
--no-remote-refresh   Use cached remote index (don't check remote).
```
> data status: exclude remote status by default

- dvc/cli/__init__.py
- dvc/repo/__init__.py
- dvc/repo/get.py
- dvc/repo/open_repo.py
- tests/conftest.py
- tests/func/test_data_cloud.py
- tests/func/test_external_repo.py
- tests/unit/repo/test_open_repo.py
Consolidating all repo-opening in one place, so we can improve it in one place and not have `external_repo` running in the wild.
In general, no one should be using `external_repo` directly.
This change helped identify `dvc get` using `external_repo` directly and so having a different behaviour with local repos from the one in `dvc import`. And also brought attention that `dvc get` doesn't have to set any cache dirs or link types, because `dvcfs` is downloading directly from the cache/remote with no `fetch`ing and so no linking involved anymore.
> repo: consolidate Repo.open logic

- dvc/dependency/repo.py
- dvc/repo/open_repo.py
- tests/unit/stage/test_stage.py
> import: don't forget to set cache.dir

- tests/func/test_import.py
Followup for https://github.com/iterative/dvc/pull/9415
> tests: import: check that dvcfs is using main repo's cache

- dvc/testing/benchmarks/fixtures.py
Allows git `refs/...` ref names containing slashes to be used in `--dvc-revs` (useful for testing PR refs)
> testing.benchmarks: sanitize venv names containing slashes

- dvc/repo/reproduce.py
- tests/func/test_repro_multistage.py
- tests/func/test_run_cache.py
- reproduce: Update pull to also pull run cache.
- reproduce: Update pull to also pull changed stages.
Closes #4742 
Point 1 in https://github.com/iterative/dvc/pull/9375#issuecomment-1529825295
> repro: pull all missing files

- dvc/repo/reproduce.py
- dvc/stage/__init__.py
- tests/func/test_run_cache.py
Per https://github.com/iterative/dvc/pull/9395#issuecomment-1541235930
> repro: Move pull logic to inside Stage.

- dvc/commands/gc.py
- dvc/repo/gc.py
- tests/unit/command/test_gc.py
> gc: disallow --remote without other flags

- dvc/commands/repro.py
- dvc/stage/__init__.py
- dvc/stage/run.py
- tests/func/test_repro_multistage.py
- tests/unit/command/test_repro.py
Point 2 in https://github.com/iterative/dvc/pull/9375#issuecomment-1531683194
---
Requires #9434
> repro: Add `--allow-missing`

- .github/workflows/packages.yaml
See https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers.
> packaging: use PyPI trusted publishers

- dvc/testing/benchmarks/fixtures.py
> testing: Lazy import `pytest_virtualenv`

- dvc/repo/experiments/push.py
- tests/func/experiments/test_remote.py
> exp push: Handle rev arg as list.

- dvc/repo/experiments/ls.py
- dvc/repo/experiments/pull.py
- dvc/repo/experiments/remove.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_remote.py
- tests/func/experiments/test_remove.py
> exp: Fix --rev args for ls pull and remove.

- dvc/commands/stage.py
- dvc/repo/stage.py
- tests/unit/command/test_stage.py
Part of #5846.
Will backport and document this for 2.0, will deprecate `dvc run` separately.
> stage add: introduce --run option

- dvc/main.py
You can import it using:
```python
from dvc.cli import main
main(...)
```
> remove `dvc.main.main` alias

- dvc/commands/experiments/run.py
- dvc/commands/repro.py
- tests/func/test_repro.py
> exp run / repro: Drop --metrics.

- dvc/repo/experiments/__init__.py
- dvc/repo/experiments/brancher.py
- dvc/repo/experiments/exceptions.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/queue/base.py
- dvc/repo/experiments/queue/celery.py
- dvc/repo/experiments/queue/tempdir.py
- dvc/repo/experiments/queue/workspace.py
- dvc/repo/plots/__init__.py
Will close #9369
- Adds support for queued exp names in `dvc plots diff` (exp name can be a queued, actively running, or failed task)
- Actively running exps will return the live values from the temp workspace
> plots diff: collect live plots for queued experiments

- dvc/commands/add.py
- dvc/exceptions.py
- dvc/repo/add.py
- dvc/stage/__init__.py
- dvc/utils/collections.py
- tests/func/test_add.py
- tests/func/test_checkout.py
- tests/func/test_commit.py
- tests/func/test_move.py
- tests/func/test_stage_load.py
- tests/func/test_status.py
- tests/unit/command/test_add.py
- tests/unit/fs/test_data.py
- tests/unit/fs/test_dvc.py
- tests/unit/utils/test_collections.py
- Remove `add --recursive`
- Rename `fname` to `file` in `Repo.add`. This was probably named this way because `file` was a builtin function in Python 2. 
- Adds support for `os.PathLike[bytes | str]` and `bytes` paths as targets.
- Also supports `Iterator` of `os.PathLike[bytes | str] | str | bytes` paths. Previously, it only supported list.
- Improve progress bar.
Related https://github.com/iterative/dvc/issues/7093
> add: remove --recursive, rename `fname` to `file`

- pyproject.toml
Temporary(?) fix for CI on windows with py >=3.9. 
```
2023-06-04T17:07:33.7789701Z tests\unit\repo\experiments\conftest.py:94: in session_worker
2023-06-04T17:07:33.7789796Z     with _thread_worker(
2023-06-04T17:07:33.7790012Z tests\unit\repo\experiments\conftest.py:61: in _thread_worker
2023-06-04T17:07:33.7790251Z     from celery.contrib.testing import worker
2023-06-04T17:07:33.7790893Z C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\celery\contrib\testing\worker.py:7: in <module>
2023-06-04T17:07:33.7791072Z     import celery.worker.consumer
2023-06-04T17:07:33.7791785Z C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\celery\worker\consumer\__init__.py:4: in <module>
2023-06-04T17:07:33.7792052Z     from .consumer import Consumer …
```
> deps: install tzdata for testing with celery

- dvc/dvcfile.py
- dvc/stage/utils.py
- tests/func/params/test_diff.py
- tests/func/params/test_show.py
- tests/func/test_repro.py
- tests/func/test_run_single_stage.py
- tests/unit/stage/test_stage.py
Part of https://github.com/iterative/dvc/issues/7093.
> remove support for reading and generating Dvcfile

- dvc/commands/add.py
- tests/func/test_add.py
- tests/unit/command/test_add.py
> add: deprecate --file

- dvc/commands/add.py
- dvc/repo/add.py
- tests/func/test_add.py
- tests/unit/command/test_add.py
- Follow up on https://github.com/iterative/dvc/pull/9522, renames jobs kwarg to remote_jobs to mirror CLI.
- Also moves validation logic to CLI.
> add: rename jobs to remote_jobs to mirror CLI; move validation to CLI

- dvc/__init__.py
- dvc/_build.py
- dvc/cli/__init__.py
- dvc/info.py
- dvc/updater.py
- dvc/utils/pkg.py
- scripts/build.py
- scripts/build_package.sh
- tests/unit/cli/test_main.py
PKG has to be specified in dvc/_build.py now, and can be imported using:
```python
from dvc import PKG
```
This is done to avoid importing from dvc/utils pkg which can be expensive, since we started logging PKG info in CLI main.
Also it's not an utility, so it is better that it remains at the top-level namespace. It's also a static information that never changes.
Note that we may have to fix the path for a few packages that we build, like conda/snap/chocolatey.
> dvc.utils.pkg: move PKG to top-level dvc

- dvc/cachemgr.py
- dvc/commands/add.py
- dvc/config_schema.py
- dvc/exceptions.py
- dvc/output.py
- dvc/repo/add.py
- dvc/stage/__init__.py
- dvc/stage/cache.py
- dvc/stage/utils.py
- dvc/testing/workspace_tests.py
- tests/func/test_add.py
- tests/func/test_gc.py
- tests/func/test_get.py
- tests/func/test_odb.py
- tests/func/test_remote.py
- tests/func/test_repo_index.py
- tests/func/test_run.py
- tests/unit/command/test_add.py
- tests/unit/stage/test_stage.py
- tests/unit/test_info.py
Fixes #9531
Docs https://github.com/iterative/dvc.org/pull/4574 Kudos @dberenbaum
> dvc: drop cached external outputs

- dvc/testing/benchmarks/cli/commands/test_exp_show.py
- dvc/testing/benchmarks/cli/commands/test_update.py
- dvc/testing/benchmarks/cli/stories/test_modify_data.py
Fixes https://github.com/iterative/dvc-bench/issues/461
> benchmarks: update tests for dvc 3.x

- dvc/api/experiments.py
- dvc/api/show.py
> api: show/exp: add config option

- dvc/repo/experiments/serialize.py
Quick fix for https://github.com/iterative/dvc/issues/9565
> exp show: quick fix for handling defaultdict in py<3.11.0

- tests/func/test_add.py
- tests/func/test_analytics.py
- tests/func/test_external_repo.py
- tests/func/test_remote.py
- tests/unit/command/test_machine.py
- tests/unit/fs/test_dvc.py
- tests/unit/repo/experiments/queue/test_remove.py
- tests/unit/repo/test_open_repo.py
- tests/unit/test_ignore.py
Had the "pleasure" of finding a mocker.patch leak into other tests and one of the suspicions is that mixing unittest.mock and mocker might be somehow related.
In any case, we should use mocker where possible anyway.
> tests: use mocker instead of unittest.mock where possible

- tests/unit/command/test_add.py
- tests/unit/command/test_data_sync.py
- tests/unit/command/test_diff.py
- tests/unit/command/test_experiments.py
- tests/unit/command/test_imp.py
- tests/unit/command/test_imp_url.py
Currently, these rely on the root of the repo being in the dvc repo.
Leftover from https://github.com/iterative/dvc/pull/9627
> tests: unit: explicitly ask for dvc repo

- dvc/commands/experiments/ls.py
- dvc/repo/experiments/ls.py
- tests/func/experiments/test_experiments.py
- tests/func/experiments/test_remote.py
- tests/func/experiments/test_save.py
- tests/unit/command/test_experiments.py
> exp list: fix ui for tags/branches

- dvc/commands/experiments/pull.py
- dvc/commands/experiments/push.py
- dvc/repo/experiments/pull.py
- dvc/repo/experiments/push.py
- tests/func/experiments/test_remote.py
- tests/unit/command/test_experiments.py
> Exp push/pull: update default to push/pull all from head rev

- dvc/output.py
- tests/func/repro/test_repro.py
Fixes #8757. Feel free to close and take a different approach. Trying to find a quick fix that will make non-cached external outputs work as expected.
> output: set remove to recursive=false

- dvc/commands/experiments/pull.py
- dvc/commands/experiments/push.py
Follow up to #9361. Updates help text to show `(HEAD by default)` in `--rev`:
```
--rev <commit>        Pull experiments derived from the specified `<commit>` as
baseline (HEAD by default).
```
> exp: push/pull --rev help text shows default val

- dvc/output.py
- tests/func/test_commit.py
Fixes issue where `exp run` would generate 3.0 `.dvc` and `dvc.lock` files even if legacy 2.x data dependencies were completely unchanged.
> output: preserve legacy hash_name on save() for unchanged data

- dvc/output.py
- tests/func/test_add.py
> output: check legacy hash name in output.add()

- dvc/fs/callbacks.py
- dvc/progress.py
- dvc/repo/checkout.py
Makes for a better ui, as users will no longer see `0%` for operations that don't have pre-determined total.
This is also more correct from arch perspective to use dvc's ui and dvc's `TqdmCallback` in dvc.
> checkout: use ui.progress

- dvc/repo/data.py
- tests/unit/command/test_data_status.py
With all fetch and checkout related things that we've done in the recent past, we now have all the mechanisms necessary to provide actual progress (no total, but still better than spinner) during `dvc data status` operations.
> data: status: use ui.progress instead of ui.status

- dvc/output.py
Relpath might not exist (e.g. on windows between different drives), we should just use path as is and not get too fancy with the ui, unless we want to constantly keep ValueError in mind when using relpath for ui needs all over the place.
These operations should use index, where we always have current directory and relative paths, so the ui will change accordingly anyway.
> output: use path instead of relpath

- dvc/dagascii.py
This PR is just additional docs for the dagascii.draw function. Specifically documents the return value type and it adds a doctest to illustrate what the function does.
I'm a big fan of text representations of graphs. So when I was browsing the code and saw this I got excited. But while reading the code I wondered: what does this graph look like? I went through the effort of constructing a small example and printed it for myself. Certainly a nifty way to visualize a DAG. I think it would be nice if the code was able to provide a gist of that output without requireing the user to construct an example, and I think adding  a doctest here provides that.
Not sure how maintainers feel about doctests -- I see the repo has some of them, but not too many. As I learn codebases I often need to …
> Add doctest for dagascii.draw

- pyproject.toml
Looks like flufl-lock switched to pdm in 8.0 which triggered a
```
pkg_resources.DistributionNotFound: The 'flufl.lock>=5' distribution was not found and is required by dvc
```
error in multiple scenarious. Can't put my finger on anything specific in flufl-lock yet, so will just limit its version for now.
Fixes https://github.com/iterative/dvc/issues/9654
> deps: limit flufl-lock to <8

- pyproject.toml
See https://github.com/PyCQA/bandit/pull/940.
Will not be needed when new version of bandit comes.
> bandit: add exclusion for dvc/repo/experiments/utils.py back

- dvc/repo/fetch.py
- dvc/repo/pull.py
Closes #9226
- fetch/pull will now warn and subsequently fail when trying to fetch a file with no version ID from a cloud-versioned remote (i.e. when the file was not previously pushed to the versioned remote)
```
$ dvc pull                                    ⏎
WARNING: Some files are missing cloud version information and will not be fetched from the remote:
azure://test-versioned/cats-dogs/data/train/cats/cat.1.jpg
azure://test-versioned/cats-dogs/data/train/cats/cat.10.jpg
ERROR: failed to pull data from the cloud - 2 files failed to download
```
> fetch: warn if cloud-versioned file has no version ID

- dvc/repo/graph.py
- dvc/repo/reproduce.py
- tests/func/repro/test_repro.py
- tests/unit/repo/test_graph.py
This PR closes https://github.com/iterative/dvc/issues/9367, and makes a few other changes:
- `--single-item` now runs in the order the target is provided, instead of the position in it's dag. So, if you provide `dvc repro stage1 stage2 --single-item`, `stage1` will run before `stage2` even if `stage2` comes before `stage1`. Because that's what you want most of the time.
(And I did not want to complicate the code too much.)
- `--downstream` stages will run in the order of the graph instead of running stages of each target with post-order traversal.
The order is also enforced in normal cases, not just in `--downstream` by traversing the graph in post order. Previously, we were removing duplicates manually. 
https://github.com/iterative/dvc/blob/36ec25ffd78a23bb718036419eb28062edee6177/dvc/r …
> repro: make stages run in order of the graph

- dvc/repo/experiments/executor/base.py
- dvc/repo/reproduce.py
- dvc/stage/utils.py
- tests/unit/repo/test_reproduce.py
- tests/unit/stage/test_utils.py
The logic is now moved to experiments, where it tracks all the stage related files itself. The `_get_stage_files()` has been modified to also return lockfile path, so that it can be staged, and has been moved to `stage/utils.py`, and out of `reproduce.py`.
Fixes #9688.
> repro: do not autostage stage files

- dvc/api/data.py
- dvc/fs/dvc.py
- dvc/repo/__init__.py
- dvc/repo/open_repo.py
- tests/func/api/test_data.py
Fixes #9176
Previously, `dvc.api.get_url` just tried to get the default or specified remote and then manually generated a URL based on hard-coded `'md5'` dict lookup. As a result, it did not support per-output `remote:` settings and did not support cases where a legacy 2.x output would return `md5-dos2unix` info instead of `md5`.
- `DVCFileSystem.info()` now returns a properly generated `dvc_info['remote_url']` field for DVC outs that gets populated using the actual remote storage for the given data index entry (meaning per-output `remote:` is used when set, and default or `--remote` flag otherwise)
- `api.get_url` and `dvc get --show-url` now use the `remote_url` field from `dvcfs.info()`
cli:
```shell
$ dvc …
```
> api.get_url: use index storage for getting remote URL

- dvc/repo/reproduce.py
On top of #9691.
Looking at the docs, it seems `--pipeline` should reproduce from the start of the pipeline, and ignore `--downstream` altogether.
There is also a bug here, when both are combined, `repro` runs the leaf nodes (stages that no one depend on).
> repro:  ignore --downstream if used together with --pipeline

- dvc/repo/__init__.py
So that different major dvc versions don't use the same cache path.
Would be nice to also take creation time into account, but it is not universally exposed yet (only for macos it is as simple as os.stat(path).st_birthtime, so might add it there later).
> repo: site_cache_dir: take major version into account

- README.rst
We no longer attach bin packages to github releases, so old link is completely misleading.
Fixes #9700
> readme: point to dvc.org for packages

- dvc/api/data.py
- dvc/fs/dvc.py
- dvc/repo/__init__.py
- dvc/repo/open_repo.py
> repo: add helper method for doing data index lookup in subrepos

- dvc/parsing/__init__.py
- dvc/parsing/context.py
- dvc/parsing/interpolate.py
Loading/Reloading config in the middle makes parsing slow. We should inject the config, as it is a static thing.
> parsing: pass config instead of loading every time

- dvc/render/match.py
Fixes #9441.
Note that we do merge props, and use that for all revision. So you may see a warning for each revisions.
Example output:
```console
$ dvc plots diff
WARNING: In 'workspace', could not find provided field ('accss') in data fields ('step, acc').                                                                                                                       
WARNING: In 'HEAD', could not find provided field ('accss') in data fields ('step, acc').
file:///home/saugat/projects/iterative/vscode-dvc-demo/dvc_plots/index.html
```
> plots: log failures during datapoint conversions

- dvc/commands/repro.py
- dvc/exceptions.py
- dvc/repo/reproduce.py
- tests/func/repro/test_repro.py
- tests/unit/command/test_repro.py
- tests/unit/repo/test_reproduce.py
`-k`/`--keep-going` will skip all dependents of a stage if it fails. It'll still try to reproduce the other dependencies of the pending targets, before it exits with a non-zero status.
`--ignore-errors` will treat any error during stage execution as a success, and will continue executing other dependencies as if it succeeded. Exits with 0 even on failure.
Also fixes:
* --force-downstream used to force everything even if one upstream nodes changed. This used to work when we supported a single targets, but there could be independent pipelines, so  we should not force everything if any node changes. Now we'll force reproduce the stage only if one of its dependency changed upstream or it's upstream node was also forced.
* Makes `--downstream` more correct, in relation to `--allow-missing` and …
> repro: introduce --keep-going/--ignore to continue on error

- dvc/commands/get.py
- dvc/commands/imp.py
- dvc/commands/ls/__init__.py
- dvc/config.py
- dvc/dependency/repo.py
- dvc/repo/get.py
- dvc/repo/imp.py
- dvc/repo/ls.py
- tests/unit/command/ls/test_ls.py
- tests/unit/command/test_get.py
- tests/unit/command/test_imp.py
Adds support for `--config` to all three commands. For `ls` and `get`, it is a purely runtime option that will merge the config you provide with target repo's configs (similar to how .dvc/config.local works). E.g.
```
$ cat myconfig
[remote "myremote"]
access_key_id = 12345
secret_access_key = 98765
$ dvc get https://github.com/efiop/mydataregistry recent-grads.csv --config myconfig
```
In case of `dvc import`, the semantics are the same, but the value is also recorded in the resulting dvcfile. E.g.
```
$ dvc import https://github.com/efiop/mydataregistry recent-grads.csv --config myconfig
...
$ cat recent-grads.csv.dvc
md5: 85c86eeb3afa6d1f7d11beedc644d28e
frozen: true
deps:
- path: recent-grads.csv
repo:
url: https://github.com/efiop/mydataregistry
config: myconfig
rev_lock: …
```
> ls/import/get: introduce --config

- dvc/exceptions.py
- tests/func/artifacts/test_artifacts.py
Fix for https://github.com/iterative/studio/issues/6897 (internal ticket).
```python
InvalidArgumentError: Can't use 'bad_name' as artifact name (ID). You can use letters and numbers, and use '-' as separator (but not at the start or end).
File "dvc/repo/artifacts.py", line 65, in read
check_name_format(name)
File "dvc/repo/artifacts.py", line 32, in check_name_format
raise InvalidArgumentError(
AttributeError: 'InvalidArgumentError' object has no attribute 'msg'
```
Bad name was causing a failure an unexpected `AttributeError` and breaking the parser in Studio.
Separate followup question to discuss is why we allow these names silently. Tbh, I think it's better for us:
- to fail fast here cc @daavoo @dberenbaum @aguschin what was the reason behind this decision? 
- also why don't we allow …
> Add parent ctr init call in InvalidArgumentError

- dvc/dependency/base.py
- dvc/fs/__init__.py
- dvc/repo/get.py
- dvc/repo/get_url.py
- tests/func/repro/test_repro.py
Fixes https://github.com/iterative/dvc/issues/8964
See https://github.com/iterative/dvc-objects/pull/214#issuecomment-1646384722
- Skips unneeded fsspec overhead in fs.expand_path (since we already do any needed recursive dir expansion via find())
- Skips unwanted fsspec glob behavior (see #8964) since we already deal with raw paths and not glob patterns
- Makes all import/get file downloads atomic
> fs.download: prefer generic.copy over fsspec fs.get()

- dvc/cachemgr.py
- dvc/data_cloud.py
- dvc/fs/__init__.py
- dvc/output.py
- tests/unit/fs/test_fs.py
- tests/unit/fs/test_tree.py
- tests/unit/remote/test_remote.py
- tests/unit/remote/test_webdav.py
Config is a more immutable thing and using `repo` is confusing and might be error prone in the bigger picture.
Related/pre-requisite to #9754
> fs: get_cloud_fs: accept config instead of repo

- dvc/output.py
- tests/unit/output/test_local.py
This is not very useful overall, but also results in a ValueError from relpath on windows if your repo and output are on different drives.
> out: str: don't try to relpath paths outside of the repo

- dvc/api/data.py
- dvc/config.py
- dvc/repo/__init__.py
Without `remote` specified, it will merge provided config with a default remote's config.
If `remote` is specified, it will set that as default and will merge or create a config for remote with that name.
If `config` is specified, `remote` and `remote_config` will be applied on top.
Example:
```
remote_config = {
"access_key_id": "mykey",
"secret_access_key": "mysecretkey",
"session_token": "mytoken",
}
with dvc.api.open("data", remote_config=remote_config) as fobj:
...
```
Part of #9656
> api: open/read: introduce remote_config

- dvc/config.py
- dvc/exceptions.py
- dvc/repo/__init__.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/graph.py
- dvc/repo/init.py
- dvc/repo/stage.py
- dvc/stage/utils.py
- dvc/utils/__init__.py
- tests/func/test_stage.py
- tests/unit/utils/test_utils.py
On windows it will get resolved to a UNC path, which is very error prone.
We've been misusing realpath in some repo-related places that triggered the need to use it in other places.
> dvc: don't use realpath where not needed

- dvc/cli/utils.py
- dvc/commands/get.py
- dvc/commands/imp.py
- dvc/commands/ls/__init__.py
- dvc/dependency/repo.py
- dvc/repo/get.py
- dvc/repo/imp.py
- dvc/repo/ls.py
- tests/unit/command/ls/test_ls.py
- tests/unit/command/test_get.py
- tests/unit/command/test_imp.py
Similar to how it is used in api. `--remote` is used to specify a new default remote to set, while `--remote-config` can amend that (or just old default if `--remote` not specified). Example:
```
dvc get URL path --remote-config "access_key_id=mykey" "secret_access_key=mysecretkey"
```
Fixes https://github.com/iterative/dvc/issues/9656
> ls/import/get: introduce --remote and --remote-config

- .pre-commit-config.yaml
Let's enable autofix in ruff as an experiment.
If it breaks code too often or gets too aggressive, we can rollback or set `unfixable` in the pyproject.toml file as follows:
```toml
[tool.ruff]
unfixable = ["B", "SIM", "TRY", "RUF"]
```
> ruff: enable autofix

- tests/func/repro/test_repro.py
> fix flaky test for repro --keep-going and --ignore

- dvc/repo/fetch.py
> fetch: add basic onerror

- dvc/config.py
- dvc/config_schema.py
- tests/func/test_config.py
- tests/unit/test_config.py
> config: resolve: handle ~ home dir

- dvc/config.py
- dvc/repo/__init__.py
This used to work like so but by accident, when we didn't reload config at all when collecting other revisions.
Regression from https://github.com/iterative/dvc/pull/9758
Testing is a bit tricky, but easy to run into when using (e.g. `dvc fetch --all-commits` when you have an azure remote that you need to set credentials for).
> config: use local config from local_dvc_dir

- dvc/__pyinstaller/hook-dvc.py
Likely with removal of dvc-machine pyinstaller stopped picking up dvc_ssh automatically, so we need to declare it explicitly just like the rest of plugins.
> pyinstaller: declare dvc_ssh as hidden import

- dvc/commands/ls/__init__.py
- dvc/commands/ls_url.py
- dvc/repo/ls.py
- dvc/repo/ls_url.py
- tests/func/test_ls.py
I really need it only for studio right now, but this is really nice to have in a daily life as well.
Caveat: we just throw whatever we have in `size` field, which means that for `dvcfs`,  you might get a disk-usage size for a directory instead of its physical size that usually is completely useless (see your ls -la). I think that's acceptable for now, but we will need `dvc du` for `du` purposes in the future.
E.g.
```
$ dvc ls-url . --size
108    Metadata-and-Results.dvc
97     AudioMP3.dvc
97     AudioWAV.dvc
12181  README.md
54     .gitignore
168    .gitattributes
99     VideoFlash.dvc
312    LICENSE.txt
139    .dvcignore
96     AudioMP3
96     Asset
192    .dvc
64     Metadata-and-Results
64     AudioWAV
192    Scripts
64     VideoFlash
384    .git
96     .vscode
```
```
$ dvc list . …
```
> ls/ls-url: introduce --size

- dvc/commands/ls/__init__.py
- pyproject.toml
Currently we get odd formatting like
```
456    .devcontainer.json
139    .dvcignore
61.0   .gitattributes
96.0   .github
7.00   .gitignore
5.76k  README.md
160    data
1.84k  dvc.lock
519    dvc.yaml
4.00   foo
96.0   models
96.0   notebooks
225    params.yaml
46.0   requirements.txt
128    results
160    src
```
(notice stuff like 46.0)
and there doesn't seem to be a simple way to fix that in tqdm, in addition to the general feeling that we are abusing tqdm's util for this.
So let's just use `humanize`, which gets us a more pleasing result:
```
456B  .devcontainer.json
139B  .dvcignore
61B   .gitattributes
96B   .github
7B    .gitignore
5.8K  README.md
160B  data
1.8K  dvc.lock
519B  dvc.yaml
4B    foo
96B   models
96B   notebooks
225B  params.yaml
46B   requirements.txt
128B  results …
```
> ls/ls-url: use humanize.naturalsize instead of tqdm

- dvc/repo/cache.py
A bit more useful info for a (temporary) hidden command.
> cache: check-missing: add type, oid name and oid

- dvc/testing/api_tests.py
get_file does not support PathLike objects. fsspec does not support them in get_file.
See https://github.com/fsspec/filesystem_spec/issues/896. Fixes test failures in dvc-webhdfs and dvc-hdfs.
> tests: dvcfs: use fspath while testing

- dvc/testing/benchmarks/cli/stories/test_modify_data.py
Better naming for some benchmarks and fixes issues due to duplicate naming that cause plots like this:
> Rename partial add/remove benchmarks

- dvc/dependency/base.py
- dvc/testing/workspace_tests.py
Fixes issue noted in slack
```
dvc import-url --version-aware ...
dvc update
```
would result in a modified `path:` for the `deps` entry (after the update, the path would contained a versioned path and no `version_id` field instead of an unversioned path + `version_id` field)
> update: preserve `def_path` for version-aware import update

- dvc/repo/experiments/queue/base.py
- tests/func/experiments/test_experiments.py
-----
Required for https://github.com/iterative/dvclive/pull/688 / https://github.com/iterative/vscode-dvc/pull/4579 / https://github.com/iterative/vscode-dvc/issues/4528
A detailed description is at https://github.com/iterative/dvclive/pull/688. The reason for this change is shown [here](https://github.com/iterative/dvclive/pull/688#discussion_r1306759893).
https://github.com/iterative/dvc/assets/37993418/d06de6dc-8b06-48b8-9632-f9e87f0df53d
> Add DVC_ROOT env var into queued experiment runs

- dvc/cachemgr.py
- dvc/repo/__init__.py
If user uses some custom cache location, there is really no reason for us to try to gitignore it, as we have no idea what he is planning to do with that and overall it often might be sign of this being misused. Maybe we could also have some warnings/errors, but that's out of scope for this PR.
Fixes https://github.com/iterative/studio/issues/7405
> repo: don't try to gitignore custom cache locations

- dvc/cli/utils.py
If value contains more `=`, this will currently error out with too many values to unpack.
Related #9886
> cli: utils: DictAction: limit split to 2 elements

- dvc/commands/get_url.py
- dvc/commands/imp_url.py
- dvc/commands/ls_url.py
- dvc/dependency/__init__.py
- dvc/output.py
- dvc/repo/get_url.py
- dvc/repo/ls_url.py
- dvc/testing/workspace_tests.py
- tests/func/test_import_url.py
- tests/unit/command/test_get_url.py
- tests/unit/command/test_imp_url.py
- tests/unit/command/test_ls_url.py
Useful when you want to set additional options for your url. E.g. `account_name` for azure, or `profile` for aws.
Considering that we already have `dvcfs` thing in API, I think it is time to embrace `fs` concept and document it.
Fixes #9886
> ls-url/get-url/import-url: introduce --fs-config

- dvc/commands/experiments/ls.py
- dvc/commands/experiments/remove.py
- dvc/commands/move.py
- dvc/commands/remove.py
Docs Issue: https://github.com/iterative/dvc.org/issues/4825
Fixes: #9901 
Alias `dvc mv` to have same functionality as `dvc move`
Alias `dvc rm` = `dvc remove`
Alias `dvc exp ls` = `dvc exp list`
Alias `dvc exp rm` = `dvc exp remove`
> move: Alias mv to move

- dvc/repo/experiments/executor/base.py
Fixes https://github.com/iterative/dvc/issues/9781
>  exp run: track files for skipped/run-cached stages

- dvc/repo/experiments/show.py
Checkpoint support was dropped in 3.x, `experiments.show` should now only return the first (tip) commit in a checkpoint exp
Fixes #9899
> exp show: drop internal legacy checkpoint support

- dvc/repo/experiments/queue/base.py
- dvc/stage/run.py
Related https://github.com/iterative/dvclive/issues/670
- Sets `DVC_ROOT` env var during stage execution regardless of whether pipeline is run with `dvc repro` or `dvc exp run` 
- `DVC_ROOT` always points to the main/parent DVC repo root. (For `dvc exp run`, it will not point to temp/queue executor tempdirs)
> stage.run: always set DVC_ROOT env var

- dvc/commands/checkout.py
- tests/unit/command/test_checkout.py
```console
$ git clone https://github.com/iterative/example-get-started-experiments
$ cd example-get-started-experiments
$ dvc fetch models/model.pkl
$ dvc checkout
A       models/model.pkl
ERROR: Checkout failed for following targets:
data/pool_data
data/train_data
data/test_data
model.tar.gz
models/model.pth
results/evaluate/plots/images
Is your cache up to date?
<https://error.dvc.org/missing-files>
```
```console
$ git clone https://github.com/iterative/example-get-started-experiments
$ cd example-get-started-experiments
$ dvc fetch models/model.pkl
$ dvc checkout --allow-missing
A       models/model.pkl
```
> checkout: Expose `--allow-missing` arg.

- dvc/repo/graph.py
> repo: use is_repo_import to check for imports in `outs_graph`

- dvc/commands/imp.py
- tests/unit/command/test_imp.py
I have also manually tested this:
```
$ dvc import https://github.com/iterative/dataset-registry use-cases/pool_data
$ dvc import https://github.com/iterative/dataset-registry use-cases/pool_data
$ dvc import https://github.com/iterative/dataset-registry use-cases/pool_data --force
```
> import: Expose `--force` flag

- dvc/dependency/param.py
- dvc/repo/metrics/show.py
- dvc/repo/params/show.py
- dvc/utils/serialize/__init__.py
- dvc/utils/serialize/_common.py
- dvc/utils/serialize/_json.py
- dvc/utils/serialize/_py.py
- dvc/utils/serialize/_toml.py
- dvc/utils/serialize/_yaml.py
See https://github.com/iterative/dvc.org/pull/4851#issuecomment-1713201448.
> params/metrics: cache remote files

- .github/workflows/build.yaml
https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers#using-trusted-publishing-with-github-actions
> Migrate from PyPI tokens to Trusted Publishers

- dvc/fs/dvc.py
Fixes #9896
`DVCFileSystem` can now be instantiated using a `fsspec`-compliant URL. 
Example:
```python
from fsspec.core import url_to_fs
fs, _ = url_to_fs("dvc::https://gitlab.com/repository/group/my-repo")
```
Not sure how to test this, feel free to give feedback on that.
PS: It unfortunately does not solve my original use case of loading a file using HuggingFace datasets, it seems that `datasets` expects the URL to be fully qualified like so: `dvc::https://gitlab.com/repository/group/my-repo/my-folder/my-file.json` but this fails because `DVCFileSystem` expects the URL to point to the root of an SCM repo. Not sure how to continue from here, according to you is it an issue with DVC or HuggingFace datasets?
> Fix Repo instantiation error when using fsspec chaining API

- dvc/repo/index.py
Will figure out a good (e2e?) test for external outs in a separate PR along with some fixes for `dvc status` and other commands.
This is mostly to fix it for studio, but will also fix it for new index based commands like `dvc diff/data status/etc`.
> index: don't load external outs

- pyproject.toml
see: https://github.com/pypa/setuptools_scm/issues/912
setuptools_scm 8.0.1 generates type hints that are only valid on python>=3.9, pinning this until the fix is released
> build: temporarily pin setuptools-scm

- dvc/cachemgr.py
- dvc/repo/index.py
Existing logic might result in weird fs cache location like `.dvc/cache/files/md5/fs`, while we really only want `.dvc/cache/fs`, since it is not an odb cache.
> index: fix fs cache location

- .github/workflows/build.yaml
https://github.com/pypa/gh-action-pypi-publish suggests separating building from publishing for security reasons.
>  try to separate building from publishing — this makes sure that any scripts maliciously injected into the build or test environment won't be able to elevate privileges while flying under the radar.
> ci: build: split publishing and building into separate jobs

- dvc/repo/experiments/executor/base.py
- tests/func/experiments/test_save.py
Right now, dvc silently ignores files from `include_untracked` if they are inside `.gitignore`. It would be better to either warn or force add them. Since these are files that are being explicitly included, I thought it would be more helpful to force add them. Some files like `dvc.yaml` are added implicitly by dvc, but in that case we probably want to force add anyway.
> exp: force add include_untracked paths

- dvc/repo/checkout.py
No reason to clear those, as they are informative for both us and our users.
> checkout: tweak messages and don't clear pbars

- dvc/repo/fetch.py
There is more we can do during the `Fetching` stage, but it will require additional tweaks, so just keeping it simple here.
Similar to https://github.com/iterative/dvc/pull/9974
> fetch: don't clear pbars

- dvc/repo/artifacts.py
Unfortunately, DVCLive was importing this function so I am bringing back the name for backwards compatibility.
See https://github.com/iterative/dvclive/pull/715
> artifacts: Bring back `name_is_compatible`.

- dvc/stage/cache.py
- tests/func/test_run_cache.py
Closes https://github.com/iterative/dvc/issues/9420
> run-cache: Load newest instead of first found in os.listdir.

- dvc/commands/data_sync.py
Currently only really affects `dvc pull` and `dvc fetch`, since they've migrated to using index, but `dvc status -c` and `dvc push` will error out (like they used to) about missing remote before they reach this new check.
Fixes #9733
> cli: data_sync: show warning about missing default remote

- dvc/commands/experiments/exec_run.py
- dvc/commands/experiments/save.py
- tests/unit/command/test_experiments.py
---
Closes #10004 
This PR matches the short option for `--message` across `exp run` &`exp save`.
Docs change at https://github.com/iterative/dvc.org/pull/4905
> `exp save`: use -m for --message short option

- dvc/commands/cache.py
- dvc/output.py
- dvc/repo/commit.py
Closes https://github.com/iterative/dvc/issues/9938
Related (workaround for): https://github.com/iterative/dvc/issues/9818
Docs PR https://github.com/iterative/dvc.org/pull/4910
Migration workflow now looks like:
```
$ dvc cache migrate --dvc-files --dry
3 files will be re-hashed and migrated to the DVC 3.0 cache location.
Entries in following DVC files will be migrated to the 3.0 format:
dir/bar.dvc
dir/dvc.yaml (dir/dvc.lock)
foo.dvc
$ dvc cache migrate --dvc-files
Migrated 3 files to DVC 3.0 cache location.
Updating DVC file 'foo.dvc'
Modifying stage 'baz' in 'dir/dvc.yaml'
Updating lock file 'dir/dvc.lock'
Updating DVC file 'dir/bar.dvc'
git add dir/dvc.yaml foo.dvc …
```
> cache migrate: add --dvc-files flag to migrate .dvc and dvc.lock files

- dvc/daemon.py
Not sure if this is the best approach to fix the issue, but currently we [do not seem to be sending analytics reports for mac since March](https://iterativeai.slack.com/archives/CB41NAL8H/p1697464559356029?thread_ts=1697200360.717249&cid=CB41NAL8H). I have tested and found that it seems to be some combination of forking and the `_popen` method used. Analytics get sent successfully if I either:
1. Drop all the forking logic, OR
2. Call `main` like it does for linux.
Here I dropped all the forking and conditions here and just use `_popen` directly. This successfully sends reports for me, and I'm not sure why we need forking here since it should happen in a separate, non-blocking process when using `_popen` (and dropping `.communicate()`). 
Not sure if I miss some context for why forking or …
> analytics: fix mac not sending reports

- dvc/render/converter/vega.py
- tests/unit/render/test_vega_converter.py
----
Related to https://github.com/iterative/dvc/issues/9940 / https://github.com/iterative/dvc/pull/9931
This PR removes a TODO + misleading comment from the `VegaConverter` class. The change is already fully tested.
For context:
There is code in Studio that duplicates this logic that I will be removing. I spent a good chunk of time going between the codebases because there is contradictory information lying around.
> `plots`: remove VegaConverter TODO and update misleading comment

- dvc/cli/__init__.py
Is useful for debugging for daemon, for example determining whether a process ran or not, or exited with some code.
> log exit code and pid on verbose-verbose logging

- dvc/cli/utils.py
Just makes it look nicer: `<name>=<value>` instead of `REMOTE_CONFIG`.
> cli: DictAction: set default metavar

- dvc/commands/experiments/apply.py
- dvc/repo/experiments/apply.py
- tests/unit/command/test_experiments.py
- reverts #9992 (see https://github.com/iterative/dvc/pull/9992#discussion_r1372465451)
- closes https://github.com/iterative/dvc.org/pull/4895
> exp apply: force dvc checkout by default

- dvc/daemon.py
- tests/unit/test_daemon.py
This PR:
1. always uses detached subprocess to run the daemon instead of a subprocess.
2. refactors to be able to run any command in the detached subprocess, not just limited to dvc commands.
> refactor: dvc.daemon

- dvc/daemon.py
- tests/func/test_daemon.py
This will be useful in log messages and while attaching debugger to the child process (and also to see the processes in task managers).
Also reduces chances of tests being flakey, and retries.
```log
2023-10-30 11:40:13,671 DEBUG: Spawned ['daemon', 'analytics', '/tmp/tmp9tj3fsb0', '-vv'] with pid 69118
```
> daemon: ipc to log pid from the child

- dvc/fs/dvc.py
- tests/unit/fs/test_dvc.py
Related to https://iterativeai.slack.com/archives/C03JS2V4MQU/p1697544594396579.
Assume a repo with an empty directory like:
```
$ tree
.
└── mydir
1 directory, 0 files
```
Before this PR, we get these results:
```python
>>> from dvc.api import DVCFileSystem
>>> fs = DVCFileSystem(".")
>>> fs.ls("mydir")
File "<stdin>", line 1, in <module>
File "/Users/dave/Code/dvc/dvc/fs/dvc.py", line 349, in ls
raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), path)
FileNotFoundError: [Errno 2] No such file or directory: 'mydir'
>>> fs.ls("missing")
[]
```
After this PR, we get these results:
```python
>>> from dvc.api import DVCFileSystem
>>> fs = DVCFileSystem(".")
>>> fs.ls("mydir")
[]
>>> fs.ls("missing")
File …
```
> dvcfs: ls: handle empty/missing dirs

- .pre-commit-config.yaml
- pyproject.toml
@iterative/dvc team decided to get rid of pylint because it's slow and also decided to replace other existing linters with ruff (including black/isort with ruff-format).
pylint suppression comments will come in the successive PRs and after that, I will make other changes.
> drop pylint from linter checks

- dvc/cli/__init__.py
- dvc/log.py
`__name__` looks something like `dvc.commands.diff`, but if we are already instantiating root logger with `dvc`, it adds up to create something like `dvc.dvc.commands.diff`.
We should be using a root logger here instead.
> fix name of the loggers used

- dvc/repo/__init__.py
This resulted in outdated `fetch` index cache and misc errors that are cleared by removing `site_cache_dir` manually. So because of the latter fact, also bumping `site_cache_dir` salt here to force refresh.
Likely related https://github.com/iterative/dvc/issues/10030
More tests coming separately.
> repo: drop_data_index: delete all first level nodes

- dvc/repo/index.py
- tests/func/test_repo_index.py
Add `param` files collection to index to implement:
```python
downloaded_cnt = repo.fetch(
...
types=["metrics", "plots", "params"],
...
)
```
It's not used anywhere atm and needed to potentially migrate Studio code to use Index.
> Add params collection to index

- dvc/testing/benchmarks/fixtures.py
- pyproject.toml
It does not look like it's being actively maintained. It is also failing on Python 3.12 due to `imp` module which has been removed in the latest version.
- https://github.com/man-group/pytest-plugins/pull/219
- https://github.com/man-group/pytest-plugins/issues/220
> remove pytest-virtualenv

- dvc/testing/tmp_dir.py
Path no longer  has `_from_parts()` in Python 3.12.
> tmp_dir: fix object initialization for Python 3.12

- pyproject.toml
We don't run benchmarks here, and benchmarking should always be a separate command than regular test run.
```python
/Users/user/Projects/dvc/.venv/lib/python3.12/site-packages/pytest_benchmark/logger.py:46: PytestBenchmarkWarning: Benchmarks are automatically disabled because xdist plugin is active.Benchmarks cannot be performed reliably in a parallelized environment.
warner(PytestBenchmarkWarning(text))
```
> pytest.ini_options: add --benchmark-skip to suppress pytest-benchmark warning with xdist

- dvc/dirs.py
- tests/unit/test_dirs.py
Minor fix in the way we handle config dirs. I think it's not documented and primarily used for test. We plan to start using it to isolate tests in Studio and isolate repos on workers.
------------
> fix(config): respect global config env variable

- dvc/repo/worktree.py
Previously we used recorded index which had stub entries for missing/failed outputs, but now we actually collect everything ourselves and those are missing.
> push: handle missing/failed version_aware file

- dvc/testing/benchmarks/cli/commands/test_fetch.py
- dvc/testing/benchmarks/cli/commands/test_pull.py
- dvc/testing/benchmarks/cli/stories/use_cases/test_sharing.py
`pull` is literally `fetch` + `checkout` and our main interest there is downloading, so let's just test `fetch` instead.
> bench: test fetch instead of pull

- dvc/testing/benchmarks/fixtures.py
Fixes https://github.com/iterative/dvc/issues/10118
> testing: import virtualenv lazily

- pyproject.toml
We should not register a pytest plugin automatically, as we may have fixtures that might override user's fixtures. Also, it might raise import errors as in https://github.com/iterative/dvc/issues/10118.
We can still use this as a plugin ourselves by setting the following in `conftest.py` file.
```python
pytest_plugins = ['dvc.testing.plugin']
```
> tests: do not setup pytest plugin entrypoint

- pyproject.toml
First release with unpinned fsspec version.
> deps: bump dvc-oss to >=2.22.0

- dvc/repo/brancher.py
- dvc/repo/experiments/pull.py
- dvc/repo/experiments/push.py
- dvc/repo/fetch.py
- dvc/repo/push.py
- tests/func/experiments/test_remote.py
Fixes https://github.com/iterative/dvc/issues/9768. Even for operations that don't use the workspace, like `dvc exp push`, dvc was logging errors if the workspace state was invalid, making it look like the command failed. This PR suppresses those errors if the workspace was not one of the included revs.
> exp: ignore workspace errors during push/pull

- dvc/testing/benchmarks/cli/commands/test_get.py
- dvc/testing/benchmarks/cli/commands/test_import.py
Sometimes seeing those error out in 2.x and early 3.x with:
```
ERROR: unexpected error - [Errno 95] no more link types left to try out: [Errno 95] Operation not supported
```
It seems like we've fixed it at some point, but I was not able to quickly find a link. Will update this if I do.
> bench: mark test_get/import as flaky

- dvc/cli/parser.py
- dvc/commands/du.py
- dvc/fs/dvc.py
- dvc/repo/__init__.py
- dvc/repo/du.py
- tests/func/test_du.py
- tests/unit/command/test_du.py
* By default shows du for every entry in path.
* -s|--summarize to show total.
* Sizes of directories themselves are considered 0.
* Humanized size by default.
* Sizes are as reported by fs/recorded in dvc files.
Example:
```
$ dvc du . data
285    data/__pycache__
826M   data/cats_dogs
11     data/.gitignore
826M   data/large
16.8M  data/tiny
18.4M  data/mnist
88.8M  data/small
1.73G  data
```
Note that we already have `--size` for `dvc ls` that just shows sizes.
> cli: introduce basic dvc du

- dvc/fs/dvc.py
- tests/func/repro/test_repro.py
We didn't care about this much because of our wrapper that makes all filesystems lazy no matter what, but having the base fs lazy is also useful and will be needed eventually.
> dvcfs: make repo creation lazy

- dvc/dependency/param.py
Closes https://github.com/iterative/dvc/issues/10177.
* By default, [`dpath.merge`](https://github.com/dpath-maintainers/dpath-python/blob/e0d412f9d3105623c8ea97159bcdfcc5415b0849/README.rst?plain=1#L279-L291) appends new elements to existing lists.
* Parsing YAML files with [reused anchors](https://yaml.org/spec/1.2.2/#alias-nodes) will create mutable objects (e.g. lists) passed by reference.
* Changes performed to e.g. lists inside `config` will also be applied to e.g. lists inside `ret` sharing the same anchor.
```python
from dpath import merge
ret = {}
config = {"list": [1, 2]}
for _ in range(4):
merge(ret, config)
print(ret)
```
```console
{'list': [1, 2]}
{'list': [1, 2, 1, 2]}
{'list': [1, 2, 1, 2, 1, 2, 1, 2]}
{'list': [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]}
``` …
> param: fix exponential memory allocation

- dvc/dependency/param.py
As @skshetry proposed on https://github.com/iterative/dvc/pull/10178#issuecomment-1858747531, deduplicating `key_paths` would be enough, because `dpath.search` with distinct keys will never output the same object twice.
> [!IMPORTANT]
> This patch seems to fix #10177 and some other creative variants I wrote, but I'm still afraid of unforeseen edge cases; not sure if this is a good idea.
> param: optimize fix for exponential memory allocation

- dvc/commands/gc.py
- dvc/exceptions.py
- dvc/repo/__init__.py
- dvc/repo/gc.py
- tests/func/test_gc.py
- tests/unit/command/test_gc.py
Closes https://github.com/iterative/dvc/issues/5037. Follows up on the great work started by @courentin in https://github.com/iterative/dvc/pull/5038. Also related to https://github.com/iterative/dvc/issues/9768#issuecomment-1845895172.
Example:
```sh
$ dvc gc -A --skip-failed
WARNING: This will remove all cache except items used in the workspace and all git commits of the current repo.
Are you sure you want to proceed? [y/n]: y
WARNING: Failed to collect 'workspace', skipping
WARNING: Failed to collect '964799719df645d5104c541410549f702d2a9b5d', skipping
WARNING: Failed to collect '9c24c7652c3eb28adaa2caafdff7dfdc21f1e449', skipping
WARNING: Failed to collect '616500724541bcd2f7f89584187b00f838ecf9a9', skipping
No unused 'repo' cache to remove.
No unused 'local' cache to remove.
No …
```
> gc: add --skip-failed

- dvc/repo/push.py
> ui: push: use blank pbar for the header

- dvc/repo/metrics/show.py
- dvc/repo/params/show.py
Not sure whether this is safe and what the ramifications are, but wanted to raise it and see if there is a good reason for locking here. Closes #10050.
> drop lock from params_show and metrics_show

- dvc/output.py
- dvc/repo/index.py
We use `out.files` to build index these days, making `out.odb` redundant. This also makes `storage.data` available for use.
Related #10194
> output: get rid of out.odb

- dvc/repo/index.py
- tests/func/test_repo_index.py
> index: fix storage for imports

- dvc/repo/plots/__init__.py
- dvc/schema.py
If you have a top-level plots with empty dict as follows:
```yaml
plots:
- {}
```
dvc would fail with traceback that looks like:
```python
StopIteration                             Traceback (most recent call last)
Cell In[3], line 1
----> 1 repo.index._plot_sources
File ~/Projects/dvc/.venv/lib/python3.12/site-packages/funcy/objects.py:25, in cached_property.__get__(self, instance, type)
23 if instance is None:
24     return self
---> 25 res = instance.__dict__[self.fget.__name__] = self.fget(instance)
26 return res
File ~/Projects/dvc/dvc/repo/index.py:448, in Index._plot_sources(self)
445 from dvc.repo.plots import _collect_pipeline_files
447 sources: List[str] = []
--> 448 for data in _collect_pipeline_files(self.repo, [], {}).values():
449     for plot_id, props in data.get("data", …
```
> top-level plot collections: fail on empty dict

- dvc/stage/__init__.py
- dvc/stage/run.py
- tests/func/repro/test_repro_pull.py
Fix for https://iterativeai.slack.com/archives/C03JS2V4MQU/p1702982308956539. 
`repro --pull` was pulling outputs but not dependencies (unless `--allow-missing` was also passed). This normally is enough, but in cases like `repro --pull --single-item`, the output from the previous stage is never pulled, causing the command to fail. This PR pulls dependencies whenever `--pull` is included.
> repro --pull: always pull deps

- dvc/commands/experiments/save.py
- dvc/repo/experiments/executor/base.py
- dvc/repo/experiments/save.py
- tests/func/experiments/test_save.py
- tests/unit/command/test_experiments.py
Fixes https://github.com/iterative/dvc/discussions/10236
For `dvc exp save`, adds `targets` and `--recursive`.
> exp save: add target arg

- dvc/repo/experiments/collect.py
- dvc/repo/experiments/queue/celery.py
Should close #9425
related: https://github.com/iterative/dvc/issues/9442
For sucessfully run queued experiments, `dvc exp show --json` will now include executor info if it's still available (i.e. logs haven't been removed with `dvc queue remove`)
```json
"experiments": [
{
"revs": [
{
"rev": "cb9a2cbf153a84f29d6c0b811e3b834054931459",
"name": "timid-pear",
"data": {
...
},
"deps": {
...
}
},
"outs": {
...
},
"meta": {}
},
"error": null,
"experiments": null
}
],
"executor": {
"state": "success",
"name": "dvc-task",
"local": {
"root": null,
"log": "/Users/pmrowla/git/example-get-started/.dvc/tmp/exps/run/af02dc1c0758c910a7c643194e5ba3f2687f463f/af02dc1c0758c910a7c643194e5ba3f2687f463f.out",
"pid": 16615, …
```
> exp show: output executor info for successful exps when available

- dvc/repo/__init__.py
Currently we join scm root_dir with subrepo root dir to have something that would represent that subrepo, but that directory might not exist in reality as we might be using a bare git repo and get such error:
```
File "/Users/.../.venv/lib/python3.11/site-packages/dvc/repo/__init__.py", line 653, in site_cache_dir
btime = self._btime or getattr(os.stat(root_dir), "st_birthtime", None)
^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/q1/fqyfkpr52qv8r43qn53xpxh40000gq/T/tmpcus9rcv7dvc-clone/pipelines/pdb_processing'
```
So we should just treat those as separate things.
Unfortunately adding a test for the error described above turned out to be rather not trivial, as we rarely end up with a bare repo these days, so I'll postpone that till …
> repo: site_cache_dir: separate subdir from root_dir

- dvc/repo/index.py
To avoid situations like
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 fs.download(cfg["dataset"]["dvc_config"]["path_in_repo"], "d.parquet")
File ~/.../.venv/lib/python3.11/site-packages/fsspec/spec.py:1546, in AbstractFileSystem.download(self, rpath, lpath, recursive, **kwargs)
1544 def download(self, rpath, lpath, recursive=False, **kwargs):
1545     """Alias of `AbstractFileSystem.get`."""
-> 1546     return self.get(rpath, lpath, recursive=recursive, **kwargs)
File ~/.../.venv/lib/python3.11/site-packages/fsspec/spec.py:983, in AbstractFileSystem.get(self, rpath, lpath, recursive, callback, maxdepth, **kwargs)
981 for lpath, rpath in …
```
> repo: index: don't set cache storage if there is no out.cache

- dvc/commands/data_sync.py
- dvc/commands/status.py
- dvc/repo/status.py
- tests/func/test_status.py
- tests/unit/command/test_status.py
Closes #10038. Adds `dvc status --no-updates`:
```
$ dvc status
data/data.xml.dvc:
changed deps:
update available:   get-started/data.xml (https://github.com/iterative/dataset-registry)
$ dvc status --no-updates
Data and pipelines are up to date.
```
> status: add option to skip imports

- dvc/repo/__init__.py
- tests/unit/repo/test_repo.py
---
Related to https://github.com/iterative/studio/issues/8848
> repo: add get_subrepo_relpath helper for Studio live experiments monorepo support

- pyproject.toml
- tests/func/test_data_cloud.py
- tests/func/test_get.py
- tests/func/test_ls.py
Since it's no longer being maintained. See https://github.com/TvoroG/pytest-lazy-fixture/issues/65.
> tests: remove pytest-lazy-fixture

- dvc/repo/plots/__init__.py
- tests/func/plots/test_show.py
- tests/integration/plots/test_plots.py
-----
This PR fixes a bug in the collection of plots definitions. The bug exists when there is a plot collected from a nested dvc.yaml that uses separate files for the x and y values.
e.g. 
```
- Error vs max_leaf_nodes:
template: simple
x: 
dvclive/plots/metrics/Max_Leaf_Nodes.tsv: Max_Leaf_Nodes
y:
dvclive/plots/metrics/Error.tsv: Error
```
in `{root}/pipelines/data-increment/dvc.yaml`
Previously the path to the x file was not updated to take into account the path to the dvc.yaml that it exists in.
For more context see [this thread](https://iterativeai.slack.com/archives/C01APS0FHDM/p1708601001649999).
> plots: support x-dict in nested dvc.yaml

- dvc/commands/dataset.py
- dvc/repo/datasets.py
- tests/unit/command/test_dataset.py
To be on parity with `dvc import`.
```console
dvc ds update --rev v1 dogs
Downgrading dogs (v2 -> v1)
git add dvc.lock
To enable auto staging, run:
dvc config core.autostage true
```
```console
$ dvc ds update --rev tune-hyperparams example-get-started
Updating example-get-started (df75c16ef -> a6d1c7a3f)
git add dvc.lock dvc.yaml
To enable auto staging, run:
dvc config core.autostage true
```
Regarding naming of the flag, we cannot use `--version`. I see that we are using `--rev` in `artifacts get`, so I did the same here.
> dataset: provide --rev to track a different dvcx dataset version or git rev

- dvc/testing/api_tests.py
`isolate` fixture don't run in plugin's tests.
So the tests will fail to run if you have `init.defaultBranch` something other than `master`.
> tests: use default branch for rev

- pyproject.toml
Changes in pytest==8.1.0 breaks `flaky` plugin.
See https://github.com/box/flaky/issues/198.
It's breaking the CI.
> limit pytest version to <8.1

- dvc/config_schema.py
- dvc/repo/experiments/executor/base.py
- tests/func/experiments/test_remote.py
As requested by https://github.com/iterative/dvc/issues/10137, we want a configuration parameter to auto-push the experiments once they are run. Auto-push means the experiments and artifacts will be sent to git and the DVC remote after each experiment succeeds.
This PR also introduces a default for the `git_remote` to `origin`
:warning: @mattseddon  In this PR I changed the DVC config (`.dvc/config`) to add the new field `exp.auto_push`. When I'm testing to run a demo project locally and look at my studio dashboard (from the web, not a branch), I have a warning
> experiments: auto push experiments 

- dvc/commands/studio.py
- dvc/repo/experiments/executor/base.py
- tests/unit/command/test_studio.py
Context: https://github.com/iterative/dvc/issues/10137
The `dvc studio login` command now sets the config so that every experiment is automatically pushed on `dvc exp run` and `dvc exp save`. 
I also added a few helping tips for the users to say that if the push is too long, they can cancel and launch it back later on. 
> `dvc studio login` automatically push experiments by default

- dvc/repo/experiments/executor/base.py
- tests/func/experiments/test_remote.py
Fixes `Handle case where remote doesn't exist` in #10137.
This raises a warning and disables auto push if remote validation fails. Without this PR, it fails early, which is also reasonable, but I think it's less desirable for this scenario. If I set up a new repo and login to Studio, I won't be able to run any experiments until I have a dvc and git remote configured or I disable auto push.
> handle auto push errors

- dvc/repo/plots/__init__.py
- tests/integration/plots/test_plots.py
Regression after https://github.com/iterative/dvc/pull/10320 that hits us in Studio parser in some repos (we are getting Sentry alerts).
I see also a few other potential issues / regressions - will add small PRs to address them as well.
-------------------
> fix(plots): handle empty directories

- pyproject.toml
fixes `AttrsInstance` import failing on older versions of attrs, fixed by https://github.com/python-attrs/attrs/issues/987
> add attrs explicit dependency

- dvc/repo/fetch.py
- tests/func/test_data_cloud.py
Fixes #8298.
Take an example where there is an output like:
```
outs:
- md5: d3b07384d113edec49eaa6238ad5ff00
size: 4
hash: md5
path: foo
remote: foo_remote
```
Previously, `dvc push/pull/fetch -r bar_remote` would push/pull/fetch output `foo` from `foo_remote`. With this PR, it skips output `foo`.
> sync: skip if remote doesn't match output remote

- dvc/output.py
`dvc add` command incorrectly raises a `DoesNotExistError` when a broken symlink exists in an output directory, and the target name is same as the directory's name.
eg: If `data` is an output, and the command is invoked as `dvc add data` (i.e. no virtual directory operations to perform).
The expected behavior is to raise a `FileNotFoundError`.
`DoesNotExistError` should only be raised if the output itself does not exist.
Related: https://github.com/iterative/dvc/issues/3717
> add: raise DoesNotExistError only if the output path does not exist

- dvc/repo/metrics/show.py
- dvc/repo/params/show.py
- dvc/utils/__init__.py
- tests/func/metrics/test_show.py
- tests/func/params/test_show.py
Closes https://github.com/iterative/dvc/issues/10018.
We have to be careful when expanding paths. This PR fall backs to assume it
as a file when either of `isdir` and `find` raises error due to some mishaps.
The consequence of this assumption happens when we try to read the file.
In that case, if the directory exists, and we happen to try to open it
as a file, dvc will raise `IsADirectoryError`, but that is handled correctly
and won't fail catastrophically like this did.
This is what I get now:
```console
$ dvc metrics show --json
DVC failed to load some metrics for following revisions: ''.
{
"": {
"data": {
"results/train/metrics.json": {
"error": {
"type": "DataIndexDirError",
"msg": "failed to load directory ('results', 'train')"
}
},
"results/evaluate/metrics.json": {
"data": { …
```
> params/metrics: do not fail during dir expansion

- dvc/commands/add.py
- dvc/commands/commit.py
- dvc/repo/add.py
- tests/unit/command/test_add.py
Adds `dvc add --no-relink` and `dvc commit --no-relink` as a way to speed up add, but at the potential cost of lots of copies and maybe having to relink later.
Related to:
- #9813
- #7607
- https://github.com/iterative/dvc-data/issues/274
> add option to not relink

- dvc/api/artifacts.py
- dvc/repo/artifacts.py
- tests/func/api/test_artifacts.py
- tests/func/artifacts/test_artifacts.py
Closes #10382.
This PR:
1) adds support for `artifacts_show()` for monorepos.
2) adds support for `dvc artifacts get` for monorepos.
3) Always returns the path from `artifacts_show()` as a git root relative path, instead of dvc repo root relative path (**breaking**)
4) Expects the `name` passed to `artifacts_show()` and `dvc artifacts get` to be a git root relative path (**breaking**)
Please review carefully, as I am not very familiar with Artifacts, and looks like we don't have enough tests. 😄
> artifacts: add support for monorepo

- dvc/config_schema.py
- pyproject.toml
see:
- https://github.com/iterative/dvc.org/pull/5229
- https://github.com/iterative/dvc-s3/pull/85
> dvc: s3: allow configuring anonymous access

- dvc/fs/__init__.py
I've significantly optimized LFS prefetching performance. With this change, `include` in `scmrepo.git.lfs.fetch()` is now a single-item list with either a Unix filename pattern like `<subdir>/**` or a file path. `scmrepo.git.lfs.fetch._collect_objects()` still enumerates all files in the repo with `fs.find("/")` (that's quite fast even with many files) but `scmrepo.git.lfs.fetch._filter_paths()` only matches those files against a single pattern.
Partially fixes https://github.com/iterative/scmrepo/issues/338.
/cc @shcheklein
> import/get: optimize LFS prefetching

- dvc/fs/__init__.py
- tests/func/test_download.py
I've fixed a bug related to passing literal/non-pattern path (parts) to the LFS prefetching function from `scmrepo` which would interpret them as Unix filename patterns and result in incorrect path filtering results. Now, the literal/non-path path (parts) are escaped.
See https://github.com/iterative/scmrepo/pull/355#discussion_r1589847222 for the preceding discussion.
/cc @shcheklein
> import/get: escape non-pattern LFS path parts

- dvc/repo/fetch.py
- dvc/repo/push.py
- tests/func/test_run_cache.py
Fixes #10440 
Since we now implicitly push / pull run cache we should probably be more resilient to errors and just ignore unsupported cache.
> fix(push/pull): don't fail on unsupported run cache

- dvc/stage/run.py
- adds check for fish version above 3.3.0
- adds --no-config to make fish shell work
- refactors warning message for fish users
- solves #1307
Co-authored-by: Alexey Stern stern.alexey@gmail.com
> fix fish shell support

- dvc/testing/benchmarks/fixtures.py
Fixes (hopefully) failing benchmarks.
If you run it locally with:
```bash
DVC_TEST=true python -m pytest --benchmark-group-by func --dvc-revs 3.10.0 --pyargs dvc.testing.benchmarks.cli.commands.test_plots::test_plots --dataset mnist
```
and then:
```
(.venv) √ pytest-14/dvc-project0 % /private/var/folders/8f/fbysfztx1mb953_gpwl477p80000gn/T/pytest-of-ivan/pytest-14/dvc-venv-3.10.00/bin/dvc plots diff HEAD
ERROR: unexpected error - cannot import name 'GIT_OBJ_COMMIT' from 'pygit2' (/private/var/folders/8f/fbysfztx1mb953_gpwl477p80000gn/T/pytest-of-ivan/pytest-14/dvc-venv-3.10.00/lib/python3.12/site-packages/pygit2/__init__.py)
```
It's all related to:
https://github.com/iterative/scmrepo/pull/359
> fix(benchmarks): force older pygit2 for older DVC versions

- dvc/commands/studio.py
This PR fixes a bug where the `config.studio.url` option was ignored. Closes #10424 
> Read studio hostname from config when not present on cli or env

- dvc/utils/studio.py
- pyproject.toml
The https://studio.iterative.ai is deprecated, and we switched to the new domain https://studio.dvc.ai.
The domain change is backwards compatible. The **older versions** of the `dvc` will still work. 🎉
> chore(studio): Update Studio URL to new domain

- pyproject.toml
Following https://github.com/fsspec/filesystem_spec/pull/1495 and https://github.com/iterative/dvc/pull/10280, I think dvc needs a lower bound on fsspec since it relies on `DEFAULT_CALLBACK` being exposed.
> set lower bound on fsspec

- dvc/stage/cache.py
Rough idea to debug why pushing run-cache is slow
> try force overwriting run cache entries on push

- dvc/dependency/repo.py
- tests/func/test_import.py
Fixes https://github.com/iterative/dvc/issues/10255. This is a partial reversion of https://github.com/iterative/dvc/pull/9246. I'm not sure this is the cleanest or best way to do it, but it solves the problem.
It builds the hashfile object and tries to checkout from that, falling back to download if it fails.
Note that the build step is still slow for 2.x imports.
> Reimport checkout

- dvc/dependency/repo.py
This should fix https://github.com/iterative/dvc/issues/10500
- When checkouting non-existent file the _checkout_file recursively calls os.stat on a symlinked file which destination doesn't exist. This causes a FileNotFoundError but it is not catched and it causes an unexpected error instead.
> dvc dependency repo: Catch FileNotFoundError

- dvc/output.py
- dvc/repo/__init__.py
- dvc/testing/benchmarks/cli/commands/test_add.py
- pyproject.toml
- tests/func/test_add.py
Upstream PR: https://github.com/iterative/dvc-data/pull/548
> deps: bump dvc-data to >=3.16.0

- dvc/dependency/base.py
- dvc/dependency/repo.py
- dvc/fs/__init__.py
- dvc/repo/artifacts.py
- tests/func/test_import.py
This saves the hash info from imports to the output state db so that we don't rehash imports. Without this PR, imported files were always hashed when the output was saved. Existing imported files were even hashed again when doing operations like `dvc import -f`.
This should improve the speed of all imports, and it also reverts the changes in #10388 that caused slowdowns in some scenarios. That previous PR wrongly assumed the slowdown occurred during download, when it actually slowed during `output.save()`. That PR happened to work in some scenarios because the workaround updated the state db.
> save import hash info to state

- dvc/fs/dvc.py
In case the filesystem is opened from a local repository, and if the file exists as a dvc tracked file, and also exists in a local workspace, DVCFileSystem.get should prefer the local file, similar to `get_file` method.
> dvcfilesystem.get: prefer downloading from repo.fs before dvc.fs

- dvc/output.py
When the `cache_type` is `hardlink`, we can simply hardlink the file from the workspace to the cache, and we don't need to relink back from the cache to the workspace.
| Name                                   | Time (in s)       |
|----------------------------------------|-------------------|
| test_add_hardlink-add[hardlink-relink] |    17.5393 (1.0)  |
| test_add_hardlink-add[main]            |    32.9904 (1.88) |
Note that this is a bit unsafe, because a failure in the middle of `dvc add` may end up in a situation where the file has been hardlinked to the cache, but we have not protected them yet to make it read-only. Modification of these files in the workspace might corrupt cache (since they are hardlinked). But this is what we were doing before #10513, and there is always a chance …
> add/commit: use hardlink to transfer files to the cache when `cache.type` is hardlink and on relink mode

- dvc/commands/ls/__init__.py
- dvc/repo/ls.py
- tests/func/test_ls.py
This feature would be useful for a project I'm working on that uses DVC as a dependency.
> Add option to show MD5 checksums in `dvc ls`

- dvc/commands/ls/__init__.py
- dvc/commands/ls/ls_colors.py
- dvc/repo/ls.py
- dvc/ui/__init__.py
- dvc/ui/table.py
- tests/func/test_ls.py
- tests/unit/command/ls/test_ls.py
```console
$ dvc ls https://github.com/iterative/dataset-registry -TL2
.
├── README.md
├── blog
│   ├── .gitignore
│   └── cats-dogs
├── dvc-course
│   ├── .gitignore
│   └── hymenoptera_data
├── get-started
│   ├── .gitignore
│   └── data.xml
├── github-issues
│   ├── .gitignore
│   └── dataset.parquet
├── images
│   ├── .gitignore
│   ├── dvc-logo-outlines.png
│   ├── owl_sticker.png
│   └── owl_sticker.svg
├── tutorials
│   ├── nlp
│   └── versioning
├── use-cases
│   ├── .gitignore
│   ├── cats-dogs
│   └── pool_data
└── workshop
├── .gitignore
├── README.md
├── dvc_discord_channel.csv
└── satellite-data
```
```console
$ dvc ls https://github.com/iterative/dataset-registry -RL2
README.md
blog/.gitignore
blog/cats-dogs
blog/cats-dogs.dvc
dvc-course/.gitignore …
```
> ls: implement --tree to show as a tree and --level to limit depth for recursion

- .pre-commit-hooks.yaml
- dvc/repo/install.py
The `pre-commit` package recommends against using mutable references such as `main`, as the version of the package pulled in the hook (in this case `dvc`), does not get updated after the first time `pre-commit` installs it. This PR addresses this by instead pinning the hooks to [`dvc` v3.56.0](https://github.com/iterative/dvc/releases/tag/3.56.0). This change is made with the goal of:
- removing the `pre-commit` warning, and
- adding the ability to automatically update the `dvc` version that `pre-commit` refers to when `dvc` receives a new release.
As a reference, [`ruff`](https://github.com/astral-sh/ruff), the python linter and formatter, keeps its pre-commit hooks in a [separate repository](https://github.com/astral-sh/ruff-pre-commit). This repository has its own pre-commit hooks that …
> Update `pre-commit` to use pinned version of `dvc` and correct stage names

- .gitignore
- dvc/version.py
- pyproject.toml
Fixes security issue https://github.com/advisories/GHSA-c33w-24p9-8m24.
> deps: bump configobj minver to 5.0.9

- .github/workflows/tests.yaml
Hopefully, this will fix windows lint failures. My guess is that dvc daemon is running in the background preventing `uv` to prune cache.
But this is just a guess. Setting this one does not hurt us. We'll know if this was really an issue. :)
> set DVC_NO_ANALYTICS on lint

- dvc/repo/experiments/remove.py
- tests/func/experiments/test_remove.py
This PR addresses issue [#10638](https://github.com/iterative/dvc/issues/10638), by providing a minimal code fix that makes the `--all-commits`(aka. `-A` flag) append to the existing `removed` list instead of replacing it with a new value. 
When `--queue` is used, it might already contain the names of experiments removed from the queue. In all other cases, the list should exist but be empty, so appending still makes the job correctly.
* [N/A] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.
> Fix #10638 : makes remove return correct list when used with both `--queue` and `-A` 

- dvc/commands/ls/__init__.py
- dvc/commands/ls_url.py
- dvc/repo/ls.py
- dvc/repo/ls_url.py
- dvc/testing/workspace_tests.py
- tests/func/test_ls.py
- tests/unit/command/test_ls_url.py
> ls-url: add support for `--tree`/`--level`

- dvc/fs/dvc.py
Add child progress bar to dvc fs to report directory import progress correctly.
Fixes #10677
> import: fix broken progressbar when importing folder

- pyproject.toml
Requires bumping `setuptools` to 77.0.0 or later.
See:
- [PEP 639](https://peps.python.org/pep-0639)
- [Writing pyproject.toml - license](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license)
> pyproject: update license to PEP 639 format

- dvc/commands/remote.py
- tests/func/test_remote.py
Fixes #10708
Hello, I'm new to DVC and this is my first contribution to this repo. Please feel free to make suggestions or edits of course. 
I'd also be more than happy to make a documentation PR but I first wanted to check you're happy with the formatting choice I have gone for to show the default remote, as that would affect the documentation. 
I have configured it so that the default remote is shown in a similar way to how `git branch` does it:
Thanks!
> remote: show default when run "dvc remote list"

- .github/workflows/build.yaml
- pyproject.toml
Uses `SETUPTOOLS_SCM_OVERRIDES_FOR_DVC` to omit the local version when uploading to Test PyPI. This is needed because (Test) PyPI does not support local version.
This requires bumping minimum version of `setuptools_scm` to `8.0.0`.
The envvar is documented here: https://setuptools-scm.readthedocs.io/en/latest/overrides/.
Also see:
https://github.com/pypa/setuptools-scm/issues/455#issuecomment-2791301186.
> ci(build): use envvar override to omit local version for Test PyPI upload

- tests/func/test_checkout.py
See https://github.com/iterative/dvc-data/pull/601 that fixed the issue. The test is based on reproduction steps from:
https://github.com/iterative/dvc/issues/4344#issuecomment-2822000925.
Related: #4344.
> tests: func test for #4344

- dvc/dependency/repo.py
- dvc/repo/open_repo.py
- tests/func/api/test_data.py
This is a proposed fix for #10608, the code here makes steps 9 and 10 described in the issue work.
**Summary:**
This change allows a user to access the dvc information in an environment that is disconnected from the original Git backend (e.g. in a deployed container, see #10608), by using something like:
```python
dvc.api.get_url(path,
repo,
config={"core": {"no_scm": True}}
)
```
**Description:**
Mainly, a call to `dvc/repo/open_repo.py:open_repo(url, *args, **kwargs)` may contain a parameter `config` in `**kwargs`. With this `config` a user might indicate they do not want to access the repo with Git support, by using `config={"core": {"no_scm": True}}`. 
During the execution of `dvc/repo/open_repo.py:open_repo()`, there is a call to a function …
> Forward args to _get_remote_config() and honour core/no_scm if present

- tests/unit/output/test_output.py
Clear logs before assertions so that logs from other tests do not interfere with the test. Some destructors may also run in between due to GC, so hopefully this will fix that issue too, or reduce the chances of it happening.
See
https://github.com/iterative/dvc/actions/runs/14873217814/job/41775314725#step:6:97.
```console
>       assert first(caplog.messages) == expected_message
E       assert 'RC: discarding all clients' == "Output 'path... 'stage.dvc'."
E
E         + RC: discarding all clients
E         - Output 'path'(stage: 'stage.dvc') is missing version info. Cache for it will not be collected. Use `dvc repro` to get your pipeline up to date.
E         - You can also use `dvc commit stage.dvc` to associate existing 'path' with stage: 'stage.dvc'.
```
Thank you for the contribution …
> tests: fix flaky test in test_get_used_objs

- .github/workflows/tests.yaml
It can already search and find these coverage files. On `v5`, they also deprecated the `file` option and renamed to `files`, which adds noisy warnings in CI.
> drop inputs passed to codecov-action

- pyproject.toml
To support `allow_anonymous_login` that was added in dvc-gs 3.0.2.
Related:
- https://github.com/iterative/dvc-gs/pull/115
- https://github.com/iterative/dvc/pull/10756
- https://github.com/iterative/dvc/issues/5797
> deps: bump minver version for dvc-gs to 3.0.2

- dvc/config.py
Fixes https://github.com/iterative/dvc/issues/6020
> fix: treated S3 configpath as a relpath

- dvc/dirs.py
- dvc/repo/__init__.py
- tests/unit/test_dirs.py
Fixes #10777
Currently: `Repo.site_cache_dir()` in `dvc/repo/__init__.py` selects first the configuration read in the config file, and if it does not exist it relies on `dirs.site_cache_dir()` to pick a value.
The documentation states that `DVC_DITE_CACHE_DIR` should override this configuration, therefore the order of priority for selecting the `site_cache_dir` is:
1. `DVC_SITE_CACHE_DIR`
2. `core.site_cache_dir`
3. `platformdirs` selection
For this, `dirs.site_cache_dir()` needs to know the three options.
This PR:
- enables `dirs.site_cache_dir()` to receive a configuration option so it can make the right choice between the three values;
- modifies `Repo.site_cache_dir()` to send `core.site_cache_dir` instead of picking itself; and
- enables tests for the proper return values.
----
Thank …
> (fix) `DVC_SITE_CACHE_DIR` environment variable should override `core.site_cache_dir`

- dvc/repo/data.py
- tests/func/test_data_status.py
In a freshly initialized Git repo with no commits, there is no `HEAD`, which caused `dvc data status` to skip showing committed changes.
We now provide empty `DataIndex` in place of Git's `HEAD` to `diff` and `coTests have been updated to cover this case.mpare`.
Tests have been updated to cover this case.
> fix(data status): show committed changes in a new Git repository

- dvc/cachemgr.py
Instead of using the default cache directory, use the the configured one. This helps with importing large datasets.
Fixes #10794
> cache: use configured cache directory for fs cache path

- dvc/repo/data.py
- tests/func/test_data_status.py
See #10792. That'd break --no-remote-refresh.
I need to figure out how to do it with batching.
> partially rollback batch remote checks

- dvc/lock.py
- dvc/repo/__init__.py
- dvc/repo/experiments/queue/celery.py
- dvc/utils/__init__.py
- tests/func/test_diff.py
- tests/unit/fs/test_dvcfs.py
- tests/unit/test_analytics.py
Communicates to OpenSSL that these function calls should be allowed in "secure" builds, since they do not function as a security layer for anything. This API was added to hashlib in Python 3.9, and so is available in all Python versions that dvc supports.
> hashing: Add usedforsecurity=False on hashlib calls

- dvc/repo/checkout.py
- dvc/repo/fetch.py
- dvc/repo/index.py
- dvc/repo/push.py
- tests/func/test_checkout.py
- tests/func/test_data_cloud.py
- tests/func/test_repo_index.py
Closes #8768.
Previous attempt: https://github.com/iterative/dvc/pull/9259
> fix(perf): only load a stage/.dvc file if the target is an address to that stage

- dvc/dvcfile.py
- dvc/output.py
- dvc/repo/commit.py
- dvc/stage/__init__.py
- tests/func/test_commit.py
- tests/unit/test_dvcfile.py
Fixes #10629.
Using reproducible script from #10629 description,
```bash
#! /bin/sh
cd "$(mktemp -d)"
git init -q
dvc init -q
echo 'stages:
stepA:
matrix:
x: [1,2,3,4,5,6,7]
y: [1,2,3,4,5,6,7]
z: [1,2,3,4,5,6,7]
cmd: echo "substep${item.x}-${item.y}-${item.z}" > data/substep${item.x}-${item.y}-${item.z}.txt
outs:
- data/substep${item.x}-${item.y}-${item.z}.txt' > dvc.yaml
mkdir data
dvc repro --no-commit
time -v dvc commit -f
```
```console
Command being timed: "dvc commit -f"
User time (seconds): 65.71
System time (seconds): 0.87
Percent of CPU this job got: 99%
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:06.69
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): …
```
> commit: batch dump stages, do not re-read on save from the workspace

- dvc/commands/checkout.py
- dvc/commands/data_sync.py
- dvc/exceptions.py
- dvc/repo/checkout.py
- dvc/repo/pull.py
- dvc/testing/remote_tests.py
- dvc/testing/workspace_tests.py
- tests/func/test_checkout.py
- tests/func/test_data_cloud.py
- tests/func/test_run_cache.py
- tests/func/test_virtual_directory.py
Closes #9831.
Note that no. of deleted files are not reported granularly if those files are no longer being tracked by DVC. In that case, they are reported as one single change in the summary.
> checkout/pull: report granular summary of changes

- dvc/repo/diff.py
- tests/func/test_diff.py
Note that this only works when second revision argument is missing, as otherwise we don't really check for missing cache entries.
Closes #7661.
> fix(diff): show in "Not in cache" if dir entry is missing

- dvc/utils/strictyaml.py
- tests/func/utils/test_strict_yaml.py
```console
'../../../../../../../dvc.yaml' validation failed in revision '8da7447'.
expected a dictionary, in stages
```
```console
'./dvc.yaml' validation failed in revision '8da7447'.
expected a dictionary, in stages
```
> fix dvc.yaml filepath in error message when reading from git revisions

- dvc/commands/check_ignore.py
- dvc/ignore.py
- dvc/output.py
- dvc/pathspec_math.py
- tests/func/test_check_ignore.py
- tests/unit/test_ignore.py
~~This does slowdown `walk()` by almost 5x, as we were using union of regexes
before and now we are iterating over all patterns. That also means this
will be slower as the number of patterns increase.~~
EDIT: Changed the implementation to combine regexes for excluded lists.
Notable changes:
- The `check-ignore` command will also show default ignore patterns
(eg: `.dvc` / `.git` / `.hg` ), similar to how `is_ignored()` worked.
- `--all` is now hidden and deprecated, and dvc will stop matching all patterns
after the first match.
Closes #10722.
Closes #10122.
> ignore: simplify and reuse same implementation across check-ignore and is_ignored API

- dvc/commands/init.py
- dvc/repo/init.py
Previously, it could be only initialized in the current working directory.
> feat(cli): support initializing DVC repository in an arbitrary directory

- dvc/repo/data.py
- tests/func/test_data_status.py
Avoid raising errors in `data_status()` when Git HEAD does not contain a DVC repository. Instead, fall back to an empty index.
Tests now cover both unborn and committed Git repos, with and without subdirs.
> fix(data status): handle missing DVC repo at Git HEAD
